### ISSUE TITLE
sphinx-markdown-tables library forces GPL license on LVGL

### ISSUE THREAD

**Issue by ckielstra** [kisvegabor/lvgl#2556]
The lvgl/docs are build using the package sphinx-markdown-tables. The problem with that library is that it's published under the GPL license, a viral license. Meaning that complete LVGL should now also be released under GPL.

I asked the maintainer of sphinx-markdown-tables if he is willing to change the license type. Until then I suggest we remove this package from the requirements.

**Comment by embeddedt** [comment]
I am not a lawyer, but does the GPL extend to a program's output by default? I know GCC has an explicit exception, but I don't know if it's needed in all cases.

I have no objections to changing the library we use if a suitable alternative exists.

**Comment by kisvegabor** [comment]
I'm also not a lawyer (mandatory disclaimer :slightly_smiling_face: ) but with the same logic every program you build using GCC should be GPL licensed. 

So far I thought that we needed to keep GPL only if we used the source code of the software or link it. E.g. if we created `MY-sphinx-markdown-tables`. But correct me if I'm wrong. 

>  I know GCC has an explicit exception, but I don't know if it's needed in all cases.

How do you mean it?

**Comment by embeddedt** [comment]
> > I know GCC has an explicit exception, but I don't know if it's needed in all cases.
> How do you mean it?

https://www.gnu.org/licenses/gcc-exception-3.1

I am not sure if this applies just to libgcc (which is a GPL library that GCC always links with your program), or if it applies to the compiler itself as well.

**Comment by ckielstra** [comment]
I'm not a lawyer person too. 
Perhaps it's no problem since since we only use the output of this library?
I also opened a ticket on the project's github to see if the license can be changed to something less restrictive.

**Comment by embeddedt** [comment]
In any case, this library is only used to produce the documentation PDF and HTML, which are built by the CI system and published on a GitHub repository with public access. Therefore, I don't think we are currently violating any GPL restrictions.

I did do a search for replacements but it seems that everyone links to this library as the recommended one to use. :laughing:

**Comment by kisvegabor** [comment]
As a reference I link the issue opened by @ckielstra 
https://github.com/ryanfox/sphinx-markdown-tables/issues/33

**Comment by puzrin** [comment]
GPL is applied to how do you [distribute] [code].

1. you don't distribute that package code, it's not part of your repo
2. things, processed by code, are not subject of code's licence

=> just close this issue as "not a problem".

**Comment by ckielstra** [comment]
@puzrin Thanks for the explanation.
I agree to close this ticket.
