### ISSUE TITLE
lv_fs_drv_t only one drive letter possible?

### ISSUE THREAD

**Issue by Slluxx** [kisvegabor/lvgl#2557]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
lv_fs_drv_t letter is a char and can hold only one character. The Documentation also states that its **one** uppercase letter. The Nintendo Switch accesses the sdcard via `sdmc:/` and other parts of the system with `romfs:/` and so on. This makes it impossible to load files via a path. 

### To Reproduce
Not easily reproducable. Needs a nintendo switch and its development environment.

### Expected behavior
Instead of one drive letter, allow the usage of a char array / string.

**Comment by kisvegabor** [comment]
The driver letter is only for LVGL. It might look ugly but in your case it looked like e.g. `F:sdmc:/path/to/file.txt`. `F` tells LVGL which `open` function to call and `sdmc:/path/to/file.txt` will be passed to that `open` function.

**Comment by Slluxx** [comment]
Not tested but im sure you are right, so ill close this issue. Thanks!
