### ISSUE TITLE
the italics font Incomplete display

### ISSUE THREAD

**Issue by guoweilkd** [kisvegabor/lvgl#2559]
hi, the italics font Incomplete display.like this:

![image](https://user-images.githubusercontent.com/35251456/133613101-c15debc3-61ba-48fd-8c40-0bd277764ccd.png)

**Comment by kisvegabor** [comment]
Please send the font you have tested with.

**Comment by guoweilkd** [comment]
The italic font above is made using the Freetype driver.
Can I generate italic fonts from `.ttf` use lvgl Font Converter?

**Comment by kisvegabor** [comment]
I mean which ttf font you have used and which size.

**Comment by guoweilkd** [comment]
arial.ttf  size=32, You need this branch https://github.com/guoweilkd/lv_lib_freetype/tree/style

**Comment by guoweilkd** [comment]
We now use lv_font_t->adv_w to calculate the string width,but if italic used , the End-of-line position character should use `ofs_x + box_w`to calculate the character width.

**Comment by kisvegabor** [comment]
I see the issue. Changing the label's width based on the last character could cause unexpected things with word wrap. E.g. due to the extra width LVGL might think a `.` still fits into the line. This way  `.` would be the last character. So it can mess up labels in special cases. 

I think a more proper solution would be to set some `ext_draw_pad` (extra area in which the object draw outside of its coordinates).  The exact required extra size is not know now but we can estimate it e.g.  like `font_height / 4`. However, this value could be saved during font conversation considering all ofs_x, adv_w and box_w.

What do you think?

**Comment by guoweilkd** [comment]
> ext_draw_pad
a good idea. How do I use this interface.

**Comment by guoweilkd** [comment]
a other trouble:freetype maybe malloc memory in lv_font_t->get_glyph_dsc, but in  lv_font_t->get_glyph_bitmap Can't release it(Because the returned bitmap pointer LVGL is used) .like this:
in lv_font_t->get_glyph_dsc:
![image](https://user-images.githubusercontent.com/35251456/134293711-b8119c87-f52d-47e3-be5a-7f9d3740e728.png)

in  lv_font_t->get_glyph_bitmap :

![image](https://user-images.githubusercontent.com/35251456/134301736-1d6e6dee-6d9d-4d51-b47d-0c656cf68fed.png)

FT_Done_Glyph() needs to be called to release resources allocated by FT_Glyph_Copy().

Do you think it's necessary to add a release interface callback?

**Comment by kisvegabor** [comment]
> a good idea. How do I use this interface.

It can be managed internally by the label. But until it's implemented you can add an [LV_EVENT_REFR_EXT_DRAW_SIZE](https://docs.lvgl.io/master/overview/drawing.html#lv-event-refr-ext-draw-size) to the label and call `lv_obj_refresh_ext_draw_size(label);`.

> a other trouble:freetype maybe malloc memory in lv_font_t->get_glyph_dsc, but in lv_font_t->get_glyph_bitmap Can't release it(Because the returned bitmap pointer LVGL is used) .like this:

In the latest version of lv_freetype.c [get_glyph_bitmap_cb_cache](https://github.com/lvgl/lv_lib_freetype/blob/dc26547de741c6a147ad9193d82283337b0f6a79/lv_freetype.c#L251-L261) looks different. Are you using this version?

**Comment by guoweilkd** [comment]
> In the latest version of lv_freetype.c [get_glyph_bitmap_cb_cache](https://github.com/lvgl/lv_lib_freetype/blob/dc26547de741c6a147ad9193d82283337b0f6a79/lv_freetype.c#L251-L261) looks different. Are you using this version?

The Bold code of Font is still experimental, so it is not pushed to the master

**Comment by guoweilkd** [comment]
> Do you think it's necessary to add a release interface callback?

 #2582  also mentions this need

**Comment by guoweilkd** [comment]
> It can be managed internally by the label. But until it's implemented you can add an [LV_EVENT_REFR_EXT_DRAW_SIZE](https://docs.lvgl.io/master/overview/drawing.html#lv-event-refr-ext-draw-size) to the label and call `lv_obj_refresh_ext_draw_size(label);`.

hi, current label does not support ext_draw_size. I submitted a fix  #2587

**Comment by kisvegabor** [comment]
> The Bold code of Font is still experimental, so it is not pushed to the master

Can you create a PR to see your code as a whole?

**Comment by guoweilkd** [comment]
> Can you create a PR to see your code as a whole?
PR has been submitted. [add blod and italics](https://github.com/lvgl/lv_lib_freetype/pull/14). Blod is implemented in a other way, It is working normally now.



> It can be managed internally by the label. But until it's implemented you can add an [LV_EVENT_REFR_EXT_DRAW_SIZE](https://docs.lvgl.io/master/overview/drawing.html#lv-event-refr-ext-draw-size) to the label and call `lv_obj_refresh_ext_draw_size(label);`.

this way is enough for `label`. but for span,Italics may appear in the middle, like this:
![image](https://user-images.githubusercontent.com/35251456/134659748-2b3e7bb9-02c3-4ee1-bb06-b35d7ee01f4e.png)

Maybe we can do like this:
in font->get_glyph_dsc callback end add:
```
    if (dsc->style & FT_FONT_STYLE_ITALIC && unicode_letter_next == '\0') {
        dsc_out->adv_w = dsc_out->box_w + dsc_out->ofs_x;
    }
```

restult:
![image](https://user-images.githubusercontent.com/35251456/134660577-9339693e-8fef-4a13-9f43-4070700a3ebc.png)

**Comment by kisvegabor** [comment]
>     if (dsc->style & FT_FONT_STYLE_ITALIC && unicode_letter_next == '\0') {

Sounds good. Here we only care about word ending to be sure italic doesn't overlap with the next letter.

**Comment by kisvegabor** [comment]
Not stale, I'll add a fix to lvgl.

**Comment by kisvegabor** [comment]
I've pushed a fix
