### ISSUE TITLE
[unit testing] Test runners doesn't include debug information

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#2566]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Currently the test runners doesn't include debug information, so if you get a SEGFAULT while running your test, or simply you want to debug your test, you're forced to add debug information, it would be better if the runners include it, we are not currently testing performance.

See https://github.com/lvgl/lvgl/pull/2551 for more information

### To Reproduce
Load a test runner into gdb, it will tell you there's no debug information.

### Expected behavior
Test runners with debug information.

### Screenshots or video

**Comment by kisvegabor** [comment]
I agree!
