### ISSUE TITLE
btnmatrix assign the hardware digital keys

### ISSUE THREAD

**Issue by a1103688841** [kisvegabor/lvgl#2567]
### Introduce the problem

HI！i want usr btnmatrix assign the hardware digital keys，but btnmarix just have LV_KEY_RIGHT/UP/LEFT/RIGHT and LV_KEY_ENTER event.  How can i use the btn to usr the btnmarix?
![image](https://user-images.githubusercontent.com/44131404/133869943-86d6156b-e867-4b83-b561-8057ad2eb84c.png)

### Examples and cases
   btn assign the keyboard but digital btnmarix i can't usr like this.
```
    /*Register a keypad input device*/
    lv_indev_drv_init(&indev_drv);
    indev_drv.type = LV_INDEV_TYPE_KEYPAD;
    indev_drv.read_cb = keypad_read;
    indev_keypad = lv_indev_drv_register(&indev_drv);
    // static lv_group_t* group;
    lv_group_t* group = lv_group_create();
    lv_group_add_obj(group, menu.b1.btn);
    lv_indev_set_group(indev_keypad, group);
```

**Comment by kisvegabor** [comment]
So your goal is that if the btnmatrix is focused and the user presses the "A" key on his keyboard, the btnmatrix should act as if the "A" key were pressed on the btnmatrix. Is it corrects?
