### ISSUE TITLE
Added configuring external SDRAM

### ISSUE THREAD

**Issue by MaybenYi** [kisvegabor/lvgl#2578]
For STM32 microcontroller with part of small memory, it is hoped to increase the configuration of external SDRAM and store buffer in it, so that there can be space for operation

**Comment by kisvegabor** [comment]
Which buffer do you mean?

**Comment by MaybenYi** [comment]
> Which buffer do you mean?
such as in lv_port_disp_template.c，
The structure lv_color_t  and lv_disp_draw_buf_t  can be saved in an external SDRAM

**Comment by MaybenYi** [comment]
> Which buffer do you mean?

such as in lv_port_disp_template.c，
The structure lv_color_t and lv_disp_draw_buf_t can be saved in an external SDRAM

**Comment by embeddedt** [comment]
I think you can do that already, independently of LVGL's configuration, as those are variables you declare in the code yourself.

**Comment by MaybenYi** [comment]
> I think you can do that already, independently of LVGL's configuration, as those are variables you declare in the code yourself.

that's true，but i think this is an optional solution for small memory devices, for beginners
