### ISSUE TITLE
lv_label_set_text_fmt scientific notation

### ISSUE THREAD

**Issue by abedevelop** [kisvegabor/lvgl#2588]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
lv_label_set_text_fmt not print value when scientific notation format is used. It's print only the "e" char.

### To Reproduce
```c
lv_obj_t *accur_lbl = lv_label_create(cont);
double acc_num = 0.000005241;
lv_label_set_text_fmt(accur_lbl, "ESTIMATED ACCURACY: %e", acc_num);
```

### Expected behavior
Print number in scientific notation like printf function.

**Comment by embeddedt** [comment]
I am not sure if our small printf implementation supports special formats like `%e`. You may want to look into [enabling use of the platform `printf` implementation](https://github.com/lvgl/lvgl/blob/51f3310592b488bf6225a13a7b74291751ea8912/lv_conf_template.h#L234-L240) instead.

**Comment by abedevelop** [comment]
> I am not sure if our small printf implementation supports special formats like `%e`. You may want to look into [enabling use of the platform `printf` implementation](https://github.com/lvgl/lvgl/blob/51f3310592b488bf6225a13a7b74291751ea8912/lv_conf_template.h#L234-L240) instead.

It works by define LV_SPRINTF_CUSTOM
