### ISSUE TITLE
Kconfig not up to date

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#2590]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Kconfig wasn't updated after merging #2484

### To Reproduce
Use the repo as is. Some configuration options introduced by #2484 are not available in the Kconfig

### Expected behavior
New configuration options should be available (when possible) in the Kconfig

### Screenshots or video
NA

I'm planning to only update that options and wait for the resolution of #2555 to continue updating the Kconfig and related files.

**Comment by kisvegabor** [comment]
> I'm planning to only update that options and wait for the resolution of #2555 to continue updating the Kconfig and related files.

Ok, let's fix it first.
