### ISSUE TITLE
when I set the msgbox size, but the image incomplete display.

### ISSUE THREAD

**Issue by Littermonkey** [kisvegabor/lvgl#2592]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

[msgbox] when I set the msgbox size, incomplete display.  
### To Reproduce

	ui->screen = lv_obj_create(NULL);
	static const char * screen_msgbox_1_btns[] = {"Apply","Close",""};
	ui->screen_msgbox_1 = lv_msgbox_create(ui->screen, "hello", "content", screen_msgbox_1_btns, true);
	lv_obj_set_pos(ui->screen_msgbox_1, 120, 72);
	lv_obj_set_size(ui->screen_msgbox_1, 160, 140);

### Expected behavior

When the msgbox becomes smaller, the image can be displayed completely, which is what I expect. 

### Screenshots or video

![msgbox](https://user-images.githubusercontent.com/30677217/134660335-4fe1a401-06bb-4896-9ecd-4d80c2876af8.PNG)

**Comment by kisvegabor** [comment]
I've pushed a fix here: 73e036bba
