### ISSUE TITLE
button in scroll page Released. 

### ISSUE THREAD

**Issue by liuy-Kuder** [kisvegabor/lvgl#2600]
### Describe the bug
lv_demo_widgets.c : The button(log out) is not released when the button slides up or down。

### To Reproduce
1、
in lvgl/src/core/lv_indev.c line: 872 fixed
   if(proc->types.pointer.scroll_obj == NULL)//in scrolling released active object
       lv_event_send(indev_obj_act, LV_EVENT_PRESSING, indev_act);
   else
       lv_event_send(indev_obj_act, LV_EVENT_RELEASED, indev_act);
2、
in lvgl/src/widgets/lv_btn.c fixed
static void lv_btn_constructor(const lv_obj_class_t * class_p, lv_obj_t * obj)
{
    LV_UNUSED(class_p);
    LV_TRACE_OBJ_CREATE("begin");
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_PRESS_LOCK); //clear press lock
    LV_TRACE_OBJ_CREATE("finished");
}

### Expected behavior
After the change, the button slide will release, but also affects the release effects of other controls.

https://user-images.githubusercontent.com/50260583/134762935-03a2f6d3-ab59-4406-8335-ee39f5299d3a.mp4

**Comment by kisvegabor** [comment]
Why is it a problem if it is kept pressed during slide?

**Comment by liuy-Kuder** [comment]
> Why is it a problem if it is kept pressed during slide?

For example, I will add button release event and add handlers (such as jump page), in the sliding page similar to the mobile phone APP icon, slide the page will inevitably press the APP button slide, slide finger release may cause APP button trigger release event, causing the page to jump, but I do not want to jump, just want to slide the page.

**Comment by kisvegabor** [comment]
You can use `LV_EVENT_CLICKED`. It isn't sent if there was scrolling. 

IMO `LV_EVENT_RELEASED` is useful this way, as the object was really released.
