### ISSUE TITLE
Tree widget

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#2606]
Does LVGL have plans to add a tree widget, eg `lv_tree`?

![image](https://user-images.githubusercontent.com/56565368/134902061-db5fee70-2e03-41fb-ad33-21f43f7e1cfc.png)

**Comment by kisvegabor** [comment]
Not on the roadmap, but really would be great.

Please open a topic for it in the feature request category in the forum:
https://forum.lvgl.io/c/feature-request/9

**Comment by Miguel0101** [comment]
I closed the issue because I opened a feature request on the LVGL forum.
https://forum.lvgl.io/t/tree-widget-feature-request/6916
