### ISSUE TITLE
gap for table

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [kisvegabor/lvgl#2612]
<img width="265" alt="table_gap" src="https://user-images.githubusercontent.com/22284222/135017823-528edda6-cbe5-4e61-92b8-490f66822899.PNG">

I find a table issue, when set border_width to larger than 6 for LV_PART_MAIN.
there will be a gap in right side and bottom side

**Comment by kisvegabor** [comment]
Thanks, I've pused a fix.
