### ISSUE TITLE
v8.0 add encoder group cause esp32-s2 reboot

### ISSUE THREAD

**Issue by shuiyihang** [kisvegabor/lvgl#2613]
hey,I use lvgl release/v8.0 as a component in esp-idf, and add an encoder driver to main, but as long as the following line is added, my esp32-s2 will always restart, and the error is reported as follows, I am really Don't know what happened to him

```c
    lv_group_t *g = lv_group_create();

    lv_indev_drv_init(&indev_drv);
    indev_drv.type = LV_INDEV_TYPE_ENCODER;
    indev_drv.read_cb = encoder_read;
    lv_indev_t *enc_indev = lv_indev_drv_register(&indev_drv);

    lv_group_add_obj(g,roller1);

    lv_indev_set_group(enc_indev, g);
```

![1](https://user-images.githubusercontent.com/43931349/135094298-daddcca6-e022-4e9d-9bd7-1219bf617cb3.png)
![2](https://user-images.githubusercontent.com/43931349/135094332-d01346f0-5133-4dc6-854b-19073e6868a9.png)

**Comment by shuiyihang** [comment]
When I used lvgl7, everything was normal, but now, after changing some local variables to static, the controls can finally be displayed normally, but as long as the encoder driver is added, problems will occur

**Comment by kisvegabor** [comment]
Note that, `lv_indev_drv_t` (and other drivers too) needs to be static in v8.

**Comment by shuiyihang** [comment]
en....,i think ,this reason ,i had attempt。I still fall back to release/v7。hhh

**Comment by shuiyihang** [comment]
the problems seems occur at lv_label.c 269 line,I may not look at it completely, but I feel that this type of forced conversion is more dangerous，may be text is null

**Comment by shuiyihang** [comment]
![Snipaste_2021-09-29_20-46-40](https://user-images.githubusercontent.com/43931349/135271522-4dad8b04-cf70-48db-b3d4-3549e551cb77.png)
![Snipaste_2021-09-29_20-48-17](https://user-images.githubusercontent.com/43931349/135271537-bc3420da-2d9f-4582-b6cd-887ccd069d62.png)

**Comment by kisvegabor** [comment]
If you pass valid object to `lv_label_get_text()` it should work.

Does it work with if you create only a single button?

**Comment by shuiyihang** [comment]
solve it tomorrow

**Comment by shuiyihang** [comment]
When I open the log of lvgl and set print the log with'printf' y. Select trace-detailed information, this problem will also appear in lvgl7. When I turn off the log and use lvgl8, it is now normal. It may not be the problem of lvgl,
In short, it's amazing~

**Comment by shuiyihang** [comment]
I closed the question
