### ISSUE TITLE
the return value of _lv_txt_get_next_line()  > strlen(txt)

### ISSUE THREAD

**Issue by guoweilkd** [kisvegabor/lvgl#2615]
in [_lv_txt_get_next_line()](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_txt.c#L338-L340)
the return value exceeds the length of the string If the argument `txt = ""`, Is the return value expected?

### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by kisvegabor** [comment]
True, it's really incorrect. 

I've pushed a fix.
