### ISSUE TITLE
Text background OPA also applied to text color

### ISSUE THREAD

**Issue by gesture1968** [kisvegabor/lvgl#2620]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

In a spinbox I want the background of the cursor (selected digit) to be transparent, and the cursor text to have a different color from the non-selected digits. To do so, I setup a style for the cursor with a different text_color and the bg_opa to be transparent. After adding the style to the cursor, the background is indeed transparent, but the text color is also transparent and has the same color as the other digits. It seems that the bg_opa background transparency is also applied to the text color (as if the text_opa is set to the bg_opa), what should not be the case as background and text color are two different 'objects'.

### To Reproduce

```c
  /* the spinbox style */
  static lv_style_t spinbox_style;
  lv_style_init(&spinbox_style);
  lv_style_set_text_color(&spinbox_style, LV_COLOR_MAKE(0x70, 0xff, 0x70));
  lv_style_set_opa(&spinbox_style, LV_OPA_COVER);
  lv_style_set_bg_color(&spinbox_style, lv_color_black());
  lv_style_set_pad_all(&spinbox_style, 10);
  lv_style_set_pad_left(&spinbox_style, 3);
  lv_style_set_pad_bottom(&spinbox_style, 0);
  lv_style_set_radius(&spinbox_style, 8);

  /* the selected digit cursor style  */
  static lv_style_t cursor_style;
  lv_style_init(&cursor_style);
  lv_style_set_text_color(&cursor_style, LV_COLOR_MAKE(0x0A, 0x5f, 0x0A));
  lv_style_set_bg_opa(&cursor_style, LV_OPA_TRANSP);
  lv_style_set_anim_time(&cursor_style, 500);

  /* the volt spinbox */
  static lv_obj_t * voltSB;
  voltSB = lv_spinbox_create(lv_scr_act());
  lv_spinbox_set_range(voltSB, 0, 2000);
  lv_spinbox_set_digit_format(voltSB, 4, 2);
  lv_spinbox_set_value(voltSB, 1000);
  lv_obj_add_style(voltSB, &spinbox_style, 0);
  lv_obj_add_style(voltSB, &cursor_style, LV_PART_CURSOR);
  lv_obj_set_size(voltSB, 135, 56);
  lv_obj_set_pos(voltSB, 6, 28);
```

### Expected behavior

The background of the cursor (selected digit) is transparent, and the textcolor is a darker shade of green while the not-selected digitS are a lighter shade of green

**Comment by kisvegabor** [comment]
Thanks, fixed :slightly_smiling_face:
