### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#2622]
If I were to create a window and add resizing, what would the resizing formula?

**Comment by kisvegabor** [comment]
You can set the new hor/ver_res in the display driver can call `lv_disp_drv_update()`.

If you have further questions please open a topic in the Forum.

**Comment by Miguel0101** [comment]
> You can set the new hor/ver_res in the display driver can call `lv_disp_drv_update()`.
> 
> If you have further questions please open a topic in the Forum.

I'm talking about resizing `lv_window`.
https://forum.lvgl.io/t/lv-window-resize/6934

cc @kisvegabor
