### ISSUE TITLE
lv_obj_set_event_cb does not exist (anymore)

### ISSUE THREAD

**Issue by gesture1968** [kisvegabor/lvgl#2626]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

In the documentation, in the Event section it is mentioned (with example) that you can use the **lv_obj_set_event_cb** to hook events on an object. This function does not exist in the code, and is probably replaced by the **lv_obj_add_event_cb** function

### To Reproduce

Just follow the example on page https://docs.lvgl.io/latest/en/html/overview/event.html#generic-events

### Expected behavior

documentation is updated with all things related to the new function

**Comment by embeddedt** [comment]
Those are v7 docs, you're probably looking for https://docs.lvgl.io/8/overview/event.html.

("latest" in the URL is pointing to v7 to prevent breaking old links.)

**Comment by kisvegabor** [comment]
As the issue seems to be solved I close it.

If it's still not working please reopen the issue and comment here.
