### ISSUE TITLE
Remove selection outline on a focused group object

### ISSUE THREAD

**Issue by gesture1968** [kisvegabor/lvgl#2627]
### Introduce the problem

When a group object is focused, a blue outline is shown around the focused object. I would like to remove (make it invisible) this outline as it does not make for good visual in my project. Since a group has no styling, and any object function I tried did not remove the outline, I don't seem to have an option to do so.

### Examples and cases

Any example using an object that can be focused in a group

### Suggested solution

Some styling option to remove/color or make the outline transparent

**Comment by kisvegabor** [comment]
The default theme adds the style with outline to `LV_STATE_FOCUS_KEY`. 
You can remove it with `lv_obj_remove_style(btn1, NULL, LV_STATE_FOCUS_KEY);`
