### ISSUE TITLE
texas instrument board tm4c1294  display communication with lvgl library reference code

### ISSUE THREAD

**Issue by kkkkkkkkkkkkkkkkkkkkkkkkkkk** [kisvegabor/lvgl#2630]
texas instrument board tm4c1294  display communication with lvgl library reference code. I need in that communication help I haven't any reference to communication with this board so, please send to reference code for that controller with lvgl in code composer studio.
currently, I am using grlib.h library is working fine but in some issues in image data generated by gimp software that software only produces only 255    8 -bit colors only but in my image is more than 255 colors so the extra color is not produced by pnmtoc.exe which is provided by gimp. 
if any solution on the gimp side? in that image, the index is only 255 I need more than 255 and convert in c array.(my main task)

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
