### ISSUE TITLE
V8.XX(master). The built-in font with UTF-8 characters does not display UTF-8 characters by default. Bug or feature?

### ISSUE THREAD

**Issue by SinglWolf** [kisvegabor/lvgl#2638]
I am migrating my project from version 7 to the current one.
Stuck with UТF-8 characters not showing in embedded font. Naturally, the UТF-8 symbols have been re-added with lv_font_conv for version 8 again.
Only ASCII characters were displayed.
In one example, I found line 
```c
lv_obj_set_style_text_font(lmy_label, &lv_font_montserrat_16, 0);
```
and decided to apply it in my project.
UТF-8 symbols appeared on the screen.
Do I now have to apply this for every object? After all, in version 7 this was not.

**Comment by kisvegabor** [comment]
Please send a short code snippet to reproduce the issue.

**Comment by SinglWolf** [comment]
> Please send a short code snippet to reproduce the issue.

I would love to, but I don't understand English well.
In my project on version 7, the Russian font was displayed without  font declaration. Why is it necessary to declare forcibly on version 8?
Is that clearer? Sorry.

**Comment by kisvegabor** [comment]
Hm, there was no Russian font by default in v7 either. I'm sure that you have added it somewhere manually in v7 too.

**Comment by SinglWolf** [comment]
I say it again. I have implemented UTF-8 symbols (Russian font, symbols of European languages, my own icons) into the built-in montserrat_16 font using the lv_font_conv script and in version 7 I did not declare anything. Everything was displayed correctly. Why in version 8 the symbols of UTF-8 (Russian font, symbols of European languages, their own icons) are displayed only after a forced declaration?
I hope it's clear now?

**Comment by embeddedt** [comment]
You had to have replaced the built-in font in v7, then, and you would need to do the same thing again in v8. As far as I know our built-in Montserrat font doesn't have those symbols by default.

**Comment by kisvegabor** [comment]
Probably you set `LV_THEME_DEFAULT_FONT_NORMAL` to your font. In v8 `LV_FONT_DEFAULT` has similar purpose.

**Comment by SinglWolf** [comment]
> You had to have replaced the built-in font in v7, then, and you would need to do the same thing again in v8. As far as I know our built-in Montserrat font doesn't have those symbols by default.

Of course I did it, I'm not that stupid!


> Probably you set `LV_THEME_DEFAULT_FONT_NORMAL` to your font. In v8 `LV_FONT_DEFAULT` has similar purpose.

I haven't changed anything in the settings. I will look again.

**Comment by embeddedt** [comment]
Sorry; that wasn't what I was trying to convey, I was just trying to understand what you've tried so far and what the state of your v7 project is.

**Comment by SinglWolf** [comment]
> Sorry; that wasn't what I was trying to convey, I was just trying to understand what you've tried so far and what the state of your v7 project is.

On version 7, everything worked fine for me, only at the edges of the objects there were incomprehensible artifacts in the form of intermittent vertical lines consisting of single pixels. I guess this is because of the display driver.

**Comment by SinglWolf** [comment]
In version 7 of my project, I didn't change anything in the font settings other than choosing the built-in Montserrat 16 font, which I added my UTF-8 characters to. And everything was displayed perfectly.
After upgrading to version 8, everything broke. The font settings are the same. The built-in Montserrat 16 font added UTF-8 characters again.
The display doesn't show UTF-8 characters as if I didn't add them.
If I change the code in the file `lvgl\src\lv_conf_internal.h` from
```c
/*Always set a default font*/
#ifndef LV_FONT_DEFAULT
#  ifdef CONFIG_LV_FONT_DEFAULT
#    define LV_FONT_DEFAULT CONFIG_LV_FONT_DEFAULT
#  else
#    define LV_FONT_DEFAULT &lv_font_montserrat_14
#  endif
#endif
```
to
```c
/*Always set a default font*/
#ifndef LV_FONT_DEFAULT
#  ifdef CONFIG_LV_FONT_DEFAULT
#    define LV_FONT_DEFAULT CONFIG_LV_FONT_DEFAULT
#  else
#    define LV_FONT_DEFAULT &lv_font_montserrat_16
#  endif
#endif
```
everything will display fine.
What am I doing wrong?
![2021-10-13_06-02-35](https://user-images.githubusercontent.com/32172969/137049412-1785425c-42cc-433a-8b05-0f05c1d993f1.png)
And why is line 986 inactive?

> Probably you set `LV_THEME_DEFAULT_FONT_NORMAL` to your font. In v8 `LV_FONT_DEFAULT` has similar purpose.

I did not find anything like `LV_THEME_DEFAULT_FONT_NORMAL` in the settings.
![2021-10-13_06-11-57](https://user-images.githubusercontent.com/32172969/137049903-d459947a-8385-417c-be84-abeea05adfda.png)

**Comment by kisvegabor** [comment]
As we mentioned you need to set `LV_FONT_DEFAULT` too.

**Comment by SinglWolf** [comment]
> As we mentioned you need to set `LV_FONT_DEFAULT` too.

I'm probably so dumb or blind from old age that I can not find where it is setting. Poke my face in this, please.
![2021-10-19_16-48-08](https://user-images.githubusercontent.com/32172969/137903290-f17ae6d6-b5ee-4777-9f29-bb4df4d52ba7.png)

**Comment by kisvegabor** [comment]
Our current [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig#L440) has no 
`CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_16` only 
`CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16`.

Seemingly these configs are still coming from v7.

**Comment by SinglWolf** [comment]
> As we mentioned you need to set `LV_FONT_DEFAULT` too.
> Our current [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig#L440) has no

So I have to do something that You don't have yet?
Is this subtle trolling?

**Comment by kisvegabor** [comment]
I don't understand. You need to simply select `CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16` but for some reason your Kconfig settings don't contain it. 

Just as an experiment what if you remove `defconfig` and generate it again with `menuconfig`

**Comment by SinglWolf** [comment]
> Just as an experiment what if you remove `defconfig` and generate it again with `menuconfig`

A very useful experiment!
Can you imagine how much I then need to remember the necessary settings for the entire project?
But thanks anyway.

**Comment by kisvegabor** [comment]
How Kconfig and menuconfig updates the old, deprecated configs is out of our control. 

All we can do is providing an up to date Kconfig file. And apparently we did it, as the new configs are really there in our Kconfig file.

**Comment by SinglWolf** [comment]
> How Kconfig and menuconfig updates the old, deprecated configs is out of our control.
> 
> All we can do is providing an up to date Kconfig file. And apparently we did it, as the new configs are really there in our Kconfig file.

Do You have any mention somewhere that before upgrading to version 8.XX, we need to remove the settings section `LVGL configuration` from `sdkconfig`?

**Comment by SinglWolf** [comment]
Deleted a section `LVGL configuration`. Launched the `menuconfig`  again. Builded a project. Everything remained the same. Waste of time.

**Comment by kisvegabor** [comment]
You should check from where `LV_FONT_DEFAULT_NORMAL_MONTSERRAT_16` is coming from. Certainly not from the current Kconfig file.

**Comment by SinglWolf** [comment]
> You should check from where `LV_FONT_DEFAULT_NORMAL_MONTSERRAT_16` is coming from. Certainly not from the current Kconfig file.

I no longer have this argument.
![2021-10-19_18-32-41](https://user-images.githubusercontent.com/32172969/137920364-d7f665a9-04a0-4cd6-96e3-4c1d3192bcfb.png)

It's easier for me to assign a default font for each object than to feel flawed here, with crooked hands and a dull head.

**Comment by kisvegabor** [comment]
It's enough to assign it to the screen as the font is inherited.

**Comment by SinglWolf** [comment]
> It's enough to assign it to the screen as the font is inherited.

And the fact that this does not work through `menuconfig`, as it was in version 7.XX, do you not care? Fine! Just some kind of holiday! Now the desire to help you in something has diminished by an order of magnitude. Keep it up!
I'm tired of proving that the error exists.
You can close the issue.

**Comment by kisvegabor** [comment]
Again, we can't do anything with how menucofig works. Updating a major version is always complicated.

---

@embeddedt and I already commented about the wording of your comments should be more respectful. We try our best to help but can't solve every issue of every developer.

I need to warn you, if you can't lower the offensive connotation of your comments, I won't have other choice than blocking you in order to keep the welcoming atmosphere of LVGL's community.

Please take a closer look especially at the first section of our Code of conduct: https://github.com/lvgl/lvgl/blob/master/docs/CODE_OF_CONDUCT.md#our-standards

**Comment by SinglWolf** [comment]
At first they tell me that everything is bad for me, I myself did not set up something there and the like, ignoring the fact that I described everything in detail.
Then they discuss something with each other, they say, he (that is, I) must choose something there, and he (that is, I) chose another and is dissatisfied with something else. This is similar to how doctors discuss a seriously ill person.
This is a good tone to encourage friendly conversation. Instead, for some reason I start to get angry, despite the invaluable help of the developers, and start talking in a bad, just offensive tone.
Of course! It is easier for you to get rid of me than to admit, and even more so - to look for a mistake. I am a wicked, rude and uncouth fool. Block. I do not care.
