### ISSUE TITLE
Can we use lvgl's own example in arduino?

### ISSUE THREAD

**Issue by xianshiqi1111** [kisvegabor/lvgl#2658]
I cannot use lv_example_btn_1 () in arduino，err：fatal error: lv_examples.h: No such file or directory
I moved the example folder to libraries ，err：arduino undefined reference to lv_example_btn_1()

**Comment by kisvegabor** [comment]
Arudino makes only the files from the `src` folder. We was thinking about adding the examples to the src folder but it's not that reasonable. As `src` should have only the source files of the library.

I suggest manually copying the content of the examples into your ino file.

**Comment by xianshiqi1111** [comment]
OK，Thanks for reply
