### ISSUE TITLE
LVGL + Python + Android + iOS + Web / Mobile Development / React Native and Qt alternative.

### ISSUE THREAD

**Issue by cederom** [kisvegabor/lvgl#2664]
### Introduce the problem
Is it possible to use LVGL as Mobile Development Framework? It would be so much better than React Native and really multiplatform i.e. desktop applications would be possible too as Qt replacement!!

### Examples and cases
I can see SDL is used. I can see OpenGL is used. FLTK uses SDL for experimental mobile development. LVGL could be Holly Grail and missing Fifth Element in real multi platform development if it could be used also for Mobile Development.

### Suggested solution
Please consider LVGL also for Android, iOS and Web development. Mobile first. That could be real Qt alternative, even FLTK. Did anyone tried that already? Would that be possible? :-)

**Comment by kisvegabor** [comment]
I haven't tried it yet, but it's super exciting.

It doable possible with [Android NDK](https://stackoverflow.com/questions/12214090/how-to-build-apk-in-android-for-java-and-native-c-c-code)

Please keep us updated, if you make any progress :slightly_smiling_face: 

---

BTW, it's unbelievable that LVGL reached a level on which people say *"It would be so much better than React Native "* and *"possible too as Qt replacement"*. Kudos to all contributors! :clap: :rocket:

**Comment by sukesh-ak** [comment]
> 

Here it is
https://blog.csdn.net/jayyuz/article/details/123842040

**Comment by cederom** [comment]
So far I am using Python + Kivy (as described in https://github.com/rreilink/pylvgl/issues/14). Will come back to LVGL when embedded project jumps in :-)

**Comment by sukesh-ak** [comment]
> So far I am using Python + Kivy (as described in [rreilink/pylvgl#14](https://github.com/rreilink/pylvgl/issues/14)). Will come back to LVGL when embedded project jumps in :-)

The above link is for LVGL on Android
