### ISSUE TITLE
When the background of the cavas is transparent, lv_canvas_set_px() unnormally.

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#2665]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When the background of the cavas is transparent, lv_canvas_set_px() unnormally.

### To Reproduce

```c
static void test(void)
{
    lv_obj_t* canvas = lv_canvas_create(lv_scr_act());
    lv_obj_set_style_bg_color(lv_scr_act(), lv_color_black(), 0);
    void* buf = lv_mem_alloc(CANVAS_WIDTH * CANVAS_HEIGHT * 4);
    lv_memset_00(buf, CANVAS_WIDTH * CANVAS_HEIGHT * 4);
    lv_obj_center(canvas);
    lv_canvas_set_buffer(canvas, buf, CANVAS_WIDTH, CANVAS_HEIGHT,
                         LV_IMG_CF_TRUE_COLOR_ALPHA);
    lv_canvas_fill_bg(canvas, lv_color_hex(0xff0000), LV_OPA_0);
    uint32_t x;
    uint32_t y;
    lv_color_t color = lv_color_hex(0x00ff00);
    for (y = 10; y < 30; y++) {
        for (x = 5; x < 20; x++) {
            lv_canvas_set_px(canvas, x, y, color);
        }
    }
}
```

### Expected behavior

![image](https://user-images.githubusercontent.com/51692568/137296593-1e81a6e3-a6fe-4fe2-ab92-dc3ef72f3286.png)

![image](https://user-images.githubusercontent.com/51692568/137296190-a193df01-4af5-4e49-9d40-4cc1f902dddb.png)

### Screenshots or video

Can't fill color
![image](https://user-images.githubusercontent.com/51692568/137296244-727a916e-9b91-4251-9166-2fe092064ba9.png)

**Comment by kisvegabor** [comment]
Hi,

`lv_canvas_set_px_opa` was missing from the API of the canvas widget. I added it, and you can use it together with `lv_canvas_set_px_color`.
