### ISSUE TITLE
Remove the stale branch

### ISSUE THREAD

**Issue by xiaoxiang781216** [kisvegabor/lvgl#2681]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The follow branches ether finish or stop the development, so should be removed to avoid the confusion:
```
  remotes/official/XuNeo-master
  remotes/official/ci/discarded-qualifiers
  remotes/official/feat/direct-mode
  remotes/official/feat/new-fs-api
  remotes/official/feat/new-rect-draw
  remotes/official/feat/private-struct
  remotes/official/feat/test-unity
  remotes/official/monorepo
```

**Comment by kisvegabor** [comment]
I've removed most of them. 
@embeddedt  Is `ci/discarded-qualifiers` still required?

**Comment by xiaoxiang781216** [comment]
Thanks.

**Comment by embeddedt** [comment]
No, we can delete it for now. I couldn't get the CI to actually produce those warnings even with the option on, so I'll need to dig deeper. It's unlikely I will have time for that in the next week or two.

**Comment by kisvegabor** [comment]
Okay, I deleted it.
