### ISSUE TITLE
Kconfig CONFIG_LV_COLOR_CHROMA_KEY_HEX is different from CONFIG_LV_COLOR_CHROMA_KEY in internal config

### ISSUE THREAD

**Issue by steprun** [kisvegabor/lvgl#2683]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### A clear and concise description of what the bug is
Kconfig CONFIG_LV_COLOR_CHROMA_KEY_HEX is different from CONFIG_LV_COLOR_CHROMA_KEY in internal config

### To Reproduce
in file Kconfig and lv_internal_config.h

### Expected behavior
Change one of name in these file

**Comment by xiaoxiang781216** [comment]
> ### A clear and concise description of what the bug is
> Kconfig CONFIG_LV_COLOR_CHROMA_KEY_HEX is different from CONFIG_LV_COLOR_CHROMA_KEY in internal config
>
It's because we can't express lv_color_hex(xx) in Kconfig:
```
#define LV_COLOR_CHROMA_KEY lv_color_hex(0x00ff00)         /*pure green*/
```
Please look at this how to convert CONFIG_LV_COLOR_CHROMA_KEY_HEX to CONFIG_LV_COLOR_CHROMA_KEY:
https://github.com/lvgl/lvgl/blob/master/src/lv_conf_kconfig.h#L29-L31

BTW, please close this and https://github.com/lvgl/lvgl/issues/2678, if the answer resolve your concern.

**Comment by steprun** [comment]
But if use menuconfig, it produce this entry named CONFIG_LV_COLOR_CHROMA_KEY_HEX

I modified code like this
```C
/*Images pixels with this color will not be drawn if they are chroma keyed)*/
#ifndef LV_COLOR_CHROMA_KEY
#  ifdef CONFIG_LV_COLOR_CHROMA_KEY_HEX
#    define LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)
#  else
#    define LV_COLOR_CHROMA_KEY lv_color_hex(0x00ff00)         /*pure green*/
#  endif
#endif
```

**Comment by xiaoxiang781216** [comment]
1. https://github.com/lvgl/lvgl/blob/master/Kconfig#L51-L56 define CONFIG_LV_COLOR_CHROMA_KEY_HEX to 0x????????
```
        config LV_COLOR_CHROMA_KEY_HEX
            hex "Images pixels with this color will not be drawn (if they are chroma keyed)."
            range 0x000000 0xFFFFFF
            default 0x00FF00
            help
                See misc/lv_color.h for some color values examples.
```
2. https://github.com/lvgl/lvgl/blob/master/src/lv_conf_kconfig.h#L29-L31 define CONFIG_LV_COLOR_CHROMA_KEY to lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX):
```
#ifdef CONFIG_LV_COLOR_CHROMA_KEY_HEX
#  define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)
#endif
```
3. https://github.com/lvgl/lvgl/blob/master/src/lv_conf_internal.h#L85-L92 define LV_COLOR_CHROMA_KEY to CONFIG_LV_COLOR_CHROMA_KEY:
```
/*Images pixels with this color will not be drawn if they are chroma keyed)*/
#ifndef LV_COLOR_CHROMA_KEY
#  ifdef CONFIG_LV_COLOR_CHROMA_KEY
#    define LV_COLOR_CHROMA_KEY CONFIG_LV_COLOR_CHROMA_KEY
#  else
#    define LV_COLOR_CHROMA_KEY lv_color_hex(0x00ff00)         /*pure green*/
#  endif
#endif
```
I don't see any problem in these steps.

**Comment by steprun** [comment]
```
#ifdef CONFIG_LV_COLOR_CHROMA_KEY_HEX
#  define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)
#endif
```

But kconfig scripts can't produce this line
 define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)

**Comment by xiaoxiang781216** [comment]
> ```
> #ifdef CONFIG_LV_COLOR_CHROMA_KEY_HEX
> #  define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)
> #endif
> ```
> 
> But kconfig scripts can't produce this line define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)

That's why option in Kconfig is CONFIG_LV_COLOR_CHROMA_KEY_HEX, not CONFIG_LV_COLOR_CHROMA_KEY.
CONFIG_LV_COLOR_CHROMA_KEY is defined by lv_conf_kconfig.h which is included by lv_conf_internal.h:
https://github.com/lvgl/lvgl/blob/master/src/lv_conf_internal.h#L14-L19

**Comment by steprun** [comment]
Sorry, I think if use kconfig scrpits, Must define LV_CONF_KCONFIG_EXTERNAL_INCLUDE in compile scripts.
