### ISSUE TITLE
Un-expect background blending

### ISSUE THREAD

**Issue by steprun** [kisvegabor/lvgl#2684]
### Introduce the problem
Set lv_slider and another object background color when CONFIG_LV_COLOR_SCREEN_TRANSP==1, but there is different backgroud blending.

### Examples and cases
```C
lv_color_t key_color;
key_color.full = 0xAF00FF00;
lv_obj_set_style_bg_color(lv_disp_get_scr_act(lvdisp), key_color, LV_PART_MAIN);
__hi_disp_set_colorkey(hidisp, lv_color_chroma_key().full, true);

lv_color_t color;
static lv_style_t style;
lv_style_init(&style);

ui_win_prev_pitch_indicator = lv_slider_create(lv_scr_act());

lv_obj_set_size(ui_win_prev_pitch_indicator, 25, 300);
lv_slider_set_mode(ui_win_prev_pitch_indicator, LV_SLIDER_MODE_SYMMETRICAL);
lv_slider_set_range(ui_win_prev_pitch_indicator, -50, 50);
lv_obj_center(ui_win_prev_pitch_indicator);
lv_obj_align(ui_win_prev_pitch_indicator, LV_ALIGN_RIGHT_MID, -10, 0);

lv_obj_remove_style(ui_win_prev_pitch_indicator, NULL, LV_PART_KNOB);

color.full = 0x19000001;
lv_style_set_bg_color(&style, color);
lv_obj_add_style(ui_win_prev_pitch_indicator, &style, LV_PART_MAIN);

static lv_style_t style_picth_txt_win;
lv_style_init(&style_picth_txt_win);
lv_obj_t *pitch_txt_win = lv_obj_create(lv_scr_act());

lv_obj_set_size(pitch_txt_win, 160, 60);
lv_obj_align(pitch_txt_win, LV_ALIGN_BOTTOM_RIGHT, 0, -130);

//lv_style_set_bg_img_opa(&style_picth_txt_win, LV_OPA_TRANSP);
//lv_style_set_border_opa(&style_picth_txt_win, LV_OPA_TRANSP);
//lv_style_set_shadow_opa(&style_picth_txt_win, LV_OPA_TRANSP);
color.full = 0x19000001;
lv_style_set_bg_color(&style_picth_txt_win, color);
lv_obj_add_style(pitch_txt_win, &style_picth_txt_win, LV_PART_MAIN);
```

###

https://user-images.githubusercontent.com/8555048/137661628-dad9f686-f059-4ba9-b9e5-1cdfaac6d9bf.mp4

 Suggested solution

**Comment by kisvegabor** [comment]
What would be the expected result? 

> color.full = 0x19000001;

Instead of this use: `lv_color_t color = lv_color_hex(0x123456);` and control the opacity with the `bg_opa` style property.

**Comment by steprun** [comment]
If LV_COLOR_CHROMA_KEY is set to Green,  I think the bar should not blend with green, but it looks like a green one.

**Comment by kisvegabor** [comment]
`LV_COLOR_CHROMA_KEY` affects only images. See the comment in `lv_conf.h`
```c
/*Images pixels with this color will not be drawn if they are  chroma keyed)*/
#define LV_COLOR_CHROMA_KEY    lv_color_hex(0x00ff00)         /*pure green*/
```

**Comment by steprun** [comment]
> `LV_COLOR_CHROMA_KEY` affects only images. See the comment in `lv_conf.h`
> 
> ```c
> /*Images pixels with this color will not be drawn if they are  chroma keyed)*/
> #define LV_COLOR_CHROMA_KEY    lv_color_hex(0x00ff00)         /*pure green*/
> ```

Display unit have 2 hardware layer video layer and gui. There is hard color key on Gui layer. The color of hard color key will not be displayed. 

How to set that  I in my application. The widget backgroud need transparency e.g. 50% opa to video.

**Comment by steprun** [comment]
I realize the effect by seting widget bg color is 32bit with alpha, bg opa is cover.

**Comment by steprun** [comment]
Scr obj and desktop obj 's color are set to chroma key and opa to 0, It works. Thanks

**Comment by kisvegabor** [comment]
bg_opa=0 on the screen should be enough. Be sure to enable `LV_COLOR_SCREEN_TRANSP` because in this case, LVGL needs to apply more complex calculations.
