### ISSUE TITLE
Can not set table cell vertical padding

### ISSUE THREAD

**Issue by zirobin** [kisvegabor/lvgl#2686]
### Description
These 2 functions is invalid to set the table cell padding:
lv_obj_set_style_pad_top(table, 0, LV_PART_ITEMS|LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(table, 0, LV_PART_ITEMS|LV_STATE_DEFAULT);

### ScreenShot
![20211018143258](https://user-images.githubusercontent.com/41822892/137680577-afd25e49-2136-476d-a200-1e4d6cdc647b.jpg)

**Comment by kisvegabor** [comment]
It's working for me. Do you use the latest version of LVGL?

**Comment by zirobin** [comment]
After updating to the lastet version, it work find.

**Comment by kisvegabor** [comment]
Great, thanks for the feedback.
