### ISSUE TITLE
Please optimize the directory structure of lvgl / SRC / extra in V8. It's really troublesome to add source files in IDE

### ISSUE THREAD

**Issue by LuWeiHuan** [kisvegabor/lvgl#2688]
MDK keil IDE is too troublesome to add the source file in lvgl/SRC/extra. It is not convenient for ied to add source files. Because keil can't search and add source files. Please optimize it. Thank you

**Comment by kisvegabor** [comment]
> MDK keil IDE is too troublesome to add the source file in lvgl/SRC/extra

I don't understand. You don't have to add files *into* the lvgl folder.

**Comment by LuWeiHuan** [comment]
> > MDK keil IDE is too troublesome to add the source file in lvgl/SRC/extra
> 
> I don't understand. You don't have to add files _into_ the lvgl folder.

Add the source files in the [extra] folder to the MDK ide. The distribution of files in the current [extra] folder structure makes it too cumbersome for the MDK ide to add the source files in the [extra] folder one by one. Because they are not applied to the functions in the [extra] folder in many places, they need to be added

**Comment by kisvegabor** [comment]
So a flat structure would be better where there is only one level of directories in the src folder?

**Comment by LuWeiHuan** [comment]
> So a flat structure would be better where there is only one level of directories in the src folder?

The main reason is that V7 is upgraded to V8. The program card is located in the [lv_uu task handler]. There are no obvious exceptions in the log. I often encounter scattered source files in the [extra] folder to add V8. Finally, there is a problem with the display driver. I'm a little broken. Sorry, it's not necessary
