### ISSUE TITLE
Chart widget rendering issues

### ISSUE THREAD

**Issue by tdjastrzebski** [kisvegabor/lvgl#2697]
Probably I have identified some issues with **chart** widget.
1. Y axis labels are not rendered despite sufficient space reserved (100);
1. X label is clipped at the axis end
1. Chart does not fill in the entire screen area (5" 800x480)
1. In the lower-right corner offset between grid line and tick mark is clearly visible, probably caused by a different rounding

I went through **chart** widget source code but I am not sure where the problem is. One suspicious fragment I found in [lv_chart.c](https://github.com/lvgl/lvgl/blob/master/src/extra/widgets/chart/lv_chart.c) sets `ext_draw_size` based on the largest label size, regardless of it is X or Y axis. This does not seem correct.
```C
else if(code == LV_EVENT_REFR_EXT_DRAW_SIZE) {
   lv_event_set_ext_draw_size(e, LV_MAX4(chart->tick[0].draw_size, chart->tick[1].draw_size, chart->tick[2].draw_size,
                                              chart->tick[3].draw_size));
```

Rev: 8.1 master

```C
lv_obj_t* chart = lv_chart_create(lv_scr_act());

lv_chart_set_type(chart, LV_CHART_TYPE_SCATTER);
lv_chart_set_div_line_count(chart, 11, 11);

lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_X, 0, 10000);
lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_X, 10, 0, 11, 1, true, 100);

lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 10000);
lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_Y, 10, 0, 11, 1, true, 100);

// set axis/grid lines style
lv_obj_set_style_line_width(chart, 1, LV_PART_MAIN);
lv_obj_set_style_line_color(chart, lv_palette_main(LV_PALETTE_GREY), LV_PART_MAIN);

// set ticks style
lv_obj_set_style_text_font(chart, &lv_font_montserrat_16, LV_PART_TICKS);
lv_obj_set_style_text_color(chart, lv_color_black(), LV_PART_TICKS);
lv_obj_set_style_line_width(chart, 2, LV_PART_TICKS);
```
![IMG_E2799](https://user-images.githubusercontent.com/7325277/137878777-298a3766-272e-4895-ba07-9232bba1456c.JPG)

**Comment by kisvegabor** [comment]
It seems to me the chart is simply larger than your screen.

**Comment by tdjastrzebski** [comment]
Initializing **chart** like this:
```C
lv_obj_t* scr = lv_scr_act();
lv_coord_t width = lv_obj_get_width(scr);
lv_coord_t height = lv_obj_get_height(scr);
lv_obj_t* chart = lv_chart_create(scr);
lv_obj_set_size(chart, width, height);
```
gives the below result - grid without labels and ticks. Not quite, because at the very bottom one or two top x-ticks pixels are visible but this is a minor issue.  
This question is if this is the desired behavior? Is the default size/alignment undefined?  
If so, it  probably makes no sense to provide tick label size as `lv_chart_set_axis_tick()` `draw_size` argument. This argument seems to make no difference. Also, notice additional space around plot area. Where/how is it defined?

![IMG_E2802](https://user-images.githubusercontent.com/7325277/138054753-d4e502b2-724c-4b93-b320-2982646bf63d.JPG)

**Comment by kisvegabor** [comment]
> This question is if this is the desired behavior? Is the default size/alignment undefined?

Yes, it's the desired behavior. Not sure, it's the best thing that can happen, I wanted it to work like this :slightly_smiling_face: 

The size of the chart not involves the "tick texts".   

Try this:
```c
lv_obj_t* scr = lv_scr_act();
lv_obj_t* chart = lv_chart_create(scr);
lv_obj_set_size(chart, lv_pct(50), lv_pct(50));
lv_obj_center(chart);
```

**Comment by tdjastrzebski** [comment]
IMHO this behavior is quite OK. Otherwise, (re)adjusting dimensions depending on labels size may be a pain some other widget deserves much more. Thanks
`lv_chart_set_axis_tick(...,draw_size)` still seems to make no good sense. It appears to be used just once to get the largest value out of four specified (X/Y primary/secondary)

**Comment by kisvegabor** [comment]
> lv_chart_set_axis_tick(...,draw_size) still seems to make no good sense. It appears to be used just once to get the largest value out of four specified (X/Y primary/secondary)

Yes, I was thinking about what API to create for it. Technically a separate function could work too. E.g. `lv_chart_set_tick_ext_draw_size(chart, 100)`. 

However, as draw_size is tightly connected to the values you set by `lv_chart_set_axis_tick` I found it better to have a config there, even if it's slightly redundant.

**Comment by tdjastrzebski** [comment]
I guess, I do not quite understand the role of `draw_size` argument.
If chart size determines its plot area size **only** and the user must size and place the chart within its parent the way there is enough space for axis labels, why `draw_size` is needed at all? And why the same value X and Y axes? X/Y labels may differ in size substantially.

**Comment by kisvegabor** [comment]
> I guess, I do not quite understand the role of draw_size argument.

It's required because widgets can't draw outsize of their bounding box. But sometimes there is some extra content that needs to be drawn out of the bound box. The most typical example is a shadow but the tick text are also out of the bounding box. 

LVGL can calculate the extra draw size required for the shadow form the style properties, but it's can't for the tick text in all case. E.g. if the numbers are replaced by month names in a draw event LVGL can't foresee see what will happen there. Therefore you need to set the extra draw size yourself.

**Comment by tdjastrzebski** [comment]
I am still not sure I fully understand. Let me ask you this: what is the most correct way of achieving the below sizing and appearance?  
It is probably the most common Excel-like scenario.

<img width="459" alt="LVGL Chart Widget 1" src="https://user-images.githubusercontent.com/7325277/138424636-575a5a7e-ba0d-4ec5-b634-e6b17f09d15b.png">

**Comment by tdjastrzebski** [comment]
@kisvegabor I mean, I know how to get the sizing I need. The question is how this should be accomplished the right way, e.g. without using zoom I found in some examples I came across. Since internally tick `draw_size` is not used the way I think it could be, the above basic layout does not seem to be attainable using just `lv_chart_*()` functions - unless I miss something.

**Comment by kisvegabor** [comment]
```c
lv_obj_set_size(chart, 800 - 100 - 25, 480 - 25 - 50);
lv_obj_set_pos(chart, 100, 25);
```

should do the job.
