### ISSUE TITLE
JavaScript simulator canvas in iframe

### ISSUE THREAD

**Issue by leidto** [kisvegabor/lvgl#2699]
### Introduce the problem
I'm working on an interactive editor in React. Based on your instructions I ran everything successfully and I was able to remove the unnaccessary code to display a simple canvas with the sample code. It runs fine but I can't use it in iframe (I'll have more scenes). 

Related conversation:
https://github.com/lvgl/lvgl/issues/2677

I get the following errors:
### First problem: 
`Uncaught (in promise) TypeError: Illegal invocation at HTMLDocument.document.querySelector (lvgl.html:37)`
###
![1](https://user-images.githubusercontent.com/7906474/137900793-612707d4-3ebe-4e01-b6a6-ea07d8f1c25f.PNG)

### Second problem:
```
lvgl_mp.js? [sm]:5896 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at Object.registerOrRemoveHandler (lvgl_mp.js? [sm]:5896)
    at registerMouseEventCallback (lvgl_mp.js? [sm]:8098)
    at _emscripten_set_mousemove_callback_on_thread (lvgl_mp.js? [sm]:8116)
    at imports.<computed> (lvgl_mp.js? [sm]:8626)
    at Emscripten_RegisterEventHandlers (firmware.wasm:0x4e645f)
    at Emscripten_CreateWindow (firmware.wasm:0x4ea483)
    at SDL_CreateWindow (firmware.wasm:0x4c688f)
    at monitor_init (firmware.wasm:0x379bc3)
    at mp_init_SDL (firmware.wasm:0x37a9ed)
    at fun_builtin_var_call (firmware.wasm:0x77e70)
```

It doesn't work in either in React or pure HTML. (in iframe).

Do you have any idea how I can resolve these issues?

I've started to rewrite the Simulator wrapper code in ES6/React, but I don't know if that would help, so I'll pause it for now.

**Comment by embeddedt** [comment]
I made the assumption when working on this that the topmost window (`window.top`) is the one with the editor & other frontend code, just in case I ever ended up needing to nest multiple layers of iframes for some reason. (MicroPython itself runs inside an iframe so it can be restarted without needing to reload the whole editor page.)

If you replaced all references to `window.top` in the code with `window.parent` and rebuilt, I suspect it would work properly, though I can't test it at the moment.

**Comment by leidto** [comment]
Thank you. It's working.
