### ISSUE TITLE
The default font is always lv_font_montserrat_14.

### ISSUE THREAD

**Issue by SinglWolf** [kisvegabor/lvgl#2702]
I risk expelled from the community, but this is a matter of principle.
Instead of sleeping peacefully, I searched all night for a reason why I can not choose the default built-in font as it was in version `7.XX`.
Found.

### Introduce the problem
I am unable to choose the default font for a trivial reason.
There is no selection menu for built-in default font. It just doesn't exist physically.
There is selection menu  for default font  for `title` the theme and that's it. Although there is a proud `LV_FONT_DEFAULT` macro in `lvgl\Kconfig`, ostensibly intended to globally select the default font. Not only does this definition of `LV_FONT_DEFAULT` do not work in the` ESP-IDF` environment, `choice LV_FONT_DEFAULT` refers to the default font selection menu for the theme's` title`.

### Examples and cases
![2021-10-20_06-51-18](https://user-images.githubusercontent.com/32172969/138015313-b7de7c70-c6e7-4fe3-a093-4336cf4ba5a7.png)
In file `lvgl\src\lv_conf_internal.h`
```c
/*Always set a default font*/
#ifndef LV_FONT_DEFAULT // Never defined
#  ifdef CONFIG_LV_FONT_DEFAULT
#    define LV_FONT_DEFAULT CONFIG_LV_FONT_DEFAULT
#  else
#    define LV_FONT_DEFAULT &lv_font_montserrat_14 // Therefore the font is always lv_font_montserrat_14.
#  endif
#endif
```

### Suggested solution
In this community, I am an outcast, on the verge of exile, so I will not even try to offer something as a solution for this problem.

Thanks for reading.

**Comment by xiaoxiang781216** [comment]
@SinglWolf could you try this patch: https://github.com/lvgl/lvgl/pull/2703?

**Comment by SinglWolf** [comment]
> @SinglWolf could you try this patch: #2703?

Fine! It works!
Now I will have a good mood all day. Despite the fact that I really want to sleep.
![2021-10-20_08-35-45](https://user-images.githubusercontent.com/32172969/138024201-6423b66d-c8d5-44eb-9fe9-299681204b91.png)
Only now you need to change the name of the menu, remove the mention of  choice font for theme title.
