### ISSUE TITLE
Arabic display error

### ISSUE THREAD

**Issue by Bluelongshirt** [kisvegabor/lvgl#2712]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I meet some problem when doing Arabic Input.
I have set LV_USE_BIDI==1 and LV_USE_ARABIC_PERSIAN_CHARS==1.

Probelm1:
I found that if I use the lv_textarea_add_text interface to add a string, an error will occur, and the actual string does not meet expectations.But if only a single character is added, the result is as expected.
According to the code, I found that because the lv_label_ins_text interface performs BIDI processing on the input string when LV_USE_BIDI==1, resulting in subsequent character deformation errors.
Excuse me, why is BIDI processing required when LV_USE_BIDI==1 in the lv_label_ins_text interface?

code:
```c
#if LV_USE_BIDI
    char * bidi_buf = lv_mem_buf_get(ins_len + 1);
    LV_ASSERT_MALLOC(bidi_buf);
    if(bidi_buf == NULL) return;

    _lv_bidi_process(txt, bidi_buf, lv_obj_get_style_base_dir(obj, LV_PART_MAIN));
    _lv_txt_ins(label->text, pos, bidi_buf);

    lv_mem_buf_release(bidi_buf);
#else
    _lv_txt_ins(label->text, pos, txt);
#endif
```
if delete bidi process,the result is correct

Problem2:
If using lv_textarea_set_align to set LV_TEXT_ALIGN_RIGHT,the cursor will not move.

### To Reproduce

```c
static const char * const default_kb_map_ar[] =
{
    "del", "جثف", "ص", "ث", "ق", "ف", "غ", "ع", "ه","خ", "ح","ج", "\n",
    "ش", "س", "ي", "ب", "ل", "ا", "ت", "ن", "م", "ك", "ط",  "\n",
    "ذ", "ء", "ؤ", "ر", "ى", "ة", "و", "ز", "ظ", "د", "ز", "ظ", "د","\n",
	"1", "2", "3", "4", "5", "q", "w", "e", "r", "!", ":", "?", "(","\n",
};

static const lv_btnmatrix_ctrl_t default_kb_ctrl_ar_map[] = {
    5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
};


static void keyboard_event_cb(lv_event_t *e){
    lv_obj_t * obj = lv_event_get_target(e);

    lv_keyboard_t * keyboard = (lv_keyboard_t *)obj;
    uint16_t btn_id   = lv_btnmatrix_get_selected_btn(obj);
    if(btn_id == LV_BTNMATRIX_BTN_NONE) return;

    const char * txt = lv_btnmatrix_get_btn_text(obj, lv_btnmatrix_get_selected_btn(obj));
    if(txt == NULL) return;
    
    if(txt=="del"){lv_textarea_del_char(keyboard->ta);}
    else{
       lv_textarea_add_text(keyboard->ta, txt);
    }
}

LV_FONT_DECLARE(testfont);
void lv_arabic_input_test(void){
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_text_font(&style,&testfont);

       lv_obj_t *textarea = lv_textarea_create(lv_scr_act());

    lv_obj_t *keyboard = lv_keyboard_create(lv_scr_act());
    lv_obj_add_style(keyboard, &style, 0);
    lv_keyboard_set_mode(keyboard, LV_KEYBOARD_MODE_TEXT_LOWER);
    lv_keyboard_set_map(keyboard, LV_KEYBOARD_MODE_TEXT_LOWER, (const char **)default_kb_map_ar, default_kb_ctrl_ar_map);
    lv_obj_remove_event_cb(keyboard, lv_keyboard_def_event_cb);
    lv_obj_add_event_cb(keyboard, keyboard_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_keyboard_set_textarea(keyboard, textarea);
    lv_obj_add_style(textarea, &style, 0);
}
```

**Comment by Bluelongshirt** [comment]
Problem3:
There seems to be a problem with the bidi algorithm when displayed
Add text "جحخ123qwe" 
Expected bahavior
![image](https://user-images.githubusercontent.com/91590626/138401444-bc723d7e-4ddd-4ded-9213-a105ccf2b370.png)
（I change the bidi_dir of obj,the bidi_dir is LV_BASE_DIR_RTL）

Actualy behavior
![image](https://user-images.githubusercontent.com/91590626/138401626-455cd169-432b-4304-9bc7-2f2936203139.png)

From the above，We can know the bidi_dir is error when displaying Arabic. the bidi_dir should be LV_BASE_DIR_RTL when displaying Arabic,But It seems not judge the first character when displaying Arabic

**Comment by kisvegabor** [comment]
Problem 1:
I pushed a fix as you suggested

Problem 2:
I pushed a fix for it too. 
No that, the last `\n` in `default_kb_map_ar` should be `""`.

Problem 3:
I don't really understand. Can you reproduce it with some `lv_textarea_add_text()` calls?
(Above fixes might affect it.)

**Comment by Bluelongshirt** [comment]
> Problem 1: I pushed a fix as you suggested
> 
> Problem 2: I pushed a fix for it too. No that, the last `\n` in `default_kb_map_ar` should be `""`.
> 
> Problem 3: I don't really understand. Can you reproduce it with some `lv_textarea_add_text()` calls? (Above fixes might affect it.)

 Thanks for your reply!
 I have pulled the latest code and verified the problem1.

I find another problem when I verified the problem2.
If I set the textarea size,the cursor is not normal at the beginning.


lv_obj_set_size(textarea,150,200),Cannot display cursor
![image](https://user-images.githubusercontent.com/91590626/138991920-ada5390a-9bea-4204-883a-e74cf7b18967.png)

lv_obj_set_size(textarea,350,200);Cursor in the middle
![image](https://user-images.githubusercontent.com/91590626/138992030-c0524726-f284-4793-bd4b-4a453b26c83f.png)

When I input a character, the cursor is normal again.
![image](https://user-images.githubusercontent.com/91590626/138992095-7526dec9-3e4a-419f-b43c-168b2daf9cbf.png)



another problem:
the cursor will not move,if cursor in the left
![image](https://user-images.githubusercontent.com/91590626/138993457-ca666549-67c6-4f3a-941e-9af9e6864ac2.png)

**Comment by Bluelongshirt** [comment]
I'm Sorry,   I didn’t express the problem3 clearly.
I plan to make an Arabic keyboard, so I need to consider the case of mixed characters.this involves the Unicode Bidirectional Algorithm.I don’t know much about the algorithm,So I use the phone input method as a comparison.

The following tests are based on the latest code.
I Input 
![image](https://user-images.githubusercontent.com/91590626/138994301-afe2493c-bc53-4666-ab59-e94a53ee668f.png)
+
![image](https://user-images.githubusercontent.com/91590626/138994344-35a2dabf-5c90-4337-80fe-0543d908dc72.png)
+
![image](https://user-images.githubusercontent.com/91590626/138994382-d58a936e-c9b8-4ca6-b571-9e36a3067310.png)
+"1"+"2"+“3”+“q”+"w"+"e"

The effect of the test is as follows:
![image](https://user-images.githubusercontent.com/91590626/138994454-b23cf05b-ebf1-48e7-a748-ce743c2f166e.png)

The effect of the test In the phone:
![image](https://user-images.githubusercontent.com/91590626/138994527-2043e2a2-6123-4b3d-b4b1-2d6b90d8894c.png)

The results is different, so I wonder if there is something wrong with the Unicode Bidirectional Algorithm on lvgl.

By the way,Why not consider add fribidi library？

**Comment by kisvegabor** [comment]
> If I set the textarea size,the cursor is not normal at the beginning.

Please send a small code snippet to reproduce. I don't need to know the text align and base dir settings.


> I plan to make an Arabic keyboard, so I need to consider the case of mixed characters.this involves the Unicode Bidirectional Algorithm.I don’t know much about the algorithm,So I use the phone input method as a comparison.

We followed mainly [this description](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics). There is only a short paragraph about numbers [here](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#numbers). It says:
> [...] the number is seen as part of the preceding Arabic text [...]

In your example it's not the case. What would happen if you added an `a` chanter at the end?

I made some test with LVGL:

**LTR base dir** (text align right doesn't matter, it just moves the text to the right)
![image](https://user-images.githubusercontent.com/7599318/139067638-27e18702-8654-490a-ac8c-dddb2c143e43.png)
It looks natural, some Arabic characters, and some ASCII left to right.

**RTL base dir** (I set LV_TEXT_ALIGN_LEFT for easier comparision)
![image](https://user-images.githubusercontent.com/7599318/139068143-c8fec280-1aaf-476b-b30e-e04aae5d97d1.png)
Reading from right to left, the Arabic text comes first and the ASCII second

So LVGL really treated numbers together with the preceding text.

An [online RTL editor](https://froala.com/wysiwyg-editor/examples/editor-direction/) gives teh same result as LVGL:
![image](https://user-images.githubusercontent.com/7599318/139069453-a45e014c-4eb8-4ea2-a7f5-c0e4df0dd23c.png)


> By the way,Why not consider add fribidi library？

It has several reasons:
- We (or at least me) didn't know about it :slightly_smiling_face: 
- It's LGPL license is not compatible with LVGL's MIT license
- It's huge, compared to LVGL's 700 line implementation.

**Comment by Bluelongshirt** [comment]
another problem:
the cursor will not move,if cursor in the left


It's the code:

static const char * const default_kb_map_ar[] =
{
    "del", "جثف", "ص", "ث", "ق", "ف", "غ", "ع", "ه","خ", "ح","ج", "\n",
    "ش", "س", "ي", "ب", "ل", "ا", "ت", "ن", "م", "ك", "ط",  "\n",
    "ذ", "ء", "ؤ", "ر", "ى", "ة", "و", "ز", "ظ", "د", "ز", "ظ", "د","\n",
	"1", "2", "3", "4", "5", "q", "w", "e", "r", "!", ":", "?", "(","\n",
    "new", ")", """, """, "&", "%", "$", "#", "@", "-", "+", "=", "*","\n",
};

static const lv_btnmatrix_ctrl_t default_kb_ctrl_ar_map[] = {
    5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
};

static void keyboard_event_cb(lv_event_t *e){
    lv_obj_t * obj = lv_event_get_target(e);

    lv_keyboard_t * keyboard = (lv_keyboard_t *)obj;
    uint16_t btn_id   = lv_btnmatrix_get_selected_btn(obj);
    if(btn_id == LV_BTNMATRIX_BTN_NONE) return;

    const char * txt = lv_btnmatrix_get_btn_text(obj, lv_btnmatrix_get_selected_btn(obj));
    if(txt == NULL) return;
    
    if(txt=="del"){lv_textarea_del_char(keyboard->ta);}
    else if(txt=="new"){lv_textarea_add_text(keyboard->ta, "\n");}
    else{
       lv_textarea_add_text(keyboard->ta, txt);
    }
}

LV_FONT_DECLARE(testfont);
void lv_example_style_8(void){
    const char *data="مرحبا ، يانغ تشاو ، أنا معجب بك كثيرا ، هيا";
    const char *data1="English iop";
    const char *data2="جحخ123qwe!:";
    const char *data3="لب";
    static lv_style_t style;
    int i=0;
    lv_style_init(&style);
    lv_style_set_text_font(&style,&test);
     lv_style_set_base_dir(&style,LV_BASE_DIR_AUTO);
     lv_obj_t *textarea = lv_textarea_create(lv_scr_act());

    lv_obj_t *keyboard = lv_keyboard_create(lv_scr_act());
    lv_obj_add_style(keyboard, &style, 0);
    lv_keyboard_set_mode(keyboard, LV_KEYBOARD_MODE_TEXT_LOWER);
    lv_keyboard_set_map(keyboard, LV_KEYBOARD_MODE_TEXT_LOWER, (const char **)default_kb_map_ar, default_kb_ctrl_ar_map);
    lv_obj_remove_event_cb(keyboard, lv_keyboard_def_event_cb);
    lv_obj_add_event_cb(keyboard, keyboard_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_set_size(textarea,350,200);

    lv_obj_add_style(textarea, &style, 0);
    lv_textarea_set_align(textarea,LV_TEXT_ALIGN_RIGHT);
    lv_keyboard_set_textarea(keyboard, textarea);
}


Thanks for your reply,I will study the relevant information.

**Comment by Bluelongshirt** [comment]
Excuse me,Is the order of the data you entered during the test consistent with what I described？
I test it in the online RTL editor you give,the results displayed on the web are consistent with the mobile phone input method
![image](https://user-images.githubusercontent.com/91590626/139180534-1e965489-54fa-44a4-89f6-5febf4b43cbb.png)

**Comment by kisvegabor** [comment]
> Excuse me,Is the order of the data you entered during the test consistent with what I described？

Oh, sorry, it seems I missed the order :sweat: 

`Arabic + Numbers + English` really gives the same result as yours screenshot. 

I refreshed my memories about handling of number in bidi text and found this description on [Wikipedia](https://en.wikipedia.org/wiki/Bidirectional_text)

> Weak characters
Weak characters are those with vague direction. Examples of this type of character include European digits, Eastern Arabic-Indic digits, arithmetic symbols, and currency symbols.

Clear, weak characters ~= numbers on any language

> Numbers
Unless a directional override is present numbers are always encoded (and entered) big-endian, and the numerals rendered LTR. The weak directionality only applies to the placement of the number in its entirety.

Clear, numbers are always written from left-to-right, but it depends on the context where to place the "number-pack".

> Runs
In the algorithm, each sequence of concatenated strong characters is called a "run". A "weak" character that is located between two "strong" characters with the same orientation will inherit their orientation. A "weak" character that is located between two "strong" characters with a different writing direction, will inherit the main context's writing direction (in an LTR document the character will become LTR, in an RTL document, it will become RTL).

So with RTL base direction, in the case of `Arabic + Numbers + English`,  `Arabic + Numbers` is one run and `English` is an other. That is It should look like
```
 English123cibarA 
 
 |  2. |    1.  |
 ======><========
        -->
```

Although, I can't speak any Arabic-like languages, this algorithm makes sense to me. If it's vague where to attache the numbers let's assume it goes to the word with matching base direction.

In light of that
1. LVGL's algorithm works as intended 
2. Not sure if the intended algorithm is correct or I understood it correctly :slightly_smiling_face: 
3. I don't know what are there rules for the bidi algorithm on web (and your phone).

---

I pushed a fix for the cursor position issue.

**Comment by Bluelongshirt** [comment]
It seems that there are some problems when numeric characters are surrounded by two strong characters with different directions.I mainly refer to the introduction of this web.
http://unicode.org/reports/tr9/tr9-17.html

In addition, I tested the latest code, and it seems that the cursor is normal from left to right, but it is abnormal from right to left, like back to the beginning.

Under abnormal conditions, the cursor will not move.

![image](https://user-images.githubusercontent.com/91590626/139371740-67bc5b05-ab53-48e4-803b-fe45639d788a.png)

![image](https://user-images.githubusercontent.com/91590626/139371754-81d3e0fe-8618-4f3d-8a45-493399f2813e.png)

**Comment by kisvegabor** [comment]
> Bluelongshirt commented 5 hours ago
It seems that there are some problems when numeric characters are surrounded by two strong characters with different directions.I mainly refer to the introduction of this web.
http://unicode.org/reports/tr9/tr9-17.html

Which part do you mean exactly?

> In addition, I tested the latest code, and it seems that the cursor is normal from left to right, but it is abnormal from right to left, like back to the beginning

I've update the cursor handling again. It wasn't working with `LV_BASE_DIR_AUTO` but it should now. Note that, LVGL figures out the base direction based on the first character. So if you need  Arabic input only I suggest using `LV_BASE_DIR_RTL`.

**Comment by Bluelongshirt** [comment]
Thanks your reply.
I have tested the latest code,The cursor looks normal.

In addition, I found a phenomenon, if the first input is Arabic, the cursor will automatically align to the right, if the first input is a letter, the cursor will automatically align to the left.
But after entering Arabic first, and then entering letters in a new line, the cursor will not automatically align to the left at this time.
Is it possible to determine the alignment direction based on the first character in new line if use "\n"?



About bidi algorithm,I get the introduce from this website
http://www.unicode.org/reports/tr9/

accroding to 3.3.1
We can know that we need to divide the level of the sentence, and define the basic level of the sentence according to the first strong character.

accroding to 3.3.4,W7

R  NI EN → R  NI  EN

accroding to 3.3.6
![image](https://user-images.githubusercontent.com/91590626/140029352-dea21c55-dc96-438c-9906-54b23e988d33.png)

accroding to 3.4
We need Rearrange resolved levels



Based on the above introduction, I rearranged the example I gave last time.

accroding to 3.3.1
![image](https://user-images.githubusercontent.com/91590626/140031010-de6764b0-424f-4a3b-a757-fcd64f70c99a.png)
the base level is R

accroding to 3.3.4,W7
![image](https://user-images.githubusercontent.com/91590626/140031038-dfb485cd-0804-4503-b29b-2ea626183d98.png)

accroding to 3.3.6
![image](https://user-images.githubusercontent.com/91590626/140031133-4c33af50-50bc-4358-be7c-bfa409055c20.png)

accroding to 3.4

![image](https://user-images.githubusercontent.com/91590626/140031897-293e81a6-9003-40d1-9f6b-91a9a9074353.png)

This is my own understanding and may be incorrect, but the result I verified with this method is consistent with the input method of the mobile phone

**Comment by kisvegabor** [comment]
> Is it possible to determine the alignment direction based on the first character in new line if use "\n"?

Do you know some editors where it works like this?

> accroding to 3.3.4,W7

It should be the problem. LVGL attaches the numbers to the strong character which has base direction equal to the text's set base direction.

I couldn't immerse in it yet, but this function is responsible for finding the runs:
https://github.com/lvgl/lvgl/blob/acd0f4fbc71ffbfeb382b7af1fa52caf3cdcda6c/src/misc/lv_bidi.c#L428

Do you have time to to take a look at it?

**Comment by Bluelongshirt** [comment]
> Do you know some editors where it works like this?

Regarding this effect, I am not sure, I will check again.


> I couldn't immerse in it yet, but this function is responsible for finding the runs:




`   
 while(dir == LV_BASE_DIR_NEUTRAL || dir == LV_BASE_DIR_WEAK) {
        letter = _lv_txt_encoded_next(txt, &i);

        pos_conv_i++;
        dir = lv_bidi_get_letter_dir(letter);
        if(dir == LV_BASE_DIR_NEUTRAL)  dir = bracket_process(txt, i, max_len, letter, base_dir);
 
        if(dir==LV_BASE_DIR_LTR || dir==LV_BASE_DIR_RTL)
        break;

        if(i >=max_len || txt[i] == '\0' || txt[i] == '\n' || txt[i] == '\r') {
            *len = i;
            *pos_conv_len = pos_conv_i;
            return base_dir;
        }
    }

  while(i_prev < max_len && txt[i] != '\0' && txt[i] != '\n' && txt[i] != '\r') {
        letter = _lv_txt_encoded_next(txt, &i);
        pos_conv_i++;
        next_dir  = lv_bidi_get_letter_dir(letter);
        if(next_dir == LV_BASE_DIR_NEUTRAL)  next_dir = bracket_process(txt, i, max_len, letter, base_dir);
   


        if(next_dir == LV_BASE_DIR_WEAK){
            if(run_dir == LV_BASE_DIR_RTL){
                if(base_dir == LV_BASE_DIR_RTL){
                    next_dir = LV_BASE_DIR_LTR;
                }   
            }
        }

        /*New dir found?*/
        if((next_dir == LV_BASE_DIR_RTL || next_dir == LV_BASE_DIR_LTR) && next_dir != run_dir) {
            /*Include neutrals if `run_dir == base_dir`*/
            if(run_dir == base_dir) {
                *len = i_prev;
                *pos_conv_len = pos_conv_i_prev;
            }
            /*Exclude neutrals if `run_dir != base_dir`*/
            else {
                *len = i_last_strong;
                *pos_conv_len = pos_conv_i_last_strong;
            }

            return run_dir;
        }

        if(next_dir != LV_BASE_DIR_NEUTRAL) {
            i_last_strong = i;
            pos_conv_i_last_strong = pos_conv_i;
        }

        i_prev = i;
        pos_conv_i_prev = pos_conv_i;
    }`
  This is the modification I tried to make. I have verified that some examples are successful, but there is no guarantee that it will be consistent with the bidi algorithm.

**Comment by Bluelongshirt** [comment]
Another Problem.

![image](https://user-images.githubusercontent.com/91590626/140694398-aa0ece11-a6a4-44ec-ba98-ab617afe9720.png)

when I put '\n' enter another line.
I Put "123qwe",but display "qwe123".
I think "123qwe" is corret.

**Comment by kisvegabor** [comment]
Let solve one thing at a time :slightly_smiling_face: 
Can you send a PR with the fixes in `get_next_run`?

**Comment by Bluelongshirt** [comment]
I have send a PR.
