### ISSUE TITLE
There are some problems with new_points_alloc() in lv chart.c.

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#2714]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When I don't know how many points there are in total, I dynamically increase the number of points drawn, and then there is a problem with the drawing of the scatter chart.

### To Reproduce

static void test(void)
{
    lv_obj_t* chart = lv_chart_create(lv_scr_act());
    lv_obj_set_size(chart, 400, 200);
    lv_chart_set_axis_tick(chart, LV_CHART_AXIS_PRIMARY_Y, 3, 0, 5, 2, true, 64);
    lv_obj_center(chart);
    lv_obj_set_style_line_width(chart, 0, LV_PART_ITEMS);
    lv_chart_set_type(chart, LV_CHART_TYPE_SCATTER);
    lv_chart_set_div_line_count(chart, 0, 0);
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_X, 0, 50);
    lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 140, 200);
    lv_chart_set_point_count(chart, 2);
    lv_chart_series_t* ser = lv_chart_add_series(chart, lv_color_hex(0x7B51F0), LV_CHART_AXIS_PRIMARY_Y);
    lv_coord_t p[] = { 140, 150, 160, 170 };
    for (lv_coord_t i = 0; i < 4; i++) {
        lv_chart_set_point_count(chart, lv_chart_get_point_count(chart) + 1);
        lv_chart_set_next_value2(chart, ser, i, p[i]);
    }
}

### Expected behavior

The following changes may be needed in new_points_alloc():
![image](https://user-images.githubusercontent.com/51692568/138291249-619d4768-897b-4859-a36c-1f0971531f44.png)

![image](https://user-images.githubusercontent.com/51692568/138290809-d85e4f2a-4fec-4f1b-a456-eba05f498570.png)

### Screenshots or video

![image](https://user-images.githubusercontent.com/51692568/138290914-91b1c0b0-e0e2-4ad8-89af-ba68efd48051.png)

**Comment by kisvegabor** [comment]
Hi,

I dig into it to understand the problem and ended up with a conceptual question that I couldn't answer.

Let's consider this code:
```c

    /*Create a chart*/
    lv_obj_t * chart = lv_chart_create(lv_scr_act());
    lv_obj_set_size(chart, 200, 150);
    lv_obj_center(chart);
    lv_chart_set_update_mode(chart, LV_CHART_UPDATE_MODE_CIRCULAR);

    lv_chart_series_t * ser1 = lv_chart_add_series(chart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);

    lv_chart_set_next_value(chart, ser1, 0);
    lv_chart_set_next_value(chart, ser1, 5);
    lv_chart_set_next_value(chart, ser1, 10);
    lv_chart_set_next_value(chart, ser1, 15);
    lv_chart_set_next_value(chart, ser1, 20);
    lv_chart_set_next_value(chart, ser1, 25);
    lv_chart_set_next_value(chart, ser1, 30);
    lv_chart_set_next_value(chart, ser1, 35);
    lv_chart_set_next_value(chart, ser1, 40);
    lv_chart_set_next_value(chart, ser1, 45);
    lv_chart_set_next_value(chart, ser1, 50);
    lv_chart_set_next_value(chart, ser1, 55);
    lv_chart_set_next_value(chart, ser1, 60);
```

Resulting in 
![image](https://user-images.githubusercontent.com/7599318/138335003-06004b18-f31e-4f3f-877a-f126802ec971.png)


What should happen if the user changes the number of points from 10 to 15? There will be 5 new points to which we can't assign data as the chart remembers only 10 points. The most obvious solution would be to add 5 empty points on the right but I wonder if we can do something better. 

What do you think?

**Comment by qinshijing** [comment]
I agree with you. From the perspective of data integrity, I think the following two changes are acceptable. What do you think?

now
![image](https://user-images.githubusercontent.com/51692568/138373613-d7f33607-35f5-4c4f-8526-0dd03716ddfc.png)
change
![image](https://user-images.githubusercontent.com/51692568/138373732-256a4aa7-dec8-433b-9ebf-c3cc5c913027.png)
or change
![image](https://user-images.githubusercontent.com/51692568/138373769-db9ab922-ec2f-4ff7-9b0d-7ae7fc2a6138.png)

**Comment by kisvegabor** [comment]
Do you think this version is not acceptable?

point cnt: 10

```
         *
50 55 60 15 20 25 30 35 40 45 
```

point cnt: 15
```
         *
50 55 60 15 20 25 30 35 40 45 -- -- -- -- --
```

IMO there is no perfect solution here, maybe we should chose the most straight forward one.

**Comment by qinshijing** [comment]
In this version:
This may cause confusion to the user, because the user has applied for 5 more points, and the chart should be able to store up to 15 points at this time. Then I added a 65 to it, and found that there are still only 10 points in the chart, and 15 is missing.
`
50 55 60 65 20 25 30 35 40 45 -- -- -- -- --
`

**Comment by kisvegabor** [comment]
Hm, in my opinion it's also counter-intuitive if the current start_point (i.e. the whole appearance of the chart) changes on point count change.

What if we simply extended the point count as I suggested but also add a function that can reorder points for a new start_point. I think it'd give the highest flexibility.

**Comment by qinshijing** [comment]
Yes, I agree with you.

**Comment by kisvegabor** [comment]
Great, do you have time/are you interested in implementing it and sending a PR?
