### ISSUE TITLE
draw_line_hor() draw_line_ver() maybe miss one pixel

### ISSUE THREAD

**Issue by steprun** [kisvegabor/lvgl#2716]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

draw_line_hor() draw_line_ver() maybe miss one pixel

### To Reproduce

I draw a 54 pixels line, and 10 point every 10 pixel.  But there is only 53 pixels in line.

```c
int cor_line_hor_len = 54;
p1.x = x_ofs;
p1.y = y_ofs + 40;
p2.x = p1.x + cor_line_hor_len - 1;
p2.y = p1.y;

line_dsc.width = 2;
lv_draw_line(&p1, &p2, clip_area, &line_dsc);

line_dsc.width = 2;
for (int i = 0; i < 100; i += 10) {
    p1.x = x_ofs + i;
    p1.y = y_ofs + 36;
    p2.x = p1.x + 1;
    p2.y = p1.y;
    lv_draw_line(&p1, &p2, clip_area, &line_dsc);
}
```

### Screenshots or video
<!--
--
![f1ea3688d7190338b7025934e972da1](https://user-images.githubusercontent.com/8555048/138384935-1ef361e1-6a2d-41bc-affd-9dacfa1c5819.jpg)
>

**Comment by steprun** [comment]
![微信图片_20211022104719](https://user-images.githubusercontent.com/8555048/138385229-00c14f93-8a92-425c-988a-c2a88fa86e05.png)

**Comment by kisvegabor** [comment]
It seems really there is some inconsistency here. In case of rectangles x1=10; x2=13 will result in a 4 px wide rectangle because the last pixel is also painted. 

But in case of lines the last pixel is not painted. I remember that I adjusted the hor/ver lines behavior to the natural behavior of the skew lines. 

Fixing skew lines would be really complicated but I'll take a look. Until that I suggest manually compensating that missing pixel.

**Comment by steprun** [comment]
```
diff --git a/src/draw/lv_draw_line.c b/src/draw/lv_draw_line.c
index 407a280a..91d17b46 100644
--- a/src/draw/lv_draw_line.c
+++ b/src/draw/lv_draw_line.c
@@ -131,7 +131,7 @@ LV_ATTRIBUTE_FAST_MEM static void draw_line_hor(const lv_point_t * point1, const

     lv_area_t draw_area;
     draw_area.x1 = LV_MIN(point1->x, point2->x);
-    draw_area.x2 = LV_MAX(point1->x, point2->x)  - 1;
+    draw_area.x2 = LV_MAX(point1->x, point2->x);
     draw_area.y1 = point1->y - w_half1;
     draw_area.y2 = point1->y + w_half0;

@@ -233,7 +233,7 @@ LV_ATTRIBUTE_FAST_MEM static void draw_line_ver(const lv_point_t * point1, const
     draw_area.x1 = point1->x - w_half1;
     draw_area.x2 = point1->x + w_half0;
     draw_area.y1 = LV_MIN(point1->y, point2->y);
-    draw_area.y2 = LV_MAX(point1->y, point2->y) - 1;
+    draw_area.y2 = LV_MAX(point1->y, point2->y);

     bool dashed = dsc->dash_gap && dsc->dash_width ? true : false;
     bool simple_mode = true;
```
