### ISSUE TITLE
Customizable display window for frame rate information and memory usage statistics

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#2735]
### Introduce the problem
The current two information windows can only be located at the bottom left and bottom right of the screen, but when using a circular screen, these two windows are located outside the screen and are not visible.

### Examples and cases
![image](https://user-images.githubusercontent.com/26767803/139012458-dc194d8b-f60b-4813-b64c-a9cd182d99cf.png)

### Suggested solution
![image](https://user-images.githubusercontent.com/26767803/139013072-ff297450-27ec-49f6-847b-79240f71ae31.png)
![image](https://user-images.githubusercontent.com/26767803/139013209-e07ee970-7831-4c46-b99f-3ba9c269f059.png)
Can these two values ​​be used as configurable options?
Such as `LV_ALIGN_LEFT_MID` and `LV_ALIGN_RIGHT_MID` when using a round screen.

**Comment by kisvegabor** [comment]
It'd be possible. We can say value `0` disables the boxes and any `LV_ALIGN_...` enables them. (0 means `LV_ALIGN_DEFAULT` which can be considered as an invalid value).

Now, the boxes are enabled with  `1` which means `LV_ALIGN_TOP_LEFT` which is slightly unfortunate, but we can make such a change in the upcoming release (will come in a few weeks).

**Comment by FASTSHIFT** [comment]
> It'd be possible. We can say value `0` disables the boxes and any `LV_ALIGN_...` enables them. (0 means `LV_ALIGN_DEFAULT` which can be considered as an invalid value).
> 
> Now, the boxes are enabled with `1` which means `LV_ALIGN_TOP_LEFT` which is slightly unfortunate, but we can make such a change in the upcoming release (will come in a few weeks).


Great, I agree with you.

**Comment by embeddedt** [comment]
Technically, we could achieve 100% backwards compatibility by changing the macro name in 8.1 and adding logic to `lv_conf_internal.h` to catch uses of the old macro name:

```c
#if !defined(LV_PERF_MONITOR_POSITION)
#if LV_USE_PERF_MONITOR
#define LV_PERF_MONITOR_POSITION LV_ALIGN_BOTTOM_RIGHT
#else
#define LV_PERF_MONITOR_POSITION 0
#endif
#endif
```

I'm not sure if it's worth all that effort for a debug feature, but I figured it was worth pointing out.

**Comment by kisvegabor** [comment]
@embeddedt 
Actually it'd work automatically if we added
```c
#define LV_PERF_MONITOR_POSITION LV_ALIGN_BOTTOM_RIGHT
```
because if `LV_PERF_MONITOR_POSITION` is not defined in `lv_conf.h` `lv_conf_internal.h` will set the default value (`LV_ALIGN_BOTTOM_RIGHT`) automatically.

I think we can go with this direction and clean it up in v9. What do you think?

**Comment by embeddedt** [comment]
True. It would require anyone with `#define LV_USE_PERF_MONITOR 0` to disable it again using the new option, but that is probably acceptable.

**Comment by kisvegabor** [comment]
I've added it. I believe it's fully backward compatible this way.
