### ISSUE TITLE
msgbox: when the font size is larger, it will exceed the button.

### ISSUE THREAD

**Issue by Littermonkey** [kisvegabor/lvgl#2740]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

is the size of the button group fixed? can't change with font size?  I think that not good function.
### To Reproduce

	ui->screen = lv_obj_create(NULL);
	static const char * screen_msgbox_1_btns[] = {"Apply","Close",""};
	ui->screen_msgbox_1 = lv_msgbox_create(ui->screen, "hello", "This is a long content", screen_msgbox_1_btns, true);
	lv_obj_set_pos(ui->screen_msgbox_1, 120, 72);
	lv_obj_set_size(ui->screen_msgbox_1, 280, 150);

	static lv_style_t style_screen_msgbox_1_extra_btns_main_default;
	lv_style_init(&style_screen_msgbox_1_extra_btns_main_default);
	lv_style_set_radius(&style_screen_msgbox_1_extra_btns_main_default, 5);
	lv_style_set_text_font(&style_screen_msgbox_1_extra_btns_main_default, &lv_font_montserrat_36);
	lv_obj_add_style(lv_msgbox_get_btns(ui->screen_msgbox_1), &style_screen_msgbox_1_extra_btns_main_default, LV_PART_ITEMS|LV_STATE_DEFAULT);
![msgboxIssue1](https://user-images.githubusercontent.com/30677217/139239237-0c7bb3ed-1f36-497d-b693-faa81bf92bfe.PNG)

**Comment by kisvegabor** [comment]
The message box is not responsive in this regard. You can adjust it's size manually:
```c
    lv_obj_t * btns = lv_msgbox_get_btns(mbox1);
    lv_obj_set_size(btns, 200, 100);
```

**Comment by Littermonkey** [comment]
Hi, Kisvegabor 
     First of all, thanks for your prompt reply.  And your suggestion makes sense.  The width and height of this function parameter are applied to the button group. right?  So, I want to get every button's width size and spacing between each button.  What is the calculation relationship between them?  
Best Regards
Monkey

**Comment by kisvegabor** [comment]
> The width and height of this function parameter are applied to the button group. right? 

Yes. Actually it's a [button matrix](https://docs.lvgl.io/master/widgets/core/btnmatrix.html), so it works the same way.

**Comment by Littermonkey** [comment]
Confused， how to distribute that every button's width size and spacing between each button? What is the calculation relationship between them?

**Comment by kisvegabor** [comment]
If you change the width of the button matrix the width of the buttons will be distributed in it equally.
