### ISSUE TITLE
About the table cell

### ISSUE THREAD

**Issue by zirobin** [kisvegabor/lvgl#2746]
I created a table and found that it have a selector, but i can not find any function to control the select cell, because I want to limit the move range of the selector and get the current select cell. 
![动画](https://user-images.githubusercontent.com/41822892/139518798-ca476ab0-6396-4a8c-acc3-429388dd003f.gif)
My program is use to view or modify the registers, so I want to know which register user select, how can I do it?

**Comment by kisvegabor** [comment]
Hi,

I've just updated to docs to mention how the get the selected sell.

Unfortunately, there is no built-in support to limit which cell can be selected. However, it really would be a useful feature.
Are you interested in contributing with this feature?
