### ISSUE TITLE
Event callback deleted objects

### ISSUE THREAD

**Issue by MsTS96** [kisvegabor/lvgl#2752]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

  Because of limited memory,when i switch another page, i will release current page's obj (call lv_group_remove_obj() and lv_obj_del()) . And than create new page . But the callback function of the deleted object will still be called . This will cause a null pointer.

### To Reproduce

```c
/* label event cb fun */
static void label_event_handler(lv_obj_t * obj, lv_event_t event)
{
    //printf("in event: %d\n",event);
    switch (event) {
    case LV_EVENT_CLICKED:
        if(obj == menu_param_label)
        {
            ui_menu_delete(); //delete current page release obj
            ui_menu_param_show(); //create new page
        }
        break;
    case LV_EVENT_CANCEL:
        ui_menu_delete();
        ui_main_show();
        break;
    default:
        break;
    }
}

void ui_menu_delete()
{
    lv_group_set_editing(group, false);
    lv_group_remove_obj(menu_param_label);
    lv_group_remove_obj(menu_conf_label);
    lv_group_remove_obj(menu_maintain_label);

    lv_obj_del(menu_title);
    lv_obj_del(menu_bg); //menu_param_label is a child of menu_bg

    menu_title = NULL;
    menu_bg = NULL;
    menu_title_label = NULL;
    menu_param_label = NULL;
    menu_conf_label = NULL;
    menu_maintain_label = NULL;

    current_page = PAGE_NULL;
}
```
### Expected behavior

When I release the object, his callback should no longer be called. 
But i found through debug, at indev_keypad_proc -> lv_event_send -> lv_event_send_func ,the 0x7 (LV_EVENT_RELEASED) still called . The called obj (menu_param_label) has been released by me in ui_menu_delete and has been removed from the lv_group. I want to know why this error occurs

**Comment by kisvegabor** [comment]
Looking into LVGL's code I can't see the problem.
Can you send an example I can test in the a simulator?
