### ISSUE TITLE
move to default screen from another screen will add local styles

### ISSUE THREAD

**Issue by lee88688** [kisvegabor/lvgl#2772]
In my code, I firstly create a obj from a screen which is not `lv_scr_act`, and then use `lv_obj_set_parent` move the obj's  parent to `lv_scr_act`. this will add 2 local style props which are `x` and `y` and both zero. these local style props will block custom style props.

### To Reproduce
here is my c code, and it is besed on [lv_sim_emscripten](https://github.com/lvgl/lv_sim_emscripten).
```c
void test1() {
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_value_t value = { .num = 500 };
    lv_style_set_prop(&style, LV_STYLE_X, value);

    lv_obj_t *screen = lv_obj_create(NULL);
    lv_obj_t *obj = lv_obj_create(screen);
    lv_obj_add_style(obj, &style, 0);
    lv_obj_set_parent(obj, lv_scr_act());
    // print_obj_style_info(obj);
    //   is_local: 1, is_trans: 0, selector: 0
    //   prop: 4103, value: 0; prop: 4104, value: 0
}
```

### Expected behavior
I think changing screen will not add local styles.

**Comment by kisvegabor** [comment]
Thank you, fixed!
