### ISSUE TITLE
Text with gradient

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#2778]
How to make text with gradient? 
Do I need mask?

**Comment by embeddedt** [comment]
There is an [example of how to do it with v7](https://docs.lvgl.io/7.11/widgets/objmask.html#text-mask), but I don't think it was updated to v8. You should be able to do something very similar, but I'm not 100% sure what the equivalent API to `objmask` is in v8. I think you may have to attach an event handler and adjust the masks in there.

**Comment by kisvegabor** [comment]
Instead of `objmask` you can use `LV_EVENT_DRAW_MAIN_BEGIN` and `LV_EVENT_DRAW_MAIN_END` to add/remove the rendered mask.

**Comment by Miguel0101** [comment]
So should I create an event using LV_EVENT_DRAW_MAIN_BEGIN to draw the masked gradient on the label and leave the LV_EVENT_DRAW_MAIN_END empty?

**Comment by kisvegabor** [comment]
I've pushed an example. Meanwhile, I found a bug with horizontal gradient drawing so be sure to update lvgl too.
