### ISSUE TITLE
just a question about how to invert display a png image, is it support?

### ISSUE THREAD

**Issue by tkernelcn** [kisvegabor/lvgl#2798]
I try to invert a png image by below approach, bug the result not expected
```
                lv_opa_t intense=200;
                unsigned char r=128,g=128,b=128;
                lv_obj_set_style_img_recolor_opa(obj_img->img, intense, 0);
                lv_obj_set_style_img_recolor(obj_img->img, lv_color_make(r,g,b), 0);
```
is there any other official approach to invert the image color?
Thanks.

**Comment by kisvegabor** [comment]
There is no feature to invert the color runtime.
You can send a Feature request here https://forum.lvgl.io/c/feature-request

--

We use GitHub Issues only for development-related discussions so I close this issue.
