### ISSUE TITLE
when is the event struct freed?

### ISSUE THREAD

**Issue by lee88688** [kisvegabor/lvgl#2801]
### Introduce the problem
in my code, I want to store the `lv_event_t * e` to use it later when `lv_event_cb_t` is called. so I want to know the lifetime of the `lv_event_t ` avoid using it after it is freed. so is there a clear lifetime for event? can I control the event's release?

**Comment by mariotaku** [comment]
I think It's freed right after `lv_event_send()`. You can use userdata to store some information, why need to store it though?

**Comment by embeddedt** [comment]
> I think It's freed right after lv_event_send().

Correct. It's allocated on the stack [here](https://github.com/lvgl/lvgl/blob/85cc84ad947786bb3d4857290503047946a55c43/src/core/lv_event.c#L58-L77), so once the event callback returns it's effectively no longer valid.

**Comment by lee88688** [comment]
@mariotaku currently I'm writing a binding for javascript, the event may be called and moved to a promise or timer, so I need store it. mybe I should create a copy of it.
