### ISSUE TITLE
support input device types of watch crown.

### ISSUE THREAD

**Issue by theazet** [kisvegabor/lvgl#2808]
### Introduce the problem

Lvgl does not support input device types of watch crown.

### Examples and cases

For example, when the crown rolls, the list scrolls with the crown, or the number increases or decreases with the crown.

**Comment by kisvegabor** [comment]
An [encoder input device](https://docs.lvgl.io/master/porting/indev.html#encoder) seems like that. 

If not please open a topic for this idea in the [Feature request](https://forum.lvgl.io/c/feature-request/9) category of the Forum and describe the requirement of such input device in more detail.
