### ISSUE TITLE
How to blur background canvas?

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#2814]
How to blur background canvas with transparency?

**Comment by kisvegabor** [comment]
It should work with the alpha channel too. If you see any issues please send a code snippet to reproduce.

**Comment by Miguel0101** [comment]
> It should work with the alpha channel too. If you see any issues please send a code snippet to reproduce.

I want to blur the objects behind the canvas object.

![blur](https://user-images.githubusercontent.com/56565368/142646160-9a3a8b2a-5492-40b5-80c8-bd35d7fd22bf.jpg)

**Comment by kisvegabor** [comment]
There is no such blur feature at this moment. You can take a snapshot of the bg widget with `lv_snapshot`, and blur it with the canvas and use it as the background of your widget. 

I know it's quite cumbersome, but that's what we have now :slightly_frowning_face:

**Comment by joelsand** [comment]
This would be a great feature
