### ISSUE TITLE
Why was lv_label_set_align() removed in 8.x?

### ISSUE THREAD

**Issue by amorganPD** [kisvegabor/lvgl#2816]
### Introduce the problem

There doesn't seem to be a way to align the text for a label. Before 8.x there was lv_label_set_align(), which allowed text to be left, right, and center.

### Examples and cases

When display text on multiple lines, it would be great to have this functionality, so that text can be aligned.

### Suggested solution

Bring back lv_label_set_align().

If there is another way to do this, it is not clear.

**Comment by Miguel0101** [comment]
Use `lv_obj_set_style_text_align(label, align, LV_PART_MAIN)`. Note that in `align` you can put `LV_TEXT_ALIGN_AUTO/CENTER/LEFT/RIGHT`, before it was `LV_LABEL_ALIGN` now it is `LV_TEXT_ALIGN`.

**Comment by WebDust21** [comment]
This needs to be part of the Label reference: https://docs.lvgl.io/master/widgets/label.html
digging all over the Internet and finding all of the ways it USED to work, but the reference does not list the current way.
