### ISSUE TITLE
line issue

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [kisvegabor/lvgl#2830]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Create a line, set 3 points, set line_width to 13.
There is a little issue in connection area.
![image](https://user-images.githubusercontent.com/22284222/143203536-5e71354d-e05d-4809-a278-1f36184fe1ba.png)

**Comment by kisvegabor** [comment]
You can use the [line_rounded](https://docs.lvgl.io/master/overview/style-props.html#line-rounded) style property.
