### ISSUE TITLE
use anim to move calendar, the header doesn't move together

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [kisvegabor/lvgl#2836]
### Introduce the problem

<img width="325" alt="calendar" src="https://user-images.githubusercontent.com/22284222/143520242-1bfd3bc5-c9e7-4813-a7ad-f403c332c2a1.PNG">

**Comment by kisvegabor** [comment]
It's solved in v8.1 where the header is part of the calendar object. See [here](https://docs.lvgl.io/master/widgets/extra/calendar.html#headers).
