### ISSUE TITLE
img issue

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [kisvegabor/lvgl#2853]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
when set pivot to (0,0), set an angle. the image will be cut off in left and bottom side.

### To Reproduce
![image](https://user-images.githubusercontent.com/22284222/143996111-01407fa1-2f76-4ecf-a76f-921cef0c8931.png)

**Comment by kisvegabor** [comment]
Hi, 

thanks for the report. I've pushed a fix.
