### ISSUE TITLE
Can LVGL play video?

### ISSUE THREAD

**Issue by snailwft** [kisvegabor/lvgl#2859]
Hello, LVGL can play video? For example, I have a lot of pictures and want to play one every 30ms. Can LVGL achieve this?

**Comment by X-Ryl669** [comment]
You should ask question on the forum, not here.
If you can decode and draw each frame under 30ms then yes, LVGL can do that. Or you can use lv_ffmpeg library to play a movie file.

**Comment by kisvegabor** [comment]
Having support for a lower-level video decoder as a 3rd party library would be great but as @X-Ryl669 mentioned we only have ffmpeg now. 

@snailwft if you made any progress with it, please open a new issue or send a Pull Request.

**Comment by snailwft** [comment]
@X-Ryl669 @kisvegabor Thanks
