### ISSUE TITLE
Add dithering support in the code

### ISSUE THREAD

**Issue by X-Ryl669** [kisvegabor/lvgl#2862]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Currently, there's no dithering algorithm implemented or used in LVGL for small color depth resulting in unpleasant color banding when rendering gradients.
@kisvegabor proposed to use images [here](https://github.com/lvgl/lvgl/issues/611#issuecomment-445491855) and @beibean  proposed a generic solution that's based on style [here](https://github.com/lvgl/lvgl/issues/258#issuecomment-390573927).

The former solution implies a trick (you have to compute the dithering out of LVGL and use additional images, that consume resources). Also, this does not work for round corner gradient (like a shadow or glow effect) since the 1px wide dithering pattern stored in the image can only be stretched in one axis.

The latter solution is better, IMHO, since at least, it can be used everywhere a gradient is used, and does not require an additional object to embed and deal with in the scene.
However, the fixed dither pattern in that solution is ok for small display, but will not work very well on large display.

Ideally a true dithering algorithm like [Floyd Steinberg](https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering) should be used instead, since it's producing the best result for not much additional work. 
[Here's a comparison of different dithering algorithms](https://surma.dev/things/ditherpunk/).

### To Reproduce
See any of the issue reported above for examples of color banding.

### Expected behavior
An *average* correct gradient on low color depth display.

### Screenshots or video
ditto

**Comment by kisvegabor** [comment]
Let's continue in #2872.
