### ISSUE TITLE
How to visualize an object in another?

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#2866]
![image](https://user-images.githubusercontent.com/56565368/144281289-326c2565-66cf-4e84-86fe-a1ee7a085007.png)

**Comment by Miguel0101** [comment]
Can I do this with `lv_snapshot`?

**Comment by kisvegabor** [comment]
Yes, it should work!

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
