### ISSUE TITLE
Encoder turn throws LV_EVENT_KEY, but no way to find, which turn it was

### ISSUE THREAD

**Issue by FlashForger** [kisvegabor/lvgl#2879]
On ver. 8.0.2, dunno if this was fixed in last release, from what I read in release notes - no.

So next scenario.

```
lv_group_set_editing(lv_group_get_default(), true);
lv_obj_add_event_cb(lv_scr_act(), key_event_cb, LV_EVENT_KEY, NULL);

static void key_event_cb(lv_event_t * event)
{
	switch (lv_indev_get_key(lv_indev_get_act()))
	{
	case LV_KEY_LEFT:
		break;
	case LV_KEY_RIGHT:
		break;
	default:
		break;
	}
}
```

The lv_indev_get_act() will return encoder driver, but lv_indev_get_key only return information about encoder press, not turn. 

Yes, it is possible to get that information from event->param, but it looks kind of hacky considering event->param, being void pointer, can be anything, not just lv_key_t.

Suggestion:
In indev_encoder_proc at " /*if encoder steps or simulated steps via left/right keys*/ " write LV_KEY_LEFT/LV_KEY_RIGHT in i->proc.types.keypad.last_key. Ideally would be nice, if that variable would hold ORed information of Encoder Button and Encoder Turn, so one can process event when encoder is pressed AND turned.

**Comment by kisvegabor** [comment]
Your suggestion sounds good at first look. Can you send a Pull request to better see it?
