### ISSUE TITLE
it will failed display when define lv_disp_draw_buf_t in extern sdram 

### ISSUE THREAD

**Issue by zsjlovestudy** [kisvegabor/lvgl#2887]
it will failed display when define lv_disp_draw_buf_t in extern sdram. 

![image](https://user-images.githubusercontent.com/52393677/145551453-b020e2af-99a5-465f-9f26-d3b7fac3a3a2.png)
![image](https://user-images.githubusercontent.com/52393677/145551584-3b33de9d-1e90-4206-94be-ae4ca7ecaeb7.png)

The following is not defined in sdram, it's normal.

![image](https://user-images.githubusercontent.com/52393677/145552366-9d6f7661-aaee-4cc1-952f-f70598675272.png)
![image](https://user-images.githubusercontent.com/52393677/145551857-b0a048ec-073a-472a-bc9e-1fc899599bb0.png)

Other related codes:

![image](https://user-images.githubusercontent.com/52393677/145552627-80514cc2-0aac-4fc3-976a-d29e08d1e863.png)
![image](https://user-images.githubusercontent.com/52393677/145553077-de12eaad-e31c-48df-9677-e03d276da2bc.png)
![1639128801(2)](https://user-images.githubusercontent.com/52393677/145552546-32ff324f-1ff5-4d7c-90e3-ffff536c1c15.jpg)

I wanted to know if the external definition would speed things up, because my MCU doesn't have hardware acceleration. meanwhile, If it can speed up the display, how can you do it.

**Comment by embeddedt** [comment]
I believe using SDRAM for LVGL's internal buffer is actually more likely to slow down rendering, as SDRAM is slower to access. 

However, I would check that caching is configured correctly (if that applies), and also try enabling [memory swapping](https://github.com/lvgl/lv_port_stm32f746_disco/commit/4f7dda9792996caf965625de02b3f72155f3d461) if you are using STM32.

**Comment by zsjlovestudy** [comment]
the sdram's config should be corrected., because  These two buf are normal if lv_disp_draw_buf is be declare in internal flash.

![image](https://user-images.githubusercontent.com/52393677/145667219-694bf39b-5112-4942-9af4-9b893f68cca3.png)

**Comment by kisvegabor** [comment]
> the sdram's config should be corrected., because These two buf are normal if lv_disp_draw_buf is be declare in internal flash.

How do you know if the SDRAM is correct from that it works if the buffers are placed into the internal RAM? (You wrote internal flash but I assume it's a typo)

**Comment by zsjlovestudy** [comment]
> How do you know if the SDRAM is correct from that it works if the buffers are placed into the internal RAM? (

If when I put lv_disp_draw_buf into internal RAM, the LCD's two refresh buffers in SDRAM work fine, so I assume SDRAM is correct.  But when I put lv_disp_draw_buf into SDRAM, the LCD will be blurred.

**Comment by kisvegabor** [comment]
Maybe I misunderstood it the whole time. By `lv_disp_draw_buf` do you mean only the `lv_disp_draw_buf_t` variable?

**Comment by zsjlovestudy** [comment]
Yes, it was my inarticulation.   if  lv_disp_draw_buf_t variable is defined in sdram, the LCD will be blurred. But it will ok, if it in internal ram.

**Comment by zsjlovestudy** [comment]
> Maybe I misunderstood it the whole time. By `lv_disp_draw_buf` do you mean only the `lv_disp_draw_buf_t` variable?

Yes, it was my inarticulation. if lv_disp_draw_buf_t variable is defined in sdram, the LCD will be blurred. But it will ok, if it in internal ram.

**Comment by kisvegabor** [comment]
I see, it's event weirder. Maybe some tricky SDRAM config issue...
However this variable is only a few bytes. Why is it important to keep it in SDRAM?

**Comment by zsjlovestudy** [comment]
> I see, it's event weirder. Maybe some tricky SDRAM config issue... However this variable is only a few bytes. Why is it important to keep it in SDRAM?
If I put this variable in SDRAM, it seems to refresh much faster, and I define this variable as the screen size, my MCU is not big enough to hold that much RAM.

**Comment by kisvegabor** [comment]
To be honest I have no idea. There is nothing special in `lv_draw_buf_t`. 

I suggest asking about in the Forum. Hopefully someone already seen something like this.
