### ISSUE TITLE
Updating from 7.5 to 8.1 issue(s) - Help please

### ISSUE THREAD

**Issue by elgerg** [kisvegabor/lvgl#2895]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Trying to update from 7.5 to 8.1 and having issues like:

App/App.c:240:5: error: unknown type name ‘lv_tabview_ext_t’; did you mean ‘lv_tabview_t’?
  240 |     lv_tabview_ext_t * ext = (lv_tabview_ext_t *)lv_obj_get_ext_attr(tabView); 

### To Reproduce
```c
    lv_tabview_ext_t * ext = (lv_tabview_ext_t *)lv_obj_get_ext_attr(tabView);
    const char * tab_name  = ext->tab_name_ptr[lv_tabview_get_tab_act(tabView)];

    if(strcmp(tab_name, LV_SYMBOL_HOME) == 0) {
        showMenuTime = false;
    } else {
        showMenuTime = true;
    }
```

### Expected behavior
I would have hoped that it would work but there have been chances that are not backwards compatible. 

Is there an upgrade guide that I can follow that has the old types and names to the new ones?

**Comment by elgerg** [comment]
hi,

The next one is tables.
In 7.5 the corners were rounded, in 8.1 they are not. How do I enable rounding so the table looks the same as the "object" next to it?
![2021-12-17-214132_1920x1080_scrot](https://user-images.githubusercontent.com/24628571/146611310-46f0598f-0908-4859-9e6a-e21aa1bb324a.png)
Thanks!

**Comment by elgerg** [comment]
Next,

In 7.5 I managed to get rid of the scroll bar on the right:
![2021-12-17-215006_1920x1080_scrot](https://user-images.githubusercontent.com/24628571/146612108-c1cae460-e746-4e90-8849-c71731dc7aa0.png)
How do i do that in 8.1?
Thanks

**Comment by elgerg** [comment]
Same with the scrollbar at the bottom here:
![2021-12-17-224928_1920x1080_scrot](https://user-images.githubusercontent.com/24628571/146616698-da5b2155-7f79-49e3-a2fc-d955f9fcc96a.png)

**Comment by elgerg** [comment]
Next...

In 7.5 you could create a label aligned to another item (lets say another label using align out bottom left) and then center the content using lv_label_set_align, how do you do this in 8.1?

IE:
    weatherItems[0].feels = lv_label_create(weatherPage, NULL);
    lv_obj_align(weatherItems[0].feels, weatherItems[0].dt, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 60);
    lv_label_set_long_mode(weatherItems[0].feels, LV_LABEL_LONG_BREAK);
    lv_obj_set_width(weatherItems[0].feels, 225);
    lv_label_set_align(weatherItems[0].feels, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(weatherItems[0].feels, "");

    weatherItems[0].min = lv_label_create(weatherPage, NULL);
    lv_obj_align(weatherItems[0].min, weatherItems[0].feels, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 5);
    lv_label_set_long_mode(weatherItems[0].min, LV_LABEL_LONG_BREAK);
    lv_obj_set_width(weatherItems[0].min, 225);
    lv_label_set_align(weatherItems[0].min, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(weatherItems[0].min, "");
![image](https://user-images.githubusercontent.com/24628571/146617826-2c4e9491-98cb-4f47-9acd-9ee3c6bc3174.png)

8.1;
    weatherItems[0].feels = lv_label_create(weatherPage);
    lv_obj_align_to(weatherItems[0].feels, weatherItems[0].icon, LV_ALIGN_BOTTOM_LEFT, 0, 10);
    lv_label_set_long_mode(weatherItems[0].feels, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(weatherItems[0].feels, 225);
    lv_obj_set_align(weatherItems[0].feels, LV_ALIGN_CENTER);
    lv_label_set_text(weatherItems[0].feels, "");

    weatherItems[0].min = lv_label_create(weatherPage);
    lv_obj_align_to(weatherItems[0].min, weatherItems[0].feels, LV_ALIGN_BOTTOM_LEFT, 0, 10);
    lv_label_set_long_mode(weatherItems[0].min, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(weatherItems[0].min, 225);
    lv_obj_set_align(weatherItems[0].min, LV_ALIGN_CENTER);
    lv_label_set_text(weatherItems[0].min, "");
![2021-12-17-230823_1920x1080_scrot](https://user-images.githubusercontent.com/24628571/146617901-62bb5f94-51d3-4d07-b841-1b63120536ba.png)



Thanks

**Comment by elgerg** [comment]
Next one..

How do I change the buttons to look like they used to?

7.5:
![image](https://user-images.githubusercontent.com/24628571/146619287-fb96c9f9-6144-4c3d-80d6-01faef01d8f0.png)

8.1:
![2021-12-17-233245_1920x1080_scrot](https://user-images.githubusercontent.com/24628571/146619340-3838136b-a289-4970-b673-6ace6e039886.png)

The utton sizes look better but I dont like the blue...

Thanks

**Comment by elgerg** [comment]
What is the 8.1 equivalent of lv_switch_on ?

**Comment by elgerg** [comment]
Next...

What is the 8.1 for lv_cont_set_fit2 ?

**Comment by elgerg** [comment]
@kisvegabor any pointers would be appreciated.
Thanks!
Alex

**Comment by kisvegabor** [comment]
Hi,

These questions are really relevant and there is no such a details migration guide at this moment. We have only [this short summary](https://docs.lvgl.io/master/CHANGELOG.html#v8-0-0-01-06-2021) now. I'd be happy to update it based on your questions. 

However, we use GitHub for development related discussion. Please ask these question in the Forum and add the topic's link here. I'll answer all the questions in the Forum.

**Comment by elgerg** [comment]
Table corners:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-table-corners/7645

**Comment by elgerg** [comment]
Buttons:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-buttons/7656

**Comment by elgerg** [comment]
Table cell colouring:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-table-cell-colours/7658

**Comment by elgerg** [comment]
Tabview padding:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-tabview-padding/7659

**Comment by elgerg** [comment]
Remove tab outline:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-tabview-outline/7660

**Comment by elgerg** [comment]
Table cell alignment:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-table-cell-align-lv-table-set-cell-align/7674

**Comment by elgerg** [comment]
Table behaving oddly:
https://forum.lvgl.io/t/migrating-from-7-5-to-8-1-table-behaving-odd/7675
