### ISSUE TITLE
lv_cont_create replacement in 8.1

### ISSUE THREAD

**Issue by elgerg** [kisvegabor/lvgl#2899]
### Perform all steps below and tick them with [x]
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I am (was) using:
lv_cont_create(lv_disp_get_scr_act(NULL), NULL);
but that doesnt work in 8.1
What is the replacement for this in 8.1?

### To Reproduce
```c
lv_cont_create(lv_disp_get_scr_act(NULL), NULL);
```

### Expected behavior
Creation of a container

**Comment by Miguel0101** [comment]
Use `lv_obj_create`. Now the `lv_cont` function has been replaced by `lv_obj`.

**Comment by kisvegabor** [comment]
> Use lv_obj_create. Now the lv_cont function has been replaced by lv_obj.

Confirmed.

**Comment by elgerg** [comment]
Thanks, is the same for pages?

Thanks
Alex

**Comment by embeddedt** [comment]
Yes; scrolling is now part of `lv_obj` as well.

**Comment by shahawi-sumup** [comment]
@embeddedt 
Could you kindly add this important information somewhere in the docs. 
this issue was the only place which mentions this change.
Thanks in advance

**Comment by embeddedt** [comment]
@shahawi-sumup I believe it was mentioned in the release changelog for v8 [here](https://docs.lvgl.io/master/CHANGELOG.html#widget-changes).

> lv_page removed, scroll features are moved to lv_obj

**Comment by shahawi-sumup** [comment]
@embeddedt Thank you, sorry overlooked it.
