### ISSUE TITLE
distorted pixel lines at animation, STM32F (glitched rendering)

### ISSUE THREAD

**Issue by epikao** [kisvegabor/lvgl#2903]
Hello

I have always distorted pixel lines with your examples, especially with animations, see pictures below. I have no idea why, but I think it could be because of the driver-code?

I already use latest lvgl version 8.1.0

![IMG_20211215_141631](https://user-images.githubusercontent.com/26655950/146193815-556c2f28-7ed3-41f8-b639-fc97c5a14e27.jpg)
![IMG_20211201_223134 (1)](https://user-images.githubusercontent.com/26655950/146193995-ec1f2a3a-deca-4006-af1f-5ec2f6a86b87.jpg)
![IMG_20211201_222904 (2)](https://user-images.githubusercontent.com/26655950/146194786-4d5d6ed6-53e3-48a8-9816-93e57a17dcb8.jpg)

**Comment by embeddedt** [comment]
I'm not 100% sure how to fix it in your case, but it looks like exactly the type of glitched rendering I see when the CPU cache is not being invalidated at the right time or isn't configured correctly.

**Comment by epikao** [comment]
> I'm not 100% sure how to fix it in your case, but it looks like exactly the type of glitched rendering I see when the CPU cache is not being invalidated at the right time or isn't configured correctly.

ok, so it looks it is more something with the STM32 setup (LTDC) and not with the driver code above?

**Comment by epikao** [comment]
solved, see: https://github.com/lvgl/lv_demos/issues/143
