### ISSUE TITLE
Upgrade documentation? 7 to 8

### ISSUE THREAD

**Issue by elgerg** [kisvegabor/lvgl#2914]
### Introduce the problem
When upgrading from 7 to 8 there are a number of changes. Is there any documentation on what should be changed. IE lv_page removed replace with lv_object. 

AND
lv_chart_set_next
becomes:
lv_chart_set_next_value

### Suggested solution
Documentation of the replacement functions.

Issue related to:
https://github.com/lvgl/lvgl/issues/2895

**Comment by kisvegabor** [comment]
See https://github.com/lvgl/lvgl/issues/2895#issuecomment-997730676
