### ISSUE TITLE
BUG report: roller stay at invalid position in lvgl v8.1

### ISSUE THREAD

**Issue by nde123456** [kisvegabor/lvgl#2916]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The roller stayed at invalid position when the LV_OBJ_EVENT_PRESS_LOST event happened.
Source code in the lv_roller.c:
```c
else if(code == LV_EVENT_RELEASED ) {
        release_handler(obj);
    }
```
It seems that LV_EVENT_PRESS_LOST should be handled here like this:
```c
else if(code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
        release_handler(obj);
    }
```
### To Reproduce

```c
     lv_obj_t *roller1 = lv_roller_create(lv_scr_act());
     lv_obj_clear_flag(roller1, LV_OBJ_FLAG_PRESS_LOCK);
```
Drag the roller to the position between two string, for example "3" and "4",  and then slide out of the roller. It should stay at "3" or "4", not just stay at somewhere between "3" and "4".

### Expected behavior

The roller should move to valid postion when the LV_EVENT_PRESS_LOST event happened.

**Comment by kisvegabor** [comment]
Thanks, I fixed as you have suggested.
