### ISSUE TITLE
how to clear a list? lv_list_create

### ISSUE THREAD

**Issue by bosiden** [kisvegabor/lvgl#2917]
### Introduce the problem
How to clear a list created using lv_list_create on v8? On V7 we had lv_list_clean, now it disappeared and documentation doesn't mention anything about it or an alternative way to clear/clean a list

### Suggested solution
A method to clear a created list?

**Comment by embeddedt** [comment]
Use `lv_obj_clean`. https://forum.lvgl.io/t/lv-obj-clean-on-list-widgets/5394/2?u=embeddedt

----------------------
We use GitHub issues for development-related discussions.
Please use the [forum](https://forum.lvgl.io/) to ask questions.
