### ISSUE TITLE
V8 couple of functions with parameters different in header

### ISSUE THREAD

**Issue by xennex22** [kisvegabor/lvgl#2922]
https://github.com/lvgl/lvgl/blob/01daed356a4eb540de77956f6c6d0ba86c4969b9/src/extra/layouts/flex/lv_flex.c#L57-L58
https://github.com/lvgl/lvgl/blob/01daed356a4eb540de77956f6c6d0ba86c4969b9/src/extra/layouts/flex/lv_flex.c#L317-L318

https://github.com/lvgl/lvgl/blob/01daed356a4eb540de77956f6c6d0ba86c4969b9/src/extra/widgets/tileview/lv_tileview.h#L51
https://github.com/lvgl/lvgl/blob/01daed356a4eb540de77956f6c6d0ba86c4969b9/src/extra/widgets/tileview/lv_tileview.c#L65

**Comment by kisvegabor** [comment]
Hi,

Thanks for reporting it. Could you open a PR?
