### ISSUE TITLE
Switch state setting/clearing documentation incorrect

### ISSUE THREAD

**Issue by elgerg** [kisvegabor/lvgl#2927]
https://docs.lvgl.io/8.1/widgets/core/switch.html
states to get/set the switch state use:
lvobj_add/clear_state(switch, LV_STATE_CHECKED)

This should be:
lv_obj_add/clear_state(switch, LV_STATE_CHECKED) 

With the missing underscore. 

It would be easier if it read:
lv_obj_add_state(switch, LV_STATE_CHECKED) 
and
lv_obj_clear_state(switch, LV_STATE_CHECKED)

Thanks!
Alex

**Comment by elgerg** [comment]
Oh and:
To get the current satte of the switch
should be:
To get the current state of the switch

**Comment by kisvegabor** [comment]
Thanks! Could you send a PR?
