### ISSUE TITLE
performance monitor label bug

### ISSUE THREAD

**Issue by xennex22** [kisvegabor/lvgl#2932]
There is a bug in commit https://github.com/lvgl/lvgl/commit/6e00724797caf63deff0a46abeb5506650f88afe for issue https://github.com/lvgl/lvgl/pull/2910

`perf_monitor.perf_label` is never going to created because a local variable is assigned the value and the static struct never updated.
https://github.com/lvgl/lvgl/blob/28d06b03543a9c809d22784f9648607a2f369585/src/core/lv_refr.c#L281-L283
I've fixed this on my forked copy but can't do a PR while there is already an outstanding PR.

**Comment by xennex22** [comment]
Also I see the same problem for the mem_monitor
https://github.com/lvgl/lvgl/blob/28d06b03543a9c809d22784f9648607a2f369585/src/core/lv_refr.c#L330-L332

**Comment by mysterywolf** [comment]
https://github.com/lvgl/lvgl/pull/2910#issuecomment-998056654
https://github.com/lvgl/lvgl/pull/2910#issuecomment-998508245

**Comment by kisvegabor** [comment]
Thanks, I've pushed a fix.
