### ISSUE TITLE
Custom blend mode about commit db53ea92

### ISSUE THREAD

**Issue by mariotaku** [kisvegabor/lvgl#2934]
### Introduce the problem

> @mariotaku I've just discovered this new blend mode. Is it really required? I'm asking because it's much slower to draw with a non-normal blending mode and it'd important to draw these screen sized parts as fast as possible.

### Examples and cases

Let's assume this case:
One app is an OSD app. It has translucent background. For each frame, the part where redrawn is needed will have to clear the whole buffer, then draw `lv_disp_t.bg_color` with opacity (or completely transparent).

### Suggested solution

 For this case, drawing backend doesn't know if the rect is the bottom-most display background, so it has to be drawn in this way, or, introduce another field called `is_disp_bg` for example for drawer to handle.

**Comment by kisvegabor** [comment]
Thanks, let's continue in the PR.
