### ISSUE TITLE
bug in recent commits

### ISSUE THREAD

**Issue by mysterywolf** [kisvegabor/lvgl#2938]
![1640227291(1)](https://user-images.githubusercontent.com/34888354/147179873-aba642fc-43da-4fdc-8b9e-12becccd574a.png)

LVGL latest code

running the music player demo

Yesterday, when I use the latest version's code to simulate. It is good. However, today, I use the latest version code to simulate, it crashed. I think this bug is caused by these recent commits.

**Comment by kisvegabor** [comment]
I've just fixed it here: https://github.com/lvgl/lvgl/issues/2943

**Comment by mysterywolf** [comment]
Thank you~
