### ISSUE TITLE
v8.1 function bug：spectrum_draw_event_cb(lv_event_t * e)   

### ISSUE THREAD

**Issue by W00ng** [kisvegabor/lvgl#2943]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
static void spectrum_draw_event_cb(lv_event_t * e)
line 837：    lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
should be： lv_draw_polygon(clip_area, &draw_dsc, poly, 4);
-->

**Comment by kisvegabor** [comment]
Thanks, I fixed it here: 92016ccac
