### ISSUE TITLE
How to remove sliding in tabview

### ISSUE THREAD

**Issue by alec-2018** [kisvegabor/lvgl#2945]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Expected behavior

Can I use the tabview widget of lvgl to achieve such an effect? I tried lv_example_tabview_2, but this example needs to be clicked and cannot be swiped;

### Screenshots or video

https://user-images.githubusercontent.com/40708750/147534452-a48252c6-6412-4e0a-a1b0-8283468c5a92.mp4

**Comment by kisvegabor** [comment]
You can use gestures as described here: https://docs.lvgl.io/master/overview/indev.html#gestures

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
