### ISSUE TITLE
lv_img_create() and lv_img_set_src() not working with commit 'allow replacing the draw engine'

### ISSUE THREAD

**Issue by NeroBurner** [kisvegabor/lvgl#2948]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version (yes done with git bisect)
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)
  - yes, doing it porting Infinitime to LVGL8 and using a pc-simulator based on https://github.com/lvgl/lv_sim_eclipse_sdl

### Describe the bug

`lv_img` is broken (random noise instead of image) on PineTime and Simulator starting with db53ea925c9502b20f38db0fc30c4ef599bdfc33

The commit before is fine

### To Reproduce

```c
const lv_img_dsc_t disc = /* picture-array-definition */;
lv_obj_t* imgDisc = lv_img_create(lv_scr_act());
lv_img_set_src(imgDisc, &disc);
```

### Expected behavior
image should be shown as before

### Screenshots or video

screenshot with 0831b6ba761bf68e535a158ff93ef3551d2bd108

![working](https://user-images.githubusercontent.com/9076163/147794047-fc6137c1-fbee-4593-a758-486f39468a1b.png)

screenshot with db53ea925c9502b20f38db0fc30c4ef599bdfc33

![garbled](https://user-images.githubusercontent.com/9076163/147794132-657746c1-860a-4a35-a777-c39d049e8d93.png)

edit: fix the example code by replacing `lv_img_set_src_arr` with `lv_img_set_src`

**Comment by kisvegabor** [comment]
Hi,

`lv_img_set_src_arr` is not a lvgl function. Did you mean `lv_img_set_src`?

Please send the converted image too that you want to set.

**Comment by NeroBurner** [comment]
yes, sorry, the `_arr` function was an internal wrapper for the `lv_img_set_src` function

The original png file:

![disc](https://user-images.githubusercontent.com/9076163/147943068-e9aa2818-4d8f-4810-8e60-3beb29af7114.png)

cpp-file can be found at https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/src/displayapp/icons/music/disc.cpp and also uploaded here and extended with `.txt` (GitHub has a file extension filter). 
[disc.cpp.txt](https://github.com/lvgl/lvgl/files/7802444/disc.cpp.txt)

Should I convert the declaration to a pure C file or is the C++ file OK?

**Comment by kisvegabor** [comment]
Thanks, I've fixed it in 109255077 and 5a0dbccf8.

Please, test it and let me know if it works on your end too.

**Comment by NeroBurner** [comment]
works like a charm, thank you very much! :)

**Comment by kisvegabor** [comment]
Great, thanks for the feedback! :slightly_smiling_face:
