### ISSUE TITLE
size check error in lv_canvas_copy_buf

### ISSUE THREAD

**Issue by gagarinlg** [kisvegabor/lvgl#2949]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
when calling lv_canvas_copy_buffer in a way, that the buffer is to be drawn at the right edge of the canvas, the out of canvas check triggers, though it should not.

### Expected behavior
It should be possible to copy a buffer to the right edge of the screen

**Comment by kisvegabor** [comment]
#2950 is merged so I close this issue.

Thank you for the fix!
