### ISSUE TITLE
Load font from flash in place

### ISSUE THREAD

**Issue by wangyz1997** [kisvegabor/lvgl#2953]
### Introduce the problem

Hi. Thanks for your wonderful project. I'm using lvgl with ESP32, and I want to add Chinese font support. However, since Chinese font is rather large, if I put it inside the code as a const struct, every time downloading the code will cost much more time. I notice that lvgl provides a method to load binary font file from filesystem. But it seems to read out and put the structured font into RAM, which is insufficient on MCU. So, I'm wondering if there would be a font loader which loads binary font file in place.

### Examples and cases

None.

### Suggested solution

None so far.

**Comment by kisvegabor** [comment]
Hi,

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

Feel free to post the link of the forum topic here, and I will respond there.
