### ISSUE TITLE
LVGL STM32H745I-Disco Porting

### ISSUE THREAD

**Issue by ahmetalperenbulut** [kisvegabor/lvgl#2954]
Hi All,
I'm developing applications with LVGL using STM32H7. I've completed porting issue and demo applications work very well. Could you create a repo as lv_port_stm32h745i_disco ?

**Comment by kisvegabor** [comment]
Hi,

Thank you very much!

I've just create the repo and sent an invitation to you. 
https://github.com/lvgl/lv_port_stm32h745i_disco

**Comment by ahmetalperenbulut** [comment]
Thanks kisvegabor
