### ISSUE TITLE
need some suggestion about theme

### ISSUE THREAD

**Issue by Juou123** [kisvegabor/lvgl#2958]
### Introduce the problem

I need 2 or more styles of label which is different in main menu , sub menu, setting menu and so on. 
Because now theme is be set style of label class by 1 style, how can i use different style about label class ?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
