### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by xaowang96** [kisvegabor/lvgl#2962]
When i set LV_COLOR_SCREEN_TRANSP enabled, i got a compile error, like this

![截屏2022-01-05 下午3 49 58](https://user-images.githubusercontent.com/32351888/148180877-adec2d90-4ac5-4601-b4a8-8f3e69fbb187.png)

**Comment by kisvegabor** [comment]
It should be fixed in the latest master version.

**Comment by xaowang96** [comment]
> It should be fixed in the latest master version.

Thanks for it. By the way, about what time is it?

**Comment by kisvegabor** [comment]
In db53ea925c [here](https://github.com/lvgl/lvgl/commit/db53ea925c9502b20f38db0fc30c4ef599bdfc33#diff-f48aa9733ddf89ef69050e3d54cb14b09a8fcf19c6a949b3d35d24621c335175R42-R44).

**Comment by xaowang96** [comment]
> In [db53ea9](https://github.com/lvgl/lvgl/commit/db53ea925c9502b20f38db0fc30c4ef599bdfc33) [here](https://github.com/lvgl/lvgl/commit/db53ea925c9502b20f38db0fc30c4ef599bdfc33#diff-f48aa9733ddf89ef69050e3d54cb14b09a8fcf19c6a949b3d35d24621c335175R42-R44).

Ok.

**Comment by kisvegabor** [comment]
Please test if it really works on your end too so that we can close this issue.

**Comment by xaowang96** [comment]
> Please test if it really works on your end too so that we can close this issue.

Sorry for keeping you waiting, i tested everything ok.

**Comment by embeddedt** [comment]
Great!
