### ISSUE TITLE
Horizontal subpixel rendering font is not displaying properly

### ISSUE THREAD

**Issue by sam0910** [kisvegabor/lvgl#2975]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Horizontal subpixel rendering font is not displaying properly.
This happens only when I checked horizontal subpixel rendering option.
If I add a few labels, only some of them displays strange or disappear.
I tried roboto and noto sans fonts, results are same.

please note the screen shot. 

I am using,
* Micropython port (freezing font files)
* Check the "Horizontal subpixel rendering" on font convertor.
* 4 bpp, size 40px
* LV_USE_FONT_SUBPX 1
* Display drv is gc9a01

### To Reproduce
```c
disp = gc9a01(
    ...
    width=240,
    height=240,
    power_on=0,
    half_duplex=False,
    asynchronous=True,
    # rot=LANDSCAPE,
    hybrid=True,
    colormode=COLOR_MODE_BGR,
)

fonts = lv.font_36n
label1 = lv.label(lv.scr_act())
label1.set_text("456")
label1.set_style_text_align(lv.ALIGN.CENTER, 0)
label1.align(lv.ALIGN.CENTER, -40, 0)
label1.set_style_text_font(fonts, 0)

label2 = lv.label(lv.scr_act())
label2.set_text("456")
label2.set_style_text_align(lv.ALIGN.CENTER, 0)
label2.align(lv.ALIGN.CENTER, 40, 0)
label2.set_style_text_font(fonts, 0)
```

![20220107_204836](https://user-images.githubusercontent.com/9714538/148541235-148745be-0d9b-4102-b074-84cfb8af833e.jpg)

**Comment by kisvegabor** [comment]
Hi,

Can you reproduce it in a C simulator on desktop?

**Comment by sam0910** [comment]
I am not familiar with C, but I've tried install both linux sim and platformio.
But I could not even execute it.

**Comment by kisvegabor** [comment]
Take look at this list of the simulators: https://docs.lvgl.io/master/get-started/pc-simulator.html#select-an-ide
You can find one that is easy to use on your OS.

**Comment by geert-KLA-BE** [comment]
I have stumped into the same issue. It has very weird behavior. The things I noticed after a week searching for the cause:
 - I can only see it  on my target with optimisation turned on (> -O0 )
 - I can hide the issue if I compile lv_font.c with -O0
 - Sometimes only part of a label is shown, sometimes it isn't shown, sometimes it works ok after refresh
 - Changing some not related code can make it appear and disappear
 - Enabling it on a specific font makes it appear only on labels using that font

I am using an STM32F4 with the latest official ARM gcc compiler

**Comment by kisvegabor** [comment]
Which LVGL version do you use?

**Comment by geert-KLA-BE** [comment]
I am using release version 8.2.

**Comment by sam0910** [comment]
That is exactly same as me. 
Some case with different position it shows, some is not.

**Comment by kisvegabor** [comment]
I have an STM32F412-Discovery board. If you also have this board, it'd be great if could send a project to reproduce the issue. If not, please send a `c` file and the converted font. Having these files I hope I can reproduce the issue.

**Comment by kctan0805** [comment]
I cannot show any text on my platform. I reference draw_letter_normal() found that draw_letter_subpx() lacks adding
blend_dsc.mask_res = LV_DRAW_MASK_RES_CHANGED;
before calling lv_draw_sw_blend(...);
after adding it I fixed my problem.
Should I send a PR?

**Comment by kisvegabor** [comment]
Great! Yes, please send a PR.
