### ISSUE TITLE
Minimal configuration in Kconfig not working as expected.

### ISSUE THREAD

**Issue by tejlmand** [kisvegabor/lvgl#2976]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [Not applicable] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html).

### Describe the bug

The Kconfig code here doesn't really create a minimal configuration which a user might expect.
https://github.com/lvgl/lvgl/blob/27fbf3c0e6f9f5b9cdea5cc65c64cc08e81b1696/Kconfig#L12-L13

Instead it means a different set of defaults which is not the same as a minimal configuration.

For example it suffers from the stuck symbol syndrome:
https://docs.zephyrproject.org/latest/guides/build/kconfig/tips.html#stuck-symbols-in-menuconfig-and-guiconfig

This can be tested when using this file together with Zephyr, for example:
```
$ cmake -GNinja -DBOARD=mimxrt1050_evk -Bbuild samples/hello_world/ -DCONFIG_LVGL=y

# Open menuconfig:
$ ninja -Cbuild menuconfig

# Navigate to: `Additional libraries → LittlevGL GUI library → LVGL configuration`
# Enable '[*] LVGL minimal configuration.'
```
and then check that the value of `LV_USE_ASSERT_NULL` is still enabled despite the fact that Minimal configuration has just been enabled.
https://github.com/lvgl/lvgl/blob/27fbf3c0e6f9f5b9cdea5cc65c64cc08e81b1696/Kconfig#L300-L302

See also following discussion: https://github.com/zephyrproject-rtos/zephyr/pull/41336#discussion_r779490147

### To Reproduce
```
$ cmake -GNinja -DBOARD=mimxrt1050_evk -Bbuild samples/hello_world/ -DCONFIG_LVGL=y

# Open menuconfig:
$ ninja -Cbuild menuconfig

# Navigate to: `Additional libraries → LittlevGL GUI library → LVGL configuration`
# Enable '[*] LVGL minimal configuration.'
```
and then check that the value of `LV_USE_ASSERT_NULL` is still enabled despite the fact that Minimal configuration has just been enabled.
https://github.com/lvgl/lvgl/blob/27fbf3c0e6f9f5b9cdea5cc65c64cc08e81b1696/Kconfig#L300-L302

### Expected behavior
Selecting minimal configuration should result in a minimal configuration, and not the same configuration that is already active.

**Comment by kisvegabor** [comment]
Hi,

I see the problem. Back then `LV_CONF_MINIMAL` was introduced especially for Zephyr. I'm not sure it worked like this that days though. So if you have a Zephyr specific idea as solution, please let us know!

I've checked the suggested solution on the [LINK](https://docs.zephyrproject.org/latest/guides/build/kconfig/tips.html#stuck-symbols-in-menuconfig-and-guiconfig) you have a posted but none of them seems to apply here.

Finally, is it important to support changing `LV_CONF_MINIMAL`? Isn't it enough to have 2 Kconfigs: a minimal and a "normal" one? Projects like Zephyr could use the minimal, and others the normal. I wouldn't like to duplicate the Kconfig file, just want to know if can start to think this way.
