### ISSUE TITLE
Documentation does not match code

### ISSUE THREAD

**Issue by Satnet** [kisvegabor/lvgl#2980]
Documentation speaks of icon as well when it comes to adding text to already existing item. This is not the case in code.

https://docs.lvgl.io/8.0/widgets/extra/list.html?highlight=lv_list_add_text
https://docs.lvgl.io/8.1/widgets/extra/list.html?highlight=lv_list_add_text
https://github.com/lvgl/lvgl/blob/0a5a07278ec995938772a2b87526eb571c9c5d36/src/extra/widgets/list/lv_list.c#L65

**Comment by kisvegabor** [comment]
Thanks, I fixed it in `master`, `release/v8.0` and `release/v8.1` too.
