### ISSUE TITLE
The slider is displayed abnormally

### ISSUE THREAD

**Issue by Johnxjj** [kisvegabor/lvgl#2981]
* fix(bidi) fix the handling of LV_BASE_DIR_AUTO in several widgets
2021/8/3 22:02:22

I noticed that after this one modification point, my slider is displayed abnormally.
![IMG_20220110_154118](https://user-images.githubusercontent.com/18185301/148732153-41ddd445-3f3f-4b2f-80f9-65771fb5e345.jpg)
![IMG_20220110_154136](https://user-images.githubusercontent.com/18185301/148732166-065f6c08-0334-4b73-b398-fee9ad3e0c9b.jpg)

**Comment by kisvegabor** [comment]
Is it solved somehow? Please describe in a few words what happened to help other user who find this issue.
