### ISSUE TITLE
Duplicated content in 'optional fields' section

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#2983]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
There is duplicated content in the ['optional fields' section](https://docs.lvgl.io/master/porting/display.html#optional-fields)

![image](https://user-images.githubusercontent.com/13148491/148771753-22a94cbd-0b79-4efe-a338-0b6f5b3b9fe0.png)

Here the 'user_data' line is duplicated.

**Comment by GorgonMeducer** [comment]
https://github.com/lvgl/lvgl/pull/2984

**Comment by kisvegabor** [comment]
Fixed by #2984.

**Comment by GorgonMeducer** [comment]
Thank you.
