### ISSUE TITLE
Pre-processing Event 

### ISSUE THREAD

**Issue by X-Ryl669** [kisvegabor/lvgl#2985]
### Introduce the problem
Right now, it's not possible to pre-process an event, so whatever we attach to an object, it'll always happen after the object as dealt with it.
For example, let's say you don't want a switch button not to go into its checked state when pressed and released, the only option is to maintain your own state tracking of the button.

In other GUI frameworks, you usually attach an event listener that's executed first and then prevent the event from continuing processing since you've dealt with it. (à la `e.preventDefault()` or `stopPropagation()`)

It won't be hard to add in LVGL so I'm wondering why it's not there.

### Examples and cases
Right now, the event processing code is doing this:
```cpp
lv_res_t lv_obj_event_base(const lv_obj_class_t * class_p, lv_event_t * e)
{
    const lv_obj_class_t * base;
    if(class_p == NULL) base = e->current_target->class_p;
    else base = class_p->base_class;

    /*Find a base in which call the ancestor's event handler_cb if set*/
    while(base && base->event_cb == NULL) base = base->base_class;

    if(base == NULL) return LV_RES_OK;
    if(base->event_cb == NULL) return LV_RES_OK;

    /*Call the actual event callback*/
    e->user_data = NULL;
    base->event_cb(base, e);

    lv_res_t res = LV_RES_OK;
    /*Stop if the object is deleted*/
    if(e->deleted) res = LV_RES_INV;

    return res;
}

static lv_res_t event_send_core(lv_event_t * e)
{
    EVENT_TRACE("Sending event %d to %p with %p param", e->code, (void *)e->current_target, e->param);

    /*Call the input device's feedback callback if set*/
    lv_indev_t * indev_act = lv_indev_get_act();
    if(indev_act) {
        if(indev_act->driver->feedback_cb) indev_act->driver->feedback_cb(indev_act->driver, e->code);
        if(e->deleted) return LV_RES_INV;
    }

    lv_res_t res = LV_RES_OK;
    res = lv_obj_event_base(NULL, e);

    lv_event_dsc_t * event_dsc = res == LV_RES_INV ? NULL : lv_obj_get_event_dsc(e->current_target, 0);

    uint32_t i = 0;
    while(event_dsc && res == LV_RES_OK) {
        if(event_dsc->cb && (event_dsc->filter == LV_EVENT_ALL || event_dsc->filter == e->code)) {
            e->user_data = event_dsc->user_data;
            event_dsc->cb(e);

            /*Stop if the object is deleted*/
            if(e->deleted) return LV_RES_INV;
        }

        i++;
        event_dsc = lv_obj_get_event_dsc(e->current_target, i);
    }

    if(res == LV_RES_OK && e->current_target->parent && event_is_bubbled(e)) {
        e->current_target = e->current_target->parent;
        res = event_send_core(e);
        if(res != LV_RES_OK) return LV_RES_INV;

    }

    return res;
}
```
In pseudo code, it's checking if there's a device filter and then it calls the class's event processing loop and finally the event descriptor's list.

### Suggested solution
We can add a preprocess member to the event list to indicate if it has to be processed first, and slighty change the loop like this:
```cpp
static lv_res_t event_send_core(lv_event_t * e)
{
    EVENT_TRACE("Sending event %d to %p with %p param", e->code, (void *)e->current_target, e->param);

    /*Call the input device's feedback callback if set*/
    lv_indev_t * indev_act = lv_indev_get_act();
    if(indev_act) {
        if(indev_act->driver->feedback_cb) indev_act->driver->feedback_cb(indev_act->driver, e->code);
        if(e->deleted) return LV_RES_INV;
    }

    lv_res_t res = LV_RES_OK;
    lv_event_dsc_t * event_dsc = res == LV_RES_INV ? NULL : lv_obj_get_event_dsc(e->current_target, 0);
    
    /*Preprocess event set first*/
    uint32_t i = 0;
    while(event_dsc && event_dsc->pre && res == LV_RES_OK) {
        if(event_dsc->pre && event_dsc->cb && (event_dsc->filter == LV_EVENT_ALL || event_dsc->filter == e->code)) {
            e->user_data = event_dsc->user_data;
            event_dsc->cb(e);

            /*Stop if the object is deleted*/
            if(e->deleted) return LV_RES_INV;
        }

        i++;
        event_dsc = lv_obj_get_event_dsc(e->current_target, i);
    }

    /*Call class processing*/
    res = lv_obj_event_base(NULL, e);

    /*Continue processing postprocess events*/
    while(event_dsc && res == LV_RES_OK) {
        if(event_dsc->cb && (event_dsc->filter == LV_EVENT_ALL || event_dsc->filter == e->code)) {
            e->user_data = event_dsc->user_data;
            event_dsc->cb(e);

            /*Stop if the object is deleted*/
            if(e->deleted) return LV_RES_INV;
        }

        i++;
        event_dsc = lv_obj_get_event_dsc(e->current_target, i);
    }

    if(res == LV_RES_OK && e->current_target->parent && event_is_bubbled(e)) {
        e->current_target = e->current_target->parent;
        res = event_send_core(e);
        if(res != LV_RES_OK) return LV_RES_INV;

    }

    return res;
}
```

A new function needs to be added to add preprocess events (it must be pushed to the head of the list), or normal events (added to the tail of the list).
Also, maybe it's worth changing the signature of the preprocess event callback to have them return a `lv_res_t` (with `LV_RES_OK` meaning continue processing and `LV_RES_INV` to stop processing immediately on return), as it'll be cleaner than setting `e->deleted` to 1

What do you think ?

**Comment by kisvegabor** [comment]
> What do you think ?

I have slightly different ideas of the implementation but in general I definitely agree.

>  if(event_dsc->pre ...

I'd use an ORed value to the event code. E.g.
```c
lv_obj_add_event_cb(obj, my_cb, LV_EVENT_CLICKED | LV_EVENT_PREPROCESS, NULL);
```

> A new function needs to be added to add preprocess events (it must be pushed to the head of the list), or normal events (added to the tail of the list).

As there are only a few events (mostly 1, rarely more than 3), it seems like a unnecessary optimization. 

> Also, maybe it's worth changing the signature of the preprocess event callback to have them return a lv_res_t (with LV_RES_OK meaning continue processing and LV_RES_INV to stop processing immediately on return), as it'll be cleaner than setting e->deleted to 1

Explicit function calls are cleaner IMO and we can do more things with them. You have mentioned `e.preventDefault()` and `stopPropagation()`. I like this approach more. In our case:
```c
lv_event_stop_bubbling(e);  //e->stop_bubbling=0;
lv_event_stop_processing(e);  //e->stop=0;    better name?
```
