### ISSUE TITLE
do you have plan to add cmsis-pack for lvgl

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#2986]
### Introduce the problem
It appears that currently there is no official cmsis-pack for lvgl. Do you have a plan to create one?
I can contribute one if you don't mind.

**Comment by kisvegabor** [comment]
Hi,

I don't know `cmsis-pack` but from the docs it seems interesting. I've read the basics from [here](https://www.keil.com/pack/doc/CMSIS/Pack/html/index.html) but still have a two main questions:
- What projects/IDEs/SDKs are using `cmsis-pack`?
- How do we need to maintain the pack?  

> I can contribute one if you don't mind.

Thanks for offering your help!

**Comment by GorgonMeducer** [comment]
For now, MDK and IAR are using cmsis-pack.
The way to maintain the pack is that:
a. every time you want to release an lvgl version, you might want to update the pack
b. you might put examples, code template and new platform support to cmsis-pack

Now cmsis-pack is donated to Linaro:

https://www.open-cmsis-pack.org/#:~:text=Overview,with%20Arm%2C%20NXP%20and%20ST.

>The Open-CMSIS-Pack project will deliver the infrastructure to integrate and manage software components and improve code reuse across embedded and IoT projects. The project is currently hosted and managed as an incubation project by Linaro in partnership with Arm, NXP and ST.

**Comment by kisvegabor** [comment]
> every time you want to release an lvgl version, you might want to update the pack

Does it mean simple bumping the version number in the descriptor file or publishing by hand?

**Comment by GorgonMeducer** [comment]
For most of the time, YES. Unless you have some major update that changes all file names (this happened before in LVGL), in that case, you have to update the script which we used to generate the cmsis-pack, it takes you 10mins.

**Comment by kisvegabor** [comment]
Ah, great! If it's this simple I think it'd be great to support `cmsis-pack`.

**Comment by GorgonMeducer** [comment]
Sure, I will do that. 
Here is an [example](https://github.com/GorgonMeducer/perf_counter/blob/main/GorgonMeducer.perf_counter.pdsc), you can have a look. 

For a cmsis-pack, here are immediately some questions for you:

Please fill blanks in the following code (I put mine as example):

```
  <vendor>GorgonMeducer</vendor>
  <name>perf_counter</name>
  <description>A dedicated performance counter for the Cortex-M Systick. It shares the SysTick with users' original SysTick function without interfering with it. This library will bring new functionalities, such as performance counter, delay_us and clock() service defined in time.h</description>
  <url>https://raw.githubusercontent.com/GorgonMeducer/perf_counter/CMSIS-Pack/cmsis-pack/</url>
  <supportContact>https://github.com/GorgonMeducer/perf_counter/issues</supportContact>
  <license>lib/LICENSE</license>
```

**Comment by GorgonMeducer** [comment]
One more question, I have read the 'how-to contribute', it says:
> Set the base branch. It means where you want to merge your update. In the lvgl repo fixes go to master, new features to dev branch.

But there is no such branch called 'dev':

![image](https://user-images.githubusercontent.com/13148491/148930162-728d602b-85aa-4132-9fb2-f1cdcad962b8.png)

Which branch should I use? 'master' ??

**Comment by GorgonMeducer** [comment]
First cmsis-pack is ready to review:

![image](https://user-images.githubusercontent.com/13148491/148953269-55ba8b8f-c016-4e67-8dfc-a9e6d0f96eec.png)


![image](https://user-images.githubusercontent.com/13148491/148952570-94090556-1305-4ff7-8294-d2a739abe5ef.png)

![image](https://user-images.githubusercontent.com/13148491/148953028-a0ea310a-2dd2-4a91-a8ef-d1cfbd8f6d08.png)

**Comment by GorgonMeducer** [comment]
https://github.com/GorgonMeducer/lvgl/tree/add-cmsis-pack

**Comment by GorgonMeducer** [comment]
The support for extra themes, widgets and layouts has been added:

![image](https://user-images.githubusercontent.com/13148491/148974989-1b77ad68-91de-4f9a-939b-5b091d2f0ab0.png)

**Comment by kisvegabor** [comment]
> But there is no such branch called 'dev'

Ops, it was out dated. Updated here https://github.com/lvgl/lvgl/commit/00d4ef3c53d9b53e993c76d1eb0bafa7b1c9b721.


> First cmsis-pack is ready to review:

Looks good, only one question. Can we avoid having `lv_conf_cmsis.h`? With this, if we add anything to `lv_conf.h` we need to update `lv_conf_cmsis.h` too? Are there any changes in it or is it just the default `lv_conf.h` file?

**Comment by GorgonMeducer** [comment]
lv_conf_cmsis.h was a copy of lv_conf.h, but to modularize the lvgl in the configuration view, I have to modify the original content inside lv_conf_cmsis.h.

Let me show you an example:

![image](https://user-images.githubusercontent.com/13148491/148979299-80c0fd6e-0029-4d51-97f2-819454a7d459.png)

As you can see, libs PNG is a separated module. You might immediately notice that, ideally, the macro **LV_USE_PNG** should be defined as '1' as long as the libs PNG is selected.  The problem of the original lv_conf.h is that there is no way to modify the macro automatically:

![image](https://user-images.githubusercontent.com/13148491/148979781-cc944c9e-d384-4f77-b142-30035977a7af.png)

Hence I modify it inside lv_conf_cmsis.h as you can guess:

```
/*PNG decoder library*/
#ifndef LV_USE_PNG
    #define LV_USE_PNG      0
#endif
```

and inside the script:

```
            <component Cgroup="lvgl" Csub="Libs PNG"  condition="LVGL-Essential">
              <description>Add PNG support</description>
              <files>
                <!-- src/extra/libs/png -->
                <file category="sourceC"            name="src/extra/libs/png/lodepng.c" />
                <file category="sourceC"            name="src/extra/libs/png/lv_png.c" />
              </files>
              
              <RTE_Components_h>
              
/*! \brief enable PNG support */
#define LV_USE_PNG          1
              </RTE_Components_h>
              
            </component>
```

Once people select the Lib PNG in the RTE window, the following code will be inserted to RTE_Components.h which is included by lv_conf_cmsis.h
```
/*! \brief enable PNG support */
#define LV_USE_PNG          1
```

![image](https://user-images.githubusercontent.com/13148491/148980382-89af6db7-ee92-4981-a08d-101b808b7417.png)

**Comment by GorgonMeducer** [comment]
Further more, MDK provides a simple syntax that turns any macro definitions into GUI-based configuration wizard. For example:

```
//-------- <<< Use Configuration Wizard in Context Menu >>> -----------------
//
// <h>Arm-2D General Configurations
// =======================
//
// <q>Enable Asynchronous Programmers' model support
// <i> Note that if you don't have any hardware accelerator, disable this feature can reduce code size and gain a small performance uplift.
// <i> This feature is enabled by default.
#ifndef __ARM_2D_HAS_ASYNC__
#   define __ARM_2D_HAS_ASYNC__                                     1
#endif

// <q>Enable anti-alias support for all rotation operations.
// <i> Note that enabling this feature suffers a non-negligible performance drop.
// <i> This feature is disabled by default.
#ifndef __ARM_2D_HAS_INTERPOLATION_ROTATION__
#   define __ARM_2D_HAS_INTERPOLATION_ROTATION__                    0
#endif

// <q>Enable support for accessing individual colour channels
// <i> Note that enabling this feature will add the support for a special colour type: ARM_2D_CHANNEL_8in32
// <i> This feature is disabled by default to save code size
#ifndef __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__
#   define __ARM_2D_CFG_SUPPORT_COLOUR_CHANNEL_ACCESS__             0
#endif
// </h>


// <<< end of configuration section >>>
```

Will be shown as:
![image](https://user-images.githubusercontent.com/13148491/148981344-43c729ea-29be-40b9-a9e0-dce7283cfd5f.png)

Details about this syntax can be found [here](https://arm-software.github.io/CMSIS_5/Pack/html/configWizard.html)

I have a plan to turn the lv_conf_cmsis.h into a wizard-enabled one.

**Comment by GorgonMeducer** [comment]
I believe there are other wizard-based solutions, such as the one used in menueconfig, the one used in the RT-Thread package and the one used in MDK.

An ultimate solution is:
- Write lv_conf_template.h in a machine-readable manner
- Use a script (.py?) generate lv_conf_cmsis.h and other required wizard description files.

A workaround for current lv_conf_template.h is:

- Make each macro switch override-able (so people can define a macro in a project configuration and it overrides the default value in lv_conf.h.

If you do that, lv_conf_cmsis.h will be a simple copy of the lv_conf_template.h

What do you think?

**Comment by GorgonMeducer** [comment]
LVGL.lvgl.0.7.0.pack

Almost everything inside lvgl repository:

![image](https://user-images.githubusercontent.com/13148491/148990271-cb0d3e2f-212d-4ea0-98e8-8358308daca9.png)

https://github.com/GorgonMeducer/lvgl/tree/add-cmsis-pack/cmsis-pack

If it is OK, I will generate a PR.

**Comment by kisvegabor** [comment]
> Hence I modify it inside lv_conf_cmsis.h as you can guess:
> /*PNG decoder library*/
#ifndef LV_USE_PNG
    #define LV_USE_PNG      0
#endif

In this case it's be better to simple remove `LV_USE_PNG` (and the other similar ones) as [lv_conf_internal.h](https://github.com/lvgl/lvgl/blob/master/src/lv_conf_internal.h#L1858-L1864) takes care of defining any undefined configs. 

It seems simple to write a script which copies `lv_conf_template.h` as `lv_conf_cmsis.h` and removes some config. This way we could easily and safely update `lv_conf_cmsis.h` later.

> Write lv_conf_template.h in a machine-readable manner
Use a script (.py?) generate lv_conf_cmsis.h and other required wizard description files.

Sounds good! For now let's find a workaround, but in the long term it'd be great. 

 > Make each macro switch override-able (so people can define a macro in a project configuration and it overrides the default value in lv_conf.h.

IMO It'd make `lv_conf.h` practically unreadable for the users :slightly_frowning_face: 

---

I'd have a few comments but I think it's cleaner to discuss them in a PR. So please create one. :slightly_smiling_face:

**Comment by GorgonMeducer** [comment]
No problem, let me use the workaround methods and create a PR, i.e. 
> ...remove LV_USE_PNG (and the other similar ones) as lv_conf_internal.h takes care of defining any undefined configs...

**Comment by GorgonMeducer** [comment]
https://github.com/lvgl/lvgl/pull/2993
