### ISSUE TITLE
Lack of documentation about creating/customizing lv_draw_ctx_t and lv_draw_sw_ctx_t implementations

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#2988]
### Introduce the problem
I was trying to find an official way to add 2D-HW-Acceleration support to lvgl. There is no section or chapter inside the porting related documents. I have to spend the whole afternoon reading the code directly.  

Although most of the details are clear for me, there might be missing details. 
I notice that the lvgl v8.x is more elegant than the previous version in welcoming any hardware accelerators. 
It is better to write something helping people with this low-level acceleration method. 

What I need is **_a list of descriptions about the expected behaviours_** of each of those methods:
```
typedef struct _lv_draw_ctx_t  {
    /**
     *  Pointer to a buffer to draw into
     */
    void * buf;

    /**
     * The the position and size of `buf` (absolute coordinates)
     */
    lv_area_t * buf_area;

    /**
     * The current clip area with absolute coordinates, always the same or smaller than `buf_area`
     */
    const lv_area_t * clip_area;


    void (*draw_rect)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * dsc, const lv_area_t * coords);

    void (*draw_arc)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_arc_dsc_t * dsc, const lv_point_t * center,
                     uint16_t radius,  uint16_t start_angle, uint16_t end_angle);

    void (*draw_img_decoded)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_img_dsc_t * dsc,
                             const lv_area_t * coords, const uint8_t * map_p, lv_img_cf_t color_format);

    lv_res_t (*draw_img)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_img_dsc_t * draw_dsc,
                         const lv_area_t * coords, const void * src);

    void (*draw_letter)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_label_dsc_t * dsc,  const lv_point_t * pos_p,
                        uint32_t letter);


    void (*draw_line)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_line_dsc_t * dsc, const lv_point_t * point1,
                      const lv_point_t * point2);


    void (*draw_polygon)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc,
                         const lv_point_t * points, uint16_t point_cnt);

    /**
     * Replace the buffer with a rect without decoration like radius or borders
     */
    void (*draw_bg)(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_area_t * coords);

    /**
     * Wait until all background operation are finished. (E.g. GPU opertions)
     */
    void (*wait_for_finish)(struct _lv_draw_ctx_t * draw);

#if LV_USE_USER_DATA
    void * user_data;
#endif

} lv_draw_ctx_t;
```

For now, people can only read the source code inside lv_draw_sw_xxxx.c to get such information. 
Code is NOT the documentation. 

Thank you.

**Comment by kisvegabor** [comment]
Very true! 

I've just add a page about it. Let me know if I missed something.

**Comment by GorgonMeducer** [comment]
It is a good start but not sufficient.

For example, 

- `void (*draw_rect)()` Draw a rectangle with shadow, gradient, border, etc. 

It is not for a normal user who can try it on any simulator. For people who wants to implement those backend accelerations, we want to know the "boxing model" with diagrams that show clear links between input parameters (descriptors) and the visual effects (What you see is what you get). Otherwise, HW Acc developers are still forced to read the draw_sw source code. This sure set up a barrier. In general, more details should be documented.

**Comment by kisvegabor** [comment]
This are documented on other pages:
- [boxing model](https://docs.lvgl.io/master/overview/coords.html#boxing-model)
- [style properties](https://docs.lvgl.io/master/overview/style-props.html). The draw functions uses `draw_dsc`s but their values are coming directly from the style properties. 

Adding links to these pages in the GPU section would be really useful. 

Anything else?

**Comment by GorgonMeducer** [comment]
OK, adding links helps. Thank you.

**Comment by kisvegabor** [comment]
Great, added.
