### ISSUE TITLE
STM32 HW acceleration

### ISSUE THREAD

**Issue by ahmetalperenbulut** [kisvegabor/lvgl#2990]
Hi All, 

I'm using STM32H7 with hw acceleration and I've seen some problem in large changes. 
@kisvegabor  have you seen any problem using hw acceleration ?  
I have fixed hw acceleration in my side but i don't know it occurs only my side or general problem.

**Comment by kisvegabor** [comment]
Hi,

There were a large rework on the draw architecture so it might be some regression. 

How did you fix it on your side?

**Comment by ahmetalperenbulut** [comment]
I've used DMA2D with HAL functions and it fixed.  
I can create a pull request if you want

**Comment by kisvegabor** [comment]
We moved to the register-level version to make LVGL work without HAL too.

I took a look and `lv_draw_stm32_dma2d_blend_fill` and `lv_draw_stm32_dma2d_blend_map` doesn't wait for he GPU to finish.

Can you try if adding `while(DMA2D->CR & DMA2D_CR_START_Msk);` at the beginning of these functions helps?

**Comment by ahmetalperenbulut** [comment]
I'm working in v8.0.1 branch but I checked out master branch. there is no problem in master branch

**Comment by kisvegabor** [comment]
Great! Meanwhile I found that there is waiting in `lv_draw_sw_blend()`.
