### ISSUE TITLE
Gesture events are not triggered when the object is scrolled

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#2995]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce
```c
static void event_cb(lv_event_t* e)
{
  lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
  LV_LOG_USER("dir: %d", dir);
}

static void gesture_test()
{
  lv_obj_t* obj = lv_obj_create(lv_scr_act());
  lv_obj_clear_flag(obj, LV_OBJ_FLAG_GESTURE_BUBBLE);
  lv_obj_set_size(obj, 400, 400);

  lv_obj_add_event_cb(obj, event_cb, LV_EVENT_GESTURE, NULL);

  lv_obj_t* obj2 = lv_obj_create(obj);
  lv_obj_set_size(obj2, 400, 600);
}
```

### Expected behavior
Gesture events can still trigger when the object is scrollable.

**Comment by kisvegabor** [comment]
Gestures are intentionally not triggered while scrolling.

What could be use case for triggering gestures while scrolling?

**Comment by FASTSHIFT** [comment]
I haven't thought of a suitable application scenario yet.

**Comment by kisvegabor** [comment]
I'm definitely open to reconsider it but at this moment I think the current behavior is more intuitive.

FYI, I updated the docs to explicitly state that there are no gestures with scrolling.
