### ISSUE TITLE
Using Multiple Layer

### ISSUE THREAD

**Issue by ahmetalperenbulut** [kisvegabor/lvgl#3006]
Hello All,

I'm wondering how to use multiple layer in lvgl ? 

In STM32H7, we have 2 layer(Foreground and background). Can lvgl handle two different layer ? 

thanks

**Comment by embeddedt** [comment]
LVGL doesn't really have a concept of the hardware having multiple layers, however, you could set it up as multiple displays and make the top display have a transparent background. This requires using an `LV_COLOR_DEPTH` of 32, so you will need a decent amount of memory available.

What are you trying to accomplish with the layers?

**Comment by ahmetalperenbulut** [comment]
STM32 and NXP support multiple layer so I'm thinking how to use lvgl with multiple layer :) 

thanks for advice.
