### ISSUE TITLE
The buffer will not automatically switch when double full-screen buffer + direct_mode

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3010]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The buffer will not automatically switch when double full-screen buffer + direct_mode.

### To Reproduce
![WAULDC50` FST9@O@~YZOPU](https://user-images.githubusercontent.com/26767803/149628850-a52a5788-39a9-46e5-81a8-ae991c617e92.png)

### Expected behavior
The buffer will automatically switch when double full-screen buffer+direct_mode.

### Screenshots or video
![%P F}_UJ53K{1BW`62H)`3H](https://user-images.githubusercontent.com/26767803/149628853-ae08da67-0bf6-4e33-b3e4-4c1ee6c566db.png)

**Disable direct_mode**
![`S )9U7{7A88~ZPX{ 1Q`XN](https://user-images.githubusercontent.com/26767803/149628928-ee99817a-0791-4c3a-ad69-d5cd398b5c49.png)

**Comment by FASTSHIFT** [comment]
The buffer switching logic in the `draw_buf_flush()` function may be incorrect, because `draw_buf->flushing_last` may be cleared in the user's `flush_cb` (calling `lv_disp_flush_ready()`)
![_6KE0Y))MZFT2WJ3P J6V)E](https://user-images.githubusercontent.com/26767803/149629130-c0a8f961-b613-4fed-a2d3-1cf30e57cba9.png)
![_UWTMN%41BOIOUKPXOS{3XX](https://user-images.githubusercontent.com/26767803/149629178-6f4c11c6-f9e5-4a6c-9d77-1179528530fb.png)

**Comment by FASTSHIFT** [comment]
Can  remove the line `disp_drv->draw_buf->flushing_last = 0;` in the `lv_disp_flush_ready()` function?

**Comment by kisvegabor** [comment]
> The buffer switching logic in the draw_buf_flush() function may be incorrect, because draw_buf->flushing_last may be cleared in the user's flush_cb (calling lv_disp_flush_ready())

Finally, is this the reason of the missed buffer switching?

> Can remove the line disp_drv->draw_buf->flushing_last = 0; in the lv_disp_flush_ready() function?

If so, I'd rather save the `flushing_last` in line 1004 and use the saved value in line 1015. What do you think?

**Comment by FASTSHIFT** [comment]
> > The buffer switching logic in the draw_buf_flush() function may be incorrect, because draw_buf->flushing_last may be cleared in the user's flush_cb (calling lv_disp_flush_ready())
> 
> Finally, is this the reason of the missed buffer switching?
> 
> > Can remove the line disp_drv->draw_buf->flushing_last = 0; in the lv_disp_flush_ready() function?
> 
> If so, I'd rather save the `flushing_last` in line 1004 and use the saved value in line 1015. What do you think?

Yes, I tried to remove the line `disp_drv->draw_buf->flushing_last = 0;`, the buffer can be switched normally. 
I agree with the way to save the value of `flushing_last`.

**Comment by FASTSHIFT** [comment]
I tested it and it seems to work fine.
![image](https://user-images.githubusercontent.com/26767803/149925530-bf589a55-7fd5-4b9d-9362-d63f4fa688ab.png)

**Comment by kisvegabor** [comment]
Fixed, as discussed.
