### ISSUE TITLE
lv_dropdown ghosting

### ISSUE THREAD

**Issue by bfjm** [kisvegabor/lvgl#3011]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Hello,All!
I have a lv_dropdown object, andI set the first tab of lv_tabview to the parent of lv_dropdown.
It's ghosting happend, when i clicked.CPU is ARM.

### Screenshots or video

like this.
![mmexport1642258782208]()

**Comment by kisvegabor** [comment]
Hi, 

Please send a video and a code snippet to reproduce.

Please also test it  a simulator.

**Comment by bfjm** [comment]
![mmexport1642258782208](https://user-images.githubusercontent.com/38400203/149969563-d2f7fff4-8742-4a41-85f0-3587e02dcac8.jpg)

like this!

**Comment by kisvegabor** [comment]
> Please send a video and a code snippet to reproduce.

**Comment by bfjm** [comment]
```c
static lv_style_t style_box;  
lv_obj_t* dd = lv_dropdown_create(cont, NULL);
lv_style_init(&style_box);
lv_style_set_value_align(&style_box, LV_STATE_DEFAULT, LV_ALIGN_OUT_TOP_LEFT);
lv_style_set_value_ofs_y(&style_box, LV_STATE_DEFAULT, - LV_DPX(10));
lv_style_set_margin_top(&style_box, LV_STATE_DEFAULT, LV_DPX(30));
lv_obj_add_style(dd, LV_CONT_PART_MAIN, &style_box);
lv_obj_set_style_local_value_str(dd, LV_CONT_PART_MAIN, LV_STATE_DEFAULT, "Dropdown");
lv_obj_set_width(dd, 200);
lv_obj_set_pos(dd, 16, 175);
lv_dropdown_set_options(dd, "Alpha\nBravo\nCharlie\nDelta\nEcho");
```
**cont** is container on second. 


https://user-images.githubusercontent.com/38400203/151568286-7c144560-b200-4cfd-9c38-e5b98692cbab.mp4

**Comment by kisvegabor** [comment]
It seems you are using v7. Exactly which version?

The video is not playing. :slightly_frowning_face:

**Comment by bfjm** [comment]
yep, v.7.11.1

**Comment by bfjm** [comment]
![VideoCapture_20220131-112043](https://user-images.githubusercontent.com/38400203/152798511-5dc2e8b2-4a02-4699-9a72-240a855f66dc.jpg)

**Comment by kisvegabor** [comment]
I've tested with v7.11 and it looks well here:
![image](https://user-images.githubusercontent.com/7599318/154283305-b569af99-4768-4a11-a014-71d12c0710ca.png)
