### ISSUE TITLE
 Performance monitor NULL pointer access

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3015]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Decoupling the disp_refr timer: https://github.com/lvgl/lvgl/commit/85cc84ad947786bb3d4857290503047946a55c43. Since `disp_refr->refr_timer = NULL` will lead to null pointer access after the performance monitor is turned on. Is there any good solution?

### To Reproduce
`#define LV_USE_PERF_MONITOR 1` in `lv_conf.h`

```c
lv_disp_t *disp = lv_disp_get_default();
lv_timer_del(disp->refr_timer);
disp->refr_timer = NULL;

while (1)
{
  lv_timer_handler();
  _lv_disp_refr_timer(NULL);
  usleep(1000);
}
```

### Expected behavior
Can correctly count frame rate.

### Screenshots or video
![image](https://user-images.githubusercontent.com/26767803/149708605-9c97e34d-a271-4d76-9212-ef75630b541d.png)

**Comment by embeddedt** [comment]
`refr_timer->period` is only used to determine the maximum possible FPS, so I think it would be safe to just set `fps_limit` to an arbitrarily high number in the case that there is no timer. I think the FPS will still display correctly since that value is just the maximum.

**Comment by FASTSHIFT** [comment]
@embeddedt 
How about `LV_DISP_DEF_REFR_PERIOD` instead of `disp_refr-> timer->period`?

**Comment by kisvegabor** [comment]
> How about LV_DISP_DEF_REFR_PERIOD instead of disp_refr-> timer->period?

I think it'd be a good fallback if `disp_refr-> timer->period` is not available.

**Comment by embeddedt** [comment]
Hmm... doesn't that mean the reported frame time would be artificially capped by `LV_DISP_DEF_REFR_PERIOD` even if the display is being refreshed faster?

**Comment by kisvegabor** [comment]
It does. But showing e.g. 1000 FPS on idle would look ugly too. `LV_DISP_DEF_REFR_PERIOD` at least provides some control over the max value.

**Comment by FASTSHIFT** [comment]
> It does. But showing e.g. 1000 FPS on idle would look ugly too. `LV_DISP_DEF_REFR_PERIOD` at least provides some control over the max value.

![image](https://user-images.githubusercontent.com/26767803/153328205-81e9c506-7d7c-4aa9-99f3-c39e26d141a8.png)

This is indeed the case, I suggest that it is more appropriate to modify it like this:

![image](https://user-images.githubusercontent.com/26767803/153328447-48853291-bc33-43c7-b5ac-978524db1e4a.png)

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Need to reopen this issue :)

**Comment by FASTSHIFT** [comment]
> Hmm... doesn't that mean the reported frame time would be artificially capped by even if the display is being refreshed faster?`LV_DISP_DEF_REFR_PERIOD`

The user can be reminded in the documentation that it is best to change `LV_DISP_DEF_REFR_PERIOD` to match the display when using this refresh mode.

**Comment by kisvegabor** [comment]
A few days ago I added section to the docs about [Decoupling the display refresh timer](https://docs.lvgl.io/master/porting/display.html#decoupling-the-display-refresh-timer). I think using `LV_DISP_DEF_REFR_PERIOD` as a limit and mentioning it in the linked section of the docs would be fine.

Could you send a PR?

**Comment by FASTSHIFT** [comment]
OK, I will send a PR.

**Comment by kisvegabor** [comment]
#3105 is merged so I close this issue.

Thank you fr the PR!
