### ISSUE TITLE
Corstone-300-FVP CI adoption

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3018]
Hi all,

In order to demonstrate the LVGL cmsis-pack, I have created a porting for Corstone-300 running on Arm MPS3 development board that hosts a Cortex-M55 example design. Arm also provides a free emulation tool called FVP that can be used together with MDK (so you don't need the real HW, i.e. MPS3).  

Could you please create a repo as lv_port_mps3_an547_cm55 ?

Please check https://github.com/GorgonMeducer/lv_port_mps3_an547_cm55 for details.

Thank you.

**Comment by GorgonMeducer** [comment]
This porting is using the latest cmsis-pack v0.8.3 (https://github.com/lvgl/lvgl/pull/3021)

**Comment by kisvegabor** [comment]
So Cortex-M55 is still not available in a real chip, right?

Is "MPS3 development board" for "causal developers"? It seems to me it's for beta testing new core architectures but correct me if I see it wrong.

**Comment by GorgonMeducer** [comment]
Cortex-M55 is used in some SoC, in the public domain, Samsung has just announced one. 

MPS3 is very expensive and you can load various FPGA images to it (in theory), but the FVP is free so everyone can try it.

FVP is used to emulate the MPS3 plus some Cortex-M FPGA images. It is widely used for software development before real-silicons are available.  

Corstone-300-FVP comes from Arm and it is publicly available (and free). So it is the perfect platform to demonstrate how to use LVGL cmsis-pack inside MDK.

**Comment by GorgonMeducer** [comment]
By the way, using Corstone-300-FVP is the ONLY FREE solution in MDK to emulate a Cortex-M development board that has an LCD.

**Comment by GorgonMeducer** [comment]
@kisvegabor are there any suggestions?

**Comment by kisvegabor** [comment]
Okay, I'm convinced and just created the repo: https://github.com/lvgl/lv_port_mps3_an547_cm55
I also sent and invitation to you with "Maintainer" role. 

---

Do you think we can use  "Corstone-300-FVP" to benchmark LVGL in reproducible way in real hardware-like environment? The goal would be to have a CI which measures the execution time (or number of clocks) for some specific operations (mainly rendering) and report if there is regression.

**Comment by GorgonMeducer** [comment]
To be honest, Corstone-300-FVP is not designed for performance evaluation, and Arm always suggests that performance data should be derived from real hardware, i.e. here MPS3 + AN547 FPGA image. 

But if we don't pursue "absolute performance data", but want to observe "accumulated performance differences" in a relative manner (between different code versions), then this is possible. 

I have a dedicated project https://github.com/GorgonMeducer/perf_counter that can measure CPU cycles for all Cortex-M processors. It uses Systick without interfering with the existing SysTick Applications, e.g. period timer or RTOS tick timer etc. The problem for FVP is, its emulation of SysTick is not accurate, you might find its value is the times of 25000 cycles... That's why I say, FVP cannot be used for absolute performance evaluation.

2D operations usually take millions of cycles, hence using SysTick to observe a relative performance difference is viable. 

I hope this helps. @kisvegabor

**Comment by GorgonMeducer** [comment]
Furthermore, the Corstone-300-FVP supports command line mode and built-in semihoting. That means **_in command-line mode_** (**NOT** inside MDK), you can use almost all stdio.h features to access host PC file system, i.e. fopen, fread, fwrite, fprintf etc without additional retargeting.  Hence it is suitable for CI system I believe.

**Comment by kisvegabor** [comment]
Thanks. On a 100 MHz MCU it's 0.25 ms accuracy which is enough for us. We can even run the tests multiple times to get longer execution time and higher precision. 

Can you link some info about the command line mode?

```c
    __cycleof__("Draw strings on LCD") {
        __LL_LCD_PRINT_BANNER("Hello LVGL!!");
    }
```

from the README seems quite handy.

**Comment by GorgonMeducer** [comment]
```
Usage: FVP_Corstone_SSE-300_Ethos-U55.exe [OPTION]... [APPLICATION]...

-L, --cadi-log                                      log all CADI calls into an XML logfile
-S, --cadi-server                                   start CADI server allowing debuggers to connect to targets in the simulation
-I, --iris-server                                   Start Iris server allowing debuggers to connect to targets in the simulation
-i, --iris-log                                      Iris log level (may be specified multiple times), example: -ii for level 2
-A, --iris-allow-remote                             Allow remote connections from other machine to Iris server (default: disabled)
    --cpulimit N                                    number of host active CPU seconds for the simulation to run, excluding simulation startup and shutdown.
                                                    Ignored when debug server started (default: unlimited)
    --cyclelimit N                                  number of cycles to run, ignored when debug server started (default: unlimited)
-h, --help                                          print this help message and exit
-K, --keep-console                                  keep console window open after completion (Windows only)
    --list-instances                                print list of target instances to standard output
-l, --list-params                                   print list of model parameters to standard output
    --dump-params                                   dump list of model parameters to JSON file
    --list-regs                                     print model register information to standard output
    --check-regs                                    same as --list-regs but do more consistency checks on the CADI register API
    --list-memory                                   print model memory information to standard output
-o, --output FILE                                   redirect parameters, memory and instance lists to output file FILE
-C, --parameter SPEC                                set parameter, format: -C INST.PARAM=VALUE
-p, --print-port-number                             print port number debug server is listening to. Use in combination with --cadi-server or --iris-server
-R, --run                                           run the simulation immediately at start of simulation when a debug server is started. Use in combination with --cadi-server or --iris-server
    --stat                                          print some run statistics on simulation exit
-T, --timelimit N                                   number of wall clock seconds for the simulator to run, excluding startup and shutdown.
                                                    Ignored when debug server started (default: unlimited)
-b, --break ADDRESS                                 set breakpoint, format: -b [INST=]ADDRESS (may be specified multiple times)
    --start ADDRESS                                 set initial PC to application start address, format: --start [INST=]ADDRESS
    --dump FILE@ADDRESS,SIZE                        dump section of memory into FILE, format: --dump [INST=]FILE@[MEMSPACE:]ADDRESS,SIZE (may be specified multiple times)
-q, --quiet                                         run quiet, suppress informational output
-f, --config-file FILE                              load model parameters from configuration file FILE
    --plugin FILE                                   load plugin FILE
    --trace-plugin FILE (DEPRECATED: use --plugin)  load trace plugin FILE
-a, --application FILE                              application to load, format: -a [INST=]FILE (use -a INST=FILE for a specific instance, use -a INST*=FILE to match multiple instances using wildcards e.g. for SMP cores)
    --fast-ram FILE                                 enable FastRAM and load the configurations of FastRAM from FILE
-s, --save DIR                                      Save checkpoint to DIR on simulation exit
-r, --restore DIR                                   Restore checkpoint from DIR on simulation startup
    --disable-analytics                             disable product analytics gathering for current run.
                                                    For persistent disabling, set ARM_DISABLE_ANALYTICS env variable.
    --simlimit N                                    Number of seconds to simulate, ignored when debug server started (default: unlimited)
    --iris-port-range MIN:MAX                       Set the range of ports to scan when starting an Iris server.
                                                    The first available port found will be used.
    --iris-port PORT                                Set a specific port to use for the Iris server.
    --data FILE@ADDRESS                             raw data to load at specified address, format: --data [INST=]FILE@[MEMSPACE:]ADDRESS (may be specified multiple times)
-D, --allow-debug-plugin                            allow a plugin to debug the simulation
    --cpi-file FILE                                 Use FILE to set Cycle Per Instruction class
-Q, --quantum N              Number of ticks to simulate per quantum (default to 10000)
-M, --min-sync-latency N     Number of ticks to simulate  before synchronizing. Events occurring
                             at a higher frequency than this are missed
                             (default to 100)
    --log FILE               Log all SystemC reports into given FILE
    --disable-model-exitcode Disables the retrieval of any exit code
                             potentially returned by the model or a plugin
    --version                Print version info


To stop running simulation press Ctrl+C
```

**Comment by GorgonMeducer** [comment]
@kisvegabor  

Usage One:
```c
    #include "perf_counter.h"
        
    __cycleof__(__STRING) {
        /* Your code block here */
    }
```

Usage Two:
```c
    #include "perf_counter.h"


    int32_t iCycleResult = 0;
    
    /* measure cycles and store it in a dedicated variable without calling printf */
    __cycleof__("delay_us(1000ul)", 
        /* insert code to __cycleof__ body, "{}" can be omitted  */
        {
            iCycleResult = __cycle_count__;   /*< "__cycle_count__" stores the result */
        }) {
        delay_us(1000ul);
    }
```

NOTE: 
1. For Usage one, the c99 MUST be enabled. 
2. For Usage Two, the gnu extensions MUST be enabled, for example, **-std=gnu99** or **-std=gnu11**

**Comment by GorgonMeducer** [comment]
I have added an FVP configuration file for the command line mode, and the following option is used to disable popup window.

https://github.com/lvgl/lv_port_mps3_an547_cm55/blob/5f3ce4a69cc6d58db796099525a0df6664589e6b/fvp_cfg.txt#L1692

The key to using semihosting in FVP is using the functions of "stdio.h" directly without any retargeting. 

As MDK doesn't support semihosting, the porting project retargets printf to USART (telnet in FVP). In command-line mode, you have to remove the retargeting code, so all printf will be retargeted to console output directly. 

Also, do not retarget exit(), so when you exit main() the FVP will exit also. 

Hence, in command line mode, the following code should be disabled:
https://github.com/lvgl/lv_port_mps3_an547_cm55/blob/5f3ce4a69cc6d58db796099525a0df6664589e6b/platform/platform.c#L94

https://github.com/lvgl/lv_port_mps3_an547_cm55/blob/5f3ce4a69cc6d58db796099525a0df6664589e6b/platform/platform.c#L100

I hope this helps.

@kisvegabor

**Comment by kisvegabor** [comment]
Awesome, thank you!

One more question: any chance to run it on Linux?

**Comment by GorgonMeducer** [comment]
> Awesome, thank you!
> 
> One more question: any chance to run it on Linux?

Yes, there is a Linux version: https://developer.arm.com/-/media/Arm%20Developer%20Community/Downloads/OSS/FVP/Corstone-300/FVP_Corstone_SSE-300_11.16_26.tgz

**Comment by kisvegabor** [comment]
Thanks, I've installed the Linux version and found `FVP_Corstone_SSE-300_Ethos-U55`. If I start it I get this window which seems good:
![image](https://user-images.githubusercontent.com/7599318/151660899-fef837ac-ff53-4c45-8c89-c59d8bc0f6ae.png)


I still don't know how the create an app (I.e. build a LVGL UI?) without Keil. Sorry for these basic questions. If you can point to a get started tutorial, I can probably figure out these things on my own . :slightly_smiling_face:

**Comment by GorgonMeducer** [comment]
If you have MDK and open the project, you should be able to find a very useful option “Create Batch File”

![image](https://user-images.githubusercontent.com/13148491/151661929-52cbb1e1-fa51-48f2-b31c-9cbafe2090b6.png)

Once you select this option, after a successful compilation, a batch file will be generated. 

![image](https://user-images.githubusercontent.com/13148491/151662002-e9b4a380-9178-4f93-a943-0b40fc1eb4a4.png)

It contains all the information for compiling the project in command line mode. It is similar to cmake verbal output. 
With that information, it should be sufficient for you to create a makefile or cmake.

If you still have questions, please feel free to let me know.

**Comment by GorgonMeducer** [comment]
Let me reopen this discussion.

**Comment by kisvegabor** [comment]
I've just realized the Keil doesn't support Linux. 

As I'm using Linux I'll need some time to make experiments.

I'll post here if I could try out the mentioned things.

**Comment by GorgonMeducer** [comment]
@kisvegabor don't worry, I have generated all related files and uploaded them to https://github.com/lvgl/lv_port_mps3_an547_cm55.

**Comment by kisvegabor** [comment]
Sorry, I didn't have time to dive into this topic :slightly_frowning_face: 

@embeddedt pinned this issue so it will remain opened as a reminder.

**Comment by GorgonMeducer** [comment]
Hi @kisvegabor,

Maybe you haven't noticed that Arm released a[ community license](https://www.keil.com/pr/article/1299.htm) for MDK which allows users to compile and debug freely for non-commercial purposes only:

![image](https://user-images.githubusercontent.com/13148491/157227309-7f2a9702-abb1-47d9-948d-9dcf436e531a.png)

So please don't worry about the license issue.

**Comment by kisvegabor** [comment]
Thanks for sharing this, @GorgonMeducer!

**Comment by kisvegabor** [comment]
Let's warm up this topic! In summery it'd be great to  create a CI from Corstone-300-FVP to test the performance of some critical parts: 
- malloc
- layouts
- widgets creation
- drawing

The [README](https://github.com/GorgonMeducer/perf_counter) describes very well how to measure the cycle count. So the only question is how to compile a GUI/LVGL project on Linux? I've installed https://developer.arm.com/-/media/Arm%20Developer%20Community/Downloads/OSS/FVP/Corstone-300/FVP_Corstone_SSE-300_11.16_26.tgz

but can't see where to add and how t compile a project.

**Comment by GorgonMeducer** [comment]
@kisvegabor FVP is used to run given elf / axf file. You can use cmake/makefile to compile a LVGL/GUI project.

**Comment by kisvegabor** [comment]
I might have missed some relevant docs, but it's still not clear to me how to turn run an LVGL code with Corstohowne-300-FVP. 
E.g. 
- how to compile it?
- what driver to use?
-  how to load the elf?

**Comment by GorgonMeducer** [comment]
For your questions:
> how to compile it?

Please use the normal toolchain to generate an elf file for Cortex-M55, i.e. gcc, llvm or armclang
and make sure you write the right ld script, the memory layout can be found in [here](https://developer.arm.com/documentation/dai0547/c?_ga=2.157798205.688811587.1624957483-616249991.1623083451)

> what driver to use?

No driver is required

> how to load the elf?

Use command-line option to specify the target elf file

For example
```sh
SET PATH=%PATH%;"C:\Program Files\ARM\FVP_Corstone_SSE-300\models\Win64_VC2017\"
FVP_Corstone_SSE-300_Ethos-U55 -a template.axf
```

**Comment by kisvegabor** [comment]
I hoped for a project which contains a hello world LVGL label with an example Makefile. I still see too many questions to get started with it (on Linux) without a super basic example. :slightly_frowning_face: 

Is there any chance that a project like this will be available?

**Comment by GorgonMeducer** [comment]
To be honest, I am not a Linux user and not good at writing cmake or makefile, hence it is not easy for me to create such an example project. 
Anyway, I will do it and please allow me more time.

**Comment by kisvegabor** [comment]
Thank you in advance. I'm also not a makefile hero but [this one](https://github.com/lvgl/lv_port_pc_eclipse/blob/master/Makefile) can be a good starting point.

**Comment by GorgonMeducer** [comment]
I will use Arm-DS to create such a project because Arm-DS can generate a makefile automatically and it supports cmsis-pack.

**Comment by kisvegabor** [comment]
The discussion continued in #3443 so I close it.
