### ISSUE TITLE
Physical display resolution doesn't work

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3032]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I tried to port demo/widgets to a development board that has a 320*240 LCD.
It appears that the resolution is too small for the widgets:

![image](https://user-images.githubusercontent.com/13148491/150423906-a08bbaa6-a3c2-4974-bfa0-78b757cee5f4.png)

According to the [porting document](https://github.com/lvgl/lvgl/blob/master/docs/porting/display.md#optional-fields), 

> physical_hor_res horizontal resolution of the full / physical display in pixels. Only set this when not using the full screen (defaults to -1 / same as hor_res).
> physical_ver_res vertical resolution of the full / physical display in pixels. Only set this when not using the full screen (defaults to -1 / same as ver_res).

I should be able to use the LCD to display part of a physical display, for example, the left corner of the demo, i.e. 

![image](https://user-images.githubusercontent.com/13148491/150424273-3c09470a-4215-43a2-abf0-75a9f71968d0.png)

by applying a bigger physical resolution:

```c
    static lv_disp_drv_t disp_drv;                                              /*Descriptor of a display driver*/
    lv_disp_drv_init(&disp_drv);                                                /*Basic initialization*/

    /*Set up the functions to access to your display*/

    /*Set the resolution of the display*/
    disp_drv.hor_res = GLCD_WIDTH;
    disp_drv.ver_res = GLCD_HEIGHT;

//#if LV_USE_DEMO_WIDGETS
    disp_drv.physical_hor_res = 480;
    disp_drv.physical_ver_res = 320;
//#endif

    /*Used to copy the buffer's content to the display*/
    disp_drv.flush_cb = disp_flush;

    /*Set a display buffer*/
    disp_drv.draw_buf = &draw_buf_dsc_1;

    /*Required for Example 3)*/
    //disp_drv.full_refresh = 1

    /* Fill a memory array with a color if you have GPU.
     * Note that, in lv_conf.h you can enable GPUs that has built-in support in LVGL.
     * But if you have a different GPU you can use with this callback.*/
    //disp_drv.gpu_fill_cb = gpu_fill;

    /*Finally register the driver*/
    lv_disp_drv_register(&disp_drv);
}
```

But this doesn't work. Do I miss anything? or is this a defect?

### Expected behavior
![image](https://user-images.githubusercontent.com/13148491/150424273-3c09470a-4215-43a2-abf0-75a9f71968d0.png)

### Actually got
![image](https://user-images.githubusercontent.com/13148491/150423906-a08bbaa6-a3c2-4974-bfa0-78b757cee5f4.png)

**Comment by GorgonMeducer** [comment]
You can reproduce this with https://github.com/lvgl/lv_port_mps3_an547_cm55

In MDK RTE dialog, unselect Benchmark and select Demo:Widgets as shown below:

![image](https://user-images.githubusercontent.com/13148491/150659635-07431240-381b-4664-b558-15887f14514e.png)

Compile and Debug directly.

**Comment by kisvegabor** [comment]
`physical_hor/ver_res` is not used by LVGL itself at all. They can be used by drivers if needed. 

Do you get the same result if you comment out 
```c
    disp_drv.physical_hor_res = 480;
    disp_drv.physical_ver_res = 320;
```

**Comment by GorgonMeducer** [comment]
@kisvegabor Yes, the result is the same. 
I thought there was some internal clipping mechanism that uses physical resolutions. 

Do you have a plan to add this feature? or maybe you can update the documents to avoid misleading.

**Comment by GorgonMeducer** [comment]
@kisvegabor I tried to use 480 * 240 as the screen resolution but cannot get the expected result.

![image](https://user-images.githubusercontent.com/13148491/150893814-dd7dca2e-4ea9-4a4c-89fd-ec2144ae5615.png)

https://github.com/lvgl/lv_port_mps3_an547_cm55/blob/master/RTE/LVGL/lv_port_disp_template.c

NOTE: the GLCD_DrawBitmap is also updated and tested. 

![image](https://user-images.githubusercontent.com/13148491/150893930-a2a97d7a-9473-4f0c-9829-845d5511462b.png)

https://github.com/lvgl/lv_port_mps3_an547_cm55/blob/e02fc8babbaa2b84b354966bd195604212ae8233/platform/GLCD_V2M-MPS3_AN547.c#L779

**Comment by kisvegabor** [comment]
I'm trying to understand what could be the problem. Can you enable [logging and asserts](https://github.com/lvgl/lvgl/blob/master/lv_conf_template.h#L197-L239)?

Is there any change if you increase `LV_MEM_SIZE`?

**Comment by GorgonMeducer** [comment]
> I'm trying to understand what could be the problem. Can you enable [logging and asserts](https://github.com/lvgl/lvgl/blob/master/lv_conf_template.h#L197-L239)?
> 
> Is there any change if you increase `LV_MEM_SIZE`?

Hi @kisvegabor 

I have increased the LV_MEM_SIZE to 64KB. It doesn't help. I think asserts are enabled by default because when I set the resolution to 480 * 240, the malloc failed (the original LV_MEM_SIZE is 32K) and was caught by assert. 

Can you replicate the issue on your side?

**Comment by kisvegabor** [comment]
> Can you replicate the issue on your side?

What is the actual of GLCD_WIDTH and GLCD_HEIGHT?

It worked for me with any resolution I tried from 240x240 to 1960x1080.

**Comment by GorgonMeducer** [comment]
GLCD_WIDTH is 320
GLCD_HEIGHT is 240.

**Comment by GorgonMeducer** [comment]
> > Can you replicate the issue on your side?
> 
> What is the actual of GLCD_WIDTH and GLCD_HEIGHT?
> 
> It worked for me with any resolution I tried from 240x240 to 1960x1080.

Can you share me your lv_conf.h ?

**Comment by kisvegabor** [comment]
> Can you share me your lv_conf.h ?

It's the as it is template, I only enabled the demos.

Does LVGL freezes when you see that strange screen? (the arcs should be animated if LVGL is running)

**Comment by GorgonMeducer** [comment]
![image](https://user-images.githubusercontent.com/13148491/151586685-15ffc859-63fb-4c2a-adbc-7fa2e0bea2a9.png)

I cannot see the arcs. 

I can pause the running, everything looks fine.

I enabled the log:

```c
/*Enable the log module*/
#define LV_USE_LOG 1
#if LV_USE_LOG

    /*How important log should be added:
    *LV_LOG_LEVEL_TRACE       A lot of logs to give detailed information
    *LV_LOG_LEVEL_INFO        Log important events
    *LV_LOG_LEVEL_WARN        Log if something unwanted happened but didn't cause a problem
    *LV_LOG_LEVEL_ERROR       Only critical issue, when the system may fail
    *LV_LOG_LEVEL_USER        Only logs added by the user
    *LV_LOG_LEVEL_NONE        Do not log anything*/
    #define LV_LOG_LEVEL        LV_LOG_LEVEL_WARN

    /*1: Print the log with 'printf';
    *0: User need to register a callback with `lv_log_register_print_cb()`*/
    #define LV_LOG_PRINTF           1

    /*Enable/disable LV_LOG_TRACE in modules that produces a huge number of logs*/
    #define LV_LOG_TRACE_MEM        1
    #define LV_LOG_TRACE_TIMER      1
    #define LV_LOG_TRACE_INDEV      1
    #define LV_LOG_TRACE_DISP_REFR  1
    #define LV_LOG_TRACE_EVENT      1
    #define LV_LOG_TRACE_OBJ_CREATE 1
    #define LV_LOG_TRACE_LAYOUT     1
    #define LV_LOG_TRACE_ANIM       1

#endif  /*LV_USE_LOG*/
```

There is only one warning:

![image](https://user-images.githubusercontent.com/13148491/151587131-872363b8-5d4a-4803-a802-80787f39a836.png)

So I enable the 
```c
#define LV_FONT_MONTSERRAT_20     1
```

After that, there is no warning or error but the problem still exists.

**Comment by GorgonMeducer** [comment]
@kisvegabor sorry, I find the issue. My fault. In the cmsis-pack, I forgot to include lv_extra.c. 

I will fix it immediately. I am really sorry about this.

![image](https://user-images.githubusercontent.com/13148491/151588247-d5e04b98-c2c1-48b0-a6d2-36bdfa5c2fe4.png)

Now everything works well as expected.

**Comment by kisvegabor** [comment]
Great! But I still see 2 issues on the image:
1. Why only 2 tabs are visible? It seems the image is clipped.
2. There is a grayish-greenish horizontal line above the "Log out" button.

**Comment by GorgonMeducer** [comment]
> Great! But I still see 2 issues on the image:
> 
> 1. Why only 2 tabs are visible? It seems the image is clipped.
- it is because I set physical resolution to 480 * 240. After changing back to 320 * 240 everything looks fine

![image](https://user-images.githubusercontent.com/13148491/151662153-f9e76ca7-321b-4521-9030-62d46bcffde5.png)


> 2. There is a grayish-greenish horizontal line above the "Log out" button.
- It is a glitch in the FVP LCD display. You can ignore it.

**Comment by kisvegabor** [comment]
All great then :slightly_smiling_face: 

BTW, I thought you will see a compiler error if `lv_extra.c` is missing. 

Anyway, feel free to close this issue if you see no more problems.

**Comment by GorgonMeducer** [comment]
> BTW, I thought you will see a compiler error if lv_extra.c is missing

in [lv_cmsis_pack.c](https://github.com/lvgl/lvgl/blob/master/env_support/cmsis-pack/lv_cmsis_pack.txt), there is a weak function which helps people to customize LVGL and decouple LVGL from the content inside extras.

```c
/* when people don't want to use src/extra */
__attribute__((weak))
void lv_extra_init(void)
{
}
```

> Anyway, feel free to close this issue if you see no more problems.
Sure, as #3056 is merged, there is no reason to keep this one.

Thank you for your support!!!
