### ISSUE TITLE
Change the drop-down box to Chinese, and the drop-down arrow is gone

### ISSUE THREAD

**Issue by RiceChen0** [kisvegabor/lvgl#3051]

**Comment by LianKaFoHaLi** [comment]
Did you add Chinese font to your project?

**Comment by RiceChen0** [comment]
> Did you add Chinese font to your project?

Yes, my project needs to switch between Chinese and English. There are arrows in English mode, but no arrows in Chinese mode

**Comment by LianKaFoHaLi** [comment]
Maybe your Chinese font doesn't have LV_SYMBOY_DOWN icon font.
![image](https://user-images.githubusercontent.com/50412488/151322588-59cc6698-c7b1-477d-806a-bc4f8c0c9286.png)
You can use _lv_dropdown_set_symbol()_ to define a custom image.
```
    /*Use a custom image as down icon and flip it when the list is opened*/
    LV_IMG_DECLARE(img_caret_down)
    lv_dropdown_set_symbol(dropdown, &img_caret_down);
```

**Comment by RiceChen0** [comment]
I still don't know how to deal with it. Could you please provide an example

**Comment by LianKaFoHaLi** [comment]
May be you can refer to this.
[https://docs.lvgl.io/master/widgets/core/dropdown.html](Drop down list) 
![image](https://user-images.githubusercontent.com/50412488/151341766-063cc55d-8912-4157-8813-7e37b1c013b9.png)

**Comment by embeddedt** [comment]
FYI, `img_caret_down` is located [in `examples/assets`](https://github.com/lvgl/lvgl/blob/master/examples/assets/img_caret_down.c).

**Comment by kisvegabor** [comment]
Have you added the symbols to your Chinese font as described [here](https://lvgl.io/tools/fontconverter)?

**Comment by RiceChen0** [comment]
Thanks for your support, I have solved the problem

**Comment by hayschan** [comment]
> Thanks for your support, I have solved the problem

How did you solve the problem?
