### ISSUE TITLE
Attach the NXP PXP/VGLITE GPUs back to the new draw context (architecture changes)

### ISSUE THREAD

**Issue by nicusorcitu** [kisvegabor/lvgl#3052]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Draw context architecture changed and now the GPU rendering is done by implementing the supported acceleration callbacks.
The NXP GPUs hooks are gone and we need to add the support back.

### To Reproduce
NXP GPUs support is currently broken on the master branch.

### Expected behavior
NXP PXP or VGLITE can be enabled and used as accelerators.

**Comment by nicusorcitu** [comment]
I am currently working on this issue, the PXP attachment is complete and tested.

**Comment by kisvegabor** [comment]
Thank you for opening this issue and working on it. 
Feel free to send a PR so that I can also try it out.

**Comment by gokhannsahin** [comment]
I wonder why PXP and VGlite are limited to 16bits and why rotating is not used with vglite? The performance of IMXRT1170 is lower than expected because the gpu drivers poor.

**Comment by gokhannsahin** [comment]
Also, using CPU to rotate is hungry, why don't use VGLite to rotate any image?

**Comment by nicusorcitu** [comment]
Thank you for your interest to the NXP products. We were about to update the GPU with more functionalities but now we have to rework the patches due to the new architecture.

We will add soon the support for ARGB 32 bit color format on both PXP and VGLITE, hopefully at the end of this ticket. Also the image rotation is in progress.

We will continue to add even more GPU acceleration support so that the performance gets better and better.

**Comment by gokhannsahin** [comment]
That is good news.
Also, multilayer features can be added default so it provides very good performance using LCDifv2 alpha blendig.

**Comment by nicusorcitu** [comment]
We are also studying if chroma key, alpha blending, multi-layers alpha blending can be accelerated using LCDIFv2.

**Comment by kisvegabor** [comment]
@nicusorcitu 
What is the current state of the new drivers?

**Comment by gokhannsahin** [comment]
I'm looking forward to your reply. Please upgrade the driver for new version because we don't use it in v8.2.

**Comment by nicusorcitu** [comment]
The GPU support is back online and we added some extra widget acceleration features. All these changes are currently on our local NXP GTEC repo.

In these days I am doing a clear set of unit tests to validate all the changes, next week I will complete them.

Next I will start the procedure to push the GPU support to upstream. The ETA for upstream is the end of March, this process is taking a while because I need to fallow an even secured mechanism now. These days the upstream to github might also suffer some changes to prevent any security breach.

**Comment by nicusorcitu** [comment]
I start the procedure to upstream.

**Comment by embeddedt** [comment]
Not stale.

**Comment by nicusorcitu** [comment]
The upstream patches is still in progress.

**Comment by jupeos** [comment]
What's the latest on this?
I'm waiting for this to be complete before I upgrade from V7 to V8.
Using IMXRT1064

**Comment by nicusorcitu** [comment]
I finally got the approval for this patch set. I will create the PR soon, hopefully by the end of this week.

**Comment by nicusorcitu** [comment]
I just opened the PR
https://github.com/lvgl/lvgl/pull/3322

**Comment by jupeos** [comment]
> I just opened the PR #3322

Fantastic! Can't wait to try it out.

**Comment by kisvegabor** [comment]
As the PR is merged I close this issue.

Thank you @nicusorcitu!
