### ISSUE TITLE
default LV_MEM_SIZE is too small to run demo: widgets

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3057]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The default value of LV_MEM_SIZE in the 'lv_conf_template.h' is too small to run our iconical demo, i.e. Widgets with a typical resolution 320 * 240. It requires **38**KBytes (35K at least for only seeing the first page)

We have to update the demos/README.md.
Except for that, should we consider increasing the default value?

**Comment by kisvegabor** [comment]
I agree to increase the default `LV_MEM_SIZE`. To be sure I suggest 48k.

**Comment by GorgonMeducer** [comment]
OK. Will generate a PR.

**Comment by kisvegabor** [comment]
Feel free to update #3032
