### ISSUE TITLE
Label area does not update correctly on layers top or sys

### ISSUE THREAD

**Issue by LuisCRSousa** [kisvegabor/lvgl#3073]
### Describe the bug
Label area does not update correctly on layers lv_layer_top() or lv_layer_sys.
It show the first text correctly, but if  I set a new text, the old one does not disappear
Tested with v8.1 and v8.2

### To Reproduce
Provide a small, independent code sample that can be used to reproduce the issue.
Ideally this should work in the PC simulator unless the problem is specific to a platform.
Format the code like this:
```c
lv_obj_t* title = lv_label_create(lv_layer_top());
lv_label_set_text(title, "Initializing");
//Update later
lv_label_set_text(title, "HOME");
```

### Expected behavior
Should show the second label text without any parts of the old one.

### Screenshots or video

![IMG_6711](https://user-images.githubusercontent.com/8472158/152374491-c5493b5b-5c41-410c-ad86-0f71fd7602d5.JPG)
![IMG_6712](https://user-images.githubusercontent.com/8472158/152374502-3d66815d-af3c-4251-a460-96c4f4b56603.JPG)

**Comment by kisvegabor** [comment]
It's probably a driver issue. How does you driver work? Please share some code snippets.

**Comment by LuisCRSousa** [comment]
Does not seem to be a driver issue because:

- Driver is refreshing all screen. `disp_drv.full_refresh = true;` I'm using the st7586s display that uses 3 pixels per byte so I can't update an area if that area does x,y is not multiple of 3. Not a problem for me, just do a full refresh.
- My app is complete. I have a lot of widgets, menus, images etc all working correctly.

The only thing that does not work is when a label is updated on a layer other than lv_scr_act()
I manage to get the app working by not using any other layers.

This is the configuration of the display:
`
// Initialize the display
static lv_disp_drv_t disp_drv;
lv_disp_drv_init( &disp_drv );
disp_drv.hor_res = UI_DRV_GLCD_DISPLAY_PIXELS_WIDTH;
disp_drv.ver_res = UI_DRV_GLCD_DISPLAY_PIXELS_HEIGHT;
disp_drv.full_refresh = true;
disp_drv.flush_cb = display_flush;
disp_drv.draw_buf = &draw_buf;
lv_disp_t* display = lv_disp_drv_register(&disp_drv);

// Initialize lvgl mono system theme
lv_theme_t* th = lv_theme_mono_init(display, 1, LV_FONT_DEFAULT);
lv_disp_set_theme(display, th);

// Defaults styles
// Remove main screen scrollable bars
lv_obj_clear_flag(lv_scr_act(), LV_OBJ_FLAG_SCROLLABLE);
`

**Comment by LuisCRSousa** [comment]
With all due respect., but why auto close open issues?

**Comment by embeddedt** [comment]
There are lot of issues which we respond to but then the original poster never replies/doesn't provide enough information to diagnose the issue. However in this case it looks like this was a mistake.

**Comment by kisvegabor** [comment]
Sorry, it was really just an oversight and this issue wasn't stale. 

You approach about the display driver seems correct and I tried to reproduce the issue in a simulator but it worked well there. 

So can you reproduce in a Simulator?
