### ISSUE TITLE
Do widgets names had a magic effect ?

### ISSUE THREAD

**Issue by LusterWong** [kisvegabor/lvgl#3076]
I tried to rename the source file of one of the widgets and change the function name.
For example, lv_tabview.c was changed to lv_tabview_mod.c, lv_tabview_create() to lv_tabview_mod_create(), and lv_tabview_add_tab() to lv_tabview_mod_add_tab ().
Then, using the same method call, you find that the graphics rendered are not the same. Why? 
Is the name qualified?

```
void lv_example_tabview_1(void)
{
    /*Create a Tab view object*/
    lv_obj_t *tabview;
    tabview = lv_tabview_mod_create(lv_scr_act(), LV_DIR_TOP, 50);

    /*Add 3 tabs (the tabs are page (lv_page) and can be scrolled*/
    lv_obj_t *tab1 = lv_tabview_mod_add_tab(tabview, "Tab 1");
    lv_obj_t *tab2 = lv_tabview_mod_add_tab(tabview, "Tab 2");
    lv_obj_t *tab3 = lv_tabview_mod_add_tab(tabview, "Tab 3");

    /*Add content to the tabs*/
    lv_obj_t * label = lv_label_create(tab1);
    lv_label_set_text(label, "This the first tab\n\n"
                             "If the content\n"
                             "of a tab\n"
                             "becomes too\n"
                             "longer\n"
                             "than the\n"
                             "container\n"
                             "then it\n"
                             "automatically\n"
                             "becomes\n"
                             "scrollable.\n"
                             "\n"
                             "\n"
                             "\n"
                             "Can you see it?");

    label = lv_label_create(tab2);
    lv_label_set_text(label, "Second tab");

    label = lv_label_create(tab3);
    lv_label_set_text(label, "Third tab");

    lv_obj_scroll_to_view_recursive(label, LV_ANIM_ON);

}
```
This is what the code looks like:
![1644149170(1)](https://user-images.githubusercontent.com/56709609/152680041-b295b337-fdd4-4ad2-bf2d-728efb399170.png)

This is the effect of the principle example code:
![1644149189(1)](https://user-images.githubusercontent.com/56709609/152680022-37dbfffd-33ca-4ded-ad0f-e942bdc0429d.png)

In addition, the layer functions lv_obj_move_foreground and lv_obj_move_background should be removed from the 8.1 help.
[https://docs.lvgl.io/master/overview/layer.html?highlight=layer](url)

**Comment by LusterWong** [comment]
I forgot to mention that I was running the PC emulation using Eclipse (ver 2021.6) win10

**Comment by kisvegabor** [comment]
There shouldn't any magic effect. 

Please attach `lv_tabview_mod.c/h` to reproduce it.
