### ISSUE TITLE
lv_img_set_zoom & lv_img_set_angle working wrong

### ISSUE THREAD

**Issue by phamvant** [kisvegabor/lvgl#3077]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I use an image as variable (C array) which generated by online converter
If i use lv_img_set_zoom, the image disappear
and when i use lv_img_set_angle, the image is cut off

I'm using Arduino on ESP32

### To Reproduce
```c
    lv_obj_t * icon = lv_img_create(lv_scr_act());
    LV_IMG_DECLARE(cloud_sun);
    lv_img_set_src(icon, &cloud_sun);
    lv_obj_set_size(icon, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_img_set_antialias(icon, true);
    lv_img_set_angle(icon, 10);`
```
My display setup
```c
    tft.setRotation( 1 );
    uint16_t calData[5] = { 275, 3620, 264, 3532, 7 };
```

### Screenshots or video
![20220207_102753](https://user-images.githubusercontent.com/44409501/152721278-27a713bd-a071-47e1-9ea6-be769b2a2f59.jpg)

**Comment by embeddedt** [comment]
Did you close this by accident or is the issue resolved?

**Comment by phamvant** [comment]
> Did you close this by accident or is the issue resolved?

Thank you. 

I have to chose "True color with alpha" instead of *indexed 256 color" and it worked.
