### ISSUE TITLE
[meta] Use pre-commit to run astyle automatically on staged files when commiting

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#3083]
### Introduce the problem
I tend to forget about formatting my code before pushing it to the remotes, then CI will fail and I will end up having multiple automatic emails complaining about it. I've also pushed commits with test cases that doesn't pass.

### Examples and cases
Any of my PR 😄 

### Suggested solution

I've found a 'tool' named [pre-commit](https://pre-commit.com/#install) in [this Interrupt post](https://interrupt.memfault.com/blog/pre-commit) and I've set it up locally, I'm pretty pleased with how it works, it also only runs astyle only on the staged files, not in all of the files.

It's worth mentioning that we can still keep the code-format scripts. 

I've recorded a explanation video, please forgive the record setup, let me know if you have additional questions https://youtu.be/Utp9GEPjJyU

**Comment by kisvegabor** [comment]
It seems useful. We can add a description to it in the docs and link it in the PR template. 

Can you share your config file too?

**Comment by C47D** [comment]
Sure, I can send the configuration file in a PR.

What about mentioning it after the [Commit message format](https://docs.lvgl.io/master/CONTRIBUTING.html#commit-message-format) in the docs?

As this is an optional work flow I'm not sure if it's worth mentioning it in every PR. I use it just to don't forget formatting the code, other people can use other tools. 

What do you think?

**Comment by kisvegabor** [comment]
> What about mentioning it after the [Commit message format](https://docs.lvgl.io/master/CONTRIBUTING.html#commit-message-format) in the docs?

I suggest this (too?): https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md

This file is linked [here](https://docs.lvgl.io/master/CONTRIBUTING.html#introduction) and in the [PR template](https://github.com/lvgl/lvgl/blob/master/.github/pull_request_template.md) too.

> As this is an optional work flow I'm not sure if it's worth mentioning it in every PR.

My experience is that people sometimes ignore notes even in the PR templates. I can hardly believe the vast majority of people will find it in the docs.
