### ISSUE TITLE
Can't display gif that has width more than 140px

### ISSUE THREAD

**Issue by phamvant** [kisvegabor/lvgl#3090]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The gif that has width more than 140px seem like doesn't show up on my 320px width screen.
I have to zoom in the gif but then the frame rate get lower. 
I can i fix this?

I'm using arduino on esp32

**Comment by kisvegabor** [comment]
Can it be an out of memory issue?
Please enable logging as described here: https://docs.lvgl.io/master/porting/log.html

Or increase `LV_MEM_SIZE`

**Comment by phamvant** [comment]
![image](https://user-images.githubusercontent.com/44409501/153899701-8d7d67a1-ddf8-4eb6-90a6-85604dead625.png)

I got this error

**Comment by embeddedt** [comment]
Your heap size is too small.

**Comment by phamvant** [comment]
I increased LV_MEM_SIZE but still not work

**Comment by kisvegabor** [comment]
What it the current size? 
It should be  at least 40 * 1024.

**Comment by embeddedt** [comment]
Hmm, @kisvegabor, in the log it appears that it tries to allocate 308KB, so I'm not sure if that's enough.

**Comment by kisvegabor** [comment]
Oh, I missed a digit. 

Note that, GIFs require a  lot of RAM. See here: https://docs.lvgl.io/master/libs/gif.html#memory-requirements

**Comment by phamvant** [comment]
I use ``` LV_MEM_CUSTOM``` and although with 120*240 gif it only use 6.3% RAM

**Comment by phamvant** [comment]
> What it the current size? 
> It should be  at least 40 * 1024.

Even 200 doesn't work
