### ISSUE TITLE
Improve the drawing accuracy of arc

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3093]
### Introduce the problem
The current arc representation angle uses the `uint16_t` type, and the range is 0~360. When the arc size is large, the result of the motion does not seem to be continuous.

### Examples and cases
```c
static void timer_cb(lv_timer_t * timer)
{
  lv_obj_t * arc = timer->user_data;
  static int i = 0;
  lv_arc_set_value(arc, i++);
}

void arc_test(void)
{
  lv_obj_t * arc = lv_arc_create(lv_scr_act());
  lv_obj_set_size(arc, 480, 480);
  lv_arc_set_range(arc, 0, 1000);
  lv_obj_center(arc);

  lv_timer_create(timer_cb, 100, arc);
}
```
https://user-images.githubusercontent.com/26767803/153990584-95a88b98-b547-45ab-b7c2-e9562c83789e.mp4

### Suggested solution
To improve the representation accuracy of arc, can refer to `lv_img_set_angle()` to use 0~3600 as the angle range?

**Comment by kisvegabor** [comment]
It looks really odd with large arcs. 

I agree to change the resolution but it would be a larger  breaking change so we can do it only in v9.

**Comment by BesitzeRuf** [comment]
Hi all, what about just add a new function for ex. lv_img_set_angle_precise(), which accepts bigger range of angle and internally refactor lv_img_set_angle() (angle parameter shall be multiplied by 10 in this case)?

**Comment by kisvegabor** [comment]
@BesitzeRuf It's nice to see you again! :slightly_smiling_face: 

It's a great idea! In v9 we can remove `lv_img_set_angle_precise` and keep only `lv_img_set_angle` using the 0.1° resolution.

**Comment by embeddedt** [comment]
> In v9 we can remove lv_img_set_angle_precise and keep only lv_img_set_angle using the 0.1° resolution.

Personally, I think we could still keep `lv_img_set_angle` as a macro in v9, as there's really not much maintenance needed for that and it'd be one less function to refactor on a major version upgrade.

**Comment by kisvegabor** [comment]
> Personally, I think we could still keep lv_img_set_angle as a macro in v9, as there's really not much maintenance needed for that and it'd be one less function to refactor on a major version upgrade.

True, but this way it won't follow the same logic as `lv_img_set_angle()`.

**Comment by GorgonMeducer** [comment]
I highly recommend using fixed-point (Q15) to represent angle. So you can keep using uint16_t and not necessarily force yourself to choose a precision (either 1° or 0.1°)

**Comment by kisvegabor** [comment]
@GorgonMeducer Do you mean 0.0 would mean 0° and 1.0  mean 360°?

**Comment by GorgonMeducer** [comment]
> @GorgonMeducer Do you mean 0.0 would mean 0° and 1.0 mean 360°?

No 1.0° means 1 degree. When using q16 to store angle, it means (-2π,2π) stored in int32_t

**Comment by kisvegabor** [comment]
I see. "So you can keep using uint16_t" made me think you are thinking in a 0..1 range. So it's Q16.15, right?

Do you have any idea how could a nice API look like for Q15.16? E.g.
```c
set_angle(arc, LV_Q(120,678)); //120.678°
```
?

**Comment by GorgonMeducer** [comment]
Q16 is Q15.16 actually, so the fractional part is 16bits.

Let me introduce what I have done to arm-2d and you can take it as a reference.

a. For getting a unified programmers' model, I use float in all APIs
b. arm-2d provides a macro to convert arc to the degree:

```c
#define ARM_2D_ANGLE(__ANGLE)  ((float)((float)(__ANGLE) * 3.1416926f / 180.0f))
```
c. In the implementation part which is transparent to users, fixed point (not only Q16 but also Q31) is used to store angles and conversion between floating-point and the fixed point is necessary:

```c
#define ONE_BY_2PI_Q31      341782637.0f
    int32_t             AngleFx = lroundf(fAngle * ONE_BY_2PI_Q31);
```

**Comment by kisvegabor** [comment]
In LVGL no `float` is used but it's just a minor difference. 

It'd great to have a way to keep it working with normal `int` argument too. 

It sounds ugly but I'm thinking about something like this:
```c
#define LV_FRACT(i, f) (i + (f << 16))

set_angle(10); //10°
set_angle(LV_FRACT(10, 5); //10.5°

void set_angle(uint32_t angle)
{
  uint32_t angle_int;
  uint32_t angle_fract;
  angle_int = angle & 0xffff;
  angle_fract = (angle >> 16) & 0xffff;
}
```

**Comment by GorgonMeducer** [comment]
@kisvegabor why not use Q16 directly?

```c
#define LV_FRACT(i, f) (f + (i << 16))
```

LV_FRACT(10, 5) means 10.5 in Q16

**Comment by kisvegabor** [comment]
> why not use Q16 directly?

How do you mean directly?


E.g.
```c
set_angle(10.5);  //Float, not allowed in lvgl
```

**Comment by GorgonMeducer** [comment]
How about introduce a macro to solve this problem:

```c
#define f2q16(__value)    (int32_t)((__value) * (float)((int32_t)1<<16))
```

Hence 

```c
void set_angle(int32_t);

set_angle( f2q16(10.5f)); 
````

**Comment by kisvegabor** [comment]
I feel like it's too much hack to avoid the obvious solution: `float`. 

Maybe we can approach it differently by introducing an `LV_USE_FLOAT` config option which changes the API of some widgets from `int` to `float`.

**Comment by GorgonMeducer** [comment]
It's up to you. My personal philosophy is, as long as we provide options for users, it is OK.

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Hi gabor, I hope this feature can be done on v9, can we reopen this issue?

**Comment by kisvegabor** [comment]
I've reopened it. 

We can implement it for sure. I think the blocking thing now it agree on a fractional parameter support format which is:
- not `float` to keep LVGL integer only
- not too verbose, such as `LV_FRACT(100, 25)`

Actually maybe we can use `float` but make it optional. E.g. 
```c
#if LV_USE_FRACTIONAL_COORDS
typedef lv_coord_fract_t float;
#else
typedef lv_coord_fract_t lv_coord_t;
#endif
``` 

And use `lv_coord_fract_t` in APIs. This way to user can pass `100.25f` or `100` easily. 

The other option could be to have 2 APIs, e.g. `lv_arc_set_start_angle(arc, 100)` and `lv_arc_set_start_angle_fract(arc, 100, 25)`

This shoul affect line drawing too where we should be able to use fractional coordinates. 

What do you think?

**Comment by W-Mai** [comment]
Since we want to increase the precision but don't want to introduce float, why not extend the angle to int32_t and use [0, 36000) to represent [0, 360)? This way we can achieve a precision of one hundredth of a degree, and the performance will be more outstanding in any situation. This is much better than the previous 10% precision.😺

What do you think?

**Comment by FASTSHIFT** [comment]
@kisvegabor 
I prefer this approach over two separate APIs:
```c
#if LV_USE_FRACTIONAL_COORDS
typedef lv_coord_fract_t float;
#else
typedef lv_coord_fract_t lv_coord_t;
#endif
```
For products with high rendering effects and high precision requirements, MCUs with rich resources are generally selected, and such MCUs generally have FPU and GPU. We can consider introducing the float type, but this will make the design of the rendering layer more complicated.

From a simple point of view, whether the accuracy of 0.1 degrees (0-3600) or 0.01 degrees (0-36000) can meet most of the needs, without introducing too many complicated design and judgment branches, and can make `lv_img_set_angle` accuracy remains uniform.

**Comment by C47D** [comment]
I've seen this issue when working with arcs, is there some work/idea done for this?

**Comment by kisvegabor** [comment]
I think there should be a way to disable `float`s to have  smaller memory footprint if needed.

In case of arcs we need to define an angle with higher resolution.  We need an angle for image rotation too. Are the any  units other then degrees where we need higher resolution?

If not, what if add this to `lv_conf.h`:
```c
#define LV_ANGLE_FLOAT   1
```

Somewhere:
```c
#if LV_ANGLE_FLOAT
    typedef float lv_angle_t;
#else
    typedef int32_t lv_angle_t;
#endif
``` 

And in `lv_arc`:
```c
lv_arc_set_bg_start_angle(lv_obj_t * arc, lv_angle_t angle);
```

This way `lv_arc_set_bg_start_angle(arc, 40)` always works, but if you have enabled `LV_ANGLE_FLOAT`, the parameter can be e.g.  `40.3f` too.

Internally in drawing routines and a few other places we can add `#if LV_ANGLE_FLOAT` to handle the angles differently if needed. 

What do you think?

**Comment by kisvegabor** [comment]
Done by `LV_USE_FLOAT` and `lv_value_precise_t`
