### ISSUE TITLE
automatically adapt to different screen resolutions  

### ISSUE THREAD

**Issue by sj15712795029** [kisvegabor/lvgl#3096]
I have many different screens, but with different resolutions, can LVGL automatically adapt to different screen resolutions ?
Thanks~

**Comment by kisvegabor** [comment]
Yes, LVGL support responsive layouts which are inspired by CSS: https://docs.lvgl.io/master/layouts/index.html

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
