### ISSUE TITLE
Add LVGL Berry mapping repo

### ISSUE THREAD

**Issue by s-hadinger** [kisvegabor/lvgl#3106]
### Introduce the problem
I have created a mapping of LVGL to the [Berry language](https://github.com/berry-lang/berry), similarly to the Micropython mapping.

Berry is a lightweight object oriented language specifically designed for embedded devices. It has been used in the Tasmota open-source project for more than a year. It now has a full mapping to LVGL.

Supported version: LVGL v8.2.0

### Examples and cases
Example of code:

``` ruby
#- start LVGL and init environment (can be called multiple times) -#
lv.start()

hres = lv.get_hor_res()       # horizontal resolution of default display
vres = lv.get_ver_res()       # vertical resolution of default display

scr = lv.scr_act()            # default screen object

#- Background with a gradient from black #000000 (bottom) to dark blue #0000A0 (top) -#
scr.set_style_bg_color(lv.color(0x0000A0), lv.PART_MAIN | lv.STATE_DEFAULT)
scr.set_style_bg_grad_color(lv.color(0x000000), lv.PART_MAIN | lv.STATE_DEFAULT)
scr.set_style_bg_grad_dir(lv.GRAD_DIR_VER, lv.PART_MAIN | lv.STATE_DEFAULT)

t = lv.label(scr)
t.set_style_text_color(lv.color(0xFFFFFF), lv.PART_MAIN | lv.STATE_DEFAULT)
t.set_text("Hello LVGL + Berry!")
t.set_align(lv.ALIGN_TOP_MID)
```

### Suggested solution

The LVGL+Berry mapping is now available as a separate module, extracted from Tasmota. I would be happy to add it as a specific repo to the LVGL org.

Current module in Tasmota repo: https://github.com/arendst/Tasmota/tree/development/lib/libesp32_lvgl/lv_berry

Here is a more general page about LVGL in Tasmota https://tasmota.github.io/docs/LVGL/

**Comment by kisvegabor** [comment]
Thanks for the great work and offering to host it in the lvgl organization. I'm very open to open a repo for it! We should also add a page in the docs, similarly to [MicroPython](https://docs.lvgl.io/master/get-started/micropython.html). 

As the Berry binding is also autogenerated it seems the maintenance won't be an issue either.

Just out of curiosity, do you know how does the Berry and MicroPython runtime's flash size compare to each other? 

cc @amirgon

**Comment by s-hadinger** [comment]
The standard pre-compiled [Tasmota-LVGL](http://ota.tasmota.com/tasmota32/) firmware is ~1640kB. It includes Tasmota standard functions (Wifi, MQTT, WebUI, TLS, Berry...) with LVGL 8.2.0 + PNG + FreeType. It also comes with a "universal display driver", working with numerous SPI or I2C display drivers (ILI9341/9342, SH1106/1107, ePaper...)

This leaves some decent room for additional features on a typical 4MB Flash:  2x1800KB for OTA + 600 KB file system.

We provide a special "Partition Manager" to resize the partitions and file system once flashed.

**Comment by amirgon** [comment]
It's great to see another LVGL binding to a high level language!  
Nice work.

> Just out of curiosity, do you know how does the Berry and MicroPython runtime's flash size compare to each other?

We were discussing Micropython+LVGL program size on https://github.com/lvgl/lv_binding_micropython/issues/81.  
When I measured it on esp32, the entire FW image was ~2MB, where LVGL consumed 269 KiB (code + data), the bindings 110Kib (although this was heavily optimized, so probably much less now), Micropython core 133KiB, and the rest are esp-idf libraries, stdlib etc.

So lv_micropython on esp32 is ~20% larger in program size than Tasmota-LVGL.

I'm curios how Micropython and Berry compare in performance. Both are compiled into byte code so it comes down to how well optimized is the "vm" that runs the bytecode.  
@s-hadinger - do you have any insight about that?

> As the Berry binding is also autogenerated it seems the maintenance won't be an issue either.

I'm also trying to understand this.
Looking at https://github.com/arendst/Tasmota/commit/33a779f105beb4a42678ec0ff5ca0c95817d7b56, that's a huge commit just to upgrade from 8.1.0 to 8.2.0. I assume most changed files there are either LVGL sources or auto-generated files, right? What are the files that were manually fixed? @s-hadinger  could you elaborate on the effort and steps taken for this upgrade?   

I noticed that generated files seem to be committed instead of generated during the build process, and that LVGL is not a git submodule - instead LVGL sources are committed directly to Tasmota, which is different from what we do with in lv_micropython.

I also see LVGL specific code in the [conversion script](https://github.com/arendst/Tasmota/blob/c7ec0481d9274bd17e41243f512b40707a9dcb03/lib/libesp32_lvgl/lv_berry/tools/convert.py) so this Python script needs to change if, for example, LVGL adds or changes a type.

There is one thing that is not clear to me. I don't see any use of `user_data` for callbacks. On Micropython it was absolutely essential for restoring the context where the callback should be called. How this is done with Berry? Can you pass in Berry a class method or lambda function as an LVGL callback? Or only a global function as you do in C?

> It also comes with a "universal display driver", working with numerous SPI or I2C display drivers (ILI9341/9342, SH1106/1107, ePaper...)

This is interesting. @s-hadinger could you elaborate more about this?  
By "universal display driver" did you mean the [Adafruit LVGL Glue](https://github.com/arendst/Tasmota/tree/development/lib/libesp32_lvgl/Adafruit_LvGL_Glue-shadinger) or do you have some other display driver implementation?  
The Adafruit display driver is C/C++ code, how do you attach and configure it in Berry?

**Comment by s-hadinger** [comment]
Hi, lots of questions! Thanks for your interest in all this.

> We were discussing Micropython+LVGL program size on [lvgl/lv_binding_micropython#81](https://github.com/lvgl/lv_binding_micropython/issues/81).

I don't know the detailed breakdown of Flash consumption. I will read the thread and apply the same methodology.

> I'm curios how Micropython and Berry compare in performance. Both are compiled into byte code so it comes down to how well optimized is the "vm" that runs the bytecode.

I have no idea, and I don't think Skiars (author of Berry) did benchmarks. Berry's primary goal is to lower resource usage (Memory+Flash), not speed. The Berry VM is highly inspired from LUA VM, but simplified. As a control plane for LVGL, we haven't seen any speed bottleneck up to now. Happy to do benchmarks.

If I remember well, the Berry VM runs roughly at 1M instructions per second on ESP32 160MHz (of course complex instructions like calling a method are slower)

> Looking at [arendst/Tasmota@33a779f](https://github.com/arendst/Tasmota/commit/33a779f105beb4a42678ec0ff5ca0c95817d7b56), that's a huge commit just to upgrade from 8.1.0 to 8.2.0. I assume most changed files there are either LVGL sources or auto-generated files, right? What are the files that were manually fixed? @s-hadinger could you elaborate on the effort and steps taken for this upgrade?

> I also see LVGL specific code in the [conversion script](https://github.com/arendst/Tasmota/blob/c7ec0481d9274bd17e41243f512b40707a9dcb03/lib/libesp32_lvgl/lv_berry/tools/convert.py) so this Python script needs to change if, for example, LVGL adds or changes a type.

Indeed, adapting from 8.1.0 to 8.2.0 took 3-4 hours in total. The main parts to change are:
- `preprocessor.py`: adding some C headers to the parsed files
- `convert.py`: adding some new C types. The basic guess here is that it was possible to parse LVGL headers with regex. Actually the C code is clean enough to make this approach work.
- `lvgl_ctypes.be`: adpating and adding new C structures (this was the longest part)

All the rest is auto-generated.

> I noticed that generated files seem to be committed instead of generated during the build process, and that LVGL is not a git submodule - instead LVGL sources are committed directly to Tasmota, which is different from what we do with in lv_micropython.

Correct. We never use submodules in Tasmota. The bindings could be generated at compile time, this could be a future extension. But no real need for now.

> There is one thing that is not clear to me. I don't see any use of `user_data` for callbacks. On Micropython it was absolutely essential for restoring the context where the callback should be called. How this is done with Berry? Can you pass in Berry a class method or lambda function as an LVGL callback? Or only a global function as you do in C?

Excellent question. No we don't use `user_data` in the binding, so developers have it available. Berry has a fixed set of C callbacks (20 by default). For LVGL callbacks like `add_event_cb` we use the same C callbacks for all calls. The trick is that callbacks always contain a pointer to the associated `lv_obj_t` object. When we create a Berry callback for LVGL, we store in 2 global maps: 1/ a map from the `lv_obj_t` pointer to the Berry function/closure, 2/ a map from the `lv_obj_t` pointer to the target fully typed Berry object.

For example, here is the dispatcher for event callbacks: https://github.com/arendst/Tasmota/blob/77660b5d3c68ac5792066f4cb49423b11f654ef5/lib/libesp32_lvgl/lv_berry/src/embedded/lvgl_glob.be#L43-L53

> This is interesting. @s-hadinger could you elaborate more about this? By "universal display driver" did you mean the [Adafruit LVGL Glue](https://github.com/arendst/Tasmota/tree/development/lib/libesp32_lvgl/Adafruit_LvGL_Glue-shadinger) or do you have some other display driver implementation? The Adafruit display driver is C/C++ code, how do you attach and configure it in Berry?

It's not "Adafruit LVGL Glue", although we used it as a kickstarter in the beginning but moved progressively to the Universal Driver. There's not much left from it.
The "universal display" was created by Gemu. It's a templating system for SPI/I2C devices. The template contains the SPI intialization sequences and basic commands. It means that we have a unique firmware, and you just need to copy the adequate `display.ini` file in the file system.

The already available display templates are here: (ILI9341, ILI9342, ILI9488, Labon_L8, Odroid-go, SD1306, SH1106, SH1107, SSD1331, SSD1351, ST7735S, ST7789, WS_epaper29/42, WT32_SC01)

https://github.com/arendst/Tasmota/tree/development/tasmota/displaydesc

**Comment by s-hadinger** [comment]
About code size, I did quick comparison on a common base:

- Tasmota + Berry base without LVGL: 1216 KB
- Tasmota + Berry + LVGL: 1587 KB
- Tasmota + Berry + LVGL + PNG + Freetype: 1645 KB

So LVGL + Berry mapping account for 371 KB of Flash.

**Comment by kisvegabor** [comment]
> LVGL consumed 269 KiB (code + data), the bindings 110Kib (although this was heavily optimized, so probably much less now), Micropython core 133KiB

So it's exactly 512 kB. 

> So LVGL + Berry mapping account for 371 KB of Flash.

Compared to MicroPython the 371 kB not includes the Berry core. But I assume it's also 100..200 kB so LVGL with MicroPython or Berry has roughly the same size.


@s-hadinger I created  [lv_binding_berry](https://github.com/lvgl/lv_binding_berry) and invited you with "Maintain" permission (like "Admin" but without destructive action)

It's an empty repo, feel free the customize it including adding a description and README (don't hesitate to add an attribution to you and/or Tasmota).

**Comment by s-hadinger** [comment]
Thanks, I have copied the code and documentation to the repo.

**Comment by s-hadinger** [comment]
One more question, can I add Berry examples in https://github.com/lvgl/lvgl/tree/master/examples/widgets so that they may be added to the online documentation?

**Comment by kisvegabor** [comment]
> One more question, can I add Berry examples in https://github.com/lvgl/lvgl/tree/master/examples/widgets so that they may be added to the online documentation?

Yes, it'd be amazing!

@embeddedt What needs to be done to add a new language to the examples: 

BTW, the `Simulator`  in docs for the MP examples is not working now. Could you take a look?

**Comment by embeddedt** [comment]
> BTW, the Simulator in docs for the MP examples is not working now. Could you take a look?

I'm aware, it should fix itself the next time @amirgon updates `lv_binding_micropython`. The reason for the issue is that there is no version of MicroPython using 8.3-dev, and that is the version the docs attempt to link to (they use whatever's in `lvgl.h`).

**Comment by amirgon** [comment]
> it should fix itself the next time @amirgon updates `lv_binding_micropython`

Done.

**Comment by kisvegabor** [comment]
Thanks, @amirgon!

**Comment by kisvegabor** [comment]
@s-hadinger can we close this issue?

**Comment by s-hadinger** [comment]
Sure. Actually https://github.com/lvgl/lv_binding_berry is still private. Anything missing to move it to public?

**Comment by kisvegabor** [comment]
Oh, I haven't noticed that it's private. Probably I created a private repo by accident. I just made it public.

**Comment by s-hadinger** [comment]
Thanks, closing now.

**Comment by kisvegabor** [comment]
Meanwhile I updated the Getting started section of the docs to have section for [Bindings](https://docs.lvgl.io/master/get-started/bindings/index.html). If you wish feel free to send a PR to add a page for Berry
