### ISSUE TITLE
A table issue...

### ISSUE THREAD

**Issue by zirobin** [kisvegabor/lvgl#3120]
I create a table with 8 cols 8 rows， in some cases,  I change the table to 4 cols and 4 rows , but it hangup. 

The LVGL version is the lastest release.
`  

    lv_obj_t * table;
    uint32_t i, j;
    
    table = lv_table_create(lv_scr_act());

    lv_obj_center(table);

    lv_table_set_col_cnt(table, 8);
    lv_table_set_row_cnt(table, 8);

    for (i = 0; i < 8; i ++) {
        for (j = 0; j < 8; j ++) {
            lv_table_set_cell_value(table, i, j, "00");
        }
    }

    lv_table_set_col_cnt(table, 4); //If comment this line, it can run
    lv_table_set_row_cnt(table, 4);

    for (i = 0; i < 4; i ++) {
        for (j = 0; j < 4; j ++) {
            lv_table_set_cell_value(table, i, j, "00");
        }
    }
`

**Comment by C47D** [comment]
Is there any interesting output when enabling the logs?

**EDIT**
I was able to replicate an issue with the code snippet, see #3121 for reference.

**Comment by C47D** [comment]
@ay123net can you set the row count before setting the column count and report back if you still have the issue? Something like this:

```c
lv_obj_t * table;
uint32_t i, j;

table = lv_table_create(lv_scr_act());

lv_obj_center(table);

lv_table_set_row_cnt(table, 8);
lv_table_set_col_cnt(table, 8);

for (i = 0; i < 8; i ++) {
    for (j = 0; j < 8; j ++) {
        lv_table_set_cell_value(table, i, j, "00");
    }
}

lv_table_set_row_cnt(table, 4);
lv_table_set_col_cnt(table, 4);

for (i = 0; i < 4; i ++) {
    for (j = 0; j < 4; j ++) {
        lv_table_set_cell_value(table, i, j, "00");
    }
}
```

**Comment by ay123net** [comment]
> @ay123net can you set the row count before setting the column count and report back if you still have the issue? Something like this:
> 
> ```c
> lv_obj_t * table;
> uint32_t i, j;
> 
> table = lv_table_create(lv_scr_act());
> 
> lv_obj_center(table);
> 
> lv_table_set_row_cnt(table, 8);
> lv_table_set_col_cnt(table, 8);
> 
> for (i = 0; i < 8; i ++) {
>     for (j = 0; j < 8; j ++) {
>         lv_table_set_cell_value(table, i, j, "00");
>     }
> }
> 
> lv_table_set_row_cnt(table, 4);
> lv_table_set_col_cnt(table, 4);
> 
> for (i = 0; i < 4; i ++) {
>     for (j = 0; j < 4; j ++) {
>         lv_table_set_cell_value(table, i, j, "00");
>     }
> }
> ```

**Comment by zirobin** [comment]
@C47D Hi, It test pass in LVGL version 8.0.3, but the lastest version 8.2.0 is fail
