### ISSUE TITLE
CI test for flash/RAM usage

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#3127]
### Introduce the problem

Inspired by the [this comment](https://github.com/zephyrproject-rtos/zephyr/pull/41336#issuecomment-1048606407) in Zephyr.
It'd be important to know that there is an already usable configuration in which LVGL has < 64kB flash usage (should be close to 48 kB) and test it with CI.  

We can have 2-3 tests like:
1. Very minimal: e.g. only button, label, image, `LV_DRAW_COMPLEX = 0`
2. Normal: general case with 5-10 widgets
3. Almost everything enabled

### Suggested solution

What do you think what would be the best way to fit something like this into or CI process?

**Comment by embeddedt** [comment]
We can probably just use `arm-none-eabi-gcc` with a fake linker script on a couple examples/demos and measure the size of the binary that's produced (it doesn't need to actually run). Obviously we'd have to set slightly lower thresholds for the sizes since there wouldn't be any drivers included.

**Comment by kisvegabor** [comment]
Great! Is it complicated?

> Obviously we'd have to set slightly lower thresholds for the sizes since there wouldn't be any drivers included.

But we still should create a display and input device to be sure the linker won't eliminate those functions.

**Comment by kisvegabor** [comment]
Continue in https://github.com/lvgl/lvgl/issues/5396
