### ISSUE TITLE
Roller Behavior with animation

### ISSUE THREAD

**Issue by arturv2000** [kisvegabor/lvgl#3132]
### Perform all steps below and tick them with [x]
- [ X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When setting a new value for a ROLLER object with animation, the object behavior is strange, not quite as I expected. 

Check the Video. Was expecting the "ITEM" to scroll directly, without what seems as a first scroll to the first item and then jumping to the selected item.

Tested on target and on simulator.

### To Reproduce
```c
//After lvgl init
my_ui_test();

while (!lv_win32_quit_signal)
    {
        lv_task_handler();
        Sleep(1);

        if ((GetTickCount() - _ticks) > 1000) {
            _ticks = GetTickCount();
            _counter++;
            lv_roller_set_selected(roller1, (_counter % 12), LV_ANIM_ON);

        }
    }
```

```c
void my_ui_test(void)
{
    roller1 = lv_roller_create(lv_scr_act());
    lv_roller_set_options(roller1,
        "January\n"
        "February\n"
        "March\n"
        "April\n"
        "May\n"
        "June\n"
        "July\n"
        "August\n"
        "September\n"
        "October\n"
        "November\n"
        "December",
        LV_ROLLER_MODE_INFINITE);

    lv_roller_set_visible_row_count(roller1, 4);
    lv_obj_center(roller1);
}
```

### Expected behavior

The object should jump between items without what it seems, is a jump to the first "item" and then jump to the correct "item".

### Screenshots or video

Video with current behavior:
https://user-images.githubusercontent.com/17281826/155772229-af7e414e-d85d-4078-a34f-a7bd904edfb0.mp4

Video with expected behavior (quick fix, but not working for all cases)
https://user-images.githubusercontent.com/17281826/155773202-1841f792-277e-4261-8d9f-c781041efc5b.mp4

**Comment by kisvegabor** [comment]
Hi,

It was really buggy. I've pushed a fix.
