### ISSUE TITLE
lv_obj_set_base_dir() not defined

### ISSUE THREAD

**Issue by fallaha** [kisvegabor/lvgl#3134]
### Perform all steps below and tick them with [x]
- [ x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I tried to use lv_obj_set_base_dir() function to change base direction from LTR to RTL but simulator tell me that this function not defined.
also when I searched this function in the code no result found.
not reported any issue or not exist any changelog about this function.

**Comment by kisvegabor** [comment]
In v8 it's already a style property:
```c
  lv_obj_set_style_base_dir();
  lv_style_set_base_dir();
```
