### ISSUE TITLE
Image zoom

### ISSUE THREAD

**Issue by Miguel0101** [kisvegabor/lvgl#3141]
Is there any way to use `lv_pct` in `lv_img_set_zoom`?

**Comment by PGNetHun** [comment]
Please ask questions in forum: https://forum.lvgl.io/

**Comment by kisvegabor** [comment]
Questions really should go to the Forum so I close this issue. If you link the opened Forum topic here, I'd happy to answer there.

**Comment by Miguel0101** [comment]
Forum link: https://forum.lvgl.io/t/image-zoom-with-percentage/8388
Now I will always open the issues on the forum.
