### ISSUE TITLE
Long screen scrolling limits

### ISSUE THREAD

**Issue by FarawayRay** [kisvegabor/lvgl#3143]
When the length of a page exceeds the height of the screen, the scroll attribute will be added by default. If the long page slides to the beginning, I need to cancel the scroll and listen to press, pressing and release events, what should I do

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

From the description, I couldn't really imagine what would be the goal, so please add a more detailed description.
