### ISSUE TITLE
fs_stdio: fs_seek issue when cached enabled

### ISSUE THREAD

**Issue by Ryzee119** [kisvegabor/lvgl#3148]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
lv_set_seek does not correctly return the file pointer when `LV_FS_STDIO_CACHE_SIZE` is set.

I happened to be using the STDIO backend, however it likely would happen with other backends too.

### To Reproduce
* Set `LV_FS_STDIO_CACHE_SIZE` to a non zero number.
* Create a sample file with some data. i.e a text file with "Hello World".
* Run this test code:
```
lv_fs_file_t fp;
uint32_t file_size;
lv_fs_open(&fp, "A:test.txt", LV_FS_MODE_RD);
lv_fs_seek(&fp, 6, LV_FS_SEEK_SET); //Set file pointer to the beginning of "World"
lv_fs_seek(&fp, 0, LV_FS_SEEK_SET); //Return file pointer to start. Reads should start from 0 now.

uint8_t data[256];
uint32_t br;
lv_fs_read(&fp, data, 12, &br); //Should readback "Hello World" but it returns "World"
lv_log(data);
```

### Expected behavior
Expected result is ofcourse `"Hello World"`, but it returns `"World"` (plus garbage) in this test case.

Seems to be falling over here i think?
https://github.com/lvgl/lvgl/blob/ff0bf6386d702ff9f32528fe6296c8da326c9914/src/misc/lv_fs.c#L261

**Comment by kisvegabor** [comment]
Hi,

thanks for reporting this issue. I pushed a fix.
