### ISSUE TITLE
Getting LVGL version when using it in a CMake-based project

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#3152]
### Introduce the problem
It is not currently possible to know/get the LVGL version (major, minor, patch) when using it in a CMake-based project.

### Examples and cases
In `lv_port_esp32` we have some API implementations that depends on the LVGL version, instead of having `#if`, `#else`, `#endif` blocks I would like to have separated source files and compiling/link them depending on the LVGL version being used.

### Suggested solution
Have a file named `version.cmake` and expoer cmake variables from there,

**Comment by kisvegabor** [comment]
Sounds reasonable.
I see no problem with adding `version.cmake` [here](https://github.com/lvgl/lvgl/tree/master/env_support/cmake).
