### ISSUE TITLE
Images cannot be partially captured

### ISSUE THREAD

**Issue by denghengli** [kisvegabor/lvgl#3168]
Introduce the problem
cannot capture a specified small icon from a large BMP or PNG image that consists of multiple small icon images

Examples and cases
![96db7537bcb4e1a14d2d47c179cfa88](https://user-images.githubusercontent.com/40051103/158060698-193c8448-0d68-4024-8882-0b8fd75544a5.png)
Like this, how do you take the "watermelon" icon off the whole picture and use it as a separate image

Suggested solution
It is suggested to add the function of capturing local data of pictures, which is very practical in actual project development. If there are a lot of small pictures, it is very troublesome to burn the picture to the external FLASH in the production process. If you support partial reading of pictures, only a few pictures need to be burned or even only one picture can be installed, which can greatly shorten the production time of burning and writing pictures

**Comment by FASTSHIFT** [comment]
```c
lv_obj_t* img = lv_img_create(lv_scr_act());
lv_img_set_src(img, src);
lv_obj_set_size(img, icon_width, icon_height);
lv_img_set_offset_x(img, offset_x);
lv_img_set_offset_y(img, offset_y);
```
