### ISSUE TITLE
[lv_chart]: Is it possible to update update only part of chart?

### ISSUE THREAD

**Issue by FlashForger** [kisvegabor/lvgl#3170]
### Introduce the problem
I'm using bar type chart for showing music spectrum analyzer. As a result I need to refresh the bars realy often. On stm32f303+ili9341 (320*240) the resulting fps for two charts is 6 FPS.

### Suggested solution
I wanted to save the values of bars that are already on screen so that I can update only those bars that needed to be updated. The problem is I have two 10row buffers and the bar values are calculated multiple times during one full refresh. Is there a solution here for getting more fps from chart refresh in case I need to only refresh certain bars?

P.S. Tried to do that with Bar widget but 20 bars take lot more space in memory then one chart with 20 bars.

**Comment by kisvegabor** [comment]
You can use `lv_chart_get_y_array(chart, ser)` to get the array where the values of the chart are stored. 
If you update it manually LVGL won't notice it so you can add you own refresh mechanism.

`lv_obj_invalidate_area(chart, &area);` can be used to manually make an an area on a widget invalid.
