### ISSUE TITLE
There is no low-level interface for accelerating Tiling (paving img in a given area) 

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3174]
### Introduce the problem
Usually, DMA based HW accelerators such as [DMA-350 from Arm](https://developer.arm.com/documentation/102482/0000/Overview/Key-features?lang=en) (and other similar 2D capable DMA) can accelerate tiling easily and hence offload CPU. But in LVGL, this work is done by [repeatedly calling `lv_draw_img()`](https://github.com/lvgl/lvgl/blob/16a1af38733ce8f06ef70615f7b55249d410221d/src/draw/sw/lv_draw_sw_rect.c#L388). 

![image](https://user-images.githubusercontent.com/13148491/158630363-f6bb7e68-f545-4fd3-b966-8f89c5b53b83.png)

### Suggested solution
It would be good to add a low-level interface for tiling with mirroring features, i.e. no-mirroring, x-mirroring, y-mirroring and xy-mirroring. 

By the way, arm-2d has a corresponding API for the feature aforementioned. By adding this interface, we can immediately take advantage of arm-2d acceleration without waiting for MCUs with such 2D-capable DMA.

**Comment by kisvegabor** [comment]
Tiling seems too high level for me at first look. E.g. a "tile" can have all the image effects, such as:
- rotation
- scale
- re-coloring
- chromakeying
- LVGL masking (e.g. to clip to a cricle)

It seems the API could be used only if a the image should be displayed as it is (i.e. no transformation).

What do you think?

**Comment by GorgonMeducer** [comment]
The tiling here just means: repeatedly paving the source image to a target area of the display buffer with at most some mirroring feature. No scale, no recolouring.

This is the kind of work that a 2D-capable-DMA is good at. 

Arm-2D support tiling with chromakeying and masking. See [**4.2 Copy, Fill and X/Y Mirroring**](https://github.com/ARM-software/EndpointAI/blob/master/Kernels/Research/Arm-2D/documents/how_to_use_tile_operations.md#42-copy-fill-and-xy-mirroring)

**Comment by kisvegabor** [comment]
I see.  I thin kit covers most of the typical use cases. 

However, let's postpone it little until the transform API is implemented :slightly_smiling_face:

**Comment by GorgonMeducer** [comment]
Yeah, we are also waiting for the transform API.

**Comment by kisvegabor** [comment]
Closing in favor of #4733.
