### ISSUE TITLE
How can I set the label to center or change the style

### ISSUE THREAD

**Issue by Kingwulin** [kisvegabor/lvgl#3175]
demo ：[simple-menu-with-custom-header](https://docs.lvgl.io/master/examples.html#simple-menu-with-custom-header)
what I want to do is the images below
I found that was not any action when I change the style of menu or label
would please tell me how to achive it 
Thanks
 
![image1](https://user-images.githubusercontent.com/16952072/158791847-5d583b79-d9f4-4010-8604-783157eaafa0.png)
![image2](https://user-images.githubusercontent.com/16952072/158791887-786b2a53-65b1-4e54-966b-45f8e8162de6.png)

**Comment by kisvegabor** [comment]
cc @HX2003

**Comment by Kingwulin** [comment]
What I want to achieve is the page jump
for example：page1->page2,then press back btn, page2->page1
Is there any other component suitable for this function?

**Comment by HX2003** [comment]
> What I want to achieve is the page jump for example：page1->page2,then press back btn, page2->page1 Is there any other component suitable for this function?

Is the question only about styling? How did you change the style?
If I understand correctly, if you just want the labels centered then you can apply `lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);` to the menu_page and menu_cont.
