### ISSUE TITLE
Adding an OPTION dynamically to ROLLER

### ISSUE THREAD

**Issue by GARBAGE-WALL-E** [kisvegabor/lvgl#3180]
Is there any way to add an option dynamically to roller without updating the entire list of 
options? 
lv_roller_set_options(roller, options, LV_ROLLER_MODE_NORMAL/INFINITE);

**Comment by kisvegabor** [comment]
There is no option for that now.

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
