### ISSUE TITLE
What is the reason for canceling lv_cont and lv_page, it is more difficult to upgrade the project from 7.7 to 8.0 ？

### ISSUE THREAD

**Issue by senlinding** [kisvegabor/lvgl#3197]
What is the reason for canceling lv_cont and lv_page, it is more difficult to upgrade the project from 7.7 to 8.0 ？

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.  

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

You can copy it's link here. I'll answer in the Forum.
