### ISSUE TITLE
 How to bind a variable to a dynamically created component.  

### ISSUE THREAD

**Issue by zhangchaomin** [kisvegabor/lvgl#3201]
### How to bind a variable to a dynamically created component.  
I can't get obJ in animation . I can't get IndiC in events

I didn't know I could get obj in the animation callback function. 
 I don't know how to get IndiC in the event callback function  .
![()05@(MDK99M$BAI)B E2](https://user-images.githubusercontent.com/26653019/159660171-b7314f71-3c35-471d-a98b-612285cebe49.png)
![WGLC}L5ZBY)E8EHI0$2N(YP](https://user-images.githubusercontent.com/26653019/159660511-d9f9e7f1-383d-4570-9bb8-54347fab6982.png)

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
