### ISSUE TITLE
Memory starvation when using round object with shadows

### ISSUE THREAD

**Issue by bosiden** [kisvegabor/lvgl#3206]
### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Memory starvation occurs when drawing a round object (~220x220) with shadows, even when using large LV_MEM size of >42k

### To Reproduce

```c
lv_obj_t* shadowGradient = lv_obj_create(lv_scr_act());
lv_obj_remove_style_all(shadowGradient);
lv_obj_set_size(shadowGradient, 200, 200); 

lv_obj_set_style_radius(shadowGradient, LV_RADIUS_CIRCLE, 0);
lv_obj_set_style_shadow_width(shadowGradient,30, 0);
lv_obj_set_style_shadow_color(shadowGradient, lv_color_black(), 0);
lv_obj_align(shadowGradient, LV_ALIGN_CENTER, -2, 0);
```

### Expected behavior

A nice round circle should be drawn with beautiful shadows.

**Comment by kisvegabor** [comment]
It's sad but it's the expected behavior. :slightly_frowning_face: 

Drawing shadow on such a large circle needs a larger amount of RAM.
