### ISSUE TITLE
LV_USE_GRIDNAV missing in Kconfig

### ISSUE THREAD

**Issue by itavero** [kisvegabor/lvgl#3207]
### Describe the bug
I'm using LVGL as a component in ESP-IDF and I noticed that I can't enable Grid navigation via menuconfig.
Upon further investigation, it turns out `LV_USE_GRIDNAV` is missing from `Kconfig`.

**Comment by kisvegabor** [comment]
Hi,

Could you send a Pull request?

**Comment by itavero** [comment]
Sure. I'll create one.

**Comment by kisvegabor** [comment]
Fixed by #3270.

Thank you!
