### ISSUE TITLE
Prioritization of GESTURE and CLICKED events

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3211]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The gesture event is registered at the root node of the screen, and the click event is registered on the button. When the screen slides, the click event of the button is also triggered.

### To Reproduce
```c
static void scr_event_cb(lv_event_t* event)
{
    LV_LOG_USER("LV_EVENT_GESTURE");
}

static void btn_event_cb(lv_event_t* event)
{
    LV_LOG_USER("LV_EVENT_CLICKED");
}

static void swipe_test(void)
{
    lv_obj_t* btn = lv_btn_create(lv_scr_act());
    lv_obj_set_width(btn, 100);
    lv_obj_center(btn);
    lv_obj_add_event_cb(btn, btn_event_cb, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(lv_scr_act(), scr_event_cb, LV_EVENT_GESTURE, NULL);
}

```

### Expected behavior
Is it possible to prevent the click event when the gesture event occurs? Or is there any way to avoid it?

### Screenshots or video

https://user-images.githubusercontent.com/26767803/160332393-88442a26-5fcd-4eb5-98a2-24d47c7d4279.mp4

**Comment by FASTSHIFT** [comment]
I tried to clear the `LV_OBJ_FLAG_PRESS_LOCK` flag, but the click still triggers.

https://user-images.githubusercontent.com/26767803/160333823-e312a052-fa70-4698-ba3d-301b3655f58f.mp4

**Comment by kisvegabor** [comment]
It makes sense. 
We an use `proc->types.pointer.gesture_sent` to skip sending some events if the a gesture was fired.

**Comment by FASTSHIFT** [comment]
> gesture_sent

Can this variable be accessed and modified at the application layer? How should it be modified?

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Did you mean this:
```c
static void event_cb(lv_event_t* event)
{
    lv_event_code_t code = lv_event_get_code(event);
    lv_indev_t* indev = lv_indev_get_act();

    uint8_t gesture_sent = indev ? indev->proc.types.pointer.gesture_sent : 0;

    if (code == LV_EVENT_CLICKED)
    {
        LV_LOG_USER("LV_EVENT_CLICKED, gesture_sent = %d", gesture_sent);
    }
    else if (code == LV_EVENT_GESTURE)
    {
        LV_LOG_USER("LV_EVENT_GESTURE, gesture_sent = %d", gesture_sent);
    }
}
```
Check the status of the `gesture_sent` flag at clicked event.

**Comment by kisvegabor** [comment]
I meant adding `if`s in LVGL itself (`lv_indev.c`) to not fire `PRESSING`, `CLICKED` events, but I've just realized it's not a good idea as it's not sure that the use was interested in the gestures.

I haven't tested it but `lv_indev_get_gesture_dir(lv_indev_act()) == LV_DIR_NONE` should indicate that there was no gesture.

**Comment by FASTSHIFT** [comment]
> I meant adding `if`s in LVGL itself (`lv_indev.c`) to not fire `PRESSING`, `CLICKED` events, but I've just realized it's not a good idea as it's not sure that the use was interested in the gestures.
> 
> I haven't tested it but `lv_indev_get_gesture_dir(lv_indev_act()) == LV_DIR_NONE` should indicate that there was no gesture.

Is it possible to add `FLAG` to the user to choose?

**Comment by kisvegabor** [comment]
The best would be if we seen that the gesture was "consumed" and if so click, press etc weren't send. But we don't know it s the user should the tell to the indev handler to skip these events.

What about calling `lv_indev_wait_release(lv_indev_act())` from the event handler of the gesture?

**Comment by FASTSHIFT** [comment]
> The best would be if we seen that the gesture was "consumed" and if so click, press etc weren't send. But we don't know it s the user should the tell to the indev handler to skip these events.
> 
> What about calling `lv_indev_wait_release(lv_indev_act())` from the event handler of the gesture?

I tested it and it works as expected.

**Comment by kisvegabor** [comment]
Great! If you find it a suitable solution, feel free to close this issue. 

If you agree it's ok this way, I'll add a note about this method here: https://docs.lvgl.io/master/overview/indev.html#gestures

**Comment by FASTSHIFT** [comment]
> Great! If you find it a suitable solution, feel free to close this issue.
> 
> If you agree it's ok this way, I'll add a note about this method here: https://docs.lvgl.io/master/overview/indev.html#gestures

OK

**Comment by kisvegabor** [comment]
The docs is updated too.

**Comment by FASTSHIFT** [comment]
@kisvegabor 
The widget's state doesn't seem to automatically transition correctly.
lv_btn does not properly exit `LV_STATE_PRESSED` state.

https://user-images.githubusercontent.com/26767803/166685179-95622ec6-bcc0-4348-b0ff-d77776aee590.mp4

```c
static void event_cb(lv_event_t* event)
{
  lv_event_code_t code = lv_event_get_code(event);
  if(code == LV_EVENT_GESTURE)
  {
    LV_LOG_USER("LV_EVENT_GESTURE");
    lv_indev_wait_release(lv_indev_get_act());
  }
  else if(code == LV_EVENT_CLICKED)
  {
    LV_LOG_USER("LV_EVENT_CLICKED");
  }
}

void gesture_test(void)
{
  lv_obj_t* btn = lv_btn_create(lv_scr_act());
  lv_obj_clear_flag(btn, LV_OBJ_FLAG_GESTURE_BUBBLE);
  lv_obj_set_size(btn, 200, 200);
  lv_obj_center(btn);
  lv_obj_add_event_cb(btn, event_cb, LV_EVENT_ALL, NULL);
}
```

**Comment by kisvegabor** [comment]
I'm thinking about solving it by sending `LV_EVENT_PRESS_LOST` in `lv_indev_wait_release()` for the active object. What do you think?

**Comment by FASTSHIFT** [comment]
> I'm thinking about solving it by sending `LV_EVENT_PRESS_LOST` in `lv_indev_wait_release()` for the active object. What do you think?

Will `lv_indev_wait_release()` emit `LV_EVENT_PRESS_LOST` event?

**Comment by kisvegabor** [comment]
Yes, I meant that.

**Comment by FASTSHIFT** [comment]
> Yes, I meant that.

Sounds good, I agree with this.

**Comment by kisvegabor** [comment]
Added, please test it. :slightly_smiling_face:

**Comment by FASTSHIFT** [comment]
It works fine, thank you.

**Comment by kisvegabor** [comment]
Great!

**Comment by mmar22** [comment]
Hi boys, nice debate, but not aplyed in Squareline. I create on screen event clicked and gesture UP.
On gesture always is fired clicked too. ???

**Comment by kisvegabor** [comment]
Finally we have decided that you can call `lv_indev_wait_relelase(lv_indev_act())` in the gesture.

**Comment by mmar22** [comment]
In Squareline I call nothing. Events is added without call. Your generator need add it in ui.c or perfect is place some checkbox , that define on event wait...

**Comment by kisvegabor** [comment]
Okay, we can add it in SLS.
