### ISSUE TITLE
lvgl can Gaussian blur be supported?

### ISSUE THREAD

**Issue by jianjunxia** [kisvegabor/lvgl#3213]
Can lvgl support Gaussian blur? In this way, we can better deal with the characteristics of some pictures

**Comment by kisvegabor** [comment]
For performance reasons now you can perform only box-blur. However. in practice performing box-blur twice looks quite similar to Gaussian blur.

---
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by jianjunxia** [comment]
> For performance reasons now you can perform only box-blur. However. in practice performing box-blur twice looks quite similar to Gaussian blur.
> 
> We use GitHub Issues for development-related discussions.
> 
> Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

thanks

**Comment by jianjunxia** [comment]
> 

why you say "For performance reasons now you can perform only box-blur"?
and do you have a useful third-party library or example? i want to test
thanks！

**Comment by kisvegabor** [comment]
> why you say "For performance reasons now you can perform only box-blur"?

Because box-blur is much simpler, thus faster.

> and do you have a useful third-party library or example? 

Please open a Forum topic, link it here, and I'll answer there.

**Comment by jianjunxia** [comment]
> > why you say "For performance reasons now you can perform only box-blur"?
> 
> Because box-blur is much simpler, thus faster.
> 
> > and do you have a useful third-party library or example?
> 
> Please open a Forum topic, link it here, and I'll answer there.


it's here https://forum.lvgl.io/t/how-to-implement-this-feature-in-lvgl-with-background-filter-blur-60px-in-css/8591?u=jianjunxia
