### ISSUE TITLE
Large option list in roller has incorrect behavior

### ISSUE THREAD

**Issue by jbarrena** [kisvegabor/lvgl#3214]
Hi,

I am using two rollers to input time. The minutes roller has 60 options and hour 12 options. The minutes roller is printed incorrectly, like if it had some spaces between options.

The code below reproduces tyhe bug in simulator:
```c
lv_roller_set_options(me->rlrHour,"01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12",
        	LV_ROLLER_MODE_INFINITE);
     lv_roller_set_visible_row_count(me->rlrHour, 1);
    lv_obj_set_height(me->rlrHour, 36); // Force height because it does not manage well font height
    lv_roller_set_selected(me->rlrHour, 0, LV_ANIM_OFF); // Select by default first item
    lv_group_add_obj(me->grpText, me->rlrHour);
    lv_obj_add_event_cb(me->rlrHour, onTimeEvent, LV_EVENT_KEY, me);
```

```c
lv_roller_set_options(me->rlrMinute,"01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n"
    									"11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n"
    									"21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n"
    									"31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n"
    									"41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n"
    									"51\n52\n53\n54\n55\n56\n57\n58\n59",
        LV_ROLLER_MODE_INFINITE);
    
    lv_roller_set_visible_row_count(me->rlrMinute, 1);
    lv_obj_set_height(me->rlrMinute, 36); // Force height because it does not manage well font height
    lv_roller_set_selected(me->rlrMinute, 0, LV_ANIM_OFF); // Select by default first item
    lv_group_add_obj(me->grpText, me->rlrMinute);
    lv_obj_add_event_cb(me->rlrMinute, onTimeEvent, LV_EVENT_KEY, me);
```
This is how it prints the options in the rollers. Expected is the roller in the left, and the right one represents the incorrect behavior.
![irudia](https://user-images.githubusercontent.com/43204123/160411417-744802fb-f162-4ca7-9727-823a9adeff22.png)

Thanks for your help.

Julen.

**Comment by embeddedt** [comment]
Sometimes enabling [`LV_USE_LARGE_COORD`](https://github.com/lvgl/lvgl/blob/9a0a74813d86c897859a33f49d477352ebf5823b/lv_conf_template.h#L323) fixes this, although I'm surprised you'd see the issue with only 60 options.

**Comment by jbarrena** [comment]
Thank you for your help! It works now.

As I described, with 60 point in LV_ROLLER_MODE_INFINITE it didn't work properly.

Thanks again!

Julen.

**Comment by SpaceTeddy** [comment]
same here.
with ESP32 and roller >29 items output is not like it should.

sers,
Chris

**Comment by kisvegabor** [comment]
I've pushed an update which automatically calculates the required number of extra "pages" in infinite mode. It targets 1000 px height but adds 3 pages at least .
