### ISSUE TITLE
How a label has the effect of being selected in a group like a button

### ISSUE THREAD

**Issue by Kingwulin** [kisvegabor/lvgl#3216]
I am using the encoder as an input device
I had add the label to the group by "lv_group_add_obj"
I found onlay can select button sliber ..
but the label and image has not that effection,how can I slove it

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
