### ISSUE TITLE
PubSub messaging

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#3218]
### Introduce the problem
There is no clear way to send/receive messaged to/from the UI and between UI components.

### Examples and cases
While implementing UIs for clients I always run into the problem of creating an API for the UI. As there is no standard way of doing it in LVGL I always do what feels the best for the given project.  But sometimes it leads to messy `get/set` calls, messy architecture, messy dependencies and references, and exposing the internals of the UI. 

The other problem is when unrelated parts of the UI needs to use the same input value, let's say the target temperature:
- a label displays it
- a slider sets the temperature
- a warning icon is show on too high temperature

### Suggested solution
I suggest implementing a simple publisher-subscriber system. It could look like this:
```c
#define MSG_SET_VENT_ON 21
#define MSG_SET_VENT_OFF 22
#define MSG_SET_TEMP 23
#define MSG_SET_STATUS 24

lv_msg_subsribe(MSG_SET_TEMP, my_callback_1);
lv_msg_subsribe_obj(MSG_SET_TEMP, temp_bar); //Send `LV_EVENT_MSG_RECEIVED` event on new msg

lv_msg_send(MSG_SET_VENT_ON);   //No parameter
lv_msg_send_int(MSG_SET_TEMP, 22);
lv_msg_send_str(MSG_SET_STATUS, "Too high temperature");
lv_msg_send_ptr(MSG_USER_LIST_CHANGES, users); //user_t users[100]

void my_callback_1(lv_msg_t * m)
{
  if(lv_msg_get_id(m) == MSG_SET_TEMP) {
    int32_t v = lv_msg_get_int(m);
    print("temp: %d\n", v);  
  } 
}

void temp_bar_event_cb(lv_event_t * e)
{
  if(lv_event_get_code(e) == LV_EVENT_MSG_RECEIVED) {
       if(lv_msg_get_id(m) == MSG_SET_TEMP) {
       int32_t v = lv_msg_get_int(m);
       lv_bar_set_value(lv_event_get_target(e), v, LV_ANIM_OFF);  
  } 
}
```

It's not standard PubSub stuff but we also need a way to request a "Publish" in some cases. E.g. if a new screen is opened which needs to show the temperature we need to get message with the current temperature. For this we can do something like:
```c
lv_msg_request_subscribe(my_callback_2);  //Get the requests and serve them

void my_callback(lv_msg_id_t id)
{
  if(id == MSG_SET_TEMP) {
     lv_msg_send_int(MSG_SET_TEMP, temp_current);
  }
}

lv_msg_request(MSG_SET_TEMP);
```

And that's it. Quite simple and would solve a ton of problem. What do you think?

**Comment by FASTSHIFT** [comment]
Is it possible to unify the data format sent to facilitate the expansion of parameters, like this:
```c
my_data_t my_data;
my_data.xxx = xxx;
my_data.yyy = yyy;
lv_msg_send(MSG_XXX, &my_data, sizeof(my_data));
```
This is the implementation of my [subscription publishing framework](https://github.com/FASTSHIFT/X-TRACK/tree/main/Software/X-Track/USER/App/Utils/DataCenter).

**Comment by kisvegabor** [comment]
> Is it possible to unify the data format sent to facilitate the expansion of parameters, like this:

I meant to use `lv_msg_send_ptr(MSG_XXX, &my_data)` for this purpose.

**Comment by kisvegabor** [comment]
I've just implemented it: [5c8eb783](https://github.com/lvgl/lvgl/commit/79a29d749d3e261ebadbe31fccbff896f63b4d93)
Finally the API became a little bit simpler.

**Comment by GiulioDallaVecchia** [comment]
Hi @kisvegabor,
we should use a generic msg object like this:

```
typedef struct lv_msg_tag {
  uint32_t signal;
}lv_msg_t
```

Then you can create new message type from this (inheriting from this base class):

```
typedef struct PT100MsgTag{
 lv_msg_t super;
 int32_t temperature;
}PT100Msg_t
```

You can also define a macro like this:

`MSG_CAST(_class) ((_class const *)m)`

that you can use inside object callback handler:

```
void my_callback_1(lv_msg_t * m)
{
  if(m->signal == MSG_SET_TEMP) {
    int32_t v = MSG_CAST(PT100Msg_t)->temperature;
    print("temp: %d\n", v);  
  } 
}
```

For each message you can create a list of object that are subscribed that will receive the message.

After that you can create generic APIs for each lv object:

```
lv_obj_subscribe(lv_obj const * obj, uint32_t signal);

lv_obj_unsubscribe(lv_obj const * obj, uint32_t signal);

lv_publish_msg(lv_msg_t const * const m);
```

**Comment by kisvegabor** [comment]
Thanks for the feedback @GiulioDallaVecchia!

With the current API you can:
```c

int32_t temp = 352;
lv_msg_send(MSG_SET_TEMP, &temp); //2nd parameter is the payload

typedef struct {
   int32_t year;
   int32_t month;
   int32_t day;
}date_t;

date_t d = {2022, 04, 20};
lv_msg_send(MSG_SET_DATE, &d);
```

Unless I miss something it can do the same as what you have suggested but it's simpler as there is no "inheritance magic" in it.

**Comment by kisvegabor** [comment]
I think this issue can be closed. If you find any problems with it or have any questions feel free to open a new issue.
