### ISSUE TITLE
how to achive the slide up effection by encoder and group

### ISSUE THREAD

**Issue by Kingwulin** [kisvegabor/lvgl#3220]
Hi，what I want to achive is using the encoder (eg,ec11) as the video below

https://user-images.githubusercontent.com/16952072/160645594-15a8f41e-a4c1-4a80-91b1-4ab2828cc3b5.mp4

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions. 

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

You can copy the topic's link here, and I'll response there.
