### ISSUE TITLE
Slider bar left knob can not focused?

### ISSUE THREAD

**Issue by xfdr0805** [kisvegabor/lvgl#3246]
Hello everyone
I am using lvgl-8.3.0-dev version building with lv_sim_visual_studio
What should I do to focus on left knob object?
thanks a lot!

![2022-04-03_121511](https://user-images.githubusercontent.com/16475847/161412368-4e0c4723-5277-4f08-92b0-e56fb9a2c6a0.png)

![slider1](https://user-images.githubusercontent.com/16475847/161411155-8e7be406-d5e3-40ca-be70-8ea7a6983e8c.gif)

**Comment by xfdr0805** [comment]
I found that the messagebox's close button also fails to focus when using the key
![2022-04-05_223434](https://user-images.githubusercontent.com/16475847/161778800-cf424c8f-c0d8-4915-b410-5dc7af86f130.png)

**Comment by t-walker-wei** [comment]
@xfdr0805  Did you solve this problem? I have the same issue now. Thank you in advance.

**Comment by kisvegabor** [comment]
I made no progress on it yet. For v9 we will rework the `group`s and we can take this issue into account as well. 

I added it to the ROADMAP: https://github.com/lvgl/lvgl/commit/b64dceae0ac5a840f03d038ac16441ce094482b0
