### ISSUE TITLE
Weird anti-aliasing result with custom TTF font renderer + dark background

### ISSUE THREAD

**Issue by huming2207** [kisvegabor/lvgl#3247]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)

### Describe the bug

I've implemented a font rendering wrapper that makes the `stb_truetype` to work with LVGL. It works, however, the antialiasing looks horrible if I use it for a `lv_label` in a darker background, particularly full black. However, it does work well in white background. 

Please refer to the images below.

### To Reproduce

- Here's my rendering wrapper library: https://github.com/huming2207/bisheng-fontmgr/blob/master/includes/stb_font_view.hpp
- Our environment:
  - Microcontroller: ESP32
  - Display: E-ink ED097TC2, 4-bit 16 level grayscale
  - LVGL version: master branch, commit at b171f7dde2a895142385ea1275f3f51255cb2811
  - ESP-IDF version: master branch, commit at e3c0229d2ec9bfd0203a3cab18d6642798457578
- To reproduce: 

1. Grab this header-only library to your codebase
2. Do something like:

```cpp
auto *font_view = new stb_font_view();
font_view->init(wqy_ttf_start, (wqy_ttf_end - wqy_ttf_start), 72);
```

...where `wqy_ttf_start` and `wqy_ttf_end` is a WenQuanYi font embedded to a ESP32 firmware.

3. Apply the style to a `lv_label`:

```cpp
static lv_style_t label_style;
lv_style_init(&label_style);
font_view->decorate_font_style(&label_style);
lv_style_set_text_color(&label_style, lv_color_white()); // Set text color to white, and assume the label is on a black background object
lv_obj_add_style(foo_label, &label_style, 0);
```

### Expected behavior

Anti-aliasing should just work fine.

### Screenshots or video

Properly anti-aliased font (when in white background):

![911C9148-A034-49D0-A827-7E03C7450195](https://user-images.githubusercontent.com/4463497/161458777-5c9f8058-4b9c-4ade-ab0b-8f037615bfc8.jpeg)

![D1EFCFEC-41DE-4186-AB05-8B78547FDB95](https://user-images.githubusercontent.com/4463497/161458851-eb0d4f35-3efd-47ca-8c15-3b19c56d19ce.jpeg)

Wrongly anti-aliased fonts (when in black background):

![E0DE616E-FC4C-4D5C-AF1B-93BF18E0EA88](https://user-images.githubusercontent.com/4463497/161458862-fa22d504-c5e5-4f97-bbdb-2d2398a1ec47.jpeg)

**Comment by huming2207** [comment]
I've also got FreeType2 working on ESP32, and yes it generates the exact same result as the `stb_truetype`! So now I think there's a bug somewhere on the software blender side, and it seems like it's not the TTF renderer or the wrapper library's fault.

**Comment by huming2207** [comment]
I've added a log at `lv_draw_label.c`, here's the result:

```
Letter: 0x32 "2", Color: 0xffff, Background: 0x24be
Letter: 0x31 "1", Color: 0xffff, Background: 0x24be
Letter: 0x31 "1", Color: 0xffff, Background: 0x24be
```

So I think this part looks correct, the color is white and the background is somewhat near black. Maybe something wrong in the software renderer?

**Comment by kisvegabor** [comment]
I don't think it's a SW blend issue because the  non-FreeType fonts are using it as well and they are working fine. 

I suggest creating a dummy image for a letter. E.g. when the bitmap of `'a'` should be returned, return a known, simple array. E.g. increase the opacity in each line.

**Comment by huming2207** [comment]
@kisvegabor thanks for your reply. Do you mean returning a bitmap from black to white from the `get_glyph_bitmap_handler()`? I will have a try tomorrow.


By the way, I'm running LVGL that generates RGB565 framebuffer data and downscale to the e-paper display with this algorithm: https://stackoverflow.com/questions/58449462/rgb565-to-grayscale

It works fine when I draw something else (e.g. a PNG image, or random `lv_obj`s). So far only the text didn't end up well.

**Comment by kisvegabor** [comment]
> Do you mean returning a bitmap from black to white from the get_glyph_bitmap_handler()?

Yes!

You can also try drawing a circle with LVGL maybe with some shadow to see if it looks well.

```c
  lv_obj_t * obj = lv_obj_create(lv_scr_act());
  lv_obj_set_size(obj, 50, 50);
  lv_obj_center(obj);

  lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_border_width(obj, 5, 0);
  lv_obj_set_style_border_color(obj, lv_color_hex3(0x333), 0);
  lv_obj_set_style_bg_color(obj, lv_color_hex3(0xccc), 0);
  lv_obj_set_style_shadow_width(obj, 40, 0);
```
![image](https://user-images.githubusercontent.com/7599318/161542908-dc6aea8e-4b0c-42be-b966-7253138ef110.png)
![image](https://user-images.githubusercontent.com/7599318/161543011-d08addb5-f5cd-4e2b-bc73-c3b3a378bd5a.png)

**Comment by huming2207** [comment]
@kisvegabor good idea, I will have a try tomorrow! Thanks in advance!

**Comment by huming2207** [comment]
Hi @kisvegabor 

Here's the result:

1. With your code

```c
  lv_obj_t * obj = lv_obj_create(lv_scr_act());
  lv_obj_set_size(obj, 50, 50);
  lv_obj_center(obj);

  lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, 0);
  lv_obj_set_style_border_width(obj, 5, 0);
  lv_obj_set_style_border_color(obj, lv_color_hex3(0x333), 0);
  lv_obj_set_style_bg_color(obj, lv_color_hex3(0xccc), 0);
  lv_obj_set_style_shadow_width(obj, 40, 0);
```
It generates something wrong:

![4EBE14A4-C4F7-453B-B682-930C8B9DA845](https://user-images.githubusercontent.com/4463497/161650633-4023e659-8c6f-4487-a09e-c29618148407.jpeg)

2. I modified a bit to:


```c
    lv_obj_t * obj = lv_obj_create(lv_scr_act());
    lv_obj_set_size(obj, 100, 100);
    lv_obj_center(obj);

    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(obj, 5, 0);
    lv_obj_set_style_border_color(obj, lv_color_hex3(0x111), 0);
    lv_obj_set_style_bg_color(obj, lv_color_hex3(0xccc), 0);
    lv_obj_set_style_shadow_width(obj, 40, 0);
```
It then generates:

![9E56FE77-E958-412D-BFD6-BDED9436BAA6](https://user-images.githubusercontent.com/4463497/161651937-65a64cdc-2479-401a-add8-3e4daa651b6b.jpeg)

![F0D81285-DF30-42F9-BEAA-E1951A2C293D](https://user-images.githubusercontent.com/4463497/161652400-9c43d94c-33bb-4a86-862f-003f6eb28244.jpeg)


3. I've also tried FreeType2 in white background and here's what it generates, this time it comes with the right anti-aliasing:

![65105ABC-FD36-4A72-B53B-9EA9B71C3281](https://user-images.githubusercontent.com/4463497/161652512-85bf9f41-a349-455b-bca9-af625a3b0114.jpeg)

**Comment by huming2207** [comment]
Meanwhile, here's a pre-rendered PNG image that writes to the display as a `lv_img` object:

![14BCADD5-D2EF-4124-952E-207DAC6A1631](https://user-images.githubusercontent.com/4463497/161658994-43c3c789-5f63-4fba-962c-540d7c353074.jpeg)

The anti-aliasing works in this case. That's another reason why I suspect probably there are some issues with our configuration and/or the LVGL software renderer rather than the display driver.

**Comment by huming2207** [comment]
Here's the gradient bitmap test. I've added the code below at: https://github.com/huming2207/bisheng-fontmgr/blob/master/includes/stb_font_view.hpp#L62
... so that to override the bitmap buffer with a dummy gradient (from full black to full white) bitmap:

```c
            for (size_t h_idx = 0; h_idx < height; h_idx += 1) {
                uint8_t color = (uint8_t)(((float)h_idx / (float)height) * (float)255);
                for (size_t idx = 0; idx < width; idx += 1) {
                    size_t buf_idx = h_idx * width + idx;
                    ctx->font_buf[buf_idx] = color;
                }
            }
```

Here's what it be like with white background & black text:

![IMG_20220405_140827](https://user-images.githubusercontent.com/4463497/161680807-e9feb536-5a8c-481f-81f8-8ae5358aca4f.jpg)

Here's the black background & white text:

![IMG_20220405_144208](https://user-images.githubusercontent.com/4463497/161680849-2b87a31a-a152-48e2-b70b-168e386cee1b.jpg)

I think both of these two scenarios supposed to be black on top and gradually turn to be white at bottom. But apparently they are not behaving like that.

**Comment by huming2207** [comment]
I fixed it! Turned out to be that the opacity in my `set_px()` callback is completely wrong! 

I think the reason why the PNG works is that PNG images are treated as non-opaque stuff while those anti-aliased pixels are somewhat opaque in this scenario.

I've searched around again and eventually I found this issue: https://github.com/lvgl/lvgl/issues/2863 

So I followed that and reimplemented the way of handling the `opa` value.

Here's my original implementation:

```cpp
void tcon_lv::disp_set_px_handler(lv_disp_drv_t *disp_drv, uint8_t *buf, lv_coord_t buf_w, lv_coord_t x, lv_coord_t y, lv_color_t color, lv_opa_t opa)
{
    uint32_t idx = ((y + 1) * buf_w) + x;
    if (opa < 16) {
        buf[idx] = 0xff;
    } else {
        // Algorithm originally from here: https://stackoverflow.com/a/58451121
        uint32_t red_0 = ((((uint32_t)color.ch.red << 8) / opa) * 3843) >> 14;
        uint32_t green_0 = (((((uint32_t)color.ch.green << 8) / opa) * 11718) >> 14) >> 1;
        uint32_t blue_0 = ((((uint32_t)color.ch.blue << 8) / opa) * 1183) >> 14;
        uint16_t gray_0 = red_0 + green_0 + blue_0;

        buf[idx] = (uint8_t)(((gray_0 << 11) + (gray_0 << 6) + gray_0) >> 8) >> 4;
    }
}
```

Here's the new implementation after I read that issue topic:

```cpp
void tcon_lv::disp_set_px_handler(lv_disp_drv_t *disp_drv, uint8_t *buf, lv_coord_t buf_w, lv_coord_t x, lv_coord_t y, lv_color_t color, lv_opa_t opa)
{
    uint32_t idx = ((y + 1) * buf_w) + x;

    // Algorithm originally from here: https://stackoverflow.com/a/58451121
    uint32_t red_0 = (((uint32_t)color.ch.red) * 3843) >> 14;
    uint32_t green_0 = ((((uint32_t)color.ch.green) * 11718) >> 14) >> 1;
    uint32_t blue_0 = (((uint32_t)color.ch.blue) * 1183) >> 14;
    uint16_t gray_0 = red_0 + green_0 + blue_0;

    uint8_t pix_in_buf = buf[idx];
    uint8_t incoming_pix = (uint8_t)(((gray_0 << 11) + (gray_0 << 6) + gray_0) >> 8) >> 4;
    uint8_t blended_pix = (pix_in_buf * (LV_OPA_COVER - opa) + incoming_pix * opa) / LV_OPA_COVER;
    buf[idx] = blended_pix;
}
```
 
Also, sorry for that previously I kept thinking it was the SW renderer issue.  It's actually my fault lol...

**Comment by kisvegabor** [comment]
> I think the reason why the PNG works is that PNG images are treated as non-opaque stuff while those anti-aliased pixels are somewhat opaque in this scenario.

The PNG images are treated as a "color map" + "alpha (mask) map". While letter are a single color  + "alpha (mask) map". 

Anyway happy to hear that you have found the issue! :slightly_smiling_face:

**Comment by huming2207** [comment]
> The PNG images are treated as a "color map" + "alpha (mask) map". While letter are a single color + "alpha (mask) map".

Oh okay, thx for the info. But if the image is in RGB888 (and no alpha), does it still has that alpha map?

**Comment by kisvegabor** [comment]
> But if the image is in RGB888 (and no alpha), does it still has that alpha map?

Nope, it's only for ARGB images. With ARGB images LVGL separates the color and alpha data and uses the alpha channel as a mask during blending.

**Comment by huming2207** [comment]
> Nope, it's only for ARGB images. With ARGB images LVGL separates the color and alpha data and uses the alpha channel as a mask during blending.

Understood, thanks.
