### ISSUE TITLE
Error defocused when group disabled wrap

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3248]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When group disabled wrap, continues to move the focus at the head or tail, and the object enters the defocused state.
Seems like this [commit](https://github.com/lvgl/lvgl/commit/72cb683c799f65cd4fbae22dafc3a35c123bb66b) is causing it?

### To Reproduce
```c
static void group_focus_test()
{
    lv_group_t* group = lv_group_get_default();
    lv_obj_t* par = lv_scr_act();

    lv_group_set_wrap(group, false);

    for (int i = 0; i < 3; i++)
    {
        lv_obj_t* obj = lv_obj_create(par);
        lv_obj_set_size(obj, 30, 30);
        lv_obj_set_flex_flow(par, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(par, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

        lv_obj_set_style_bg_color(obj, lv_palette_main(LV_PALETTE_BLUE), 0);
        lv_obj_set_style_bg_color(obj, lv_palette_main(LV_PALETTE_RED), LV_STATE_FOCUSED);
        lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
        lv_group_add_obj(group, obj);
    }
}
```

### Expected behavior
Don't lose focus at head and tail.

### Screenshots or video
https://user-images.githubusercontent.com/26767803/161520429-bbb958b9-d443-4e6c-9cce-d829062f25b9.mp4

**Comment by kisvegabor** [comment]
I reverted that commit. The issue it meant to fix can be solved by using `lv_del_async()`. In a later version we should reconsider how groups work and it will be fixed in a better way then.
