### ISSUE TITLE
JavaScript simulator: increase heap size and performance

### ISSUE THREAD

**Issue by leidto** [kisvegabor/lvgl#3256]
### Introduce the problem
I'd like to increase the heap/stack size to work with large canvases.

### Examples and cases
I set the screen with:
`from display_driver_utils import driver`
`drv = driver(width=1024,height=1024)`

and the buffer with:
`buf2 = bytearray(1024*1024*4)` but it has gave the following error:
**MemoryError: memory allocation failed, allocating 4194304 bytes**

### My questions
1. How is it possible to increase the heap/stack size?
2. I found this suggestion also: `emit or O[N] can help to improve performance  with the JS port`. How is it possible? Are there other opportunities to increase performance?

**Comment by embeddedt** [comment]
The heap size is controlled [here](https://github.com/lvgl/lv_micropython/blob/8dbd4565aca599f68ab433698be851038d16f4d2/ports/javascript/lvgl.html#L96) and is currently set to 1MB. You can just change the value in that HTML file to increase it.

> I found this suggestion also: emit or O[N] can help to improve performance with the JS port. How is it possible? Are there other opportunities to increase performance?

I'm not sure where you found this suggestion, but our fork of the JS port is already being compiled with `-O3` and WebAssembly now, so you can't turn up the optimization any further to my knowledge.

**Comment by kisvegabor** [comment]
> I found this suggestion also: emit or O[N] can help to improve performance with the JS port. How is it possible? Are there other opportunities to increase performance?


Maybe @amirgon knows something about these.

**Comment by kisvegabor** [comment]
> I'm not sure where you found this suggestion, but our fork of the JS port is already being compiled with -O3 and WebAssembly now, so you can't turn up the optimization any further to my knowledge.

`./micropython -h` prints them.

(With @leidto we are evaluating some alternative backends for SquareLine Studio. That's why the JS related questions in the near past. :slightly_smiling_face: )

**Comment by amirgon** [comment]
> `./micropython -h` prints them.

I think you are referring to Micropython bytecode optimizations while @embeddedt referred to C optimizations.
I believe `-O0` bytecode optimizations are applied on any port by default, but AFAIK they are far less significant than the C optimizations. They simply enable/disable some checks and assertions.

Micropython bytecode optimizations can also be set on runtime with `micropython.opt_level`, so you can try changing them online.

See: https://docs.micropython.org/en/latest/library/micropython.html#micropython.opt_level

> (With @leidto we are evaluating some alternative backends for SquareLine Studio. That's why the JS related questions in the near past.  )

The JS port is obviously less performant than the unix port.  
In that port C code is emulated by WASM and would always be slower than C code compiled natively.  
Additionally, there are many features missing from the JS port. For example, [`native`](https://docs.micropython.org/en/latest/reference/speed_python.html#the-native-code-emitter) and [`viper`](https://docs.micropython.org/en/latest/reference/speed_python.html#the-viper-code-emitter) emitters are not supported. [uasyncio](https://docs.micropython.org/en/latest/library/uasyncio.html) is not supported, etc.  
Another limitation of the JS port is that it is blocking (the UI is not refreshed while sleeping or waiting for some synchronous event)

So the JS port is very nice for demos or small and relatively simple applications, but if you are looking for a performant and fully featured Micropython backend, you should definitely use the unix port.

**Comment by kisvegabor** [comment]
Thanks for the insight! 

We have just tried it with full HD resolution, using almost screen sized animations, screen change with fade and got an acceptable FPS. 

I think switching to the SDL renderer could improve it further assuming it uses WebGL internally.
