### ISSUE TITLE
[lv_menu] Can menu sidebar aligned to the right instead of left?

### ISSUE THREAD

**Issue by richardclli** [kisvegabor/lvgl#3260]
### Introduce the problem
Currently the lv_menu sidebar align to the left.  Walk through all the settings in the doc and cannot figure out a way to align to the right.

### Examples and cases
I tried to make the sidebar align to the right starting with the Complex Menu example that comes with LVGL, but no success.

### Suggested solution
A new option to support left/right alignment of the sidebar?

**Comment by richardclli** [comment]
Just figured out a way to work out the alignment:

lv_obj_move_to_index(((lv_menu_t *) menu)->sidebar, 2);

**Comment by kisvegabor** [comment]
You can also reverse the layout with `lv_obj_set_flex_flow(menu, LV_FLEX_FLOW_ROW_REVERSE)`.
