### ISSUE TITLE
function "lv_obj_get_text_color_filtered" return the wrong color

### ISSUE THREAD

**Issue by wey4321** [kisvegabor/lvgl#3261]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

after function "lv_obj_set_text_color_filtered" is called, i call function "lv_obj_get_text_color_filtered" to get the color i just set, then i found the color returned is not same with the color i set, 
**this bug exists on branch v8.2**
### To Reproduce

```c
lv_color_t color1 = lv_color_make(0, 0, 0);
lv_obj_set_text_color_filtered(obj, color1, LV_PART_SELECTED);
lv_color_t color2 = lv_obj_get_text_color_filtered(obj, LV_PART_SELECTED);
// then i found color1 != color2
```

**Comment by wey4321** [comment]
![image](https://user-images.githubusercontent.com/17686596/162396142-47b491bb-d203-425d-8788-8b8648099d80.png)
i fix the issue like this, and the return color is correct.
maybe there are better ways to fix it!

**Comment by embeddedt** [comment]
Setting filtered properties was a bug in the autogenerated API. There should only be a getter. In the next version of LVGL `lv_obj_set_text_color_filtered` will be removed. You should just set the regular property with `lv_obj_set_text_color`.

**Comment by wey4321** [comment]
@embeddedt   the code of  'lv_obj_get_style_prop' of master branch is like this
![image](https://user-images.githubusercontent.com/17686596/162650099-fd8dbe85-906f-4a93-93ca-35655c6a6019.png)
is seems, this bug is fixed. and whether the next version of LVGL will be availabel at branch release_v8.2?

**Comment by kisvegabor** [comment]
We will release v8.3 in a few months.

**Comment by wey4321** [comment]
@kisvegabor so the branch release_v8.2 is not long-term stable version, and it will be replaced by release v8.3 ? and the bugs of v8.2 will only be fixed at master branch?

**Comment by embeddedt** [comment]
I think there is some confusion here. There isn't a bug from what I can tell, aside from the fact that you were able to call `lv_obj_set_style_text_color_filtered` in previous versions (which you should not have been able to, and the API does not exist in v8.3 anymore). Filtering is intended to be applied inside a getter only based on other style properties. You should not be setting the filtered version of a property.

**Comment by wey4321** [comment]
@embeddedt  ok, i got it. thanks a lot!

**Comment by embeddedt** [comment]
Glad I could help!
