### ISSUE TITLE
Setting the file cache to 512 will cause the font to fail to load

### ISSUE THREAD

**Issue by alec-2018** [kisvegabor/lvgl#3262]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

hi @kisvegabor ,I Setting the file cache to 512 will cause the font to fail to load，The emulator version is the latest（lv_port_win_visual_studio-master）
### To Reproduce

In the emulator, setting LV_FS_WIN32_CACHE_SIZE to 512 reproduces the problem
```c
    lv_font_t* font = lv_font_load("C:\\font.bin");
    lv_obj_t* label = lv_label_create(lv_scr_act());
    lv_label_set_text(label, "abcdefghigklmnopqrst");
    lv_obj_set_style_text_font(label, font, 0);
```
### Expected behavior

![0_succ](https://user-images.githubusercontent.com/40708750/162395633-a03aaa70-e082-48d6-8457-408d57919cb4.png)

### Screenshots or video

![aaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/40708750/162401468-e09e2637-3d5d-42ec-a549-eba99bd86aa0.png)

**Comment by kisvegabor** [comment]
Are using the latest version of LVGL from the master branch?

If so, please attach your `font.bin` to reproduce the issue.

**Comment by alec-2018** [comment]
> Using the latest version of LVGL from the master branch?
> yes
> If so, please attach yours `font.bin`to reproduce the issue.
[font.zip](https://github.com/lvgl/lvgl/files/8489496/font.zip)
Sorry, I lost my previous font file.
I can reproduce the problem using this font file；It's strange that I put cache_size = 512, no error occurs, but cache_size = 1024, the problem will reproduce
I modified the code here: "file_p->cache->start = file_p->cache->end + 1" to "file_p->cache->start = file_p->cache->end" ，cache_size = 1024 OK

**Comment by alec-2018** [comment]
> Using the latest version of LVGL from the master branch?
> yes
> If so, please attach yours `font.bin`to reproduce the issue.
[font.zip](https://github.com/lvgl/lvgl/files/8489496/font.zip)
Sorry, I lost my previous font file.
I can reproduce the problem using this font file；It's strange that I put cache_size = 512, no error occurs, but cache_size = 1024, the problem will reproduce
I modified the code here: "file_p->cache->start = file_p->cache->end + 1" to "file_p->cache->start = file_p->cache->end" ，cache_size = 1024 OK

**Comment by kisvegabor** [comment]
Hi,

I've tracked it down and found the root of the issue: an extra `+ 1`... 

Once I was there I added a simple unit test for `lv_fs.c` which revealed that cached mode doesn't handle if EOF is reached. So I fixed that too. 

Let me know if it works on your end as well.

**Comment by alec-2018** [comment]
> Hi,
> 
> I've tracked it down and found the root of the issue: an extra `+ 1`...
> 
> Once I was there I added a simple unit test for `lv_fs.c` which revealed that cached mode doesn't handle if EOF is reached. So I fixed that too.
> 
> Let me know if it works on your end as well.

thanks, it works for me
