### ISSUE TITLE
LV_LAYOUT_FLEX incompatible with lv_obj_set_style_layout

### ISSUE THREAD

**Issue by wrgallo** [kisvegabor/lvgl#3273]
### Describe the bug

- [`LV_LAYOUT_FLEX`](https://github.com/lvgl/lvgl/blob/016099e09c3bccdf6b0dd5269c1ec4d00eb07b86/src/extra/layouts/flex/lv_flex.h#L60) is defined as a `uint32_t`;
- [`lv_obj_set_style_layout`](https://github.com/lvgl/lvgl/blob/016099e09c3bccdf6b0dd5269c1ec4d00eb07b86/src/core/lv_obj_style_gen.h#L633) requires a `uint16_t` value;
- `lv_obj_set_style_layout( obj, LV_LAYOUT_FLEX, 0 );` generates the warning [C4244](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-170).

### To Reproduce

- Setup a [LVGL project with Visual Studio](https://github.com/lvgl/lv_port_win_visual_studio).
- Set [Warning Level](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170) to 3 or Higher
- Somewhere in your code, set `LV_LAYOUT_FLEX`, like `lv_obj_set_style_layout( obj, LV_LAYOUT_FLEX, 0 );` 

### Expected behavior

- No warnings should happen here, but only casting `LV_LAYOUT_FLEX` to `uint16_t` would remove the warning. 
```C
lv_obj_set_style_layout( obj, (uint16_t)LV_LAYOUT_FLEX, 0 );
```

**Comment by kisvegabor** [comment]
Thanks, fixed!
