### ISSUE TITLE
a line with a gradient of color

### ISSUE THREAD

**Issue by Qianoo** [kisvegabor/lvgl#3277]
Hi， guys，I just learn lvgl， I want to  create a line with a gradient of color， is anyone know how to do？ if you konw， please thanks tell me， thank you very much ！

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

You can copy the link of the Forum topic here and I'll reply there. :slightly_smiling_face:
