### ISSUE TITLE
Should the animation add a callback for deletion?

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#3279]
### Introduce the problem

When I add user data to the animation, I need to release memory in the ready callback, but the animation may be deleted in obj destructor. At this time, there is no ready callback, resulting in memory leakage. I was wondering if the user should be informed when the animation is deleted?

### Examples and cases

static void anim_ready_cb(lv_anim_t* a)
{
    printf("%s, %s\n",__func__, a->user_data);
    lv_mem_free(a->user_data);
}

static void btn_callback_cb(lv_event_t* e)
{
  lv_obj_del_async(lv_event_get_current_target(e));
}

static void anim_test(void)
{
  lv_obj_set_style_bg_color(lv_scr_act(), lv_color_black(), 0);
  lv_obj_t* btn = lv_btn_create(lv_scr_act());
  lv_obj_set_size(btn, 100, 60);
  lv_obj_center(btn);
  lv_obj_add_event_cb(btn, btn_callback_cb, LV_EVENT_CLICKED, NULL);
  
  lv_obj_t* label = lv_label_create(btn);
  lv_obj_center(label);
  lv_label_set_text(label, "delete btn");

  char *anim_name = lv_mem_alloc(100);
  snprintf(anim_name, 100, "please free me.");
  lv_anim_t a ;
  lv_anim_init(&a);
  lv_anim_set_var(&a, btn);
  lv_anim_set_user_data(&a, anim_name);
  lv_anim_set_ready_cb(&a, anim_ready_cb);
  lv_anim_set_time(&a, 5000);
  lv_anim_start(&a);
}

### Suggested solution

Could I add a callback to delete animation and then free memory in this callback?

**Comment by kisvegabor** [comment]
Hi,

It sounds reasonable. Could you send a Pull request?

**Comment by kisvegabor** [comment]
Added in https://github.com/lvgl/lvgl/pull/3295 but we are still waiting for minor docs update. 

Let keep only PR open.
