### ISSUE TITLE
Invalid branch in lv_grid

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3306]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The `last_fr_i` in **lv_grid.c:557** is always less than 0.

### Screenshots or video
![image](https://user-images.githubusercontent.com/26767803/165894668-808747de-06ad-4204-8481-b2dc978fd2ac.png)

**Comment by kisvegabor** [comment]
These 2 lines are added in column calculation but missing from row calculation: https://github.com/lvgl/lvgl/blob/e8cf036955bd40800acc3627077961d8fee589d0/src/extra/layouts/grid/lv_grid.c#L494-L495

I've pushed a fix.
