### ISSUE TITLE
lv_obj_area_is_visible() performance degradation

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3334]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
After the object transform function is added, the time-consuming of the lv_obj_area_is_visible() function becomes significantly longer, resulting in a decrease in overall performance. I compared this [commit](https://github.com/lvgl/lvgl/commit/318146a2c25362eabf258470be263a4cfeaefe87) and the previous version on my hardware platform (AT32F435CGU7 @288MHz), `lv_obj_area_is_visible()` takes about **1-2us**, and after adding object transform function, the time is increased to **100-200us**.

### To Reproduce
Add time-consuming measurements in **lv_obj_pos.c**
```c
static bool _lv_obj_area_is_visible(const lv_obj_t * obj, lv_area_t * area)
{
...
}

bool lv_obj_area_is_visible(const lv_obj_t * obj, lv_area_t * area)
{
    uint32_t start = micros();
    bool ret = _lv_obj_area_is_visible(obj, area);
    LV_LOG_USER("cost %dus", micros() - start);
    return ret;
}
```

### Expected behavior
When the object has no transform attribute, the time-consuming should be the same as before.

**Comment by kisvegabor** [comment]
Hi,

I was aware of that it will be slower, but 100 times slower is really to much. I've pushed a fix.
