### ISSUE TITLE
esp32s3 idf.py menuconfig CONFIG_LV_FS_STDIO_LETTER="A" should be CONFIG_LV_FS_STDIO_LETTER='A'

### ISSUE THREAD

**Issue by chrdwhdhxtszpzclljxk** [kisvegabor/lvgl#3342]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

after idf.py menuconfig, in sdkconfig follow instructions updated
but "A" should be 'A'. otherwise lv_fs will init fail.

#
# 3rd Party Libraries
#
CONFIG_LV_USE_FS_STDIO=y
CONFIG_LV_FS_STDIO_LETTER="A"
CONFIG_LV_FS_STDIO_PATH=""
CONFIG_LV_FS_STDIO_CACHE_SIZE=""

**Comment by kisvegabor** [comment]
In the latest Kconfig file it should be fixed to have  an `int` type to set an ASCII character.
