### ISSUE TITLE
Please add a warning to lv_img_set_zoom

### ISSUE THREAD

**Issue by shahawi-sumup** [kisvegabor/lvgl#3351]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When zoom is set to any value other than `256` the image disappear and the docs doesn't mention that `lv_img_set_zoom` only supports True color images.
I found your comment here: https://github.com/lvgl/lvgl/issues/1896#issuecomment-727848659

### To Reproduce

```c
LV_IMG_DECLARE(logo_idx256); // 256 color image or any non True color
lv_obj_t * img = lv_img_create(lv_scr_act());
lv_img_set_src(img, &logo_idx256);
lv_img_set_zoom(img, 128);
```
### Expected behavior

Image Zoomed (scaled down by) 50% !

### Screenshots or video

N/A

Please add to the documentation of `lv_img_set_zoom` that it only supports True color images.

Thanks :)

**Comment by kisvegabor** [comment]
Makes sense, I updated the comments. :slightly_smiling_face:  See https://github.com/lvgl/lvgl/commit/ccbb41dedcf9c6424897fab9a1627bad63b7cc52

FYI, it was mentioned in the docs [here](https://docs.lvgl.io/master/widgets/core/img.html#transformations).
