### ISSUE TITLE
crash when set disp_drv->draw_buf->flushing = 0;

### ISSUE THREAD

**Issue by ghost** [kisvegabor/lvgl#3354]
mcu:esp32s2
 lcd driver:ili9488, 320*320
when i use lvgl-v7.2,all works ok,but when i upgrade to release v8.2,below is callback of flush screen
```c
void disp_driver_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_map)
{
   ESP_LOGE(TAG,"drv %p",drv->draw_buf);
   if (!BackLightTimeout)
   {
      memset(color_map, 0, ((area->x2 - area->x1 + 1) * (area->y2 - area->y1 + 1) * sizeof(lv_color_t)));
   }
   lcd_ili9488_draw_bitmap(area->x1, area->y1, area->x2 + 1, area->y2 + 1, (uint16_t *) color_map);
   lv_disp_flush_ready(drv);
}
```

when call the last function,it crashed
![snap_screen_20220512140942](https://user-images.githubusercontent.com/105137937/168003389-4547c520-94b5-4617-973f-f7efe6b482b5.png)

i don't ust lvgl_esp32_drivers,because it has no i2s interface driver.

what's wrong with the v8.2?

**Comment by kisvegabor** [comment]
Hi,

Take look at this part of the migration guide: https://docs.lvgl.io/master/CHANGELOG.html#driver-changes
