### ISSUE TITLE
slider on tileview

### ISSUE THREAD

**Issue by ghost** [kisvegabor/lvgl#3357]
i place a slider on one of a tileview  page，the tileview don‘t only has one page，when i slide the slider，the page slide，slider work wrong

how to resolve this

**Comment by kisvegabor** [comment]
Slider shouldn't propagate the scrolling to the parent. Please send a code snippet to reproduce the issue.

**Comment by ghost** [comment]
> Slider shouldn't propagate the scrolling to the parent. Please send a code snippet to reproduce the issue.
this is my code
[Lcd86Box.zip](https://github.com/lvgl/lvgl/files/8704377/Lcd86Box.zip)

**Comment by kisvegabor** [comment]
It seems you are using LVGL v7. GuiGuider already supports LVGL v8 too. Is it an option for you to update to v8?

**Comment by JustQY** [comment]
> It seems you are using LVGL v7. GuiGuider already supports LVGL v8 too. Is it an option for you to update to v8?

thinks，the v8 has no this issue

**Comment by kisvegabor** [comment]
Great!
