### ISSUE TITLE
Image disappears when updating lv_label

### ISSUE THREAD

**Issue by hard-cat** [kisvegabor/lvgl#3360]
I updated the library in the project from 7.10 to 8.2, and got a strange effect.

I displayed 2 labels, and periodically change the text in them, sometimes the label image disappears, and the next time lv_label_set_text_fmt is called, it returns to the screen.
When using version 7.10, this is not observed.

static void init_term_ref(lv_obj_t * cont)
{

	  LabelTRef = lv_label_create(cont);
	  LabelTRefRes = lv_label_create(cont);
	  lv_label_set_recolor(LabelTRef, true);	
	  lv_label_set_recolor(LabelTRefRes, true);
	  lv_obj_set_style_text_font(LabelTRef, &MontserratSemiBold_96, 0);		
	  lv_obj_set_style_text_font(LabelTRefRes, &MontserratSemiBold_48, 0);
	  lv_obj_align(LabelTRef, LV_ALIGN_LEFT_MID, 0, 0);
	  lv_obj_align(LabelTRefRes, LV_ALIGN_LEFT_MID, 0, 13); 

}
  
void lv_widgets(void)
{

          lv_obj_t * cont = lv_scr_act();
           lv_obj_t * img1 = lv_img_create(cont);
           lv_img_set_src(img1, &preview1);
            init_term_ref(img1);
            lv_label_set_text(LabelTRef, "#ffffff --");
            lv_label_set_text(LabelTRefRes, "");
            update_align_term_ref();

}
  
static void guiUserTask(void)
{  

	  float tref = get_param();
          int16_t dec = (int16_t)tref;
          if (dec >= 0 && dec < 100) {
	          lv_label_set_text_fmt(LabelTRef, "#ffffff %d", dec);
	          int16_t dot = (tref * 10) - (dec * 10);
	          if (dot < 10) 
		          lv_label_set_text_fmt(LabelTRefRes, "#ffffff .%d", dot);
	          else lv_label_set_text(LabelTRefRes, "");
          }	

}

**Comment by kisvegabor** [comment]
Did you pay attention to [these](https://docs.lvgl.io/master/CHANGELOG.html#driver-changes) when you updated to v8?

**Comment by hard-cat** [comment]
> Did you pay attention to [these](https://docs.lvgl.io/master/CHANGELOG.html#driver-changes) when you updated to v8?

Yes, I fixed the initialization as described

[video](https://cndslctl.mysmartflat.ru/mp3/dima/video_2022-05-17_14-09-03.mp4)

#define DISPLAY_BUFF_SIZE (240*40)

static void gui_task(void * p)
{

	lv_init();
    lvgl_driver_init();

    EXT_RAM_ATTR static lv_color_t buf1[DISPLAY_BUFF_SIZE];
    EXT_RAM_ATTR static lv_color_t buf2[DISPLAY_BUFF_SIZE];

	static lv_disp_draw_buf_t disp_buf;
	lv_disp_draw_buf_init(&disp_buf, buf1, buf2, DISPLAY_BUFF_SIZE);

    static lv_disp_drv_t disp_drv;
	lv_disp_drv_init(&disp_drv);
    disp_drv.flush_cb = disp_driver_flush;
	disp_drv.draw_buf = &disp_buf;
	disp_drv.hor_res = 240;
    disp_drv.ver_res = 240;
	disp_drv.antialiasing = 1;
    lv_disp_drv_register(&disp_drv);

    const esp_timer_create_args_t periodic_timer_args = {
        .callback = &lv_tick_task,
        .dispatch_method = ESP_TIMER_TASK,
        .name = "periodic_gui"
    };
    esp_timer_handle_t periodic_timer;
    ESP_ERROR_CHECK(esp_timer_create(&periodic_timer_args, &periodic_timer));
    ESP_ERROR_CHECK(esp_timer_start_periodic(periodic_timer, LV_TICK_PERIOD_MS * 1000));

    lv_widgets();
	set_lcd_bright(DEF_BRIGHT_LCD, 1000);

	while(1) 
	{
		vTaskDelay(10 / portTICK_PERIOD_MS);

		lv_task_handler();
		guiUserTask();
	}
}

**Comment by pete-pjb** [comment]
Hi @kisvegabor,

cc @hard-cat 

Just to let you know I have updated to the latest master branch today and my splash screen images have stopped appearing on the screen when my systems boot up.  

Could this be a related problem?

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
AFAIK nothing critical was added in the past few days. Do you know where/how it halts?

**Comment by hard-cat** [comment]
![image](https://user-images.githubusercontent.com/87597134/168787251-6a291772-6943-450e-b555-700d70b7a2d3.png)

the problem was solved by disabling "Horizontal subpixel rendering".....

new library has worse performance?

**Comment by pete-pjb** [comment]
Hi @kisvegabor,

cc @hard-cat

I hadn't read the post properly here sorry, I see @hard-cat is using v8.2 not latest master.

I am continuing to look in to this problem and I will open a new issue once I understand better what is happening.

Sorry for the noise on this thread.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Regarding the rendering issue please attach the converted font and "one label" example to reproduce the issue.

Regarding the performance, in which case do you see regression?

**Comment by Linzdigr** [comment]
I have the same issue on labels occurring here but with specific conditions:
- Fonts compiled from `npx github:lvgl/lv_font_conv` with option `--lcd` (horizontal subpixel rendering)
- Heavy interruptions on the rendering thread (i.e. short ISR routine triggered multiple times: >2k per second) on an nRF52840.
