### ISSUE TITLE
rendering error in objects with rounded corners

### ISSUE THREAD

**Issue by moinmoin-sh** [kisvegabor/lvgl#3362]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When creating a button (or panel) with rounded corners adn the background of the button is set by using opacity, the aread within the avtive radius on the top and the bottom of the button is redered darker than the background of the remaining area. Please see attached screen shot for better explanation

### To Reproduce

```c
    lv_obj_t* act = lv_scr_act();

    lv_obj_t* screen = lv_obj_create(act);
    lv_obj_set_size(screen, 320, 480);
    lv_obj_set_style_bg_color(screen, lv_color_make(50, 0, 50), LV_PART_MAIN);

    lv_obj_t* btn = lv_btn_create(screen);
    lv_obj_set_size(btn, 100, 100);
    lv_obj_set_style_radius(btn, 10, LV_PART_MAIN);
    lv_obj_center(btn);
    lv_obj_set_style_bg_color(btn, lv_color_make(255, 255, 255), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn, 50, LV_PART_MAIN);

```

### Expected behavior

The whole area should be colored consistent.

### Screenshots or video

![grafik](https://user-images.githubusercontent.com/53935853/168923824-34611211-77e3-4d04-8671-4669dc0865e0.png)

**Comment by kisvegabor** [comment]
Thanks for the report. I fixed it. 

I suggest setting `LV_COLOR_MIX_ROUND_OFS 0` to gain some performance.

**Comment by moinmoin-sh** [comment]
Thanks for the quick fix !

**Comment by moinmoin-sh** [comment]
Sorry for coming back, but the issue doesn't seam to be fully fixed. The mentioned upper and lower area are still darker.

![grafik](https://user-images.githubusercontent.com/53935853/169093252-2f490ba3-6eb0-46b7-b5e0-936fb60ffd3a.png)
![grafik](https://user-images.githubusercontent.com/53935853/169093587-0cd9b7e0-ebe5-4ab6-b8ca-295b683f3f5c.png)
![grafik](https://user-images.githubusercontent.com/53935853/169093835-a535c24e-4c5d-4545-bf8d-338d98ac76d0.png)

**Comment by kisvegabor** [comment]
It seem good to me on PC. Please attach your `lv_conf.h` file.

**Comment by moinmoin-sh** [comment]
The screenshots are taken from the PC.
Changed extension to .txt to be accepted here.

[lv_conf.txt](https://github.com/lvgl/lvgl/files/8720834/lv_conf.txt)

**Comment by kisvegabor** [comment]
Thanks, I improved it.

**Comment by moinmoin-sh** [comment]
Looks good now!
Thanks for fixing it!

**Comment by kisvegabor** [comment]
Great, thanks!

**Comment by moinmoin-sh** [comment]
Hello @kisvegabor , I needed to reopen this issue.
Everything worked fine until I needed to set `LV_COLOR_16_SWAP=1`. The rendering issue came back exactly as I described above.
I took a closer look into the fix that you made and think the fix is only applied if `LV_COLOR_16_SWAP=0`. I made a little change to `lv_color.h` that applies your fix if color swap is turned on as well by byte swaping the input colors (c1, c2) before they are processed and swaping back the result before returning. Probably not the smartest solution, but I could prove it works.
FYI : here is the updated snipet. It starts in `lv_color.h` at line 443  (Version 8.3.5)

```CPP

#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0 && LV_COLOR_MIX_ROUND_OFS == 0
    /*Source: https://stackoverflow.com/a/50012418/1999969*/
    mix = (uint32_t)((uint32_t)mix + 4) >> 3;
    uint32_t bg = (uint32_t)((uint32_t)c2.full | ((uint32_t)c2.full << 16)) &
                  0x7E0F81F; /*0b00000111111000001111100000011111*/
    uint32_t fg = (uint32_t)((uint32_t)c1.full | ((uint32_t)c1.full << 16)) & 0x7E0F81F;
    uint32_t result = ((((fg - bg) * mix) >> 5) + bg) & 0x7E0F81F;
    ret.full = (uint16_t)((result >> 16) | result);

#elif LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 1 && LV_COLOR_MIX_ROUND_OFS == 0
// proposal to fix rounding errors when LV_COLOR_16_SWAP=1
    /*Source: https://stackoverflow.com/a/50012418/1999969*/
    c1.full = c1.full << 8 | c1.full >> 8;  // swap c1
    c2.full = c2.full << 8 | c2.full >> 8;  // swap c2
    mix = (uint32_t)((uint32_t)mix + 4) >> 3;
    uint32_t bg = (uint32_t)((uint32_t)c2.full | ((uint32_t)c2.full << 16)) &
                  0x7E0F81F; /*0b00000111111000001111100000011111*/
    uint32_t fg = (uint32_t)((uint32_t)c1.full | ((uint32_t)c1.full << 16)) & 0x7E0F81F;
    uint32_t result = ((((fg - bg) * mix) >> 5) + bg) & 0x7E0F81F;
    ret.full = (uint16_t)((result >> 16) | result);
    ret.full = ret.full << 8 | ret.full >> 8;  // swap result

#elif LV_COLOR_DEPTH != 1
    /*LV_COLOR_DEPTH == 8, 16 or 32*/
    LV_COLOR_SET_R(ret, LV_UDIV255((uint16_t)LV_COLOR_GET_R(c1) * mix + LV_COLOR_GET_R(c2) *
                                   (255 - mix) + LV_COLOR_MIX_ROUND_OFS));
    LV_COLOR_SET_G(ret, LV_UDIV255((uint16_t)LV_COLOR_GET_G(c1) * mix + LV_COLOR_GET_G(c2) *
                                   (255 - mix) + LV_COLOR_MIX_ROUND_OFS));
    LV_COLOR_SET_B(ret, LV_UDIV255((uint16_t)LV_COLOR_GET_B(c1) * mix + LV_COLOR_GET_B(c2) *
                                   (255 - mix) + LV_COLOR_MIX_ROUND_OFS));
    LV_COLOR_SET_A(ret, 0xFF);
#else
    /*LV_COLOR_DEPTH == 1*/
    ret.full = mix > LV_OPA_50 ? c1.full : c2.full;
#endif

```

**Comment by kisvegabor** [comment]
It think it'd be easier to read like this:

```c
#if LV_COLOR_DEPTH == 16 && LV_COLOR_MIX_ROUND_OFS == 0
#if LV_COLOR_16_SWAP == 1
    c1.full = c1.full << 8 | c1.full >> 8;  // swap c1
    c2.full = c2.full << 8 | c2.full >> 8;  // swap c2
#endif

...
```

If you agree and it works well, could you open a pull request for the `release/v8.3` branch?

**Comment by moinmoin-sh** [comment]
Will do.
Thanks for looking into this!
