### ISSUE TITLE
-Werror=maybe-uninitialized variable in lv_draw_label.c

### ISSUE THREAD

**Issue by dbongartz** [kisvegabor/lvgl#3365]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
While compiling LVGL I get an error with `-Werror=maybe-uninitialized` under linux-gcc 11.2.0 here: https://github.com/lvgl/lvgl/blob/22854ff3fba236f50893221805c9cc4d378baaca/src/draw/lv_draw_label.c#L285

It looks to me to be a false positive because I don't think there is a path that uses it uninitialized but that should be checked.
I think it could get initialized to something sane here: https://github.com/lvgl/lvgl/blob/22854ff3fba236f50893221805c9cc4d378baaca/src/draw/lv_draw_label.c#L205

**NOTE**: Could as well be something wrong in GCC. Some 9.x version for ARM does not flag this as an error. The default on Ubunut 20.4 also does not detect it.

### To Reproduce
Compile any label with `-Werror -Wall` enabled.

### Expected behavior
No warning/error emitted.

**Comment by embeddedt** [comment]
`-Wmaybe-uninitialized` is heavily affected by optimization, if I recall correctly, so it makes sense that the warning isn't seen anywhere. I agree that the variable appears to always be initialized but I set it to black at the start just to be extra safe.
