### ISSUE TITLE
Support for 12-bit RGB444

### ISSUE THREAD

**Issue by acumartini** [kisvegabor/lvgl#3369]
I have no idea how difficult this is, but could be a big benefit to people running smaller displays that do not support 8-bit RBG332 but still want to speed up their frame rate. For example the ST7789V driver, which only supports 12/16/32-bit RGB.

**Comment by acumartini** [comment]
I can take a stab at this with some pointers 👍

**Comment by kisvegabor** [comment]
Are you sure 12 bit would speed up frame rate? If the pixels are tightly packed (i.e. on 13th bit the next pixel starts) it will be slow do to the complicated addressing of pixels and color channels. If the pixels are byte aligned it will be like 16 bit.

Or the speed up could come from less data via SPI (assuming tight packing here too)?

**Comment by acumartini** [comment]
Yeah I think there would be some overhead due to complicated addressing although I do not understand the problem as well as you do. But the primary speed increase would be from sending less data over SPI, assuming you could compensate for addressing costs with frame buffers and/or DMA.

**Comment by kisvegabor** [comment]
Have you tried using the `set_px_cb` ( probably `rounder_cb` is also required). See [here](https://docs.lvgl.io/master/porting/display.html#optional-fields). These can be used to add external support for any custom format. Rendering will be slower than RGB565 but if we added it natively we could achive only something similar.
