### ISSUE TITLE
Supports for indexed colour and alpha-only are broken. 

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3370]
It looks like the support for indexed colour and alpha-only colour are broken.

It is easy to reproduce these issues by running the benchmark project.

I highly suspect this is due to a recent change in https://github.com/lvgl/lvgl/commit/b7733302348adc9379eaedd81c9914f1cc84a361

<img width="871" alt="image" src="https://user-images.githubusercontent.com/13148491/169424636-895af76e-0942-4c7d-b092-4b8d875dffc0.png">

### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by GorgonMeducer** [comment]
After changing this part of code back to the origin form (and add RGB565-A8 support), everything looks fine now:

```c
    lv_img_cf_t cf;
    if(lv_img_cf_is_chroma_keyed(cdsc->dec_dsc.header.cf)) cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED;
    else if(LV_IMG_CF_ALPHA_8BIT == cdsc->dec_dsc.header.cf) cf = LV_IMG_CF_ALPHA_8BIT;
    else if(LV_IMG_CF_RGB565A8 == cdsc->dec_dsc.header.cf) cf = LV_IMG_CF_RGB565A8;
    else if(lv_img_cf_has_alpha(cdsc->dec_dsc.header.cf)) cf = LV_IMG_CF_TRUE_COLOR_ALPHA;
    else cf = LV_IMG_CF_TRUE_COLOR;
    //lv_img_cf_t cf = cdsc->dec_dsc.header.cf;
```

I will raise a PR to fix this.

**Comment by kisvegabor** [comment]
PR is merged, closing.
