### ISSUE TITLE
Should we add scenes in benchmark for RGB565-A8?

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3379]
### Introduce the problem
We have introduced a new colour format RGB565-A8. The performance improvement for 16bit colours comes for free, as long as the resource images are converted into c arrays using this new format. 

I believe this colour format should be suggested as the recommended colour format when the target LCD is using RGB565 for all new applications. 

We can already see a lot of 2D GPU drivers are updated to take advantage of this new colour format, e.g. NXP PXP and arm-2d. 

The problem is that
1. in the benchmark, we don't have scenes to cover this new colour format. We definitely need them for helping people add new GPU and do profiling.
2. How to handle the relationship between ARGB8565 and RGB565-A8 in the same benchmark? Exclusive from each other? or Co-existing when calculating the Weighted FPS?

### Suggested solution

Solution A: 
When `LV_COLOR_DEPTH` is `16`, use a macro, for example, `LV_BM_USE_RGB565A8` to switch between ARGB8565 and RGB565-A8 for all ARGB related scenes.

**Comment by kisvegabor** [comment]
> When LV_COLOR_DEPTH is 16, use a macro, for example, LV_BM_USE_RGB565A8 to switch between ARGB8565 and RGB565-A8 for all ARGB related scenes.

It makes sense. 

> I believe this colour format should be suggested as the recommended colour format when the target LCD is using RGB565 for all new applications.

I can imagine these places to mention this new format:
- [Color formats](https://docs.lvgl.io/master/overview/image.html#color-formats)
- [Image widget](https://docs.lvgl.io/master/widgets/core/img.html)
- [Image converter](https://lvgl.io/tools/imageconverter)

Now, when someone selects "True color with alpha" format in the image converter he/she gets all color depth options selected by `#if LV_COLOR_DEPTH == ...`. What about having an option in the converter to include the `RGB565-A8` format by default, instead of the `ARGB8565`? 

cc @embeddedt  


BTW, I haven't measured the performance different between the 2 formats yet. Do have any info about it?

**Comment by GorgonMeducer** [comment]
@kisvegabor since we have no scene in the benchmark for RGB565-A8, I don't have such data also.
But as you can imagine, avoiding repeating iterations for decoding (i.e. separate pixels into rgb_buf and mask_buf), the CPU time used by decoding can be removed, this is the source of performance improvement.

**Comment by embeddedt** [comment]
> Now, when someone selects "True color with alpha" format in the image converter he/she gets all color depth options selected by #if LV_COLOR_DEPTH == .... What about having an option in the converter to include the RGB565-A8 format by default, instead of the ARGB8565?

The converter can be adjusted easily, but how does the library differentiate between older images using ARGB8565 and newer ones using RGB565-A8?

**Comment by GorgonMeducer** [comment]
@embeddedt check cf?

**Comment by embeddedt** [comment]
Right now `LV_IMG_CF_TRUE_COLOR_ALPHA` means that the image will either be RGB332, ARGB8565, or ARGB8888, depending on `LV_COLOR_DEPTH`. We would need to introduce a new cf value in order to make this change.

**Comment by GorgonMeducer** [comment]
@embeddedt we already have such new cf, i.e. `LV_IMG_CF_RGB565A8`

**Comment by kisvegabor** [comment]
> The converter can be adjusted easily, but how does the library differentiate between older images using ARGB8565 and newer ones using RGB565-A8?

If RGB565-A8 is used for 16 bit the converted image header could look like this:
```c
const lv_img_dsc_t some_image = {
  .header.always_zero = 0,
  .header.w = 100,
  .header.h = 100,
  .data_size = 10000 * LV_IMG_PX_SIZE_ALPHA_BYTE,
#if LV_COLOR_DEPTH == 16
  .header.cf = LV_IMG_CF_RGB565A8,
#else
  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
#endif

  .data = some_image,
};
```

**Comment by embeddedt** [comment]
Ah, now I understand. That's a clever approach. I will look into it!

I suppose that since the older 8.x versions are still supported, there needs to be an option to disable this so that images converted today will still work in those versions.

**Comment by kisvegabor** [comment]
Yes, it should be optional. Maybe having a checkbox like "RGB565-A8 format for 16 bit" when `TRUE_COLOR_ALPHA` is selected.

**Comment by embeddedt** [comment]
I have realized that we currently have an R-B-swapped option for ARGB8565. Are we going to need that feature for RGB565A8 as well?

**Comment by GorgonMeducer** [comment]
@embeddedt No.

In fact, my suggestion is that the high-low-byte-swapping feature should be removed from the LVGL rendering and only do it right before calling disp_flush.

**Comment by kisvegabor** [comment]
> In fact, my suggestion is that the high-low-byte-swapping feature should be removed from the LVGL rendering and only do it right before calling disp_flush.

It's faster to render with the desired (swapped) format than swapping as a separate step. I haven't measured the performance cost of manual swapping though. Probably we can find a good algorithm which work on 32 bit data to swap 2 pixels at once.

Counting with 320x240=76,800 pixels, and 2 instructions per pixel on a 80MHz MCU it's: 76,800x2/80,000,000 = ~2ms. 
30FPS->28.5FPS, so not big deal. And it should be slightly faster to render in normal  (not swapped) format. 

I added a note to https://github.com/lvgl/lvgl/issues/3298 to consider removing it.

**Comment by GorgonMeducer** [comment]
@kisvegabor the biggest problem is, if we have a swapped image, and we need to apply transform, then the decoding overhead will be very high:
1) decoding: swap to get a normal rgb565 pixel
2) transform
3) swap back to a swapped pixel for LCD flush

If we only use normal rgb565 and do it once just before disp_flush, the swap process in decoding can be removed. When GPU is available, a rgb565a8 image can be accelerated directly without decoding. 

Further more, for Cortex-M processor, the instruction __REV16 can process two 16bit pixels in one cycle, with proper loop-unrolling, we can get roughly 1cycle per-pixel performance. With helium support, we can reach  0.25 cycle per pixel performance. 

An example code for Cortex-M0+:
https://github.com/lvgl/lv_port_raspberry_pi_pico_mdk/blob/8a05050ccd94063fd311db183c6a4ca6a36bfbf8/project/mdk/RTE/LVGL/lv_port_disp_template.c#L134-L160

Here, arm compiler 6 will unroll the loop automatically in -Ofast and above

**Comment by kisvegabor** [comment]
Ok, we can even have a callback in `draw_ctx` to do the swapping.  So it can be implemented in assembly too.

Maybe we can call it `buffer_post_process_cb`. It could apply any other effect or conversion too.

**Comment by GorgonMeducer** [comment]
@kisvegabor sound like a good idea. Please also give the `buffer_post_process_cb` a meaningful return value, for example: if it returns false, then the calling of `disp_flush` will be skipped. Does this sound familiar?

**Comment by kisvegabor** [comment]
Sounds good! It can be added even for v8.3 as we can still keep `LV_COLOR_16_SWAP` for backward compatibility. 

We need to be careful about placing these new callback(s) into `lv_disp_drv_t` or `lv_draw_ctx_t`. As I see `lv_disp_drv_t` should be responsible for how the rendered image is transferred to the display while `lv_draw_ctx_t` is for how the image is rendered. Another aspect is `lv_disp_drv_t` is board/display/system dependent, while `lv_draw_ctx_t` is only MCU/architecture/software dependent.

For v9 we should review this two struct in this regard.

**Comment by kisvegabor** [comment]
I've add an option the select between the two formats.

**Comment by GorgonMeducer** [comment]
Thank you very much! @kisvegabor 
Now I can use it to test my RGB565-A8 acceleration
