### ISSUE TITLE
Message box button height fit is broken after v8

### ISSUE THREAD

**Issue by luka177** [kisvegabor/lvgl#3382]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
After v8 mbox got a bit broken and if you have more then one row of buttons it will have very small button size.

### To Reproduce
Format the code like this:
```c
#include "../../lv_examples.h"
#if LV_USE_MSGBOX && LV_BUILD_EXAMPLES

static void event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_current_target(e);
    LV_LOG_USER("Button %s clicked", lv_msgbox_get_active_btn_text(obj));
}

void lv_example_msgbox_1(void)
{
    static const char * btns[] ={"Apply", "Close", ""};

    lv_obj_t * mbox1 = lv_msgbox_create(NULL, "Hello", "This is a message box with two buttons.", btns, true);
    lv_obj_add_event_cb(mbox1, event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox1);
}

#endif
```
will work fine, but if you will try to split button to 2 rows it will become broken, i do that like this:
```c
#include "../../lv_examples.h"
#if LV_USE_MSGBOX && LV_BUILD_EXAMPLES

static void event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_current_target(e);
    LV_LOG_USER("Button %s clicked", lv_msgbox_get_active_btn_text(obj));
}

void lv_example_msgbox_1(void)
{
    static const char * btns[] ={"Apply", "\n", "Close", ""};

    lv_obj_t * mbox1 = lv_msgbox_create(NULL, "Hello", "This is a message box with two buttons.", btns, true);
    lv_obj_add_event_cb(mbox1, event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox1);
}

#endif
```

### Expected behavior
It must automatically fit buttons

### Screenshots or video
![image](https://user-images.githubusercontent.com/15714420/170524221-3c72b2b2-8587-41ab-af77-92426c138097.png)

**Comment by kisvegabor** [comment]
You can solve it by 
```c
lv_obj_set_height(lv_msgbox_get_btns(mbox1), 80);
```

**Comment by luka177** [comment]
Thanks will try, but in lvgl v7 it worked ok even without

**Comment by pete-pjb** [comment]
Hi @luka177 ,

Can you confirm if you have changed the value of:

``` #define LV_DPI_DEF ```

to something lower than 130 in 'lv_conf.h'?

Kind Regards,

Pete

**Comment by pete-pjb** [comment]
Hi @luka177 ,

I have pushed a fix [here](https://github.com/lvgl/lvgl/commit/d4c9ab5037aacdfdc42d44d791c492d89b57a23c) for this.

If you have reduced the LV_DPI_DEF value to something less than 130 with this fix the buttons will pad correctly.

cc @kisvegabor 

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
> Thanks will try, but in lvgl v7 it worked ok even without

We can improve v8 to count the rows and calculates with them.  Now LVGL just set height which makes sens for one row.

> If you have reduced the LV_DPI_DEF value to something less than 130 with this fix the buttons will pad correctly.

I'm not sure it's the right approach. In the original version DPI/10 means 25.4mm/10 = 2.54mm. Which makes sense (IMO) to always set the same  padding size in `mm` as the size of the user's finger is defined in `mm` too. In other words with a very small DPI, I think the user still wants a small extra area around the buttons' text.  Considering dpi=130 in this case would result in a larger than expected button size.

**Comment by pete-pjb** [comment]
Hi @kisvegabor ,

Sorry for my late reply I have been away on holiday.  I have reverted my change to the padding, having revisited it I was probably a bit hasty.  My apologies... 🙂 

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
No problem at all. :slightly_smiling_face:
