### ISSUE TITLE
Recolor for label text doesn't work when text is wrapped

### ISSUE THREAD

**Issue by moinmoin-sh** [kisvegabor/lvgl#3383]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When recolor is enabled `lv_label_set_recolor(label, true)` and a line of text is automatically wrapped the recolor works for the first line only, the wrapped part of the line is not recolored

### To Reproduce

```c
    lv_obj_t* act = lv_scr_act();
    lv_obj_t* label = lv_label_create(act);
    lv_obj_set_size(label, 100, LV_SIZE_CONTENT);
    lv_obj_set_style_bg_color(label, lv_palette_main(LV_PALETTE_GREY), NULL);
    lv_obj_set_style_bg_opa(label, 255, NULL);
    lv_label_set_recolor(label, true);
    lv_label_set_text(label, "#ff0000 This is a test label text#");
    lv_obj_center(label);

```

### Expected behavior

The whole text between `#ff00 some text ....# ` shall be recolored (independing from the wrap)

### Screenshots or video

![grafik](https://user-images.githubusercontent.com/53935853/170544932-e5f83a46-f9bc-4db4-9908-5f6120152789.png)

**Comment by embeddedt** [comment]
This is a known limitation, see https://github.com/lvgl/lvgl/issues/3332. Thanks for the report, though!
