### ISSUE TITLE
SDL Renderer Issue When Zoom Set

### ISSUE THREAD

**Issue by mariotaku** [kisvegabor/lvgl#3386]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

After commit https://github.com/lvgl/lvgl/commit/318146a2c25362eabf258470be263a4cfeaefe87, 
SDL renderer will have issue drawing objects has zoom transform. Object is not properly zoomed, and when drawing it invades a part of objects in the front.

![image](https://user-images.githubusercontent.com/830358/170804561-6809bd42-75b9-42ce-a45a-46e38735f8f7.png)

Sorry that I didn't post more details. I'll be investigating this issue and make patches.

**Comment by kisvegabor** [comment]
Hi,

Note that, before that commit only images could be scaled  and not any widget. 

Regarding the SDL support see this [comment](https://github.com/lvgl/lvgl/issues/3269#issuecomment-1109934136) for more context on it.

**Comment by mariotaku** [comment]
Thanks for the info. Maybe I'll need to abstract the part that it creates snapshot buffer (as SDL uses texture instead of bitmap), then support off-screen drawing to the snapshot.

**Comment by kisvegabor** [comment]
I think the `draw_ctx` should have a callback like `draw_ctx->set_buf(draw_ctx, buf)` (probably with a better name). It can create a new texture, which uses this buffer. 
IIRC correctly now `disp_drv->user_data` is used to store SDL specific stuff. Would it be possible to store them in `draw_ctx->user_data`?

**Comment by kisvegabor** [comment]
I've just realized probably there is no such a thing as a "buffer" as you use the Texture directly. Se the callback should be `draw_ctx->buf_alloc(draw_ctx, hor_res, ver_res)`

I still don't know how to blend the snapshot Texture as an image once it's rendered.

**Comment by mariotaku** [comment]
For an object, rendering on a texture is as simple as rendering on screen. Once it's rendered, it is an image (but can't be modified pixel by pixel easily). I'll explore this part for a bit and see if I can make some changes.

**Comment by kisvegabor** [comment]
I mean the snapshot is directly passed to `lv_draw_img` [here](https://github.com/lvgl/lvgl/blob/master/src/core/lv_refr.c#L997).

**Comment by mariotaku** [comment]
Oh! That's also fine. Underlying I have some logic to render SDL_Texture by passing to lv_draw_img.

**Comment by kisvegabor** [comment]
Ahh, great!

**Comment by kisvegabor** [comment]
Let's continue in the PR: https://github.com/lvgl/lvgl/pull/3403
