### ISSUE TITLE
GPU SDL Object opacity

### ISSUE THREAD

**Issue by cagrig** [kisvegabor/lvgl#3391]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When using GPU SDL, object opacity cannot be set to intermediate values. `LV_OPA_0` gives transparency but any other `LV_OPA_x` gives full opacity. This happens only when using the function `lv_obj_set_style_opa`, and if the function `lv_obj_set_style_bg_opa` is used everything works as expected.

The issue is observed while using `lv_obj_fade_in` function because its callback is based on `lv_obj_set_style_opa`.

Debug information:
While drawing of the objects `lv_draw_sdl_mask_dump_texture` function (in `lvgl/src/draw/sdl/lv_draw_sdl_mask.c`) is invoked. If I check for SDL errors in this function via `SDL_GetError()`, I am getting the message : `That operation is not supported`. In the same function, an improper surface may be passed to `SDL_CreateTextureFromSurface` . I could not verify this.

### To Reproduce

1. Use GPU SDL
2. Use any demo application
3. Create an object
4. Use `lv_obj_set_style_opa` and set the opacity to any intermediate value or use `lv_obj_fade_in` function to animate the object

### Expected behavior
Expected behavior is setting object opacity to any value in the valid interval.

### Screenshots or video
No screenshot or video is provided.

**Comment by kisvegabor** [comment]
The root of the issue should be the same as this: https://github.com/lvgl/lvgl/issues/3386

With @mariotaku, the author of the SDL support we track this problem in the mentioned issue. 

So let's continue in #3386
