### ISSUE TITLE
lv_arc drawing is not properly working in case of negative angle values

### ISSUE THREAD

**Issue by rmantovani68** [kisvegabor/lvgl#3392]
### Describe the bug
lv_arc drawing is not properly working in case of negative angle values

### To Reproduce
Draw an lv_arc setting a negative value in start or end angles

### Expected behavior
I expect to see the lv_arc well painted

### Screenshots or video

As you can see the arc is closing before  the correct point.
I've use SquareLine to reproduce the issue, but the same problem happens in real life appplication.

![lv_arc_bug](https://user-images.githubusercontent.com/13162352/171140411-79834e15-1b4c-40ca-a323-d94c394afc30.png)
![square_line_arc_bug](https://user-images.githubusercontent.com/13162352/171140403-07de3da0-49fa-44c4-a7bc-a11da38e6c61.png)

**Comment by kisvegabor** [comment]
`lv_arct_set_angles` accepts `uint16_t` parameters. See 
https://github.com/lvgl/lvgl/blob/9ac8ce69f67234563d4254e29e1903a638bb8f4e/src/widgets/lv_arc.h#L106

So it's rather related to SquareLine as it shouldn't allow negative values values here. I added this problem to SquareLine bug tracker.

**Comment by rmantovani68** [comment]
Ok

All clear

Thank you
