### ISSUE TITLE
Transparent Canvas not Working

### ISSUE THREAD

**Issue by cagrig** [kisvegabor/lvgl#3393]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
"Transparent Canvas with chroma keying" (from docs) example is not working as expected. Both of simulator (`lv_example_canvas_2()`) and [docs examples](https://docs.lvgl.io/master/examples.html) are giving same result.

It is observed after updating lvgl to its latest version. Before updating, the canvas section was working as expected.

### To Reproduce
`lv_example_canvas_2()` example can be run or [docs example](https://docs.lvgl.io/master/examples.html) can be visited.

### Expected behavior
Chroma keyed pixels should have transparency but in the examples those have green color.

### Screenshots or video
![image](https://user-images.githubusercontent.com/32802359/171184181-2b1f6f9e-6622-4200-be63-31e31f35863e.png)

The Green area is assumed to be transparent.

**Comment by cagrig** [comment]
Update:
If `LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED` and `LV_CANVAS_BUF_SIZE_TRUE_COLOR_CHROMA_KEYED` are used for canvas buffer, the canvas background can be made transparent with `lv_canvas_fill_bg(canvas, LV_COLOR_CHROMA_KEY, LV_OPA_TRANSP)`.

**Comment by kisvegabor** [comment]
With the recent updates (you mentioned) the indexed color formats really doesn't support chroma keying. Normally it's not a big problem as the palette is described with ARGB8888 colors, so an element of the palette can have alpha=0 value for transparent colors. 

The bigger problem is that there is no correct API to set the alpha channel of the palette. As workaround you can add this after setting the palette colors:
```c
    uint8_t * buf8 = (uint8_t *) cbuf;
    buf8[3] = 0x00;  /*Make the first color transparent*/
```

I added [a note](https://github.com/lvgl/lvgl/issues/3298) to fix the canvas API in v9.

**Comment by cagrig** [comment]
Thank you for your detailed explanation.
