### ISSUE TITLE
 Crash in some cases, introduced by fix of issue #2868: Updating arc causes memory leak in specific situation 

### ISSUE THREAD

**Issue by ivooesch** [kisvegabor/lvgl#3398]
### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

in file src/draw/sw/lv_draw_sw_arc.c:
lv_draw_mask_free_param() is called on unitiialized mask in certain cases

When drawing a filled circle, the inner area has a size of 0,
an therefore mask_in_param will not get initialized,
resulting in a hardfault as lv_draw_mask_free_param()
is done always, even if mask_in_param was not initialized.
lv_draw_mask_free_param should only be done if
mask_in_param was initialized, e.g. when
(lv_area_get_width(&area_in) > 0 && lv_area_get_height(&area_in)) > 0 was true

Code snippet (look for '<<<<<<<'):
```c
/Create inner the mask/
int16_t mask_in_id = LV_MASK_ID_INV;
lv_draw_mask_radius_param_t mask_in_param;

if(lv_area_get_width(&area_in) > 0 && lv_area_get_height(&area_in) > 0) {
   //<<<<< Init only done if area is not 0 >>>>>>>>>
   lv_draw_mask_radius_init(&mask_in_param, &area_in, LV_RADIUS_CIRCLE, true);
   mask_in_id = lv_draw_mask_add(&mask_in_param, NULL);
}

lv_draw_mask_radius_param_t mask_out_param;
lv_draw_mask_radius_init(&mask_out_param, &area_out, LV_RADIUS_CIRCLE, false);
int16_t mask_out_id = lv_draw_mask_add(&mask_out_param, NULL);

/*Draw a full ring*/
if(start_angle + 360 == end_angle || start_angle == end_angle + 360) {
    cir_dsc.radius = LV_RADIUS_CIRCLE;
    lv_draw_rect(draw_ctx, &cir_dsc, &area_out);

    lv_draw_mask_remove_id(mask_out_id);
    if(mask_in_id != LV_MASK_ID_INV)  lv_draw_mask_remove_id(mask_in_id);
      

    lv_draw_mask_free_param(&mask_out_param);

  //<<<<<< Free always done, results in hardfault when area was 0 >>>>>>>>>>>>
  // This line was introduced while fixing issue #2868:
    lv_draw_mask_free_param(&mask_in_param);

    return;
}
```

### Expected behavior

Free mask_in_param only if initialize before

**Comment by kisvegabor** [comment]
It seems your are right. Can you send a pull request with the fix?

**Comment by ivooesch** [comment]
Sent Pullrequest #3399 with a possible fix, probably not the most efficient, as I am new with LVGL.
Used just a boolean to know if mask_in_param is initialized.
As I see it, (mask_in_id != LV_MASK_ID_INV) cannot be used, since lv_draw_mask_add() might also return LV_MASK_ID_INV.
Instead of a boolean, it might also be possible to use
lv_area_get_width(&area_in) > 0 && lv_area_get_height(&area_in) > 0) 
again, but to me it looks more complicated and difficult to read, and I am not sure if area_in is unmodified during the whole function body.

**Comment by kisvegabor** [comment]
Merged, thank you!
