### ISSUE TITLE
png images stored as LV_IMG_SRC_VARIABLE are not rendered properly

### ISSUE THREAD

**Issue by moinmoin-sh** [kisvegabor/lvgl#3400]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

.png image created as .c file with the online image converter is not rendered properly.
The example `lv_example_png_1.c` shows this issue.

original image descriptor 
 ```c
const lv_img_dsc_t img_wink_png = {
    .header.always_zero = 0,
    .header.w = 50,
    .header.h = 50,
    .data_size = 5158,
    .header.cf = LV_IMG_CF_RAW_ALPHA,
    .data = img_wink_png_map,
};
```

if its is manually changed to 
```c
const lv_img_dsc_t img_wink_png = {
    .header.always_zero = 0,
    .header.w = 50,
    .header.h = 50,
    .data_size = 5158,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = img_wink_png_map,
};
```
The image is displayed correctly.

Note: the original result from the online image converter sets `header.w` and `header.h` to `0` which results in nothing displayed. With .w and .h set properly, the corrupted images as shown below is displayed.
Only if .h , .w and .cf are set as above the image is correctly displayed.

### To Reproduce

relevant code portion is the first part that deals with the image stored as variable.

```c
#include "../../lv_examples.h"
#if LV_USE_PNG && LV_USE_IMG && LV_BUILD_EXAMPLES

/**
 * Open a PNG image from a file and a variable
 */
void lv_example_png_1(void)
{
    LV_IMG_DECLARE(img_wink_png);
    lv_obj_t * img;

    img = lv_img_create(lv_scr_act());
    lv_img_set_src(img, &img_wink_png);
    lv_obj_align(img, LV_ALIGN_LEFT_MID, 20, 0);

    img = lv_img_create(lv_scr_act());
    /* Assuming a File system is attached to letter 'A'
     * E.g. set LV_USE_FS_STDIO 'A' in lv_conf.h */
    lv_img_set_src(img, "A:lvgl/examples/libs/png/wink.png");
    lv_obj_align(img, LV_ALIGN_RIGHT_MID, -20, 0);
}

#endif
```

### Screenshots or video

![grafik](https://user-images.githubusercontent.com/53935853/171946725-14c85ec4-5c9f-4024-aca1-f45f600e8dc8.png)

**Comment by kisvegabor** [comment]
`img_wink_png` is working well for me with the original settings:

```c
const lv_img_dsc_t img_wink_png = {
    .header.always_zero = 0,
    .header.w = 50,
    .header.h = 50,
    .data_size = 5158,
    .header.cf = LV_IMG_CF_RAW_ALPHA,
    .data = img_wink_png_map,
};
```

What is your `LV_COLOR_DEPTH` setting?

> Note: the original result from the online image converter sets header.w and header.h to 0 which results in nothing displayed. 

cc @embeddedt

**Comment by moinmoin-sh** [comment]
#define `LV_COLOR_DEPTH `16

that's strange ??
Please note also, that the online image converter sets `header.w` and `header.h` to `0`

**Comment by embeddedt** [comment]
The image converter will always set `w` and `h` to 0 if you convert an image using a RAW format. This is because the file contents are just stored within the array and not decoded and converted at all with that format.

**Comment by moinmoin-sh** [comment]
Hm, but your data above  shows `h` and `w` set to 50. In my case nothing is displayed with `h` and `w` set to 0?

**Comment by moinmoin-sh** [comment]
I have to apologize ... I got confused for some reason and double checked.

Actual status : 
`.header.cf = LV_IMG_CF_RAW_ALPHA,` **works**,  image is displayed 

BUT  with
```
   .header.w = 0,
   .header.h = 0,
```
 **Nothing** is displayed.

Sorry for the confusion.

**Comment by kisvegabor** [comment]
I can confirm that it works like this.

@embeddedt would it be possible to set width/height too if the image can be opened by the converter?

**Comment by embeddedt** [comment]
It's possible, but I'm not sure that it makes sense. For raw mode, the input file is stored unchanged, including its header, so isn't the decoder expected to read that header to find the actual width & height? The `data_size` is still provided correctly.

**Comment by kisvegabor** [comment]
It'm not sure it's consistent, but when LVGL sees an `lv_img_dsc_t` variable it assumes that the width and height are set there. It will work better with @X-Ryl669 [decoder updated](https://github.com/lvgl/lvgl/pull/3294) (planned for v8.3) so I wouldn't change LVGL for this short time. I think 99% of the problems (even in the earlier version) can be solved if the converter tries to extract the dimensions of the image.

**Comment by X-Ryl669** [comment]
Yes, that's one of the issue I've come upon and I think, I've solved. The online converter tool shouldn't be necessary anymore for upcoming version, since the actual image content is used to extract metadata (like size & color format) and it does not rely on the online tool to build a functional header. Ideally, the raw image decoder will become optional and can be skipped from building since it's not very efficient to store a raw image in a binary.

**Comment by kisvegabor** [comment]
> Ideally, the raw image decoder will become optional and can be skipped from building since it's not very efficient to store a raw image in a binary.

IMO the biggest advantage of the raw format is that it needs no RAM and still supports transformations.

**Comment by moinmoin-sh** [comment]
May I ask what the path forward will be? How will the handling with .PNG images in the "upcoming version" be?

**Comment by X-Ryl669** [comment]
In LVGL v9, LVGL will become smarter, so it'll better deal with encoded image file efficiently. You won't need to use the online converter, and your binary will be smaller since you'll only embed the encoded picture. The downside is that the image will take a bit more time to load at first and it'll use a bit of memory.

The online converter will only be useful if you need to perform transformation (rotation & zoom) on some encoded picture (like GIF or PNG), or if you are very limited in RAM (but not in flash) and you can have mappable flash space as RAM (not all system allow this). 

Typically, you'll write this:
```cpp
   // From .data section, stored in application binary
   const uint8_t png_file[] = { ... // from any tool to convert a file to C array };

   lv_img * img = lv_img_create(parent);
   lv_img_set_src(img, lv_img_src_from_data(png_file, sizeof(png_file)));

   // Or this, using the stdlib's filesystem, using RAM to store (a part of) the file
   lv_img_set_src(img, lv_img_src_from_file("/path/to/file.png"));

   // On ESP32 with FrogFS filesystem, get read only memory map of flash filesystem
   frogfs_file_t * file = frogfs_open(fs, "/path/to/file.png");
   void * png_data;
   size_t len = frogfs_faccess(file, &png_data);

   lv_img_set_src(img, lv_img_src_from_data((const uint8_t*)png_data, len));
   frogfs_close(file);

```

**Comment by moinmoin-sh** [comment]
That sounds very promissing! Would make my life easier. Hope v9 is available soon.

**Comment by moinmoin-sh** [comment]
I'm really interested in this new feature, Is v9 available for testing?

**Comment by kisvegabor** [comment]
We will release v8.3 in a few weeks and start to work on v9 after that. Although, the feature @X-Ryl669 mentioned is available in this PR: https://github.com/lvgl/lvgl/pull/3294

You can try it out with:
```git
git checkout -b X-Ryl669-imgdecoder arch/img-decode-rework
git pull https://github.com/X-Ryl669/lvgl.git imgdecoder
```

**Comment by moinmoin-sh** [comment]
unfortunately that didn't work for me

```
git checkout -b X-Ryl669-imgdecoder arch/img-decode-rework
>>
fatal: 'arch/img-decode-rework' is not a commit and a branch 'X-Ryl669-imgdecoder' cannot be created from it
```

**Comment by kisvegabor** [comment]
I see the same issue. @X-Ryl669 could you take a look at it?

**Comment by embeddedt** [comment]
This should work?

```
git remote add imgdecoder https://github.com/X-Ryl669/lvgl.git
git fetch imgdecoder
git checkout -b X-Ryl669-imgdecoder imgdecoder/imgdecoder
```

**Comment by moinmoin-sh** [comment]
Thanks for your effort. The above works github wise, but I can't get the above proposal running. I don't want to bother further and will wailt untill v9 becomes available.

For now I devolped a simple patch to `lv_png.c` that uses the same calculations for `w `and `h ` as done in case of `LV_IMG_SRC_FILE`. That makes the file from the online converter with `h `and `w `set to `0 `usable.

```
    /*If it's a PNG file in a  C array...*/
    else if(src_type == LV_IMG_SRC_VARIABLE) {
        const lv_img_dsc_t * img_dsc = src;
        const uint32_t data_size = img_dsc->data_size;
        const uint8_t magic[] = {0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a};
        if(data_size < sizeof(magic)) return LV_RES_INV;
        if(memcmp(magic, img_dsc->data, sizeof(magic))) return LV_RES_INV;

        /* Read the width and height from img_dsc->data. They have a constant location:
         * [16..23]: width
         * [24..27]: height
         */
        uint32_t size[2];
        memcpy(&size[0], img_dsc->data+16, 8);

        header->always_zero = 0;
        header->cf = img_dsc->header.cf;       /*Save the color format*/
        //header->w = img_dsc->header.w;         /*Save the color width*/
        //header->h = img_dsc->header.h;         /*Save the color height*/
        /*The width and height are stored in Big endian format so convert them to little endian*/
        header->w = (lv_coord_t)((size[0] & 0xff000000) >> 24) + ((size[0] & 0x00ff0000) >> 8);
        header->h = (lv_coord_t)((size[1] & 0xff000000) >> 24) + ((size[1] & 0x00ff0000) >> 8);

        return LV_RES_OK;
    }
```
