### ISSUE TITLE
Bug with LV_ARC_MODE_REVERSE

### ISSUE THREAD

**Issue by jadonmmiller** [kisvegabor/lvgl#3417]
### Describe the bug

When using LV_ARC_MODE_REVERSE, the value of the arc appears incorrectly. This is because the arc's value is mapped the same way in reverse mode as in normal mode. I have found the issue and will submit a pull request shortly; this issue is simply for a documentation paper trail. 😃 

### To Reproduce

```c
    lv_obj_t* arc = lv_arc_create(lv_scr_act()); //Create an arc
    lv_obj_center(arc); //Center it on the screen
    lv_arc_set_mode(arc, LV_ARC_MODE_REVERSE); //Put it into reverse mode
    lv_arc_set_value(arc, 25); //Set it to 25%
```
This code makes the screenshot below,
![LVGL Fix Before](https://user-images.githubusercontent.com/61329420/174415095-673d6ff4-8e4a-4bf7-9c7a-f736ffa6f49f.png)
which appears as 75%, not 25%.

### Expected behavior

In this screenshot,
![LVGL Fix After](https://user-images.githubusercontent.com/61329420/174415094-3841f153-e0ff-43cd-90c3-9c84d1238e96.png)
the arc shows 25%.

**Comment by jadonmmiller** [comment]
Wait a second... The documentation for the arc has been revised since I noticed this "bug" last fall. It seems like this is intended behavior? If so, should the behavior I'm looking for be an additional option?

Basically, I'm making a cluster of arcs used as indicators. I have a normal arc in the middle, then a half-arc on each side to show the level of three tanks. These should work like graphs, with 0% on the bottom and 100% on the top of the half-arcs.

I apologize; it seems I was too hasty in declaring a bug. I do think, however, that the behavior described above would be useful as a feature built into the library. Just let me know how you want to proceed and how this fits into your vision for the library.

Thanks!

**Comment by jadonmmiller** [comment]
I'm afraid I've not had the time to work on this, and I likely won't in the near future. If someone wants to take the idea and my initial work, go for it. There are more details about the current status in #3418.

**Comment by kisvegabor** [comment]
No problem. I've just fixed the failing unit test and merged your fix.

Thank you!
