### ISSUE TITLE
flickering on iMX RT 1060

### ISSUE THREAD

**Issue by rmantovani68** [kisvegabor/lvgl#3421]
### Describe the bug
If using latest PXP usable version (master) the screen is flickering under particular circumstances (images with color background).    

- I'm using LVGL on a NXP i.MX RT1060 MCU based board.  
- The screen (240x320) is flickering on the lower half side (see attached video)
- The version deployed by NXP is v 8.0.2  and it's not having this problem
- I downloaded and built and linked against master  (aka 8.3.0) dated 01-06-2022  
   (mainly because I need clipping - not supported in 8.0.2, and new - layered - drawing functions )  
- Cannot use v 8.2.0 because of a problem in pxp gpu management [(#3191)](https://github.com/lvgl/lvgl/issues/3191)  

### Expected behavior
I expect that the screen is not flickering

### Video

[](https://user-images.githubusercontent.com/13162352/174971167-f0fb14c3-6d83-4dd4-9123-9bdf41b0e926.mp4)

**Comment by kisvegabor** [comment]
Do you see the same issue without NXP too?

cc @nicusorcitu

**Comment by rmantovani68** [comment]
> Do you see the same issue without NXP too?  
on other boards  ? I haven't tried

On PC windows simulator is working without flickering (but my notebook is an I7 with 16GB ram :-) )  

Maybe I'm wrong but it seems connected to images drawing and with background not null.  

Would you like a specific test ? in this case you would need a RT1060 family board

**Comment by kisvegabor** [comment]
Sorry, I meant to write "Do you see the same issue without **PXP** too?" :smile:

**Comment by rmantovani68** [comment]
Do you mean to disable pxp on RT1060 ?    

this ?  
#define LV_USE_GPU_NXP_PXP 0

**Comment by kisvegabor** [comment]
Yes

**Comment by rmantovani68** [comment]
just trying

**Comment by rmantovani68** [comment]
Yes, it's flickering also with  

```C
#define LV_USE_GPU_NXP_PXP 0
```

https://user-images.githubusercontent.com/13162352/175521850-f2d2e97a-e88a-48ae-a944-d728feaf26a7.mp4

**Comment by kisvegabor** [comment]
Normally I'd say it should be unrelated to LVGL and it's probably a display controller or memory configuration issue, but you said it was working with v8.0.2.

I can't recall any new feature which can cause such flickering but here is a few things to test: 
- do you see the same flickering with an empty screen too? 
- do you flickering when the screen is no animated/updated too?
- do you see the same flickering when only small area is changing? E.g. have only one label on the screen showing a counter.

Some questions about your driver:
- have you enabled the `disp_drv.full_refresh` flag?
- do you use DMA to or GPU in `flush_cb`?
- in which memory do you store the frame buffer(s) and draw buffer(s)?

**Comment by rmantovani68** [comment]
Thank you for the reply
I will check and reply all the questions in the beginning of the next week.

**Comment by nicusorcitu** [comment]
Are you using single buffer or double buffer? I will search for an RT1160 and run some tests on it.

**Comment by nicusorcitu** [comment]
Are you using SDK 2.11?
Talked to the SDK team and there was an issue in lvgl_support.c file that could result to flicker in SDK 2.11 and was fixed in SDK 2.12 (not released yet).

**Comment by rmantovani68** [comment]
I'm not able to check it now
I will do it next week

**Comment by rmantovani68** [comment]
Version is 2.11

**Comment by rmantovani68** [comment]
Here I am

> Normally I'd say it should be unrelated to LVGL and it's probably a display controller or memory configuration issue, but you said it was working with v8.0.2.
> 
> I can't recall any new feature which can cause such flickering but here is a few things to test:
> 
> * do you see the same flickering with an empty screen too?

No flickering if the screen is empty

> * do you flickering when the screen is no animated/updated too?

No flickering if the screen is not animated / updated

> * do you see the same flickering when only small area is changing? E.g. have only one label on the screen showing a counter.

If a label is updated every 50ms **is** flickering

> 
> Some questions about your driver:
> 
> * have you enabled the `disp_drv.full_refresh` flag?  

Yes : 
```C
/**
 * @brief LVGL port Display init function.
 * 
 */
static void _il_drv_port_disp_init(il_drv_t *d)
{
    static lv_disp_draw_buf_t dispBuf;
    uint32_t pixelCount = d->width * d->height;
    uint32_t fbSize = Display_GetFrameBufferSize();
    void *fbAddr = (void *)Display_GetFrameBufferAddress();

    lv_disp_draw_buf_init(&dispBuf, fbAddr, fbAddr + fbSize, pixelCount);

    /*-----------------------------------
     * Register the display in lvgl
     *----------------------------------*/

    lv_disp_drv_t *drv = &(d->disp_drv);

    /* Basic initialization */
    lv_disp_drv_init(drv);

    /* Set the resolution of the display */
    drv->hor_res = d->width;
    drv->ver_res = d->height;

    /* Used to copy the buffer's content to the display */
    drv->flush_cb = _il_drv_flush_cb;
    /* Wait flush */
    drv->wait_cb  = _il_drv_flush_wait_cb;

#if LV_USE_GPU_NXP_PXP
    /* Clean cache function */
    drv->clean_dcache_cb = _il_drv_cache_clean_cb;
#endif

    /* Set a display buffer */
    drv->draw_buf = &dispBuf;

    /* Full refresh */
    drv->full_refresh = 1;

    /* Finally register the driver */
    lv_disp_drv_register(drv);
}


```

> * do you use DMA to or GPU in `flush_cb`?

No in flush_cb the framebuffer is simply switched after cleaning the cache.

> * in which memory do you store the frame buffer(s) and draw buffer(s)?

The frame buffer is stored in a non cached memory area in OCRAM.
Draw buffer is stored in a cached memory area in OCRAM

**Comment by kisvegabor** [comment]
> The frame buffer is stored in a non cached memory area in OCRAM.
Draw buffer is stored in a cached memory area in OCRAM

I don't got it.  
```c
    lv_disp_draw_buf_init(&dispBuf, fbAddr, fbAddr + fbSize, pixelCount);
```

This line suggests that the frame buffer and the draw buffers are the same thing.

**Comment by rmantovani68** [comment]
Do you mean fbAddr and fbAddr+fbSize ?
They are two different memory areas
The first is used to define the buffer used for lvgl drawing 
The second is used for lvgl images

right ?

**Comment by pdgendt** [comment]
Not sure if this is helpful, but you can increase the read QOS for the LCD interface.

For i.MXRT1064 I've added:
```
	#define GPV0_BASE     0x41000000
	#define read_qos_LCD  (0x44000 + 0x100)
	// Increase read_qos bus arbitration for LCD to avoid underflow
	// so that the LCDIF has SDRAM bus read priority over the core
	// which has default priority 4.  This prevents flicker and LCD
	// buffer disturbance when running code in XIP from SPI Flash
	// See i.MX RT1064 Reference Manual sec 29.4, SIM_MAIN
	*(uint32_t*)(GPV0_BASE + read_qos_LCD) = 10;
```

**Comment by kisvegabor** [comment]
> Do you mean fbAddr and fbAddr+fbSize ?

Yes.

> The first is used to define the buffer used for lvgl drawing
The second is used for lvgl images
right ?

Nope. Both for drawing. See [here](https://docs.lvgl.io/master/porting/display.html#two-buffers).

**Comment by rmantovani68** [comment]
This is an update
Using SDK v 2.12 from NXP instead of v 2.11 solved the problem

**Comment by kisvegabor** [comment]
Great news! I'm closing this issue then.
