### ISSUE TITLE
gcc pedantic and  empty translation units

### ISSUE THREAD

**Issue by JAremko** [kisvegabor/lvgl#3424]
When running gcc with `-Werror=pedantic` it complains that "ISO C forbids an empty translation unit"  maybe you should add something like a dummy `typedef` when, lets say, tests are excluded. Just to make pedantic compilers happy.

**Comment by kisvegabor** [comment]
Which is the problematic file?

**Comment by JAremko** [comment]
`lvgl/env_support/rt-thread/lv_rt_thread_port.c` and files with  `#if LV_BUILD_TEST` like `lvgl/tests/src/test_cases/_test_template.c` 
 `lvgl/tests/unity/unity.c` (plenty of them)

**Comment by kisvegabor** [comment]
You should build the files only from the `src` folder.
