### ISSUE TITLE
Error code in function _lv_obj_style_create_transition

### ISSUE THREAD

**Issue by zhango5** [kisvegabor/lvgl#3427]
### Introduce the problem
Whether the wrong function is used in lv_obj_style.c line 344

### Examples and cases
![image](https://user-images.githubusercontent.com/19200786/175818479-52065b5a-d04b-4783-880f-a5e0e9075bc7.png)

Here is the height of @obj, not width. Otherwise,the following code "LV_MIN" is not work.

### Suggested solution
Use the function lv_obj_get_height

**Comment by kisvegabor** [comment]
Thank you, fixed.
