### ISSUE TITLE
How can I run it on raspberry PI 4B?

### ISSUE THREAD

**Issue by htk719809837** [kisvegabor/lvgl#3433]
How can I run it on raspberry PI 4B? Is there a detailed tutorial? When I click on the raspberry PI development link in the document, it shows 404。thanks！Looking forward to your early reply.

**Comment by kisvegabor** [comment]
Hi,

You should use this project: https://github.com/lvgl/lv_port_linux_frame_buffer

I've updated the README too.

**Comment by htk719809837** [comment]
thank you, i will try it!
