### ISSUE TITLE
The default LV_MEM_SIZE is too small to finish running benchmark

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3434]
The default size of `LV_MEM_SIZE` (which is 64KByte) is too small to finish running the benchmark.

70K - Failed
128K - Failed
200K - Failed
256K - Pass

I highly suspect that there is some memory leaking issue in the newly added layer part (f5759351806d8b14537c0488842e3c7132c72fc9)

I tested it on a 320 * 240 RGB565 env.

### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

It is blocked in an assert. 
![image](https://user-images.githubusercontent.com/13148491/176562566-0f87e620-9ba1-4e9b-ae6b-30274156a778.png)

**Comment by Viatorus** [comment]
I get the same issue under Linux and ARM.

The problem seems to be:

This isn't called:
https://github.com/lvgl/lvgl/blob/cbff8e83e50fecc2b4b43d661deb91d8d81d6696/src/core/lv_refr.c#L964

Because this returns before:
https://github.com/lvgl/lvgl/blob/cbff8e83e50fecc2b4b43d661deb91d8d81d6696/src/core/lv_refr.c#L918-L922

Why does it return? Because of this:
https://github.com/lvgl/lvgl/blob/cbff8e83e50fecc2b4b43d661deb91d8d81d6696/src/draw/sw/lv_draw_sw_layer.c#L46-L49

So setting `LV_COLOR_SCREEN_TRANSP` to 1 should do the trick.

But the screen doesn't support `LV_COLOR_SCREEN_TRANSP`.... hmm..


**EDIT:**

Just a side note:

Comparing the benchmark results between LVGL 8.2 and LVGL 8.3 nearly all SubStr. benchmark are worse than before.
E.g. Substr. rectangle has 41 fps less than in LVGL 8.2.

**Comment by GorgonMeducer** [comment]
Fixed

**Comment by kisvegabor** [comment]
> Comparing the benchmark results between LVGL 8.2 and LVGL 8.3 nearly all SubStr. benchmark are worse than before.
E.g. Substr. rectangle has 41 fps less than in LVGL 8.2.

Is it better is you increase `LV_LAYER_SIMPLE_BUF_SIZE`?

**Comment by Viatorus** [comment]
> > Comparing the benchmark results between LVGL 8.2 and LVGL 8.3 nearly all SubStr. benchmark are worse than before.
> > E.g. Substr. rectangle has 41 fps less than in LVGL 8.2.
> 
> Is it better is you increase `LV_LAYER_SIMPLE_BUF_SIZE`?

Absolute no difference. I stepped through and the bigger buffer is allocated but no difference in FPS.

**Comment by kisvegabor** [comment]
> Substr. rectangle has 41 fps less than in LVGL 8.2.

What was the original FPS?

**Comment by Viatorus** [comment]
Here are my benchmark results.

LVGL 8.2/8.3 running on STM32H7 with double buffer LTDC, CPU 280 MHz, program code located on OctoSPI 80 MHz, ITCM & DTCM enabled, no further optimization (e.g. code relocation into RAM)

| Name                               | LVGL 8.2 | LVGL 8.3 | Diff 8.2 -> 8.3 |
|------------------------------------|----------|----------|-----------------|
| Rectangle                          | 105      | 100      | -5              |
| Rectangle+OPA                      | 81       | 87       | 6               |
| Rectangle rounded                  | 84       | 84       | 0               |
| Rectangle rounded+OPA              | 82       | 75       | -7              |
| Circle                             | 81       | 79       | -2              |
| Circle+OPA                         | 79       | 67       | -12             |
| Border                             | 120      | 96       | -24             |
| Border+OPA                         | 114      | 92       | -22             |
| Border rounded                     | 87       | 87       | 0               |
| Border rounded+OPA                 | 85       | 80       | -5              |
| Circle border                      | 81       | 67       | -14             |
| Circle border+OPA                  | 82       | 67       | -15             |
| Border top                         | 89       | 93       | 4               |
| Border top+OPA                     | 88       | 83       | -5              |
| Border left                        | 91       | 83       | -8              |
| Border left+OPA                    | 91       | 83       | -8              |
| Border top + left                  | 86       | 80       | -6              |
| Border top + left+OPA              | 85       | 87       | 2               |
| Border left + right                | 85       | 81       | -4              |
| Border left + right+OPA            | 85       | 84       | -1              |
| Border top + bottom                | 85       | 86       | 1               |
| Border top + bottom+OPA            | 84       | 84       | 0               |
| Shadow small                       | 54       | 49       | -5              |
| Shadow small+OPA                   | 53       | 52       | -1              |
| Shadow small offset                | 50       | 53       | 3               |
| Shadow small offset+OPA            | 50       | 54       | 4               |
| Shadow large                       | 31       | 32       | 1               |
| Shadow large+OPA                   | 31       | 34       | 3               |
| Shadow large offset                | 39       | 42       | 3               |
| Shadow large offset+OPA            | 43       | 40       | -3              |
| Image RGB                          | 105      | 101      | -4              |
| Image RGB+OPA                      | 102      | 95       | -7              |
| Image ARGB                         | 100      | 95       | -5              |
| Image ARGB+OPA                     | 98       | 96       | -2              |
| Image chorma keyed                 | 96       | 96       | 0               |
| Image chorma keyed+OPA             | 96       | 87       | -9              |
| Image indexed                      | 87       | 75       | -12             |
| Image indexed+OPA                  | 74       | 72       | -2              |
| Image alpha only                   | 77       | 75       | -2              |
| Image alpha only+OPA               | 72       | 68       | -4              |
| Image RGB recolor                  | 86       | 90       | 4               |
| Image RGB recolor+OPA              | 77       | 80       | 3               |
| Image ARGB recolor                 | 88       | 88       | 0               |
| Image ARGB recolor+OPA             | 90       | 74       | -16             |
| Image chorma keyed recolor         | 86       | 89       | 3               |
| Image chorma keyed recolor+OPA     | 89       | 77       | -12             |
| Image indexed recolor              | 68       | 65       | -3              |
| Image indexed recolor+OPA          | 57       | 56       | -1              |
| Image RGB rotate                   | 35       | 80       | 45              |
| Image RGB rotate+OPA               | 35       | 61       | 26              |
| Image RGB rotate anti aliased      | 17       | 35       | 18              |
| Image RGB rotate anti aliased+OPA  | 17       | 35       | 18              |
| Image ARGB rotate                  | 35       | 72       | 37              |
| Image ARGB rotate+OPA              | 35       | 63       | 28              |
| Image ARGB rotate anti aliased     | 17       | 35       | 18              |
| Image ARGB rotate anti aliased+OPA | 17       | 35       | 18              |
| Image RGB zoom                     | 35       | 82       | 47              |
| Image RGB zoom+OPA                 | 35       | 64       | 29              |
| Image RGB zoom anti aliased        | 17       | 35       | 18              |
| Image RGB zoom anti aliased+OPA    | 17       | 35       | 18              |
| Image ARGB zoom                    | 35       | 77       | 42              |
| Image ARGB zoom+OPA                | 35       | 75       | 40              |
| Image ARGB zoom anti aliased       | 17       | 35       | 18              |
| Image ARGB zoom anti aliased+OPA   | 17       | 35       | 18              |
| Text small                         | 37       | 36       | -1              |
| Text small+OPA                     | 36       | 36       | 0               |
| Text medium                        | 36       | 36       | 0               |
| Text medium+OPA                    | 36       | 36       | 0               |
| Text large                         | 36       | 36       | 0               |
| Text large+OPA                     | 36       | 36       | 0               |
| Text small compressed              | 44       | 42       | -2              |
| Text small compressed+OPA          | 41       | 43       | 2               |
| Text medium compressed             | 44       | 44       | 0               |
| Text medium compressed+OPA         | 43       | 43       | 0               |
| Text large compressed              | 52       | 52       | 0               |
| Text large compressed+OPA          | 46       | 52       | 6               |
| Line                               | 80       | 81       | 1               |
| Line+OPA                           | 85       | 80       | -5              |
| Arc think                          | 81       | 76       | -5              |
| Arc think+OPA                      | 81       | 75       | -6              |
| Arc thick                          | 78       | 80       | 2               |
| Arc thick+OPA                      | 77       | 78       | 1               |
| Substr. rectangle                  | 84       | 44       | -40             |
| Substr. rectangle+OPA              | 82       | 38       | -44             |
| Substr. border                     | 79       | 56       | -23             |
| Substr. border+OPA                 | 85       | 52       | -33             |
| Substr. shadow                     | 36       | 25       | -11             |
| Substr. shadow+OPA                 | 37       | 25       | -12             |
| Substr. image                      | 87       | 67       | -20             |
| Substr. image+OPA                  | 96       | 64       | -32             |
| Substr. line                       | 79       | 62       | -17             |
| Substr. line+OPA                   | 80       | 67       | -13             |
| Substr. arc                        | 82       | 81       | -1              |
| Substr. arc+OPA                    | 82       | 76       | -6              |
| Substr. text                       | 36       | 27       | -9              |
| Substr. text+OPA                   | 36       | 25       | -11             |

**Comment by kisvegabor** [comment]
Hmmm, in summary:
- Border got slower
- Image transformation got faster (I really improved it, the double FPS makes sense)
- Subcontracted blend mode got slower. 

I'll check it out too, but I see not reason why Border became slower.

**Comment by kisvegabor** [comment]
I found the issue. In v8.2 when a color was blended LVGL cached the previous destination and source pixel and didn't do the expensive additive/subtractive blending on the same data again. In v8.3 non-normal blended objects are rendered into a layer first (which is an image) and that image is blended. But on images it was assumed that there are not many similar pixels so this caching wasn't implemented.  

However in the benchmark , e.g. in "Substr. rectangle" a lot of plain rectangles are blended and we could make a good use of this cache.  I'm trying to add caching here too.

**Comment by kisvegabor** [comment]
I pushed a fix to speed it up (5a06fce47).

It's still not the same as before, but much better. Could you rerun the benchmark on your end too?

**Comment by Viatorus** [comment]
| Name                               | LVGL 8.2 | 8.3 (old) | 8.3 (new) | Diff 8.3 old -> new |
|------------------------------------|----------|-----------|-----------|---------------------|
| Rectangle                          | 105      | 100       | 91        | -9                  |
| Rectangle+OPA                      | 81       | 87        | 87        | 0                   |
| Rectangle rounded                  | 84       | 84        | 88        | 4                   |
| Rectangle rounded+OPA              | 82       | 75        | 75        | 0                   |
| Circle                             | 81       | 79        | 78        | -1                  |
| Circle+OPA                         | 79       | 67        | 69        | 2                   |
| Border                             | 120      | 96        | 96        | 0                   |
| Border+OPA                         | 114      | 92        | 91        | -1                  |
| Border rounded                     | 87       | 87        | 84        | -3                  |
| Border rounded+OPA                 | 85       | 80        | 82        | 2                   |
| Circle border                      | 81       | 67        | 72        | 5                   |
| Circle border+OPA                  | 82       | 67        | 69        | 2                   |
| Border top                         | 89       | 93        | 82        | -11                 |
| Border top+OPA                     | 88       | 83        | 83        | 0                   |
| Border left                        | 91       | 83        | 80        | -3                  |
| Border left+OPA                    | 91       | 83        | 86        | 3                   |
| Border top + left                  | 86       | 80        | 80        | 0                   |
| Border top + left+OPA              | 85       | 87        | 84        | -3                  |
| Border left + right                | 85       | 81        | 84        | 3                   |
| Border left + right+OPA            | 85       | 84        | 83        | -1                  |
| Border top + bottom                | 85       | 86        | 82        | -4                  |
| Border top + bottom+OPA            | 84       | 84        | 82        | -2                  |
| Shadow small                       | 54       | 49        | 48        | -1                  |
| Shadow small+OPA                   | 53       | 52        | 50        | -2                  |
| Shadow small offset                | 50       | 53        | 54        | 1                   |
| Shadow small offset+OPA            | 50       | 54        | 49        | -5                  |
| Shadow large                       | 31       | 32        | 32        | 0                   |
| Shadow large+OPA                   | 31       | 34        | 32        | -2                  |
| Shadow large offset                | 39       | 42        | 39        | -3                  |
| Shadow large offset+OPA            | 43       | 40        | 40        | 0                   |
| Image RGB                          | 105      | 101       | 111       | 10                  |
| Image RGB+OPA                      | 102      | 95        | 95        | 0                   |
| Image ARGB                         | 100      | 95        | 92        | -3                  |
| Image ARGB+OPA                     | 98       | 96        | 93        | -3                  |
| Image chorma keyed                 | 96       | 96        | 97        | 1                   |
| Image chorma keyed+OPA             | 96       | 87        | 90        | 3                   |
| Image indexed                      | 87       | 75        | 71        | -4                  |
| Image indexed+OPA                  | 74       | 72        | 63        | -9                  |
| Image alpha only                   | 77       | 75        | 68        | -7                  |
| Image alpha only+OPA               | 72       | 68        | 58        | -10                 |
| Image RGB recolor                  | 86       | 90        | 91        | 1                   |
| Image RGB recolor+OPA              | 77       | 80        | 78        | -2                  |
| Image ARGB recolor                 | 88       | 88        | 84        | -4                  |
| Image ARGB recolor+OPA             | 90       | 74        | 82        | 8                   |
| Image chorma keyed recolor         | 86       | 89        | 87        | -2                  |
| Image chorma keyed recolor+OPA     | 89       | 77        | 85        | 8                   |
| Image indexed recolor              | 68       | 65        | 59        | -6                  |
| Image indexed recolor+OPA          | 57       | 56        | 54        | -2                  |
| Image RGB rotate                   | 35       | 80        | 80        | 0                   |
| Image RGB rotate+OPA               | 35       | 61        | 62        | 1                   |
| Image RGB rotate anti aliased      | 17       | 35        | 35        | 0                   |
| Image RGB rotate anti aliased+OPA  | 17       | 35        | 35        | 0                   |
| Image ARGB rotate                  | 35       | 72        | 76        | 4                   |
| Image ARGB rotate+OPA              | 35       | 63        | 62        | -1                  |
| Image ARGB rotate anti aliased     | 17       | 35        | 35        | 0                   |
| Image ARGB rotate anti aliased+OPA | 17       | 35        | 35        | 0                   |
| Image RGB zoom                     | 35       | 82        | 82        | 0                   |
| Image RGB zoom+OPA                 | 35       | 64        | 64        | 0                   |
| Image RGB zoom anti aliased        | 17       | 35        | 35        | 0                   |
| Image RGB zoom anti aliased+OPA    | 17       | 35        | 35        | 0                   |
| Image ARGB zoom                    | 35       | 77        | 81        | 4                   |
| Image ARGB zoom+OPA                | 35       | 75        | 74        | -1                  |
| Image ARGB zoom anti aliased       | 17       | 35        | 35        | 0                   |
| Image ARGB zoom anti aliased+OPA   | 17       | 35        | 35        | 0                   |
| Text small                         | 37       | 36        | 36        | 0                   |
| Text small+OPA                     | 36       | 36        | 36        | 0                   |
| Text medium                        | 36       | 36        | 36        | 0                   |
| Text medium+OPA                    | 36       | 36        | 36        | 0                   |
| Text large                         | 36       | 36        | 36        | 0                   |
| Text large+OPA                     | 36       | 36        | 36        | 0                   |
| Text small compressed              | 44       | 42        | 43        | 1                   |
| Text small compressed+OPA          | 41       | 43        | 43        | 0                   |
| Text medium compressed             | 44       | 44        | 42        | -2                  |
| Text medium compressed+OPA         | 43       | 43        | 44        | 1                   |
| Text large compressed              | 52       | 52        | 47        | -5                  |
| Text large compressed+OPA          | 46       | 52        | 52        | 0                   |
| Line                               | 80       | 81        | 80        | -1                  |
| Line+OPA                           | 85       | 80        | 80        | 0                   |
| Arc think                          | 81       | 76        | 78        | 2                   |
| Arc think+OPA                      | 81       | 75        | 73        | -2                  |
| Arc thick                          | 78       | 80        | 74        | -6                  |
| Arc thick+OPA                      | 77       | 78        | 86        | 8                   |
| Substr. rectangle                  | 84       | 44        | 53        | 9                   |
| Substr. rectangle+OPA              | 82       | 38        | 41        | 3                   |
| Substr. border                     | 79       | 56        | 56        | 0                   |
| Substr. border+OPA                 | 85       | 52        | 57        | 5                   |
| Substr. shadow                     | 36       | 25        | 25        | 0                   |
| Substr. shadow+OPA                 | 37       | 25        | 26        | 1                   |
| Substr. image                      | 87       | 67        | 63        | -4                  |
| Substr. image+OPA                  | 96       | 64        | 70        | 6                   |
| Substr. line                       | 79       | 62        | 64        | 2                   |
| Substr. line+OPA                   | 80       | 67        | 64        | -3                  |
| Substr. arc                        | 82       | 81        | 80        | -1                  |
| Substr. arc+OPA                    | 82       | 76        | 81        | 5                   |
| Substr. text                       | 36       | 27        | 25        | -2                  |
| Substr. text+OPA                   | 36       | 25        | 27        | 2                   |

Maybe a little bit better. But some test are really noise I think - I don't know why.

**Comment by kisvegabor** [comment]
I saw double FPS on my end. You make more precise measurements if you disable refreshing the display. Just have only a `lv_disp_flush_ready()` in your `flush_cb`. this way we can test only the rendering performance.
