### ISSUE TITLE
[Fix] fragment cannot reuse all the memory

### ISSUE THREAD

**Issue by FreeFO** [kisvegabor/lvgl#3438]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I run the examples/others/fragment/lv_example_fragment_2, click the "Push" button and then click the "Pop" button. Then memory usage increased about 80-120Bytes. I want to know where increased the memory and how can i avoid it.
English is not my native language; please excuse typing errors.

### To Reproduce

Run lv_example_fragment_2 in [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html) can reproduce.

### Screenshots or video

https://user-images.githubusercontent.com/26663669/176855837-7f00eda5-e790-4904-b262-725943c2062c.mp4

**Comment by kisvegabor** [comment]
I cc @mariotaku, who is the author of this feature.

**Comment by mariotaku** [comment]
Thanks for the info. I'll run ASAN to check.

**Comment by mariotaku** [comment]
@FreeFO @kisvegabor The issue has been fixed.

**Comment by FreeFO** [comment]
> @FreeFO @kisvegabor 问题已修复。

Thanks.

**Comment by FreeFO** [comment]
@mariotaku has been fixed.
