### ISSUE TITLE
arc: display abnormal in mode SYMMETRICAL

### ISSUE THREAD

**Issue by ting-liu** [kisvegabor/lvgl#3465]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
arc: display abnormal in mode SYMMETRICAL, if setting arc_rounded to false for part 'indicator'

### To Reproduce

Using online Simulator: https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html
```python
import display_driver
import lvgl as lv

scr = lv.obj()
lv.scr_load(scr)

arc = lv.arc(lv.scr_act())
arc.set_start_angle(0)
arc.set_end_angle(200)
arc.set_mode(lv.arc.MODE.SYMMETRICAL)
arc.set_size(150, 150)
arc.center()
arc.set_style_arc_rounded(False, lv.PART.INDICATOR | lv.STATE.DEFAULT)

```

### Screenshots or video
![arc](https://user-images.githubusercontent.com/20961645/177960983-90d52a24-37d0-409f-9932-49777b1fc4b2.jpg)

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it.
