### ISSUE TITLE
Missing LV_STYLE_CONST_FLEX_*

### ISSUE THREAD

**Issue by geert-KLA-BE** [kisvegabor/lvgl#3481]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The const style defines for the flex layout are missing and should be added. 
I believe also those from the grid layout are missing

### Expected behavior

Add the flex const style defines:

```
#define LV_STYLE_CONST_FLEX_FLOW(val) \
{ \
    .prop = LV_STYLE_FLEX_FLOW, .value = { .num = (int32_t)val } \
}

#define LV_STYLE_CONST_FLEX_MAIN_PLACE(val) \
{ \
    .prop = LV_STYLE_FLEX_MAIN_PLACE, .value = { .num = (int32_t)val } \
}

#define LV_STYLE_CONST_FLEX_TRACK_PLACE(val) \
{ \
    .prop = LV_STYLE_FLEX_TRACK_PLACE, .value = { .num = (int32_t)val } \
}

#define LV_STYLE_CONST_FLEX_CROSS_PLACE(val) \
{ \
    .prop = LV_STYLE_FLEX_CROSS_PLACE, .value = { .num = (int32_t)val } \
}

#define LV_STYLE_CONST_FLEX_GROW(val) \
{ \
    .prop = LV_STYLE_FLEX_GROW, .value = { .num = (int32_t)val } \
}
```

**Comment by kisvegabor** [comment]
It's true. The other properties are "core style properties" and the const versions are generated by a script. However flexbox and grid are optional  extensions (i.e. not core properties) so the cost properties are not generated along with other properties. 

I think the best we can do is adding  them manually. Could you send a Pull request?

**Comment by geert-KLA-BE** [comment]
Hi I won't have time to do that before my vacation.
There is another issue though after adding them manually is that LV_LAYOUT_FLEX, LV_FLEX_FLOW_ROW, etc are initialized in the module. So it doesn't work when I make the style a constant at compile time.

Shouldn't those values be something constant at compile time?

```
uint32_t LV_LAYOUT_FLEX;
lv_style_prop_t LV_STYLE_FLEX_FLOW;
lv_style_prop_t LV_STYLE_FLEX_MAIN_PLACE;
lv_style_prop_t LV_STYLE_FLEX_CROSS_PLACE;
lv_style_prop_t LV_STYLE_FLEX_TRACK_PLACE;
lv_style_prop_t LV_STYLE_FLEX_GROW;

void lv_flex_init(void)
{
    LV_LAYOUT_FLEX = lv_layout_register(flex_update, NULL);

    LV_STYLE_FLEX_FLOW = lv_style_register_prop();
    LV_STYLE_FLEX_MAIN_PLACE = lv_style_register_prop() | LV_STYLE_PROP_LAYOUT_REFR;
    LV_STYLE_FLEX_CROSS_PLACE = lv_style_register_prop() | LV_STYLE_PROP_LAYOUT_REFR;
    LV_STYLE_FLEX_TRACK_PLACE = lv_style_register_prop() | LV_STYLE_PROP_LAYOUT_REFR;
}
```

**Comment by kisvegabor** [comment]
Uh, it's really a problem. The ID of the non-core properties are registered dynamically to make extra modules really modular. 

The only thing I can imagine is storing a pointer in these const styles to e.g. `LV_STYLE_FLEX_MAIN_PLACE`. If the pointer is not NULL use it, else check the normal value. But it adds +4 byte to each const property. It's 8 byte now so it mean +50%. 

@embeddedt Do you have any ideas?

**Comment by embeddedt** [comment]
What if we *only* stored a pointer to the property ID, and stopped storing the property ID?

**Comment by kisvegabor** [comment]
Does it mean we need to have an array in flash just the point the pointers there? (128 x 2 extra bytes, not the end of the world)

**Comment by embeddedt** [comment]
Yes. I figure the 256 bytes of flash isn't very much nowadays, and it's a clean way of allowing the ID to still be dynamic.

**Comment by kisvegabor** [comment]
Okay, let's go for it. Are you  or @geert-KLA-BE interested in adding it?

**Comment by embeddedt** [comment]
I've added it locally, but it seems that the tests are broken after https://github.com/lvgl/lvgl/pull/3501, so it's not ready to be pushed yet.

**Comment by kisvegabor** [comment]
I've just fixed a the C unit tests.

**Comment by geert-KLA-BE** [comment]
Just back from vacation. Will this change allow me to use it as a const property at compile time?
Also I am wondering why is it truly run time modular and not compile time modular? Is there a use case for this?

**Comment by kisvegabor** [comment]
@geert-KLA-BE 
With @embeddedt's update this should work for layouts:
```c

#define LV_STYLE_CONST_FLEX_FLOW(val) \
    { \
        .prop_ptr = &LV_STYLE_FLEX_FLOW, .value = { .num = (lv_flex_flow_t)val } \
    }
```

Please confirm if manually adding this works well on your end too. If so I'll add the grid and flex properties manually. 

@embeddedt 
I tried merging flex and grip properties to core style properties to auto generate these too but resulted in a odd dependencies. E.g. flex depends on styles, but style depends on flex too to see `lv_flex_..._t`.

I left it as it is for now.

**Comment by geert-KLA-BE** [comment]
I am able to test it. Seems that it works mostly. But the main layout setting does not yet.
`LV_STYLE_CONST_LAYOUT            ( LV_LAYOUT_FLEX             )` does not work
I still need to set that with `lv_obj_set_layout( m_container, LV_LAYOUT_FLEX );`

Note that I cannot use it as constexpr only as const because of the dynamic pointers used.

**Comment by geert-KLA-BE** [comment]
I added the following to test it:

       #define LV_STYLE_CONST_FLEX_FLOW(val) \
        { \
            .prop_ptr = &LV_STYLE_FLEX_FLOW, .value = { .num = (lv_flex_flow_t)val } \
        }

        #define LV_STYLE_CONST_FLEX_MAIN_PLACE(val) \
        { \
            .prop_ptr = &LV_STYLE_FLEX_MAIN_PLACE, .value = { .num = (lv_flex_flow_t)val } \
        }

        #define LV_STYLE_CONST_FLEX_TRACK_PLACE(val) \
        { \
            .prop_ptr = &LV_STYLE_FLEX_TRACK_PLACE, .value = { .num = (lv_flex_flow_t)val } \
        }

        #define LV_STYLE_CONST_FLEX_CROSS_PLACE(val) \
        { \
            .prop_ptr = &LV_STYLE_FLEX_CROSS_PLACE, .value = { .num = (lv_flex_flow_t)val } \
        }

**Comment by kisvegabor** [comment]
`LV_LAYOUT_FLEX` is also set runtime. It seems it can be fixed in v9 with a minor API change. I've added a not the the [ROADMAP](https://github.com/lvgl/lvgl/commit/95e8358962aee5e822e1826c098003f20187d088?diff=unified#diff-0d96796e2b2a475d618f28659f8bca752e1513e54ae8741220ec7b800d3777c2R36). 

I've added the const styles to both grid and flex.

**Comment by kisvegabor** [comment]
Fixed in the `feat/multi-instance` branch.

In v9 Flex and Grid are tightly integrated in LVGL and their style properties are handled as any other style property.
