### ISSUE TITLE
lv_keyboard_set_map and ctrl_map documentation

### ISSUE THREAD

**Issue by Satnet** [kisvegabor/lvgl#3490]
### Perform all steps below and tick them with [x]
- [ X ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ X ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ X ] Update lvgl to the latest version

### Describe the bug
https://docs.lvgl.io/master/widgets/extra/keyboard.html?highlight=lv_keyboard_set_ctrl_map
The LVGL keyboard documentation is very limited. There's only one example and no example on how to do custom keyboard mappings. In the documentation it says
`You can specify a new map (layout) for the keyboard with lv_keyboard_set_map(kb, map) and lv_keyboard_set_ctrl_map(kb, ctrl_map). Learn more about the Button matrix object. Keep in mind that using following keywords will have the same effect as with the original map:`

In reality "lv_keyboard_set_ctrl_map" doesn't exist in the library. So it gets very confusing.
I would appreciate an example on how to set custom map and ctrl_map for custom keyboard mappings. I think the documentation needs another example and updated text.

**Comment by kisvegabor** [comment]
You are right about both the should-have example and the incorrect docs. 

So I've added an example and fixed the documentation.
