### ISSUE TITLE
Multiple screen questiones

### ISSUE THREAD

**Issue by anghd** [kisvegabor/lvgl#3503]

**Comment by anghd** [comment]
I'm using three screens but they share the same wifi & ble &sd card status bars on top. Three buttons will trigger screens switching . So how to switch between those screens without consuming too much RAM resources ? I have seen two solutiones: 1. hide other screens when click button; or 2. loading targeted screen by calling lv_scr_load.  Anyone knows which  is more efficient?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
