### ISSUE TITLE
how to design colorful content of lv_table?

### ISSUE THREAD

**Issue by anghd** [kisvegabor/lvgl#3507]
###I want to design a table filling the full screen, and its inner digits has different color, I'm using littlelvgl V8 version. How can I implement this?

### 
![image](https://user-images.githubusercontent.com/20429565/179875703-f2bd7037-d46d-41b5-a716-d087b60f08d3.png)

**Comment by kisvegabor** [comment]
I can't see simple built-in way to achieve it. :slightly_frowning_face: 

Maybe create "helper" columns for the different colors with hidden border. (See [here](https://docs.lvgl.io/master/examples.html#simple-table) how to modify the draw descriptor of the cells)

----

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
