### ISSUE TITLE
 ../../lv_conf.h: No such file or directory

### ISSUE THREAD

**Issue by Sarah-C** [kisvegabor/lvgl#3514]
It's back again.

I've just run the new "factory" build for Lilygo T-QT...
```

            from C:\Users\sarah\Documents\Arduino\sketches\T-QT\factory\factory.ino:5:
c:\users\sarah\documents\arduino\libraries\lvgl\src\lv_conf_internal.h:41:18: fatal error: ../../lv_conf.h: No such file or directory
#include "../../lv_conf.h" /Else assume lv_conf.h is next to the lvgl folder/
^~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by kisvegabor** [comment]
Have you done [these](https://docs.lvgl.io/master/get-started/platforms/arduino.html#configure-lvgl) steps?

**Comment by Sarah-C** [comment]
I'll get back to it this week! Thread not dead.

**Comment by met989** [comment]
it was a error in line 41 in https://github.com/lvgl/lvgl/blob/master/src/lv_conf_internal.h
repleace 
#include "../../lv_conf.h"
with
#include "../lv_conf.h"
work after configure https://docs.lvgl.io/master/get-started/platforms/arduino.html#configure-lvgl

**Comment by kisvegabor** [comment]
`#include "../../lv_conf.h"` seems correct as `lv_conf_internal.h` is in the `lvgl/src` folder. So `../../` goes to the parent folder of `lvgl` where `lv_conf.h` should be.

**Comment by dorel50** [comment]
C:\Program Files (x86)\Arduino\libraries\T-Display-S3-main\example\factory\lvgl.h:24:10: fatal error: src/misc/lv_log.h: No such file or directory
 #include "src/misc/lv_log.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Aceeasi problema !!

**Comment by suqmadiq2ama** [comment]
same problem Compilation error: src/misc/lv_log.h: No such file or directory
(If i remove file next error is not such file or directory lv_timer.h)

**Comment by DenDonnar** [comment]
I've got the same issue. Tried some couple of different lvgl versions (uning Arduino IDE and some from github)
[#include "../lv_conf.h"](c:\arduino\libraries\lvgl\src/lv_conf_internal.h:41:18: fatal error: ../lv_conf.h: No such file or directory)

**Comment by kisvegabor** [comment]
Have you copied `lv_conf.h` as described [here](https://docs.lvgl.io/8.3/get-started/platforms/arduino.html#configure-lvgl)?

**Comment by byNMI** [comment]
so, not working

**Comment by kisvegabor** [comment]
Could you share 
1. a project the we can try to compile
2.  the required steps/links to set up an environment?

**Comment by tsgouros** [comment]
I have exactly this issue. From the Arduino IDE, with the long and ungainly path shortened to XX.

> In file included from XX/libraries/lvgl/src/../src/lv_init.h:17,
>                  from XX/libraries/lvgl/src/../lvgl.h:24,
>                  from XX/libraries/lvgl/src/lvgl.h:16,
>                  from XX/Teensy_40_NMEA2000_depth_and_temperature_480x320_LCD.ino:6:
> XX/libraries/lvgl/src/../src/lv_conf_internal.h:59:18: fatal error: ../../lv_conf.h: No such file or directory
>    59 |         #include "../../lv_conf.h"                /*Else assume lv_conf.h is next to the lvgl folder*/
>       |                  ^~~~~~~~~~~~~~~~~
> compilation terminated.
> exit status 1

I believe that lv_conf.h is exactly where it is supposed to be, NEXT TO the lvgl folder, with the "#if 0" changed to "#if 1". If I open lv_conf_internal.h in an editor and then look for ../../lv_conf.h, my editor finds it no problem. A tar of the code I'm using: https://sgouros.com/lvgl-sample.tgz. Any suggestions welcome, thank you.

**Comment by danserrano23** [comment]
Any solution now?

**Comment by Qianxunha** [comment]
cp lv_conf_template.h  lv_conf.h 

vi src/lv_conf_internal.h   

- -#include "../../lv_conf.h"
- +#include "./../lv_conf.h"

<img width="1027" height="329" alt="Image" src="https://github.com/user-attachments/assets/95c3a2c2-0dc3-46d5-9a67-40bdee56dbd1" />
