### ISSUE TITLE
Wrong lv_spinbox_set_cursor_pos function

### ISSUE THREAD

**Issue by MYaqoobEmbedded** [kisvegabor/lvgl#3516]
https://github.com/lvgl/lvgl/blob/284834e79974406583ff3631e2ea003cb11c7377/src/extra/widgets/spinbox/lv_spinbox.c#L166
There should not be a multiply by spinbox->step. Otherwise this function will shift X digits from current cursor not from 0.

**Comment by kisvegabor** [comment]
Thanks, I've fixed it as you suggested.

**Comment by MYaqoobEmbedded** [comment]
Keep up the good work Gabor!
