### ISSUE TITLE
Chinese symbol "。" in label string compiled fail

### ISSUE THREAD

**Issue by mifarelight** [kisvegabor/lvgl#3518]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

/examples/widgets/label/lv_example_label_3.c compile fail

### To Reproduce

I'm using MDK-ARM Professional Version Development environment(Armcc.exe V5.06 update 1 (build 6 1)).
During the compilation process, "lv_example_label_3.c" reports an error "..\Lib\LVGL\examples\widgets\label\lv_example_label_3.c(25): error:  #8: missing closing quote". When I remove the symbol "。" at the end of the line ""...计算性能的计算机系统。");", the compilation passes. Should this be a problem with the MDK Development environment or with the code?

**Comment by mysterywolf** [comment]
Keil5 MDK确实有时候对汉语（或者说其他语种）支持不是很好，因为汉字占了两个字符长度，所以有时候MDK会报错，但是这个不是LVGL源码的问题。而且在使用MDK的时候，如果.c文件有汉语字符串的话，还要注意你的.c文件是UTF-8格式还是GB2312格式。
