### ISSUE TITLE
SPI_HOST_MAX, LV_VER_RES_MAX and LV_HOR_RES_MAX not defined!

### ISSUE THREAD

**Issue by mohammadjavadpirhadi** [kisvegabor/lvgl#3521]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Hello,
I'm using lvgl v8.3.1 and the master branch of lvgl_esp32_drivers, but during the build, I get these errors:

../components/lvgl_esp32_drivers/lvgl_helpers.c:157:28: error: 'SPI_HOST_MAX' undeclared (first use in this function);
../components/lvgl_esp32_drivers/lvgl_helpers.c:157:28: error: 'LV_VER_RES_MAX' undeclared (first use in this function);
../components/lvgl_esp32_drivers/lvgl_helpers.c:157:28: error: 'LV_HOR_RES_MAX' undeclared (first use in this function);

I think it's because of lvgl update. Manually add these configs in lvgl_helpers.h solves the issue.

Related issue on lvgl_esp32_drivers: https://github.com/lvgl/lvgl_esp32_drivers/issues/202

### To Reproduce
Add lvgl v8.3.1 and lvgl_esp32_drivers master branch to IDF components and build it.

### Expected behavior
Build successfully!

### Screenshots or video
No screenshots or video!

**Comment by kisvegabor** [comment]
It's because the ESP related repos are still not updated to LVGL v8. 

As it's not related too the core lvgl, I close this issue. It should be discussed in https://github.com/lvgl/lvgl_esp32_drivers/issues/202
