### ISSUE TITLE
How load picture of wink.png  in Visual Studio Project

### ISSUE THREAD

**Issue by maotouying** [kisvegabor/lvgl#3527]
I want to load a PNG image on my PC to LVGL,So I use the example of png，But the picture can't load success.
Whether the file system needs to be configured？
![image](https://user-images.githubusercontent.com/16067208/181505424-d3cc861b-40f4-4526-9cb7-09c3906b89ee.png)
![image](https://user-images.githubusercontent.com/16067208/181505517-4be89608-7b7e-4993-9640-3db679de3a19.png)

**Comment by PGNetHun** [comment]
Hello,
Try to register the FS driver, and then load the image from that virtual FS drive.

See:  
Image loading: https://docs.lvgl.io/master/widgets/img.html#image-source
> > You also need to use LVGL's file system module and register a driver with some functions for the basic file operation.

FS:  https://docs.lvgl.io/master/overview/file-system.html

So, in the end:
`lv_img_set_src(img, "A:path_to_img/wink.png")`

(`A` is the LVGL's virtual FS drive letter)

Please let us know whether it worked.
(I use MicroPython-LVGL this way both on Unix and ESP32 device, and loading image works from LVGL's virtual FS driver)

**Comment by maotouying** [comment]
Thanks for your answer，After use the LVGL's virtual FS，it can load the picture from my PC to LVGL.
![image](https://user-images.githubusercontent.com/16067208/181871036-6f319bce-ea34-406e-bdbe-136bb0b71b46.png)
