### ISSUE TITLE
Why LV_DEF_REFR_PERIOD is fixed

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#3530]
### Introduce the problem
I notice that since  https://github.com/lvgl/lvgl/commit/5369d7d473446a8953f2ea37b9116da918d3c8d2 macro `LV_DISP_DEF_REFR_PERIOD` has been renamed to `LV_DEF_REFR_PERIOD`. It is OK.

Why does the macro `LV_DEF_REFR_PERIOD` have a fixed value 33 rather than configurable? 

https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/hal/lv_hal_disp.h#L39

**Comment by kisvegabor** [comment]
I was trying to reduce the number of config options  in `lv_conf.h` and removed some which can be run-time configured anyway and LVGL only needs a default value. 

It's not documented yet and might be worth a dedicated API function but you can adjust the period time like this:
```c
  lv_timer_set_period(disp->refr_timer, 10);
```

**Comment by GorgonMeducer** [comment]
OK, as long as there is a method, no problem.

**Comment by brightproject** [comment]
Sorry @kisvegabor , I encountered the need to increase `FPS`.

`My platformio.ini`

> build_flags = 
>   ; Don't use lv_conf.h. Tweak params via platfom.ini.
>   -D LV_CONF_SKIP
>   -D LV_CONF_INCLUDE_SIMPLE
>   ; Enable LVGL monitoring
>   -D LV_USE_SYSMON=1
>   -D LV_USE_MEM_MONITOR=1
>   -D LV_USE_PERF_MONITOR=1
>   -D LV_DEF_REFR_PERIOD=20

The flag has no effect on the system.

Where should I put this function?

> lv_timer_set_period(disp->refr_timer, 10);

LVGL simulator

https://github.com/user-attachments/assets/61ff531f-655b-480a-8b54-fb606ea11a59

Real hardware https://aliexpress.ru/item/1005006335587633.html

https://github.com/user-attachments/assets/fdd89819-b427-4456-8757-659c2f5468e3

**Comment by GorgonMeducer** [comment]
I think your FPS is not limited by the `LV_DEF_REFR_PERIOD` but the device's 2D capability.
It is better to create a dedicated issue for the problem you encountered. 
And please provide more details in the issue:

- Processor and Processor Frequency
- Resolution
- Colour Depth?
- Any GPU?
- Any Acceleration?

**Comment by brightproject** [comment]
> I think your FPS is not limited by the `LV_DEF_REFR_PERIOD` but the device's 2D capability.

You are absolutely right, my device is not powerful enough, it is not a PC and not a graphics accelerator.
I use a device with `esp32s3` and a display connected via `RGB` bus.
The processor frequency is `240 MHz` and the SDRAM is only `512 KB`.
The library for graphics is

> Arduino_GFX_Library

However, the question in this issue was about changing the `LV_DEF_REFR_PERIOD` parameter and it seems that this does not work via `platformio.ini`🙂
