### ISSUE TITLE
how to deal with buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1] when the data send to /dev/fb0

### ISSUE THREAD

**Issue by haidongpan** [kisvegabor/lvgl#3544]
### Introduce the problem

I saw that when LV_COLOR_SCREEN_TRANSP is enable, there is a opa value in buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1]  no matter the LV_COLOR_DEPTH value is, So i want to know how to deal with buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1] when the data send to /dev/fb0,  for example there just 2 byte length in a pix when LV_COLOR_DEPTH is 16, and LV_IMG_PX_SIZE_ALPHA_BYTE  is 3 at the time, so the third byte is the 
opa value, but in the standard display driver just care about 2 byte length when LV_COLOR_DEPTH  is 16, the doubt is that data buffer every opa in buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1]  is already take up the space in data buffer， how does the /dev/fb0 deal with the 
buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1] , in my opinion, the display driver of /dev/fb0 just deal with the data buffer 2 bytes after 2 bytes, and it does know there is a opa value after every two 2 bytes length, I can not found the answer in source code, so i need help
### Examples and cases
I saw the buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1] is set in this function

static inline void set_px_argb(uint8_t * buf, lv_color_t color, lv_opa_t opa)
{
        lv_color_t bg_color;
        lv_color_t res_color;
        lv_opa_t bg_opa = buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1];
#if LV_COLOR_DEPTH == 8
        bg_color.full = buf[0];
        lv_color_mix_with_alpha(bg_color, bg_opa, color, opa, &res_color, &buf[1]);
        if(buf[1] <= LV_OPA_MIN) return;
        buf[0] = res_color.full;
#elif LV_COLOR_DEPTH == 16
        bg_color.full = buf[0] + (buf[1] << 8);
        lv_color_mix_with_alpha(bg_color, bg_opa, color, opa, &res_color, &buf[2]);
        if(buf[2] <= LV_OPA_MIN) return;
        buf[0] = res_color.full & 0xff;
        buf[1] = res_color.full >> 8;
#elif LV_COLOR_DEPTH == 32
        bg_color = *((lv_color_t *)buf);
        lv_color_mix_with_alpha(bg_color, bg_opa, color, opa, &res_color, &buf[3]);
        if(buf[3] <= LV_OPA_MIN) return;
        buf[0] = res_color.ch.blue;
        buf[1] = res_color.ch.green;
        buf[2] = res_color.ch.red;
#endif
}

### Suggested solution

i do not know how lvgl deal with buf[LV_IMG_PX_SIZE_ALPHA_BYTE - 1] when the data send to /dev/fb0

**Comment by kisvegabor** [comment]
Since v8.3 `LV_COLOR_SCREEN_TRANSP` only enables some extra render functions to handle blending to non fully covering background.  To actually produce ARGB you need to set `disp_drv->screen_transp = 1`. 

It can be mostly used with ARGB8888 color format. ARGB8565  (16bit + alpha) is not a standard format and probably /dev/fb cannot handle it.
