### ISSUE TITLE
rotated canvas is cropped

### ISSUE THREAD

**Issue by rabbitsaviola** [kisvegabor/lvgl#3545]
Hi,
  I use canvas.transform to rotate a canvas and render it on another. It seems the rotated image is cropped. 

This is the result without rotation.
![image](https://user-images.githubusercontent.com/26240242/182854503-615ac12b-2b8b-43f9-98bd-bf376fe1805e.png)

This is the result with 10 degree rotation.
![image](https://user-images.githubusercontent.com/26240242/182854520-48622570-6f61-41fa-b33b-6200db5b6b7a.png)

It can be seen the text outside the source region is cropped although it's still in the target region. I use LVGL v8. The old v7 doesn't have this issue. Does it work as design for v8?

Following is my test code

```python
_CANVAS_WIDTH = 200
_CANVAS_HEIGHT = 150
LV_IMG_ZOOM_NONE = 256

label_dsc = lv.draw_label_dsc_t()
label_dsc.init()
label_dsc.color = lv.palette_main(lv.PALETTE.RED)

cbuf = bytearray(_CANVAS_WIDTH * _CANVAS_HEIGHT * 4)

canvas = lv.canvas(lv.scr_act())
canvas.set_buffer(cbuf, _CANVAS_WIDTH, _CANVAS_HEIGHT, lv.img.CF.TRUE_COLOR)
canvas.center()
canvas.fill_bg(lv.palette_lighten(lv.PALETTE.GREY, 3), lv.OPA.COVER)

canvas.draw_text(0, 0, 100, label_dsc, "Some text on text canvas")

# Test the rotation. It requires another buffer where the original image is stored.
# So copy the current image to buffer and rotate it to the canvas

img = lv.img_dsc_t()
img.data = cbuf[:]
img.header.cf = lv.img.CF.TRUE_COLOR
img.header.w = _CANVAS_WIDTH
img.header.h = _CANVAS_HEIGHT

canvas.fill_bg(lv.palette_lighten(lv.PALETTE.BLUE, 3), lv.OPA.COVER)
canvas.transform(img, 100, LV_IMG_ZOOM_NONE, 70, 60, 0, 0, True)
```

**Comment by kisvegabor** [comment]
Hi,

Thanks for reporting this problem. I've pushed a fix.
