### ISSUE TITLE
lv_img_buf_set_palette() incompatible with image converter output

### ISSUE THREAD

**Issue by brett-dalton** [kisvegabor/lvgl#3547]
### Introduce the problem
I encountered this yesterday while trying to implement a color scheme system for some palettized image resources. It appears that lv_img_buf_set_palette() is provided for this purpose, but perhaps not for built-in images. The function tries to write to the palette, which is part of the image array, which is declared const. So, it seems I either have to make the whole image non-const, or allocate a redundant copy of it. Neither option is ideal, since the descriptor's contents should remain unchanged between instantiations, the image is fairly large, and I'm only changing a few values in the palette.

### Examples and cases

Call lv_img_buf_set_palette() on any image generated by the converter:
```
lv_img_dsc_t src = generated_img_src;
lv_obj_t* img = lv_img_create(parent);
lv_img_set_src(img, &src);
lv_img_buf_set_palette(&src, 0, lv_color_make(128, 0, 0));
```
The descriptor is declared const, so at least there is protection.
Of course, you can copy the descriptor, and obviously this will just crash.

### Suggested solution
I had expected an interface like: lv_img_set_palette(lv_obj_t *img, lv_color_t *palette)
(Something like this would allow for palette re-use, which would also be a nice feature.)

I first looked into adding a separated palette to the descriptor, but it looks like lots of code relies on the palette and the image being combined. However, I saw that the image decoder already allocates a copy of the palette, so I thought I could use that. Before making my own decoder, I added lv_img_decoder_set_palette() to the built-in decoder. This worked, but now I see it is has a problem: it requires caching to be enabled, otherwise the original palette data is reloaded every draw. 
This implementation works for me, but it would lead to unpredictable behavior if someone loaded lots of images. 

Anyway, there doesn't seem to be an obvious way to do this without modifying LVGL, so I figured it's worth drawing to your attention.

**Comment by kisvegabor** [comment]
Yes, it's not for "converted images" but for cases when you handcraft an image. Anyway, I agree that it'd be nice feature.

Now I'm thinking about how to rework the color formats supported by LVGL to be more conscious and index formats caused me some headache. Separating the palette and an image seems like an interesting idea that I haven't considered so far. 

I'll write here if there some updates on this topic.
