### ISSUE TITLE
How to customize the animation parameters of label scrolling?

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#3561]
### Introduce the problem

When label sets long mode to LV_LABEL_LONG_SCROLL or LV_LABEL_LONG_SCROLL_CIRCULAR, I want to modify its animation parameters (for example: repeat_count/playback_delay/repeat_delay/ready_cb, etc.), how to do it?
### Suggested solution

At present, the speed of the animation is obtained using lv_obj_get_style_anim_speed(), and the animation is also obtained using lv_obj_get_style_anim(), and then a few specific parameters are replaced. However, it always feels that these two methods are not perfect, and all customization of animation has not been realized. I haven't thought of a better way yet.

**Comment by kisvegabor** [comment]
Hi,

You can take a look at this example: https://docs.lvgl.io/master/examples.html#customize-circular-scrolling-animation

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by qinshijing** [comment]
hi, i run the example, but can't set repeat_count and ready_cb, right?

**Comment by qinshijing** [comment]
![image](https://user-images.githubusercontent.com/51692568/184637589-67069390-6b0a-4758-8ed3-5987e48761a0.png)
Only act_time and repeat_delay are provided here, so should we add other parameters of anim?

**Comment by kisvegabor** [comment]
Ah, true. I see no problem with using more parameters after `if(anim_template)`. Which properties do you find useful?

**Comment by qinshijing** [comment]
hi. I send a pull requests. Do you think this change is reasonable?

**Comment by kisvegabor** [comment]
Yes, I think it's reasonable. Once the animation can be customized, lets make it really customizable.
