### ISSUE TITLE
I can't clean the obj and renew the new one(v7)

### ISSUE THREAD

**Issue by TingRui608470158** [kisvegabor/lvgl#3562]
### 
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
 I want to clean the previous obj in screen，but i can just show nothing or show  a lot of overlapping obj

### To Reproduce

this function will called continuous
```
static void task_objectDet_cb(lv_task_t* task)
{ 	
	lv_style_init(&style);
	lv_style_set_bg_opa(&style, LV_STATE_DEFAULT, LV_OPA_0);
	lv_style_set_bg_color(&style, LV_STATE_DEFAULT, LV_COLOR_SILVER);
	lv_style_set_bg_grad_color(&style, LV_STATE_DEFAULT, LV_COLOR_BLUE);
	lv_style_set_bg_grad_dir(&style, LV_STATE_DEFAULT, LV_GRAD_DIR_VER);
	lv_obj_t * obj = lv_obj_create(lv_scr_act(), NULL);
	lv_obj_add_style(obj, LV_OBJ_PART_MAIN, &style);
	lv_obj_set_size(obj,100,100);
	x_axis++;
	lv_obj_align(obj, NULL, LV_ALIGN_IN_TOP_LEFT, 100+(x_axis), 50);
	if(hidden_obj)
	{
		lv_obj_del(obj);
		hidden_obj = false;
	}else{
		hidden_obj = true;
	}
}
```

### Expected behavior

i want to show a rect,and clean it,and make a new one

### Screenshots or video

[video](https://drive.google.com/file/d/1UOeHQNyiV-55b1K5_hgnrbIXW0IhAVcs/view?usp=sharing)

**Comment by kisvegabor** [comment]
It looks strange because if `hidden_obj == true` you immediately delete the object you just created.

I'm not sure I fully understand what your goal is. If you just wan't to move the rectangle, just create it once, save it in a global variable and call `lv_obj_align(obj, NULL, LV_ALIGN_IN_TOP_LEFT, 100+(x_axis), 50);`

If you want to hide it periodically use `lv_obj_add/clear_flag(obj, LV_OBJ_FLAG_FIDDEN)`

**Comment by TingRui608470158** [comment]
Sorry, please ignore ` hidden_obj == true` part .
I want to show a dynamic rect，but `lv_obj_clean` , `lv_obj_del_async` , `lv_obj_del ` all not working.

**Comment by kisvegabor** [comment]
What do you mean by dynamic?

**Comment by TingRui608470158** [comment]
a moving object

**Comment by kisvegabor** [comment]
You can simply save `obj` as a global variable and call `lv_obj_set_x(obj, x)` without recreating the object.

**Comment by TingRui608470158** [comment]
```
static lv_obj_t * obj_display;
static void task_objectDet_cb(lv_task_t* task)
{ 
        lv_style_init(&style);
	lv_style_set_bg_opa(&style, LV_STATE_DEFAULT, LV_OPA_0);
	lv_style_set_bg_color(&style, LV_STATE_DEFAULT, LV_COLOR_SILVER);
	lv_style_set_bg_grad_color(&style, LV_STATE_DEFAULT, LV_COLOR_BLUE);
	lv_style_set_bg_grad_dir(&style, LV_STATE_DEFAULT, LV_GRAD_DIR_VER);
	obj_display = lv_obj_create(lv_scr_act(), NULL);
	lv_obj_add_style(obj_display, LV_OBJ_PART_MAIN, &style);
	lv_obj_set_size(obj_display,100,100);
	x_axis++;
	lv_obj_align(obj_display, NULL, LV_ALIGN_IN_TOP_LEFT, 100+(x_axis), 50);
}
```

It still not work

**Comment by kisvegabor** [comment]
Call this only once
```c
        lv_style_init(&style);
	lv_style_set_bg_opa(&style, LV_STATE_DEFAULT, LV_OPA_0);
	lv_style_set_bg_color(&style, LV_STATE_DEFAULT, LV_COLOR_SILVER);
	lv_style_set_bg_grad_color(&style, LV_STATE_DEFAULT, LV_COLOR_BLUE);
	lv_style_set_bg_grad_dir(&style, LV_STATE_DEFAULT, LV_GRAD_DIR_VER);
	obj_display = lv_obj_create(lv_scr_act(), NULL);
	lv_obj_add_style(obj_display, LV_OBJ_PART_MAIN, &style);
	lv_obj_set_size(obj_display,100,100);
```

And the task:
```c
static lv_obj_t * obj_display;
static void task_objectDet_cb(lv_task_t* task)
{ 
	x_axis++;
	lv_obj_align(obj_display, NULL, LV_ALIGN_IN_TOP_LEFT, 100+(x_axis), 50);
}
```

**Comment by TingRui608470158** [comment]
It work !!!
Thanks you so much~~
