### ISSUE TITLE
roller not stopping at the correct position

### ISSUE THREAD

**Issue by vijaydhiman** [kisvegabor/lvgl#3570]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by embeddedt** [comment]
Try enabling `LV_USE_LARGE_COORD`.

**Comment by vijaydhiman** [comment]
thanks for replying
will try this.
