### ISSUE TITLE
No examples in the docs

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#3571]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The example section of the widgets is empty:
![image](https://user-images.githubusercontent.com/7599318/184611108-fb435046-c942-4a63-b3d9-1217dacf571f.png)

Interestingly the examples here are working: https://docs.lvgl.io/master/examples.html#customize-circular-scrolling-animation

It might be related that v8.3 is missing from the version list:
![Untitled](https://user-images.githubusercontent.com/7599318/184611349-2e3b9af8-0c47-40c0-bedc-6a9246d0d946.png)

@embeddedt, could you take a look?

**Comment by embeddedt** [comment]
Fixed. The include paths for the examples' RST files just needed to be updated.

As an aside, the link you gave me crashes Chromium 104 with an "Aw, snap!" error. It does work in Firefox, so I suspect it's a Chromium bug that will be fixed eventually.

**Comment by kisvegabor** [comment]
Ah, thank you.

> As an aside, the link you gave me crashes Chromium 104 with an "Aw, snap!" error. It does work in Firefox, so I suspect it's a Chromium bug that will be fixed eventually.

It works for me in Brave, Chrome and Firefox too. Probably just a temporary bug.
