### ISSUE TITLE
Rename `lv_label_set_text_sel_start` and `lv_label_set_text_sel_end` to match getters

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#3573]
### Introduce the problem
Label text selection interfaces does not follow the same naming convention, setters are different than getters.

### Examples and cases
Setters: `lv_label_set_text_sel_start` and `lv_label_set_text_sel_end`
Getters: `lv_label_get_text_selection_start` and `lv_label_get_text_selection_end`

### Suggested solution
Rename `lv_label_set_text_sel_start` and `lv_label_set_text_sel_end` to `lv_label_set_text_selection_start` and `lv_label_set_text_selection_end`

**Comment by C47D** [comment]
Against which branch should I send the fix?

**Comment by embeddedt** [comment]
`master`, please. 8.3 is only accepting bugfixes now.
