### ISSUE TITLE
The non-default group adding an object will result in a memory leak.

### ISSUE THREAD

**Issue by hellototoro** [kisvegabor/lvgl#3593]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

To create a new group and add some new objects, then deleting the group and its' all objects will lead to a memory leak.

### To Reproduce

```
void event2_handler(lv_event_t* event)
{
    lv_obj_t* target = lv_event_get_target(event);
    lv_obj_t* parent = lv_obj_get_parent(target);
    lv_group_t* group = (lv_group_t*)lv_obj_get_group(target);
    lv_group_remove_all_objs(group);
    lv_group_del(group);
    lv_obj_del(parent);
}

void group_test(lv_obj_t* parent)
{
    lv_group_t* group = lv_group_create();
    lv_obj_t* panel = lv_obj_create(parent);
    lv_obj_set_size(panel, 500, 600);
    lv_obj_set_align(panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(panel, LV_FLEX_FLOW_COLUMN);

    lv_obj_t* ui_BTN = lv_btn_create(panel);
    lv_obj_set_size(ui_BTN, 50, 50);
    lv_obj_set_align(ui_BTN, LV_ALIGN_CENTER);
    lv_group_add_obj(group, ui_BTN);
    lv_obj_add_event_cb(ui_BTN, event2_handler, LV_EVENT_CLICKED, NULL);

    for (int i = 0; i < 10; i++) {
        ui_BTN = lv_btn_create(panel);
        lv_obj_set_size(ui_BTN, 100, 50);
        lv_obj_set_align(ui_BTN, LV_ALIGN_CENTER);
        lv_group_add_obj(group, ui_BTN);
    }
    lv_group_focus_obj(lv_obj_get_child(panel, 0));
}

void event_handler(lv_event_t* event)
{
    (void)event;
    group_test(lv_scr_act());
}

void test(void)
{
    lv_obj_t* btn = lv_btn_create(lv_scr_act());
    lv_obj_set_size(btn, 80, 50);
    lv_obj_center(btn);

    lv_group_t* defualt_group = lv_group_get_default();
    lv_group_add_obj(defualt_group, btn);
    lv_obj_add_event_cb(btn, event_handler, LV_EVENT_CLICKED, NULL);
}
```
### Screenshots or video

<img width="810" alt="微信截图_20220818223956" src="https://user-images.githubusercontent.com/35717799/185426149-f8bde673-421f-471d-8c28-721b6df2d5fc.png">
<img width="810" alt="微信截图_20220818224016" src="https://user-images.githubusercontent.com/35717799/185426155-401be95b-0431-4cbd-b0ee-2aa6206a191d.png">
<img width="810" alt="微信截图_20220818224040" src="https://user-images.githubusercontent.com/35717799/185426160-34dc2bc6-33b8-44b9-b1a6-38bcbe92c55e.png">

**Comment by kisvegabor** [comment]
It's because `lv_group_add_obj` doesn't remove the object from its current group automatically. 

I've fixed in `master` and also cherry-picked it to `release/v8.3`
