### ISSUE TITLE
CMSIS-Pack broken links

### ISSUE THREAD

**Issue by koval-alexander** [kisvegabor/lvgl#3597]
### Introduce the problem

Links to CMSIS-Packs v1.0.3 and newer are broken, unable to download packs from Pack installer or Keil site. 
It seems that links pointing to master branch instead of 8.3 and so on.

### Suggested solution

Fix broken links and use permanent links for such things.

**Comment by kisvegabor** [comment]
cc @GorgonMeducer

**Comment by GorgonMeducer** [comment]
Will have a look

**Comment by GorgonMeducer** [comment]
@kisvegabor @koval-alexander  Double Checked, I see no problem from my side.

Pack installer works well.
<img width="825" alt="image" src="https://user-images.githubusercontent.com/13148491/186275532-405776c1-53ea-4fbc-8160-a6026fd3db17.png">

Keil site works well.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/13148491/186275770-68072710-a600-4410-84e6-b2b2b5e51ec1.png">

No link is broken.

**Comment by GorgonMeducer** [comment]
> It seems that links pointing to master branch instead of 8.3 and so on.

That's intended behaviour, no problem at all.

> Fix broken links and use permanent links for such things.
No links broken and LVGL.lvgl.pdsc does indeed use permanent links 

https://github.com/lvgl/lvgl/blob/b98ccf94f88979ddace54032b36db5f108160232/env_support/cmsis-pack/LVGL.lvgl.pdsc#L39-L90

You can try any of those URLs of the release tags in your web browser. All works.

**Comment by GorgonMeducer** [comment]
@kisvegabor please verify what I have said.

**Comment by GorgonMeducer** [comment]
@koval-alexander there are some suggestions for your MDK environment:

- try the latest MDK (current version is 5.37)
- Open Pack-installer and select menu Packs->Check for Updates

<img width="335" alt="image" src="https://user-images.githubusercontent.com/13148491/186276544-bc2c589f-3bad-4c53-8baa-bf4fe9ee3536.png">

**Comment by koval-alexander** [comment]
Hmm, it looks like the problem is really on my side, checked on another computer, everything works fine. Clearing the MDK cache seems to solve the problem.
Links on [arm site](https://developer.arm.com/tools-and-software/embedded/cmsis/cmsis-packs) are still broken, but on keil.com it's fine. It is strange that the links are not updated at the same time.
Thanks for your help, everything is working now.
