### ISSUE TITLE
Encoder long-press on one-checked-button-matrix makes selection without visually selecting button

### ISSUE THREAD

**Issue by pm-mic** [kisvegabor/lvgl#3613]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
- Input device is an encoder with a push button.
- Screen features a button-matrix with 2 buttons, and some other components
- When the focus is on the button-matrix and button 2 has been selected (PRESSED), option 2 is activated, button 2 is highlighted
- Navigate to option 1 with the encoder
- LONG PRESS in order to return focus to the screen. 
- Upon leaving the focus from the button-matrix, option 1 (last focused) is being pressed as well (because it gets selected with the PRESS of the button which is fired at the start of the LONG PRESS), hence the "selected_btn" is now option 1. 
- However, button 2 is still highlighted, and the component does not represent it's internal state, button 1 is not selected.

### To Reproduce
Using the example project **with the mousewheel as encoder option enabled**. 
This is a variation on lv_example_btnmatrix_3.c
```c
#include "../../lv_examples.h"
#if LV_USE_BTNMATRIX  && LV_BUILD_EXAMPLES

static lv_obj_t *label;

static void event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    uint32_t id = lv_btnmatrix_get_selected_btn(obj);
    bool prev = id == 0 ? true : false;
    bool next = id == 6 ? true : false;
    if(prev || next) {
        /*Find the checked button*/
        uint32_t i;
        for(i = 1; i < 7; i++) {
            if(lv_btnmatrix_has_btn_ctrl(obj, i, LV_BTNMATRIX_CTRL_CHECKED)) break;
        }

        if(prev && i > 1) i--;
        else if(next && i < 5) i++;

        lv_btnmatrix_set_btn_ctrl(obj, i, LV_BTNMATRIX_CTRL_CHECKED);
    }

    lv_label_set_text_fmt(label, "selected button is: %i", id);
}

/**
 * Make a button group (pagination)
 */
void lv_example_btnmatrix_3(void)
{
    static lv_style_t style_bg;
    lv_style_init(&style_bg);
    lv_style_set_pad_all(&style_bg, 0);
    lv_style_set_pad_gap(&style_bg, 0);
    lv_style_set_clip_corner(&style_bg, true);
    lv_style_set_radius(&style_bg, LV_RADIUS_CIRCLE);
    lv_style_set_border_width(&style_bg, 0);


    static lv_style_t style_btn;
    lv_style_init(&style_btn);
    lv_style_set_radius(&style_btn, 0);
    lv_style_set_border_width(&style_btn, 1);
    lv_style_set_border_opa(&style_btn, LV_OPA_50);
    lv_style_set_border_color(&style_btn, lv_palette_main(LV_PALETTE_GREY));
    lv_style_set_border_side(&style_btn, LV_BORDER_SIDE_INTERNAL);
    lv_style_set_radius(&style_btn, 0);

    static const char * map[] = {LV_SYMBOL_LEFT, "1", "2", "3", "4", "5", LV_SYMBOL_RIGHT, ""};

    lv_obj_t * btnm = lv_btnmatrix_create(lv_scr_act());
    lv_btnmatrix_set_map(btnm, map);
    lv_obj_add_style(btnm, &style_bg, 0);
    lv_obj_add_style(btnm, &style_btn, LV_PART_ITEMS);
    lv_obj_add_event_cb(btnm, event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_set_size(btnm, 225, 35);

    /*Allow selecting on one number at time*/
    lv_btnmatrix_set_btn_ctrl_all(btnm, LV_BTNMATRIX_CTRL_CHECKABLE);
    lv_btnmatrix_clear_btn_ctrl(btnm, 0, LV_BTNMATRIX_CTRL_CHECKABLE);
    lv_btnmatrix_clear_btn_ctrl(btnm, 6, LV_BTNMATRIX_CTRL_CHECKABLE);

    lv_btnmatrix_set_one_checked(btnm, true);
    lv_btnmatrix_set_btn_ctrl(btnm, 1, LV_BTNMATRIX_CTRL_CHECKED);

    lv_obj_center(btnm);

    // label to show the selected button
    label = lv_label_create(lv_scr_act());
    lv_obj_align(label, LV_ALIGN_CENTER, 0, 100);

    // button to allow for something else to focus on
    // besides our button matrix
    lv_obj_t *btn = lv_btn_create(lv_scr_act());
    lv_obj_align(btn, LV_ALIGN_BOTTOM_MID, 0, 0);

}

#endif
```

### Expected behavior
- I would expect the object to lose focus without selecting the current button. When the user long presses he clearly wants to exit the component and not select something. 
- Alternatively I would at least expect the component to accurately show it's internal state.

**Comment by pm-mic** [comment]
Is there anyone with any insight on this?

**Comment by kisvegabor** [comment]
Hi,

Sorry for the late reply.

The problem is that when the PRESS happens we don't know if it will be a long press or not so the press event needs to be processed.

However you can make the buttons to not react on press but on release. It worked for me:
```c
lv_btnmatrix_set_btn_ctrl_all(btnm1, LV_BTNMATRIX_CTRL_CLICK_TRIG | LV_BTNMATRIX_CTRL_NO_REPEAT);
```

**Comment by pm-mic** [comment]
Hi Gabor, 

Thank you very much for this solution. It works as expected, this provides exactly the desired behavior. 

In my opinion this is a workaround for a bug because the default behavior has undesired side-effects.
But as this is probably an edge case since it seems I'm the only one so far who has run into this, I would suggest to at least mention this in the documentation.

Regardless, I'm very thankful for this solution.

**Comment by kisvegabor** [comment]
Happy to hear it works. I've updated the docs.
