### ISSUE TITLE
Complex menu Micropython code lv_example_menu_5.py file is missing 

### ISSUE THREAD

**Issue by bx5974** [kisvegabor/lvgl#3616]
https://github.com/lvgl/lvgl/tree/master/examples/widgets/menu/lv_example_menu_5.py example file is missing 

https://docs.lvgl.io/master/widgets/menu.html#complex-menu

`Error encountered while trying to open /home/runner/work/lvgl/lvgl/examples/widgets/menu/lv_example_menu_5.py
`

**Comment by embeddedt** [comment]
Thanks! We are tracking the missing MicroPython examples in https://github.com/lvgl/lvgl/issues/3535 so I've made a note of this there.
