### ISSUE TITLE
How to update the lvgl bar progressbar percentage when my other py function is running

### ISSUE THREAD

**Issue by bx5974** [kisvegabor/lvgl#3617]
I compiled lvgl for micropython 1.19.1

How to update the lvgl bar progressbar percentage when my other py function is running

when i call my function - my function alone is running and lvgl progress bar is stuck

Could you please help with an micropython lvgl progress bar updating example

i was searching but I dont see any fitting micropython examples for this

**Comment by embeddedt** [comment]
Duplicate of https://github.com/lvgl/lv_binding_micropython/issues/231.
