### ISSUE TITLE
LodePNG: Incompatible pointer type in "decoder_open"

### ISSUE THREAD

**Issue by jacquesdmernok** [kisvegabor/lvgl#3620]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
In the simulator I can use the lodePNG lib fine, but when I port to STM32, I get incompatible pointer type errors in the decoder_open function.

### To Reproduce
Use lodePNG on STM32. (I am compiling with the GCC compiler).

```c
error = lodepng_decode32(&img_data, &png_width, &png_height, png_data, png_data_size);
```

If I cast the pointers:
```c
error = lodepng_decode32(&img_data, (unsigned*) &png_width, (unsigned*) &png_height, png_data, png_data_size);
```
the issue goes away.

### Expected behavior
Just trying to build the project with PNG enabled in lv_conf.h/

**Comment by kisvegabor** [comment]
Thanks for the report, I've pushed a fix.

**Comment by jacquesdmernok** [comment]
Thanks so much for the fix, but it seems as though there were two instances of this warning. Just a few lines up from where you implemented the fix, there is another instance.

Kind Regards,
Jacques Duminy
Junior Electronic Design Engineer
Mernok Elektronik (Pty) Ltd
tel +27 12 661 4828
fax +27 86 542 9007
***@***.******@***.***>
www.mernok.co.za<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-za.mimecast.com%2Fs%2FV7P-CRgnPlcy2DkFNi1SH%3Fdomain%3Dmernok.co.za%2F&data=05%7C01%7Chabib.c%40powermite.co.za%7Cb430d8ac6cf441d1008908da749ff627%7Cf66ea97f8cc74a2896e5539105b2cf59%7C0%7C0%7C637950527627834019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pQ0mtqwKoACG7MABw4YWbfRdFBjYyNGtvPnbW93CT24%3D&reserved=0>
***@***.***<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-za.mimecast.com%2Fs%2F-AMSCVmr7vuzGnLuyBU-w%3Fdomain%3Dtickets.tixsa.co.za&data=05%7C01%7Chabib.c%40powermite.co.za%7Cb430d8ac6cf441d1008908da749ff627%7Cf66ea97f8cc74a2896e5539105b2cf59%7C0%7C0%7C637950527627834019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZP7ACLzt%2BtPnntz73HWe8bOs30dYgzqX7jmSedJHK9I%3D&reserved=0>
***@***.***

**Comment by kisvegabor** [comment]
These seem to be fixed too:
https://github.com/lvgl/lvgl/blob/master/src/libs/png/lv_png.c#L170-L171
