### ISSUE TITLE
Lvgl SquareLine Stdio about Calendar.

### ISSUE THREAD

**Issue by Szeroy** [kisvegabor/lvgl#3647]
Does the calendar now only support 2023? My version is 8.2.0, and once it is set beyond 2023, it will go back to 1901. In the code generated with Stdio, only lv_obj_create is created in the calendar part. Therefore, lv_calendar_create should be used normally, so the calendar is not displayed.

**Comment by kisvegabor** [comment]
Hi,

Please ask SquareLine Studio related questions in [its forum](https://forum.squareline.io/). I'll will answer there.
