### ISSUE TITLE
btn: display abnormal with specific border_width

### ISSUE THREAD

**Issue by ting-liu** [kisvegabor/lvgl#3648]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
if radius is set to non-zero value and less than border_width, btn display abnormal with specific border_width value
1. border_width value 5: OK
2. border_width value 6: abnormal

### To Reproduce
Using online Simulator: https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html
```python
# Initialize 

import display_driver
import lvgl as lv

# Create a button

scr = lv.obj()
lv.scr_load(scr)

btn = lv.btn(scr)
btn.align(lv.ALIGN.CENTER, 0, 0)
btn.set_width(60)
btn.set_style_radius(1, 0)
btn.set_style_border_width(6, 0)

```

### Screenshots or video

<img width="891" alt="btn-with-radius-border-width" src="https://user-images.githubusercontent.com/20961645/188083765-e57cbd2c-5b3d-4b3f-8ffc-56383fbf870d.png">

**Comment by kisvegabor** [comment]
Thanks for the report, I fixed it.
