### ISSUE TITLE
Transparent round cap lines have wrong opacity values

### ISSUE THREAD

**Issue by StefanBabatie** [kisvegabor/lvgl#3651]
### Perform all steps below and tick them with [x]
- [ x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x ] Update lvgl to the latest version
- [ x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When drawing a transparent round capped line, the intersection between the circles drawn at the ends and the rectangle that constitutes the line has a darker tone because of the blending, instead of having the same tone as the rest of the line and circles. This ocurs on the up to date master branch, and it has been reproduced both on the simulator and a board itself.

### To Reproduce
Create a thick, blue, round ended line with a 20% opacity value.
```c
  /*Create an array for the points of the lines*/
  static lv_point_t line_points[] = { {5, 100}, {240, 100} };

  /*Create style for the lines*/
  static lv_style_t style_line;
  lv_style_init(&style_line);
  lv_style_set_line_width(&style_line, 20);
  lv_style_set_line_color(&style_line, lv_palette_main(LV_PALETTE_BLUE));
  lv_style_set_line_rounded(&style_line, true);
  lv_style_set_line_opa(&style_line, LV_OPA_20);

  /*Create line and apply the style*/
  lv_obj_t* line;
  line = lv_line_create(lv_scr_act());
  lv_line_set_points(line, line_points, 2);     /*Set the points*/
  lv_obj_add_style(line, &style_line, 0);
  lv_obj_center(line);
```

### Expected behavior
Instead of the intersections between the line and the circles being darker than the rest of the line, they should have identical opacity.

### Screenshots or video
Expected result:
![ROUND_CAP_TRANSPARENT_LINE_EXPECTED](https://user-images.githubusercontent.com/97175134/188159510-9d6f5787-a19e-451a-8572-63cd3d038f78.png)

Actual result:
![ROUND_CAP_TRANSPARENT_LINE_ACTUAL](https://user-images.githubusercontent.com/97175134/188159555-cdedb6d2-9b8c-414b-a05c-703b759b02b2.png)

### Possible fixes
The cause of this issue seems to be the fact that the full circle is always drawn at the end of the line, instead of only half a circle. This poses no issue and is the efficient solution when the opacity of the shape is 100%, but when it's lower, the described issue appears. 

While it is more complex, the solution may be only drawing half a circle at the end of the line. This half circle should be rotated around the center of the full circle in order to fit the line ending such that no intersection occurs between the line and the half circle.

Another solution may be creating the full opacity version of the line in a temporary buffer, then drawing the result with the given opacity to the screen.

**Comment by kisvegabor** [comment]
It's also a limitation at this moment. The same issue exists with arcs too.

In v9 I'm planning to reconsider how masks are working (mask are used to draw non-rectangle shapes) and an important goal is to resolve these issues.

**Comment by kisvegabor** [comment]
Added to the v9.3 Roadmap as widget caching. 
https://github.com/lvgl/lvgl/issues/6763

**Comment by kisvegabor** [comment]
It's a complicated issue to resolve if the line has multiple points (line segments). I close it for now because it hasn't received any comments in the past 2 years, so I assume that it's not a burning problem.  

We can reopen it at any time if needed.
