### ISSUE TITLE
[Error] (19234.671, +0)  _lv_inv_area: detected modifying dirty areas in render         (in lv_refr.c line #212)

### ISSUE THREAD

**Issue by anghd** [kisvegabor/lvgl#3667]
00

**Comment by kisvegabor** [comment]
What's the problem here?

**Comment by codegrue** [comment]
What does this error mean. I get them all time also.

**Comment by XuNeo** [comment]
> What does this error mean. I get them all time also.

It normally means widget's properties have been modified during rendering(such as DRAW_MAIN event callback). It will cause rendering issues thus are forbidden.

**Comment by codegrue** [comment]
Using FreeRTOS where the UI is being altered in a different thread than the LVGL refresh loop, what is the proper pattern to prevent this kind of conflict?

**Comment by XuNeo** [comment]
LVGL is not thread safe. You can only call LVGL APIs from one thread.

**Comment by kisvegabor** [comment]
@XuNeo 
I'm thinking about something like this:
```c
lv_lock();  /*LVGL is not thread safe, so lock it before using any `lv_...` functions in any threads. */
lv_timer_handler(); /*/*Process timers, events, animations, display refreshed, and input devices*/*/
lv_unlock(); 
```
`lv_lock` and `lv_unlock` are using an `lv_mutex` internally if `LV_USE_OS` is set. Without OS they set/clear a bool variable for which we can ASSERT on some critical places. In case of `LV_OS_CUSTOM` the user can implement these functions.

This practice can be shown all the places so people will intuitively know that is locking is required.  

What do you think?

**Comment by codegrue** [comment]
Take for example a screen that shows data from an api call. The main loop is calling lv_timer_handler() and another thread calls the API and then updates screen labels when the data cones back. It seems like it's not possible to have this on the same thread without blocking the UI during the API wait period.

**Comment by XuNeo** [comment]
Adding a global lock to `lvgl` will work. I'm not sure if it's a best practice. 
Operation to `lvgl` normally should be done in signal thread and never block UI thread. Move block operations outside of `lvgl`'s thread like using `libuv` etc.

**Comment by kisvegabor** [comment]
Once people have an OS, they will use it for sure and will attempt to adjust the widgets from an other thread as well.

**Comment by kisvegabor** [comment]
`lv_lock` is not added yet, we are just talking about it. 

If you are calling LVGL function from multiple threads take look at [this](https://docs.lvgl.io/8.3/porting/os.html).

**Comment by codegrue** [comment]
Thank you. Wanted to share for FreeRTOS the code looks like this:

```
SemaphoreHandle_t xLVGLMutexHandle;
TaskHandle_t tUIHandle;
TaskHandle_t tLVGLHandle;

xLVGLMutexHandle = xSemaphoreCreateMutex();
xTaskCreate(uiCallback, "tUIHandle", 3000, (void *)0, tskIDLE_PRIORITY, &tUIHandle);
xTaskCreate(lvglCallback, "tLVGLHandle", RTOS_LVGL_STACK_SIZE, (void *)0, RTOS_LVGL_PRIORITY, &tLVGLHandle);

void lvglCallback(void *p)
{
    while (1)
    {
        // use mutex to insure nothing writes to LVGL during the render
        if (xSemaphoreTake(xLVGLMutexHandle, (TickType_t)10) == pdTRUE)
        {
            lv_timer_handler();

            xSemaphoreGive(xLVGLMutexHandle);
        }

        vTaskDelay(5 / portTICK_PERIOD_MS);
    }
}

void uiCallback(void *p)
{
    while (1)
    {
        // use mutex to lock LVGL before updating UI
        if (xSemaphoreTake(xLVGLMutexHandle, (TickType_t)10) == pdTRUE)
        {
            /* update LVGL UI here */

            xSemaphoreGive(xLVGLMutexHandle);
        }

        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
}
```
