### ISSUE TITLE
lv_switch lv_switch_get_value error

### ISSUE THREAD

**Issue by JRNetherlands** [kisvegabor/lvgl#3684]
When I try to get the value of a lv_switch i get a compilation error:

error:
ui_events.c:134: undefined reference to `lv_switch_get_value'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

code:
void ChargerClick(lv_event_t * e)
{
	// Your code here
	global.charger.chargeflag = lv_switch_get_value(ui_ChargeronSW);	
}

I use v8.3.1 and Squarlinestudio 1.1.0

I don't know for sure, but it seems like the lv_switch.h has no functions for getting and setting the values as documented on:
https://docs.lvgl.io/latest/en/html/widgets/switch.html

**Comment by embeddedt** [comment]
You are looking at v7 documentation. Here's the v8 link. :)

https://docs.lvgl.io/8/widgets/core/switch.html#change-state

By the way, please use the [forum](https://forum.lvgl.io/) to ask questions.
