### ISSUE TITLE
Wrong behavior of overflow of lv_span

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#3685]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When the font placeholder is turned off, and `lv_span` is used to display the mixed text of Chinese + emoji, displaying ellipses is not expected behavior.

### To Reproduce
in lv_conf.h:
`#define LV_USE_FONT_PLACEHOLDER 0`

```c
void span_test(void)
{
    lv_obj_t* spans = lv_spangroup_create(lv_scr_act());
    lv_spangroup_set_align(spans, LV_TEXT_ALIGN_LEFT);
    lv_spangroup_set_overflow(spans, LV_SPAN_OVERFLOW_ELLIPSIS);
    lv_spangroup_set_mode(spans, LV_SPAN_MODE_EXPAND);
    lv_obj_set_style_border_width(spans, 1, 0);
    lv_obj_set_style_border_color(spans, lv_color_black(), 0);
    lv_obj_set_style_text_font(spans, &lv_font_simsun_16_cjk, 0);

    lv_span_t* span = lv_spangroup_new_span(spans);
    lv_span_set_text(span, "a写\ua060");  // ‘\ua060’ is an emoji that does not support display
}

```

### Expected behavior
![image](https://user-images.githubusercontent.com/26767803/189879206-93f4dc59-54df-4750-b4f6-3f58156b822d.png)

### Screenshots or video
![image](https://user-images.githubusercontent.com/26767803/189879108-dcce9b41-999b-4db6-8eff-b4bbc286b78a.png)

**Comment by FASTSHIFT** [comment]
It can be displayed normally when the text order is modified:
```c
lv_span_set_text(span, "写a\ua060");
```

![image](https://user-images.githubusercontent.com/26767803/189892305-ce2c2227-2406-44fc-a0d1-dd7cc8dee673.png)


I tried to compare the drawing process of the two texts and found that `_lv_txt_get_next_line()` in `lv_txt_get_snippet()` returned different values.

For text: "写a\ua060", `ofs = 7`
![image](https://user-images.githubusercontent.com/26767803/189893583-aa04ee39-624e-4fff-ac6a-aa093d0cd451.png)

For text: "a写\ua060", `ofs = 4`
![image](https://user-images.githubusercontent.com/26767803/189892888-7843594a-0378-4507-b4db-97f031c3d8e4.png)

`ofs` will be passed to `last_snippet->bytes` here:
![image](https://user-images.githubusercontent.com/26767803/189894943-bc9d22c5-3795-4bfa-9db9-e73e57cafea8.png)

This leads to an error in the text overflow judgment of the function `lv_draw_span()`, and finally makes the span mistaken for a truncated text, and finally draws an ellipsis.

**Comment by FASTSHIFT** [comment]
The reason why the return value of `_lv_txt_get_next_line()` is different is caused by word truncation.
![image](https://user-images.githubusercontent.com/26767803/189900130-554907ec-f2e4-44f4-a1bf-9bc46c753987.png)

For text: "a写\ua060"
'a' occupies 1 byte, '写' occupies 3 bytes, because Chinese is truncated text and the `max_width` passed in by span is exactly the sum of the pixel widths of 'a' and '写' (\ua060' glyphs cannot be drawn glyph, pixel width is 0), and finally returns 4.

For text: "写a\ua060"
"a\ua060" is regarded as a completed word by `lv_txt`, the byte occupied by this word is `1+3=4`, plus 3 bytes of '写', so return 7.

**Comment by FASTSHIFT** [comment]
There is a problem now that `lv_span` will calculate the total width of the text and pass it to the `max_width` of `_lv_txt_get_next_line()`, but since the placeholder is closed, it will encounter the case where the glyph width is 0, and `max_width` cannot contain this information, resulting in problems with word matching.

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/3687 is merged so I close it.
