### ISSUE TITLE
In lv_api_map undefined reference to lv_timer_handler()

### ISSUE THREAD

**Issue by PaulskPt** [kisvegabor/lvgl#3689]
For an Espressif ESP32-S3-BOX, using Espressif repo 'esp-box', example image_display,
the ```idf.py flash monitor``` command results in the following error:

![undefined_reference_to_tv_timer_handler](https://user-images.githubusercontent.com/9107950/190425949-69d6e51e-83f7-457a-b5c5-6a62b4eb8c3b.png)

where as the call to ```lv_timer_handler```, in file ```lv_api_map.h```  is here:
![call_to_tv_timer_handler](https://user-images.githubusercontent.com/9107950/190426100-17b5532d-181d-46b3-8553-0100e6c81e18.png)

The definition is in lv_timer.h:

![definition_lv_timer_handler](https://user-images.githubusercontent.com/9107950/190427224-d4b3c8d0-e33e-4ca6-9d30-b396d13fc4b3.png)

**Comment by kisvegabor** [comment]
It's very strange. Which LVGL version do you use?

**Comment by PaulskPt** [comment]
Thank you for your reply!
I am using the lvgl which is a componentent in the Espressif esp-box repo. Below a screenshot of the lvgl/library.properties file.

![2022-09-16 13-08_esp-box_lvgl_version](https://user-images.githubusercontent.com/9107950/190635830-f43c6005-a274-4c06-a7c7-af9cbba70092.png)

**Comment by PaulskPt** [comment]
Here a view of the location of lvgl component in the esp-box repo

![lvgl_as_component_of_esp-box_repo](https://user-images.githubusercontent.com/9107950/190675908-4ac7858c-3e3f-47bf-9529-5f8bf953bdac.png)

**Comment by kisvegabor** [comment]
`lv_timer_handler` is available in v8.1 for sure:
https://github.com/lvgl/lvgl/blob/release/v8.1/src/misc/lv_timer.c#L67

I can't see what could be the problem. :slightly_frowning_face: 

At worst case, just delete the problematic part from `lv_api_map.h`.

**Comment by PaulskPt** [comment]
OK, thank you
