### ISSUE TITLE
lv_sliders with discrete positions floor() instead of round()

### ISSUE THREAD

**Issue by lentinj** [kisvegabor/lvgl#3690]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

If using a slider to choose discrete values, a click to the slider goes to the next-smallest value, rather than the nearest value.

### To Reproduce

Using 8.3.1, create a wide slider with small range, e.g:

```c
  obj = lv_slider_create(obj);
  lv_obj_set_width(obj, LV_PCT(100));
  lv_slider_set_mode(obj, LV_SLIDER_MODE_NORMAL);
  lv_slider_set_range(obj, 0, 4);
  lv_slider_set_value(obj, 0, LV_ANIM_OFF);
```

Then click / touch the slider at just before point 3. instead of the knob jumping to point 3, it will jump to point 2, the next smallest value.

### Expected behavior

I'd expect the slider to jump to point 3, i.e. the one where my finger basically is.

It could be I'm abusing the slider and this is outside it's remit, but I'm pretty sure this use-case has been suggested on the forum.

### Suggested fix

The following turns the integer division's implicit floor into a round:

```patch
diff --git a/src/widgets/lv_slider.c b/src/widgets/lv_slider.c
index 9c820c22..08cd78bf 100644
--- a/src/widgets/lv_slider.c
+++ b/src/widgets/lv_slider.c
@@ -212,7 +212,7 @@ static void lv_slider_event(const lv_obj_class_t * class_p, lv_event_t * e)
                 /*Make the point relative to the indicator*/
                 new_value = p.x - (obj->coords.x1 + bg_left);
             }
-            new_value = (new_value * range) / indic_w;
+            new_value = (new_value * range + indic_w/2) / indic_w;
             new_value += slider->bar.min_value;
         }
         else {
@@ -223,7 +223,7 @@ static void lv_slider_event(const lv_obj_class_t * class_p, lv_event_t * e)

             /*Make the point relative to the indicator*/
             new_value = p.y - (obj->coords.y2 + bg_bottom);
-            new_value = (-new_value * range) / indic_h;
+            new_value = (-new_value * range + indic_h/2) / indic_h;
             new_value += slider->bar.min_value;
         }
```

This works for me, but I've not tested much outside my own use cases admittedly.

Thanks for LVGL!

**Comment by kisvegabor** [comment]
Thank you! I fixed it in both `master` and `release/v8.3` as you suggested.

I've tested it and it worked well for me too.
