### ISSUE TITLE
LV_COLOR_16_SWAP missing

### ISSUE THREAD

**Issue by Olfox59** [kisvegabor/lvgl#3694]
Hi all,

I'm working on last esp32s3 lilygo board.

I need to use LV_COLOR_16_SWAP otherwise my color are doing some band effect ,  what i did in lv_conf.h, but compared to lvgl v7, it seems that LV_COLOR_16_SWAP is not manage in this v8.3 and has desappear from the librarie. How to proceed please ?

Thank you !

**Comment by kisvegabor** [comment]
Please use `release/v8.3` branch. The `master` branch is under development now.
