### ISSUE TITLE
Very low FPS and high CPU during benchmark - ESP32 + ILI9488 + LVGL V8.3 + Arduino IDE

### ISSUE THREAD

**Issue by dills-b** [kisvegabor/lvgl#3701]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Running on an ESP-WROOM-32
DOIT ESP32 DEVKIT V1
480x320 TFT w/ ILI9488

Running the Arduino_LVGL.ino included with the latest V8.3 (installed from Library Manager)
lv_conf configured per the Get Started -> Arduino documentation (Used 8.2 as it does not exist for 8.3)
TFT_eSPI configured to work with ILI9488. SPI speed set to 40Mhz.
Enabled lv_demo_benchmark()

LV_MEM_SIZE (48U * 1024U) -> unchanged from lv_conf template

Results:
Weighted FPS:2 
Opa. speed: 66%

CPU usage while sitting on the benchmark summary screen is consistently above 50%. 100% while running benchmark.

Have run multiple times with various settings with no change to performance. Running the widgets demo was also very slow (didn't monitor FPS). Significant skipping between tabs and when scrolling. 

### To Reproduce

Run LVGL_Arduino with lv_demo_benchmark() enabled 
Only changes to lv_conf are those initially outlined in Get Started documentation

### Expected behavior
Based on examples online I was expecting more than 2-3 FPS.

Thanks for taking a look at this. My guess is that there is something I have not configured properly but I have been unable to make any progress.

**Comment by C47D** [comment]
It's been a while since I used a similar setup, the limitation is the SPI interface and the color depth. Using a parallel interface showed bigger FPS.

Saying that maybe there's something else others can add so you could improve the FPS.

**Comment by r-karthik-r** [comment]
hi @dills-b, struck with the same issue. the load speed is satisfactory while directly controlling with TFT_ESPI library. so confused. Found any resolution?

**Comment by kisvegabor** [comment]
Yes, we have found something. The drawing pipeline on v9 is more complex than v8 and probably due the higher number of nested functions the ESP chip is out of flash cache. We can mitigate it by introducing a few shortcuts for typical cases, e.g. immediately blend an image without any transformation or recoloring.

Exactly which use case was slower or you in v9?
