### ISSUE TITLE
lvgl.h not updated to 8.3.2

### ISSUE THREAD

**Issue by elgerg** [kisvegabor/lvgl#3711]
Hi,

I just updated to 8.3.2 but noticed that the version number hasnt been updated.

Made me think I was referencing an older version..

Thanks
Alex

**Comment by tripathiu** [comment]
Hello, where specifically can we see the version number?

**Comment by kisvegabor** [comment]
I really missed to update version number on one place and already fixed it with https://github.com/lvgl/lvgl/commit/c8bee40410da4945d0267a4f4af7fa189bc33ed1 ... :sob: 

But to be honest, I have no good idea how to fix it after the release.
 
cc @embeddedt

**Comment by embeddedt** [comment]
I think the cleanest solution is to release 8.3.3 with no other changes.

**Comment by kisvegabor** [comment]
I have no better idea either. I'll do it tomorrow.

**Comment by kisvegabor** [comment]
I released v8.3.3 so I close this issue.
