### ISSUE TITLE
LVGL v9.0 - Arduino Example - ld.exe: region `dram0_0_seg' overflowed by 39768 bytes

### ISSUE THREAD

**Issue by iw7dmh** [kisvegabor/lvgl#3746]
MCU or Board name: **DOIT ESP32 DEVKIT V1**
Panel Driver IC: **SSD1963 - 800x480**
Bus type: **Parallel8**
LVGL version: **v9.0 dev**
Graphic Libs: **TFT_eSPI**
FrameWork version: **ArduinoESP32 v2.0.3**
Build Environment : **ArduinoIDE 2.0**
Operating System: **Windows 11**
Display:  https://www.buydisplay.com/lcd-5-ssd1963-tft-module-touch-screen-display-800x480-mcu-arduino

### Describe the bug
In LVGL 9.0 release the official Arduino example (**LVGL_Arduino**) can't be compiled/uploaded on any ESP32 device. I am having the following error: c:/users/enzo/appdata/local/ ... ../xtensa-esp32-elf/bin/**ld.exe: region `dram0_0_seg' overflowed by 39768 bytes**

### To Reproduce
Just compile the code for a 800x480 display

### Expected behavior
Compile and upload the default Arduino Example

Everything is fine with the 8.3 stable release

Best regards

**Comment by kisvegabor** [comment]
There is no v9.0 release as v9 is still under development. You should use v8.3 from https://github.com/lvgl/lvgl/tree/release/v8.3
