### ISSUE TITLE
GIF images with only one frame or one cycle cannot be stopped correctly

### ISSUE THREAD

**Issue by qingliyu** [kisvegabor/lvgl#3760]

**Comment by qingliyu** [comment]
The single cycle gif generated by Photoshop cannot be stopped correctly
    lv_obj_t *icon2 = lv_gif_create(lv_scr_act());
    /*From file*/
    lv_gif_set_src(icon2, "B:/resources/test");
    lv_obj_align(icon2, LV_ALIGN_TOP_LEFT, 0, 0);

**Comment by kisvegabor** [comment]
Can you send an example gif?

**Comment by qingliyu** [comment]
> Can you send an example gif?

This gif is single cycle on PC and cyclic on LVGL project.

![1](https://user-images.githubusercontent.com/45723140/197789033-7dd806a9-ebab-4391-a4cb-226f686ad2ed.gif)

**Comment by kisvegabor** [comment]
Thank you, I fixed it in https://github.com/lvgl/lvgl/commit/4972efc3eeab32b83aa4faa4d471aab7dea71687
