### ISSUE TITLE
Why is there no . h file in the compiled product

### ISSUE THREAD

**Issue by CliffHorse008** [kisvegabor/lvgl#3766]
### Introduce the problem

cmake output has no header file, only  liblvgl. a
### Examples and cases

N/A
### Suggested solution

Provide the header file corresponding to the library

**Comment by kisvegabor** [comment]
What is the common practice in this case? Should CMake  also create an `inc` folder that you can copy/install where needed?

**Comment by CliffHorse008** [comment]
Yes, I think that cmake should also create an inc file, otherwise a single library file cannot be used by others. Many relative paths are used in the source code, which makes it inconvenient to embed lvgl into other projects

**Comment by CliffHorse008** [comment]
In my project, I hope to directly use the products of lvgl cmake to provide external projects and form a complete compilation system

**Comment by kisvegabor** [comment]
> Many relative paths are used in the source code, which makes it inconvenient to embed lvgl into other projects

We can simply copy the `src` folder, rename it to `inc` and remove all the `.c` files. After that `inc/lvgl.h` should work and all relative path will be correct. What do you think?

**Comment by CliffHorse008** [comment]
I think so！

**Comment by 0x0203** [comment]
I had similar thoughts with respect to making a library. My one concern with doing this, however, would be to make sure whatever documentation discusses using the library in this way makes a clear, hard to miss disclaimer about how the compiled library will only work for whatever configuration was set in lv_conf.h when it was compiled. Maybe it's obvious to anyone already working with LVGL, but I can see someone trying to link against the installed "system" .a for a different target that needs a different configuration (e.g., using a different color depth), and not understanding why it doesn't work.

**Comment by 0x0203** [comment]
As a follow up thought, perhaps it would be useful to name the .a to include the target platform so that you could have multiple system .a's installed, one for each target you need. For example, lvgl_TFT_eSPI.a and lvgl_esp32.a? Target name could be a user-set parameter set in lv_conf.h or a cmake define.

**Comment by CliffHorse008** [comment]
You are right. If a novice uses it directly, it may be misleading that it cannot run, but the main reason is that its kconfig clipping mode+cmake compilation mode are perfectly compatible with my project. For different target platforms, I just need to use different kconfigs, so there will be no problem you mentioned above!

**Comment by kisvegabor** [comment]
Are you interested in updating CMake with creating the `inc` folder? Adding an option to set the output name seems useful. 

BTW, our CMake alrady supports `install`:
https://github.com/lvgl/lvgl/blob/6e62fcfd08987946ab99e6fa3369f4268bab83b1/env_support/cmake/custom.cmake#L67-L71


I'm not a CMake expert so I'm not sure it helps.

**Comment by 0x0203** [comment]
I'm not sure who's being asked, but I'm probably not the right person to implement this. I'm not using cmake for my builds so testing would be difficult, and I have pretty limited experience in using/configuring it.

**Comment by kisvegabor** [comment]
I meant: Are _any of_ you interested in updating CMake with creating the inc folder? :slightly_smiling_face: 

Maybe @chenyinen?
