### ISSUE TITLE
Compilation warning `maybe-uninitialized` with -O2 when LV_COLOR_DEPTH = 1

### ISSUE THREAD

**Issue by sorz** [kisvegabor/lvgl#3772]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

LVGL version: v8.3.3

Compile failed with -O2 (while -Og is OK) and LV_COLOR_DEPTH = 1:
```
Compiling .pio\build\esp32dev\components\lvgl\src\draw\sw\lv_draw_sw_transform.o
components\lvgl\src\draw\sw\lv_draw_sw_transform.c: In function 'lv_draw_sw_transform':
components\lvgl\src\draw\sw\lv_draw_sw_transform.c:422:25: error: 'c_base.full' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 cbuf[x] = c_base;
                 ~~~~~~~~^~~~~~~~
components\lvgl\src\draw\sw\lv_draw_sw_transform.c:353:24: note: 'c_base.full' was declared here
             lv_color_t c_base;
                        ^~~~~~
cc1.exe: some warnings being treated as errors
*** [.pio\build\esp32dev\components\lvgl\src\draw\sw\lv_draw_sw_transform.o] Error 1
```

`c_base` is initialized and used on following code block:

https://github.com/lvgl/lvgl/blob/5545ffc9257808ee26eac833ec5326706cdf2007/src/draw/sw/lv_draw_sw_transform.c#L398-L423

Environment:
- Windows 11
- PlatformIO 6.1.4
- Espressif 32 v5.2.0
- ESP-IDF v4.4.2

### To Reproduce
1. Setup PlatformIO with platform `espressif32`, framework `espidf`, and board `esp-wrover-kit`
2. Clone LVGL v8.3.3 to `components/lvgl`; set `#define LV_COLOR_DEPTH 1` on `lv_conf.h`
3. Set `CONFIG_COMPILER_OPTIMIZATION_PERF=y` on `sdkconfig` to turn on compiler optimization
4. Build

### Expected behavior
Built without maybe-uninitialized warning.

**Comment by kisvegabor** [comment]
Thank you for reporting this issue. I've pushed a fix.
