### ISSUE TITLE
Transformation for 90,180,270 degrees will make label text blurred.

### ISSUE THREAD

**Issue by EagleLiao** [kisvegabor/lvgl#3777]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Transformation for 90,180,270 degrees will make label text blurred.

### To Reproduce
1. Enable LV_COLOR_SCREEN_TRANSP feature.
2. Create a lable, and set the transform parameters for 90, 180, or 270 degrees.
```c
    lv_obj_t* labela = lv_label_create(lv_scr_act());
    lv_label_set_text(labela, "Transform for 0");
    lv_obj_center(labela);

    lv_obj_t* labelb = lv_label_create(lv_scr_act());
    lv_label_set_text(labelb, "Transform for 90");
    lv_obj_center(labelb);
    lv_obj_set_style_transform_angle(labelb, 900, 0);
```

### Expected behavior
n/a.

### Screenshots or video
![image](https://user-images.githubusercontent.com/32354697/198927908-4da53104-8cef-43cc-aef0-e4d6de000ddc.png)

**Comment by kisvegabor** [comment]
Thank you for reporting it. It helped to spot an inaccuracy in the transformation algorithm. I've fixed it in both `release/v8.3` and `master`.
