### ISSUE TITLE
LVGL Meter with multiple arcs More Property Adjustments

### ISSUE THREAD

**Issue by arilink** [kisvegabor/lvgl#3789]
I would like to make a similar control by referring to the example of Meter with multiple arcs, but I can only modify the background color of meter but cannot modify the background color of internal arc. Could you please tell me whether it is possible to modify the background color of internal arc and adjust the value of arc to achieve better effects? (Currently you cannot adjust the arc background color. You can only use arc start end to adjust the color of the area to be displayed.)

**Comment by kisvegabor** [comment]
I added a simple change to the `meter` to handle the bg img too: d274523be

The `meter`'s API will be updated in lvgl v9, so I haven't added a API for it, but it can be used easily like this:
```c
    indic->type_data.arc.src = &image;
```

**Comment by arilink** [comment]
Ok, I'll try and get back to you later. Thank you very much
