### ISSUE TITLE
v8.2 lvgl/src/core/lv_refr.c   draw_buf_rotate()::while(row < area_h) {}  

### ISSUE THREAD

**Issue by YulongHan** [kisvegabor/lvgl#3801]
When variable height is zero, it loops indefinitely

#4  0xb6dba166 in draw_buf_rotate (area=0xbee42b5c, color_p=0x82000)
    at ./lvgl/src/core/lv_refr.c:959
--Type <RET> for more, q to quit, c to continue without paging--
        height = 0
        rot_buf = 0x10c190
        draw_buf = 0x81fe0
        area_h = 56
        max_row = 0
        init_y_off = 320
        area_w = 1
        row = 1
        drv = 0xcb6fc
        __func__ = "draw_buf_rotate"

**Comment by kisvegabor** [comment]
Could you send a pull request with a fix?
