### ISSUE TITLE
How to adjust the Label color of the Meter Scaler?

### ISSUE THREAD

**Issue by arilink** [kisvegabor/lvgl#3803]
I was trying to make a car meter with scaler for scale and number display but when I changed the bg_color of meter to black, The label of scaler cannot be displayed. I query lv_meter.c but there is no api to adjust the label color.

**Comment by kisvegabor** [comment]
It should work:
```c
    lv_obj_set_style_text_color(meter, lv_color_hex(0xff0000), LV_PART_TICKS);
```
