### ISSUE TITLE
free png_data resources

### ISSUE THREAD

**Issue by glory-man** [kisvegabor/lvgl#3806]
lodepng_load_file() could exit with error code
https://github.com/lvgl/lvgl/blob/d219960de0ca00122f131e8dbdf55b153eb8a383/src/libs/png/lv_png.c#L163
but problem may be inside of
https://github.com/lvgl/lvgl/blob/d219960de0ca00122f131e8dbdf55b153eb8a383/src/libs/png/lodepng.c#L380
In this case memory allocated in lodepng_load_file()
https://github.com/lvgl/lvgl/blob/d219960de0ca00122f131e8dbdf55b153eb8a383/src/libs/png/lodepng.c#L402
not freed, what can cause a leakage in case of problems with open/seek/read files

**Comment by kisvegabor** [comment]
Could you send a Pull request with a fix?

**Comment by glory-man** [comment]
PR https://github.com/lvgl/lvgl/pull/3853 created

**Comment by kisvegabor** [comment]
The PR is merged, so closing this issue.

**Comment by kisvegabor** [comment]
Upps, I forgot to actually press the close button :smile:
