### ISSUE TITLE
keyboard popover

### ISSUE THREAD

**Issue by GeGeShan** [kisvegabor/lvgl#3808]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When you press the 1# key on your keyboard, the keyboard will still pop up even though you have set `lv_keyboard_set_popovers(kb,false);`

**Comment by kisvegabor** [comment]
There was similar bug earlier that I've already fixed. Which LVGL version do are using? In v8.3.3 it's already fixed for sure.
