### ISSUE TITLE
Why cancel LV_COLOR_16_SWAP？

### ISSUE THREAD

**Issue by qingliyu** [kisvegabor/lvgl#3811]
### 

###

**Comment by qingliyu** [comment]
I am using the spi interface of nrf52840 to drive a 128 * 128 LCD screen. The color cannot be displayed correctly. It is used normally in 8.3.2. There is a problem when upgrading to master.

**Comment by kisvegabor** [comment]
See the README:
![image](https://user-images.githubusercontent.com/7599318/202903328-5ff63a4a-551f-498c-972b-2be42e9e0df4.png)

Please use the `release/v8.3` branch.
