### ISSUE TITLE
lv_tabview can not scroll when use Cmake build

### ISSUE THREAD

**Issue by haidongpan** [kisvegabor/lvgl#3813]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce
1. add the demo of lv_demo_widgets in main.c
2. build it by CMakeList
### Expected behavior
Expected the lv_tabview can scroll and switch normally

### Screenshots or video

https://user-images.githubusercontent.com/107170273/202888507-453f7796-b253-4f37-889b-96bc2617d864.mp4

**Comment by embeddedt** [comment]
We will need some more details. What platform are you using? Which LVGL commit/version?

**Comment by haidongpan** [comment]
The version of lvgl i used is v8.3, and i portting it on linux-5.10

**Comment by haidongpan** [comment]
when i build it by Makefile, the tab can switch normally, but CMakelist can not , i do not known why

**Comment by haidongpan** [comment]
i also download the latest source code, which is master branch, lv_tabview also can not scroll, and can not change tab 

https://user-images.githubusercontent.com/107170273/203196676-f84931fe-d8de-46b9-a726-f30e9c4693c4.mp4

**Comment by haidongpan** [comment]
does this problem have have confirmed ?

**Comment by kisvegabor** [comment]
It's very strange. I wonder what could be the difference between make and Cmake. They both `glob` all source files so the only difference could be the build settings. I think mainly the optimization level can affect these strange behavior.

Is there any difference you change the optimization level?

You can also enable `TRACE` level logging in `lv_conf.h` and check the difference.

**Comment by haidongpan** [comment]
I have not change the optimization level, just download source code from github, does your local project have the same phenomenon as my project

**Comment by haidongpan** [comment]
all source code build in execute file by Makefile,  and source code build in execute file and  liblvgl.so liblvgl_demos.a liblvgl_samples.a dynamic library. I think ether build method is OK, but i do not know what is the reason that cause the problem. this already takes one week for me

**Comment by kisvegabor** [comment]
It works for me in both cases. 

The `.a` files just an intermediate step. Finally all linked together into a single executable with CMake too. 

But you mentioned `liblvgl.so`. Isn't it also `liblvgl.a`?

Have you tried to logs?

**Comment by haidongpan** [comment]
[make.log](https://github.com/lvgl/lvgl/files/10089594/make.log)
[cmake.log](https://github.com/lvgl/lvgl/files/10089595/cmake.log)
1. attachment is the lv_log when info debug is enable, i found no diffrence in each other
2. i make sure that liblvgl, liblvgl_demos and liblvgl_examples will be generate when build by cmake, you can check is in custom.cmake file

**Comment by haidongpan** [comment]
![cmake](https://user-images.githubusercontent.com/107170273/203928726-c1f2b312-9aab-4704-9d76-5d03e717e764.PNG)
attachment is the place that liblvgl, liblvgl_demos and liblvgl_examples define

**Comment by haidongpan** [comment]
the execute file will link the dynamic library when it is in runtime

**Comment by haidongpan** [comment]
did you have any more suggestion ?

**Comment by kisvegabor** [comment]
In the `flush_cb` please `printf` the coordinates of the flushed area. Do you see large screens sized areas when the screen transition should happen?

**Comment by haidongpan** [comment]
You are right, yes, I found out the reason that due this case, the optimize level is O2 in my project. i do not known which part is optimized.

**Comment by kisvegabor** [comment]
Normally optimization shouldn't matter. I usually use O3 in production and never found an issue like this. 

Anyway, at least now we know that not build system causing the issue.

**Comment by haidongpan** [comment]
thank you very much

**Comment by kisvegabor** [comment]
Anyway, I'd be curious which part gets broken with optimization. Do you see any warnings?

**Comment by haidongpan** [comment]
if i have time i will check these details
