### ISSUE TITLE
lv_msg_subscribe API has wrong spelling in 8.x

### ISSUE THREAD

**Issue by sukesh-ak** [kisvegabor/lvgl#3822]
lv_msg_subscribe API has wrong spelling in 8.x
`c` is missing in the spelling. I also noticed, this is fixed on the master branch.

### Describe the bug
Link of the relevant API code below
Its `lv_msg_subsribe` instead of `lv_msg_subscribe`

https://github.com/lvgl/lvgl/blob/716e5e2c8bd2a22e7d56e8d7ca33054a11a1f4ed/src/extra/others/msg/lv_msg.c#L62

https://github.com/lvgl/lvgl/blob/716e5e2c8bd2a22e7d56e8d7ca33054a11a1f4ed/src/extra/others/msg/lv_msg.c#L76

**Comment by kisvegabor** [comment]
Thanks for the report, I've just fixed it.
