### ISSUE TITLE
Alternatives to Framebuffer

### ISSUE THREAD

**Issue by ChrisPasda** [kisvegabor/lvgl#3830]
### Introduce the problem
I am using LVGL on my embedded system on the framebuffer in the initramfs. But i wanted to use it in my rootfs aswell and my windowmanager is blocking the framebuffer. So i was wondering what alternatives i have with LVGL without shutting down the window manager. Is it possible to get LVGL working with wayland on my embedded system or are there other alternatives?

Thank you very much in advance and best regards,

Chris

**Comment by kisvegabor** [comment]
Is SDL an option for you?

**Comment by ChrisPasda** [comment]
Yeah for sure, i tried to get SDL running and i managed to compile everything correct but i dont see anything on my display and i don't know why. Do you have experience mit SDL and the framebuffer? 

Thank you very much in advance and have a nice weekend,

Chris

**Comment by kisvegabor** [comment]
Do you see a new windows opened with empty or transparent content?  Could you take a photo about it?
