### ISSUE TITLE
demos benchmark overflow

### ISSUE THREAD

**Issue by mysterywolf** [kisvegabor/lvgl#3836]
In lvgl/demos/benchmark/lv_demo_benchmark.c

https://github.com/lvgl/lvgl/blob/release/v8.3/demos/benchmark/lv_demo_benchmark.c#L999 will cause memory overflow, if I change to whatever other string, the demo will be going normal.

![image](https://user-images.githubusercontent.com/34888354/204108335-4900fbec-2da4-4c4f-b77b-ae35fc9220c2.png)

**Comment by FASTSHIFT** [comment]
Can you enable [ASAN](https://learn.microsoft.com/zh-cn/cpp/sanitizers/asan?view=msvc-170) for testing?

**Comment by kisvegabor** [comment]
Our CI tests are running the benchmark demo with ASAN so it should work in general.

Any debug info, or ASAN as @FASTSHIFT mentioned?

**Comment by mysterywolf** [comment]
@FASTSHIFT Thank you. It works now, Gabor has fixed at here https://github.com/lvgl/lvgl/commit/ae3825871e31cd42cad2f310bdfc605150670511
