### ISSUE TITLE
Has the non antialiased drawing disappeared?

### ISSUE THREAD

**Issue by alepi** [kisvegabor/lvgl#3838]
Hi,

I have a possibly unusual use case where I have a big display ( a TV, it could be any size up to tens of inches ) and low resolution ( 320 x 240 ).

Antialiasing does not work well for me in that situation.

There used to be an LV_ANTIALIAS constant to set to 0 in lv_conf.h but it seems to have disappeared.

I tried messing around a bit with the latest (8.3) code and I managed to get rid of antialias on text and images but not on rounded corners of rectangles.

Is there any chance we can get the LV_ANTIALIAS constant back?

**Comment by FASTSHIFT** [comment]
Antialiasing parameters are located at: https://github.com/lvgl/lvgl/blob/master/src/hal/lv_hal_disp.h#L100
It is turned on by default: https://github.com/lvgl/lvgl/blob/master/src/hal/lv_hal_disp.c#L89

**Comment by alepi** [comment]
Hi, thank you for your response.

That is indeed one of the changes I made when I talked about "messing around" with the code. I just grep'd for "alias" in the whole LVGL directory and changed that setting and the analogous one for images. Also, I set the default font to unscii 8.

I believe that rounded corners are drawn with some form of antialias regardless, that's why I opened this issue.

I switched back to release v7 for now, which seems to be the last one to support LV_ANTIALIAS. However, I would love to be able to keep up with the latest version of LVGL.

**Comment by FASTSHIFT** [comment]
The anti-aliasing algorithm can only alleviate the aliasing problem, but it cannot completely solve it. After all, the accuracy of physical display is limited.

**Comment by alepi** [comment]
???

I want the drawing to be aliased...

I am trying to disable the anti aliasing...

**Comment by FASTSHIFT** [comment]
Sorry, I think I misunderstood you, it's true that lvgl doesn't seem to handle drawing without anti-aliasing.

**Comment by kisvegabor** [comment]
It was moved to `disp_drv.antialiasing = 0;`.

**Comment by FASTSHIFT** [comment]
> It was moved to `disp_drv.antialiasing = 0;`.

I tried turning that off, but the non-anti-aliased drawing doesn't seem to be taking effect.
I searched the code, it seems that lvgl only accesses this parameter when `layer_type != LV_LAYER_TYPE_NONE` (https://github.com/lvgl/lvgl/blob/master/src/core/lv_refr.c#L936), but later The software drawing does not continue to read this parameter.
Has non-anti-aliased rendering been removed?

**Comment by alepi** [comment]
yep, like I said I had a look at the code too and it seems that text and images can be drawn without antialiasing, but rounded corners and possibly other drawing primitives still draw with antialiasing on

**Comment by kisvegabor** [comment]
Do you use `master`? If so, please use the `release/v8.3`.

**Comment by alepi** [comment]
I was using master indeed. I switched to 8.3. Still no joy.
I set
      disp_drv.antialiasing = 0;
after initialising it and still the rounded corners are not sharp and don't look good on a large display.
Also tried changing the code in lv_img.c and lv_hal_disp.c to initialise without anti aliasing but I still don't get sharp rounded corners.
Version 7 still does not antialias sharp corners.

**Comment by kisvegabor** [comment]
Uhh, you are right. I was sure it's working fine in v8 but it really wasn't. 

I've pushed a fix.

**Comment by alepi** [comment]
Absolutely perfect :-) Thank you very much
