### ISSUE TITLE
Wrong FPS when running benchmark

### ISSUE THREAD

**Issue by HaoboGu** [kisvegabor/lvgl#3844]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version - I'm using LVGL v8.3
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I'm using LVGL with azure threadx together. 
When I ran the lvgl benchmark, I got 33341 FPS:
![image](https://user-images.githubusercontent.com/8640918/204789959-1cf4421e-e58f-4752-9930-59787cae4ed5.png)

The timer tick is already set to 1ms:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/8640918/204790987-662184f2-f6ec-4853-8d21-81149d1ff1e4.png">

### Expected behavior

The benchmark should give me correct fps

**Comment by kisvegabor** [comment]
I have 2 questions:
- approximately what is the correct FPS?
- why are these artifacts on the screen?

**Comment by HaoboGu** [comment]
hello @kisvegabor
 
1. the correct FPS should be 100 ~ 120 when I ran lvgl on the bare metal chip.
2. The timing I used for the screen is not perfect, results in those black rectangles. You can just ignore it.

attachment: the correct displayed content:
![image](https://user-images.githubusercontent.com/8640918/205586503-c492d07f-c1e8-4938-9b92-4dd61cc69fa5.png)

**Comment by kisvegabor** [comment]
How fast the MCU is and what is the resolution of the display? Maybe the 30k FPS is correct.

30,000 FPS means 0.03 ms = 30 us rendering time. It looks like a ~128x48 display -> ~6k pixels -> 30us/6k = 5 ns -> 200 MHz. So 1 instruction per pixel with a 200 MHz MCU. Does't seem unrealistic.

**Comment by HaoboGu** [comment]
My MCU is running at 280MHZ, but the screen is 310 * 100. It's strange because the fps monitor at the bottom-right shows 33FPS, which is not same as benchmark shows

**Comment by kisvegabor** [comment]
The bottom-right indicator shows how much time elapsed between two rendering cycle. So unless rendering takes more then 30 ms, it will show 33FPS (for 1ms and 29ms rendering time too).

On the other hand the benchmark measures the pure rendering time.

**Comment by HaoboGu** [comment]
I suspect the weird FPS is caused by some configurations of Azure RTOS. When I ran benchmark on bare mental, the FPS seems to be right(about 120FPS).

**Comment by kisvegabor** [comment]
It's great that we can narrow down the issue.

I can imagine only one thing that can mess up the measurement: if  `lv_tick_inc` is not called from an interrupt to always tell the precise "time".

**Comment by HaoboGu** [comment]
`lv_tick_inc` is called from a timer thread which has higher priority than main thread:

```c
// It's timer thread
void lvgl_tick_thread_entry(ULONG thread_input)
{
  while (1)
  {
    lv_tick_inc(1);
    // sleep for 1 tick(1ms)
    tx_thread_sleep(1);
  }
}
```

The main thread is:
```c
void main_thread_entry(ULONG thread_input)
{
  while (1)
  {
    tx_thread_sleep(5);
    lv_timer_handler_run_in_period(5);
  }
}
```

I fount that when I changed the time period in MAIN thread to 50, the FPS becomes 20000:
```c
// Results in 20000FPS
void main_thread_entry(ULONG thread_input)
{
  while (1)
  {
    tx_thread_sleep(50);
    lv_timer_handler_run_in_period(50);
  }
}
```
It seems that when calculating FPS, lvgl regards the ticks in us rather than ms somewhere?

**Comment by kisvegabor** [comment]
Ar you sure the OS is preemptive? I.e. a higher priority task can interrupt an other task at any time?

Is there `get_milliseconds()` or similar function in the OS? If so you can use it instead of `lv_tick_inc()`. See [here](https://github.com/lvgl/lvgl/blob/bcffe08b36e9dd9fcd91aaf598f37f78486e28cc/lv_conf_template.h#L79-L85).

**Comment by HaoboGu** [comment]
I tried `LV_TICK_CUSTOM`, the FPS is correct then. Maybe the timer thread was not running as I imagined. Anyway, the bug is fixed, thanks @kisvegabor

**Comment by HaoboGu** [comment]
Finally I figured it out -- I set a same preemption threshold of main thread as the lvgl timer thread, then the timer thread couldn't interrupt main thread to increase the tick. Thanks again @kisvegabor for your help!
