### ISSUE TITLE
lv_style_set_bg_grad no effect when using SDL2 GPU

### ISSUE THREAD

**Issue by LuWB** [kisvegabor/lvgl#3848]
### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by kisvegabor** [comment]
cc @mariotaku

**Comment by mariotaku** [comment]
Which branch should I use for SDL2 backend based changes by the way?
