### ISSUE TITLE
LV_USE_DRAW_MASKS and LV_USE_DRAW_SW missing from Kconfig, unable to use meter widget with menuconfig

### ISSUE THREAD

**Issue by mak0t0san** [kisvegabor/lvgl#3849]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I get the following error message when trying to build:
```
components/lvgl/src/widgets/meter/lv_meter.h:22:2: error: #error "lv_meter: Complex drawing is required. Enable it in lv_conf.h (LV_USE_DRAW_MASKS 1)"
```

When using `menuconfig` to configure LVGL, there is no option to enable Use Draw Masks. I confirmed that this is not present in the Kconfig file.

Also, `LV_USE_DRAW_SW` is missing as well

### To Reproduce

Ensure that meter is an enabled widget
![image](https://user-images.githubusercontent.com/987722/205421172-636c213b-58bf-4a4a-910c-5061ec348343.png)

```c
// Simply including lvgl.h and building will cause a build failure
#include "lvgl.h"
```
### Expected behavior

Expect to be able to use meter and enable `LV_USE_DRAW_MASKS` from menuconfig

**Comment by kisvegabor** [comment]
Please do not use the `master` branch for now. See the README: 
![image](https://user-images.githubusercontent.com/7599318/205844719-1ceadfe7-58a2-4417-8a8e-0fcaab04c542.png)
