### ISSUE TITLE
Grid navigation + encoder + button BUG

### ISSUE THREAD

**Issue by Wangs121** [kisvegabor/lvgl#3854]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html) and there is a similar bug [Encoder long-press on one-checked-button-matrix makes selection without visually selecting button](https://github.com/lvgl/lvgl/issues/3613)

### Describe the bug

I run [lv_example_gridnav_3.c](https://github.com/lvgl/lvgl/blob/be27e3ca6f69946a42c020e405b57d95b8cde2b3/examples/others/gridnav/lv_example_gridnav_3.c) with encoder on my device.
When long press encoder button, encoder get a 'back' command and navigate back to 'cont_main' but button still kept pressed state.
### To Reproduce

```c
    lv_obj_t * cont_main = lv_obj_create(lv_scr_act());
    lv_gridnav_add(cont_main, LV_GRIDNAV_CTRL_ROLLOVER | LV_GRIDNAV_CTRL_SCROLL_FIRST);

    /*Only the container needs to be in a group*/
    lv_group_add_obj(lv_group_get_default(), cont_main);

    /*Use flex here, but works with grid or manually placed objects as well*/
    lv_obj_set_flex_flow(cont_main, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_style_bg_color(cont_main, lv_palette_lighten(LV_PALETTE_BLUE, 5), LV_STATE_FOCUSED);
    lv_obj_set_size(cont_main, lv_pct(80), LV_SIZE_CONTENT);

    lv_obj_t * btn;
    lv_obj_t * label;
    //...
    lv_obj_t * cont_sub2 = lv_obj_create(cont_main);
    lv_gridnav_add(cont_sub2, LV_GRIDNAV_CTRL_ROLLOVER);
    /*Only the container needs to be in a group*/
    lv_group_add_obj(lv_group_get_default(), cont_sub2);

    lv_obj_add_event_cb(cont_sub2, cont_sub_event_cb, LV_EVENT_KEY, NULL);
    //...
    btn = lv_btn_create(cont_sub2);
    lv_group_remove_obj(btn);
    label = lv_label_create(btn);
    lv_label_set_text(label, "Button 3");

    btn = lv_btn_create(cont_sub2);
    lv_group_remove_obj(btn);
    label = lv_label_create(btn);
    lv_label_set_text(label, "Button 4");
```
### Expected behavior

lone press encoder button ,navigate back and button recover to default state.

**Comment by kisvegabor** [comment]
Sorry that it took so long but I've just pushed a fix to both the `release/v8.3` and `master` branches.
