### ISSUE TITLE
lodepng_zlib_decompressv failure

### ISSUE THREAD

**Issue by Duolabs** [kisvegabor/lvgl#3855]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [] Update lvgl to the latest version
- [] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
**lodepng_zlib_decompressv** returns error 83 generated by function **inflatev** when loading the a .png file from drive. 
By digging the nested code it fails in function lodepng_zlib_decompressv with error 83 while running in inflatev.
Afterward the in function zlib_decompress the *out is NULL and fails in  **zlib_decompress** and so on. 
The final result is a "no data" on the screen.
I am using version 8.3.0 of LVGL in ESP32 managed component.
The same .png image if converted in .bin (with online converter) works beautifully.

### To Reproduce
```c
lv_img_set_src(ui.mage_1, "S:/mypicture.png");
```

### Expected behavior
If lodepng is correctly loaded and initialized the png image should be loaded from external file .png

**Comment by glory-man** [comment]
https://github.com/lvgl/lvgl/blob/32948428c396edfb74bcb3189e9c7f02319899ed/src/libs/png/lodepng.c#L6749

> case 83:
            return "memory allocation failed";

You have no enough RAM to decompress image. As far as I understand online converter png->bin already decompress png-file and you have image map stored in ROM as a result (bin file). While lvgl-png-decompress need a lot of RAM: 
1. store png-file content for decompressor (which will be freed after decompression)
2. unpacked data

**Comment by Duolabs** [comment]
It is correct. It was a RAM issue with the ESP module I had to activate the external SPI RAM to get it to work.
Issue closed.
