### ISSUE TITLE
amoled display spi dis location

### ISSUE THREAD

**Issue by Maucke** [kisvegabor/lvgl#3862]
![1A73B40C-6C80-4901-9A72-696570DF5C33](https://user-images.githubusercontent.com/37175026/206735032-830fc660-aab1-4657-8060-25050fb48f9d.png)
As shown in the figure, sometimes it is displayed normally and sometimes it is displayed obliquely

thanks

**Comment by kisvegabor** [comment]
Probably it's an off by in issue in width calculation in `flush_cb`.
