### ISSUE TITLE
This line will cause some problem in some special cases.

### ISSUE THREAD

**Issue by BenXie81** [kisvegabor/lvgl#3866]
https://github.com/lvgl/lvgl/blob/101400158e0bc93daee0f812b7694110ff733cf9/src/widgets/dropdown/lv_dropdown.c#L411

For example, If there're two items, one is: abc followed by an item: abcdef, and when I invoke dropdown_get_option_index(obj, "abcdef"); to get the item, it will give me the index of the abc item.

I've changed this line to :

if(strlen(option) == char_i && memcmp(start, option, char_i) == 0) return opt_i;

to make the function return the right one.

**Comment by kisvegabor** [comment]
Great catch! Could you send a Pull request?
