### ISSUE TITLE
LV_ALIGN_* missing from the documentation website

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#3875]
As the title says. Missing an enumeration in the online documentation.

**Comment by kisvegabor** [comment]
It's documented here: https://docs.lvgl.io/master/overview/coords.html#align

**Comment by kdschlosser** [comment]
Same deal as the other issue. There is no API listed for it.

**Comment by kisvegabor** [comment]
It's not that clear as the events because `LV_ALIGN_*` is part of [lv_area.h](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_area.h) which contains a lot of low leven functions. It would messy to to show the whole file. 

I'll try to reorganize it in v9.
