### ISSUE TITLE
Arc alpha problem

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#3876]
### Perform all steps below and tick them with [x]
- [ x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Screenshots or video

![image](https://user-images.githubusercontent.com/10932297/208546527-963cb603-4337-4d35-a8ce-c5767efe7daa.png)

**Comment by kisvegabor** [comment]
It's a know issue, in v9 we are working on a solution.

**Comment by kdschlosser** [comment]
OK cool deal!
