### ISSUE TITLE
LV_EVENT_* enum missing from documentation

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#3877]
As the title states...

**Comment by kisvegabor** [comment]
It's documented here: https://docs.lvgl.io/master/overview/event.html#event-codes

**Comment by kdschlosser** [comment]
There is no API listed for it. There is a slew of stuff that is not listed under the API sections.

**Comment by kisvegabor** [comment]
I've just added a section for it: https://github.com/lvgl/lvgl/commit/53dd64677037e4f146a57712de16a47c16c15eef
