### ISSUE TITLE
lv_snapshot_take returns a 32 bit image regardless of colour format

### ISSUE THREAD

**Issue by MrWFoulkes** [kisvegabor/lvgl#3880]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

lv_snapshot_take returns a 32 bit image regardless of whether colour format is set to LV_IMG_CF_TRUE_COLOR or LV_IMG_CF_TRUE_COLOR_ALPHA. One would expect LV_IMG_CF_TRUE_COLOR to return a 24 bit image.

Also, the data_size field of the resulting image struct is always zero, otherwise I would've used that to work out how many bits the image was.

### To Reproduce
Create a screenshot using colour format LV_IMG_CF_TRUE_COLOR, and try encode it with both lodepng_encode24_file and lodepng_encode32_file.

```c
    /* Need to #include "lvgl/src/extra/libs/png/lodepng.h" and setup working directory as drive A in lv_conf.h */

    //Take screenshot
    lv_img_cf_t colour_format = LV_IMG_CF_TRUE_COLOR;
    lv_img_dsc_t * screenshot = lv_snapshot_take(lv_scr_act(), colour_format);
    
    //encode the screenshot as a PNG using lodePNG
    const unsigned char * image = screenshot->data;
    unsigned int width = screenshot->header.w;
    unsigned int height = screenshot->header.h;
    lodepng_encode24_file("A:screenshot24.png", image, width, height); //produces garbled image
    lodepng_encode32_file("A:screenshot32.png", image, width, height); //produces correct image
```

### Expected behavior

If colour_format of screenshot is LV_IMG_CF_TRUE_COLOR, lodepng_encode24_file should encode it correctly. data_size should be 3 * w * h for LV_IMG_CF_TRUE_COLOR and 4 * w * h for LV_IMG_CF_TRUE_COLOR_ALPHA.

**Comment by kisvegabor** [comment]
Sorry for the late reply. Somehow I missed this issue. :slightly_frowning_face: 

In v8 "normal" 24 bit (RGB888) format is not supported, only XRGB8888 (alpha is always 255). In v9 it will be updated and  native rendering in RGB888 will work too.
