### ISSUE TITLE
Wrong number of gif cycles

### ISSUE THREAD

**Issue by yuqingli05** [kisvegabor/lvgl#3883]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Wrong number of gif cycles

I tested four situations.

1、gif->loop_ count does not exist (no application ext). Web page display is single. Adobe Photoshop displays a single time. The lvgl display is single.
![none](https://user-images.githubusercontent.com/106426122/209470311-60d4d7ad-30a2-4c37-b15c-157ff130d785.gif)

2、gif->loop_ count is 1. The web page is displayed in a loop twice. Adobe Photoshop display cycles twice. The lvgl display is single.
![1](https://user-images.githubusercontent.com/106426122/209470316-d69acd31-2a2a-4887-94f3-a736601ff38e.gif)

3、gif->loop_ count is 2. The web page display cycles 3 times. Adobe Photoshop display cycles 3 times. Lvgl shows an infinite loop.
![2](https://user-images.githubusercontent.com/106426122/209470317-3605ea7e-4d95-49b7-9bbc-17f7b066e791.gif)

4、gif->loop_ count is 0. Web page display is an infinite loop. Adobe Photoshop shows an infinite loop. The lvgl display is single.
![0](https://user-images.githubusercontent.com/106426122/209470320-ee30da76-ee24-432b-9054-219e6bb1913e.gif)

However, web pages, winddows image apps and Android image apps are different. Even once, app are all infinite loops. I don't know which is more standard.

**Comment by kisvegabor** [comment]
Closing as the PR is merged.
