### ISSUE TITLE
Fix the action to upload recent tag version of LVGL to Espressif component registry

### ISSUE THREAD

**Issue by KoLoong** [kisvegabor/lvgl#3885]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The action to upload LVGL to Espressif component registry doesn't take effect. The recent tag version is v8.3.4, but the version in Espressif component registry is still v8.3.0, upload 5 months ago. https://components.espressif.com/components/lvgl/lvgl

**Comment by kisvegabor** [comment]
Closing as the PR is merged.
