### ISSUE TITLE
'LV_ATTRIBUTE_LARGE_CONST' does not name a type error when trying to use the online image converter in Arduino

### ISSUE THREAD

**Issue by ljunquera** [kisvegabor/lvgl#3893]
### Introduce the problem
I am using Arduino, downloaded the library, and was following [these directions](https://docs.lvgl.io/latest/en/html/overview/image.html) to use the [online image converter](https://lvgl.io/tools/imageconverter) for generation of an image file.

When I copy the contents of the resulting file into a blank Arduino h file and try to compile I get this error:

'LV_ATTRIBUTE_LARGE_CONST' does not name a type

On this line:

`const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_ICON-1 uint8_t icon-1_map[] = {`

### Examples and cases
The directions are to:

1. Copy the resulting C file into your LVGL project
2. In a C file of your application declare the image as: LV_IMG_DECLARE(my_image_name);
3. Set the image as the source of an image object: lv_img_set_src(img, &my_image_name);
4. Checkout the [Docs](https://docs.lvgl.io/master/overview/image.html) for more details.

### Suggested solution
I'm just going to have to see if there is a good Arduino example but I thought following the directions was the best option. If anybody has done this before, please let me know what I'm doing wrong.

**Comment by kisvegabor** [comment]
Can you  share your ino file?
