### ISSUE TITLE
driver register issue (lvgl 8.3)

### ISSUE THREAD

**Issue by denisdemaisbr** [kisvegabor/lvgl#3894]
hi all

today a start a new fresh project/aproach to know lvgl better

started a new project using lv_port_linux_frame_buffer template
some beers after I then realized that when reversing the order the input driver did not respond

# works

...
**lv_disp_drv_init(&disp_drv);**
disp_drv.flush_cb = &my_disp_flush;
disp_drv.draw_buf = &draw_buf;
disp_drv.hor_res = MY_DISP_HOR_RES;
disp_drv.ver_res = MY_DISP_VER_RES;
lv_disp_drv_register(&disp_drv);

**my_indev_drv_init();** // dummy function
lv_indev_drv_init(&indev_drv);
indev_drv.type = LV_INDEV_TYPE_POINTER;
indev_drv.read_cb = &my_indev_drv_read;
lv_indev_drv_register(&indev_drv);
...

# dont works
**my_indev_drv_init();**
lv_indev_drv_init(&indev_drv);
indev_drv.type = LV_INDEV_TYPE_POINTER;
indev_drv.read_cb = &my_indev_drv_read;
lv_indev_drv_register(&indev_drv);

**lv_disp_drv_init(&disp_drv);**
disp_drv.flush_cb = &my_disp_flush;
disp_drv.draw_buf = &draw_buf;
disp_drv.hor_res = MY_DISP_HOR_RES;
disp_drv.ver_res = MY_DISP_VER_RES;
lv_disp_drv_register(&disp_drv);
...

**Comment by kisvegabor** [comment]
It happens because the input devices are bound to a display. If you create a display first, the input device will be automatically attached to it later. 

However if the input device is crated first there is no display where to attach it automatically so you need to do it manually later with:
```c
  lv_disp_t * disp = lv_disp_drv_register(&disp_drv);

  indev_drv.disp = disp;
```
