### ISSUE TITLE
using about lv_obj_set_ext_click_area

### ISSUE THREAD

**Issue by seadog-www** [kisvegabor/lvgl#3900]
### Introduce the problem

In V7, void lv_obj_set_ext_click_area(lv_obj_t * obj, lv_coord_t left, lv_coord_t right, lv_coord_t top, lv_coord_t bottom). We can set different value for left, right, top and bottom， which is very flexible.
However, in V8, void lv_obj_set_ext_click_area(lv_obj_t * obj, lv_coord_t size). The value of left, right, top and bottom must be same.

### Suggested solution

I think it is useful and flexible that the value of left, right, top and bottom can be different.

**Comment by kisvegabor** [comment]
I've simplified it to save some bytes of RAM in the object. If you need more precise control you can use `LV_EVENT_HIT_TEST`. See here https://docs.lvgl.io/master/overview/event.html#input-device-events
