### ISSUE TITLE
lv_demo_benchmark - incorrect FPS results (8.3)

### ISSUE THREAD

**Issue by tdjastrzebski** [kisvegabor/lvgl#3933]
`lv_demo_benchmark()` shows all the FPS results being either 33 or 34k.
LVGL 8.3 the latest dev, GCC compiler, STM32F769NI-DISCO, lvgl tick frequency=200Hz (5ms)
![IMG_8893](https://user-images.githubusercontent.com/7325277/212686927-38c84c57-8d2f-438c-aa16-8dc794998c96.JPG)

**Comment by baldhead69** [comment]
I think it's right.

The fps is not calculate to full screen render + flush.

https://github.com/lvgl/lvgl/tree/release/v8.3/demos/benchmark

"Note that it can result in very high FPS results for simple cases. E.g. if some simple rectangles are drawn in 5 ms, the benchmark will tell it's 200 FPS. So it ignores LV_DISP_REFR_PERIOD which tells LVGL how often it should refresh the screen. In other words, the benchmark shows the FPS from the pure rendering time."

**Comment by baldhead69** [comment]
The STM32F769NI chip has hardware graphics accelerators, but these fps seem a bit high anyway.

"Graphics
Chrom-ART Accelerator (DMA2D), graphical hardware accelerator enabling enhanced graphical user interface
Hardware JPEG codec
LCD-TFT controller supporting up to XGA resolution
MIPI® DSI host controller supporting up to 720p 30 Hz resolution"

**Comment by tdjastrzebski** [comment]
Thanks, maybe those values are correct then, but they seem to be a bit odd. Why only two values?
DMA2D is not used by LVGL, unless one explicitly enables it in **lv_conf.h** - `LV_USE_GPU_STM32_DMA2D`.
DMA2D was not well supported, I just proposed a significant rework - see PR #3904
LCD-TFT support (LTDC) and MIPI-DSI is a different story, they do not speed up rendering itself, just transfer to a display once screen bytes are rendered.

**Comment by GorgonMeducer** [comment]
This issue probably has been fixed in v9. Can you please verify it in the master branch?

**Comment by kisvegabor** [comment]
Usually it happens if you don't call `lv_tick_inc()` from an interrupt. Could you check it?

**Comment by tdjastrzebski** [comment]
`lv_tick_inc()` is called and I verified that it is called every 5 ticks. [complete test code](https://github.com/tdjastrzebski/STM32F769I-DISCO-LVGL/blob/2159eb4d328d637628ec3cd0872428ee4051d915/master.cpp#L116)

**Comment by kisvegabor** [comment]
Exactly this configuration causes this kind of issues. This way `lv_tick_inc()` cannot tick-ing while `lv_task_handler` is working. So anything happens in `lv_task_handler` can not know how long an operation lasted. 

On STM all you need to do is this:

https://github.com/lvgl/lv_port_stm32f769_disco/blob/c567b238d629b4dbb1164a43392db64e69e48cc9/src/stm32f7xx_it.c#L39-L46

And call `lv_task_handler()` somewhere in a lower priority interrupt or main function.

**Comment by tdjastrzebski** [comment]
I see, so the problem is `lv_tick_inc()` and `lv_task_handler()` are called from within the interrupt context?
The above does not mean the same interrupt handler. Probably the same handler can be used, as long as it is a different interrupt context and `lv_tick_inc()` has higher priority. Is that right?
Anyway, thanks, it helped.

**Comment by kisvegabor** [comment]
> I see, so the problem is lv_tick_inc() and lv_task_handler() are called from within the interrupt context?

There is no problem with the interrupt in general. The only thing matters is the `lv_tick_inc()` should be called from a higher priority to keep it ticking while `lv_task_handler` is running.

**Comment by tdjastrzebski** [comment]
Interesting that fixing this issue noticeably speeded up lv_demo_music intro/splash screen rays rendering and lv_demo_widgets responsiveness.

**Comment by kisvegabor** [comment]
It's because let's rendering took 40 ms in `lv_task_handler` but you only added 5 in `lv_tick_inc`. So the animations thought that on 5ms elapsed while it was 40ms.
