### ISSUE TITLE
Files that need to include "LV_LVGL_H_INCLUDE_SIMPLE"

### ISSUE THREAD

**Issue by baldhead69** [kisvegabor/lvgl#3938]
Hi,

The following files need to include "LV_LVGL_H_INCLUDE_SIMPLE":

* animimg001.c
* animimg002.c
* animimg003.c
* img_caret_down.c

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "../../lvgl.h"
#endif

lvgl version:  v9.0.0 dev

I think it's related too: https://github.com/lvgl/lvgl/issues/3930

https://www.microchip.com/forums/m/tm.aspx?m=1224283&fp=1

**Comment by baldhead69** [comment]
https://github.com/lvgl/lvgl/issues/3930

**Comment by kisvegabor** [comment]
I don't get it. From these files are part of LVGL and relative to them  `lvgl.h` wil be always on the same place. Why/How does the suggest solve the issue?

For Microchip's answer:
> These errors occur because the linking step is very large. 

LVGL is large, but not so large to break a compiler or linker. Really xs32 cannot build and link ~500 C files?

**Comment by baldhead69** [comment]
In microchip forum( "https://www.microchip.com/forums/m/tm.aspx?m=1224283&fp=1" ) maybe you are no seeing the image(microchip buggish forum).

"In Windows, you have a max command line length of 8191 chars. When linking long programs, the link line might go over this limit. XC32 provides response file capabilities. Check this option to create a makefile that uses a response file for the link step."

I checked "use response file to link".

Image below:

![my_image](https://user-images.githubusercontent.com/17574492/213207433-4394cedb-1cc9-4494-a942-c1c24928de21.png)

**Comment by baldhead69** [comment]
> I don't get it. From these files are part of LVGL and relative to them `lvgl.h` wil be always on the same place. Why/How does the suggest solve the issue?

For me it didn't work with:
#include "../../lvgl.h"

If i put, worked:
#include "lvgl.h"
 
So i think using this, is better, and worked to me too( i declareted "LV_LVGL_H_INCLUDE_SIMPLE" in xc32 preprocessor macros ):
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "../../lvgl.h"
#endif

**Comment by baldhead69** [comment]
@kisvegabor 

I downloaded the lvgl-master now and:

```c
../src/my_Files/graphic_Interface/lvgl/tests/src/test_assets/test_animimg001.c:1:10: fatal error: ../../lvgl.h: No such file or directory
 #include "../../lvgl.h"
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [build/default/production/_ext/443351157/test_animimg001.o] Error 255
make[2]: *** Waiting for unfinished jobs....
../src/my_Files/graphic_Interface/lvgl/tests/src/test_assets/test_animimg002.c:1:10: fatal error: ../../lvgl.h: No such file or directory
 #include "../../lvgl.h"
          ^~~~~~~~~~~~~~
compilation terminated.
../src/my_Files/graphic_Interface/lvgl/tests/src/test_assets/test_animimg003.c:1:10: fatal error: ../../lvgl.h: No such file or directory
 #include "../../lvgl.h"
          ^~~~~~~~~~~~~~
compilation terminated.
../src/my_Files/graphic_Interface/lvgl/tests/src/test_assets/test_img_caret_down.c:1:10: fatal error: ../../lvgl.h: No such file or directory
 #include "../../lvgl.h"
          ^~~~~~~~~~~~~~
```

After putting this, in this error files above, the compilation worked now:

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "../../lvgl.h"
#endif


Thank's for https://github.com/lvgl/lvgl/issues/3930#issuecomment-1386665479

**Comment by baldhead69** [comment]
Benchmark testing are crashing, and i can't debug, because:  

```c
"C:\Microchip\xc32\v4.21\bin\xc32-gcc.exe"  @nbproject/default.debug 
nbproject/Makefile-default.mk:6767: recipe for target 'dist/default/debug/LCD.X.debug.elf' failed
make[2]: Leaving directory 'C:/Users/Rangel/Desktop/Mplab-Progs/pic32mz-teste/firmware/LCD.X'
nbproject/Makefile-default.mk:85: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/Rangel/Desktop/Mplab-Progs/pic32mz-teste/firmware/LCD.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
Format of option is not correct (section)
collect2.exe: error: ld returned 1 exit status
make[2]: *** [dist/default/debug/LCD.X.debug.elf] Error 255
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 36s)
```

// I think worked with LV_MEM_SIZE 32 kBytes.
lv_demo_benchmark(LV_DEMO_BENCHMARK_MODE_RENDER_AND_DRIVER);  

// Worked with LV_MEM_SIZE 64 KBytes not with 32 kBytes.
lv_demo_benchmark(LV_DEMO_BENCHMARK_MODE_REAL);  

// crashing even with LV_MEM_SIZE 128 kBytes.
lv_demo_benchmark(LV_DEMO_BENCHMARK_MODE_RENDER_ONLY);

**Comment by kisvegabor** [comment]
I really didn't see the image. 

I'v just noticed that `#include "../../lvgl.h"` is off by one level in the test asset images. I wonder how it worked so far. Please try with `#include "../../../lvgl.h"`

**Comment by baldhead69** [comment]
> I really didn't see the image. 
> 
> I'v just noticed that `#include "../../lvgl.h"` is off by one level in the test asset images. I wonder how it worked so far. Please try with `#include "../../../lvgl.h"`
> 

With include simple already worked.


#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "../../lvgl.h"
#endif


Or only

#include "lvgl.h"

**Comment by kisvegabor** [comment]
I'd like to understand why it works and `#include "../../../lvgl.h"` should be the correct way of including it.

**Comment by baldhead69** [comment]
My opinion.

I think it's better like this:

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "../../../lvgl.h"
#endif

**Comment by baldhead69** [comment]
> I'd like to understand why it works and `#include "../../../lvgl.h"` should be the correct way of including it.

#include "lvgl.h" work, because i declareted "LV_LVGL_H_INCLUDE_SIMPLE" in xc32 preprocessor macros.

**Comment by kisvegabor** [comment]
But it's an extra step that the users can miss. `#include "../../../lvgl.h"` should work out of the box without any extra config.
