### ISSUE TITLE
NXP PXP GPU and VG-Lite GPU on imx8 mini platform

### ISSUE THREAD

**Issue by kay54068** [kisvegabor/lvgl#3939]
HI ,

One question about the NXP GPU support. 

The LV_USE_GPU_NXP_PXP abd LV_USE_GPU_NXP_VG_LITE macro  the remark is note support `iMX RTxxx platforms`. 
IMX8 mini have PXP and VG_LITE GPU  also , it can support the `IMX8 mini platform` ?

thanks.

**Comment by kisvegabor** [comment]
cc @nicusorcitu

**Comment by nicusorcitu** [comment]
imx8M mini have VSI 2D GPU. It does not have PXP or VGLite GPU. So the LVGL acceleration cannot be supported.
