### ISSUE TITLE
[lv_chart] Handling zoom factor being less than 256

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#3941]
### Introduce the problem
Docs states that `factor` can't be less than 256, what should `lv_chart_set_zoom_y` and `lv_chart_set_zoom_x` functions do when trying to do `factor < 256`? Return without doing anything?

![imagen](https://user-images.githubusercontent.com/11037705/213901445-e13156e6-f01b-4cd2-9bb2-49215daa638d.png)

Also the docs mention `LV_ZOOM_NONE`, but i can't find it's definition.
![imagen](https://user-images.githubusercontent.com/11037705/213901575-cd7b3995-0370-4771-9bee-70428e40852b.png)

### Examples and cases
Found about it when doing the minimal test case for both functions, I was expecting not to be able to set `factor` to 128.
![imagen](https://user-images.githubusercontent.com/11037705/213901456-228b6837-58e0-4575-a2d2-c427b4930c23.png)

### Suggested solution
Check `factor` and return if it's less than 256.

**Comment by kisvegabor** [comment]
I'd set to the zoom to 256 if the user tries to set < 256 value.

**Comment by C47D** [comment]
> I'd set to the zoom to 256 if the user tries to set < 256 value.

Ok, I'll do that. What about `LV_ZOOM_NONE` where can I declare it? `lv_chart.h` looks ok for me.

**EDIT**
Done it in b544990b122d7c2f01d3d800ec4e5c59189c154c and 41eaf3dc3691ebef23945c3fc8c3e80f26534881, I'll close this issue once the pull request gets merged.

**Comment by kisvegabor** [comment]
> Ok, I'll do that. What about LV_ZOOM_NONE where can I declare it? lv_chart.h looks ok for me.

In `master` we have `LV_IMG_ZOOM_NONE` now which is not a good fit for the chart. Could you refactor `LV_IMG_ZOOM_NONE` back to `LV_ZOOM_NONE` so that we can use it for both the images and the charts. It's in `misc/lv_style.h`.


> Done it in https://github.com/lvgl/lvgl/commit/b544990b122d7c2f01d3d800ec4e5c59189c154c and https://github.com/lvgl/lvgl/commit/41eaf3dc3691ebef23945c3fc8c3e80f26534881.

It seems something is wrong with these commits.

![image](https://user-images.githubusercontent.com/7599318/213998407-0fbc48e5-6252-4458-933b-a08a48d493d2.png)

**Comment by C47D** [comment]
> Could you refactor LV_IMG_ZOOM_NONE back to LV_ZOOM_NONE so that we can use it for both the images and the charts. It's in misc/lv_style.h.

Sure, I can update it in a separated pull request? I don't know how long it will take me to finish the chart tests

> It seems something is wrong with these commits.

Maybe github are searching in this repo and not mine, here's the link to the branch where I'm doing the updates https://github.com/C47D/lvgl/tree/test/chart

**Comment by kisvegabor** [comment]
> Sure, I can update it in a separated pull request? I don't know how long it will take me to finish the chart tests

A separate PR would be welcome. Thank you!

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
Fixed in #4005
