### ISSUE TITLE
How to get the ON/OFF state of a switch?

### ISSUE THREAD

**Issue by cuishuang413** [kisvegabor/lvgl#3943]
### Introduce the problem

Hello, how to get the ON/OFF state of a switch?
### Examples and cases

On this page: https://lvgl.io/docs/latest/en/html/widgets/switch.html#overview
I see that I should be able to use "lv_switch_get_state" to get the state of a switch.
So I tried this:
bool sw_state = lv_obj_get_state(sw1);
But I got: 'lv_switch_get_state' was not declared in this scope

### Suggested solution

I have no suggestion.

**Comment by kisvegabor** [comment]
Hi,

See here: https://docs.lvgl.io/master/widgets/switch.html#change-state
