### ISSUE TITLE
How to implement "home" gesture in a scrollable menu?

### ISSUE THREAD

**Issue by 952736147** [kisvegabor/lvgl#3944]
### Introduce the problem

When using a smartphone, we use gesture "up" to return to the desktop
however in LVGL, gesture will not be triggerred if an object is being scrolled.

### Examples and cases

e.g. at a long menu such as "Settings", what is expected to happen is:
you swipe the screen up from below, then the active app exits and returns to desktop
but in lvgl what actually happen is:
you swipe the screen up from below, then the long menu "Settings" starts to scroll
it is very hard and  counterintuitive to implement "home" gesture in lvgl

### Suggested solution

i have though of a solution that is:
add a scroll event call back to the scrollable object
and when it starts to scroll, check the start coordinate
if the coordinate is near the bottom of the screen
set the object not scrollable in the call back
but i think this solution is complicated and  not elegant

so could you please add more function to scroll/gesture API? i really want to solve this problem with just a lvgl func

**Comment by kisvegabor** [comment]
I'd do something like this:
```c
static void home_event_cb(lv_event_t * e)
{
    lv_indev_t * indev = lv_event_get_indev(e);
    if(lv_indev_get_gesture_dir(indev) == LV_DIR_TOP) {
        printf("Home\n");
    }
}

void lv_example_home(void)
{
    /*Create a list*/
    lv_obj_t * list1 = lv_list_create(lv_scr_act());
    lv_obj_set_size(list1, lv_pct(100), lv_pct(100));
    lv_obj_center(list1);

    /*Add buttons to the list*/
    for(int i = 0; i < 50; i++) {
        lv_list_add_btn(list1, LV_SYMBOL_CLOSE, "Close");
    }

    lv_obj_t * bottom_obj = lv_obj_create(lv_scr_act());
    lv_obj_set_size(bottom_obj, lv_pct(100), 50);
    lv_obj_align(bottom_obj, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_clear_flag(bottom_obj, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_obj_add_event_cb(bottom_obj, home_event_cb, LV_EVENT_GESTURE, NULL);
    lv_obj_set_style_bg_opa(bottom_obj, LV_OPA_50, 0);
}
```
Of course you can make `bottom_obj` fully transparent. 

![gh1](https://user-images.githubusercontent.com/7599318/214548013-e67aee2d-bae9-41e6-922a-dcdd621576f5.gif)

**Comment by 952736147** [comment]
> I'd do something like this:
> 
> ```c
> static void home_event_cb(lv_event_t * e)
> {
>     lv_indev_t * indev = lv_event_get_indev(e);
>     if(lv_indev_get_gesture_dir(indev) == LV_DIR_TOP) {
>         printf("Home\n");
>     }
> }
> 
> void lv_example_home(void)
> {
>     /*Create a list*/
>     lv_obj_t * list1 = lv_list_create(lv_scr_act());
>     lv_obj_set_size(list1, lv_pct(100), lv_pct(100));
>     lv_obj_center(list1);
> 
>     /*Add buttons to the list*/
>     for(int i = 0; i < 50; i++) {
>         lv_list_add_btn(list1, LV_SYMBOL_CLOSE, "Close");
>     }
> 
>     lv_obj_t * bottom_obj = lv_obj_create(lv_scr_act());
>     lv_obj_set_size(bottom_obj, lv_pct(100), 50);
>     lv_obj_align(bottom_obj, LV_ALIGN_BOTTOM_MID, 0, 0);
>     lv_obj_clear_flag(bottom_obj, LV_OBJ_FLAG_GESTURE_BUBBLE);
>     lv_obj_add_event_cb(bottom_obj, home_event_cb, LV_EVENT_GESTURE, NULL);
>     lv_obj_set_style_bg_opa(bottom_obj, LV_OPA_50, 0);
> }
> ```
> 
> Of course you can make `bottom_obj` fully transparent.
> 
> ![gh1](https://user-images.githubusercontent.com/7599318/214548013-e67aee2d-bae9-41e6-922a-dcdd621576f5.gif) [ ![gh1](https://user-images.githubusercontent.com/7599318/214548013-e67aee2d-bae9-41e6-922a-dcdd621576f5.gif) ](https://user-images.githubusercontent.com/7599318/214548013-e67aee2d-bae9-41e6-922a-dcdd621576f5.gif) [ ](https://user-images.githubusercontent.com/7599318/214548013-e67aee2d-bae9-41e6-922a-dcdd621576f5.gif)

Thank you for your good advise. I will work on it and try to support more gestures. Thanks again

**Comment by kisvegabor** [comment]
You're welcome. :slightly_smiling_face: 

Not that we are using GitHub for development related discussions and how-to questions should be asked in the Forum.

So I close this issue now.
