### ISSUE TITLE
lv_obj_get_height func does not work on widget "keyboard"

### ISSUE THREAD

**Issue by 952736147** [kisvegabor/lvgl#3953]
### Perform all steps below and tick them with [x]
- [√ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [√ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [ √] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

you can set the height of a keyboard with lv_obj_set_height, and that works well
but when you use lv_obj_get_height on a keyboard, it always returns 0
**my lvgl version is 8.3**
### To Reproduce

lv_obj_t* keyboard = lv_keyboard_create(scr);
    lv_obj_set_height(keyboard,120);
    lv_obj_set_align(keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(keyboard, lv_obj_get_height(keyboard));
    printf("%d", lv_obj_get_height(keyboard));

### Expected behavior

it returns the height of the keyboard, but in fact not

**Comment by kisvegabor** [comment]
You can find the explanation [here](https://docs.lvgl.io/master/overview/coords.html#postponed-coordinate-calculation).
