### ISSUE TITLE
long_press_rep_time is nonexistant

### ISSUE THREAD

**Issue by daywink** [kisvegabor/lvgl#3954]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

`'lv_indev_drv_t {aka struct _lv_indev_drv_t}' has no member named 'long_press_rep_time'

### To Reproduce

```c
  lv_indev_drv_init(&enc_indev_drv);
  enc_indev_drv.type = LV_INDEV_TYPE_ENCODER;
  enc_indev_drv.read_cb = enc_read;
  enc_indev_drv.long_press_rep_time = 5; // This line gives an error on compilation
  lv_indev_drv_register(&enc_indev_drv);
```

### Expected behavior

Expected to be able to change the value, but it is nonexistent.

### Screenshots or video

![Screenshot from 2023-01-30 16-51-17](https://user-images.githubusercontent.com/65610123/215510756-a8225a2b-77d1-4e51-9a64-d300b16229ac.png)
![Screenshot from 2023-01-30 16-51-27](https://user-images.githubusercontent.com/65610123/215510762-7c647d2d-4a1d-4938-a86e-d97a32bdb63c.png)

**Comment by kisvegabor** [comment]
It should be `long_press_repeat_time`. I've fixed it in the docs.
