### ISSUE TITLE
Discussion of whether `lvgl` border needs to shrink the `clip area` for children

### ISSUE THREAD

**Issue by W-Mai** [kisvegabor/lvgl#3958]
### Introduce the problem

Note that lvgl adds the width of the border to the inward offset, but does not subtract the area of the border when drawing the children. This results in an unexpected overlap between the border and the children when the border is translucent.
### Examples and cases

After making the border transparent

The unexpected:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/24841247/215655558-7754029a-2517-4d14-b2be-ea5e28c51463.png">

The expected:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/24841247/215655525-67a68f66-b6a7-4ed7-84ee-2aeee102f9a5.png">

### Suggested solution

https://github.com/lvgl/lvgl/blob/837f5035923e9ee782fb3663cbef379c78f201c2/src/core/lv_refr.c#L162-L173

make changes like this (Not the final code)

```cpp
    lv_area_t clip_coords_for_children;
    bool refr_children = true;
    if(lv_obj_has_flag(obj, LV_OBJ_FLAG_OVERFLOW_VISIBLE)) {
        clip_coords_for_children  = *clip_area_ori;
    }
    else {
        lv_area_t chi_coords = obj->coords;
        lv_coord_t border_width = lv_obj_get_style_border_width(obj, LV_PART_MAIN);
        if (border_width) {
            chi_coords.x1 += border_width;
            chi_coords.x2 -= border_width;
            chi_coords.y1 += border_width;
            chi_coords.y2 -= border_width;
        }

        if(!_lv_area_intersect(&clip_coords_for_children, clip_area_ori, &chi_coords)) {
            refr_children = false;
        }
    }

```

**Comment by kisvegabor** [comment]
It should work as you have described:
```c
  lv_obj_t * cont = lv_obj_create(lv_scr_act());
  lv_obj_set_style_border_width(cont, 30, 0);
  lv_obj_set_style_border_opa(cont, LV_OPA_50, 0);
  lv_obj_set_style_border_color(cont, lv_color_hex(0xff0000), 0);
  lv_obj_set_style_pad_all(cont, 0, 0);
  lv_obj_set_size(cont, 300, 300);

  LV_IMG_DECLARE(img_cogwheel_argb);
  lv_obj_t * img = lv_img_create(cont);
  lv_img_set_src(img, &img_cogwheel_argb);
```
![image](https://user-images.githubusercontent.com/7599318/215715280-42685e4b-9d19-4b23-ab6b-10aa3a5d57ca.png)

With:
```c
  lv_obj_set_style_border_width(cont, 5, 0);
```
![image](https://user-images.githubusercontent.com/7599318/215715360-0857156a-08fb-48b9-a058-5c67f537e093.png)

**Comment by W-Mai** [comment]
What I mean is that when the child is larger than the parent component, scroll the child component under the parent's border, and the child under the border still renders

**Comment by W-Mai** [comment]
The expected:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/24841247/215717118-14cc3ad4-32e5-412d-af2e-30513c83fd27.png">

This screenshot might clarify the problem better

**Comment by kisvegabor** [comment]
There is a `border_post` style property to control when the border should be drawn:
```c
lv_obj_set_style_border_post(cont, true, 0);
```
![image](https://user-images.githubusercontent.com/7599318/215716596-b7b7c895-6d12-4a47-90a1-5a7868ab885b.png)

```c
lv_obj_set_style_border_post(cont, false, 0);
```
![image](https://user-images.githubusercontent.com/7599318/215716833-38c96a83-8f50-4843-9452-b9ccdbfef3f5.png)

Can it solve the issue?

Actually I'm thinking about removing the `border_post` property to make it just work as what the user would expect. But I still need to understand more what would  the "expected way of working".

**Comment by W-Mai** [comment]
> here is a border_post style property to control when the border should be drawn:
> lv_obj_set_style_border_post(cont, true, 0);

Yes, this will hide the children, but if the border is translucent, the border and children will overlap
```cpp
lv_obj_set_style_border_opa(obj0, LV_OPA_30, LV_PART_MAIN);
```


But what I'm expecting is that children won't overlap the border, even though the border is transparent

**Comment by W-Mai** [comment]
> Actually I'm thinking about removing the border_post property to make it just work as what the user would expect. But I still need to understand more what would the "expected way of working".

The way to fix this is to shrink the children's clip region so that it renders only the area within the subtracted border

So, the border drawing post or not will not to be a problem😁

**Comment by kisvegabor** [comment]
It doesn't work well if the border has an inner radius. Like this:
![image](https://user-images.githubusercontent.com/7599318/215724150-43544b67-3f31-43a3-a511-ebf2c560690e.png)

**Comment by W-Mai** [comment]
> It doesn't work well if the border has an inner radius. Like this:
> ![image](https://user-images.githubusercontent.com/7599318/215724150-43544b67-3f31-43a3-a511-ebf2c560690e.png)

Exactly, so can we fix this problem?

**Comment by kisvegabor** [comment]
This is how it works on web:
![gh](https://user-images.githubusercontent.com/7599318/216022561-418923dc-b3c8-42ac-94e3-30bb4dac5b25.gif)
https://codepen.io/kisvegabor/pen/gOjQaNq

We there is a mask on the inner part of the border to clip the content.

It might be a little overkill for most of the embedded systems.

I think `border_post:true` is a good compromise. What do you think?

**Comment by W-Mai** [comment]
Agree

I also think clip causes more computation, which is a bit of a pants drop in an embedded development case

Indeed, `border_post: True` is a good solution

**Comment by kisvegabor** [comment]
Okay. So can we close this issue? :slightly_smiling_face:

**Comment by W-Mai** [comment]
yes😁

**Comment by kisvegabor** [comment]
Anyway, now we see it clearer.
