### ISSUE TITLE
Name conflict between CRC variables and HAL driver #define CRC in STM32U5XXX.

### ISSUE THREAD

**Issue by BillFleming** [kisvegabor/lvgl#3961]
### Perform all steps below and tick them with [x]
- [ X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ X] Update lvgl to the latest version 8.3.4
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html) 
-- Not applicable

### Describe the bug
There is a name conflict between some variables and HAL driver **#define CRC** in STM32U5XXX.

### To Reproduce
Try to build an LVGL project with STM32U5XXX with CRC HAL module included and some code to call MX_CRC_Init() on it.
In this particular case, I had to set "#define LV_USE_GPU_STM32_DMA2D 1" in lv_conf.h to get it to build in the offending code in lodepng.c. Also #include "stm32u5xx_hal.h" was being pulled into lvgl, for the DMA2D requirement.

### Expected behavior
Project will Build.

### Screenshots or video
We get a name conflict with "define CRC CRC_NS" in the STM32 HAL drivers.
I have seen this before on other software and micro-controllers. I believe other STM32s use similar HAL names and I think I have encountered a similar issue with CRC name on Renesas MCUs before also. A variable naming standard should be enforced to avoid using the all caps naming scheme in local variables.
![image](https://user-images.githubusercontent.com/41557749/215889389-efa1c74d-3438-4bb9-a4b0-719ef461a9ab.png)

**Comment by kisvegabor** [comment]
Form the screenshot I think the problem is that you have included `main.h` in in `lv_conf.h`. To add `stm32u5xx_hal.h` to you project you can use `LV_GPU_DMA2D_CMSIS_INCLUDE` in `lv_conf.h`.
