### ISSUE TITLE
Two or more indevs handling

### ISSUE THREAD

**Issue by mmar22** [kisvegabor/lvgl#3973]
Roller is controlled by two indevs touch and encoder, but if touch is used
object is switched from EDITED to FOCUS and encoder stop working,

Howto best way to handle this ???

EDITED is activated from setup screen 
`lv_group_set_editing(g1, true);`

sorry i dont test on latest, but 8.2.0 .. SLS , but i mean latest do it same

**Comment by kisvegabor** [comment]
Hi,

I also think that it'd better if it worked as you suggested. Can you try these modifications? 
```diff
diff --git a/src/core/lv_group.c b/src/core/lv_group.c
index 2c4fa93e9..63fe4c0c9 100644
--- a/src/core/lv_group.c
+++ b/src/core/lv_group.c
@@ -238,13 +238,13 @@ void lv_group_focus_obj(lv_obj_t * obj)
 
     if(g->frozen != 0) return;
 
-    /*On defocus edit mode must be leaved*/
-    lv_group_set_editing(g, false);
-
     lv_obj_t ** i;
     _LV_LL_READ(&g->obj_ll, i) {
         if(*i == obj) {
             if(g->obj_focus != NULL && obj != *g->obj_focus) {  /*Do not defocus if the same object needs to be focused again*/
+                /*On defocus edit mode must be leaved*/
+                lv_group_set_editing(g, false);
+
                 lv_res_t res = lv_event_send(*g->obj_focus, LV_EVENT_DEFOCUSED, get_indev(g));
                 if(res != LV_RES_OK) return;
                 lv_obj_invalidate(*g->obj_focus);
```

If it works well I'll add these changes to LVGL.

**Comment by mmar22** [comment]
Maybe you miss copy paste need here true
+ lv_group_set_editing(g, false);

and from this code I see frozen. Cant be used for lock ? Or from my side is better based on some setup ignore false and return from lv_group_set_editing?

**Comment by mmar22** [comment]
SOLVED with
`  lv_group_focus_freeze(g1, true);
`
