### ISSUE TITLE
Animated QR codes.

### ISSUE THREAD

**Issue by jeandudey** [kisvegabor/lvgl#3975]
### Introduce the problem

It'd be great to have support for animated QR codes, right now it is possible to do it using the QR code widget but it doesn't offer too much control and can cause memory fragmentation on MCUs with little memory.

### Examples and cases

Animated QR codes are useful for devices that need to communicate data using only a display, for example, using the [UR standard](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md).

### Suggested solution

I think this can be solved by making the `lv_qrcode_update` take a `error_correction` and a `version` parameters to control the size of the QR code and use that version only, or maybe some `lv_qrcode_set_version`, `lv_qrcode_set_error_correction` getter and setters and leave `lv_qrcode_update` with the current behaviour and signature. The `version` and `error_correction` presence is to keep all of the frames at the same size.

To reduce fragmentation maybe the `data_tmp` and the `qr0` buffer could be allocated only once and if a bigger one is required then would be reallocated using a bigger size.

It'd be also great to check for the encoding type to use, as right now the code uses binary encoding only and checking if the input data is alphanumeric would help to fit more data in a single QR.

**Comment by kisvegabor** [comment]
In general I like to idea but we are using the `qrcode` library as a [3rd party solution](https://github.com/nayuki/QR-Code-generator/tree/master/c). So ideally these features should be added in the original library. Could you open an issue/send a Pull request there?
