### ISSUE TITLE
Code-Generation in Squareline-Studio with dash in project name

### ISSUE THREAD

**Issue by MrMarteng** [kisvegabor/lvgl#3981]
# Description
SquareLineStudio seems to take the use the project name for the declaration of some defines in the source-code

# To Reproduce
Simply use a dash ("-") in your project name and the exported UI will no longer complile properly.
The `#ifndef` guard includes the project name and also the dash, which of course isn't a valid definition
Tested with Squareline V1.2.1

**Comment by kisvegabor** [comment]
Thanks for reporting it. I've forwarded this issue to the developers of SquareLine. 

In the future, please report the SquareLine related issues in its own [Forum](https://forum.squareline.io/).
