### ISSUE TITLE
How does Meter change the color of the center dot?

### ISSUE THREAD

**Issue by CYCHEN97** [kisvegabor/lvgl#3993]
How does Meter change the color of the center dot?

**Comment by kisvegabor** [comment]
You can use:
```c
    lv_obj_set_style_bg_color(meter, lv_color_hex(0xff0000), LV_PART_INDICATOR);
```

This [part of the docs](https://docs.lvgl.io/master/widgets/meter.html#parts-and-styles) describes how the styles work for the meter.

---

Note that we use GitHub Issues for development-related discussions.

Please ask similar how-to question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
