### ISSUE TITLE
lv_label disregards max_width

### ISSUE THREAD

**Issue by sparkles43** [kisvegabor/lvgl#4006]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When creating a label and setting it into `LV_LABEL_LONG_DOT`-mode, the function `lv_label_refr_text(lv_obj_t * obj)` will not properly regard cases in which a maximum width was set on the label but its width is still set to LV_SIZE_CONTENT by default.
The result is that the label's text is clipped instead of replaced by three dots.

This is most likely due to the line
https://github.com/lvgl/lvgl/blob/bdf3d4e66606135e84a49ce47da22df2b66120a7/src/widgets/label/lv_label.c#L899
which occurs at several places in the source code file.

To properly handle this case, an additional check for the maximum width should be implemented.

_Additional odd behavior:_
Once I set the width properly (by `label.set_width(30)`), it resulted in a proper three dots replacement. However, I got a rather strange line break behavior since the text now breaks line within the word "Hello" (compare second screenshot).
Only after I added an additional `label.set_height(16)` or `label.set_style_max_height(16)`, I finally received the intended output (screenshot 3). I know that the algorithm may break lines unless the height is fixed, but the behavior of the line breaking is odd.
(Will it break lines until the very last word is reached and only this one will receive three dots?)

(I assume similar issues had been brought up in: https://github.com/lvgl/lvgl/issues/2150 and https://github.com/lvgl/lvgl/issues/3792. We don't need to discuss them here any further)

### To Reproduce

```python
# Initialize 

import display_driver
import lvgl as lv

# Create a button with a label 

scr = lv.obj()
btn = lv.btn(scr)
btn.align(lv.ALIGN.CENTER, 0, 0)

label = lv.label(btn)
label.set_text('Hello World, let''s go!')
label.set_width(lv.SIZE_CONTENT) # same as default
# label.set_width(30) # three dots properly working with this line
# label.set_height(16) # line breaks properly working with this line
label.set_style_max_width(30, 0)
label.set_long_mode(label.LONG.DOT)

lv.scr_load(scr)
```

### Expected behavior

The refresh function detects that a maximum width is set (therefore does not set LV_TEXT_FLAG_FIT) and prints three dots to indicate the label's text is too long.

### Screenshots or video

label's text clipped instead of three dots:
![grafik](https://user-images.githubusercontent.com/112950468/220085854-fcccd37c-e119-48af-8603-3fedb5ba8fce.png)

half-way correct case (with `label.set_width(30)`):
![grafik](https://user-images.githubusercontent.com/112950468/220086587-06b4215a-43cd-45bb-b426-58fed14418e9.png)

final (with `label.set_height(16)`):
![grafik](https://user-images.githubusercontent.com/112950468/220088451-d5460afa-6b8d-46b4-a416-672880449d34.png)

**Comment by kisvegabor** [comment]
It's really not supported correctly now. I'm planning to fix it v9.

As this issue is already reported in https://github.com/lvgl/lvgl/issues/3420 I close this one.
