### ISSUE TITLE
lv_list arbitrary content?

### ISSUE THREAD

**Issue by pr8x** [kisvegabor/lvgl#4018]
### Introduce the problem

Hey, is it possible to add arbitrary (i.e. any `lv_object`) to a `lv_list`? 

### Suggested solution

It would be nice if I could et (for example) `lv_span` in there.

**Comment by kisvegabor** [comment]
Yes you can add any widgets. E.g.
```c
   lv_obj_t * sg =  lv_spangroup_create(list1);
   lv_spangroup_set_mode(sg, LV_SPAN_MODE_BREAK);
   lv_obj_set_width(sg, lv_pct(100));
   lv_span_t * s = lv_spangroup_new_span(sg);
   lv_span_set_text(s, "Hello, hello! I'm very long, so you can see word wrapping!");
```

![image](https://user-images.githubusercontent.com/7599318/221514914-fd205073-4f5e-46f4-a821-7cbd7778d166.png)

**Comment by pr8x** [comment]
Ah, I see. Thanks.
