### ISSUE TITLE
[Unit tests] Running a single test file

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#4019]
### Introduce the problem
Lately when running the test suite the last test execution takes a long time and I had to Ctrl-C it.

![imagen](https://user-images.githubusercontent.com/11037705/221432105-677fd792-fdcb-455f-b7ef-2b0f5415b84d.png)

You can see the 40th test is missing.

At work (and for personal projects) I'm used to run only the test file I'm working on, and do nightly runs of all the test files (like LVGL currently do), so I wondered how feasible it would be to run only one test file. I tried to write a Makefile to run only the lv_chart test runner but I found out it has a lot of dependencies on other source files so I gave up.

### Examples and cases
While working in a test file we should not be worried about breaking other test files.

### Suggested solution
Try to find out if it's possible to update, compile and run a single test runner of a given configuration and add an option to the main.py to run a selected test runner, this way hand made Makefiles would not be needed.

This can lead to running test files in less than a second, like this one that took 80ms
![imagen](https://user-images.githubusercontent.com/11037705/221432594-4cf9f5ea-5018-4ba1-8ccf-d9c0fab1cf33.png)

**Comment by kisvegabor** [comment]
`test_style` was slow because there was loop in it with 1000 repetitions. I've just updated in, and now it should be faster. 

Anyway,  it's just a workaround and doesn't solve your original question.


@some00 has added some changed to the CMakeFile recently, so I'd like to ask if you a have some time and interest to add this improvement.

**Comment by some00** [comment]
Hi @kisvegabor, I'll do it by the end of the week. Could you assign the issue to me?

**Comment by kisvegabor** [comment]
Assigned, thank you!

**Comment by C47D** [comment]
Great, thanks in advance @some00 and also thanks @kisvegabor
