### ISSUE TITLE
Benchmark Result is always 0

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#4027]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://github.com/lvgl/lv_port_an547_cm55_sim/tree/Using-LVGL9)

### Describe the bug
When running the benchmark, the result is always 0.

![image](https://user-images.githubusercontent.com/13148491/222006633-d4165be3-db14-482f-8541-bf3a6b387211.png)

### To Reproduce

```c
lv_demo_benchmark(LV_DEMO_BENCHMARK_MODE_RENDER_AND_DRIVER);
```

**Comment by kisvegabor** [comment]
Thank you for reporting it.

I've just pushed a fix.

**Comment by GorgonMeducer** [comment]
This helps a lot !!! @kisvegabor 
Thank you.

**Comment by GorgonMeducer** [comment]
I can confirm this issue is fixed.
