### ISSUE TITLE
Substr. related tests failed when `LV_COLOR_DEPTH` is 16

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#4029]
All Substr. related rendering failed when `LV_COLOR_DEPTH` is 16.
The rendering needs to be corrected.

```c
    {.name = "Substr. rectangle",            .weight = 10, .create_cb = sub_rectangle_cb},
    {.name = "Substr. border",               .weight = 10, .create_cb = sub_border_cb},
    {.name = "Substr. shadow",               .weight = 10, .create_cb = sub_shadow_cb},
    {.name = "Substr. image",                .weight = 10, .create_cb = sub_img_cb},
    {.name = "Substr. line",                 .weight = 10, .create_cb = sub_line_cb},
    {.name = "Substr. arc",                  .weight = 10, .create_cb = sub_arc_cb},
    {.name = "Substr. text",                 .weight = 10, .create_cb = sub_text_cb},
```

The initial analysis shows the problem related to `LV_COLOR_FORMAT_NATIVE_ALPHA_SIZE` and ARGB8565.

For example:
https://github.com/lvgl/lvgl/blob/41aebfa319d89f561ea5d462e00cf1aeb2824e3c/src/draw/sw/lv_draw_sw_blend.c#L110-L114

The current code leads to a problem related to 

https://github.com/lvgl/lvgl/blob/41aebfa319d89f561ea5d462e00cf1aeb2824e3c/src/misc/lv_color.c#L40-L79

i.e. `dest_buf` offset calculation use `3` as pixel size, but the `lv_color_fill` implies the pixel size is `2`. 

https://github.com/lvgl/lvgl/blob/41aebfa319d89f561ea5d462e00cf1aeb2824e3c/src/misc/lv_color.h#L165-L171

The whole issue seems more complicated than I observed. 

### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by GorgonMeducer** [comment]
When `LV_COLOR_DEPTH` is `32`, everything works well.

**Comment by kisvegabor** [comment]
Thank you, fixed!
