### ISSUE TITLE
Benchmark Result is always 0 in `LV_DEMO_BENCHMARK_MODE_RENDER_ONLY` mode

### ISSUE THREAD

**Issue by GorgonMeducer** [kisvegabor/lvgl#4030]
Similar issue to #4027 

### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce
```c
lv_demo_benchmark(LV_DEMO_BENCHMARK_MODE_RENDER_ONLY);
```

**Comment by kisvegabor** [comment]
Fixed. I should have tried it out in #4027... :slightly_frowning_face:

**Comment by GorgonMeducer** [comment]
Lol.

Thanks.
