### ISSUE TITLE
Using combination of key focus and touch/mouse focus exhibits odd behavior

### ISSUE THREAD

**Issue by sparkles43** [kisvegabor/lvgl#4034]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

After using the TAB-key to shift the focus to the next object (here textarea), the focus is not set back to the previous object (here button) when clicking it.

### To Reproduce

Python simulator code:
```python3
# Initialize 

import display_driver
import lvgl as lv

# Create a button with a label 

scr = lv.obj()
btn = lv.btn(scr)
btn.align(lv.ALIGN.TOP_MID, 0, 0)
red_focus = lv.color_make(180,100,100)
btn.set_style_bg_color(red_focus, lv.STATE.FOCUSED);

label = lv.label(btn)
label.set_text('Hello World!')

textarea = lv.textarea(scr);
textarea.align_to(btn, lv.ALIGN.OUT_BOTTOM_MID, 0, 10)
textarea.set_style_bg_color(red_focus, lv.STATE.FOCUSED);

lv.scr_load(scr)
```

Additional steps:
- Click on the button -> It receives the focus (red background)
- Press TAB-key to set key focus to the textarea -> button turns blue again
- Click the button again -> button stays blue and does not receive the focus & the textarea remains focused

(Only after clicking in the textarea and then on the button, the button is focused again)

### Expected behavior

The focus is moved back to the button when it is clicked.

**Comment by kisvegabor** [comment]
Hi,

I'm planning a larger rework on groups and focusing, but I've just added a fix to `master`. The same can be applied in `v8` too.
