### ISSUE TITLE
returning a signed integer value when setting the value of a widget that uses integers 

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#4038]
### Introduce the problem

when calling `set_value` for a widget that uses integers and the value given to the widget is outside of the min and max provided when the widget is constructed the widget automatically uses the min or the max value but provides no indication that the value supplied is the one that was used.

### Examples and cases
In this example I have a set min and max of -50 and 50. but I am able to set the value to 70 without any indication that the supplied value was out of bounds.

https://sim.lvgl.io/v9.0/micropython/ports/javascript/index.html?script_startup=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/header.py&script=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/styles/lv_example_style_13.py&script_direct=a7ac2dbcbe7aed967212edec428a3bc656ce3bae

and here is pseudo code of what I mention below.
https://sim.lvgl.io/v9.0/micropython/ports/javascript/index.html?script_startup=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/header.py&script=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/styles/lv_example_style_13.py&script_direct=2951d8fd89cce028d26a923f7c4783282149fb0d

and here is a code example of what would have to be done currently.
https://sim.lvgl.io/v9.0/micropython/ports/javascript/index.html?script_startup=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/header.py&script=https://raw.githubusercontent.com/lvgl/lvgl/6cd98892a4e60fc2c48b31a50f02feea8e8d7299/examples/styles/lv_example_style_13.py&script_direct=e829d067aba71412ce1fb669627331cc2265b4f6

The last example is redundant because the widget also checks the boundaries to set the value. so adding a return value should be pretty easy to do. it removes redundantly checking the value to see if it is within the boundaries. The default behavior of setting to value to the min or max if it is out of bounds can actually be left as it is. That way the current API and functionality would remain the same and moving forward if a user wanted to use the returned value they would be able to.  

### Suggested solution
returning -1 if the supplied value is lower than the min value, 0 if the supplied value is higher than the max and 1 if the value fell within the given min and max values. This would give the user the ability to react to an out of bounds supplied value without the need to check the value every single time before it gets passed to `set_value`.

When working with MCUs specifically the pins there is usually remapping that is done when doing something like reading an analog pin. In MicroPython setting the remapped value to a variable takes time to do and if the remapped value can be passed to set_value at the time the value gets remapped skipping setting it to a variable and a simple check of the  return value from set_value gets done to determine if it was successful or not and react if it was successful would save some code execution time by only doing checks and changes to values that do not succeed.

**Comment by kdschlosser** [comment]
Never got a response to this suggestion.

**Comment by kisvegabor** [comment]
Sorry, somehow I overlooked this issue.

What about extending [`lv_res_t`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_types.h#L42-L47) with new members and using it where possible.
