### ISSUE TITLE
glitches using stm32 dma2d for lvgl v8.3

### ISSUE THREAD

**Issue by HaoboGu** [kisvegabor/lvgl#4041]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce

recently I updated lvgl version from v8.2 to v8.3, but the display has some glitches if stm32 dma2d is enabled. I used dma2d in version v8.2, all things are good. Disable dma2d in v8.3, the display is also good, so I suspect that the problem is introduced by stm32 dma2d updates in v8.3. 

My MCU is stm32h7.

### Screenshots or video

<img width="252" alt="image" src="https://user-images.githubusercontent.com/8640918/223316486-d5ff245a-3912-4052-8969-171327496a88.png">

**Comment by kisvegabor** [comment]
@tdjastrzebski Could you take a look at it?

**Comment by tdjastrzebski** [comment]
I am afraid without source code I can not even try to make a guess.

**Comment by tdjastrzebski** [comment]
However, you may want to take a look at my demo example and try to find differences or adapt it to your needs.
https://github.com/tdjastrzebski/STM32F769I-DISCO-LVGL

**Comment by HaoboGu** [comment]
I'm using FMC to send data to LCD using 8080 interface. In this case, DMA2D is used only for processing frames, am i right? The only difference I see is that I use FMC to send data to LCD, not DMA2D. However, I still get improvements of FPS by enabling DMA2D in this case.

**Comment by tdjastrzebski** [comment]
I have no way of knowing.
If you do NOT use DMA(2D) to move data from draw buffer to (e.g.) 8080, try invalidating draw buffer first (call `SCB_InvalidateDCache_by_Addr()`) to avoid reading dirty cached bytes, make sure both draw buffer length and start address are 32 byte (byte, not bit) aligned. See [this line](https://github.com/tdjastrzebski/STM32F769I-DISCO-LVGL/blob/c5aa36a3de62e464c07bce401cbcb5f3ac5ff3e3/master.cpp#L33) and [this](https://github.com/tdjastrzebski/STM32F769I-DISCO-LVGL/blob/c5aa36a3de62e464c07bce401cbcb5f3ac5ff3e3/master.cpp#L287) commented out `FlushBufferStart()` function implementation not using DMA(2D).

**Comment by HaoboGu** [comment]
CleanDCache worked, but only by calling `SCB_CleanInvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);` before and after flushing. Here is my `disp_flush`:

```c
static void disp_flush(lv_disp_drv_t *disp_drv, const lv_area_t *area, lv_color_t *color_p) {
#if LV_USE_GPU_STM32_DMA2D
  // Clean and invalidate dcache before and after display flushing
  SCB_CleanInvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);
#endif

  // Write display data using fmc
  lcd_fill_data_fmc(area->x1, area->x2, area->y1, area->y2, color_p);

#if LV_USE_GPU_STM32_DMA2D
  SCB_CleanInvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);
#endif

  lv_disp_flush_ready(disp_drv);
}
```

**Comment by tdjastrzebski** [comment]
That is interesting. I would say Invalidating alone and only before the transmitting should be sufficient abut anyway, I am glad it works.   
Do not neglect to align the draw buffer. Otherwise, if draw buffer is surrounded with other data, you may experience random crashes and nondeterministic behavior because you may be incidentally cleaning/invalidating bytes which should not be touched. On Cortex-M7 cache is maintained using 32byte blocks, hence the address and length that you specify as arguments may not be those actually used if they are not 32 byte aligned (address is rounded down, length is rounded up).  
Good luck

**Comment by HaoboGu** [comment]
Adding `SCB_InvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);` before transmitting data fixes almost all cases except scenes having this picture when running lvgl benchmark: 
<img width="183" alt="image" src="https://user-images.githubusercontent.com/8640918/224635955-3e5b9b07-95a6-4509-b0a8-e18ecd0db638.png">

The interesting thing is, only the picture is affected, the FPS monitor does not:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/8640918/224636555-585d011c-6ce1-466c-a13c-2fc695f96d8d.png">

**Comment by HaoboGu** [comment]
I guess `SCB_InvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);` should be also added to somewhere else when rendering images? Is there a separate buffer for images in lvgl? @kisvegabor

**Comment by tdjastrzebski** [comment]
Yeah, it is a bit more complicated and tricky since, unfortunately, LVGL does not always fill-in draw buffer using DMA2D when it is enabled. Hopefully this will be some how fixed in rev 9. I do not think the current implementation can be much better due to internal rev 8 constraints.
See my remarks [here](https://github.com/lvgl/lvgl/pull/3904#issuecomment-1398193372)

**Comment by tdjastrzebski** [comment]
Do you use 16 or 32bit color? That may make a subtle difference

**Comment by HaoboGu** [comment]
I use 16bit color, RGB565

**Comment by tdjastrzebski** [comment]
That's what I thought. Especially in 16b mode sometimes images are internally painted without DMA2D if the internal image format does not match any of the available DMA2 modes. I may want to take another look to see if anything could be SAFELY improved.

**Comment by kisvegabor** [comment]
> Is there a separate buffer for images in lvgl? @kisvegabor

Actually there are two main cases:
- As @tdjastrzebski pointed out, during software rendering ARGB images are splint into an RGB and and alpha buffer
- If there some special effects on the images (e.g. additive blending, `style_transform_...`, not `img_angle` or `img_zoom`) then a widget an all its children are drawn into a separate buffer first and the "snapshot" is rendered as an image.

**Comment by tdjastrzebski** [comment]
Regardless of special effects applied, if at the end bytes are in a buffer and color format can be handled by dma2d, there is no problem.
I believe currently the most problematic case is 16b color with opacity, 24b total (ARGB8565). There is no way to draw it directly with dma2d, unless buffer is first translated to ARGB32 (or ARGB4444) - which is an option. Another case which dma2d cannot handle is subtractions.

**Comment by tdjastrzebski** [comment]
@kisvegabor Maybe the right solution to the above problem would be NOT to use separate 8b bitmap masks and 16b color buffers and instead always use 32b/pixel buffers, even when effective color format is 24b? This way 24b color (argb8565) could be easily ("in-place") converted to argb8888 just before dma2d blending, without having to copy bytes to a separate buffer, which would involve allocating extra memory and then having to free it. It is just a thought.

**Comment by kisvegabor** [comment]
@tdjastrzebski 
We are talking about using RGB565 + A8 format in v9. See [this comment](https://github.com/lvgl/lvgl/issues/4059#issuecomment-1469699345). What do you think? To keep the conversation in one place, please comment in the linked issue.

**Comment by maxpromer** [comment]
> ```c
> SCB_CleanInvalidateDCache_by_Addr((uint32_t *)buf, buffer_length);
> ```

What is `buf` and `buffer_length` ? it frame buffer like `color_p` ?
