### ISSUE TITLE
Remove LV_USE_USER_DATA configuration

### ISSUE THREAD

**Issue by FASTSHIFT** [kisvegabor/lvgl#4051]
### Introduce the problem
In most GUI applications, `user_data` is basically relied on to bind some private data, and `LV_USE_USER_DATA` is almost a configuration item that must be enabled. So the meaning of this configuration reservation is actually not great.

### Suggested solution
Remove the `LV_USE_USER_DATA` configuration, which can reduce the macro judgment in many data structures and make the code more elegant.

**Comment by kisvegabor** [comment]
The only advantage of having `LV_USE_USER_DATA` is to save 4 bytes in some cases. 
But as time passes an MCUs get better, it's really less important.

Could you send a PR to remove it?

**Comment by FASTSHIFT** [comment]
> The only advantage of having `LV_USE_USER_DATA` is to save 4 bytes in some cases. But as time passes an MCUs get better, it's really less important.
> 
> Could you send a PR to remove it?

Done, Now the code is cleaner :)

**Comment by kisvegabor** [comment]
The PR is merged, closing. 
Thank you!
