### ISSUE TITLE
Slider control hit test location incorrect

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#4053]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Performing set_style_transform_angle on a slider  the slider doesn't hit test properly. In the example below you have to click off of the slider to the upper right of where the slider is located and you move in the opposite direction then what you would normally to move the slider. So moving away from the slider lessens the indicator and moving closer to and over the slider increases the indicator. 

as a side note and related to #4052 the outline and the border width are both set to zero for both the MAIN and INDICATOR parts but there is a border and it persists even after clicking to move the widget.

### To Reproduce
https://sim.lvgl.io/v9.0/micropython/ports/javascript/index.html?script_startup=https://raw.githubusercontent.com/lvgl/lvgl/126fbee5ae0f568ed35d03736de00ef093b9bd0a/examples/header.py&script=https://raw.githubusercontent.com/lvgl/lvgl/126fbee5ae0f568ed35d03736de00ef093b9bd0a/examples/widgets/arc/lv_example_arc_1.py&script_direct=5b330ceb0e7cb4b58ad43cdb7cc7a9ad0e7a8bc7

### Expected behavior
for the input to move the slider control properly.

**Comment by kisvegabor** [comment]
I've just fixed it :slightly_smiling_face:
