### ISSUE TITLE
Can we have decoder read multiple lines at once

### ISSUE THREAD

**Issue by greedyhao** [kisvegabor/lvgl#4084]
### Introduce the problem

Can we change the function `lv_img_decoder_read_line` from read a signal line to read multiple line. This reduces the number of function calls and increases the frame rate

### Examples and cases

I did a little experiment here, increasing the size of the len parameter, and I saw a real improvement in efficiency

**Comment by kisvegabor** [comment]
We will completely update the image decoders as described in [this discussion](https://github.com/lvgl/lvgl/pull/3294#issuecomment-1374512677). It will be more flexible and it will be easy to add support for multiple line read decoding.

**Comment by greedyhao** [comment]
Great, but when will this pr merge, it seems the progress is stuck

**Comment by XuNeo** [comment]
You can write a custom `bin` decoder, and simply read the full file to RAM, just like what `PNG` decoder does but with no decoding needed.

**Comment by kisvegabor** [comment]
> Great, but when will this pr merge, it seems the progress is stuck

It will be part of v9, but now we are focusing on [something else](https://github.com/lvgl/lvgl/issues/4016).
