### ISSUE TITLE
Does LVGL only support updating the display by 1 pixel?

### ISSUE THREAD

**Issue by cexianl** [kisvegabor/lvgl#4087]
### Introduce the problem
When I adapt a display that can only update data according to 4 pixels, it seems that LVGL only supports 1 pixel to update the display, so the data cannot be displayed normally.

### Suggested solution
I temporarily modified the code here to solve my problem. Is there a better way for LVGL?
![image](https://user-images.githubusercontent.com/100854497/227499534-fcdebede-9c65-4f58-89d3-e1ae2e49a4a4.png)

**Comment by kisvegabor** [comment]
You can use the [`rounder_cb`](https://docs.lvgl.io/8.3/porting/display.html#optional-fields) (see line 231).

We use GitHub Issues for development-related discussions.

--

Please ask similar questions in the [Forum](https://forum.lvgl.io) to make them visible for a larger community. You can simply log in with your GitHub account.

**Comment by cexianl** [comment]
Thanks for your help.
