### ISSUE TITLE
tabview dynamic add and delete tab isus

### ISSUE THREAD

**Issue by PassengerOfLastBus** [kisvegabor/lvgl#4090]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by kisvegabor** [comment]
It's planned for v9. See [here](https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md#widgets).
