### ISSUE TITLE
lv_btnmatrix_set_btn_height missing

### ISSUE THREAD

**Issue by daniu-de** [kisvegabor/lvgl#4103]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
the above function seems to be missing - in some cases it makes sense to adjust the height instead of the width. E. g. a Enter Button is not only wider but also heigher and for tabview with tabs on the left the tab height is like the tab width in horizontal tabviews

**Comment by kisvegabor** [comment]
The rows of the button matrix always cover the full height of the widget. We could add a `set_row_height` function which can be set to any px or % value or `auto`. 

Regarding the tabview, I'll replace it's button matrix with buttons in v9 as usually it has only a few buttons but they should be more flexible.
