### ISSUE TITLE
v8.3.6 release plan

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#4104]
In March we didn't have a patch release as there were only a few updates. However for April we got a reasonable amount of fixes so we can release v8.3.6 next week.

cc @GorgonMeducer could you send a PR with the CMSIS pack update?

**Comment by GorgonMeducer** [comment]
OK, I will do it today.

**Comment by GorgonMeducer** [comment]
Done https://github.com/lvgl/lvgl/pull/4108

**Comment by mysterywolf** [comment]
RT-Thread has tested, everything looks good.

**Comment by kisvegabor** [comment]
Released, thank you!
