### ISSUE TITLE
Replace direct usage of strlen and strcpy with macros of lv_config.h

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#4110]
### Introduce the problem
There are some direct calls to `strlen` and `strcpy` remaining in the code base, I think `LV_STRLEN` and `LV_STRCPY` can be used instead.

### Examples and cases
E.g. in `lv_checkbox_set_text` those APIs are used directly.

```c
void lv_checkbox_set_text(lv_obj_t * obj, const char * txt)
{
    lv_checkbox_t * cb = (lv_checkbox_t *)obj;

    if(NULL != txt) {
        size_t len = 0;

#if LV_USE_ARABIC_PERSIAN_CHARS
        len = _lv_txt_ap_calc_bytes_cnt(txt);
#else
        len = strlen(txt);
#endif

        if(!cb->static_txt) cb->txt = lv_realloc(cb->txt, len + 1);
        else cb->txt = lv_malloc(len + 1);

        LV_ASSERT_MALLOC(cb->txt);
        if(NULL == cb->txt) return;

#if LV_USE_ARABIC_PERSIAN_CHARS
        _lv_txt_ap_proc(txt, cb->txt);
#else
        strcpy(cb->txt, txt);
#endif

        cb->static_txt = 0;
    }

    lv_obj_refresh_self_size(obj);
    lv_obj_invalidate(obj);
}
```

### Suggested solution
`LV_STRLEN` and `LV_STRCPY` are available in the `lv_conf.h` file, use them instead of direct calls to `strlen` and `strcpy`.

**Comment by kisvegabor** [comment]
Good point, however `lv_strncpy()` and `lv_strlen()` should be used.
