### ISSUE TITLE
printf format string vulnerability

### ISSUE THREAD

**Issue by maxgerhardt** [kisvegabor/lvgl#4119]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The example code

https://github.com/lvgl/lvgl/blob/efa02eca24120ec536144dc5bc9d1a2c29fe0918/examples/arduino/LVGL_Arduino/LVGL_Arduino.ino#L21-L28

is susceptible to a security vulnerability called [Format String Attack](https://owasp.org/www-community/attacks/Format_string_attack). 

### To Reproduce
```c
lv_log("Evil format string %s\n", "%s %s %s");
// will call my_print() with argument "Evil format string %s %s %s"
// causes stack leakage thanks to not being printed as a literal but interpreted as another format string
```

### Expected behavior
Example code should be free of security vulnerabilities.

E.g.,
```cpp
#if LV_USE_LOG != 0
/* Serial debugging */
void my_print(const char * buf)
{
    Serial.printf("%s", buf);
    Serial.flush();
}
#endif
```
or
```cpp
#if LV_USE_LOG != 0
/* Serial debugging */
void my_print(const char * buf)
{
    Serial.print(buf);
    Serial.flush();
}
#endif
```

### Screenshots or video
None applicatable.

**Comment by FASTSHIFT** [comment]
fixed https://github.com/lvgl/lvgl/pull/4125
