### ISSUE TITLE
lv_dropdown Does Not Check "style_max_height"

### ISSUE THREAD

**Issue by BasicCode** [kisvegabor/lvgl#4137]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version - **NOTE:** Although I'm using lv_port_linux_frame_buffer, I have gone and updated *lvgl*, and *lv_drivers* to the latest release for this test.
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I wanted to force ```lv_dropdown``` to a maximum height when expanded, however ```lv_style_set_max_height()```, and ```obj_set_height()``` did not seem to work. I could not see that this value was checked in ```lv_dropdown_open()``` or elsewhere.

### To Reproduce

```c
    /*Create a normal drop down list*/
    lv_obj_t * dd = lv_dropdown_create(scr1);

    static lv_style_t style_dropdown;
    lv_style_init(&style_dropdown);

    // Try to set maximum height
    lv_style_set_max_height(&style_dropdown, 100);
    lv_obj_add_style(dd, &style_dropdown, 0);

    lv_dropdown_set_options(dd, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");

    lv_obj_align(dd, LV_ALIGN_TOP_MID, 0, 20);
    lv_obj_add_event_cb(dd, dropdown_event_handler, LV_EVENT_ALL, NULL);
```

### Expected behavior

I would expect the expanded box to have a maximum height of 100px, or 100dp.

### Screenshots or video

Sorry for potato quality.

Expected Behaviour:
![PXL_20230417_075558533](https://user-images.githubusercontent.com/4321855/232421650-72701172-2895-45cb-bdad-6287cd0a12cf.jpg)

Actual Behaviour:
![PXL_20230417_075532736](https://user-images.githubusercontent.com/4321855/232421674-481a1ccd-1b51-41a6-a8eb-a131e088d1b5.jpg)

### Fix
I'm not really sure if this is actually the intended behaviour of this function, but it is a feature that I wanted so I made a fix:
https://github.com/BasicCode/lvgl/commit/8f215a443f787483b7bfad80ea597d12fcf7ab85

**Comment by pete-pjb** [comment]
Hi @BasicCode ,

The dropdown widget is made from a list object so you need to change the style of the list object to achieve your desired result.  I hope this untested code snippet will help you out:

```c
  /*Create a normal drop down list*/
    lv_obj_t * dd = lv_dropdown_create(scr1);

 
    // Try to set maximum height
    lv_obj_t *list = lv_dropdown_get_list(dd);
    lv_obj_set_style_max_height(list, 100);
    lv_obj_add_style(dd, &style_dropdown, 0);

    lv_dropdown_set_options(dd, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");

    lv_obj_align(dd, LV_ALIGN_TOP_MID, 0, 20);
    lv_obj_add_event_cb(dd, dropdown_event_handler, LV_EVENT_ALL, NULL);
```

Kind Regards,

Pete

**Comment by BasicCode** [comment]
Thanks for that! Problem solved.

Final code:
```c
    /*Create a normal drop down list*/
    lv_obj_t * dd = lv_dropdown_create(scr1);

    lv_obj_t *list = lv_dropdown_get_list(dd);
    lv_obj_set_style_max_height(list, 100, LV_PART_MAIN);

    lv_dropdown_set_options(dd, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");

    lv_obj_align(dd, LV_ALIGN_TOP_MID, 0, 20);
    lv_obj_add_event_cb(dd, dropdown_event_handler, LV_EVENT_ALL, NULL);
```
