### ISSUE TITLE
Lv_flex:  LV_FLEX_ALIGN_END not work on cross place

### ISSUE THREAD

**Issue by luhuaipei** [kisvegabor/lvgl#4146]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I am trying to play around the flex layout of lvgl. But the behavior of my program does not work as expected.
![小米办公20230419-232248](https://user-images.githubusercontent.com/9547905/233123543-2d725382-e5b3-40c7-b742-f64029ae0003.png)

As the picture shows, I add three item in a container and set the container's flex property using following code:
```
 lv_obj_set_flex_align(cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
```
In my opinion, the three item should be located on the bottom of the container like this:
![image](https://user-images.githubusercontent.com/9547905/233120527-f3cf67e2-32a3-47ec-8373-a3d8ce0ea931.png)

So is this a bug or if I get it wrong ?

### To Reproduce

```c
#include "../../lv_examples.h"

void initobj(lv_obj_t * cont){
    lv_obj_remove_style_all(cont);
         lv_obj_set_style_border_post(cont, true, LV_PART_MAIN);
    lv_obj_set_style_border_width(cont, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(cont, 0, LV_PART_MAIN);
    lv_obj_clear_flag(cont,
        LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);
}

void initChild(lv_obj_t * cont){
    lv_obj_remove_style_all(cont);
         lv_obj_set_style_border_post(cont, true, LV_PART_MAIN);
    lv_obj_set_style_border_width(cont, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(cont, 0, LV_PART_MAIN);
    lv_obj_clear_flag(cont,
        LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);


    lv_obj_set_style_bg_color(cont,lv_color_white(),LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cont,LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_border_width(cont,1,LV_PART_MAIN);
    lv_obj_set_style_border_color(cont,lv_color_black(),LV_PART_MAIN);
}

/**
 * Demonstrate flex grow.
 */
void lv_example_flex_3(void)
{
    lv_obj_t * cont = lv_obj_create(lv_scr_act());
    initobj(cont);


    lv_obj_set_style_bg_color(cont,lv_color_black(),LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cont,LV_OPA_COVER, LV_PART_MAIN);
    //lv_obj_set_flex_flow(cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_flow(cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    //set container size(400*40)


    //set container size(400*40)
    lv_obj_set_size(cont, 400, 40);

    lv_obj_t * obj;
    obj = lv_obj_create(cont);
    initChild(obj);
    lv_obj_set_size(obj, 100, 34);           /*Fix size*/

    obj = lv_obj_create(cont);
    initChild(obj);
    lv_obj_set_size(obj, 100, 34);

    obj = lv_obj_create(cont);
    initChild(obj);
    lv_obj_set_size(obj, 100, 34);

}
```

### Expected behavior

As above.
### Screenshots or video

As above.

**Comment by kisvegabor** [comment]
At this point LVGL's flexbox is not exactly the same CSS's flexbox. In LVGL the track's height is always equals to the highest item in that track. So in your example the track's height is 34 px, and the items are aligned to the bottom of this track. But the track is still aligned  to the top of the container. 

To fix it all you need to do is changing the last parameter to `END`:
```c
    lv_obj_set_flex_align(cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
```

**Comment by luhuaipei** [comment]
Thanks for the reply. 

> In LVGL the track's height is always equals to the highest item in that track
.

For this implementation, I am not quite understand the purpose. 

Can we  use the following code in find_track_end() in lv_flex.c to implement the align-item feature?


```
           if(f->wrap){
                t->track_cross_size = LV_MAX(get_cross_size(item), t->track_cross_size);
            }else{
                if(f->row){
                   //for flex direction is ROW
                    t->track_cross_size = LV_MAX3(get_cross_size(item), t->track_cross_size, lv_obj_get_height(item->parent) );
                }else{
                   //for flex direction is COLUMN
                    t->track_cross_size = LV_MAX3(get_cross_size(item), t->track_cross_size, lv_obj_get_width(item->parent) );
                }
            }
```

**Comment by kisvegabor** [comment]
It could work too, but I don't see why would it be better than the current version. Can you mention some cases when this modification makes things simpler?

**Comment by luhuaipei** [comment]
After reading the document of flex layout in lvgl. I got it that the last three params of function 
`lv_obj_set_flex_align(cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);`
represent the 'justify-content', 'align-item', 'align-content' in CSS defination.

So I think for the people who have get used to CSS behavior, although we could achieve the layout in my root question by changing the third param to 'LV_FLEX_ALIGN_END', I think it's better to support it in lvgl by only set the second param to 'LV_FLEX_ALIGN_END'. 

Above is my personal understanding, if there's any misunderstanding, please correct me immediately. :)

Thanks.

**Comment by kisvegabor** [comment]
Actually we need to balance between following CSS and keeping things simple and consistent. Sometimes it seems both are not possible at the same time :smile: 

Here my way of thinking was that it's easier to communicate, document and understand that "the track height equals to the highest item in the track". In my opinion in results in the least confusion and surprise.

**Comment by luhuaipei** [comment]
I agree that we need to keep simple and consistent on lvgl implementation. 

Maybe another way to solve my confusion is that,  instead of editing the code, we could take a highlight note on the [overview part of flex document](https://docs.lvgl.io/master/layouts/flex.html#overview) to let user know that lvgl implementation may have different behavior with CSS. 

In this way, I think it could cause less confusion for people like me.

What do you think?

**Comment by kisvegabor** [comment]
> Maybe another way to solve my confusion is that, instead of editing the code, we could take a highlight note on the [overview part of flex document](https://docs.lvgl.io/master/layouts/flex.html#overview) to let user know that lvgl implementation may have different behavior with CSS.

We don't get many issues due the discrepancy from CSS so I'd rather start with documenting the differences. Could you update #4206 with the docs update?

**Comment by luhuaipei** [comment]
Of course.  I can do it. But before that, let's double check what I'll do.
1. update the pull request  by removing  the lv_flex.c code editing.
2. update the pull request with docs update.

Is it right?

**Comment by kisvegabor** [comment]
Yes, I meant the same :slightly_smiling_face:
