### ISSUE TITLE
Does lvgl support displaying png  like this?

### ISSUE THREAD

**Issue by hurryboylqs** [kisvegabor/lvgl#4148]
![image](https://user-images.githubusercontent.com/41365726/233251047-4d7d621c-f64f-46d8-baae-fc7d5551d563.png)

My PC screen resolution is relatively high(width 3840, height 2160)，but the picture is not that big.
How should I write the code

**Comment by kisvegabor** [comment]
Hi,

I don't really understand the question. If you would like to scale the image you can use and online of offline image editor tool to do so.

**Comment by hurryboylqs** [comment]
I want to stretch and display the png in the same way as the image above

**Comment by kisvegabor** [comment]
Ah, it's not supported yet, but it will be supported in v9.
