### ISSUE TITLE
请问如何实现虚线倾斜线

### ISSUE THREAD

**Issue by Smallyellowcroaker** [kisvegabor/lvgl#4153]
我在chart这个控件中使用虚线来显示数据，当虚线倾斜的时候，虚线的效果就不存在，变回实线了，我该如何解决这个问题？

> 请用英语。slightly_smiling_face您也可以使用谷歌翻译。

**Comment by kisvegabor** [comment]
In English please. :slightly_smiling_face: 
You can use Google Translate too.

**Comment by Smallyellowcroaker** [comment]
Sorry, my problem is as follows. I use dashed lines to display data in the chart control. When the dashed lines are tilted, the effect of the dashed lines does not exist and they become solid again. How can I solve this problem?
