### ISSUE TITLE
Hello, I would like to ask you about the use of LVGL dashed lines. thank you

### ISSUE THREAD

**Issue by Smallyellowcroaker** [kisvegabor/lvgl#4154]
Hello, I would like to ask how to solve the problem of VLGL dashed lines turning back to solid lines when tilted. I used lv in the chart control_ obj_ set_ style_ line_ dash_ Gap() and lv_ obj_ set_ style_ line_ dash_ The width() functions are ineffective when the data is in a non horizontal and vertical state. How can I solve this problem. Thank you.

**Comment by kisvegabor** [comment]
Hi,

Unfortunately, LVGL's software render can not draw dashed skew lines at this moment. However it will be supported in LVGL v9 or in v9.1.

**Comment by Smallyellowcroaker** [comment]
Hello, does this mean that v8 does not yet support diagonal dashed lines?

**Comment by kisvegabor** [comment]
Yes, v8 doesn't support diagonal dashed lines.
