### ISSUE TITLE
lv_disp_create() not available

### ISSUE THREAD

**Issue by Deadeye5589** [kisvegabor/lvgl#4157]
### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

According to this section of the documentation (https://docs.lvgl.io/master/porting/display.html) 
your supposed to create display instances by calling lv_disp_t * disp = lv_disp_create(hor_res, ver_res)
but it seems that the function lv_disp_create is not available in the latests LVGL library 8.3.6

### To Reproduce

lv_disp_t * disp = lv_disp_create(320, 140);

lv_disp_create gets squiggeld. Also you can try to find this function within the libaray by hand without success. 

### Expected behavior

function should be available or the documentation has to be changed.

**Comment by kisvegabor** [comment]
For LVGL v8 please use the related version of the docs: 
https://docs.lvgl.io/8/
