### ISSUE TITLE
for IMX6ULL, Port the LVGL on OLED 

### ISSUE THREAD

**Issue by shallwing** [kisvegabor/lvgl#4160]
There is an OLED screen using SPI bus on my **IMX6ULL**. I know that the LVGL supports for Framebuffer driver, now I want to port the LVGL on my **IMX6ULL**. So how should I edit my OLED driver program to adapt the LVGL arch? 

Maybe the answer is behind the lv_driver, file [fbdev.c], which is driver config file for Framebuffer.
![image](https://user-images.githubusercontent.com/46883012/234168941-b9cdb8d6-98f3-44e7-9c2f-62b46b3a353d.png)

The following is my Device Tree for OLED:
&ecspi1 {
	fsl,spi-num-chipselects = <1>;
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_spi &pinctrl_spi_rst &pinctrl_spi_dc>;
	cs-gpio = <&gpio3 26 GPIO_ACTIVE_LOW>;
	dc-gpio = <&gpio3 23 GPIO_ACTIVE_LOW>;
	rst-gpio = <&gpio3 24 GPIO_ACTIVE_LOW>;
	status = "okay";

	#address-cells = <1>;
	#size-cells = <0>;

	oled@0 {
		compatible = "DS,oled-spi";
		reg = <0>;
		spi-max-frequency = <8000000>;
		status = "okay";
	};
};

       pinctrl_spi: oled_spi {
		fsl,pins = <
			MX6UL_PAD_LCD_DATA22__ECSPI1_MOSI		0x10b0
			MX6UL_PAD_LCD_DATA20__ECSPI1_SCLK		0x10b0
			MX6UL_PAD_LCD_DATA23__ECSPI1_MISO		0x10b0
			MX6UL_PAD_LCD_DATA21__GPIO3_IO26		0x10b0			//CS
		>;
	};
	
	pinctrl_spi_rst: oled_spi_rst {
	     fsl,pins = <
			MX6UL_PAD_LCD_DATA19__GPIO3_IO24		0x10b0
		 >;
        };
	
	pinctrl_spi_dc: oled_spi_dc {
		 fsl,pins = <
			MX6UL_PAD_LCD_DATA18__GPIO3_IO23		0x10b0
		 >;
	};

**Comment by kisvegabor** [comment]
If you write something to the fbdev with `echo` do you see it on the display?

**Comment by shallwing** [comment]
> If you write something to the fbdev with `echo` do you see it on the display?

Thank you, I will have a try.
