### ISSUE TITLE
Question about `lv_draw_sw_img_decoded`

### ISSUE THREAD

**Issue by greedyhao** [kisvegabor/lvgl#4163]
### Introduce the problem

Could anyone please tell me why the height of the screen is used in the calculation of `MAX_BUF_SIZE`？Why not use the entire screen size？

https://github.com/lvgl/lvgl/blob/8ee6f17ade48bc56b286e7efdb79a0d8da6b9260/src/draw/sw/lv_draw_sw_img.c#L23
https://github.com/lvgl/lvgl/blob/8ee6f17ade48bc56b286e7efdb79a0d8da6b9260/src/draw/sw/lv_draw_sw_img.c#L112
https://github.com/lvgl/lvgl/blob/8ee6f17ade48bc56b286e7efdb79a0d8da6b9260/src/draw/sw/lv_draw_sw_img.c#L113
https://github.com/lvgl/lvgl/blob/8ee6f17ade48bc56b286e7efdb79a0d8da6b9260/src/draw/sw/lv_draw_sw_img.c#L116

**Comment by kisvegabor** [comment]
A buffer for the entire screen might need >100kB. If we do all these things in smaller chunks we can save a lot of memory.

**Comment by greedyhao** [comment]
Got it. Thanks a lot.
