### ISSUE TITLE
Texture LRU cache insertion failure not accounted for in the SDL GPU driver

### ISSUE THREAD

**Issue by ReimuNotMoe** [kisvegabor/lvgl#4164]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When using the SDL GPU driver, it is possible that the total size (key for lookup + itself) of a texture does not fit in the LRU cache at all. However, in the texture cache management functions (`lv_draw_sdl_texture_cache.c`), the return value of `lv_lru_set` is not checked at all. If the LRU cache insertion is failed, the texture pointer will be lost forever, and causing serious GPU memory leaks.

### To Reproduce
- Use the SDL GPU driver and a monitor with 4K or larger resolution
- The SDL version needs to be newer than 2.0.6, to support `LV_GPU_SDL_CUSTOM_BLEND_MODE`
- Create a slider bar that occupies the entire horizontal space
- Drag the slider back and forth and watch the RAM usage grow exponentially

This has been reproduced on Linux + NVIDIA GTX 1660Ti and MacOS + AMD RX580

### Expected behavior
If a texture cannot be put into the LRU cache, it should be destroyed immediately after use.

### Screenshots or video
![image](https://user-images.githubusercontent.com/34613827/234598278-3e5b98e2-74e4-4434-b661-23830306a401.png)

![image](https://user-images.githubusercontent.com/34613827/234598395-d4791953-431e-4994-b415-673021c0340d.png)

**Comment by kisvegabor** [comment]
@mariotaku, could you take a look at this?

**Comment by mariotaku** [comment]
@kisvegabor Sure!

**Comment by mariotaku** [comment]
@ReimuNotMoe Would you like to give https://github.com/lvgl/lvgl/pull/4173 a shot? I tested it with Valgrind and it's looking good so far.

**Comment by ReimuNotMoe** [comment]
> @ReimuNotMoe Would you like to give #4173 a shot? I tested it with Valgrind and it's looking good so far.

Yes, it's working nicely now. Thanks!

**Comment by mariotaku** [comment]
@ReimuNotMoe Cool.
@kisvegabor the PR is ready for review :)

**Comment by kisvegabor** [comment]
The PR is merged, I close this issue.
