### ISSUE TITLE
Arm-2D applies chromakeying to LV_IMG_CF_TRUE_COLOR images

### ISSUE THREAD

**Issue by kjbracey** [kisvegabor/lvgl#4169]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The Arm-2D accelerator applies chromakeying even when not requested. Observed in 8.3.4, but issue still present by code inspection.

This section of code does not distinguish the values of `cf`.

https://github.com/lvgl/lvgl/blob/b603fb90f13fb473fdcf4369d2629bf1054a0b82/src/draw/arm2d/lv_gpu_arm2d.c#L1078-L1096

### To Reproduce
```c
    imageObj = lv_img_create(lv_scr_act());
    imageDesc.data = (const uint8_t *)lvgl_image;
    imageDesc.data_size = sizeof lvgl_image;
    imageDesc.header.always_zero = 0;
    imageDesc.header.reserved = 0;
    imageDesc.header.cf = LV_IMG_CF_TRUE_COLOR;
    imageDesc.header.w = 224;
    imageDesc.header.h = 224;
    lv_img_set_src(imageObj, &imageDesc);
```
With the image (test bars in my case) containing some pure green, with default config.

### Expected behavior
No pixels should be transparent (unless indicated by alpha).

**Comment by kisvegabor** [comment]
@GorgonMeducer, could you take a look at it?

**Comment by GorgonMeducer** [comment]
OK, I will fix it. 

@kjbracey Just one question, are you using Cortex-M55 or Cortex-M85 processors?

**Comment by GorgonMeducer** [comment]
The issue is fixed in cmsis-pack v8.3.7-dev

**Comment by kjbracey** [comment]
> @kjbracey Just one question, are you using Cortex-M55 or Cortex-M85 processors?

M55.

Thanks for the quick fix!

**Comment by kisvegabor** [comment]
I've merged the PR.

**Comment by kjbracey** [comment]
As I asked on #4179, this looks like it's just disabling the acceleration for non-colorkey images - or does it end up accelerated via another path?

**Comment by GorgonMeducer** [comment]
@kjbracey Yes. It will use other basic acceleration.

So the whole acceleration strategy is:

First, use condition filters to find those specific scenarios that can be accelerated with dedicated arm-2d API directly,
After that, the left parts will go to the default acceleration routine which is also good.

**Comment by GorgonMeducer** [comment]
@kjbracey dedicated acceleration for transform-only-with-opacity is added: https://github.com/lvgl/lvgl/pull/4203
And as the code suggested, 
https://github.com/lvgl/lvgl/blob/2b56e04205481daa6575bd5f7ab5df59d11676eb/src/draw/arm2d/lv_gpu_arm2d.c#L1313-L1330

you won't get the acceleration until the release of arm-2d v1.1.3.

**Comment by GorgonMeducer** [comment]
@kjbracey arm-2d v1.1.3 is released. 
https://github.com/ARM-software/Arm-2D/releases/tag/v1.1.3

Please have a try and let me know whether the issue is solved or not.

**Comment by GorgonMeducer** [comment]
@kjbracey Any update? Or are you happy with this fix?

**Comment by kjbracey** [comment]
Sorry, I've not had a chance to try it yet. I will let you know when I do. (Looks good to me from inspection though).

**Comment by kjbracey** [comment]
Okay, tested 8.3.7 + 1.1.3 now, and it's fixed the display error in our app. But I've not profiled it to check performance, and I'm only testing that chromakey isn't applied - I have nothing attempting to use it. Thanks!

**Comment by GorgonMeducer** [comment]
@kjbracey Thank you for the confirmation. Don't worry about the performance part. I have done that locally. It is identical to the previous.
