### ISSUE TITLE
Need to place  widgets beside others, such as one is (x,y, w, h), the other is (x, y+h, w, h)

### ISSUE THREAD

**Issue by CristXu** [kisvegabor/lvgl#4187]
### Introduce the problem
Have an idea to place multiple widgets one by one, e.g. one is at (x, y) with (w, h), so want to place other at (x, y+h) with same shape (w, h). But after check and debug the code, found that there is a :
![image](https://user-images.githubusercontent.com/49855018/235308978-47229e02-d7ab-4b17-b666-090d074b7635.png)
lv_area_increase(area, 5, 5); at function lv_obj_get_transformed_area.
Seems that this will cause a overlap between two widgets.
So, My question is that, is it possiable to set the increase to 0, or add a macro to set this by user.
Or do you have any ideas about this idea? place two widgets beside each.

### Examples and cases
NO

### Suggested solution
Give the user a chance to set the area-increase value.

**Comment by kisvegabor** [comment]
Do you need to position transformed widgets? If not you don't need to use the `lv_obj_get_transformed_area` for it.

Can [flex layout](https://docs.lvgl.io/master/layouts/flex.html) work for you?

**Comment by CristXu** [comment]
Hi, 
    Thank you very much for your quick reply. 
    No, I do not need a position transformed widgets. But after check the code, seems that the lv_obj_get_transformed_area function will always be called when I set a widget visiable:
![image](https://user-images.githubusercontent.com/49855018/236123847-436415cf-f72f-461a-bab2-d4859c4cfad7.png)
    Then inside the lv_obj_get_transformed_area , the area will be enlarge by (5, 5) with lv_area_increase(area, 5, 5); :
![image](https://user-images.githubusercontent.com/49855018/236124006-ee47553a-ca68-4a99-96d9-103f1c3ea885.png)
    So why the code always increase the area? and how can I avoid this area-increase?
    And Yes, I have try the flex layout, but seems that can not work when I place two widget alongside others, for one of the area will overlap the others by 5px(lv_area_increase(xx, 5, 5));

Regards,
    Crist

**Comment by kisvegabor** [comment]
It's increased just to be sure the are is large enough even after some rounding errors. However,  `lv_obj_get_transformed_area` is not used the position the widgets. It's only used to calculate the figure out which area needs to be redrawn.

**Comment by CristXu** [comment]
Thank you. and Have another question, the redrawn area is larger than the widget inside. So if I put two widget as below:
![image](https://user-images.githubusercontent.com/49855018/236190174-9330d0a9-c2f5-48d2-8af0-9aa3a5e6d298.png)
We have red and black rects, but the redrawn area is the blue one, larger than each widget by 5px. So when redrawn the red one, the redrawn area will overlap the black? Is it correct? 
Thank you again for your help.

**Comment by kisvegabor** [comment]
> So when redrawn the red one, the redrawn area will overlap the black? Is it correct?

That's correct and it's really not ideal. This 5px extra size should be removed in v9 .
