### ISSUE TITLE
Per object antialiasing control

### ISSUE THREAD

**Issue by megaboy2k** [kisvegabor/lvgl#4197]
It is appeared that for some font sizes antialiasing can improve an appearance and get it worse in other cases.
For example, for tiny font sizes it get it worse and it would be very helpful to disable antialiasing only for such objects
keeping it enabled for the rest. 
This also applies to some mini icons such as GPS/GSM signals and technology name (2D, 3D, E, H, 3G, etc).
It would be highly desirable to add individual antialiasing control, say, in style properties.
The described feature is mostly actual for middle and low resolution displays, say, 320x240 with not a super tiny pixel size.

**Comment by kisvegabor** [comment]
You can convert the fonts with different bpp (bit per pixel). For small fonts you can use higher bpp, for the larger ones small bpp should be enough too.


In the [font converter](https://lvgl.io/tools/fontconverter):
![image](https://user-images.githubusercontent.com/7599318/235620499-19b09fb9-628f-47d2-b4bf-8b269383c2de.png)

**Comment by megaboy2k** [comment]
@kisvegabor Correct, if I set 1 bpp for a small font the anti aliasing gets effectively disabled. However I can do nothing in case of other object types. E.g. I use lines to cross out a small icon (no signal imitation) and it would appear better if anti aliasing was not applied to these lines. This is why per object anti aliasing control would be very helpful in designing.

**Comment by kisvegabor** [comment]
I see. We are changing a lot of things for v9, and I'll keep it in mind. We sill see we can add it with a reasonable way.
