### ISSUE TITLE
keypad input device callback is not triggered

### ISSUE THREAD

**Issue by tranvnhan** [kisvegabor/lvgl#4205]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I am using a keypad with some number keys and navigation keys to provide inputs to the TFT display. The display part is working fine. But when I add the keypad as an input device, it seems that the callback is never called when I press the keys.

LVGL version: 8.3

### To Reproduce
Display initialization:
```c
lv_init();
// #if LV_USE_LOG != 0
//     lv_log_register_print_cb( my_print ); /* register print function for debugging */
// #endif
lv_disp_draw_buf_init( &draw_buf, buf, NULL, TFT_WIDTH * TFT_HEIGHT / 10 );

/*TFT display setup*/
tft.init();
tft.setRotation(1);  // view display horizontally

/*Initialize the display*/
static lv_disp_drv_t disp_drv;
lv_disp_drv_init( &disp_drv );
/*Change the following line to your display resolution*/
disp_drv.hor_res = TFT_HEIGHT;  // flipped since we use horizontal view
disp_drv.ver_res = TFT_WIDTH;
disp_drv.flush_cb = my_disp_flush;
disp_drv.draw_buf = &draw_buf;
lv_disp_drv_register( &disp_drv );
```

Keypad as input device initialization:
```c
lv_indev_drv_t keypad_drv;
lv_indev_drv_init(&keypad_drv);
keypad_drv.type = LV_INDEV_TYPE_KEYPAD;
keypad_drv.read_cb = keypad_read;
lv_indev_t * keypad_indev = lv_indev_drv_register(&keypad_drv);
lv_indev_set_group(keypad_indev, input_grp);
```

A textarea object which I want to input using the keypad:
```c
void lv_example_textarea_1(void) {
  lv_obj_t * ta = lv_textarea_create(lv_scr_act());
  lv_textarea_set_one_line(ta, true);
  lv_obj_align(ta, LV_ALIGN_TOP_MID, 0, 10);
  lv_obj_add_event_cb(ta, textarea_event_handler, LV_EVENT_READY, ta);

  // assign object to group
  lv_group_add_obj(input_grp, ta);
}
```

Keypad callback:
```c
void keypad_read(lv_indev_drv_t * drv, lv_indev_data_t*data){
  char key = keypad.getKey();
  printf("KEY: %c\n", key);

  data->key = (uint32_t)key;

  if(key) data->state = LV_INDEV_STATE_PR;
  else data->state = LV_INDEV_STATE_REL;

  // return false; /*No buffering now so no more data read*/
}
```

### Expected behavior
When the keypad is pressed, the input device callback should be called.
The documentation says that the callback function will be called frequently. Do I have to call it manually?

**Comment by kisvegabor** [comment]
Are you sure the textarea is focused? 

Please call `lv_group_focus_obj(textarea);` to be sure the ta is focused.

**Comment by tranvnhan** [comment]
>Are you sure the textarea is focused?
>
>Please call lv_group_focus_obj(textarea); to be sure the ta is focused.

Hi. The ta is focused correctly.
I found out that the problem is due to I declared `keypad_indev` inside `setup()`.
When I declare it as a global variable, the program can run appropriately.

```c
// Declare as global variable
static lv_indev_t * keypad_indev;
```

I can now use the keypad to control the display.
I will close the issue now.
Thanks.
