### ISSUE TITLE
How not to send LV_EVENT_CLICKED when the touch screen slides

### ISSUE THREAD

**Issue by qinshijing** [kisvegabor/lvgl#4208]
### Introduce the problem

In a touch screen scenario, the user presses a button, but the user expects no LV_EVENT_CLICKED to be generated after moving the finger.

### Examples and cases

Although I can add a piece of code like the following to each event response, it doesn't feel very elegant.
//////////////////////////////////////////
    case LV_EVENT_CLICKED: 
        lv_indev_t* indev = lv_event_get_indev(e);
        if (!indev || LV_ABS(indev->proc.types.pointer.scroll_sum.x)
                >= LV_INDEV_DEF_SCROLL_LIMIT
            || LV_ABS(indev->proc.types.pointer.scroll_sum.y)
                >= LV_INDEV_DEF_SCROLL_LIMIT) {
            sr_info("be scrolled, not click.\n");
            return;
        }
//////////////////////////////////////////
### Suggested solution

How about adding it directly in lv_indev.c? Or is there a better way?
//////////////////////////////////////////
         if (proc->types.pointer.scroll_sum.x <= LV_INDEV_DEF_SCROLL_LIMIT
                && proc->types.pointer.scroll_sum.y <= LV_INDEV_DEF_SCROLL_LIMIT)
                lv_event_send(indev_obj_act, LV_EVENT_CLICKED, indev_act);
//////////////////////////////////////////

**Comment by kisvegabor** [comment]
If you still press the button while moving your finger, I think it makes sens to click the button. See 
![click](https://user-images.githubusercontent.com/7599318/236858194-564fb143-024a-4431-bdd5-80feda22e921.gif)

However if you mean that when you keep the button pressed and move your finger out of the button and don't want to send a clicked event when you release the screen out of the button, you can use `lv_obj_clear_flag(btn, LV_OBJ_FLAG_PRESS_LOCK);`.

**Comment by qinshijing** [comment]
Yes, it should be reasonable if the finger does not move obj to generate clicked. But there is a scenario where the user's finger does not leave obj, but the finger movement distance occurs. I want to use short_clicked to handle this kind of scene, but short_clicked only has time judgment, no distance judgment. When there is a gesture response and short_clicked scene, if no gesture is triggered, short_clicked will be generated, so you think the short_clicked event increases the scroll_sum judgment reasonable?

**Comment by kisvegabor** [comment]
I'd like to understand the scenario when this kind of judgement is required. Could you describe your use-case?
