### ISSUE TITLE
lv_img_src_get_type is not returning correctly to big endian plataform

### ISSUE THREAD

**Issue by jadergn** [kisvegabor/lvgl#4209]
### Perform all steps below and tick them with [x]
- [X] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The function lv_img_src_get_type use the first byte to determinate the source of the image, when the plataform is little and the image source is LV_IMG_SRC_VARIABLE the first byte us the fields cf+always_zero of the struct lv_img_header_t, but for a big endian plataform this struct is inverted and this fields is the fourth byte, the first byte is part of imagem height.
```c
#if LV_BIG_ENDIAN_SYSTEM
typedef struct {

    uint32_t h : 11; /*Height of the image map*/
    uint32_t w : 11; /*Width of the image map*/
    uint32_t reserved : 2; /*Reserved to be used later*/
    uint32_t always_zero : 3; /*It the upper bits of the first byte. Always zero to look like a
                                 non-printable character*/
    uint32_t cf : 5;          /*Color format: See `lv_color_format_t`*/

} lv_img_header_t;
#else
typedef struct {

    uint32_t cf : 5;          /*Color format: See `lv_color_format_t`*/
    uint32_t always_zero : 3; /*It the upper bits of the first byte. Always zero to look like a
                                 non-printable character*/

    uint32_t reserved : 1; /*Reserved to be used later*/
    uint32_t chroma_keyed : 2; /*Reserved to be used later*/

    uint32_t w : 11; /*Width of the image map*/
    uint32_t h : 11; /*Height of the image map*/
} lv_img_header_t;
#endif
```
```c
lv_img_src_t lv_img_src_get_type(const void * src)
{
    lv_img_src_t img_src_type = LV_IMG_SRC_UNKNOWN;

    if(src == NULL) return img_src_type;
    const uint8_t * u8_p = src;

    /*The first byte shows the type of the image source*/
    if(u8_p[0] >= 0x20 && u8_p[0] <= 0x7F) {
        img_src_type = LV_IMG_SRC_FILE; /*If it's an ASCII character then it's file name*/
    }
    else if(u8_p[0] >= 0x80) {
        img_src_type = LV_IMG_SRC_SYMBOL; /*Symbols begins after 0x7F*/
    }
    else {
        img_src_type = LV_IMG_SRC_VARIABLE; /*`lv_img_dsc_t` is draw to the first byte < 0x20*/
    }

    if(LV_IMG_SRC_UNKNOWN == img_src_type) {
        LV_LOG_WARN("unknown image type");
    }

    return img_src_type;
}
```
I found this bug trying to run the canvas example, but only works if the canvas buffer height is less then 256, this happing because if the height is 255, the field height is 00011111111(11bits), and the first byte is 00011111(0x1F), in this case is less then 0x20 and 0x80 so the function sets  `img_src_type = LV_IMG_SRC_VARIABLE`, but if the height is 256  the height is 00100000000(11bits), and the first byte is 00100000(0x20), and in this case  `img_src_type = LV_IMG_SRC_FILE`. 
But the information that need to be used to calculate the imagem source is the fields cf+always_zero.

Possible solution(worked for me):
```c
lv_img_src_t lv_img_src_get_type(const void * src)
{
    lv_img_src_t img_src_type = LV_IMG_SRC_UNKNOWN;

    if(src == NULL) return img_src_type;
    const uint8_t * u8_p = src;

    /*The first byte shows the type of the image source*/
#if LV_BIG_ENDIAN_SYSTEM
    if(u8_p[3] >= 0x20 && u8_p[3] <= 0x7F) {
#else
    if(u8_p[0] >= 0x20 && u8_p[0] <= 0x7F) {
#endif
        img_src_type = LV_IMG_SRC_FILE; /*If it's an ASCII character then it's file name*/
    }
#if LV_BIG_ENDIAN_SYSTEM
    else if(u8_p[3] >= 0x80) {
#else
    else if(u8_p[0] >= 0x80) {
#endif
        img_src_type = LV_IMG_SRC_SYMBOL; /*Symbols begins after 0x7F*/
    }
    else {
        img_src_type = LV_IMG_SRC_VARIABLE; /*`lv_img_dsc_t` is draw to the first byte < 0x20*/
    }

    if(LV_IMG_SRC_UNKNOWN == img_src_type) {
        LV_LOG_WARN("unknown image type");
    }

    return img_src_type;
}
```
### To Reproduce

Run this canvas example in big endian plataform (need to set LV_BIG_ENDIAN_SYSTEM to 1) and change `CANVAS_HEIGHT` to 256
https://github.com/lvgl/lvgl/blob/e19410f8f8a256609da72cff549598e0df6fa4cf/examples/widgets/canvas/lv_example_canvas_1.c

### Expected behavior

Show the canvas on the screen, but for me it shows a white screen, if you change the `CANVAS_HEIGHT` to 255 the example works.

**Comment by kisvegabor** [comment]
Hi,

I can't imagine a better solution either.  Could you send a Pull request with the suggest fix for the `release/v8.3` branch?
