### ISSUE TITLE
lv_scale

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#4210]
### Introduce the problem
I'm currently working on the horizontal `lv_scale` widget and getting familiar with the drawing mechanisms of LVGL. It seems like the drawing gets masked in the red stroke, is that the correct term?

Here the tick starts at 25 and has 10 ticks, with major ticks every 5. You can see only the 5 of the 25 number on the far left, where 25 is expected

![imagen](https://user-images.githubusercontent.com/11037705/236701024-43374df8-baa8-41e6-b7cd-ffc65788f8dd.png)

### Examples and cases
None

### Suggested solution
Current implementation here: https://github.com/C47D/lvgl/tree/lv_scale

**Comment by kisvegabor** [comment]
Hi Carlos,

Be default the widgets can't draw outside of their coordinates.  The add some extra draw area you need to use the `LV_EVENT_REFR_EXT_DRAW_SIZE` event. See an example here https://docs.lvgl.io/8.3/examples.html#slider-with-extended-drawer

**Comment by kisvegabor** [comment]
Let's continue in the PR: https://github.com/lvgl/lvgl/pull/4196
