### ISSUE TITLE
LV_STYLE_FLEX_GROW is not a registered property

### ISSUE THREAD

**Issue by billybednar** [kisvegabor/lvgl#4214]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The style `LV_STYLE_FLEX_GROW` is never registered and has the default id of 0 / `LV_STYLE_PROP_INV`.

https://github.com/lvgl/lvgl/blob/64009fec232e5aeba660cf5afeabb2cc25aa0ac8/src/layouts/flex/lv_flex.c#L67-L76
https://github.com/lvgl/lvgl/blob/64009fec232e5aeba660cf5afeabb2cc25aa0ac8/src/layouts/flex/lv_flex.c#L98-L106

It appears that the lack of registration with the `LV_STYLE_PROP_FLAG_LAYOUT_UPDATE` flag results in the parent not being invalidated when this property changes. The manual invalidation in `lv_obj_set_flex_grow` should no longer be needed once the property is properly registered.

https://github.com/lvgl/lvgl/blob/64009fec232e5aeba660cf5afeabb2cc25aa0ac8/src/layouts/flex/lv_flex.c#L123-L127

Perhaps an assertion that property is not invalid in `lv_style_set_prop_internal` would be helpful.

**Comment by kisvegabor** [comment]
Thank you for reporting it. I've pushed a fix to both `master` and `release/v8.3`. 

I've also added an assert in a43748ea3 as you have suggested.
