### ISSUE TITLE
Regarding the issue of some driver chips requiring even row and column addresses or related lengths.

### ISSUE THREAD

**Issue by snoooopy** [kisvegabor/lvgl#4217]
### Introduce the problem

I am working on the driver of the chip RM67162/RM69330. The user manual describes "The SC [9:0] and EC [9:0] - SC [9:0]+1 must be visible by 2."
![1](https://github.com/lvgl/lvgl/assets/20832172/e64d627c-268d-4923-93dc-a40260dae9f4)

How should this be handled in Lvgl? The current display of Spinner or screen refresh is incorrect, as shown in the following image.
![2](https://github.com/lvgl/lvgl/assets/20832172/8e6c664c-fa4a-4b58-aedb-635ed64aeed9)

**Comment by kisvegabor** [comment]
Hi,

You can use the `rounder_cb`. See [here](https://docs.lvgl.io/8.3/porting/display.html).

**Comment by snoooopy** [comment]
> Hi,
> 
> You can use the `rounder_cb`. See [here](https://docs.lvgl.io/8.3/porting/display.html).

It's really helpful. Thank you so much. I have modified the round_cb according to the requirements of the driver chip,and  the screen is working properly now!
![3](https://github.com/lvgl/lvgl/assets/20832172/7f8e60dc-94c5-46cd-95f1-783edf575ac4)

**Comment by kisvegabor** [comment]
Great! :)

**Comment by Robox-Robotics** [comment]
Hello @snoooopy , I'm developing a smartwatch based on the same display I bought from Alibaba. Can you help me with steps you followed to make the custom driver for RM69330?
