### ISSUE TITLE
Textarea does not work properly with pointer type input devices in grid navigation

### ISSUE THREAD

**Issue by yinntian** [kisvegabor/lvgl#4225]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When POINTER input devices click on a textarea managed by grid navigation, only the cursor blinks, but the KEYPAD input device cannot enter text on it

### To Reproduce
```c
void test() {
    lv_group_t * g = lv_group_get_default();

    lv_obj_t * panel = lv_obj_create(lv_scr_act());
    lv_obj_center(panel);
    lv_obj_set_size(panel, lv_pct(50), lv_pct(50));
    lv_obj_set_flex_flow(panel, LV_FLEX_FLOW_COLUMN);
    lv_group_add_obj(g, panel);
    lv_gridnav_add(panel, LV_GRIDNAV_CTRL_ROLLOVER);

    lv_obj_t * btn_1 = lv_btn_create(panel);
    lv_obj_t * textarea_1 = lv_textarea_create(panel);
    lv_obj_t * textarea_2 = lv_textarea_create(panel);
    lv_obj_t * btn_2 = lv_btn_create(panel);
}
```

### Expected behavior
textarea responds correctly to POINTER input device focus under grid navigation

### Screenshots or video
![1](https://github.com/lvgl/lvgl/assets/92867869/ad826163-334e-4f21-bda0-462c5ca9f825)

**Comment by kisvegabor** [comment]
Hi,

it works well here in v8.3. Which LVGL version do you use?

![ta](https://github.com/lvgl/lvgl/assets/7599318/6a5de755-67f1-4fa3-9fa2-3513026716a8)

**Comment by yinntian** [comment]
I'm sorry, I forgot to remove textarea from the default group, I don't use the default group in my code, so I should add these lines at the end, my version is 8.3.3
```c
    lv_group_remove_obj(btn1);
    lv_group_remove_obj(btn2);
    lv_group_remove_obj(textarea_1);
    lv_group_remove_obj(textarea_2);
```

**Comment by kisvegabor** [comment]
I see now and it's tricky corner case. 

You can do 2 things:
- `lv_obj_clear_flag(textarea1, LV_OBJ_FLAG_CLICK_FOCUSABLE);` after this the textareas wont be focused on click
- add an `LV_EVENT_FOCUSED` event callback to the text areas in which you call `lv_gridnav_set_focused(panel, lv_event_get_target(e), LV_ANIM_OFF);` to manually make the clicked (focused) item as the focused gridnav item.

**Comment by yinntian** [comment]
The suggestion you gave me seems a bit problematic, there will still be two textareas in focus at the same time. However, I found a workaround that required group-focused settings for container objects in event callbacks.

Here is the complete code
```c
void textarea_handle(lv_event_t * e){
    lv_obj_t * cont = lv_event_get_user_data(e);
    lv_obj_t * obj = lv_event_get_target(e);
    lv_group_focus_obj(cont);
    lv_gridnav_set_focused(cont, obj, LV_ANIM_OFF);
}

void test() {
    lv_group_t * g = lv_group_get_default();

    lv_obj_t * panel = lv_obj_create(lv_scr_act());
    lv_obj_center(panel);
    lv_obj_set_size(panel, lv_pct(50), lv_pct(50));
    lv_obj_set_flex_flow(panel, LV_FLEX_FLOW_COLUMN);
    lv_group_add_obj(g, panel);
    lv_gridnav_add(panel, LV_GRIDNAV_CTRL_ROLLOVER);

    lv_obj_t * btn_1 = lv_btn_create(panel);
    lv_obj_t * textarea_1 = lv_textarea_create(panel);
    lv_obj_t * textarea_2 = lv_textarea_create(panel);
    lv_obj_t * btn_2 = lv_btn_create(panel);

    lv_group_remove_obj(btn1);
    lv_group_remove_obj(btn2);
    lv_group_remove_obj(textarea_1);
    lv_group_remove_obj(textarea_2);

    lv_obj_clear_flag(textarea_1, LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_clear_flag(textarea_2, LV_OBJ_FLAG_CLICK_FOCUSABLE);
}
```
