### ISSUE TITLE
feat(sdl): add a way for user to define applications exit directly or not while close window

### ISSUE THREAD

**Issue by hanhsuan** [kisvegabor/lvgl#4250]
### Introduce the problem

If using SDL backend, it will stop whole application while close the window. 

```c
        if(event.type == SDL_QUIT) {
            SDL_Quit();
            lv_timer_del(event_handler_timer);
            exit(0);
        }
```

### Examples and cases

I would like to create an application that pops up the GUI for user to input or check some information then close GUI and run in the back ground. 

### Suggested solution

It maybe able to add new configuration in `lv_conf.h`, such as 

```c
#define LV_SDL_DIRECT_EXIT      1
```

and in `static void sdl_event_handler(lv_timer_t * t)` of `lv_sdl_window.c`

```c
        if(event.type == SDL_QUIT) {
            SDL_Quit();
            lv_timer_del(event_handler_timer);
            lv_disp_t * disp = _lv_sdl_get_disp_from_win_id(event.window.windowID);
            if(disp != NULL)
            {
                lv_disp_remove(disp);
            }
#if LV_SDL_DIRECT_EXIT
            exit(0);
#else
            break;
#endif
        }
```

to give a way for `lvgl` user to define what kind behavior they would like to.

**Comment by kisvegabor** [comment]
It's a good idea, I've just added it.
