### ISSUE TITLE
lv_line_t not properly aligned with custom line_width

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#4251]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce
Simply test the below code in online python simulator https://sim.lvgl.io/v9.0/micropython/ports/javascript/
I want to draw a line of width=50 and center it in screen, but it's not centered horizontally nor vertically.
But if I change line width=1, it's looks perfectly centered
```python
import lvgl as lv
import display_driver

line = lv.line(lv.scr_act())
line.align(lv.ALIGN.CENTER, 0, 0)
line.set_points([{'x':0, 'y':0}, {'x':200, 'y':0}], 2)
line.set_style_line_width(50, 0)
```
Same result tested with release/v8.3 in C
Same with https://github.com/lvgl/lv_port_win_codeblocks in win10, but I think it's not using latest version of lvgl.
```c
    static lv_obj_t* line;
    line = lv_line_create(lv_scr_act());
    lv_obj_set_style_line_width(line, 50, 0);
    static lv_point_t ln_pts[] = {{0, 0}, {200, 0}};
    lv_line_set_points(line, ln_pts, 2);
    lv_obj_align(line, LV_ALIGN_CENTER, 0,0);
```
### Expected behavior
The line alignment should take line width into account.

### Screenshots or video
![image](https://github.com/lvgl/lvgl/assets/44317361/a2e84dba-987d-41b0-8647-f7d3643a8eba)

![image](https://github.com/lvgl/lvgl/assets/44317361/ee3c310c-3e11-4109-b27e-78ed76eaba44)

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it!
