### ISSUE TITLE
How to achieve video playback

### ISSUE THREAD

**Issue by xuzfa** [kisvegabor/lvgl#4257]
I want to directly play videos in MP4 format. Can it be achieved now?

**Comment by kisvegabor** [comment]
We have [ffmpeg](https://docs.lvgl.io/8.3/libs/ffmpeg.html) support MPUs. For MCUs we don't have a ready to use solution now, but you can use any open source video decoder with and show the rendered frame as an `lv_img`.


---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
