### ISSUE TITLE
Problem with inclusion of files in the library

### ISSUE THREAD

**Issue by Kamylosp** [kisvegabor/lvgl#4260]
### Introduce the problem

I'm trying to compile the code in Arduino IDE but it's not compiling. The problem seems to be happening in the inclusion of some files of the library. I searched for solutions but I found anything.

### Examples and cases
![image](https://github.com/lvgl/lvgl/assets/80530580/aba1f6ee-77b7-475f-b8e1-44d74e685ca9)

![image](https://github.com/lvgl/lvgl/assets/80530580/d41fcf23-f801-481e-8a00-eb656d28ee14)

### Suggested solution

I don't have an ideia for the solution of the problem.

**Comment by kisvegabor** [comment]
Hi,

Have you followed the steps here?
https://docs.lvgl.io/8.3/get-started/platforms/arduino.html
