### ISSUE TITLE
Corrupted display on unhide/hide flag

### ISSUE THREAD

**Issue by mmar22** [kisvegabor/lvgl#4268]
Reported https://forum.lvgl.io/t/troubles-with-layered-objects/11947

Additional info log level INFO enabled no warnings. No relevant info.
v 8.3.7
Platformio
ESP32

**Comment by kisvegabor** [comment]
I've answered on the Forum

**Comment by mmar22** [comment]
OK but this is bug and forum dont have bug part

**Comment by kisvegabor** [comment]
I doubt that it's really a bug in LVGL as the hide feature is used a lot and a lot of people would have reported if it wasn't working well.

**Comment by mmar22** [comment]
I agree YES and NO
1. Only some uses DMA drivers. And bug is partly in lovyan
2. LVGL part of bug is that calling set changes on invisible objects invoke flush_cb. You can test Hide bar aside other object and call update random value into bar .

Perfect will be when lvgl create driver for ESP i80 with right DMA.

**Comment by kisvegabor** [comment]
To keep the discussion on one place I'll reply in the Forum.
