### ISSUE TITLE
LVGL Micropython with Raspberry Pi Pico

### ISSUE THREAD

**Issue by MishalJasmine** [kisvegabor/lvgl#4282]
I am currently trying to use the LVGL in  micropython for Raspberry Pi Pico. I am using a Windows system. I followed these steps:

1. git clone https://github.com/lvgl/lv_micropython.git
2. cd lv_micropython
3. git submodule update --init --recursive lib/lv_bindings
4. make -C ports/rp2 BOARD=PICO submodules
5. make -j -C mpy-cross

I am getting this error 

`
make: Entering directory 'C:/Users/xxxx/lv_micropython/mpy-cross' `
`Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.`
`process_begin: CreateProcess(NULL, uname -s, ...) failed.`
`Makefile:10: pipe: No error`
`FIND: Parameter format not correct`
`Access denied - ../LIB/LV_BINDINGS/LVGL/SRC`
`Access denied - ../LIB/LV_BINDINGS/LVGL/EXAMPLES`
`Access denied - ../LIB/LV_BINDINGS/DRIVER/GENERIC`
`File not found - -TYPE`
`File not found - F`
`File not found - -NAME`
`"LVGL-GEN build/lvgl/lv_mpy.c"`
`The syntax of the command is incorrect.`
`make: *** [../py/py.mk:46: build/lvgl/lv_mpy.c] Error 1`
`make: Leaving directory 'C:/Users/xxxx/lv_micropython/mpy-cross'`

How do I resolve this issue?

**Comment by kisvegabor** [comment]
I cc @amirgon and @uraich who know more about MicroPython.

**Comment by amirgon** [comment]
@MishalJasmine - What's the point in duplicating the same questions in 3 places?
You also asked it [on the forum](https://forum.lvgl.io/t/unable-to-build-lvgl-micropython-for-rp/11983) and [on lv_binding_micropython](https://github.com/lvgl/lv_binding_micropython/issues/280)...

I suggest we continue this discussion in a single place - the forum.
Did you try starting with Micropython without LVGL, as you were suggested?
