### ISSUE TITLE
Why's a checkbox scrollable?

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#4283]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

In the demo/keypad_encoder example, the checkbox behaves differently from the switch. they both are binary state widgets. but if you use encoder indev, the checkbox has to enter into editing mode before you can change its state.
I think you forget to clear scrollable flag on its creation .
see
https://github.com/lvgl/lvgl/blob/master/src/widgets/checkbox/lv_checkbox.c#L136
https://github.com/lvgl/lvgl/blob/master/src/widgets/switch/lv_switch.c#L94

**Comment by kisvegabor** [comment]
You are perfectly right. I've just fixed it as you have suggested.
