### ISSUE TITLE
How to make a global page but it does matter other pages

### ISSUE THREAD

**Issue by steveluo01** [kisvegabor/lvgl#4288]
Mr.kisvegabor
### Introduce the problem

I want to display a page to set the volume and light.
I hope that on all pages, events can be triggered by sliding down the screen to display the page I want.

And I think I can use lv_layer_sys(), but the global page will override the buttons below. Can you help me?

**Comment by kisvegabor** [comment]
Hi,
 
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

Please also specify more details:
- LVGL version
- I don't really understand this: "the global page will override the buttons below.". Could you describe it in more detail?

You can link the form topic here, and I'll take a look.
