### ISSUE TITLE
LV_FONT_MONTSERRAT_12_SUBPX not rendering properly

### ISSUE THREAD

**Issue by brentru** [kisvegabor/lvgl#4291]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Hi @kisvegabor  - I'm using `LV_FONT_MONTSERRAT_12_SUBPX` on hardware and it is rendering incorrectly while `LV_FONT_MONTSERRAT_12` renders as-expected

This works fine on the simulator but when transferring to hardware (Adafruit FunHouse ESP32-S2 running LVGL_Glue and a pinned version of LVGL 8.2), the results are not the same as the simulator.

### To Reproduce

Provide a small, independent code sample that can be used to reproduce the issue.
Ideally this should work in the PC simulator unless the problem is specific to a platform.
Format the code like this:
```c
  consoleLabel = lv_label_create(lv_scr_act());
  lv_obj_align(consoleLabel, LV_ALIGN_BOTTOM_LEFT, 3, 0);
  lv_obj_set_width(consoleLabel, 230);
  lv_label_set_long_mode(consoleLabel, LV_LABEL_LONG_WRAP);
  static lv_style_t styleConsoleLabel;
  lv_style_init(&styleConsoleLabel);
  lv_style_set_text_color(&styleConsoleLabel, lv_color_white());
  lv_style_set_text_font(&styleConsoleLabel, &lv_font_montserrat_12_subpx);
  lv_obj_add_style(consoleLabel, &styleConsoleLabel, LV_PART_MAIN);
  lv_label_set_text_static(consoleLabel, textBuffer);
  lv_obj_move_background(consoleLabel);
```

LV Configuration, font region:
```
/*==================
 *   FONT USAGE
 *===================*/

/*Montserrat fonts with ASCII range and some symbols using bpp = 4
 *https://fonts.google.com/specimen/Montserrat*/
#define LV_FONT_MONTSERRAT_8 0
#define LV_FONT_MONTSERRAT_10 1
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_24 0
#define LV_FONT_MONTSERRAT_26 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_30 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_34 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_38 0
#define LV_FONT_MONTSERRAT_40 0
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_44 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 0

/*Demonstrate special features*/
#define LV_FONT_MONTSERRAT_12_SUBPX 1
#define LV_FONT_MONTSERRAT_28_COMPRESSED 0 /*bpp = 3*/
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW                                       \
  0 /*Hebrew, Arabic, Perisan letters and all their forms*/
#define LV_FONT_SIMSUN_16_CJK 0 /*1000 most common CJK radicals*/

/*Pixel perfect monospace fonts*/
#define LV_FONT_UNSCII_8 0
#define LV_FONT_UNSCII_16 0

/*Optionally declare custom fonts here.
 *You can use these fonts as default font too and they will be available
 *globally. E.g. #define LV_FONT_CUSTOM_DECLARE   LV_FONT_DECLARE(my_font_1)
 *LV_FONT_DECLARE(my_font_2)*/
#define LV_FONT_CUSTOM_DECLARE

/*Always set a default font*/
#define LV_FONT_DEFAULT &lv_font_montserrat_14

/*Enable handling large font and/or fonts with a lot of characters.
 *The limit depends on the font size, font face and bpp.
 *Compiler error will be triggered if a font needs it.*/
#define LV_FONT_FMT_TXT_LARGE 0

/*Enables/disables support for compressed fonts.*/
#define LV_USE_FONT_COMPRESSED 0

/*Enable subpixel rendering*/
#define LV_USE_FONT_SUBPX 1
#if LV_USE_FONT_SUBPX
/*Set the pixel order of the display. Physical order of RGB channels. Doesn't
 * matter with "normal" fonts.*/
#define LV_FONT_SUBPX_BGR 0 /*0: RGB; 1:BGR order*/
#endif
```

### Screenshots or video

Using `LV_FONT_MONTSERRAT_12_SUBPX`:
![IMG_3783](https://github.com/lvgl/lvgl/assets/322428/0a310feb-eced-4fd9-824f-8505d9777af7)

Using `LV_FONT_MONTSERRAT_12`:
![IMG_3785](https://github.com/lvgl/lvgl/assets/322428/541d014f-45b0-4dbe-b82b-7084c1906dd8)

**Comment by kisvegabor** [comment]
Hi,

Unfortunately I couldn't reproduce the issue in the simulator either. :slightly_frowning_face:  

To fix it, it'd important to see the problem on my end too. To make the issue happen in the simulator, please be sure to use the same
- UI code
- color depth and LV_COLOR_16_SWAP settings
- draw buffer size

**Comment by brentru** [comment]
> color depth and LV_COLOR_16_SWAP settings, draw buffer size

Where are these found - in the configuration file or in the port?

**Comment by kisvegabor** [comment]
- color depth and LV_COLOR_16_SWAP settings: in `lv_conf.h`
- draw buffer size: in port

**Comment by daironxuan** [comment]
Yes, the PC is no problem, once on the hardware 'Chinese' will present � � � � Ҫ � ¨ squared � ѧ ϰ �...

The test screen is: TTFLCD, 240*320,

Whether it is defined using LV_FONT_DECLARE or not, it is still invalid!

**Comment by kisvegabor** [comment]
I'm sorry but I have now idea. If it's working in simulator, I can't do much to figure it out. :slightly_frowning_face:
