### ISSUE TITLE
Abnormal display of screen transparency setting

### ISSUE THREAD

**Issue by starstar222** [kisvegabor/lvgl#4292]
### Describe the bug

The code runs well and displays normally without setting transparency.
Here are two methods I tried to set the bottom screen to be completely transparent：
1. 
```c
    lv_obj_t * scr = lv_scr_act();
    lv_obj_remove_style_all(scr);
    lv_obj_set_style_bg_opa(scr, LV_OPA_TRANSP, 0);
```
After running this code, there will be a problem with the widget dragging downwards.
2. 
```c
    lv_color32_t color32={ 0x00,0xff,0x00,0x00};  // green and completely transparent.
    lv_obj_t * scr = lv_scr_act();
    lv_obj_remove_style_all(scr);
    lv_obj_set_style_bg_color(scr, color32, LV_PART_MAIN);

    meter = lv_meter_create(lv_scr_act());
    lv_obj_center(meter);
    lv_obj_set_size(meter, 200, 200);
```
This code can achieve transparency, but there will be extra vertical lines in the background of the meter display.

### Screenshots or video

case 1:
![20230616-200431](https://github.com/lvgl/lvgl/assets/57593875/fab464a8-7796-4c61-9797-a3329747ea73)

case 2:
![20230616-200426](https://github.com/lvgl/lvgl/assets/57593875/c422ae29-68e9-4875-af2a-091ae385d849)

**Comment by kisvegabor** [comment]
Which LVGL version do you use?

**Comment by starstar222** [comment]
I tested both master branch(1bfdecf585bb50fbb22ed1c38450b5c9eb600196) and v8.3.0 and found issues, but v8.1.0 is normal

**Comment by kisvegabor** [comment]
In v8.3, did you set `LV_COLOR_SCREEN_TRANSP 1` in `lv_conf.h`?

**Comment by starstar222** [comment]
> In v8.3, did you set `LV_COLOR_SCREEN_TRANSP 1` in `lv_conf.h`?

Yes, I have set it up. Later, I tested version 8.3.7 and it worked normally after set `disp_drv.screen_transp = 1`

**Comment by kisvegabor** [comment]
Great! :blush:
