### ISSUE TITLE
esp32 lv_dropdown_create, erase test, reboot.

### ISSUE THREAD

**Issue by Red-Owl** [kisvegabor/lvgl#4300]
### Perform all steps below and tick them with [x]
- [x] ESP32 WT32-SC01 / Plus , Touch Screen
- [ ] esp32
- [x] 8.3

### Describe the bug
continuos reboot 

### To Reproduce
i have write  to crete  lv_dropdown_create and test test_replace_user,
lv_obj_t * USER_LIST;
lv_obj_t * us_user_list(lv_obj_t * cnt){
    /*Create a normal drop down list*/
    lv_obj_t * USER_LIST = lv_dropdown_create(cnt);
    lv_dropdown_set_options(USER_LIST, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");
    lv_obj_set_pos(USER_LIST, 5, 20);   /*Set its position*/
    lv_obj_set_size(USER_LIST, 140, 40);   /*Set its size*/
   
    lv_obj_add_event_cb(USER_LIST, event_user_list, LV_EVENT_ALL, NULL);
    return USER_LIST;
}

void test_replace_user(){
  // lv_dropdown_clear_options(USER_LIST);
   lv_dropdown_set_text(USER_LIST, "qApple\n"
                            "qBanana\n"
                            "qOrange\n"
                            "qCherry\n"
                            "qGrape\n"
                            "qRaspberry\n"
                            "qMelon\n"
                            "qOrange\n"
                            "qLemon\n"
                            "qNuts");  
}

-->

**Comment by kisvegabor** [comment]
Please format the code blocks like this:
````
```c
your 
code
here
```
````

and add the content of `event_user_list` too.

**Comment by Red-Owl** [comment]
''

```c
static void event_user_list(lv_event_t * e){
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        char buf[32];
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
        LV_LOG_USER("Option: %s", buf);
    }
}


lv_obj_t * USER_LIST;
lv_obj_t * us_user_list(lv_obj_t * cnt){
    /*Create a normal drop down list*/
    lv_obj_t * USER_LIST = lv_dropdown_create(cnt);
    lv_dropdown_set_options(USER_LIST, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");
    lv_obj_set_pos(USER_LIST, 5, 20);   /*Set its position*/
    lv_obj_set_size(USER_LIST, 140, 40);   /*Set its size*/
   
    lv_obj_add_event_cb(USER_LIST, event_user_list, LV_EVENT_ALL, NULL);
    return USER_LIST;
}


void test_replace_user(){
  // lv_dropdown_clear_options(USER_LIST); 
   lv_dropdown_set_options(USER_LIST, "qApple\n"
                            "qBanana\n"
                            "qOrange\n"
                            "qCherry\n"
                            "qGrape\n"
                            "qRaspberry\n"
                            "qMelon\n"
                            "qOrange\n"
                            "qLemon\n"
                            "qNuts");  
}

```

''

**Comment by kisvegabor** [comment]
I've tested in and found a small mistake.

You have `  lv_obj_t * USER_LIST;` both as a local and a global variable. You should do this:
```c

lv_obj_t * USER_LIST;
lv_obj_t * us_user_list(lv_obj_t * cnt){
    /*Create a normal drop down list*/
    //lv_obj_t * USER_LIST = lv_dropdown_create(cnt); 
    USER_LIST = lv_dropdown_create(cnt);
   
    lv_dropdown_set_options(USER_LIST, "Apple\n"
                            "Banana\n"
                            "Orange\n"
                            "Cherry\n"
                            "Grape\n"
                            "Raspberry\n"
                            "Melon\n"
                            "Orange\n"
                            "Lemon\n"
                            "Nuts");
    lv_obj_set_pos(USER_LIST, 5, 20);   /*Set its position*/
    lv_obj_set_size(USER_LIST, 140, 40);   /*Set its size*/
   
    lv_obj_add_event_cb(USER_LIST, event_user_list, LV_EVENT_ALL, NULL);
    return USER_LIST;
}
```

**Comment by Red-Owl** [comment]
YES error in my code, your full funcion tranks
