### ISSUE TITLE
Changing style to btnmatrix when a button is pressed

### ISSUE THREAD

**Issue by HaoboGu** [kisvegabor/lvgl#4301]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I want to change the btnmatrix pressed style when one of the buttons in the btnmatrix is pressed. 
Use `lv_obj_add_style(btn_matrix, &style_btn_pressed,
                     LV_PART_ITEMS | LV_STATE_CHECKED)` cannot do this
### To Reproduce

```c

    static lv_style_t style_btn;
    lv_style_init(&style_btn);
    lv_style_set_bg_opa(&style_btn, LV_OPA_10);

    static lv_style_t style_btn_pressed;
    lv_style_init(&style_btn_pressed);
    lv_style_set_bg_opa(&style_btn_pressed, LV_OPA_100);
    btn_matrix = lv_btnmatrix_create(main_scr);
    lv_btnmatrix_set_map(btn_matrix, btn_map);
    lv_obj_add_style(btn_matrix, &style_btn, LV_PART_ITEMS);  
    lv_obj_add_style(btn_matrix, &style_btn_pressed,
                     LV_PART_ITEMS | LV_STATE_CHECKED);  
    lv_obj_add_style(btn_matrix, &style_btn_pressed,
                     LV_PART_ITEMS | LV_STATE_PRESSED); 
    lv_obj_add_style(btn_matrix, &style_btn,
                     LV_PART_ITEMS | LV_STATE_FOCUSED);  
```

### Expected behavior

The pressed button's style is changed to style_btn_pressed

**Comment by kisvegabor** [comment]
It looks like this for me, which seems correct based on the styles you add.

![btnm](https://github.com/lvgl/lvgl/assets/7599318/a02baba6-c851-4b3f-8dca-a760bfb6f3cc)


Do you see the same result?

**Comment by HaoboGu** [comment]
Could you try `lv_style_set_transform_height(&style_btn_pressed, 10);` or `lv_style_set_height(&style_btn_pressed, 10);`? The button size is not changed

**Comment by kisvegabor** [comment]
Yes, it's because the coordinates of the buttons are set automatically. See here: https://docs.lvgl.io/8.3/widgets/core/btnmatrix.html#control-buttons

**Comment by HaoboGu** [comment]
Okay, so manually changing the size of buttons in a btnmatrix using `lv_style_set_size` will not work.

I also tried to make the btnmatrix scrolling, the background is also scrolled with the btnmatrix. It seems that the actual scrolled obj is background. If so, is there a way to scroll btnmatrix only(leaving background unchanged)? 

<img width="297" alt="image" src="https://github.com/lvgl/lvgl/assets/8640918/8063e2ab-fd37-40c6-b841-3a8714472f83">

**Comment by kisvegabor** [comment]
How did you make it scrollable? Please attach a short codesnippet.

**Comment by HaoboGu** [comment]
I just set the height of the btnmatrix larger than the background and screen size. Here is the code:
```c
btn_matrix_screen = lv_obj_create(NULL);
lv_obj_set_size(btn_matrix_screen, 300, 200);

btn_matrix = lv_btnmatrix_create(btn_matrix_screen);
lv_btnmatrix_set_map(btn_matrix, btn_map);
lv_obj_set_size(btn_matrix, 320, 300);
lv_obj_scroll_to_x(btn_matrix, 0, LV_ANIM_OFF);
lv_obj_align(btn_matrix, LV_ALIGN_TOP_MID, 0, 0);
```

**Comment by kisvegabor** [comment]
In this case really the background (i.e. the screen) will be scrollable. However you shouldn't change the size of the screen. The screen is always display sized.

**Comment by HaoboGu** [comment]
@kisvegabor thanks for the explanation! If I want to achieve btnmatrix scrolling, and keep background unchanged, what's the best way?

**Comment by kisvegabor** [comment]
You can wrap the button matrix into an `lv_obj` and make the background of the btnmatrix transparent:
```c
static const char * btnm_map[] = {"1", "2", "3", "4", "5", "\n",
                                  "6", "7", "8", "9", "0", "\n",
                                  "Action1", "Action2", ""
                                 };

void lv_example_btnmatrix_1(void)
{
    lv_obj_t * wrapper = lv_obj_create(lv_scr_act());
    lv_obj_set_size(wrapper, 300, 200);

    lv_obj_t * btnm1 = lv_btnmatrix_create(wrapper);
    lv_obj_set_size(btnm1, 400, 150);
    lv_obj_set_style_bg_opa(btnm1, 0, 0);
    lv_obj_set_style_border_opa(btnm1, 0, 0);

    lv_btnmatrix_set_map(btnm1, btnm_map);
```

![btnm_scroll](https://github.com/lvgl/lvgl/assets/7599318/31ef0975-143e-43a4-a0ce-1a0f516a990d)


I've never tried a scrolling button matrix and as you can see there is an issue while scroll it the buttons are activated. I've just pushed a fixed for it, so it should work normally now.

**Comment by HaoboGu** [comment]
Thanks very much! It worked as expected.

**Comment by HaoboGu** [comment]
> I've never tried a scrolling button matrix and as you can see there is an issue while scroll it the buttons are activated. I've just pushed a fixed for it, so it should work normally now.

I found this issue also exists when using gesture: 

https://github.com/lvgl/lvgl/assets/8640918/395208b2-d371-4c73-99ae-52131bcfec48

**Comment by HaoboGu** [comment]
@kisvegabor any updates?

**Comment by HaoboGu** [comment]
@kisvegabor Yes, I agree. 

I also tried on several devices, including my iPhone. No button is activated if my finger slides out of the button, the gesture/scroll can be triggered in this case.

**Comment by kisvegabor** [comment]
Great, I've pushed a fix to `master`.

**Comment by HaoboGu** [comment]
Thanks!
