### ISSUE TITLE
[v8.3][Docs] Display Software Rotation: Mention Incompatibility with `full_refresh` and `direct_mode`

### ISSUE THREAD

**Issue by kolliemo** [kisvegabor/lvgl#4304]
# [v8.3][Docs] Display Software Rotation: Mention Incompatibility with `full_refresh` and `direct_mode`

As far as I understand, software rotation is incompatible with using either `full_refresh` or `direct_mode`. Is that correct or am I misunderstanding something here?

It that is correct, what about adding a small mention of that to the [display porting docs](https://docs.lvgl.io/8.3/porting/display.html)? Personally, this has caused me quite a bit of confusion why my display would glitch when trying to rotate, until I found this mentioned in some github issues and some few forum threads, e.g.:

https://github.com/lvgl/lvgl/issues/4060#issuecomment-1486538873

https://github.com/lvgl/lvgl/issues/3829

https://forum.lvgl.io/t/framebuffer-refresh-problem/10043/6

**Comment by kisvegabor** [comment]
Hi,

I agree that it should be mentioned there. Could you send a pull request with this update?  You can just click the edit button at the top of the page.

**Comment by kolliemo** [comment]
Will do, just wanted to double check I didn't misunderstand, thanks!

**Comment by kisvegabor** [comment]
Merged, thank you!
