### ISSUE TITLE
How to simulate how RGB888 color gradient will look on RGB565 display

### ISSUE THREAD

**Issue by krupis** [kisvegabor/lvgl#4307]
### Introduce the problem

I am working with ST7789 1.9inch display based on ESP32-S3 Board. For painting and designing I use GIMP and Squareline Studio.
When I create some background image with gradient using GIMP (using RGB888), I would like to see how the gradient is going to look like on my RGB565 display before I flash it to save some time.

Most of the time, the gradient that I produce on RGB888 is not usable on RGB565 so I would like to save some time.

### Examples and cases

I recently created the following blueish/greenish gradient background image:
![green_blue](https://github.com/lvgl/lvgl/assets/22237034/8572895f-59f7-496a-a4c9-3d4a17fa1711)

It looked nice on Squareline studio:
![image](https://github.com/lvgl/lvgl/assets/22237034/08da3a97-f862-4f76-a6c2-66fcc2e16f67)

But when I flashed it to my device, it does not look good at all:
![blue_green](https://github.com/lvgl/lvgl/assets/22237034/e095e715-6e4f-41cc-a746-f8b6bdf94f9c)

You can see some stripes most likely where the display was not able to reproduce the color.

Is there any way on GIMP or Photoshop or any other too to simulate how my gradient is going to look like on my RGB565 display? Or even better, can I create UI design using RGB565 instead of RGB888 so I know how its going to look like

**Comment by kisvegabor** [comment]
It's really ugly on the real device. Or in reality is it better than on the photo?

It shouldn't be that much difference between the SLS and the real device.

**Comment by krupis** [comment]
Actually it looks much better on the photo than in reality.
In reality you have gray stripes where the gradient is transitioning colors.

I have enabled gradient dithering and installed GIMP plugin for dithering to RGB565 and that seem to improve the situation

**Comment by kisvegabor** [comment]
Are the other colors correct? Maybe there is a mismatch in `LV_COLOR_DEPTH` and the display's color format.

**Comment by krupis** [comment]
> Are the other colors correct? Maybe there is a mismatch in `LV_COLOR_DEPTH` and the display's color format.

I think other colors seem correct. LV_COLOR_DEPTH is set to 16 bit (RGB565) and my ST7789 display uses RGB565.


It might have been an issue with my gradient image. I only have been able to reproduce this issue with that particular gradient image, the other images are "decent". Il be sure to let you know if I manage to reproduce these strange stripes with any other images

**Comment by kisvegabor** [comment]
> Il be sure to let you know if I manage to reproduce these strange stripes with any other images

Okay, let's close this issue until then.
