### ISSUE TITLE
IMG Object Consulting

### ISSUE THREAD

**Issue by htk719809837** [kisvegabor/lvgl#4322]
Hello, when I use the img object in lvgl7.11, if my img object size is 100 X 100 and I give a 50 X 50 image, this image will be made four copies and filled into the 100 X 100 img object. How to turn off this autofill function, looking forward to your reply

**Comment by htk719809837** [comment]
There is another problem, I now use cont objects as follows, '()' represents the container, '口' represents the empty space, 'T' represents the text, 'O' represents the picture, 'O' is only one, 'T' may have multiple. The width of the outermost container is 1000. When the number of 'T' in my inner two subcontainers changes, I want to keep the width of the '口' on both sides of the two subcontainers and in the middle of the blank space the same. Can you provide an example?

It's equivalent to two child containers in my parent container, and no matter how long the child containers are, I always want them to be equally spaced on both sides and in the middle, right

Expected results:
（（口口OTT口）（口TO口口））
（（口口OTT口）（口TTO口口））
（（口口OT口）（口TTTO口口））

The only thing I can do with this container is as follows
（（口口OTT口口）（口口TO口口））

**Comment by htk719809837** [comment]
like this

**Comment by htk719809837** [comment]
![Uploading IMG_5984.jpeg…]()
like this

**Comment by htk719809837** [comment]
![IMG_5984](https://github.com/lvgl/lvgl/assets/62541077/7953e59c-8a3b-4e6a-9526-67a0e8481186)
like this

**Comment by kisvegabor** [comment]
In both LVGL v7 and v8 tiling the images if the container size is larger is the only supported scenario. 

Adding this layout thing would be much simpler in v8 where we have advanced layouts. So I wonder if you can update to v8.
