### ISSUE TITLE
Hello, in lvgl7.11, is there a way to scale jpg images?

### ISSUE THREAD

**Issue by htk719809837** [kisvegabor/lvgl#4325]
We have implemented a jpg decoder demo, want to try to scale the picture, but found that the picture can not scale, there is no way to scale the image in jpg format

**Comment by kisvegabor** [comment]
Scaling JPG is not supported either in v7 or v8. :slightly_frowning_face:

**Comment by htk719809837** [comment]
Are there plans to add this feature

**Comment by htk719809837** [comment]
Are there plans to add this feature

**Comment by kisvegabor** [comment]
Maybe in v9, but there some open questions regarding image handling in v9.
