### ISSUE TITLE
The Image Button widget does not respect the LV_OBJ_FLAG_CHECKABLE flag when configured with a single image.

### ISSUE THREAD

**Issue by pete-pjb** [kisvegabor/lvgl#4373]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The Image Button widget does not respect the LV_OBJ_FLAG_CHECKABLE flag when configured with a single image.

### To Reproduce

Format the code like this:
```c
void imgbtn_test( lv_obj_t *parent ) {

	LV_IMG_DECLARE( btn_press );
	LV_IMG_DECLARE( btn_release );
	LV_IMG_DECLARE( btn_dis );

    /*Create an image button*/
    lv_obj_t * imgbtn1 = lv_imgbtn_create(lv_scr_act());
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_RELEASED, NULL, &btn_release, NULL);
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_PRESSED, NULL, &btn_press, NULL);
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_DISABLED, NULL, &btn_dis, NULL);
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &btn_release, NULL);
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &btn_press, NULL);
    lv_imgbtn_set_src(imgbtn1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &btn_dis, NULL);

//    lv_obj_add_state( imgbtn1, LV_STATE_DISABLED );
    lv_obj_add_flag( imgbtn1, LV_OBJ_FLAG_CHECKABLE );
//    lv_obj_add_state( imgbtn1, LV_STATE_PRESSED );

}
```
### **NOTE:**
I have attached a zipped 'c' source file with the images also, just add it to the simulator project and call  ```imgbtn_test( lv_scr_act());```
### Expected behavior

The Image Button widget should respect the LV_OBJ_FLAG_CHECKABLE flag when configured with a single image and respond accordingly.
### Screenshots or video

N/A

I have taken a quick look at this but I am unable to see where it is going wrong at this point and I am not around for a few days now so if anyone else see what is happening that would be great!

Cheers,

Pete
[imgbtn_test.zip](https://github.com/lvgl/lvgl/files/12039742/imgbtn_test.zip)

**Comment by kisvegabor** [comment]
Hi Pete,

Thank you for reporting it. I've just pushed a fix. 

The image button has it's own state manager API so, I doesn't react on all `LV_STATE`, however supporting the `CHECKABLE` flag really makes sense. 

FYI, in v9 this widget will be removed and the `style_bg_img` property will be improved to work as a [9 patch image](https://medium.com/flobiz-blog/create-resizable-bitmaps-9-patch-files-48c774db4526). As it will work as style property all states will work normally.
