### ISSUE TITLE
Sets the default focused child component when scrolling is used

### ISSUE THREAD

**Issue by yel-best** [kisvegabor/lvgl#4376]
### Introduce the problem

When I use the scroll function, I set to allow horizontal scrolling. There are panel 1, panel 2, and panel 3 respectively. By default, panel 1 will be focused, but I want to set panel 2 as the default focus. Every time I enter this interface, I will see it first. It is panel 2, slide left and right to see panel 1 and panel 3 respectively

### Examples and cases

![image](https://github.com/lvgl/lvgl/assets/82205638/3dfe2e97-185f-48da-a9d6-121a9e278996)

### Suggested solution

Sorry, I didn't think of a good way, but I want to achieve this function and hope to get some suggestions or discussions,thanks.

**Comment by BestStark** [comment]
oh, `lv_obj_scroll_to_view(lv_obj_get_child(parent, 0), LV_ANIM_OFF); ` This method can. thanks

**Comment by BestStark** [comment]
But I found a strange problem. For example, I have three panels in the scrolling area, and one of the panels has a button. **When I click the button**, there will be a msgbox. When I click yes or no, the current entire scrolling area is activated after the event is triggered. Refresh, it will return to the last panel, what is the reason?

**Comment by kisvegabor** [comment]
> When I click yes or no, the current entire scrolling area is activated after the event is triggered. Refresh, it will return to the last panel, what is the reason?

I believe you have  set a default group with `lv_group_set_default`. Due to this all interactive elements (e.g. buttons) are automatically added to default group (so you can control them e.g. with a keyboard too).

When you delete the message box LVGL looks for a new widget to focus and it finds the last created widget, which is the last button. 

You can solve it by
- removing `lv_group_set_default`
- manually selecting which widget to focus when the message box is closed

**Comment by BestStark** [comment]
> > When I click yes or no, the current entire scrolling area is activated after the event is triggered. Refresh, it will return to the last panel, what is the reason?
> 
> I believe you have set a default group with `lv_group_set_default`. Due to this all interactive elements (e.g. buttons) are automatically added to default group (so you can control them e.g. with a keyboard too).
> 
> When you delete the message box LVGL looks for a new widget to focus and it finds the last created widget, which is the last button.
> 
> You can solve it by
> 
> * removing `lv_group_set_default`
> * manually selecting which widget to focus when the message box is closed

oh , yes !! 

Thank you very much for your help. It was very useful to me 😄

**Comment by kisvegabor** [comment]
Happy to help! :slightly_smiling_face:
