### ISSUE TITLE
Character '%' not printed in lv_label_set_text_fmt

### ISSUE THREAD

**Issue by vnneti** [kisvegabor/lvgl#4387]
Hi,
I want to display a float value and unit percent % in a label with function
lv_label_set_text_fmt, but the character % is not shown.
lv_label_set_text_fmt(levellabel, "%.1f%", level);

**Comment by XuNeo** [comment]
You need to escape `%` in format string.

`lv_label_set_text_fmt(levellabel, "%.1f%%", level);`

**Comment by marcusobrien** [comment]
Dereferencing the % with a % (so using 2 percentages) works, and is the solution.
