### ISSUE TITLE
lv_spinner style change discussion

### ISSUE THREAD

**Issue by yel-best** [kisvegabor/lvgl#4389]
### Introduce the problem

**use lvgl v8.3 version**

When I want to modify the style of lv_spinner, it feels very difficult. Although the 8.3 version directly uses the same style as arc, I still don’t understand how to modify the width & color of this area that rotates outside. It has always been the default blue & default width. I tried to adjust 
```
style_arc_color
style_bg_color
style_arc_width
```
It will only take effect on the background of the bottom layer, but it has no effect on the rotation....

### Examples and cases

![image](https://github.com/lvgl/lvgl/assets/82205638/b9d2b4dc-8ead-4dbb-adc1-b2fcd0c8a87d)

### Suggested solution

Is it possible to add some simple and special color modification methods, or is there a problem with my approach?

thanks.

**Comment by BestStark** [comment]
oh..I see, I think it should be ok, it's ok, sorry it's my problem

```
lv_obj_set_style_arc_width(loading_spinner, 5, LV_PART_MAIN);
lv_obj_set_style_arc_width(loading_spinner, 5, LV_PART_INDICATOR);
```
