### ISSUE TITLE
Extremely slow with lv_canvas_fill_bg on ESP32S3

### ISSUE THREAD

**Issue by weixiongmei** [kisvegabor/lvgl#4396]
### Describe the bug
When calling lv_canvas_fill_bg to clear the Canvas, it takes 4248ms on the  ESP32S3
LVGL v9.0.0-dev
#define LV_COLOR_DEPTH 16

### To Reproduce
```c
uint8_t cbuf = malloc(590* 334 * 4); //External RAM
lv_obj_t * canvas = lv_canvas_create(lv_scr_act());
lv_canvas_set_buffer(canvas, cbuf, 590, 334, 0x10);
lv_canvas_fill_bg(canvas, lv_color_hex(0xFFFFFF), 0xFF);
lv_obj_center(canvas);
```

### Expected behavior
Clear the canvas in a reasonable time, but it took around 4250ms per background filling. But If I use draw line to fill the whole canvas will only took around 20ms.

**Comment by kisvegabor** [comment]
Hi,

I'e just pushed a fix.
