### ISSUE TITLE
External Signal Interrupt to the animation

### ISSUE THREAD

**Issue by CodeOn-ArK** [kisvegabor/lvgl#4398]
### Introduce the problem
Hi, I would like to interface external input devices such as buttons/sensors to my LVGL project which is based on RPi 4. What should be the correct procedure for this

### Examples and cases
interfacing LVGL based UI with external input devices (buttons/sensors)

### Suggested solution
NULL

**Comment by C47D** [comment]
You can use LVGL input devices: [docs](https://docs.lvgl.io/8.3/overview/indev.html)

**Comment by CodeOn-ArK** [comment]
> You can use LVGL input devices: [docs](https://docs.lvgl.io/8.3/overview/indev.html)

Don't we have anything more generic, which can be set to & used for any input, like adc input or uart message from another board?

**Comment by kisvegabor** [comment]
How would you like to control the UI exactly with these external data? So far all real life use cases I've seen were doable with the 4 input devices types of LVGL.

**Comment by CodeOn-ArK** [comment]
Well, In my use case, I am using an Arduino for interfacing with the sensors (all sorts of data acquisition) and It would be sending uart commands to beaglebone, which would be running the GUI.
 Ik we can simplify this scenario to fit the current methods of interfacing which lvgl provides,  but that won't be feasible in this project. 
1 way is to control gpios to send signals to the beaglebone which would read the signals as external buttons, but for huge number of commands, the number of gpios used will be high.

**Comment by kisvegabor** [comment]
With the [BUTTON indev type](https://docs.lvgl.io/8.3/porting/indev.html#button) you can handle `my_btn_read` can return  the pressed button based on UART commands too.

**Comment by CodeOn-ArK** [comment]
So you are saying to handle uart through the btn indev API right?

**Comment by kisvegabor** [comment]
Yes, could it work for you?

**Comment by CodeOn-ArK** [comment]
As of now, I used buttons for the projects, didn't test uart, but if you want I will test it after sometime
