### ISSUE TITLE
invalid conversion from 'const lv_img_dsc_t*' to 'lv_img_dsc_t*'

### ISSUE THREAD

**Issue by krupis** [kisvegabor/lvgl#4421]
### Introduce the problem
Cannot pass const lv_img_dsc_t* to lv_img_buf_get_px_color function.

### Examples and cases

I have previously used this function in some of my C projects without any issues:
```

LV_IMG_DECLARE(ui_img_round_pallette_png)

static void get_img_color(uint16_t x, uint16_t y){
    lv_color_t pixel_color = lv_img_buf_get_px_color(&ui_img_round_pallette_png, 50, 50,lv_color_make(0, 0, 0));
    uint32_t c32 = lv_color_to32(pixel_color);
    printf("Pixel color: %lu \n", c32);
}
```

One of the libraries that I use for this particular project is cpp therefore I had to convert my project to cpp to be able to use this library.
I mean not sure whether that could be the cause but for some reason this wont build. Perhaps you know what would be the cause and how to correctly pass this image to the ```lv_img_buf_get_px_color``` function?

The logs:

```
D:/Programming/ESP32/RGB_Controller_Round/T-RGB/main/main.cpp:560:54: error: invalid conversion from 'const lv_img_dsc_t*' to 'lv_img_dsc_t*' [-fpermissive]
  560 |     lv_color_t pixel_color = lv_img_buf_get_px_color(&ui_img_round_pallette_png, 50, 50,lv_color_make(0, 0, 0));
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      const lv_img_dsc_t*
```

**Comment by kisvegabor** [comment]
Thanks for the report. I've just fixed in the `release/v8.3` branch.
