### ISSUE TITLE
xpt2046 is support ?

### ISSUE THREAD

**Issue by cyberumut** [kisvegabor/lvgl#4425]
xpt2046 is support ? lvgl 8.x.x

i m using lovyangfx and lvgl 8.x  with il9341 2.8" tft display

display working but touch not work

**Comment by kisvegabor** [comment]
Yes, you just need to create a driver and an input device for LVGL as described [here](https://docs.lvgl.io/8.3/porting/indev.html).

It should work well with LVGL, so be sure your driver is working correctly. 

---
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
