### ISSUE TITLE
Draw object part events and descriptors are missing in v9

### ISSUE THREAD

**Issue by PeterBee97** [kisvegabor/lvgl#4427]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

LV_EVENT_DRAW_PART_BEGIN/END and lv_obj_draw_part_dsc_t has been removed in v9 and [related chart examples](https://docs.lvgl.io/master/examples.html#faded-area-line-chart-with-custom-division-lines) are now disabled. Is there any alternatives to this feature? The chart is used heavily in our use case.

**Comment by kisvegabor** [comment]
I've implemented a simpler solution. In v9 you can modify the draw tasks directly, or add new ones. Not all examples are updated now, but you can see some example here:
- lv_example_table_1()
- lv_example_table_2()
- lv_example_btnmatrix_2()

(Search for `LV_EVENT_DRAW_TASK_ADDED`).

This update haven't received much feedback sofar, so I'm really curious what you think. :slightly_frowning_face: 
I think it's much cleaner but I might be biased :sweat_smile:

**Comment by C47D** [comment]
@kisvegabor Where do you think we could add a 'migration' guide for those using v9?

**Comment by kisvegabor** [comment]
So far we added it in the changelog but we can open an issue to collect the changes gradually and use that list in the changelog later. What do you think?

**Comment by PeterBee97** [comment]
I saw that the comprehensive widgets demo already provides a nice working example for chart with faded area below. Hence my confusion is solved. It would still be appreciated if a migration guide were added.

**Comment by kisvegabor** [comment]
I'll update the first comment of #4011 to look more like a migration guide.
