### ISSUE TITLE
Missing colorwheel documentation in master branch

### ISSUE THREAD

**Issue by hayschan** [kisvegabor/lvgl#4429]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

In the latest master of LVGL, the colorwheel folder under `examples/widgets` gone missing. It should be at https://github.com/lvgl/lvgl/tree/master/examples/widgets/colorwheel but it does not exist there.

This causes no Examples and API in the latest documentation of colorwheel in LVGL.

### To Reproduce

This is the screenshot of the [latest documentation](https://docs.lvgl.io/master/widgets/colorwheel.html) on the web:

![image](https://github.com/lvgl/lvgl/assets/25737801/1d75bb54-299f-482b-9349-95ad40aca235)

### Expected behavior

This is the screenshot of the `v8` [documentation](https://docs.lvgl.io/8/widgets/extra/colorwheel.html) on the web:

![image](https://github.com/lvgl/lvgl/assets/25737801/6a1af308-680a-471b-9033-32441a193d33)

**Comment by PeterBee97** [comment]
Hi @hayschan ,
The colorwheel widgets was removed in v9.

**Comment by kisvegabor** [comment]
FYI, it was removed because it was non intuitive and slow.  I'm planning to replace it with something more universal later.

**Comment by hayschan** [comment]
> Hi @hayschan , The colorwheel widgets was removed in v9.

omg, just started using colorwheel in my project.

**Comment by hayschan** [comment]
> FYI, it was removed because it was non intuitive and slow. I'm planning to replace it with something more universal later.

I see. 

The color picker introduced in iOS 14 is quite intuitive and easy to use. We may try something similar. 

There are three modes for the color picker:

1. Grid
2. Spectrum
3. Sliders



![image](https://github.com/lvgl/lvgl/assets/25737801/0d078371-efc5-447f-a284-97655838a882)

![image](https://github.com/lvgl/lvgl/assets/25737801/afaf5506-5eb0-405b-9a8f-8a4565faaf0c)

![image](https://github.com/lvgl/lvgl/assets/25737801/08624d57-a698-4728-b0b2-e5788795615b)

**Comment by hayschan** [comment]
I re-created the sliders mode of iOS color picker using Squareline Studio.

![image](https://github.com/lvgl/lvgl/assets/25737801/735b270f-f8f2-441b-9f1c-df4ded653248)

**Comment by kisvegabor** [comment]
Thank you for sharing. My idea is to allow using an image and specifying the knob movement, such as:
- Any: Rectangle image pick any color
- Grid: As in your example, allow selecting only fixed positions. If the image is not rectangle we don't select cells where the opacity is 0.
- Circle: Set radius on which the knob can move
- Slider: Move vertically or horizontally.  
- Custom: Somehow allow using custom movement

Once you set the knob somewhere LVGL just ready the color of that image.

What do you think?

**Comment by hayschan** [comment]
I also came across Google's implementation on their [web color picker](https://g.co/kgs/tkQZ91), which is quite intuitive.

- On the left box, it shows the selected color appearance. 
- On the bottom, the slider controls the Hue.
- On the right, there is rectangle plane to choose the color in two dimensional space, which is Saturation and Value/Lightness (depends on HSV/HSL model used).

![1691140487489](https://github.com/lvgl/lvgl/assets/25737801/1c3123c3-f8be-41e6-8167-5517c4187ebf)

**Comment by kisvegabor** [comment]
I meant implementing all five but I'm not sure about it yet, just thinking aloud. I think what we need is:
- allow using an image from where colors can be picked (can be grid, small hexagons, ring, rectangle, bar) because generating the colors run time are slow an limited 
- limit the selection area (e.g. horizontal only for bars, discrete points for grid, circle for ring).

**Comment by dchithinh** [comment]
Hi everyone,
Does lvgl support this kind of color wheel & picker?

![wheel-5-ryb](https://github.com/lvgl/lvgl/assets/42795905/882b1280-6b16-4553-9e47-f6859fa0aa3e)

**Comment by kisvegabor** [comment]
Not directly,but there is a workaround: Use any image you want as a color picker, and its `CLICK`event, get the clicked coordinates with  `lv_indev_get_point(lv_indev_active(),&point);` and read the color on that pixel from the image.

**Comment by haigithub** [comment]
> Not directly,but there is a workaround: Use any image you want as a color picker, and its `CLICK`event, get the clicked coordinates with `lv_indev_get_point(lv_indev_active(),&point);` and read the color on that pixel from the image.

lv_img_buf_get_px_color was not found in LVGL v9 version, is there an alternative resolution?

**Comment by kisvegabor** [comment]
Auch, I think there is no replacement for it, however if you are using a normal RGB565 or ARGB8888 image, it should be simple to seek to a pixel and read its color.

**Comment by leelx78** [comment]
Hi can you pls give an example of how to read the color of a given pixel on the screen using LVGL9?

**Comment by kisvegabor** [comment]
LVGL doesn't provide an interface to read back colors from the screen. If you are using a display controller you can read its memory or i na frame buffer you can also find the required pixel.

**Comment by leelx78** [comment]
Hi I tried to implement a colorwheel based on CLICK and PRESS events but I can't manage to have it track the wheel as user might expect (i.e. you move the pinger across the wheel and the color changes continuously). It only seems to work by clicking each time.

Can you bring back the old color wheel? it wasn't perfect and indeed a bit slow but it's still better than not having it at all

Thanks!

**Comment by kisvegabor** [comment]
Could the `PRESSING` event help?

> Can you bring back the old color wheel? it wasn't perfect and indeed a bit slow but it's still better than not having it at all

Let's see what we can do with the custom things before making a decision on it. :slightly_smiling_face:

**Comment by smcgann99** [comment]
Just to add my interest in the return of a color wheel ;-)
I use openHASP and Tasmota projects, which both use LVGL for home automation where a color picker is an important feature.

**Comment by kisvegabor** [comment]
Noted, thank you! I'll keep it mind!

**Comment by kisvegabor** [comment]
Using my memory :smile:
