### ISSUE TITLE
Thai cannot be fully displayed

### ISSUE THREAD

**Issue by somon1616371** [kisvegabor/lvgl#4430]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
I want to display Thai on the interface, but when Thai is displayed with consonants superimposed on vowels and tones, the tone cannot be fully displayed and will be mixed with vowels. How can I display it correctly? This is not a problem with the font, which appears fine on Windows 10.

### To Reproduce

    lv_freetype_init(64,1,0);
    static lv_ft_info_t info;
    info.name = "/system/res/fonts/leelawdb.ttf";
    info.weight = 50;
    info.style = FT_FONT_STYLE_NORMAL;
    info.mem=NULL;
    if(!lv_ft_font_init(&info)) {
        printf("create failed.\n");
    }

    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_text_font(&style, info.font);

    lv_obj_t * label1 = lv_label_create(lv_scr_act());    
    lv_label_set_text(label1, "ทิ๋");
    lv_obj_set_width(label1, 100);   
    lv_obj_set_pos(label1, 100, 100);   
    lv_obj_add_style(label1, &style, 0);

    lv_obj_t * label2 = lv_label_create(lv_scr_act());    
    lv_label_set_text(label2, "ทิ");
    lv_obj_set_width(label2, 100);   
    lv_obj_set_pos(label2, 300, 100);   
    lv_obj_add_style(label2, &style, 0);

### Expected behavior
Full display of Thai language

### Screenshots or video
The display in the simulator is shown below:
![image](https://github.com/lvgl/lvgl/assets/140498695/12869f57-989e-4d38-9d4e-c7eadcea3a91)
The right way to display is:
![image](https://github.com/lvgl/lvgl/assets/140498695/5858bd3a-e506-4433-8ee5-04dab06a0818)

**Comment by kisvegabor** [comment]
Hi,

We were discussing to have a more flexible and module text shaping engine [here](https://forum.lvgl.io/t/alternative-text-shaping-engine/12414).

We concluded it's a large work, but it can be added later. 

Let's continue in he Forum topic.
