### ISSUE TITLE
offline image converter bug

### ISSUE THREAD

**Issue by cyberumut** [kisvegabor/lvgl#4433]
i'm using offline image conveter 
php img_conv_core.php "name=button&img=button.png&format=bin_565&cf=true_color_alpha"

but the picture mixes the colors blue and red and where is the problem ? 

my lvgl 8.x
i know online image converter but i need offline

**Comment by kisvegabor** [comment]
The PHP version is very old, please use this: https://github.com/lvgl/lv_img_conv/
