### ISSUE TITLE
lv_obj_align_to() make no effect after object size change

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#4453]
```python
import lvgl as lv
import display_driver

label = lv.label(lv.scr_act())
label.set_text("AAAAAAA")
label.center()

label2 = lv.label(lv.scr_act())
label2.align_to(label, lv.ALIGN.OUT_BOTTOM_MID, 0, 10)
label2.set_text("BBBBBBBBBBBBBB")    # not centered ?
```
![image](https://github.com/lvgl/lvgl/assets/44317361/b044b9fc-7bfa-4ae8-a862-01569318e85d)

same result in C if I use `label_set_text()` **after** `lv_obj_align_to()`

**Comment by kisvegabor** [comment]
Ah, yes! I thought it's `lv_obj_align()`. `lv_obj_align_to()` really can't update alignment when the size of the reference or the target object changes. 

Unfortunately, it'd be quite difficult to fix. Instead I suggest using the [flex](https://docs.lvgl.io/master/layouts/flex.html) layout if possible.

**Comment by hyansuper** [comment]
ok, I can simply call `lv_obj_align_to()` again after size change
