### ISSUE TITLE
How to optimize the transition of image backgrounds to make it smoother?

### ISSUE THREAD

**Issue by qq8512852** [kisvegabor/lvgl#4474]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [no] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

LVGL version:8.1.0 
When the page changes, it is not smooth with the simulator on the Windows platform.
Please refer to the following video.

### To Reproduce

Images info: (3 background images are 800*480) 
![image](https://github.com/lvgl/lvgl/assets/15918325/600212ae-8ea1-4fe9-9ddb-0d054fb02ce2)
lv_config.c   refresh period changed from 30 to 10 ms
![image](https://github.com/lvgl/lvgl/assets/15918325/34f31f39-a34a-4101-a5d8-c5e67319a862)

### Expected behavior

Achieve smoother transition of images without resizing the image.

### Screenshots or video

https://github.com/lvgl/lvgl/assets/15918325/1dd5a9f7-3cc4-4a1f-bb60-c1b69b4fdecf

**Comment by kisvegabor** [comment]
If these are backgrouud images  you should use `LV_IMG_CD_TRUE_COLOR` format. It should be much faster this way.

**Comment by qq8512852** [comment]
> If these are backgrouud images you should use `LV_IMG_CD_TRUE_COLOR` format. It should be much faster this way.

Thanks , let me try.

**Comment by qq8512852** [comment]
> If these are backgrouud images you should use `LV_IMG_CD_TRUE_COLOR` format. It should be much faster this way.

Even the size reduce  to  ".data_size = 384000 * LV_COLOR_SIZE / 8," with LV_IMG_CF_TRUE_COLOR.  However, the display effect is still no different from the video.

**Comment by kisvegabor** [comment]
It seems like  a large display. How fast your MCU is? And what is the actual resulution and color depth of the display?

**Comment by qq8512852** [comment]
> It seems like a large display. How fast your MCU is? And what is the actual resolution and color depth of the display?

Actually, I just want to make a demo in simulator. I though to switch background image was using a computer GPU, and there shouldn't be such a stuck feeling. And I also want to learn and see if there are any ways to optimize it.

It seems that there are no intentions to implement this on a real MCU. Clearly, the current approach is not very practical. For example, a background image alone consumes around 27 MB.

**Comment by kisvegabor** [comment]
> Actually, I just want to make a demo in simulator. I though to switch background image was using a computer GPU, and there shouldn't be such a stuck feeling. And I also want to learn and see if there are any ways to optimize it.

In simulator it's shouldn't be that slow. Can you share code snippet to reproduce it?

**Comment by qq8512852** [comment]
> > Actually, I just want to make a demo in simulator. I though to switch background image was using a computer GPU, and there shouldn't be such a stuck feeling. And I also want to learn and see if there are any ways to optimize it.
> 
> In simulator it's shouldn't be that slow. Can you share code snippet to reproduce it?

Sure.   
Execution order:
Create->Enter->Layout
change page:
last screen Exit-> last screen Destroy -> target Create-> target Enter -> target Layout

![image](https://github.com/lvgl/lvgl/assets/15918325/3f45cac6-5caa-40fd-8780-3d7dbd738fef)

<img width="576" alt="image" src="https://github.com/lvgl/lvgl/assets/15918325/da562a4c-ae37-40ee-83c7-3848122d391d">

<img width="569" alt="image" src="https://github.com/lvgl/lvgl/assets/15918325/4707344b-15bf-4b58-be01-62c91ad098c4">

<img width="448" alt="image" src="https://github.com/lvgl/lvgl/assets/15918325/585e313d-9830-4060-9ab1-d7b08d6d5d84">

**Comment by kisvegabor** [comment]
Sorry, but I can't see what should be smooth. I thought there will be an image sequence animation or so, but it seems you just set a few images and that's what I see in the video too.

**Comment by qq8512852** [comment]
> Sorry, but I can't see what should be smooth. I thought there will be an image sequence animation or so, but it seems you just set a few images and that's what I see in the video too.

Thanks for your support.
I understand that screen transitions are implemented using the lvgl library, and when changing the background image, the lv_btn_create() function is called. As the caller, you may not see any specific optimizations to be made, so you're unsure about the potential areas for optimization. You noticed some lag during page transitions, which shouldn't ideally occur on a powerful PC with the simulator. 
I speculate whether it is necessary to consider optimizing the underlying LVGL interface for displaying animations with large images？

**Comment by C47D** [comment]
That might be the reason, the third parameter is the time of the animation, see [lv_scr_load_anim docs here](https://docs.lvgl.io/8.3/overview/display.html?highlight=lv_scr_load_anim#_CPPv416lv_scr_load_animP8lv_obj_t18lv_scr_load_anim_t8uint32_t8uint32_tb)

**Comment by qq8512852** [comment]
> 

Yeah, much appreciate.

**Comment by qq8512852** [comment]
> 

Yeah, much appreciate.
