### ISSUE TITLE
lv_obj with a big child button draw overflow

### ISSUE THREAD

**Issue by incity** [kisvegabor/lvgl#4486]
```
    lv_obj_t* parent = lv_obj_create(lv_scr_act());
    lv_obj_t* child = lv_btn_create(parent);
    lv_obj_set_pos(parent, 50, 50);
    lv_obj_set_size(parent, 300, 250);

    lv_obj_set_pos(child, 0, 0);
    lv_obj_set_size(child, 1000, 1000);
```

![image](https://github.com/lvgl/lvgl/assets/7846605/ad941cdd-3802-4928-84e7-3f3b16fb0f95)
![image](https://github.com/lvgl/lvgl/assets/7846605/20907ec1-9da7-4884-8706-95bb77fe3f29)

**Comment by kisvegabor** [comment]
You can enable `lv_obj_style_set_clip_corner(obj, true, LV_PART_MAIN)`
