### ISSUE TITLE
Is there any method to call the render method to render all active widgets manully?

### ISSUE THREAD

**Issue by zeroxer** [kisvegabor/lvgl#4491]
I want to embed lvgl to my app/game framework. I already have got nanovg render working. But when I try to embed lvgl with nanovg as backend, I find that there is no render function I can use to render the all active widget.
The main loop in my app/game is
```cpp
 while (not_quit) {
      update(0);
      beginFrame();
      render();
      endFrame();
      glfwSwapWindow(mWindow);
  }
```
In nanovg, the render api call is in render() and it will be called every frame and then swap to window buffer.
But in lvgl, I don't find any method like `lv_draw_content/lv_draw_widgets` which can re-render all active widget using one function.

It seems that lvgl only render when needed, seems that it has some internal algorithm to do dirty rendering. Dirty rendering is a very good feature. But if i don't want to use dirty rendering, is there any method/function I can use to force render all widgets? Or I have to re-implement my backend to adapt to lvgl's dirty renering?

**Comment by bjsylvia** [comment]
Maybe you can use `lv_obj_invalidate` to update dirty region, and call `_lv_disp_refr_timer(NULL)` to draw directly. 

You can find more information [here](https://docs.lvgl.io/8.3/porting/display.html#decoupling-the-display-refresh-timer).
