### ISSUE TITLE
Image recoloring doesn't function for non-default states

### ISSUE THREAD

**Issue by swilson** [kisvegabor/lvgl#4509]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Have an image inside a button. I want to be able to recolor it when the button is pressed, i.e. LV_STATE_PRESSED, however it doesn't work. Have tried setting the style on both the button & the image. Will only recolor with the style set on the image with LV_STATE_DEFAULT. If the style is set on the button it doesn't seem to cascade to the image (even for LV_STATE_DEFAULT).

### To Reproduce

```c
    lv_obj_t *screen = lv_obj_create(NULL);

    lv_obj_t *button = lv_btn_create(screen);
    lv_obj_set_style_img_recolor(button, lv_color_black(), LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(button, LV_OPA_100, LV_STATE_PRESSED);
    
    lv_obj_t *image_obj = lv_img_create(button);
    LV_IMG_DECLARE(img_cogwheel_argb);
    lv_img_set_src(image_obj, &img_cogwheel_argb);
   
    lv_scr_load(screen);

```

### Expected behavior
I expect the image to be recolored to black when the button is pressed.

**Comment by kisvegabor** [comment]
True, the img_recolor property is not inherited. You need to manually adjust the image in any event handler of the button.
