### ISSUE TITLE
Add unified widget set/get property API

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#4518]
### Introduce the problem

For all bindings(js, micropython, lua, ...) including external library wants to interact with lvgl like a physical anim engine, all of them need to address the porting by themselves. 

The porting work includes at least:
 - support obj local styles. There's already unified API `lv_obj_set_local_style_prop`, so it makes binding very easy.
 - support widget special properties like `lv_label_set_text`, `lv_img_set_src`.

For widgets properties, this has to be done widget by widget and need to consider if the propery comes from base class. 

For a system including multiple bindings, they implement repeated code for bindings. It also needs additional maintainance especially during major version upgrade.

### Suggested solution

Similarly to obj's local style, we can implement a `lv_obj_set_property` method, and use PROPERTY_ID to specify which property to set.

For existing native C applications, they can still use the original `set` methods. On top of that, introduce a map in `lv_obj_class_t` to describe PROPERTY_ID to `set` method.

`lv_obj_set_property` needs to check `property_map` from base class recursively.

```c
const struct _lv_obj_property_map_t {
    uint32_t id,
    void (*setter)(lv_obj_t*, uint32_t id, union _lv_obj_property_value_t * value);
    void (*getter)(....);
} img_property_map = {
    {.id = IMG_SRC, lv_img_set_src, blablabla},
    {.id = IMG_ANGLE, lv_img_set_angle, blablabla},
}；

const lv_obj_class_t lv_img_class = {
    .constructor_cb = lv_img_constructor,
    .destructor_cb = lv_img_destructor,
    .event_cb = lv_img_event,
    .width_def = LV_SIZE_CONTENT,
    .height_def = LV_SIZE_CONTENT,
    .instance_size = sizeof(lv_img_t),
    .base_class = &lv_obj_class,
    .property_map = &img_property_map;
};
```

However, there are lots of prerequisites.
- property value should be a single value from `int32_t`, `color`, `pointer`, `other common types if necessary`
- set one propery should not affect other properties. E.g. set image src should not affect its pivot.
- update properties asynchronously similarly to `lv_obj_set_width` etc. Update property on each set method could take more time when multiple properties need to update together like `lv_bar_set_limit(obj, min, max)`
- property name should be unified. This could make property extraction from C source code easier too.

### References
per-widget process in lua binding: https://github.com/XuNeo/luavgl/blob/master/src/widgets/img.c#L30
per-widget process in [pika script binding](https://github.com/lvgl/lv_binding_pikascript/blob/master/LVGL.Simulator/pikascript/pikascript-api/__pikaBinding.c#L3354)
[image wrapper in js binding](https://github.com/lvgl/lv_binding_js/blob/master/src/render/native/components/image/image_wrap.cpp)

**Comment by XuNeo** [comment]
> * Do we really need `img_property_map`? Having a switch-case in the setter and getter can do the same and it's more flexible as additional code can be added there if needed.

Using a switch-case could work too, let's see which way looks more elegant.


> * We should do the same with other APIs besides widgets: animation, display, indev, font(?)

I think those we can ignore those modules becase they are not extendable like widget.


> 3\. We should have only one property per setter/getter. E.g. instead of `lv_bar_set_range` have `lv_bar_set_min` and `max`

Agree.

**Comment by kisvegabor** [comment]
> I think those we can ignore those modules becase they are not extendable like widget.



Is the extending feature is the main issue? I thought it's more about the huge number of properties and the large API in general.

The "widget extension" (i.e. overwriting some properties in a "derived class") is very rare. I can mention only 2 examples:
- `lv_slider` inherits a few `lv_bar` properties (e.g. range, value, mode). 
- similarly `lv_keyboard` inherites `lv_btnmatrix` features 

I'm thinking for long if we really need this object orientated approach like widget inheritance. There are only few use cases for it, which probably can be handled differently as well. Without this we could say everything is an `lv_obj` and all `lv_obj_set/get` functions can be used on them, but `lv_slider` is **not** an `lv_bar` (maybe `lv_bar` just has some generic public function which can be used by other widgets, like `draw_indicator`).  

What I mean by that the abstraction of widget inheritance is just a made up concept in C which is clunky, but is bounds us to some patterns and lowers the flexibility.  

Without it, maybe we can make it easier to extend the widgets with application specific data. E.g. we can have an `obj->extension_pointer` where the widgets can allocate their data, and we can just reallocate it to add some custom data as well. And that's it we have a new widget without any boiler plate. 

I can look into it's feasibility if you think it would be an interesting direction.

**Comment by XuNeo** [comment]
> I thought it's more about the huge number of properties and the large API in general.

You are correct. It's just too many properties need to be considered case by case. Not simple as what style does.

It's true there's rare usecase of overriding. `lvgl` mainly use the `inheritance` part which I think is not too clunky and works good. I have no intention to change the widget inheritance model but only want to find a common way to set widget properties just like style.

For overriding, I do have another [example](https://github.com/XuNeo/luavgl/blob/master/simulator/widgets/lv_analog_time.h) that one object(`lv_obj_t` as base in example but let's assume it's `lv_img_t` in order to explain `overriding`) includes another three images as hands to show analog time. The property `img_opa` (again, assume base is `lv_img_t`) should be overrided to set value to directly three images.

For a unified set/get property API, none of them matter. Because inside the API, it needs to find a method associated to peroperty name(or ID), and call it. Both overriding, inheritance can be achieved.

**Comment by kisvegabor** [comment]
I see and makes sense. Let's keep the class and inheritance part as it is :slightly_smiling_face: 

Next week I'll work on #4012. After that we will have more unified names.

Until that we can still do some early exploration. If you would like to send a PR with the your idea, I would be happy to review it.

**Comment by XuNeo** [comment]
Let's continue on lvgl#4579
