### ISSUE TITLE
Update image caching

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#4530]
### Introduce the problem

The image caching of v8 is not used in v9 yet and it has several issues
- Hacky and complicated: a lot of special cases
- Based on number of image, and not the used memory
- Caches a lot of smaller data and not only the image itself
- The cache can not be disabled for a particular image decoder
- It's not possible to use a custom cache manager for a special image decoder

### Examples and cases

- Obviously we need a memory size based image decoder
- We need to disable caching for image decoders with `get_area`
- It would be nice if other parts of LVGL could reuse the same cache. E.g. glyph caching or widget screenshot caching

### Suggested solution

I made an experiment in the [feat/img-cache-2](https://github.com/lvgl/lvgl/tree/feat/img-cache-2) branch. It's not complete but it's already working with the PNG decoder.  Although you have mentioned in our meeting that you prefer to keep the current "the image cache calls the decoder" I found that  "the decoder calls the cache" is much more flexible and simpler.

Please let me know what you think.

cc @XuNeo

**Comment by XuNeo** [comment]
Hi Gabor,

Thanks for the update.
Current `image cache calls the decoder` doesn't have any issue from my point of view. Let's see if the opposite is better.

@FASTSHIFT @W-Mai You guys have many experiences on writing your own cache management and algorithm for both image and font. Could you spend some time to disscuss your opinion?

cc @terry0012

**Comment by FASTSHIFT** [comment]
For different devices, due to differences in performance, cache management methods and algorithms may not be completely unified. At this stage, can we continue to use the old cache algorithm and cache request separation structure, and provide several commonly used cache algorithm implementations? Give users more freedom of choice.

**Comment by FASTSHIFT** [comment]
We have previously tried to track total memory usage for cache eviction, but there are two problems:
1. Too many small cache applications will cause memory fragmentation and affect large memory applications.
2. Some decoders (such as lodepng) allocate a lot of small memory internally, which is usually difficult to track.

**Comment by kisvegabor** [comment]
> For different devices, due to differences in performance, cache management methods and algorithms may not be completely unified. 

We can add back the previous functionality of using custom cache managers.  Does it need to be a run time feature, or can we do it compile time as well.

> Too many small cache applications will cause memory fragmentation and affect large memory applications.

I think this is mostly solved in the [feat/img-cache-2](https://github.com/lvgl/lvgl/tree/feat/img-cache-2) where only the image itself (large memory) is cached. 

> Some decoders (such as lodepng) allocate a lot of small memory internally, which is usually difficult to track.

But these are freed as well when decoding finishes. In the end only the decoded image will remain which can be cached.

**Comment by kisvegabor** [comment]
> OK, it may be more flexible when using runtime.

Are there a particular use case to add run time config? If not I would go for some thing similar to `  LV_USE_STDLIB_MALLOC    LV_STDLIB_CLIB`. E.g. `LV_USE_CACHE    LV_CACHE_BUILTIN` (or `LV_CACHE_CUSTOM`).

> Yes，we may still have to develop img cache independent heap.

My intention is to use `draw_buf`s for large image `malloc`s as it already needs to support large memory allocations. But it's up to you how to handle it. 

> So we still need to carefully estimate the memory occupied by the image based on its size and color format?

Yes, but I think it's quite simple as there is only one thing that will be cached (the image data).

**Comment by FASTSHIFT** [comment]
> Are there a particular use case to add run time config? If not I would go for some thing similar to LV_USE_STDLIB_MALLOC     LV_STDLIB_CLIB. E.g. LV_USE_CACHE    LV_CACHE_BUILTIN (or LV_CACHE_CUSTOM).

If it is determined at runtime, do I still need to use macros to control it? The built-in cache can always be available unless the user actively changes the callback function of the cache management method.

> My intention is to use draw_bufs for large image mallocs as it already needs to support large memory allocations. But it's up to you how to handle it.

I agree with this plan.

**Comment by kisvegabor** [comment]
> If it is determined at runtime, do I still need to use macros to control it? The built-in cache can always be available unless the user actively changes the callback function of the cache management method.

It just came to my mind that now you don't necessary have to replace the built in cache manager to use your own, as in custom image decoders you can call your custom cache manager too.

Of course you still might want to make LVGL use a different cache manager for the built in decoders and other features. However in parallel you might want to keep the built in manager too. 

So finally, I agree to use a run time cache selector which is always initialized to the built in be default. 

I'll update it today and merge to master.

**Comment by kisvegabor** [comment]
Merged to `master`. 

Please pay attention to that there is a `lv_cache_lock()` and a `lv_cach_unlock()` function to lock/unlock the mutex of the cache modul. These needs to be called manually around any cache handling code.

It was required to add this external mutex handling because of situations like this:
```c
lv_cache_entry_t * e = lv_cache_find(data, ...);   //Internally protected by mutex
//In an other thread:  "lv_png" requests some cache memory, and "e" is dropped
lv_cache_invalidate(e); //Internally protected by mutex, but "e" is already freed
``` 

The current solution:
```c
lv_cache_lock();
lv_cache_entry_t * e = lv_cache_find(data, ...);   //No internal mutex handling
//In an other thread:  "lv_png" requests some cache memory, but the mutex is locked so it returns here
lv_cache_invalidate(e); //No internal mutex handling
lv_cache_unlock();

//In an other thread:  "lv_png" continues running
```

**Comment by kisvegabor** [comment]
The new cache mechanism is merged so I close this issue.
