### ISSUE TITLE
lv_scale updates

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#4551]
### Introduce the problem

Updates based on observations from @kisvegabor made during `lv_scale` integration.
- Using `float` should be avoided. Instead some up scaling or smart ordering of operation should be used.
- The horizontal and vertical scale should consider the horizontal and vertical padding respectively. That is the ticks should start after the left/top padding and stop before the right/bottom padding.

### Examples and cases
N/A

### Suggested solution
Fix both observations

**Comment by C47D** [comment]
For the float issue, when using lv_coords there was a rouding issue with the positioning of the ticks, I'll check if it's possible to remove that rounding issue without using the float type.

For the padding issue, do you mean the ticks should start X pixels after the start of the main line and stop Y pixels before the ending of the line?

**Comment by C47D** [comment]
For reference, this is the current renders of the examples (using float) commit 140369c5c:

Example 1
![image](https://github.com/lvgl/lvgl/assets/11037705/0c224539-43a8-45a5-8751-11505b814960)

Example 2
![image](https://github.com/lvgl/lvgl/assets/11037705/0449afa2-d1ee-4dcb-b55c-de5d370aeaaf)

Example 3
![image](https://github.com/lvgl/lvgl/assets/11037705/7c1ee8d3-c859-4b05-911a-a608bae1174b)

Example 4
![image](https://github.com/lvgl/lvgl/assets/11037705/fc4c1f00-dd83-4755-8bfa-8ee2243f690a)

Example 5
![image](https://github.com/lvgl/lvgl/assets/11037705/47743c61-1b79-4188-b1cf-89177f7bc314)

**Comment by kisvegabor** [comment]
> For the float issue, when using lv_coords there was a rouding issue with the positioning of the ticks, I'll check if it's possible to remove that rounding issue without using the float type.

I mean the whole scale (not only the ticks) should start after/stop before the padding.
