### ISSUE TITLE
Header file installation problem in custom. cmake

### ISSUE THREAD

**Issue by zpy-0713** [kisvegabor/lvgl#4554]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When I build the lvgl library using cmake, I import lvgl as a subdirectory. After compiling, execute “make install” and find that there is a problem in the include directory. The directory becomes recursive, causing execution failure

### Expected behavior
Imported as a subdirectory, can be compiled and installed normally

**Comment by 597244721** [comment]
![图片](https://github.com/lvgl/lvgl/assets/31878138/05736e29-5dc9-4e71-9467-d7f3c4a7d32a)
I tried to modify it like this and it works as expected

**Comment by kisvegabor** [comment]
Thank you for pointing it out. Could you open Pull request with the proposed fix?

**Comment by zephyr-zhu** [comment]
ok, I'll try to submit it
