### ISSUE TITLE
lv_img with sdcard path problem. (uppercase and lowercase problem)

### ISSUE THREAD

**Issue by acer1204** [kisvegabor/lvgl#4561]
version:In lvgl 8.2 with lv_fs.
lv_img with lv_fs path to show image.bin.
but i have some problem.
my image name is "bird.bin".
if i use this code, it work.
`
lv_img_set_src(ui->screen_img_preview,"S:bird.bin");
`
but if i use this code, it not wrok.
`
lv_img_set_src(ui->screen_img_preview,"S:BIRD.BIN");
`.
does lvgl has some config to ignore uppercase and lowercase problem?

**Comment by kisvegabor** [comment]
> does lvgl has some config to ignore uppercase and lowercase problem?

There is not. It's up to the underlying FS driver  to decide how handle the path.
