### ISSUE TITLE
Arc : clickable area outside of the draw 

### ISSUE THREAD

**Issue by spilz87** [kisvegabor/lvgl#4576]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

With a partial arc (120°), when I click outside of these 120° but still in the ring, it changes the value.
which can be a big issue when it controls volume for example and it put it at 100% :(

### To Reproduce

```
// Volume
  lv_obj_t *volume_label = lv_label_create(lv_scr_act());
  lv_label_set_text(volume_label, "Value");

  /*Create Volume Arc*/
  volume_arc = lv_arc_create(lv_scr_act());
  lv_obj_set_size(volume_arc, 225, 225);
  // lv_arc_set_rotation(volume_arc, 135);
  lv_arc_set_rotation(volume_arc, 210);
  lv_obj_set_style_arc_width(volume_arc, 5, LV_PART_MAIN); // Changes background arc width
  lv_obj_set_style_arc_width(volume_arc, 6, LV_PART_INDICATOR); // Changes set part width 
  // lv_arc_set_bg_angles(volume_arc, 0, 270);
  lv_arc_set_bg_angles(volume_arc, 0, 120);
  lv_arc_set_value(volume_arc, 10);
  lv_obj_remove_style(volume_arc, NULL, LV_PART_KNOB);   /*Be sure the knob is not displayed*/
  lv_obj_center(volume_arc);
  lv_obj_add_event_cb(volume_arc, value_changed_event_cb, LV_EVENT_VALUE_CHANGED, volume_label);
```
and
```
static void value_changed_event_cb(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target(e);
    lv_obj_t * label = (lv_obj_t *)lv_event_get_user_data(e);

    lv_label_set_text_fmt(label, "%d%%", lv_arc_get_value(arc));
}
```

### Expected behavior

I would expect it change only when I click on the drown part of the arc, not on the full ring
### Screenshots or video

None

thanks in advance for your help

**Comment by C47D** [comment]
I think this patch make it work as you expected @spilz87 

Does it look good @kisvegabor ?
```patch
diff --git a/src/widgets/arc/lv_arc.c b/src/widgets/arc/lv_arc.c
index 6156328e3..9aafec9d0 100644
--- a/src/widgets/arc/lv_arc.c
+++ b/src/widgets/arc/lv_arc.c
@@ -589,7 +589,7 @@ static void lv_arc_event(const lv_obj_class_t * class_p, lv_event_t * e)
         }
     }
     else if(code == LV_EVENT_HIT_TEST) {
-        lv_hit_test_info_t * info = lv_event_get_param(e);;
+        lv_hit_test_info_t * info = lv_event_get_param(e);
 
         lv_point_t p;
         lv_coord_t r;
@@ -609,6 +609,28 @@ static void lv_arc_event(const lv_obj_class_t * class_p, lv_event_t * e)
             return;
         }
 
+        /*Calculate the angle of the pressed point using a temporary point*/
+        lv_point_t tmp_point;
+        tmp_point.x = info->point->x;
+        tmp_point.y = info->point->y;
+        /*Make point relative to the arc's center*/
+        tmp_point.x -= p.x;
+        tmp_point.y -= p.y;
+
+        LV_ASSERT_MSG(tmp_point.x == 0 && tmp_point.y == 0, "Both coordinates are 0");
+
+        int16_t angle = lv_atan2(tmp_point.y, tmp_point.x);
+        /*Make the angle relative to the start angle*/
+        angle -= arc->rotation;
+        angle -= arc->bg_angle_start;
+        if(angle < 0) angle += 360;
+
+        /* Point is not in the arc background, do not update value */
+        if(angle > arc->bg_angle_end) {
+            info->res = false;
+            return;
+        }
+
         /*Valid if no clicked outside*/
         lv_area_increase(&a, w + ext_click_area * 2, w + ext_click_area * 2);
         info->res = _lv_area_is_point_on(&a, info->point, LV_RADIUS_CIRCLE);

```

I've attached it, change the extention from txt to patch and apply it using `git apply arc_click_on_bg.patch
[arc_click_on_bg.txt](https://github.com/lvgl/lvgl/files/12680336/arc_click_on_bg.txt)
`

**Comment by spilz87** [comment]
@C47D thanks a lot for your very quick reply.
I’m using v8.3, the latest stable release on arduino (if I’m right) 

Yes it looks like the invisible part of the arc is sensible to click which is confusing for UI.

I will modify the file as you suggest and I will let you know in few hours. 

Thanks again

**Comment by spilz87** [comment]
I modify the file lv_arc.c as you suggest (if I understand it well)
compile everything
but it doesn't change the behavior

**Comment by C47D** [comment]
Can you send me an screenshot of the updated section of the code? I'll check it tomorrow morning, it's midnight here :smile:

**Comment by spilz87** [comment]
I will do some test today and I will send you 
It’s morning here :) 
Have a good night and thanks for your help

**Comment by kisvegabor** [comment]
Hey,

It's really odd as it works now and I agree with the fix proposed by @C47D. However,
1. It should be added to the `PRESSING` event, else it will work only if `LV_OBJ_FLAG_ADV_HITTEST` is enabled. 
2. We should add a little bit of extra room  before/after the start/end angle, else it would be impossible to set the knob to the very end. Maybe +/- 10 degrees wold make it. However care must be taken is the start and end angles are very close to each other. 

Regarding the +/- 10 degree, it would be better to say we add e.g. `LV_DPX(50)` (LV_DPX considers the DPI too) tolerance.  And we need convert the pixels to angle like: 
```
circumference = (2 * radius * 314) / 100; //avoid float
tolerance_deg = 360 * lv_dpx(50) / circumference;
```

**Comment by spilz87** [comment]
the flag `LV_OBJ_FLAG_ADV_HITTEST` is not very clear for me about it's consequences

**Comment by spilz87** [comment]
I add : 

```
/* Point is not in the arc background, do not update value */
        if(angle > arc->bg_angle_end) {
            return;
        }
```

in `PRESSING` event after `if(angle < 0) angle += 360;` 
it seems to work :)

**Comment by C47D** [comment]
@kisvegabor I'll update the patch with your suggestions and send a PR :smile_cat:

**Comment by spilz87** [comment]
> Hi @kisvegabor, thanks for taking a look at the proposal, I'll update it with your suggestions and send a PR 😸

if there is a way it's done in v8.3 relaese too as it's the one used by arduino users, it would be very nice :)

**Comment by spilz87** [comment]
thanks a lot for your help :D

**Comment by C47D** [comment]
@kisvegabor Could you expand on this? I don't follow the need to convert angle to pixels, shouldn't the arc range angles be enough?
> Regarding the +/- 10 degree, it would be better to say we add e.g. LV_DPX(50) (LV_DPX considers the DPI too) tolerance. And we need convert the pixels to angle like

@spilz87 Sure, I can send the fix on master version of lvgl and it will be also ported into v8.3

**Comment by spilz87** [comment]
> if(angle > arc->bg_angle_end) {
>             return;
>         }

I think this is enought.
i can access to 0 and 100% with no problem

**Comment by kisvegabor** [comment]
> i can access to 0 and 100% with no problem

Even if you just click on an end? I think it's easy to miss the end with one pixel and in this nothing will happen.

> Could you expand on this? I don't follow the need to convert angle to pixels, shouldn't the arc range angles be enough?

Because with angles on a smaller arc the same angle means smaller sensitive area than on larger arc. And you finger has the same size, so  we should make the sensitive area independent of the actual size of the arc.

**Comment by kisvegabor** [comment]
Let's continue in #4586.
