### ISSUE TITLE
LVGL Compile issue with MSVC toolchain

### ISSUE THREAD

**Issue by MouriNaruto** [kisvegabor/lvgl#4601]
I found an issue when I update the LVGL git submodule for the LVGL for Visual Studio project.

https://github.com/lvgl/lvgl/blob/9c437d107320369584e06d85367f72086f056616/src/widgets/roller/lv_roller.c#L184

`(uint32_t)LV_ABS((int16_t)act_opt - sel_opt)` should be changed to `(uint32_t)LV_ABS((int16_t)(act_opt - sel_opt))`, or you will meet the compilation "error C4146: unary minus operator applied to unsigned type, result still unsigned" when you compiling LVGL with MSVC toolchain.

Kenji Mouri

**Comment by kisvegabor** [comment]
Fixed, thank you!
