### ISSUE TITLE
image setsize: When I set the image size, it always has a mosaic effect. If I use setsize instead of setzoom to achieve the scaling effect, it will achieve the same effect as reactnative.

### ISSUE THREAD

**Issue by SUPPH** [kisvegabor/lvgl#4602]
### Introduce the problem

When I use avatar.setWidth(100);, it always has a mosaic effect. How can I achieve the scaling effect? I'd be grateful if anyone could tell me.

**Comment by SUPPH** [comment]
reactnative example: https://reactnative.dev/docs/image

**Comment by kisvegabor** [comment]
In v8, it's really tiled automatically if the widget size is larger. 
Howevem, in LVGL v9 (under development) we will add image sizing modes, similar to CSS.

**Comment by SUPPH** [comment]
@kisvegabor Ok, thanks for your answer

**Comment by SUPPH** [comment]
@kisvegabor May I ask why there is an operation of adding and subtracting coordinates by 1 in the lv_img_set_zoom function?I would be grateful if you could answer
`a.x1 += obj->coords.x1 - 1;
    a.y1 += obj->coords.y1 - 1;
    a.x2 += obj->coords.x1 + 1;
    a.y2 += obj->coords.y1 + 1;`

**Comment by kisvegabor** [comment]
It just makes the area to invalidate slightly larger to avoid rounding errors.

**Comment by SUPPH** [comment]
Got it, thank you very much
