### ISSUE TITLE
Is's lv_fs has no api with lv_fs_size in lvgl v8.2?

### ISSUE THREAD

**Issue by acer1204** [kisvegabor/lvgl#4603]
Is's lv_fs has has no api with lv_fs_size in lvgl v8.2?
i find this api in lvgl v7.11.
is anyway to get file size by use lv_fs in lvgl v8.2?

**Comment by kisvegabor** [comment]
Really there is no API function fro that. 

You can use this trick:
```c
lv_fs_seek(&f, 0, LV_FS_SEEK_END);
uint32_t s = lv_fs_tell(&f);
```
