### ISSUE TITLE
lvgl list

### ISSUE THREAD

**Issue by liangfei2021** [kisvegabor/lvgl#4660]
Hi:
   1.Creates multiple list-items, introduces a keypad to control it, switches from the end of the list to the head, and the head of the list is invisible
   2.How to change the color of the keypad when an item is selected? Its color overrides the background color of the item.

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
