### ISSUE TITLE
How to get pictures through url

### ISSUE THREAD

**Issue by SUPPH** [kisvegabor/lvgl#4665]
### Introduce the problem

I am using version 8.3.9. How do I get the image through setsource url? I couldn’t find it. Can anyone give me an answer?

**Comment by kisvegabor** [comment]
There is no built-in solution for that, what you can do is downloading the image in RAM an putting together an image descriptor manually. Something like this: https://github.com/lvgl/lvgl/blob/release/v8.3/examples/assets/img_star.c#L143-L152

**Comment by SUPPH** [comment]
OK, I'll try it, thank you
