### ISSUE TITLE
Meter needle line start point customization

### ISSUE THREAD

**Issue by 1saeed** [kisvegabor/lvgl#4671]
### Introduce the problem

I'm using v8.3. I was about to change needle line start point in `LV_EVENT_DRAW_PART_BEGIN` event to start drawing from an arc instead of the scale center and realized that it's not possible since in `draw_needles` function, it's always start drawing line from center regardless of `part_draw_dsc.p1` here: `lv_draw_line(draw_ctx, &line_dsc, &scale_center, &p_end);`

### Examples and cases

If in callback event you change `part_draw_dsc.p1` pointer, it won't work.

### Suggested solution

changed to : `lv_draw_line(draw_ctx, &line_dsc, part_draw_dsc.p1, &p_end);` so it will draw from the actual p1 instead of center.

Also `inv_line` function should be adopted accordingly.

**Comment by kisvegabor** [comment]
Hi,

Thank you for the suggestion!

If you have already made some experiments could you send a [Pull Request](https://docs.lvgl.io/8.3/CONTRIBUTING.html#pull-request)?

**Comment by 1saeed** [comment]
Hi,

Sure, I'll send the pull request once I'm done with the experiments.

**Comment by kisvegabor** [comment]
#4682 is merged so I close this issue.

Thank you!
