### ISSUE TITLE
Test cases for `lv_scale`

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#4673]
### Introduce the problem
The new (v9) widget `lv_scale` doesn't have any test cases.

### Examples and cases
When updating the implementation we need to validate nothing got broken.

### Suggested solution
Consider adding tests for:
- Rendering tests
- edge cases
- styling
- main features (like tick texts)

**Comment by C47D** [comment]
For rendering tests I was thinking of using the examples. What do you think @kisvegabor ?

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
@C47D are there any updates on this topic?

**Comment by kisvegabor** [comment]
Let continue in #4678
