### ISSUE TITLE
Image recolor not working

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#4692]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The first draw of image with recolor enabled is correct. But when moving mouse on it, redraw image with dirty area is not working.

### To Reproduce

```c
    LV_IMAGE_DECLARE(img_cogwheel_rgb);
    lv_obj_t * img1 = lv_image_create(lv_screen_active());
    lv_image_set_src(img1, &img_cogwheel_rgb);
    lv_obj_set_style_image_recolor(img1, lv_color_hex(0xff0000), 0);
    lv_obj_set_style_image_recolor_opa(img1, LV_OPA_50, 0);
```
### Screenshots or video

<img width="124" alt="image" src="https://github.com/lvgl/lvgl/assets/25867991/e0ecbf6b-1056-41ee-9d31-be71a527b506">

**Comment by kisvegabor** [comment]
Thanks for the report, should be fixed!
