### ISSUE TITLE
Outdated GitHub action

### ISSUE THREAD

**Issue by szepeviktor** [kisvegabor/lvgl#4694]
GitHub actions used are outdated.
Please see https://github.com/szepeviktor/lvgl/pulls

You could run Dependabot once or - for example - every month.
https://github.com/szepeviktor/lvgl/blob/48a9e5eb4459419fde27386d2d60314534360eff/.github/dependabot.yml#L1-L10

**Comment by kisvegabor** [comment]
I've just added `dependabot.yml` as you have suggested but it fails:
https://github.com/lvgl/lvgl/actions/runs/6623783042

**Comment by szepeviktor** [comment]
🪰 
Toomuch "moth" in it!

**Comment by kisvegabor** [comment]
Thanks, now it works! I've merged the PRs too! :metal:
