### ISSUE TITLE
Link to ESP32 Component in README is broken

### ISSUE THREAD

**Issue by georgik** [kisvegabor/lvgl#4705]
Link to ESP32 Component in the section Packages is broken: https://github.com/lvgl/lvgl#package-packages

The link points to URL https://docs.lvgl.io/master/get-started/platforms/espressif.html which returns 404.

**Comment by kisvegabor** [comment]
Hey,

Thank you for pointing it out. I've just fixed it with https://github.com/lvgl/lvgl/commit/e869d76f53369e4f56c884f0f420f013d21e7f75
