### ISSUE TITLE
I couldn't find lv_refr_get_fps_avg in LVGL 9.x series

### ISSUE THREAD

**Issue by MouriNaruto** [kisvegabor/lvgl#4754]
https://github.com/lvgl/lvgl/blob/0bdd54abedf352e82acfbaabe8be48324f9435a2/demos/music/lv_demo_music.c#L228

I found this compilation issue when I continued to improve the Windows simulator.

When I searched the repository, I couldn't find any reference of lv_refr_get_fps_avg outside of LvglPlatform\lvgl\demos\music\lv_demo_music.c.

Kenji Mouri

**Comment by kisvegabor** [comment]
Thank you for reporting it. I fixed it here:  96ce50565

While testing I noticed some drawing issues in the music player demo. I'll fix it soon.
