### ISSUE TITLE
Set the style shadow to have a white line in the middle

### ISSUE THREAD

**Issue by C-Ackerman** [kisvegabor/lvgl#4755]
### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When setting lv_obj_set_size(btn, 200, 100); when the width and height are not equal and setting lv_obj_set_style_shadow_width(btn, 2, LV_PART_MAIN); when the lv_coord_t is less than 3, a white line will appear in the middle of the shadow

```c
void lv_demo_widgets(void)
{
    lv_obj_t * btn = lv_obj_create(lv_scr_act());
    lv_obj_remove_style_all(btn);

    /* default */
    lv_obj_set_size(btn, 200, 100);
    lv_obj_set_pos(btn, 100, 100);
    lv_obj_set_style_radius(btn, 0x7FFF, 0);
    lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
    lv_obj_set_style_bg_color(btn, lv_palette_main(LV_PALETTE_BLUE), 0);

    lv_obj_set_style_shadow_ofs_x(btn, 100, LV_PART_MAIN);
    lv_obj_set_style_shadow_ofs_y(btn, 100, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(btn, 2, LV_PART_MAIN);
    lv_obj_set_style_shadow_color(btn, lv_palette_main(LV_PALETTE_GREEN), LV_PART_MAIN);

    return;
}
```

![image](https://github.com/lvgl/lvgl/assets/49789618/d157bc38-b942-4af1-bcde-d029f5f72c60)

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it
