### ISSUE TITLE
 lv_conf_template.h Version description not updated

### ISSUE THREAD

**Issue by landaming** [kisvegabor/lvgl#4765]
### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

In v8.3.10, lv_conf_template.h The version description of the file has not been updated
### Screenshots or video

![image](https://github.com/lvgl/lvgl/assets/50478841/0755f773-13c4-4b64-8cb5-5c1d02f64235)

**Comment by kisvegabor** [comment]
Thank you for pointing it out.  I think there is no good way to fix it after the the release. What we can do is setting it to v8.3.11 in the next release. :slightly_frowning_face: 

cc @GorgonMeducer

**Comment by GorgonMeducer** [comment]
Sorry, I will double check next time.

**Comment by kisvegabor** [comment]
No worries. :+1:
