### ISSUE TITLE
 obj's border opa display is not normal in lvgl8.3.10

### ISSUE THREAD

**Issue by guoqiang-gump** [kisvegabor/lvgl#4771]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
In lvgl8.3.10, Set obj border opa to be the same as obj bg opa, but the displayed border opa is inconsistent compared to the bg opa.

### To Reproduce
```c
static void anim_opa_cb(void * var, int32_t v)
{
    lv_obj_set_style_opa(var, v, 0);
}

    lv_obj_t *ui_rightTool = lv_obj_create(root);
    lv_obj_set_width(ui_rightTool, 69);
    lv_obj_set_height(ui_rightTool, 86);
    lv_obj_align(ui_rightTool, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_align(ui_rightTool, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightTool, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_rightTool, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightTool, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_rightTool, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightTool, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightTool, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_rightTool);
    lv_anim_set_values(&a, 10, 50);
    lv_anim_set_time(&a, 1000);
    lv_anim_set_playback_delay(&a, 100);
    lv_anim_set_playback_time(&a, 300);
    lv_anim_set_repeat_delay(&a, 500);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_in_out);

    lv_anim_set_exec_cb(&a, anim_opa_cb);
    lv_anim_set_values(&a, LV_OPA_0, LV_OPA_100);
    lv_anim_start(&a);
```

### Expected behavior
The border opa of the obj should display the same as the bg opa of the obj

### Screenshots or video
<img width="243" alt="54899c8736606684ca01fc5d1d6fc71" src="https://github.com/lvgl/lvgl/assets/58102897/1171ff15-7987-45b7-a6f9-ff1e61eba9aa">

### Bug Location
In lv_obj_draw api，drawing the border twice causes the border's opa to be halved. But I do not know how to fix it.
![image](https://github.com/lvgl/lvgl/assets/58102897/15335c26-2bd7-4f6e-90bf-73c4e037d628)

**Comment by kisvegabor** [comment]
Please use `lv_obj_set_style_opa_layered`. 

Background story: 
In v8.3 we have introduced a "layers" to allow correct blending with opacity and tranformation of any widgets. For these kind of operations LVGL creates a spanshot about he widget and blends it as a single image. In case of opacity it results in better result, but it's also slower and uses much more memory. So we have introduced the `opa_layered` property to explicitly tell that you want slower and more memory hungry mode.

**Comment by guoqiang-gump** [comment]
Thanks for the reply.
lv_obj_set_style_opa_layered does have an effect. I've been able to tell the difference between lvgl 8.3.10 and lvgl 8.3.7, and learned that lv_obj_set_style_opa_layered() replaces lv_obj_set_style_opa().

But when I call lv_scr_load_anim(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0):  lv_scr_load_anim --->opa_scale_anim ---->lv_obj_set_style_opa, which ends up calling This makes the FADE_ON or FADE_OUT screen switching strange.

**Comment by kisvegabor** [comment]
Hm, I see. I think the best would be to have `LV_SCR_LOAD_ANIM_FADE_ON_LAYERED` too. What do you think?

**Comment by guoqiang-gump** [comment]
Yes, I think adding LV_SCR_LOAD_ANIM_FADE_ON_LAYERED is necessary because after many developers upgraded from lvgl8.3.7 to lvgl8.3.10, they use LV_SCR_LOAD_ANIM_FADE_ON and they find that the scr opa displays weirdly. So need LV_SCR_ LOAD_ANIM_FADE_ON_LAYERED to correspond to lv_obj_set_style_opa.

Also I found the biggest upgrade surprise for lvgl 8.3.10, a huge frame rate increase using double fb and dirct_mode. I think lv_port_disp_template.c should be updated to guide developers to use double fb and dirct_mode.

**Comment by kisvegabor** [comment]
>  So need LV_SCR_ LOAD_ANIM_FADE_ON_LAYERED to correspond to lv_obj_set_style_opa.

Almost. `LV_SCR_ LOAD_ANIM_FADE_ON_LAYERED` should correspond to `lv_obj_set_style_opa_layered` (which allcoates a new layer and has higher quality).

Could you help us by sending a PR?

> Also I found the biggest upgrade surprise for lvgl 8.3.10, a huge frame rate increase using double fb and dirct_mode. I think lv_port_disp_template.c should be updated to guide developers to use double fb and dirct_mode.

Sure! Approximately how much was the increase?

**Comment by guoqiang-gump** [comment]
> Almost. LV_SCR_ LOAD_ANIM_FADE_ON_LAYERED should correspond to lv_obj_set_style_opa_layered (which allcoates a new layer and has higher quality).
Could you help us by sending a PR?
I've been very busy lately and won't be available until some time later. Until then, I'll have to see about submitting PR.

> Sure! Approximately how much was the increase?
I have a GPU inside my MCU, and direct_mode doubles the frame rate over full_reflesh, currently at 58FPS inside my clock_demo

**Comment by kisvegabor** [comment]
> I've been very busy lately and won't be available until some time later. Until then, I'll have to see about submitting PR.

I'm quite busy too, so I leave this issue open for now.


> I have a GPU inside my MCU, and direct_mode doubles the frame rate over full_reflesh, currently at 58FPS inside my clock_demo

Really cool!
