### ISSUE TITLE
Will lvgl support epaper's 16 levels of grayscale color?

### ISSUE THREAD

**Issue by lanistor** [kisvegabor/lvgl#4779]
Combining lvgl and [Eink paper](https://www.eink.com/), we facing a problem: the pixel need to convert to color of epaper(16 levels of grayscale color), when using `set_px_cb`, the painting will be very slow, [see previous testing result](https://github.com/lvgl/lvgl/issues/3921#issuecomment-1407588802).

We are using [epdiy](https://github.com/vroland/epdiy/tree/s3_lcd) for painting, it's a soft solution timing driver of epaper. the color rule is this: only have 16 colors, represents different grayscale colors(Eink paper's rule), each pixel occupies 4 bits, the high 4 bits and low 4 bits of a byte represent two adjacent pixels respectively.

So how to resolve this problem to improve rendering speed?

### Suggested solution

I think out a way: to let lvgl support `16 levels of grayscale color`, add a subtype of `lv_color_t`, like `lv_color4_t`, so the pixel doesn't need to convert by `set_px_cb`.

Do you think it's a good way? or any other ways?

**Comment by kisvegabor** [comment]
Hi,

For LVGL v8 (that you are using now) we are not planning to add such a features. In LVGL v9 (under development) we have much more flexible rendering architecture, where 4 bit rendering is not supported yet but it could be in the future. 


To make it faster with v8, I recommend using normal 16 bit rendering and convert it to 4 bit in the `flush_cb`.

**Comment by mataide** [comment]
@lanistor Were you able to combine Epdiy with Lvgl? I am trying to do the same.

**Comment by lanistor** [comment]
> @lanistor Were you able to combine Epdiy with Lvgl? I am trying to do the same.

You can use this: https://github.com/martinberlin/lvgl_epaper_drivers
