### ISSUE TITLE
ime_pinyi discuss in V9

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#4781]
Use 'ime_pinyin', after entering Chinese, select the next Chinese character in 'cand_panel'. Later, output Pinyin again, and only '<' will be displayed for 'cand_panel'.

[test](https://docs.lvgl.io/master/others/ime_pinyin.html)

**Comment by kisvegabor** [comment]
Hi,

Thank for reporting the problem. Could you find the root of the issue? If so can you send a Pull request?

**Comment by IAMMX** [comment]
Sorry, my level is limited and I cannot solve this problem. I hope you can find a way as soon as possible

**Comment by kisvegabor** [comment]
Okay, no worries. I cc @100ask, to original author of this feature. Could you take a look?

**Comment by IAMMX** [comment]
OK。But in v8 this feature is normal
