### ISSUE TITLE
The brower_file_event_handler interface has hidden risks

### ISSUE THREAD

**Issue by sunzigang** [kisvegabor/lvgl#4782]
<!  --
IMPORTANT
Issues that don't use this template will be ignored and closed.
-->

### Perform all steps below and tick them with [x]
- [x ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
<!  --
-->
When clicking on an empty space in the file list, an illegal access is generated

### To Reproduce
<!  --
Provide a small, independent code sample that can be used to reproduce the issue.
Ideally this should work in the PC simulator unless the problem is specific to a platform.

Use this routine: LVGL/examples/others/file_explorer
/lv_example_file_explorer_1.c

### Expected behavior
<!  --
-->
No illegal access is generated

### Screenshots or video
<!  --
-->
![image](https://github.com/lvgl/lvgl/assets/35128999/9cc62a3c-b7cf-482a-bd37-ba3fc9dfef30)
 here return ""
![image](https://github.com/lvgl/lvgl/assets/35128999/79b27175-0d93-48ba-b189-061cb4300d79)
str_fn = str_fn + 5;

**Comment by sunzigang** [comment]
![image](https://github.com/lvgl/lvgl/assets/35128999/051aaa92-9782-4e6c-8e33-0020fa5def30)
Should there be a judgment?

**Comment by kisvegabor** [comment]
Nice catch! I think we should return `NULL` and also check the return value where needed. Could you send a Pull request with the fix?
