### ISSUE TITLE
sjpg can't load big .jpg

### ISSUE THREAD

**Issue by Jeeeeeiel** [kisvegabor/lvgl#4785]
### Introduce the problem

sjpg cannot load .jpg with size 240*240 on platform arduino+esp32 picoD4.
error happens here:
"sjpeg->frame_cache = (void *)lv_mem_alloc(sjpeg->sjpeg_x_res * sjpeg->sjpeg_single_frame_height * 3);"
can anybody help me?thx

**Comment by Jeeeeeiel** [comment]
how can i load .jpg with sjpg segmented？i mean piece by piece

**Comment by kisvegabor** [comment]
Seems like a out of memory issue. Try increasing `LV_MEM_SIZE` in `lv_conf.h`

**Comment by Jeeeeeiel** [comment]
> Seems like a out of memory issue. Try increasing `LV_MEM_SIZE` in `lv_conf.h`

not a solution😓

**Comment by kisvegabor** [comment]
Let's start form the beginning: 
- Which version of LVGL do you use?
- If v8, I recommend updating to v9. See the changelog [here](https://docs.lvgl.io/master/CHANGELOG.html)
- In v9 SJPG was replaced by TJPGD
- Please using your image in [PC simulator](https://docs.lvgl.io/master/integration/ide/pc-simulator.html) first to rule out as much hardware related issues as possible.
