### ISSUE TITLE
Rotation Codes for ILI9341

### ISSUE THREAD

**Issue by monkeytronics** [kisvegabor/lvgl#4814]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by kisvegabor** [comment]
Please describe the problem in more detail by filling the template.
