### ISSUE TITLE
How to customize _lv_text_is_a_word ?

### ISSUE THREAD

**Issue by yushuailong** [kisvegabor/lvgl#4830]
### Introduce the problem

_lv_text_is_a_word is a function defined inside lvgl, but the Unicode range inside is incomplete. [CJK characters](https://en.wikipedia.org/wiki/CJK_characters)

I want to complete it in an overseas project, but I can only modify the lvgl source code. One modification usually cannot take into account all situations. Is there any way we can customize it?

### Examples and cases

Japanese katakana and hiragana are not included.

```
    /*Hiragana and Katakana*/
    if (letter >= 0x3040 && letter <= 0x30FF) {
        return true;
    }

```

### Suggested solution

Implement this function outside lvgl

**Comment by kisvegabor** [comment]
I would like to fix it in LVGL instead adding a config option or extension point for it.  Could you send a Pull request?

**Comment by fuxiujun** [comment]
> I would like to fix it in LVGL instead adding a config option or extension point for it. Could you send a Pull request?

We don't know how sentences are segmented in all languages, but we just discovered this bug during testing. If you later find that other languages also have this problem, you will need to continue to add it.

Custom extensions can solve problems more efficiently and avoid frequent changes to lvgl. What do you think?

**Comment by kisvegabor** [comment]
> Custom extensions can solve problems more efficiently and avoid frequent changes to lvgl. What do you think?

My approach is that there isn't much room for customization here. These are standard things and LVGL should work accordingly. If something is missing we should solve it in LVGL to have good out of the box experience for everyone's happiness :slightly_smiling_face:  

Thank you for the PR!
