### ISSUE TITLE
Run the image convert in the browser

### ISSUE THREAD

**Issue by W-Mai** [kisvegabor/lvgl#4866]
### Introduce the problem

Reference to this discussion https://github.com/lvgl/lvgl/pull/4414#issuecomment-1764819295

I wrote a simple demo to fit the requirements for this comment.

The repo is here

https://github.com/W-Mai/RunPyScriptInBrowserWithWasmLibCompiledByRust

@kisvegabor 

snapshot

<img width="958" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/b32d5205-d640-4411-b6b7-e82038f02050">

**Comment by kisvegabor** [comment]
Thank you for dealing with it @W-Mai!

I've tried it based on the README and it worked well locally. 
I copied the 3 files from the `web` folder to lvgl.io's webserver but it doesn't work that well there: https://lvgl.io/tools/new_img_conv/

![image](https://github.com/lvgl/lvgl/assets/7599318/717478fa-b10b-4bcd-8f3d-39d1ceccbac5)

**Comment by W-Mai** [comment]
I notice that the console shows an error message about MIME type mismatching
<img width="674" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/9afb237c-a5e0-4819-8fd4-31664a91ae7b">

There is a `content-type` in the normal http request and response

<img width="806" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/6d6939c0-1d5a-4795-b5c1-3f780fe45b74">

But lvgl.io server seems not to provide the `content-type` property

<img width="797" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/37caee69-f575-41ca-abf6-4b1c52e4b635">

I think this may be the real cause of this problem

**Comment by kisvegabor** [comment]
I have no idea where to start, so it'd be great if you could provide an example for these 3 points.

**Comment by W-Mai** [comment]
> I have no idea where to start, so it'd be great if you could provide an example for these 3 points.

Ok, I will do it later 😁

**Comment by W-Mai** [comment]
<img width="2038" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/39b221ab-1c2d-4ca7-a0ec-b4a9cc00d53d">

Well done!

Now this demo supports dealing multiple images and also can download from a visible link.
And also it has the ability to get information form `select` component. 😁

**Comment by kisvegabor** [comment]
Looks good! I'll try to integrate it soon!

**Comment by kisvegabor** [comment]
Hi @W-Mai,

I started to integrate it to the online converter, however something still seems missing. I cannot see where you call the actual Image converter to which I can pass parameters like color format.

**Comment by W-Mai** [comment]
Here is the calling entry
https://github.com/W-Mai/RunPyScriptInBrowserWithWasmLibCompiledByRust/blob/2b7e6351f4069b2f51173ece779579ae971b6c14/web/main.py#L89

And you will find the same function definition here https://github.com/W-Mai/RunPyScriptInBrowserWithWasmLibCompiledByRust/blob/2b7e6351f4069b2f51173ece779579ae971b6c14/src/main.rs#L10-L17

**Comment by W-Mai** [comment]
oh, you mean where is the real image converter already in the lvgl repo.

It's a pity that this demo is an example of a simple version that I rewrote. It's just an example.

**Comment by kisvegabor** [comment]
> oh, you mean where is the real image converter already in the lvgl repo.

Yes, I mean that :slightly_smiling_face: 
Where how can I add it?

If the whole thing is too complicated we can just slightly update the current image converter to use the new `LV_COLOR_FORMAT`  definitions and accept that it has some limitations. (E.g. not supporting stride). For a more complex converter people can use the the Python script.

**Comment by W-Mai** [comment]
I don't think it should be very complicated, so please give me some time if you need to support the full script (I'm working on cache right now).

**Comment by kisvegabor** [comment]
Okay, thank you! I would like to have a "call to test" for v9 on Monday, so some kind of converter should work by then. At worst case I can recommend to use the script directly, so there is no emergency. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
@W-Mai As discussed on our meeting I attach the HTML file for the front-end of the current converter.
[index.html.zip](https://github.com/lvgl/lvgl/files/13860420/index.html.zip)

**Comment by W-Mai** [comment]
Not Stale

**Comment by kisvegabor** [comment]
I close it for now. The current simplified online converter should be ok for  while.
