### ISSUE TITLE
MSVC will return error C4576 for the following code

### ISSUE THREAD

**Issue by MouriNaruto** [kisvegabor/lvgl#4905]
https://github.com/lvgl/lvgl/blob/ba229b0708fe3b893a179da3b3635a807b046c4b/src/misc/lv_area.h#L267-L279

Kenji Mouri

**Comment by kisvegabor** [comment]
Thank you for reporting it!  Do you see an easy fix?
cc @XuNeo

**Comment by XuNeo** [comment]
It has been discussed before. 
https://forum.lvgl.io/t/visual-studio-2019-compile-errors/1379/23 
https://stackoverflow.com/questions/33270731/error-c4576-in-vs2015-enterprise/33271165#33271165

@MouriNaruto Could you try if this fix it?

**Comment by MouriNaruto** [comment]
@XuNeo 

We shouldn't force users use LVGL in pure C projects. Especially it will limit the usage case of LVGL.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@XuNeo 

> Could you try if this fix it?

I will try you patch. Please wait.

Kenji Mouri
