### ISSUE TITLE
Inconsistency in `lv_anim_t` Module Operation Compared to Other Modules like `lv_obj_t` and `lv_timer_t`

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#4920]
### Introduce the problem

In the `lvgl` library, most modules such as `lv_obj_t` and `lv_timer_t` follow a common pattern where an instance is created and then operated upon. However, the `lv_anim_t` module deviates from this pattern in the following ways:

- An animation instance is not created explicitly, but rather implicitly through the `lv_anim_start` function.

- The `lv_anim_del` function does not allow for deletion of an animation instance directly. Instead, it requires passing the variable being animated and the callback function used for animation (bool lv_anim_del(void * var, lv_anim_exec_xcb_t exec_cb)).
- It automatically deletes self when `anim` finishes.
- There is no provision to stop an animation, modify its parameters, and then restart it.

This inconsistency in the operation of the `lv_anim_t` module compared to other modules can lead to confusion and potential misuse. It would be beneficial to align the operation of `lv_anim_t` with the common pattern used in other modules.

### Examples and cases

For `lua` binding, a fake `anim instance` is needed to describe the `anim` handler and `anim configuration`.

https://github.com/XuNeo/luavgl/blob/937327cd52ca6655994eb42251e5781ef48513ac/src/anim.c#L11-L21

### Suggested solution

Introduce a new function, `lv_anim_create`, to explicitly create an animation instance. This aligns with the operation of other modules like `lv_obj_t` and `lv_timer_t`.

Modify the `lv_anim_del` function to allow deletion of an animation instance directly, renaming it to `lv_anim_delete` for clarity.

Provide a wrapper function that automatically allocates and frees animation instances. This would simplify the process of adding simple animations.

**Comment by kisvegabor** [comment]
I agree, however we should keep the current behavior too for backward compatibility. 

In `lv_anim_init()` and `lv_anim_create()` we should set/clear a flag to indicate how the animation was created and whether it needs to be allocated in `lv_anim_start()`.

**Comment by kisvegabor** [comment]
> lv_event_t has same issue that no handler is returned to user for remove. Perhaps we should find a suitable solution for both.

The list (array) of event descriptors are reallocated when a new event is added, so we cannot return anything as on reallocation it will become a wild pointer. See [here](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_event.c#L86-L92).

**Comment by XuNeo** [comment]
Yes. So we need to find other methods in order to return a handler.

How about storing array of pointers `lv_event_dsc_t *` instead of the array of `lv_event_dsc_t`.

**Comment by kisvegabor** [comment]
It's about 8 byte extra RAM usage per event (4 byte for the pointer + ~4 byte for malloc overhead) but I think it's a good trade off to have a good way to delete events.

**Comment by XuNeo** [comment]
Not started yet.

**Comment by XuNeo** [comment]
Not stale.

**Comment by kisvegabor** [comment]
Closing in favor of #5350
