### ISSUE TITLE
Migrate to C11(or use gnu99) to support `anonymous union`

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#4980]
### Introduce the problem

Anonymous union makes code looks cleaner. It's supported in c11 or `gnu99` extension but not current `c99`.
Need to discuss the drawbacks to make such change.

**Comment by kisvegabor** [comment]
I'm ok with it in general, but we need to check it with
- Arduino
- Microchip's XC16 compiler (last time I tried it was supporting some C features)
- MSVC

**Comment by XuNeo** [comment]
For XC16, it does mention gnu99 is added. 
https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/Readme_XC16.html

For others, it needs some time to confirm.

**Comment by XuNeo** [comment]
Not stale.
Current code is NOT C99 compliant.
