### ISSUE TITLE
In v9 Parent and child elements of the same size, but the child element cannot completely cover the parent element

### ISSUE THREAD

**Issue by HongChao6** [kisvegabor/lvgl#4993]
### Describe the bug
Set the size of the parent element to 200X200, the background to red, 
the child element to a 100X100 picture, the child element is scaled to 200X200, 
As a result, the child element does not completely cover the parent element.

```
void lv_image_test(void){
   int ww = 200;
   lv_obj_t* native = lv_obj_create(lv_scr_act());
   lv_obj_remove_style_all(native);
   lv_obj_set_width(native,ww);
   lv_obj_set_height(native,ww);
   lv_obj_set_pos(native, 100, 50); 

   lv_image_t* img_ = lv_img_create(native);
   lv_obj_remove_style_all(img_);
   lv_obj_center(img_);
   lv_img_set_src(img_, "00.jpeg");
   lv_obj_set_width(img_,ww);
   lv_obj_set_height(img_,ww);

   lv_obj_set_style_bg_color(img_, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN);     
   lv_obj_set_style_bg_opa(img_, LV_OPA_80, LV_PART_MAIN); 

   uint16_t zoomHeight = ww * LV_SCALE_NONE / img_->h;
   img_->zoom = zoomHeight; 
  lv_img_set_size_mode(img_, LV_IMAGE_SIZE_MODE_REAL);
}
```

00.jpeg
![00](https://github.com/lvgl/lvgl/assets/49054754/5e1ea02b-49e6-4578-ada6-dc37c535438d)

### Expected behavior
The child element completely covers the parent element.

### Screenshots or video
![image](https://github.com/lvgl/lvgl/assets/49054754/d6e3849f-ee54-4c56-b356-e83987339902)

**Comment by XuNeo** [comment]
Could you create a minimal reproducible example on LVGL simulator?

**Comment by sam0910** [comment]
Dear @HongChao6, sorry about out of issues, 
Could I ask you what kind of watch is running LVGL?

**Comment by HongChao6** [comment]
This example is run on lvgl simulator
![image](https://github.com/lvgl/lvgl/assets/49054754/c50fe66b-d1f1-4354-b3e5-9ec59d2ea005)

**Comment by HongChao6** [comment]
> Dear @HongChao6, sorry about out of issues, Could I ask you what kind of watch is running LVGL?

That's just a picture, not running on the watch

**Comment by kisvegabor** [comment]
Is it the same in v9 (`master` branch?)

**Comment by XuNeo** [comment]
Yes, that can be reproduced in latest master branch with lvgl's simulator.

**Comment by kisvegabor** [comment]
I could also reproduce it and will get back to this in January when hammering out v9 issues.

**Comment by kisvegabor** [comment]
I've tried to fix it but I found that here 2 independent issues:

### Issue 1
LVGL calculated the zoom with a minor inaccuracy. It can be fixed by this:
```patch
diff --git a/src/draw/lv_image_buf.c b/src/draw/lv_image_buf.c
index 7f5f161cc..551c15db2 100644
--- a/src/draw/lv_image_buf.c
+++ b/src/draw/lv_image_buf.c
@@ -73,18 +73,18 @@ void _lv_image_buf_get_transformed_area(lv_area_t * res, int32_t w, int32_t h, i
 
     lv_point_t p[4] = {
         {0, 0},
-        {w - 1, 0},
-        {0, h - 1},
-        {w - 1, h - 1},
+        {w, 0},
+        {0, h},
+        {w, h},
     };
     lv_point_transform(&p[0], angle, scale_x, scale_y, pivot, true);
     lv_point_transform(&p[1], angle, scale_x, scale_y, pivot, true);
     lv_point_transform(&p[2], angle, scale_x, scale_y, pivot, true);
     lv_point_transform(&p[3], angle, scale_x, scale_y, pivot, true);
     res->x1 = LV_MIN4(p[0].x, p[1].x, p[2].x, p[3].x);
-    res->x2 = LV_MAX4(p[0].x, p[1].x, p[2].x, p[3].x);
+    res->x2 = LV_MAX4(p[0].x, p[1].x, p[2].x, p[3].x) - 1;
     res->y1 = LV_MIN4(p[0].y, p[1].y, p[2].y, p[3].y);
-    res->y2 = LV_MAX4(p[0].y, p[1].y, p[2].y, p[3].y);
+    res->y2 = LV_MAX4(p[0].y, p[1].y, p[2].y, p[3].y) - 1;
 }
```

### Issue 2
There are all sort of minor rounding error in the SW render. It'd require more time to better understand how to approach it, but if you are using a GPU for image transformation it should work. I suggest adding these to the image to reduce the possible rounding errors:
```c
   lv_image_set_align(img_, LV_IMAGE_ALIGN_TOP_LEFT);
   lv_image_set_pivot(img_, 0, 0);
```

**Comment by XuNeo** [comment]
Hi Gabor,
Thank you for your quick response. We have tried solution for issue 1, and yes, it still has issue. So when there's no rotation, how the rounding error could happen? 

Say the image is 100x100, scale x2 should give us exactly 200x200. 
The method use for zoom is get transformed all four points (0,0), (99,0) .... 
Thus `99,0` is transformed to `198,0`. So the width becomes 198-0+1 = 199. Give us 1px error. I don't understand what's wrong here.

**Comment by kisvegabor** [comment]
Do you see the issue with GPU rotation too? If so, do you see any strange numbers in the transformed area?

**Comment by XuNeo** [comment]
This issue is reported on CPU only hardware. Thus no GPU is related.

**Comment by kisvegabor** [comment]
It means we need to deeply look into the SW image transformation. I'll try fixing it again.

**Comment by kisvegabor** [comment]
I should be fixed. Finally I added a special handling to image scale only (no rotation).

**Comment by kisvegabor** [comment]
I've already fixed it: https://github.com/lvgl/lvgl/commit/7b9f9a9f9e5c5e57077e09e7549889df3520b8af
