### ISSUE TITLE
About the Display Effect of List Title Background (v9)

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5005]
In v8, the background color of the list title is gray. But when it comes to v9, the title of the list is white, which makes it feel that the display effect of the title is not obvious. Please help repair it.
## v8
![Screenshot_20231213_181857_com huawei browser](https://github.com/lvgl/lvgl/assets/150422110/7c10f921-6b8f-446d-9a45-d50d908b1ec5)
## v9
![Screenshot_20231213_182434_com huawei browser](https://github.com/lvgl/lvgl/assets/150422110/9ba13e3f-e9ae-4606-a1bf-2c0c0b26814a)

**Comment by kisvegabor** [comment]
Hi,

Thank you for the report! 
I've just fixed it. :slightly_smiling_face:
