### ISSUE TITLE
Roller Widget in infinite mode not working with more than ~90 items

### ISSUE THREAD

**Issue by Lerosen** [kisvegabor/lvgl#5006]
### Perform all steps below and tick them with [x]
- [X ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ X] Update lvgl to the latest version
- [ X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)
  Reproduced it in the online simulator here https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html

### Describe the bug

The roller widget in infinite mode does not render if given many items. In my example with 100 options, these are not displayed anymore. This behavior can be observed in the simulator but also on my device (ESP32-S3 based)
With 80 items the selection is misaligned and on my device with touchscreen it is hard to deteministically select anything.

Without infinity mode everything works as expected.

Verison 8.3.0-dev

### Expected behavior

The roller options should be rendered correctly (see screenshot).

### Screenshots or video

misaligned @ 80
![image](https://github.com/lvgl/lvgl/assets/20213986/159a1c80-370c-4409-a8b2-9f5230c9caa6)

no options @ 100 items
![image](https://github.com/lvgl/lvgl/assets/20213986/17b4bb96-1bc1-4997-a1b7-797c8953b0b6)

expected @ 10 items
![image](https://github.com/lvgl/lvgl/assets/20213986/e922230d-b57a-4bdc-965c-e38f179b6878)

**Comment by supremeneuron** [comment]
I had a similar situation with 60 elements that the roller widget would not render accurately where it would properly snap to a set option.  I modified my lv_conf.h file as below and it seemed to solve the issue.

/*Extend the default -32k..32k coordinate range to -4M..4M by using int32_t for coordinates instead of int16_t*/
#define LV_USE_LARGE_COORD 1

**Comment by Lerosen** [comment]
I can confirm it ist working fine with that flag, thanks for your answer! 

I would suggest to add a Note regarding that behavior in the documentation of the Roller Widget.

**Comment by kisvegabor** [comment]
I updated the docs here: https://github.com/lvgl/lvgl/commit/68a7beb5d8e258d312f4099dbeb78eb1342870f2

FYI, in v9 it always works as always large coordinates are used.

**Comment by Lerosen** [comment]
Great and thanks for the quick help! Closing this issue now...
