### ISSUE TITLE
lvgl/lvgl.h

### ISSUE THREAD

**Issue by EBQA** [kisvegabor/lvgl#5026]
Hi All

I am using SMT32CubeIDE and I have followed all the steps in the form, downloading the latest library and still it this error pops out:

../Drivers/lvgl/tests/test_images/stride_align64/UNCOMPRESSED/test_A1_NONE_align64.c:7:10: fatal error: lvgl/lvgl.h: No such file or directory
    7 | #include "lvgl/lvgl.h"
      |          ^~~~~~~~~~~~~

Any Help?

**Comment by XuNeo** [comment]
Hi,
This is the test image for CI to run. Have you mistakenly included the 'tests/' directory in your project?

**Comment by EBQA** [comment]
yes it is included in the lvgl folder, when i try to delete it it shows me more than 300 errors! ;)
