### ISSUE TITLE
Dash width and gap are rendered incorrectly on horizontal lines.

### ISSUE THREAD

**Issue by philmoz** [kisvegabor/lvgl#5029]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Horizontal lines with dash_width and dash_gap are not drawn correctly.

E.G. If dash_width = 1 and dash_gap = 1 then the result is a solid horizontal line instead of a dotted line.

Vertical lines are drawn correctly.

### To Reproduce
```c
  lv_style_t style;
  lv_style_init(&style);
  lv_style_set_line_width(&style, 1);
  lv_style_set_line_dash_width(&style, 1);
  lv_style_set_line_dash_gap(&style, 1);

  lv_point_t pts[2] = {{50, 50}, {250, 50}};

  lv_obj_t* line = lv_line_create(lv_scr_act());
  lv_obj_add_style(line, &style, LV_PART_MAIN);
  lv_line_set_points(line, pts, 2);
```

### Expected behavior
Dash settings should render correctly.

### Screenshots or video
dash_width = 1 and dash_gap = 1
![Screenshot 2023-12-18 at 1 21 43 pm](https://github.com/lvgl/lvgl/assets/9474356/94b5838a-0d53-4c57-bf05-a4e894eb5d16)

dash_width = 2 and dash_gap = 2
![Screenshot 2023-12-18 at 1 21 17 pm](https://github.com/lvgl/lvgl/assets/9474356/584112eb-4593-4e1e-9522-f75bd9df02fc)

The problem is in src/draw/sw/lv_draw_sw_line.c lines 171 - 172.
Should be:
```c
                        if(dash_cnt < dsc->dash_width) {
                            int16_t diff = dsc->dash_width - dash_cnt - 1;
```

**Comment by kisvegabor** [comment]
Sorry, I missed this issue.

**Comment by kisvegabor** [comment]
I can't look into it now, but will check it soon.
