### ISSUE TITLE
`buf_clear_cb` and `buf_copy_cb` should not use GPU

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5037]
### Introduce the problem

User application could call lv_draw_buf_clear and renderer could also use GPU in the same time.

### Examples and cases

https://github.com/lvgl/lvgl/blob/3ececbfc93670af6bdaf4843ff3cb289a770fb04/src/draw/lv_draw.c#L389

### Suggested solution

Make it clear for GPU portings, take it into consideration or use CPU only.

cc @FASTSHIFT  Please comment if you have more questions.

**Comment by FASTSHIFT** [comment]
Yes, the GPU API is not necessarily thread-safe, and multi-threaded use may cause thread-safety issues.

**Comment by kisvegabor** [comment]
Besides we cannot start a GPU operation randomly as the GPU might work on a draw_task. 

I agree to keep it CPU only. What do you think about moving it to `lv_draw.c` as `lv_draw_clear_buf()`?

**Comment by XuNeo** [comment]
Should we simply implement them in `lv_draw_buf.c`? 
And keep the original name `lv_draw_buf_copy` or `lv_draw_buffer_copy` if we decide to change name.

**Comment by kisvegabor** [comment]
It also works, just remove the `callback` option (same as you did with the `go_to_xy`).
