### ISSUE TITLE
When `LV_CACHE_DEF_SIZE` is not 0, running the `test_clip_corner` will crash

### ISSUE THREAD

**Issue by W-Mai** [kisvegabor/lvgl#5058]
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When `LV_CACHE_DEF_SIZE` is not 0, running the `test_clip_corner` will crash.

The latest code in the master branch.

I got a crash like this.

<img width="961" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/7d069143-4d5f-498d-b615-c614156c56b6">

**Comment by XuNeo** [comment]
We haven't got time to debug it yet. Please help on it if you have time, the issue may be caused due to wrong data returned from cache.

To reproduce:
1. change lv_conf.h `#define LV_CACHE_DEF_SIZE       (1024*1024U)`
2. Add below test code to main()
```c

static lv_obj_t * create_panel(int32_t radius, bool transform)
{
    lv_obj_t * parent = lv_obj_create(lv_screen_active());
    lv_obj_set_style_pad_all(parent, 3, 0);
    lv_obj_set_style_radius(parent, radius, 0);
    lv_obj_set_style_clip_corner(parent, true, 0);
    if(transform) lv_obj_set_style_transform_rotation(parent, 300, 0);

    lv_obj_t * label = lv_label_create(parent);
    lv_obj_set_width(label, lv_pct(200));
    lv_label_set_text(label,
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dignissim quam id eros iaculis dapibus. Mauris nisl orci, vulputate sed eleifend a, consectetur et nulla.");
    lv_obj_set_style_text_font(label, &lv_font_montserrat_24, 0);
    lv_obj_set_style_bg_color(label, lv_palette_main(LV_PALETTE_RED), 0);
    lv_obj_set_style_bg_opa(label, LV_OPA_20, 0);

    lv_obj_update_layout(parent);
    lv_obj_scroll_by(parent, -15, -15, LV_ANIM_OFF);

    return parent;
}

void test_func_1(void)
{
    lv_obj_set_flex_flow(lv_screen_active(), LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(lv_screen_active(), LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_set_style_pad_column(lv_screen_active(), 40, 0);

    create_panel(0, false);
    create_panel(10, false);
    create_panel(30, false);
    create_panel(100, false);

    lv_obj_t * cont = create_panel(0, true);
    lv_obj_add_flag(cont, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);
    create_panel(10, true);
    create_panel(30, true);
    create_panel(100, true);
}

```

**Comment by W-Mai** [comment]
@XuNeo oh! Thank you for summary this case.

**Comment by XuNeo** [comment]
Haa, I have just found out the issue.

**Comment by W-Mai** [comment]
@XuNeo Great, I help you to submit the fix code in the last new change pr.

**Comment by XuNeo** [comment]
The issue is now fixed. For variable image, if it can be used directly like ARGB8888 etc, it won't be added to cache.
