### ISSUE TITLE
Is there a way to track changes in between different major versions of LVGL?

### ISSUE THREAD

**Issue by djixon** [kisvegabor/lvgl#5068]
It would be nice if some document(s) containing let's say changes made from v7 to v8 and changes made from v8 to v9 exist.

Yesterday I spent several hours trying to upgrade QMSD library (containing drivers for nine the most popular ESP32 LCD boards which is tightly dependent on LVGL v8.3.1 which is included within library)   
[https://github.com/smartpanle/QMSD-ESP32-BSP](url) to the last master branch and I gave up. So many changes and renaming (of types and enums) was made, that its impossible to track them without some documents where those changes are counted.

So here are some suggestions about future LVGL upgrades:
1. If ENUMS are renamed but their functionality is not changed please keep BOTH (old name and new name) sharing the same enum value for at least 1 major version upgrades. You can comment near OLD enum name that it will be removed in the next release but let it "live" at least 1 version. That way, upgrades of old CODE written for old LVGL versions can be upgraded to new versions much easier.  
2. If TYPE is just renamed, make typedef of old type with new type so both exists (compatible to newtype) for at least single version. That way even if type changed it's structure, user upgrading an old code can instantly see what is changed.  Compiler error let's say, property xxx does not exist in type yyy is much better (you can jump to definition of type yyy and see what is changed) than error like type yyy does not exist. In such a case you can not "jump", but have to search through old version where YYY was defined then to search through a new library version where it is migrated and renamed.... which is kind of nightmare 

But also having a PDF where all changes (related to renaming, types/enums changed/added, migration from one header to another etc)  from version to version would be helpful.

**Comment by kisvegabor** [comment]
I've written the [changelog](https://docs.lvgl.io/master/CHANGELOG.html) last week. It's still very new, so things might be missing. So feedback is welcome, but a Pull request is even more welcome :slightly_smiling_face:
