### ISSUE TITLE
Cannot compile lvgl with gcc on Windows due to obsolete stdint.h issue

### ISSUE THREAD

**Issue by ygramoel** [kisvegabor/lvgl#5070]
As part of my attempt to integrate LVGL support in Embeetle IDE, I am trying to compile LVGL (latest master revision as of today) with gcc on Windows.

This fails on the following code in `lvgl/src/libs/tjpgd/tjpgd.h`
```
#if defined(_WIN32) /* VC++ or some compiler without stdint.h */
typedef unsigned char   uint8_t;
typedef unsigned short  uint16_t;
typedef short           int16_t;
typedef unsigned long   uint32_t;
typedef long            int32_t;
#else               /* Embedded platform */
#include <stdint.h>
#endif
```
because _WIN32 is defined and the given definition of uint32_t is not compatible with the definition in gcc:
The exact error message is:
```
18:25: error: conflicting types for 'uint32_t'; have 'long unsigned int'
   18 | typedef unsigned long   uint32_t;
      |                         ^~~~~~~~
```
Note that VC++ has support for stdint.h  since 2012;  see https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h

It may therefore be worthwhile to consider to remove this code,  and unconditionally include stdint.h.  Alternatively, look for a way to detect the VC++ compiler,  because _WIN32 is not a reliable indicator of VC++.

For completeness,  this is the gcc compiler I am using: https://github.com/xpack-dev-tools/gcc-xpack/releases/tag/v12.3.0-1/

**Comment by kisvegabor** [comment]
Hi,

Thank you for pointing it out. I also agree that we an include `stdint.h` without any issues. Other parts of LVGL also rely on it.
