### ISSUE TITLE
Wrong casting in some widgets when calling lv_event_get_param.

### ISSUE THREAD

**Issue by jimbom** [kisvegabor/lvgl#5083]
### Perform all steps below and tick them with [x]
- [ x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [- ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Some widgets will not work properly on big endian architectures. I noticed it when using the tabview, which are using the button matrix, with a keypad. The tabs will then not change as expected (as it does in the simulator).

In case of events with code LV_EVENT_KEY, lv_event_get_param is returing an uint32_t pointer. However, in several widgets, this is casted to a char pointer:
`char c = *((char *)lv_event_get_param(e));`

In most cases this will work, but in big endian architectures this will always give c=0. I have found this issue in the following files, but I may have missed some:
lv_arc.c
lv_btnmatrix.c
lv_dropdown.c 
lv_obj.c
lv_roller.c
lv_slider.c

The solution should be to just replace the char with  uint32_t
`uint32_t c = *((uint32_t*)lv_event_get_param(e));`

### To Reproduce
Just add a tab view, or button matrix, to a big endian architecture.

### Expected behavior
The tabs in tabview should change also while using a keypad on a big endian architecture.

### Screenshots or video
NA

**Comment by kisvegabor** [comment]
Could you confirm if using
```c
uint32_t c = lv_event_get_key(e);
```
solves the issue?

**Comment by jimbom** [comment]
Seems like that should work! I can verify the first week in January when I have access to the hardware.

**Comment by kisvegabor** [comment]
Cool!

**Comment by jimbom** [comment]
I have now tested using 
`uint32_t c = lv_event_get_key(e);`
in lv_btnmatrix.c and can confirm that it solves the issue.

**Comment by kisvegabor** [comment]
That's great! Are you interested in sending a Pull request for it?

**Comment by jimbom** [comment]
I made an attempt :-)

**Comment by kisvegabor** [comment]
Let's continue in #5169
