### ISSUE TITLE
[scale] Add `length` style property

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#5099]
Add `length` property in style and use it in `scale` widget to set `major` and `minor` ticks length.

_Originally posted by @kisvegabor in https://github.com/lvgl/lvgl/issues/4678#issuecomment-1869085027_

**Comment by kisvegabor** [comment]
PR is sent, please review it: https://github.com/lvgl/lvgl/pull/5135
When it's merged, the scale can be updated to use the new length property.

**Comment by C47D** [comment]
I just reviewed it, it looks good to me.

**Comment by kisvegabor** [comment]
Thank you! Let's continue in the PR.
