### ISSUE TITLE
I tried to compile and build and example but got 'undefined reference to main`  in Ubuntu

### ISSUE THREAD

**Issue by raphael10-collab** [kisvegabor/lvgl#5105]
### What MCU/Processor/Board and compiler are you using?
x86_64
OS: Ubuntu 22.10
LVGL: 8.3

###  What do you want to achieve?
A working plain simple starter example

`lv_example_get_started_1.h` : 

I managed to compile both `lvgl` and `lv_drivers`:

```
    /home/raphy/LVGL/lvgl/demos/widgets/../../src/misc/../lv_conf_internal.h:46:17: note: ‘#pragma message: Possible failure to include lv_conf.h, please read the comment in this file if you get errors’
       46 |         #pragma message("Possible failure to include lv_conf.h, please read the comment in this file if you get errors")
          |                 ^~~~~~~
    [100%] Linking C static library liblvgl_demos.a
    [100%] Built target lvgl_demos

    raphy@raohy:~/LVGL/lv_drivers$ cmake --build build
    [ 95%] Building C object CMakeFiles/lv_drivers.dir/win_drv.c.o
    [100%] Linking C static library lib/liblv_drivers.a
    [100%] Built target lv_drivers
    raphy@raohy:~/LVGL/lv_drivers$ 
```

I tried to compile and build and example but got 'undefined reference to main` : 

```
raphy@raohy:~/LVGL/lvgl/examples/widgets/menu$ g++ lv_example_menu_1.c -std=c++17 -I ../../../src/ -I ../../../../lv_drivers/src -L ../../../build/lib -L ../../../../lv_drivers/build/lib/ -llvgl -o example_menu_1
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

What am I missing, and what do I have to do in order to make it work?

PS:
Due to this message in LVGL Forum (I previously created other topics which I deleted from the Forum)

    An error occurred: We appreciate your enthusiasm! That said, for the safety of our community, you’ve reached the maximum number of topics a new user can create on their first day. Please wait 16 hours and you’ll be able to create more new topics.

I had to ask this question here

**Comment by kisvegabor** [comment]
Note that LVGL is just a library. You need to provide the main.c file, drive initialization, etc.
See this project to get started: https://github.com/lvgl/lv_port_pc_eclipse

**Comment by raphael10-collab** [comment]
Thank you @kisvegabor
