### ISSUE TITLE
how use the LV_DRAW_BUF_DEFINE to load the image?

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5127]
![图片](https://github.com/lvgl/lvgl/assets/40679769/f31e9f60-3478-4199-a2b8-31afe4525b42)

i also inlucde the lv_draw_buf.h file,but  some compile error

**Comment by xinsuinizhuan** [comment]
I also add the .c files, but still could not link:
![图片](https://github.com/lvgl/lvgl/assets/40679769/32a5b558-5953-44f6-b653-71c19a8799af)

**Comment by XuNeo** [comment]
It looks like you haven't include the file to build. It complains no symbol can be found.

**Comment by xinsuinizhuan** [comment]
> It looks like you haven't include the file to build. It complains no symbol can be found.

how to include the file to build? I also inlcude the .c file in my project.

**Comment by xinsuinizhuan** [comment]
![图片](https://github.com/lvgl/lvgl/assets/40679769/c6c25984-610c-44b8-b434-de5e051b1bfa)

**Comment by XuNeo** [comment]
I'm not familiar with vscode. But the error suggests the symbol is not linked in. You can try to add faulty code to img_hand.c and compile to see if it reports error.

**Comment by xinsuinizhuan** [comment]
> I'm not familiar with vscode. But the error suggests the symbol is not linked in. You can try to add faulty code to img_hand.c and compile to see if it reports error.

I  add the faulty img_hand.c file to my project, if have some head file to add, or set some define to 1?

**Comment by xinsuinizhuan** [comment]
I resolve the problem， i create the preject is c++, and the main file is .cpp file, the .cpp file to load the imge .c buffer file, load false, it need to add extern "C".

**Comment by kisvegabor** [comment]
As the issue is resolved, I close it.
