### ISSUE TITLE
LV_METER documentation error

### ISSUE THREAD

**Issue by MrTechrics** [kisvegabor/lvgl#5143]
Hi i just noticed that there is a documentation error on the page for the LV_METER widget

Under parts and styles it says to use "LV_PART_TICK " but in code it is not "LV_PART_TICK" but "LV_PART_TICKS"

(https://docs.lvgl.io/8.3/widgets/extra/meter.html)

**Comment by kisvegabor** [comment]
Thanks, I've fixed it here: https://github.com/lvgl/lvgl/commit/e277114631da2caf6cebcf020ab19fdce6c068c0
