### ISSUE TITLE
Add memory leak test for image decoder

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5152]
Need some test to make sure when image is not added to cache, there's no memory leak.

> It would be nice to test it somehow. Calling `lv_image_decoder_open/close` manually combined with the rendering of the decoded image as a raw draw buf, and checking for [memory leak](https://github.com/lvgl/lvgl/blob/master/tests/src/test_cases/libs/test_lodepng.c#L61) might work.

_Originally posted by @kisvegabor in https://github.com/lvgl/lvgl/issues/5111#issuecomment-1872478244_

**Comment by XuNeo** [comment]
Yes, please. It may take me awhile to work on it.

**Comment by kisvegabor** [comment]
Pinned

**Comment by kisvegabor** [comment]
Continue in https://github.com/lvgl/lvgl/issues/5396
