### ISSUE TITLE
Adding an object to a group in theme callback is ineffective when a default group is set

### ISSUE THREAD

**Issue by clydebarrow** [kisvegabor/lvgl#5164]
### LVGL version

8.3.9

### What happened?

In a theme callback, an object is added to a group. But this happens before the default group is assigned to the object, so this is ineffective.

### How to reproduce?

```
lv_theme_set_apply_cb(lvthemetype, [](LvThemeType * th, LvObjType * obj) {
    if (lv_obj_check_type(obj, &lv_btn_class)) {
        lv_group_add_obj(lv_esp_group_general, obj);
        lv_obj_add_flag(obj, (int)LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    }
}
```

But the code in [`lv_obj_class.c`](https://github.com/lvgl/lvgl/blob/7963ffbe9c5bb1d1e3bc4da7c60bda207733ea9e/src/core/lv_obj_class.c#L96) is:

``` c
void lv_obj_class_init_obj(lv_obj_t * obj)
{
    lv_obj_mark_layout_as_dirty(obj);
    lv_obj_enable_style_refresh(false);

    lv_theme_apply(obj);      // <- theme apply sets group here
    lv_obj_construct(obj);

    lv_obj_enable_style_refresh(true);
    lv_obj_refresh_style(obj, LV_PART_ANY, LV_STYLE_PROP_ANY);

    lv_obj_refresh_self_size(obj);

    lv_group_t * def_group = lv_group_get_default();
    if(def_group && lv_obj_is_group_def(obj)) {
        lv_group_add_obj(def_group, obj);      // <-- Default group overwrites theme-set group
    }
...

```

**Comment by kisvegabor** [comment]
Hi,

I already see a few times that people are using the theme apply callback to do any kind modifications on the created widgets. 

I see why it's tempting but the apply callback is not designed for that. I think we need a specific mechanism to handle this. 

In v9 lv_display can have events similar to the widgets. A clean solution would be to use `LV_EVENT_CREATE` on a display for themes and user related things as well. What do you think?

For v8 I think the best would to modify `lv_obj_class_init_obj` locally as it's hard to measure what kind of issues it will cause in existing projects.
