### ISSUE TITLE
Can we add a macro definition for the selection of `bin_decoder`？

### ISSUE THREAD

**Issue by lhdjply** [kisvegabor/lvgl#5178]
### Introduce the problem

@XuNeo 
I find the line 198 in lv_init.c ,bin_decoder must be use.
https://github.com/lvgl/lvgl/blob/e217674295204785f3f61e299929f2943a97fdae/src/lv_init.c#L196-L199
Can we add a macro definition for the selection of `bin_decoder`?
For example add define in `lv_conf.h`
```c
#define LV_USE_BIN_DECODER 0
```

**Comment by XuNeo** [comment]
Without bin decoder, the whole draw image will not work. For example, lv_image_set_src will need to consult decoder for image header to get the image w,h etc.

**Comment by lhdjply** [comment]
> Without bin decoder, the whole draw image will not work. For example, lv_image_set_src will need to consult decoder for image header to get the image w,h etc.

Okay, I understand. I don't think `lv_bin_decoder. c` should be placed in the lib folder because it is usually optional to use in this folder.

**Comment by XuNeo** [comment]
The binary decoder was originally located in lv_image_decoder.c. However, due to its increased complexity, it has been moved to the libs directory alongside other decoders.
