### ISSUE TITLE
CI break due to micropython script update

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5182]
### Introduce the problem

A dirty fix would be https://github.com/lvgl/lv_binding_micropython/pull/309
I don't know why it doesn't report error before. There's a variable in ESP named `del` which is a keyword in python, thus script converted to `_del`.

**Comment by XuNeo** [comment]
I guess the original script doesn't correctly generates all bindings. With latest script, it includes some new struct, thus `del` is now included.

**Comment by XuNeo** [comment]
Script has been updated. Manually test passes now. 
The issue is that script incorrectly sanitizes the C struct field.

**Comment by PGNetHun** [comment]
@XuNeo , I can test this also with unix and esp32-generic port, so please wait merging this.

**Comment by PGNetHun** [comment]
> @XuNeo , I can test this also with unix and esp32-generic port, so please wait merging this.

Tested your PR only with unix port, it's OK, no compilation nor runtime errors.

**Comment by kisvegabor** [comment]
Merged and the submodule is updated in `lv_micropython.`

Now the CI passes! :tada:
