### ISSUE TITLE
Compilation error when LV_USE_LINUX_FBDEV and LV_LVGL_H_INCLUDE_SIMPLE defined in v9

### ISSUE THREAD

**Issue by rmshub** [kisvegabor/lvgl#5191]
### Introduce the problem

The following error observed when Frame buffer `LV_USE_LINUX_FBDEV` and `LV_LVGL_H_INCLUDE_SIMPLE` defined.
`/components/lvgl/lvgl/src/dev/display/fb/lv_linux_fbdev.c:29:10: fatal error: lvgl/lvgl.h: No such file or directory
 #include <lvgl/lvgl.h>`

### Proposal

Change header include as follows:
```
#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
```

**Comment by C47D** [comment]
Hi, could you please send a Pull request with the proposed fix?

**Comment by rmshub** [comment]
#5192

**Comment by kisvegabor** [comment]
Thank you! Let continue in the PR
