### ISSUE TITLE
v9 github codespace fails to build

### ISSUE THREAD

**Issue by ttump** [kisvegabor/lvgl#5203]
### LVGL version

v9 current github

### What happened?

Followed to 3 clicks vscode github codespace procedure, build fails with multiple errors of the same type

/usr/local/emsdk/upstream/emscripten/cache/sysroot/include/bits/alltypes.h:182:15: error: Expected ,, instead got: int16_t
typedef short int16_t;
              ^
make[2]: *** [lvgl/CMakeFiles/lvgl.dir/build.make:1155: lvgl/CMakeFiles/lvgl.dir/src/draw/sw/blend/neon/lv_blend_neon.S.o] Error 1

**Comment by C47D** [comment]
@kisvegabor Sounds like the same issue we had at eclipse, is it?

**Comment by kisvegabor** [comment]
It should be fixed by #5209.

To test it just remove the `#include <stdint.h>` at the beginning of `lv_conf.h`

**Comment by ttump** [comment]
That works fine, thank you. Good luck with the release of v9

**Comment by kisvegabor** [comment]
Thank you :blush:
