### ISSUE TITLE
lv_image_set_src: failed to get image info: E:/lvgl/git/lvgl-master/examples/libs/bmp/example_32bit.bmp lv_image.c:175

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5214]
### LVGL version

v9.0.0

### What happened?

the lv_example_bmp_1.c example,
/**
 * Open a BMP file from a file
 */
void lv_example_bmp_1(void)
{
	lv_obj_t* img = lv_image_create(lv_screen_active());
	/* Assuming a File system is attached to letter 'A'
	 * E.g. set LV_USE_FS_STDIO 'A' in lv_conf.h */
	lv_image_set_src(img, "E:/lvgl/git/lvgl-master/examples/libs/bmp/example_32bit.bmp");
	lv_obj_center(img);

}

[Warn]  (7889.578, +7889578)     lv_image_set_src: failed to get image info: E:/lvgl/git/lvgl-master/examples/libs/bmp/example_32bit.bmp lv_image.c:175
[Warn]  (7889.578, +0)   _lv_display_refr_timer: No draw buffer lv_refr.c:349

### How to reproduce?

run the lv_example_bmp_1.c example, in widows

**Comment by kisvegabor** [comment]
`E:` is not your drive on Window but a File system identifier for LVGL. See [here](https://docs.lvgl.io/master/overview/fs.html).

**Comment by xinsuinizhuan** [comment]
> `E:` is not your drive on Window but a File system identifier for LVGL. See [here](https://docs.lvgl.io/master/overview/fs.html).

I am still don't know how to do, i only want to load a image by gived image path? how to do, for example?
 i try to do below, but nod sucess:
lv_conf.h:
![图片](https://github.com/lvgl/lvgl/assets/40679769/ee9d7de6-8cb0-47d8-bc8a-4e4889f1be9a)
the run:
void lv_example_libjpeg_turbo_1(void)
{
	lv_obj_t* wp;

	wp = lv_image_create(lv_screen_active());
	/* Assuming a File system is attached to letter 'A'
	 * E.g. set LV_USE_FS_STDIO 'A' in lv_conf.h */
	lv_image_set_src(wp, "E:lvgl/examples/libs/libjpeg_turbo/flower.jpg");
	lv_obj_center(wp);
}
but still could not find image:
![图片](https://github.com/lvgl/lvgl/assets/40679769/ab198c9f-533a-4d00-bafd-cc1c75d60041)

**Comment by kisvegabor** [comment]
Have you installed and enabled turbo-jpeg? If not I suggest using TJPGD
