### ISSUE TITLE
[Micropython] feat/multi-instance, canvas.init_layer() is freezing after Jan 4 commit

### ISSUE THREAD

**Issue by sam0910** [kisvegabor/lvgl#5225]
### LVGL version

v9.0.0

### What happened?

Compiling feat/multi-instance branch with [lvgl@e217674](https://github.com/lvgl/lvgl/commit/e217674295204785f3f61e299929f2943a97fdae) ([#5161](https://github.com/lvgl/lvgl/pull/5161)) ```chore: move lv_obj_t define to lv_types.h```
it was Jan 4, after that commit, canvas.init_layer() is causing the board freezing.
lv.image(), lv.label() is working normally, only happens on canvas.init_layer().

previous commit [lvgl@11afc95](https://github.com/lvgl/lvgl/commit/11afc952e411e3144ebb909a8d7b17bba0290bb3) is working fine.

ESP32 + SPIRAM, ESP-IDF v4.4.6, GC9A01 display.

### How to reproduce?

```
cbuf = bytearray(100 * 100 * 4)
canvas = lv.canvas(lv.screen_active())
canvas.set_buffer(cbuf, 100, 100, lv.COLOR_FORMAT.NATIVE)
canvas.fill_bg(lv.color_hex(0xCCCCCC), lv.OPA.COVER)
canvas.center()

layer = lv.layer_t()
canvas.init_layer(layer)
```

**Comment by kisvegabor** [comment]
@XuNeo Can it be related to the changes [here](https://github.com/lvgl/lvgl/pull/5132/files#diff-44e6c48dcb2ea880a01bbae515ecb86bba087c705413c45a37e7f9eccd43ab5b)?

**Comment by XuNeo** [comment]
I cannot reproduce it using ports/unix simulator.
Board freezing could be due to an assert happened. Enable all logs and check where it reports error.

**Comment by sam0910** [comment]
It is not happening on latest PR on lv_binding_micropython, [Update LVGL to v9 prerelease version #311](https://github.com/lvgl/lv_binding_micropython/pull/311)

It will be merged soon, It is solved!
Thank you so much for the concern, and I am very grateful to use latest v9 !
