### ISSUE TITLE
Type `lv_draw_glyph_bitmap_format_t ` should be removed and use `lv_font_glyph_format_t` 

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5234]
This type(`lv_draw_glyph_bitmap_format_t`) should be removed and `lv_font_glyph_format_t` should be used instead. (See below).

_Originally posted by @kisvegabor in https://github.com/lvgl/lvgl/pull/5154#discussion_r1442898229_

**Comment by XuNeo** [comment]
Not stale. Will working on it in coming days.

**Comment by W-Mai** [comment]
In progress now
