### ISSUE TITLE
After scaling the image, there is a slight abnormality in the edges of the image.

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5237]
### LVGL version

v9.0.0

### What happened?
CC @XuNeo @kisvegabor 
After scaling the image, there is a slight abnormality in the edges of the image.
The image format is: `LV_COLOR_FORMAT_ARGB8888`.
In V8.3, there is no problem using `LV_IMG_CF_TRUE_COLOR_ALPHA`.
![image](https://github.com/lvgl/lvgl/assets/150422110/6628c266-6773-4406-9b4c-cb5484a611cb)

### How to reproduce?

```c
LV_IMG_DECLARE(img_test);
void img_scale_test(void)
{
  lv_obj_t *logo1;
  logo1 = lv_image_create(lv_screen_active());
  lv_image_set_src(logo1, &img_test);
  lv_obj_align(logo1,LV_ALIGN_CENTER,-110,0);
  lv_image_set_scale(logo1, 256);

  lv_obj_t *logo2;
  logo2 = lv_image_create(lv_screen_active());
  lv_image_set_src(logo2, &img_test);
  lv_obj_align(logo2,LV_ALIGN_CENTER,110,0);
  lv_image_set_scale(logo2, 255);
}
```

**Comment by kisvegabor** [comment]
Hi, 

thank you for the report. Please attach the test image too.

**Comment by IAMMX** [comment]
![img_test](https://github.com/lvgl/lvgl/assets/150422110/05d84e71-e46a-4d9a-ae55-95600bf677bf)

**Comment by IAMMX** [comment]
![Uploading img_test.png…]()

**Comment by IAMMX** [comment]
![img_test](https://github.com/lvgl/lvgl/assets/150422110/7354024f-896b-4cec-8ac0-f4f58ecc85b8)

**Comment by IAMMX** [comment]
no stale

**Comment by kisvegabor** [comment]
Should be related to https://github.com/lvgl/lvgl/issues/5447

**Comment by IAMMX** [comment]
ok👌

**Comment by lhdjply** [comment]
related to #5548 ,please test it

**Comment by kisvegabor** [comment]
It turned out that it's hard to solve rounding error. It would require a large rework on the transformation system.

I close it for now.
