### ISSUE TITLE
Use `LV_PCT` is not correct in `lv_obj_align_to`

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5241]
### LVGL version

v9.0.0

### What happened?

Use `LV_PCT` is not correct in `lv_obj_align_to`

### How to reproduce?

```c
void lv_pct_test(void)
{
  lv_obj_t *obj1,*obj2;

  obj1=lv_obj_create(lv_screen_active());
  lv_obj_set_style_bg_color(obj1,lv_palette_main(LV_PALETTE_RED),LV_PART_MAIN);
  lv_obj_align(obj1,LV_ALIGN_TOP_MID,0,0);

  obj2=lv_obj_create(lv_screen_active());
  lv_obj_set_style_bg_color(obj2,lv_palette_main(LV_PALETTE_BLUE),LV_PART_MAIN);
  lv_obj_align_to(obj2,obj1,LV_ALIGN_OUT_BOTTOM_MID,0,LV_PCT(1));
}
```

**Comment by kisvegabor** [comment]
What would be the expected behavior in your opinion? Which object's which property's 1% shall be considered?

**Comment by IAMMX** [comment]
> What would be the expected behavior in your opinion? Which object's which property's 1% shall be considered?

Both obj1 and obj2 are created on lv_screen_active. Once obj2 is moved down 1% based on obj1, it should normally be very close to obj1. But the actual result is that obj2 goes to the next page.

**Comment by kisvegabor** [comment]
I mean 1% of 
- obj1
- obi2
- parent of obj1
- or parent of obj2

Normal `lv_obj_align` uses the parent size, in case of `lv_obj_align_to` obj1 and obj2 can be on different parents.

**Comment by IAMMX** [comment]
I think it means 1% of  the obj size.But in the video, the 1% is so large.

**Comment by kisvegabor** [comment]
Think more about it I agree to use `obj1` (base) for percentage calculation.

Adding this [here](https://github.com/lvgl/lvgl/blob/master/src/core/lv_obj_pos.c#L454) should fix it.  
```c
    if(LV_COORD_IS_PCT(x_ofs)) x_ofs = (lv_obj_get_width(base) * LV_COORD_GET_PCT(x_ofs)) / 100;
    if(LV_COORD_IS_PCT(y_ofs)) y_ofs = (lv_obj_get_height(base) * LV_COORD_GET_PCT(y_ofs)) / 100;
```

It's not clear for me if we should use the `content_width/height` (reduced by padding) or the normal width/height. As these alignment is usually used to position widgets next each other, I think normal width/height is a better choice.

**Comment by IAMMX** [comment]
Oh，thank you

**Comment by IAMMX** [comment]
let's continue in #5252
