### ISSUE TITLE
Memory leak in draw sw arc

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5242]
### LVGL version

master

### What happened?

Memory leak reported in `lvgl/src/draw/sw/lv_draw_sw_arc.c:126`

### How to reproduce?

Change `tests/src/lv_test_conf.h`
```c
+#define LV_DRAW_BUF_STRIDE_ALIGN               1
+#define LV_DRAW_BUF_ALIGN                      1
```

Run `./main.py test`

**Comment by kisvegabor** [comment]
Should be fixed in #5245
