### ISSUE TITLE
Child with zero radius is overflow from parent with radius

### ISSUE THREAD

**Issue by rmshub** [kisvegabor/lvgl#5251]
### Introduce the problem

I added a two button (Cancel and Sumbit) with 0 as radius at bottom of a parent container with radius 10. Both buttons overflow over the parent container. This issue present in both v8.3.11 and v9 verisons

![image](https://github.com/lvgl/lvgl/assets/38435057/85496c44-1aa6-4abc-9cb0-2ff77370c0cd)

How to avoid the overflow child area from parent container

**Comment by kisvegabor** [comment]
You can enable the `clip_corner` style property.

**Comment by rmshub** [comment]
It is working with `clip_corner` style property.
