### ISSUE TITLE
Use draw_buf in API  lv_snapshot_take_to_buf(obj, draw_buf)

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5261]
Let's change the API `lv_snapshot_take_to_buf ` to lv_snapshot_take_to_buf(obj, draw_buf) in future.
For now you can use `lv_draw_buf_from_image(&draw_buf, dsc);` directly.

Unified draw buffer is much easier to use instead of raw pointers.

_Originally posted by @XuNeo in https://github.com/lvgl/lvgl/pull/5254#discussion_r1447094941_

**Comment by kisvegabor** [comment]
I agree that stride needs to be controlled here to make the image usable for GPUs.

It would be even better if `draw_buf` and `image_dsc` were unified so the taken image would be usable as an image (I know it is, but the names don't suggest that)

Just confirm it would look like this:
```c
lv_draw_buf_t * draw_buf = lv_draw_buf_create(300, 200, LV_COLOR_FORMAT_ARGB8888, 0);
lv_snapshot_take_to_buf(obj, draw_buf);
```

or
```c
lv_draw_buf_t draw_buf;
lv_draw_buf_init(&draw_buf, 300, 200, LV_COLOR_FORMAT_ARGB8888, 0, my_buf, my_buf_size);
lv_snapshot_take_to_buf(obj, &draw_buf);
```

On a side note, what do you think about having `#define LV_STRIDE_AUTO 0`?

**Comment by XuNeo** [comment]
> On a side note, what do you think about having `#define LV_STRIDE_AUTO 0`?

Totally agree. It's done in another patch but dropped later. Will do so soon.



> Just confirm it would look like this:
> 
> ```c
> lv_draw_buf_t * draw_buf = lv_draw_buf_create(300, 200, LV_COLOR_FORMAT_ARGB8888, 0);
> lv_snapshot_take_to_buf(obj, draw_buf);
> ```

No. If the buffer is going to be created, then use `lv_snapshot_take` directly. `lv_snapshot_take_to_buf` is only used when same buffer is reused to take multiple snapshots.



> or
> 
> ```c
> lv_draw_buf_t draw_buf;
> lv_draw_buf_init(&draw_buf, 300, 200, LV_COLOR_FORMAT_ARGB8888, 0, my_buf, my_buf_size);
> lv_snapshot_take_to_buf(obj, &draw_buf);
> ```

How about we approche it similarly with display buffer. Add api lv_snapshot_take_to_draw_buf(obj, draw_buf); 
We should provide a helper `lv_snapshot_create_draw_buf(obj)` too.

**Comment by kisvegabor** [comment]
> How about we approche it similarly with display buffer. Add api lv_snapshot_take_to_draw_buf(obj, draw_buf);
We should provide a helper lv_snapshot_create_draw_buf(obj) too.

I was thinking about the same, but here I can't see the value of having the current API. Listing buf, width, height, color format in `lv_draw_buf_init` is just one extra line of code. And to use the raw buffer, you still need to create an image manually. With `draw_buf` we can easily convert between images and darw_bufs.

**Comment by XuNeo** [comment]
Let's continue in https://github.com/lvgl/lvgl/pull/5487
