### ISSUE TITLE
Add unit test for bin decoder cache behavior

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5266]
For images that can be drawn directly, do not add to cache. Need test for this behavior.

              Is there a way to write a unit test for it?

_Originally posted by @kisvegabor in https://github.com/lvgl/lvgl/issues/5162#issuecomment-1874988406_

**Comment by XuNeo** [comment]
Not stale

**Comment by kisvegabor** [comment]
Not stale
