### ISSUE TITLE
newest version, could not show!!! _lv_display_refr_timer: No draw buffer lv_refr.c:350

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5271]
### LVGL version

v9.0.0

### What happened?

time:2024/01/11 version, when i run the lv_demo_widgets, no UI show:
![图片](https://github.com/lvgl/lvgl/assets/40679769/c833cbe6-771d-4576-ad5f-ba2e39eead5f)

### How to reproduce?

run  lv_demo_widgets, in windows!

**Comment by kisvegabor** [comment]
Should be related to #5273. We will revert this change but until that you can set `LV_MEM_SIZE` to `8*1024*1024`

**Comment by xinsuinizhuan** [comment]
> 8*1024*1024

I set  #define LV_MEM_SIZE (8*1024*1024) in lv_conf.hv, but still not work

**Comment by XuNeo** [comment]
@xinsuinizhuan Please apply the patch https://github.com/lvgl/lvgl/pull/5274 and have a try.
