### ISSUE TITLE
github codespaces can't build in latest version now

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5295]
### LVGL version

v9.0.0

### What happened?

![屏幕截图 2024-01-12 133012](https://github.com/lvgl/lvgl/assets/150422110/85d6194e-14b7-412f-90e3-241cff70f047)

**Comment by kisvegabor** [comment]
I've started to update the cache of Codespace. It should work in ~20 minutes.

**Comment by IAMMX** [comment]
> I've started to update the cache of Codespace. It should work in ~20 minutes.

Cool

**Comment by kisvegabor** [comment]
Can you confirm it's working on your end?

**Comment by IAMMX** [comment]
yes

**Comment by kisvegabor** [comment]
Great, thank you
