### ISSUE TITLE
Calendar can't show highlighted_dates and today_date

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5296]
### LVGL version

v9.0.0

### What happened?
Calendar can't show highlighted_dates and today_date
https://docs.lvgl.io/master/widgets/calendar.html
![image](https://github.com/lvgl/lvgl/assets/150422110/600cc3c7-f01b-401f-b81d-9d394e31ece6)
![image](https://github.com/lvgl/lvgl/assets/150422110/affe0c51-5cc8-446a-bf04-3b216238df20)

**Comment by kisvegabor** [comment]
I'll check it at latest on Monday.

**Comment by C47D** [comment]
I went back to 00825c1ff to check if the latest change of calendar caused the issue and I see the same issue
![image](https://github.com/lvgl/lvgl/assets/11037705/f16e5709-54af-4979-8c61-4d08263bb3a7)

I will try to take a look at it, I'm not very familiar with the calendar widget.

**Comment by IAMMX** [comment]
Now it is correct ,thanks
