### ISSUE TITLE
Why is lv_obj called lv_obj?

### ISSUE THREAD

**Issue by voltangle** [kisvegabor/lvgl#5302]
### Introduce the problem

Knowing that in the documentation all objects are usually called "widgets" (even the top-level group for all objects in the documentation is called Widgets), why is `lv_obj` called `lv_obj`, and not `lv_widget`? Or am I missing something? 😅

**Comment by kisvegabor** [comment]
I agree with you and I've proposed to rename it to `lv_widget` for v9 but as feedback basically all people said that the large API change would cause bigger trouble than it solves :smile:

**Comment by ggoraa** [comment]
That's _is_ quite interesting 🧐 
In that case, can I name the widget class `lvgl::Widget` in the C++ binding, as a kind of "start" to the name migration? 😅

**Comment by XuNeo** [comment]
> And also, isn't it possible to rename `lv_obj` to `lv_widget`, place a `typedef lv_widget lv_obj` for backwards compatibility, mark `lv_obj` deprecated, and then nuke it a major version after?)

The main problem is all those APIs/types/variables started with `lv_obj_` prefix. Those are massive.

**Comment by ggoraa** [comment]
Oh, yes, right, I forgot about those...
That would definitely make the refactor much larger and more impactful

**Comment by kisvegabor** [comment]
Later, we can investigate how can we make a gradual translation without breaking.

**Comment by ufbycd** [comment]
> That's _is_ quite interesting 🧐 In that case, can I name the widget class `lvgl::Widget` in the C++ binding, as a kind of kickstart to the name migration? 😅
> 
> And also, isn't it possible to rename `lv_obj` to `lv_widget`, place a `typedef lv_widget lv_obj` for backwards compatibility, mark `lv_obj` deprecated, and then nuke it a major version after?)

We can define some macros for backward compatibility. For example:
```C
#define lv_obj_t lv_widget_t
#define lv_obj_set_x lv_widget_set_x
```
