### ISSUE TITLE
Build error while enabling file system

### ISSUE THREAD

**Issue by caichao** [kisvegabor/lvgl#5307]
### Introduce the problem

I am trying to enable FatFs file system while  using LVGL libs.

I clone the official repository here: https://blog.lvgl.io/2018-01-03/linux_fb#other-notes

I can make the right output. When I enable the file system by enabling the following defines

![image](https://github.com/lvgl/lvgl/assets/3417516/03de1910-bb5c-492a-bd7b-b44778ba0c92)

![image](https://github.com/lvgl/lvgl/assets/3417516/75326562-b853-4ce0-972f-e043505c0a42)

I still cannot make it right. The follow errors occur:

![image](https://github.com/lvgl/lvgl/assets/3417516/5b416851-b92d-42c8-9623-9dcb580801ab)

I just search over the source file and then enable WIN32 in the Makefile, try building again:
![image](https://github.com/lvgl/lvgl/assets/3417516/01cc2671-e170-41a4-a4ac-38c25a3747bb)

New errors occur:
![image](https://github.com/lvgl/lvgl/assets/3417516/1523b1d2-ab50-4f51-a453-b43358af5c63)

Can anybody tell me how to fix these problems?
Thanks in advance.

**Comment by caichao** [comment]
By the way, I can build bin file if do not activate file system and see the demo under build/bin folder.

**Comment by kisvegabor** [comment]
`DT_DIR` in not defined in C)) but a GCC extension. See [here](https://stackoverflow.com/questions/46694350/cant-compare-dirent-d-type-to-dt-dir).

Can you try `LV_USE_FS_POSIX`?

**Comment by caichao** [comment]
Not ok. post the following error:
![image](https://github.com/lvgl/lvgl/assets/3417516/a2aa9ca5-bc5e-4fb3-8fdc-77e7b83bbec1)

Thanks for your response

**Comment by caichao** [comment]
I feel confused. When I first change to LV_USE_FS_POSIX, I get the aforementioned error. It seems that ffmpeg is not installed. However, when I make clean and make again. The same problem happens again. 

![image](https://github.com/lvgl/lvgl/assets/3417516/623947e5-4345-46f2-b441-523822120287)

**Comment by caichao** [comment]
> `DT_DIR` in not defined in C99 but a GCC extension. See [here](https://stackoverflow.com/questions/46694350/cant-compare-dirent-d-type-to-dt-dir).
> 
> Can you try `LV_USE_FS_POSIX`?

Problem solved when add the macro "_DEFAULT_SOURCE"

**Comment by caichao** [comment]
Thanks for the help

**Comment by kisvegabor** [comment]
Great!
