### ISSUE TITLE
LV_USE_DEV_VERSION should be delete

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5311]
### Introduce the problem
@kisvegabor  @FASTSHIFT 
v9 will be released tomorrow, should we delete this code?
https://github.com/lvgl/lvgl/blob/2cbeddce8a74007c101967c5e744cfd087141701/lvgl.h#L140-L142

**Comment by FASTSHIFT** [comment]
I agree.

**Comment by kisvegabor** [comment]
See #5312
