### ISSUE TITLE
missing years in calendar V8.3 and V9

### ISSUE THREAD

**Issue by GastonHP** [kisvegabor/lvgl#5315]
### LVGL version

8.3.9 and 9

### What happened?

the dropdown list of years in calendar does not contain  years after 2023!  I fixed it localy in the source lv_calendar_obj_dropdown.c by adding missing years in static const char * year_list...

**Comment by C47D** [comment]
Related to #5202 
What should be the solution here @kisvegabor ? Using a custom year list?

**Comment by kisvegabor** [comment]
Now we have function to set a custom year list. I think we should add both 2024 and 2025 to the default year list to be future proof.

**Comment by C47D** [comment]
On it
