### ISSUE TITLE
v9.0.0 `LV_STYLE_TRANSFORM_SCALE` not defined

### ISSUE THREAD

**Issue by s-hadinger** [kisvegabor/lvgl#5343]
### LVGL version

V9.0.0

### What happened?

In `lv_api_map.h`: line 246:

`#define LV_STYLE_TRANSFORM_ZOOM       LV_STYLE_TRANSFORM_SCALE`

`LV_STYLE_TRANSFORM_SCALE` is not defined, there must be a typo somewhere.

https://github.com/lvgl/lvgl/blob/fb0fc86895331bac9f5ce514ef6324342e8ed3c6/src/lv_api_map.h#L246C1-L246C63

### How to reproduce?

Compilation issue found by Berry mapping

**Comment by s-hadinger** [comment]
I suppose it should be replaced with:
```C
#define LV_STYLE_TRANSFORM_ZOOM_X       LV_STYLE_TRANSFORM_SCALE_X
#define LV_STYLE_TRANSFORM_ZOOM_Y       LV_STYLE_TRANSFORM_SCALE_Y
```

**Comment by kisvegabor** [comment]
In v8 there was no ZOOM_X and ZOOM_Y only ZOOM. Therefore `LV_STYLE_TRANSFORM_SCALE_X/y` has no v8 counterpart. I think these rather should be removed.

**Comment by s-hadinger** [comment]
So let's remove. It breaks the Berry mapping since `LV_STYLE_TRANSFORM_SCALE` is not defined.

**Comment by kisvegabor** [comment]
I'm afraid many other things need to be updated for v9 too. :sweat_smile:

**Comment by s-hadinger** [comment]
The good news is that it's the only constant that broke the mapping engine.

**Comment by kisvegabor** [comment]
Oh, very nice! Btw, can you give give some feedback about how often lvgl used with Tasmota?

**Comment by s-hadinger** [comment]
Not so many users yet, but we're seeing a slowly increasing number of questions about LVGL in Tasmota. Actually many prefer to use HASPmota (our own flavor of OpenHASP) based on LVGL, but easier to use quickly.
