### ISSUE TITLE
windows,break!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5397]
### LVGL version

v9.0.0

### What happened?

new version,time 20240119:
![图片](https://github.com/lvgl/lvgl/assets/40679769/baa300f8-391d-4d4b-bcba-e82752b92da8)

### How to reproduce?

run lv_demo_widgets in windows

**Comment by W-Mai** [comment]
Please try the latest code. Try to see if there is still a current problem.
