### ISSUE TITLE
[C++] support non zero terminated strings

### ISSUE THREAD

**Issue by jrahlf** [kisvegabor/lvgl#5399]
### Introduce the problem

When calling lvgl functions from C++, you might have `std::string_view`, which are not guaranteed to be zero terminated. One must then first copy the string_view contents into a zero terminated string and then call lvgl functions (which most likely copies the data again..).

### Proposal

This problem can be fixed by adding a second function which takes the string length as a parameter. The existing functions then become mere wrappers around the new functions.

```c
void lv_label_set_text(lv_obj_t *obj, const char *text, unsigned int text_length);

static inline void lv_label_set_text(lv_obj_t *obj, const char *text)
{ 
  lv_label_set_text(obj, text, strlen(text)); 
}
```

**Comment by and-elf** [comment]
Why bother with string_view with c? You could just pass const string& all over your copy and do c_str when using the c api. 
I realize string_view gives you now freedom in CPP, but it doesn't play very nice with c
