### ISSUE TITLE
Bugs in lv_gridnav's function

### ISSUE THREAD

**Issue by TCRnext** [kisvegabor/lvgl#5409]
### LVGL version

v9.0.0

### What happened?

![图片](https://github.com/lvgl/lvgl/assets/141553835/f9f3c5f5-4b52-47b3-bcaf-40df221023a0)
In function void lv_gridnav_remove(lv_obj_t * obj) if the obj has no event which has its callback function is gridnav_event_cb, but the obj has at least one event.The function will delete the last event of the obj and free its userdata.In some case,it's will course immediately crash.

### How to reproduce?

    if(event_dsc) {
        if(lv_event_dsc_get_cb(event_dsc) == gridnav_event_cb){
            lv_free(lv_event_dsc_get_user_data(event_dsc));
            lv_obj_remove_event(obj, i);

        }

    }

**Comment by kisvegabor** [comment]
Continue in https://github.com/lvgl/lvgl/pull/5410
