### ISSUE TITLE
.C and .SJPG decoder not working

### ISSUE THREAD

**Issue by spytaspund** [kisvegabor/lvgl#5411]
### LVGL version

v8.3.9

### What happened?

I am trying to decode one .sjpg image stored in SPIFFS. Tested filesystem like this: 
```
lv_fs_file_t f;
    lv_fs_res_t res;
    res = lv_fs_open(&f, "A:/spiffs/sjpegtile.sjpg", LV_FS_MODE_RD);
    if(res != LV_FS_RES_OK)
        Serial.printf("lv file err, %d", res);
    else
    {
        char buf[60];
        lv_fs_read(&f, buf, 40, NULL);
        Serial.printf("%s", buf);
    }
```
And serial prompt prints first symbols of a file: `_SJPG  `
But, when I try to decode this image:
`lv_img_set_src(tile_00, "A:/spiffs/sjpegtile.sjpg");`
Nothing happens. Also, `tile_00` is a member of another object, that is visible on the screen, but `tile_00` is not.

LOGGING ENABLED (level trace), but shows nothing.
In `lv_conf.h` enabled LV_USE_SJPG and LV_FS_USE_STDIO
MCU is esp32doit-devkit-v1

### How to reproduce?
```
lv_obj_t tile_00;
lv_img_create(lv_scr_act());
lv_obj_set_size(tile_00, 256,256);
lv_obj_align(tile_00, LV_ALIGN_CENTER, 0, 0);

lv_fs_file_t f;
    lv_fs_res_t res;
    res = lv_fs_open(&f, "A:/spiffs/sjpegtile.sjpg", LV_FS_MODE_RD);
    if(res != LV_FS_RES_OK)
        Serial.printf("lv file err, %d", res);
    else
    {
        char buf[60];
        lv_fs_read(&f, buf, 40, NULL);
        Serial.printf("%s", buf);
    }

lv_img_set_src(tile_00, "A:/spiffs/sjpegtile.sjpg", LV_FS_MODE_RD);
//OR
//lv_img_set_src(tile_00, "A:/spiffs/sjpegtile.c", LV_FS_MODE_RD);
```

**Comment by PGNetHun** [comment]
Hello!
If only a black box is shown instead the JPEG, and no error, then try fixing the color format in `lv_sjpg.c` file like in this PR: https://github.com/lvgl/lvgl/pull/4473/files#diff-2fc24a411b3721d06a9b849261e6acd3d7ede8e47af2a1eabb43150894a55dd4
