### ISSUE TITLE
Use the `lv_obj_set_style_transform_scale` function to scale, and there will still be residual borders when zoomed out.

### ISSUE THREAD

**Issue by lhdjply** [kisvegabor/lvgl#5447]
### LVGL version

v9.0.0

### What happened?

Use the `lv_obj_set_style_transform_scale` function to scale, and there will still be residual borders when zoomed out.

https://github.com/lvgl/lvgl/assets/18370433/5fa0469b-1846-4527-9bb2-171f46333a7f

### How to reproduce?

```c
static void anim_cb(void * obj, int32_t value)
{
  lv_obj_set_style_transform_scale(obj, value, LV_PART_MAIN);
}

void test_demo(void)
{
  lv_obj_t *obj=lv_obj_create(lv_screen_active());
  lv_obj_set_size(obj,200,200);
  lv_obj_set_style_bg_color(obj,lv_palette_main(LV_PALETTE_BLUE),LV_PART_MAIN);
  lv_anim_t aa;
  lv_anim_init(&aa);
  lv_anim_set_var(&aa, obj);
  lv_anim_set_values(&aa, 0, 256);
  lv_anim_set_time(&aa, 500);
  lv_anim_set_playback_time(&aa, 500);
  lv_anim_set_repeat_count(&aa, LV_ANIM_REPEAT_INFINITE);
  lv_anim_set_path_cb(&aa, lv_anim_path_linear);
  lv_anim_set_exec_cb(&aa, anim_cb);
  lv_anim_start(&aa);
}
```

**Comment by kisvegabor** [comment]
Thank you, I'll test it tomorrow.

**Comment by kisvegabor** [comment]
I'm working on it. It seems like LVGL zooms a little bit more than it should. Therefore when the size of the zoomed area is calculated a smaller area will be invalidated. 

Investigating...

**Comment by lhdjply** [comment]
I think it's the same problem with #5237.

**Comment by kisvegabor** [comment]
I'm also suspecting it.

**Comment by lhdjply** [comment]
Is there any progress?

**Comment by kisvegabor** [comment]
Finally I found the issue and opened #5548. Please try it out.
