### ISSUE TITLE
When the chart slides to the edge, the pressed prompt number will display misalignment. See `lv_demo_widgets`

### ISSUE THREAD

**Issue by lhdjply** [kisvegabor/lvgl#5450]
### LVGL version

v9.0.0

### What happened?

https://github.com/lvgl/lvgl/assets/18370433/a02c3976-4bec-43bd-b3de-0fcb366f6b62

### How to reproduce?

code see `lv_demo_widgets`

**Comment by kisvegabor** [comment]
The video can't be played. Can you upload it again? :slightly_frowning_face:

**Comment by lhdjply** [comment]
@kisvegabor Is the video ready to turn on?

**Comment by kisvegabor** [comment]
Yes, it was just network issue sorry. I'see the bug, and will look into tomorrow.

**Comment by kisvegabor** [comment]
Or if you have time, a PR would be very welcome :)

**Comment by lhdjply** [comment]
> Or if you have time, a PR would be very welcome :)

I tried to fix it this afternoon, but I couldn't find the problem.
