### ISSUE TITLE
about  real-time refreshing

### ISSUE THREAD

**Issue by pan1024** [kisvegabor/lvgl#5452]
### Introduce the problem

How to refresh controls in real-time during events, such as in button events, refreshing a label or img multiple times before the event ends

**Comment by kisvegabor** [comment]
You can ask LVGL to refresh the invalidated areas by calling `lv_refr_now(NULL)`

**Comment by pan1024** [comment]
> You can ask LVGL to refresh the invalidated areas by calling `lv_refr_now(NULL)`

Thank you for your prompt reply. The solution you proposed is effective. If possible, you can mention this in the v9 version of the document, which is very useful and makes the program more flexible

**Comment by kisvegabor** [comment]
Sure, I've opened this PR: #5480

Please review it.
