### ISSUE TITLE
Text area accepted chars not working on big endian system

### ISSUE THREAD

**Issue by jimbom** [kisvegabor/lvgl#5454]
### LVGL version

v8.3.4

### What happened?

When adding accepted chars to a textarea, no characters are accepted on my big endian system.

The reason is the following line in lv_textarea.c:
`uint32_t c_uni = _lv_txt_encoded_next((const char *)&c, NULL);`

The char pointer will here point to 0 and c_uni will be 0. To fix it I made the change shown below to lv_textarea.c, but I am not sure if this is the best solution. I basically swapped the byte order of the uint_32_t that is added in lv_textarea_add_char. What makes it a bit tricky is that if lv_textarea_add_char is called from lv_textarea_add_text, the byte order seems to be correct, so in that case we cannot swap the byte order.

```
uint32_t c2 = c;
#if LV_BIG_ENDIAN_SYSTEM
    if(c != 0) while(*letter_buf == 0) ++letter_buf;

    // The byte order may or may not need to be swapped here, since lv_textarea_add_text is ordering bytes correctly.
    // Assume swapping is needed if highest byte is zero. May not be foolproof.
    if ((c != 0) && ((c & 0xff000000) == 0) ) {
        c2 = ((c >> 24) & 0xff) | // move byte 3 to byte 0
            ((c << 8) & 0xff0000) | // move byte 1 to byte 2
            ((c >> 8) & 0xff00) | // move byte 2 to byte 1
            ((c << 24) & 0xff000000); // byte 0 to byte 3
    }
#endif

    lv_res_t res = insert_handler(obj, letter_buf);
    if(res != LV_RES_OK) return;

    uint32_t c_uni = _lv_txt_encoded_next((const char *)&c2, NULL);
```

### How to reproduce?

```lv_obj_t * ta = lv_textarea_create(lv_screen_active());
lv_textarea_set_accepted_chars(ta, "+-.01234567890");```

**Comment by kisvegabor** [comment]
It seems really complicated and hard to test as most people doesn't have big endian machines at hand.

Anyway, if you have tested it, I'm sure it really works. Can you send a Pull request with the suggested changes?
