### ISSUE TITLE
Padding is not working in linux framebuffer v9

### ISSUE THREAD

**Issue by rmshub** [kisvegabor/lvgl#5494]
### Introduce the problem

Upgraded v8 code base to v9. Verified changes in linux SDL simulator and working as expected. However, same code is not working properly in hardware using linux framebuffer. Here looks like there is a issue with padding. Could you please help us to resolve this issue.

**Linux SDL simulator**:
![image](https://github.com/lvgl/lvgl/assets/38435057/63022f8f-a190-475d-bed4-a5fda36017e8)
**Linux FrameBuffer**:
![1706238461841](https://github.com/lvgl/lvgl/assets/38435057/2f910d19-363e-4e0f-8132-c62e0b7480e1)

**Comment by rmshub** [comment]
SDL lv_conf.h vs framebuffer lv_conf.h
![image](https://github.com/lvgl/lvgl/assets/38435057/e287a1e5-1527-4f1e-8e8d-7aeaf728216b)

**Comment by kisvegabor** [comment]
Hi,

Could you print `lv_display_get_dpi(NULL)` in both cases?

**Comment by rmshub** [comment]
Hi @kisvegabor 

**Linux Frame Buffer**: DPI -26008
```
[Info]  (95.621, +27)    lv_linux_fbdev_set_file: 1024x600, 32bpp lv_linux_fbdev.c:179
[Info]  (95.621, +0)     lv_linux_fbdev_set_file: The framebuffer device was mapped to memory successfully lv_linux_fbdev.c:194
[Info]  (95.622, +1)     lv_linux_fbdev_set_file: Resolution is set to 1024x600 at -26008dpi lv_linux_fbdev.c:238
```
**Linux SDL**: DPI 130

**Comment by rmshub** [comment]
https://github.com/lvgl/lvgl/blob/master/src/drivers/display/fb/lv_linux_fbdev.c#L234
Calculating DPI for negative values also. I think, DPI should be calculated for positive width values.

With below changes linux framebuffer working as expected
```
 if(width > 0)
 {
      lv_display_set_dpi(disp, DIV_ROUND_UP(hor_res * 254, width * 10));
 }
```

**Comment by kisvegabor** [comment]
Thank you, closing this issue.
