### ISSUE TITLE
the button style in the list while scrolling is not user-friendly.

### ISSUE THREAD

**Issue by ustbshen** [kisvegabor/lvgl#5495]
### Introduce the problem

I create a list by `lv_list_create` and then add some buttons into it to make the list scrollable. when I click inside the list(also on a list button) and try to scroll the list, the button still shows the style of pressed while list is scrolling.
after I release the click, no button click event is not triggered.
I try in Android and some other touch UI, while scrolling, no button will be displayed as pressed.

Here is the example on webpage(https://docs.lvgl.io/master/examples.html#list), I scroll the list and keep mouse down, but the button is still in pressed style.
![image](https://github.com/lvgl/lvgl/assets/35228404/0bfdacb1-a0c1-48fc-bbab-3f0710539c28)

**Comment by kisvegabor** [comment]
I was also thinking about it already. We can easily do it by adding `lv_obj_remove_state(indev->pointer.act_obj, LV_STATE_PRESSED);` [here](https://github.com/lvgl/lvgl/blob/master/src/indev/lv_indev_scroll.c#L58).

cc @XuNeo

**Comment by kisvegabor** [comment]
I've opened #5660
