### ISSUE TITLE
Draw SW ASM Neon is not working

### ISSUE THREAD

**Issue by rmshub** [kisvegabor/lvgl#5514]
### Introduce the problem

Processor: Cortex-A7
Enabled Software ASM neon, but screen is not displayed properly.
```
#define  LV_USE_DRAW_SW_ASM     LV_DRAW_SW_ASM_NEON
```
![1706461158199](https://github.com/lvgl/lvgl/assets/38435057/5abbe2bb-c9a8-4cb4-8bb6-5b2bb7dd0f34)

**Comment by kisvegabor** [comment]
cc @PeterBee97 @XuNeo 
Could you help to debug it?

**Comment by XuNeo** [comment]
Hi @PeterBee97 , 

Please help to check if it's related to recently code refactor. Thank you.

**Comment by PeterBee97** [comment]
Hotfix in  #5526 . Please review :)

**Comment by PeterBee97** [comment]
Fix in #5526 .

**Comment by kisvegabor** [comment]
Great, thank you! @rmshub please test it.
