### ISSUE TITLE
SD card display image

### ISSUE THREAD

**Issue by joeyandyou** [kisvegabor/lvgl#5519]
### LVGL version

8.3

### What happened?

When I was using lvgl, I used the lvgl file system to display images. Due to limited memory, I saw that the underlying call of lvgl was to brush image data line by line. When I used it with the screen sliding switch window, the image data would be scrambled until the window switch was successful, and the image would only appear normal. However, when I used the internal c array image, this situation did not occur. How can I solve this problem?

**Comment by kisvegabor** [comment]
cc @XuNeo 
What option do we have to read bin images from file system in v9?

**Comment by XuNeo** [comment]
In v9, we still use same method for low memory device. If the image can't be read all to RAM like the C-array image, it cannot perform transformation.

**Comment by kisvegabor** [comment]
I think it's not the transformations, but the image is read line by line  in v8 which is slow. I wonder if in v9 we have more option to manage this.

**Comment by kisvegabor** [comment]
I just want to get a confirmation about in v9 `get_area_cb` reads the images line by line too. It seems this is the case in [lv_bin_decoder_get_area](https://github.com/lvgl/lvgl/blob/master/src/libs/bin_decoder/lv_bin_decoder.c#L371).
