### ISSUE TITLE
emoji_F617

### ISSUE THREAD

**Issue by fatihozen3** [kisvegabor/lvgl#5532]
### LVGL version

v9.0.0

### What happened?

There are two emoji_F617 structs in this version. One is in examples/assets/emoji/img_emoji_F617.c and another is in test/src/test_assets/test_img_emoji_F617.c . I have got an compile time error and wanted to write it. Maybe it is not a bug and we can avoid this with a macro definition but it prevented me to compile properly.

I have excluded one from compilation and could compile in success.

**Comment by kisvegabor** [comment]
I've created #5559 to fix it.
