### ISSUE TITLE
lv_ffmpeg_player_set_src does not set image stride

### ISSUE THREAD

**Issue by josepho0918** [kisvegabor/lvgl#5539]
### LVGL version

v9.0.0

### What happened?

```
    player->imgdsc.header.w = width;
    player->imgdsc.header.h = height;
    player->imgdsc.data_size = data_size;
    player->imgdsc.header.cf = has_alpha ? LV_COLOR_FORMAT_ARGB8888 : LV_COLOR_FORMAT_NATIVE;
    player->imgdsc.data = ffmpeg_get_image_data(player->ffmpeg_ctx);
```
The variable `player->imgdsc.header.stride` is not set in the `lv_ffmpeg_player_set_src` function.

**Comment by kisvegabor** [comment]
Hi,

Could test it by setting the stride to 
`player->imgdsc.header.stride = width * lv_color_format_get_size(player->imgdsc.header.cf);`
?

**Comment by josepho0918** [comment]
Hi @kisvegabor,

It works great!🙂

**Comment by kisvegabor** [comment]
Ah great! Could you send a Pull request with the fix?

**Comment by josepho0918** [comment]
Sent.
