### ISSUE TITLE
IME PINYIN cannot work after click keyboard symbol

### ISSUE THREAD

**Issue by monkery** [kisvegabor/lvgl#5541]
### LVGL version

8.3.9

### What happened?

recurrent：
1. use ime pinyin
2. open K26, close k9
3. click keyboard symbol
4. focus on textarea
5. ime pinyin cannot work
6. repeat 3 and 3, ime pinyin can work  again.
7. repeat 3 and 4, ime pinyin can not work .

cause analysis:
in lv_ime_pinyin.c, method lv_ime_pinyin_kb_event(...);
when click keyboard symbol, the mode will switch between  k26 and k9.
when mode == k9, ime pinyin cannot work.

**Comment by kisvegabor** [comment]
@100ask could you take look at it?
