### ISSUE TITLE
v8.3 unused DMA STM32 functions

### ISSUE THREAD

**Issue by faxe1008** [kisvegabor/lvgl#5542]
### Introduce the problem

There is a pending PR on our lvgl module which tries to improve the STM32 performance of LVGL. [https://github.com/zephyrproject-rtos/zephyr/pull/68254](https://github.com/zephyrproject-rtos/zephyr/pull/68254)
Everything works but CI is failing because there are 4 unused functions. 

```
_lv_gpu_stm32_dma2d_invalidate_cache
_lv_draw_stm32_dma2d_copy_buffer
lv_gpu_stm32_dma2d_wait_cb
lv_draw_stm32_dma2d_img
```

### Proposal

Either removal of the functions or introduction of an `LV_ATTRIBUTE_MAYBE_UNUSED`. 
I'd be happy to submit a PR for this.

**Comment by CharlesDias** [comment]
Dear, this is the comparison result.

https://github.com/lvgl/lvgl/assets/27859307/a08147a6-ef36-45ca-8bf2-5beab04dfa46

**Comment by kisvegabor** [comment]
Hi,

@faxe1008 I've just opened #5561

@CharlesDias Very impressive. I hope we will have ChromeArt and NeoChrome in LVGL v9 too soon.

**Comment by kisvegabor** [comment]
The PR is merged, I close this issue.
