### ISSUE TITLE
LV_USE_OBJ_ID / LV_USE_OBJ_ID_BUILTIN problem

### ISSUE THREAD

**Issue by PercentageCorporation** [kisvegabor/lvgl#5544]
### LVGL version

v9.0.0

### What happened?

I set the following in lv_conf.h which causes build problems in lv_obj.c and lv_obj_tree.c

/* Add `id` field to `lv_obj_t` */
#define LV_USE_OBJ_ID           1
/* Use lvgl builtin method for obj ID */
#define LV_USE_OBJ_ID_BUILTIN   0

The #if LV_USE_OBJ_ID statements in these files should be #if LV_USE_OBJ_ID_BUILTIN, otherwise undefined references occur in the build.

**Comment by kisvegabor** [comment]
Hi,

Thank you for the report. 

Could you send a PR?

**Comment by XuNeo** [comment]
Disable `LV_USE_OBJ_ID_BUILTIN ` means using custom ID generator. 
Below APIs needed to be implemented and linked to lvgl.
```c
    void lv_obj_assign_id(const lv_obj_class_t * class_p, lv_obj_t * obj);
    void lv_obj_free_id(lv_obj_t * obj);
    const char * lv_obj_stringify_id(lv_obj_t * obj, char * buf, uint32_t len);

```
See https://docs.lvgl.io/master/others/obj_id.html#use-custom-id-generator
