### ISSUE TITLE
fix variable name in v9.0.0

### ISSUE THREAD

**Issue by huenrong** [kisvegabor/lvgl#5581]
### LVGL version

v9.0.0

### What happened?

There are the same variable names in file `lvgl/examples/assets/emoji/img_emoji_F617.c` and file `lvgl/tests/src/test_assets/test_img_emoji_F617.c`

- file `lvgl/examples/assets/emoji/img_emoji_F617.c`
```c
const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMAGE_1F617 uint8_t emoji_F617_map[] = {
...
const lv_image_dsc_t emoji_F617 = {
    .header.cf = LV_COLOR_FORMAT_NATIVE,
    .header.w = 72,
    .header.h = 72,
    .data_size = 5184 * LV_COLOR_DEPTH / 8,
    .data = emoji_F617_map,
};
```
- file `lvgl/tests/src/test_assets/test_img_emoji_F617.c`
```c
const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMAGE_1F617 uint8_t emoji_F617_map[] = {
...
const lv_image_dsc_t emoji_F617 = {
    .header.cf = LV_COLOR_FORMAT_NATIVE,
    .header.w = 72,
    .header.h = 72,
    .data_size = 5184 * LV_COLOR_DEPTH / 8,
    .data = emoji_F617_map,
};
```

but In file `lvgl/tests/src/test_assets/test_img_emoji_F617.c` there should be prefix `test_`, such as `test_emoji_F617_map`, `test_emoji_F617`

**Comment by C47D** [comment]
Hi, 

Is #5559 fix included in your project?

**Comment by huenrong** [comment]
> Hi,
> 
> Is #5559 fix included in your project?

@C47D 
thanks, i just used master branch, it`s ok.
But I think should modify this variable name, because if I enable `LV_BUILD_EXAMPLES`, an error will also be reported.

**Comment by kisvegabor** [comment]
Sorry, my bad. There was a typo in #5559

It should with #5594

**Comment by huenrong** [comment]
> Sorry, my bad. There was a typo in #5559
> 
> It should with #5594

@kisvegabor 
thanks, If this is the case, then the contents of the files in this directory are somewhat inconsistent.
some files use `LV_BUILD_EXAMPLES` macro(eg: `tests/src/test_assets/test_animimg001.c`)
some files use `test_xx` name(eg: `src/test_assets/test_img_cogwheel_rgb565.c`)
some files use `LV_BUILD_TEST` macro(eg: `tests/src/test_assets/test_img_emoji_F617.c`)

It seems that the rules are not uniform, maybe I didn’t understand it correctly in some places.

**Comment by kisvegabor** [comment]
Oh, really there is a bigger mess here than I thought :sweat_smile:

I unified the guard in #5616. I'll update the filenames too.
