### ISSUE TITLE
Grid navigation seems to be broken

### ISSUE THREAD

**Issue by BeatSkip** [kisvegabor/lvgl#5600]
### LVGL version

9.0.1-dev

### What happened?

i cannot seem to get grid navigation working.
groups are set up properly.

i have hardware buttons that are set up to emulate keyboard arrow buttons via EVDEV. everything was working fine in lvgl 8.3. if i change the key mapping in lv_evdev.c from LV_KEY_UP to LV_KEY_NEXT, i get 'some' semblence of navigation. but obviously no nice grid navigation. but this does prove groups and indev etc etc are set up properly.

is the gridnav feature in lvgl 9 actually tested and validated?

EDIT:

just compiled and tested the keypad encoder navigation demo.
and keypad navigation is nigh impossible and basically broken.

### How to reproduce?

lv_port_pc_eclipse with lv_demo_keypad_encoder();

try to navicate with the arrow keys and the problem will present itself instantly

**Comment by kisvegabor** [comment]
The SDL driver for`lv_port_pc_eclipse` was updated recently. With the latest LVGL master version both the gridnav and the lv_demo_keypad_encoder are working well on my end.

It was the related update: #5575
