### ISSUE TITLE
Bug of label with DOT mode

### ISSUE THREAD

**Issue by seadog-www** [kisvegabor/lvgl#5606]
### LVGL version

V8.2

### What happened?

When the content of label is conbined with chinese char and number, there will be a problem, only showing “…”. As the following picture shown

![image](https://github.com/lvgl/lvgl/assets/83915874/b5fa519a-899e-48b0-b9e5-523588051c50)

### How to reproduce?

#!/opt/bin/lv_micropython -i

import lvgl as lv
import display_driver
import fs_driver

fs_drv = lv.fs_drv_t()
fs_driver.fs_register(fs_drv, 'S')
font_simsun_16_cjk = lv.font_load("S:../../assets/font/lv_font_simsun_16_cjk.fnt")

label1 = lv.label(lv.scr_act())
label = label1
label.set_style_text_font(font_simsun_16_cjk, 0)
label.set_long_mode(lv.label.LONG.DOT)     
label.set_text("机123456")
label.set_size(70, 20)                
label.align(lv.ALIGN.TOP_MID, 0, 20)
label.set_style_bg_color(lv.color_hex(0xFF00FF), 0)
label.set_style_bg_opa(100, 0)

label2 = lv.label(lv.scr_act())
label = label2
label.set_style_text_font(font_simsun_16_cjk, 0)
label.set_long_mode(lv.label.LONG.DOT)     
label.set_text("机1234567")
label.set_size(70, 20)                
label.align(lv.ALIGN.TOP_MID, 0, 60)
label.set_style_bg_color(lv.color_hex(0x00FFFF), 0)
label.set_style_bg_opa(100, 0)

**Comment by kisvegabor** [comment]
It's known issue which is not resolved yet even in v9. :slightly_frowning_face:

**Comment by seadog-www** [comment]
> It's known issue which is not resolved yet even in v9. 🙁

Alright, it seems like I'll have to find a temporary solution on my own for now.

**Comment by kisvegabor** [comment]
I've just found a forgotten ancient feature which solves this issue. Just set `LV_TXT_LINE_BREAK_LONG_LEN 1`

Context: You see the issue  because LVGL assumes that long texts can be wrapped    on any Chinese character. And in your case the text is wrapped automatically like
```
机
123456
``` 

But the second line is clipped, so what remains is some dots in the first line.

`LV_TXT_LINE_BREAK_LONG_LEN 1` tells LVGL that it can wrap even after 1 character, so the text will become:
```
机123
456
```

**Comment by seadog-www** [comment]
> I've just found a forgotten ancient feature which solves this issue. Just set `LV_TXT_LINE_BREAK_LONG_LEN 1`
> 
> Context: You see the issue because LVGL assumes that long texts can be wrapped on any Chinese character. And in your case the text is wrapped automatically like
> 
> ```
> 机
> 123456
> ```
> 
> But the second line is clipped, so what remains is some dots in the first line.
> 
> `LV_TXT_LINE_BREAK_LONG_LEN 1` tells LVGL that it can wrap even after 1 character, so the text will become:
> 
> ```
> 机123
> 456
> ```

Yes, it does work.
However, after setting LV_TXT_LINE_BREAK_LONG_LEN 1, a complete word may be broken in middle in LV_LABEL_LONG_WRAP mode, which may be unacceptable for someone.
Perhaps these two modes(LV_LABEL_LONG_WRAP and LV_LABEL_LONG_DOT) should not share the same parameter(LV_TXT_LINE_BREAK_LONG_LEN )

**Comment by kisvegabor** [comment]
I think the real solution would be to not wrap the text in the last line in case of `LV_LABEL_LONG_DOT`.

As a workaround you can just comment out this [line](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_text.h#L182).

**Comment by niklasf** [comment]
Tried to implement this in #6362.
