### ISSUE TITLE
Several Readme in the demo are completely inconsistent with the content

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5609]
### Introduce the problem

https://github.com/lvgl/lvgl/blob/master/demos/benchmark/README.md
https://github.com/lvgl/lvgl/blob/master/demos/multilang/README.md
https://github.com/lvgl/lvgl/blob/master/demos/render/README.md
https://github.com/lvgl/lvgl/blob/master/demos/transform/README.md

**Comment by IAMMX** [comment]
I think we can delete the irrelevant README file first, and then slowly fill it up.

**Comment by kisvegabor** [comment]
Let's continue in #5626
