### ISSUE TITLE
RunThread stack size with FreeRTOS

### ISSUE THREAD

**Issue by Felix-devel** [kisvegabor/lvgl#5642]
### LVGL version

V9.0.0

### What happened?

The stack used in the file lv_draw_sw.c in the function lv_draw_sw_init is 8*1024. FreeROTS uses this value and multiplies it with the word size (which could be more than one byte). In my case it would use 32kbyte. Is this correct or should it be only 8kbytes.

**Comment by Felix-devel** [comment]
Ok, but than [here ](https://github.com/lvgl/lvgl/blob/e6dc2f05d239b914617f19e1db019ebb35d83449/src/osal/lv_freertos.c#L76) it should be divided by sizeof(StackType_t) or sizeof(portSTACK_TYPE).

**Comment by kisvegabor** [comment]
You are right! Could you send a PR?

**Comment by Felix-devel** [comment]
It was my first PR. I hope I did it correct

**Comment by kisvegabor** [comment]
You did, thank you! :heart:
