### ISSUE TITLE
lv_obj_align_to method BUG

### ISSUE THREAD

**Issue by mhtrbg** [kisvegabor/lvgl#5649]
### LVGL version

V9.0.0

### What happened?

Dear LVGL Development Team,

I am encountering a critical issue with the LVGL library version 9.0. Whenever I use the lv_obj_align_to method, my display crashes immediately. This issue occurs consistently only when this specific method is invoked. If I avoid using lv_obj_align_to(), everything else functions normally, including the execution of official demo applications.

### How to reproduce?

    lv_obj_t *obj1 = lv_obj_create(lv_scr_act());
    lv_obj_center(obj1);
    lv_obj_set_size(obj1, 50, 50);
    lv_obj_t *obj2 = lv_obj_create(lv_scr_act());
    lv_obj_set_size(obj2, 50, 50);
    lv_obj_align_to(obj1, obj2, LV_ALIGN_OUT_TOP_MID, 0, 0);

**Comment by FASTSHIFT** [comment]
This code works well in the Simulator, have you tried replicating the problem in the [simulator](https://github.com/lvgl/lv_port_pc_eclipse)?
![5AP$51GO4ESWRTC`}SE5}QB](https://github.com/lvgl/lvgl/assets/26767803/2714f863-d139-4d1e-9c18-beb4fef457ea)

**Comment by kisvegabor** [comment]
That code looks good to me too. 

> This issue occurs consistently only when this specific method is invoked.

That's great! What platform do you use? Do you have access to a debugger? If not please [enable LVGL's logging](https://docs.lvgl.io/master/porting/log.html) as described here with `TRACE` level.
