### ISSUE TITLE
Issue with Benchmark Execution in Version 9.0.0 - LV_MEM_SIZE Adjustment Required

### ISSUE THREAD

**Issue by dani007200964** [kisvegabor/lvgl#5654]
### LVGL version

v9.0.0

### Description
In version 9.0.0, I encountered a problem where the benchmark fails to execute. After some investigation, I discovered that increasing the LV_MEM_SIZE to 128k bytes is necessary to prevent a hard fault from occurring.

### Environment:
* Microcontroller: STM32F7
* Display: ST7789, 240x240px, 16-bit RGB565 mode
* Double buffering enabled.

### Details:
The hard fault occurs specifically within the `containers_with_scrolling_cb` function during the execution of the for loop. Increasing the `LV_MEM_SIZE` to `128k` bytes resolves the hard fault issue. However, it's worth noting that this may be more memory than necessary, and it would be beneficial to identify an optimal value for the LV_MEM_SIZE to run the benchmark successfully.

### Recommendation:
1. Explore and find the optimal `LV_MEM_SIZE` value to ensure efficient memory utilization without compromising functionality.
2. Adjust `LV_MEM_SIZE` to the minimum value required for successful benchmark execution.

Best regards,
Daniel

### How to reproduce?

```c
// This is the init section of my code
lv_init();
lv_display_t* display = lv_display_create( ST7789_WIDTH, ST7789_HEIGHT );
lv_display_set_flush_cb( display, display_flush );
lv_display_set_buffers( display, display_buffer_0, display_buffer_1, sizeof( display_buffer_0 ), LV_DISPLAY_RENDER_MODE_PARTIAL );

// This is how I would like to run the benchmark
lv_demo_benchmark();
```
Problematic part:
```c
// lv_demo_benchmark.c file
static void containers_with_scrolling_cb(void)
{
    lv_obj_t * scr = lv_screen_active();

    lv_obj_set_flex_flow(scr, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(scr, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    uint32_t i;
    for(i = 0; i < 50; i++) {
        card_create(); // <- This line will throw a fardfault during the iterations with the 64k LV_MEM_SIZE setting.
    }

    lv_obj_update_layout(scr);
    scroll_anim(scr, lv_obj_get_scroll_bottom(scr));
}
```

**Comment by kisvegabor** [comment]
True, we can a `#warning` in the benchmark to be sure a suitable memory is available. I've opened #5661 to help in finding the max memory usage.
