### ISSUE TITLE
LV_DRAW_SW_ASM_HELIUM is very slow

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#5658]
### LVGL version

v9.0.1-dev

### What happened?

On Renesas EK-RA8D1 setting `LV_USE_DRAW_SW_ASM`   to  `LV_DRAW_SW_ASM_HELIUM` is twice as slow as pure SW rendering.

See the results [here](https://docs.google.com/spreadsheets/d/1u46wGS6c8PMpOjBs46h04Wj0c1TmZmg72NKluhhknuQ/edit?usp=sharing). Note the pages at the bottom for CPU usage and render time charts. 

### How to reproduce?

I was using the GCC toolchain with [this project](https://github.com/lvgl/lv_renesas), enabled  `LV_DRAW_SW_ASM_HELIUM` and disabled `LV_USE_DRAW_DAVE2D`. 

@GorgonMeducer As this code is pure ASM, can it depend on the compiler/toolchain and it's settings?

cc @PeterBee97, @jeremy-baker

**Comment by PeterBee97** [comment]
Are these results tested on 16bpp? If so, could you test again on 24bpp or 32bpp? The current implementation is not clever for 16bpp and slower than SW may be expected.

**Comment by GorgonMeducer** [comment]
@kisvegabor For Pure-ASM, gcc compiler can do almost nothing to affect the performance.

**Comment by GorgonMeducer** [comment]
A rough review shows that there are plenty of structural hazards and RAW hazards in the Helium assembly that stall the pipeline. It is suggested to improve those code on real silicon rather than on simulators.

**Comment by PeterBee97** [comment]
Did some improvement, would you please test again with this new PR #5702 ? @kisvegabor

**Comment by kisvegabor** [comment]
Thank you Peter! Let's continue in the PR.
