### ISSUE TITLE
Setting LV_DRAW_SW_COMPLEX 0 won't compile

### ISSUE THREAD

**Issue by razor5k** [kisvegabor/lvgl#5663]
### LVGL version

v9.0.0

### What happened?

If I try to compile with LV_DRAW_SW_COMPLEX 0, build errors in lv_draw_sw_box_shadow.c will occur

[ 24%] Building C object lvgl/CMakeFiles/lvgl.dir/src/draw/sw/lv_draw_sw_box_shadow.c.o
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c: In function ‘lv_draw_sw_box_shadow’:
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c:120:5: warning: implicit declaration of function ‘shadow_draw_corner_buf’ [-Wimplicit-function-declaration]
  120 |     shadow_draw_corner_buf(&core_area, (uint16_t *)sh_buf, dsc->width, r_sh);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c:128:5: error: unknown type name ‘lv_draw_sw_mask_radius_param_t’; did you mean ‘lv_draw_sw_mask_res_t’?
  128 |     lv_draw_sw_mask_radius_param_t mask_rout_param;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     lv_draw_sw_mask_res_t
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c:131:9: warning: implicit declaration of function ‘lv_draw_sw_mask_radius_init’; did you mean ‘lv_draw_sw_mask_rect’? [-Wimplicit-function-declaration]
  131 |         lv_draw_sw_mask_radius_init(&mask_rout_param, &bg_area, r_bg, true);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         lv_draw_sw_mask_rect
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c:185:42: warning: implicit declaration of function ‘lv_draw_sw_mask_apply’; did you mean ‘lv_draw_sw_mask_rect’? [-Wimplicit-function-declaration]
  185 |                     blend_dsc.mask_res = lv_draw_sw_mask_apply(masks, mask_buf, clip_area_sub.x1, y, w);
      |                                          ^~~~~~~~~~~~~~~~~~~~~
      |                                          lv_draw_sw_mask_rect
/home/dha/Software/lvgl/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c:550:9: warning: implicit declaration of function ‘lv_draw_sw_mask_free_param’; did you mean ‘lv_draw_sw_mask_rect’? [-Wimplicit-function-declaration]
  550 |         lv_draw_sw_mask_free_param(&mask_rout_param);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         lv_draw_sw_mask_rect
make[2]: *** [lvgl/CMakeFiles/lvgl.dir/build.make:1026: lvgl/CMakeFiles/lvgl.dir/src/draw/sw/lv_draw_sw_box_shadow.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: lvgl/CMakeFiles/lvgl.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### How to reproduce?

lv_conf.h
...
#define LV_DRAW_SW_COMPLEX 0
...

**Comment by kisvegabor** [comment]
Thank you for the report. It should be fixed by #5695.
