### ISSUE TITLE
When main.py is executed, the test image cannot be generated after the folder is deleted.

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5664]
### Introduce the problem

When running `main.py` in tests, if the output folder is deleted, the test picture will not be generated.
 For example, delete the `tests/ref_imgs/widgets` folder, and then execute `python main.py test`. All tests pass, but the image cannot be generated. 
So can you determine whether the folder exists before generating the image, and if it does not exist, create the folder first.

**Comment by kisvegabor** [comment]
I see no problem with automatically generating the missing folders. 

Added in #5696
