### ISSUE TITLE
LVGL9 lv_obj_remove_flag() issue

### ISSUE THREAD

**Issue by KenVanHoeylandt** [kisvegabor/lvgl#5678]
### LVGL version

v9.0.0

### What happened?

I'm upgrading LVGL from `v8.3` to `v9.0`.

There seems to be a behaviour change when calling `lv_obj_remove_flag()` (formerly `lv_obj_clear_flag()`).
Let's take a look at this code:

```c
lv_obj_set_style_img_recolor(image, lv_color_white(), 0);
lv_obj_set_style_img_recolor_opa(image, 255, 0);
lv_img_set_src(image, icon->image);
lv_obj_remove_flag(image, LV_OBJ_FLAG_HIDDEN); // <-- problematic
```
The main intention of that problematic line of code is that I want to show/hide widgets.
The code above is called from a custom widget's event callback for `LV_EVENT_DRAW_MAIN`.

Before v9, this was not a problem, but now with v9 it triggers an assert with the following callstack:
- ` LV_ASSERT_MSG(!disp->rendering_in_progress, "Invalidate area is not allowed during rendering.");`
- `_lv_inv_area`
- `lv_obj_invalidate_area`
- `lv_obj_invalidate`

There seems to be no documentation on this change:
https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.rst

**Comment by XuNeo** [comment]
The assertion means you are modify widget properties during rendering. It will generate new dirty areas thus it's forbidden.

Could you check where are you calling those functions? Are you calling it in DRAW_EVENT?
> 
```c
lv_obj_set_style_img_recolor(image, lv_color_white(), 0);
lv_obj_set_style_img_recolor_opa(image, 255, 0);
lv_img_set_src(image, icon->image);
lv_obj_remove_flag(image, LV_OBJ_FLAG_HIDDEN); // <-- problematic
```

**Comment by KenVanHoeylandt** [comment]
Yep, as I mentioned:
> The code above is called from a custom widget's event callback for LV_EVENT_DRAW_MAIN.

I understand why it's a problem and I have a solution, but I kinda expected it to be in the changelog / migration guide.

**Comment by kisvegabor** [comment]
It was not by design that it was working in v8, only pure luck :slightly_smiling_face: 
So I don't think it needs be highlighted in the changelog as it was never a recommended to add any modification during drawing.

**Comment by C47D** [comment]
@kisvegabor maybe we can add that explicitly 

> Updating widgets during rendering is not supported.

**Comment by KenVanHoeylandt** [comment]
> It was not by design that it was working in v8, only pure luck 🙂 So I don't think it needs be highlighted in the changelog as it was never a recommended to add any modification during drawing.

Thanks!

**Comment by kisvegabor** [comment]
> Updating widgets properties during rendering is not supported.

Where can be a good place for that?

**Comment by kisvegabor** [comment]
@vwheeler63 Adding a line of warning there would be helpful for sure.

**Comment by vwheeler63** [comment]
> [@vwheeler63](https://github.com/vwheeler63) Adding a line of warning there would be helpful for sure.

Done in PR #7685.  Doc modification shown in the [Base Widget > Events > Drawing Events section](http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/details/base-widget/event.html#drawing-events).
