### ISSUE TITLE
Remove lead/trailing spaces with centered, wrapped text when calculating centering.

### ISSUE THREAD

**Issue by jonsmirl** [kisvegabor/lvgl#5679]
### LVGL version

V8

### What happened?

Button label with long text and lv_label_set_long_mode() set to make it wrap. Also have lv_obj_set_style_text_align() to center the text. LVGL works properly to line break the text on spaces. But then when it centers the text, is it not trimming lead or trailing spaces before doing the centering calculation.

To fix -- need to remove lead/trailing spaces from the centering calculation on wrapped text.

**Comment by kisvegabor** [comment]
It's really a problem. Can you work on a fix and send a Pull request?
