### ISSUE TITLE
'docs/build.py' on Windows

### ISSUE THREAD

**Issue by gvanem** [kisvegabor/lvgl#5693]
### LVGL version

"git -C ../git-latest describe --tags" -> "v9.0.0-155-g907a17c97"

### What happened?

Trying to understand the internals of LVGL, I tried to build a local manual (`LVGL.pdf` etc.) using the
included `docs/build.py` script. But it's terribly broken on Windows:

First, it assumes a bash shell in the use of e.g. `cmd('cd "{0}" && doxygen Doxyfile'.format(temp_directory))`.
If `temp_directory` is on another drive than `project_path`, this command fails.
So I tried to fix this by a new function instead:
```py
def chdir_and_run(_dir, _cmd):
    if sys.platform == "win32":
        cmd('pushd "%s" & %s & popd' % (_dir, _cmd))
    else:
        cmd('cd "%s" && %s' % (_dir, _cmd))
```

Second, there are issues with the generated (?) `.doctrees` under the `temp_directory` that I faiil to understand.
  E.g. in a `sphinx-build -b html .. ` step, I get this error:
```py
Exception occurred:
  File "F:\gv\Python310\lib\site-packages\breathe\project.py", line 117, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
AttributeError: 'WindowsPath' object has no attribute 'rstrip'
The full traceback has been saved in c:\temp\sphinx-err-dqk8c7lv.log, if you want to report the issue to the developers.
```

`c:\temp\sphinx-err-dqk8c7lv.log` is [here](https://github.com/lvgl/lvgl/files/14331840/sphinx-err-dqk8c7lv.log).
Anyone on Windows that understand more about sphinx-build that I do, that can help here?

### How to reproduce?

`cd docs & py -3 build.py skip_latex` and see the errors on Windows.

**Comment by gvanem** [comment]
*Update*.   I did a `pip install -U sphinx-build` going from version 7.2.2 to version 7.26.
This seems to have fixed the above `Exception` issue, but caused another exception. The last-log: [sphinx-err-38g0xkpn.log](https://github.com/lvgl/lvgl/files/14354995/sphinx-err-38g0xkpn.log).

And the issue with `project_path` and `temp_directory` on different drives remains.

**Comment by kisvegabor** [comment]
Hi,

I can confirm that the script is not designed to run on Windows. It has 2 main reasons:
- Typically the users shouldn't build the docs for themselves and we use Linux in the CI
- On Windows WSL can be sued to emulate Linux. Is it an option for you?

**Comment by gvanem** [comment]
> Typically the users shouldn't build the docs for themselves

Why is that?

> On Windows WSL can be sued to emulate Linux. Is it an option for you?

No way. Too messy. I'm closing this issue since I've hacked up a better .py-script + GNU-makefile for this.

**Comment by kisvegabor** [comment]
>> Typically the users shouldn't build the docs for themselves

> Why is that?

Because it's available online.


> I've hacked up a better .py-script + GNU-makefile for this.

Could you elaborate on that? We are always looking for improvement opportunities.
