### ISSUE TITLE
"undefined reference" to custom default font if not explicitly used

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#5705]
### LVGL version

v9.0.0

### What happened?

I have lvgl as a components in my ESP-IDF porject. 
I have a `my_font.c` file and I define it as default font in `lv_conf.h` :

```c
...
/*Optionally declare custom fonts here.
 *You can use these fonts as default font too and they will be available globally.
 *E.g. #define LV_FONT_CUSTOM_DECLARE   LV_FONT_DECLARE(my_font_1) LV_FONT_DECLARE(my_font_2)*/
#define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(my_font)

/*Always set a default font*/
#define LV_FONT_DEFAULT &my_font
...
```

But it seems I need to explicitly "mention" the variable `my_font` in the program, otherwise the compiler says "undefined reference to 'my_font' :

```c
#include "lvgl.h"
void app_main(void) {
    LV_LOG_INFO("%p",  &my_font); // won't compile without this line.
    lv_init();
    ...
} 
```

Can this be fixed with lvgl? or is it related to ESP-IDF?

**Comment by kisvegabor** [comment]
Hi,

Please copy the whole compiler log.

**Comment by yesnoj** [comment]
ciao Gabor, i've the same issue, this is the output of the compiler for my fonts :

`/Users/francescoprochilo/Library/Arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: sketch/objs.a(TheBeginning.ino.cpp.o):(.literal.processes+0x28): undefined reference to `FilMachineFontIcons_30'
/Users/francescoprochilo/Library/Arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: sketch/objs.a(TheBeginning.ino.cpp.o):(.literal.menu+0x14): undefined reference to `FilMachineFontIcons_20'
collect2: error: ld returned 1 exit status`

I'm trying to define all the custom font in the lv_config.h , but i've the issue of the user that opened this topic...
Do you have any suggestions?!

**Comment by kisvegabor** [comment]
Hm, to be honest I have no idea what could be problem.

Please try if simply adding `LV_FONT_DECLARE(FilMachineFontIcons_30);` to your ino file works.

**Comment by yesnoj** [comment]
i really don't know how solve.
If i need more than one font, basically the same with different size, i don't know how to do it :/

**Comment by kisvegabor** [comment]
C files never should be included. The fonts can be defined with `LV_FONT_DECLARE(my_font)`

Does it help if you use `LV_FONT_CUSTOM_DECLARE` and in the ino file at the end of setup, you add this for all fonts?
```
LV_UNUSED(&my_font1);
LV_UNUSED(&my_font2);
LV_UNUSED(&my_font3);
```

**Comment by yesnoj** [comment]
> ```c
> #define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(my_font)
> ```

i've added this on lv_conf.h
```

#define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(FilMachineFontIcons_10) LV_FONT_DECLARE(FilMachineFontIcons_15) LV_FONT_DECLARE(FilMachineFontIcons_20) LV_FONT_DECLARE(FilMachineFontIcons_30) LV_FONT_DECLARE(FilMachineFontIcons_40) 

```

and this at the end of the setup method into the only .ino file i've in the project 


```

void setup()
{
    Serial.begin(115200);

    String LVGL_Arduino = "Hello Arduino! ";
    LVGL_Arduino += String('V') + lv_version_major() + "." + lv_version_minor() + "." + lv_version_patch();
    Serial.println(LVGL_Arduino);

    lcd.init();
    lcd.setRotation(1);

    lv_init();

    lvDisplay = lv_display_create(TFT_HOR_RES, TFT_VER_RES);
    lv_display_set_color_format(lvDisplay, LV_COLOR_FORMAT_RGB565);
    lv_display_set_flush_cb(lvDisplay, my_disp_flush);    
    lv_display_set_buffers(lvDisplay, lvBuffer1, lvBuffer2, lvBufferSize, LV_DISPLAY_RENDER_MODE_PARTIAL);

    lvInput = lv_indev_create();
    lv_indev_set_type(lvInput, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(lvInput, my_touchpad_read);

    actualMillis = millis();

    homePage();
    
    LV_UNUSED(&FilMachineFontIcons_10);
    LV_UNUSED(&FilMachineFontIcons_15);
    LV_UNUSED(&FilMachineFontIcons_20);
    LV_UNUSED(&FilMachineFontIcons_30);
    LV_UNUSED(&FilMachineFontIcons_40);
}

```

I've removed all the includes, but still get the error :

```

Library/Arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: sketch/objs.a(TheBeginning.ino.cpp.o):(.literal.processes+0x24): undefined reference to `FilMachineFontIcons_30'

```

In the file page_process.h that i use is used the font FilMachineFontIcons_30 for the icons. I use the custom font just for the icons...i need more customs to have different icon sizes from FontAwesome :/

**Comment by yesnoj** [comment]
@kisvegabor i was placing the font.c files in an inner folder, called "resources"...moving the font.c files near the .ino works perfectly!
Can i place the font.c files in a different location from the main folder?
Sorry, of course was my mistake :/

**Comment by kisvegabor** [comment]
Aaaah, Arduino really has some limitation in this regard. [This comment](https://forum.arduino.cc/t/subfolders-in-sketch-folder/564852/3) say that, you can have an `src` folder, in which you can add as many folders as you wich.

**Comment by yesnoj** [comment]
Thanks Gabor, i will try!
