### ISSUE TITLE
8.3.10/11 not in platformio registry 

### ISSUE THREAD

**Issue by thijstriemstra** [kisvegabor/lvgl#5712]
### LVGL version

8.3.11

### What happened?

The latest version of lvgl 8.x on platformio registry is 8.3.9: https://registry.platformio.org/libraries/lvgl/lvgl/versions

can (8.3.10 and) 8.3.11 be added as well?

**Comment by kisvegabor** [comment]
Thanks you for reporting it. I published both. 

They should show up in a few minites.

**Comment by thijstriemstra** [comment]
thanks!
