### ISSUE TITLE
SDL Keyboard lv_indev_get_key returns 0

### ISSUE THREAD

**Issue by Ka1mes** [kisvegabor/lvgl#5717]
### LVGL version

v9.0.1-dev

### What happened?

I am trying to read keyboard inputs on Windows using SDL2. The sdl_keyboard_read callback function of the SDL keyboard seems to be returning the correct keys. I am also able to use the SDL mouse without any problems.
In the code snippet below I am expecting the program to print the last key pressed on the keyboard but it will only print 0.

### How to reproduce?

#include "lvgl.h"
#include <stdio.h>

lv_indev_t * keyboard;

int main(int argc, char *argv[])
{
        lv_init();       
        lv_sdl_window_create(1024,650);      
        lv_obj_t * main = lv_obj_create(lv_screen_active());

        keyboard = lv_sdl_keyboard_create();
        

        while (1)   
        {
                lv_task_handler();
                printf("last key: %d\n",lv_indev_get_key(keyboard));
        }
        
        lv_deinit();
        return 0;
}

**Comment by kisvegabor** [comment]
I've just checked it out, and when processing the keypad it return very early when there is no focused widgets to forward the keys to. See [here](https://github.com/lvgl/lvgl/blob/master/src/indev/lv_indev.c#L691-L695).

However I see no issue with moving [these lines](https://github.com/lvgl/lvgl/blob/master/src/indev/lv_indev.c#L699-L704) before the early returns. 

Could you test if with these modification it works well on your end too?

**Comment by Ka1mes** [comment]
Works like a charm on my end as well. Thank you for the quick fix

**Comment by kisvegabor** [comment]
I've opened https://github.com/lvgl/lvgl/pull/5795 to fix it.
