### ISSUE TITLE
If LV_DRAW_SW_COMPLEX is set to 0 lv_demo_widgets looks odd

### ISSUE THREAD

**Issue by razor5k** [kisvegabor/lvgl#5727]
### LVGL version

v9.0.0-176-gf5c59f3f8

### What happened?

Texts are blended together and not replaced if a value of a combobox is changed

### How to reproduce?

LV_DRAW_SW_COMPLEX is set to 0
Build lvgl with lv_demo_widgets and SDL
Start the demo and change the gender from Male to Female
The Male text is not replaced by Female but it is blended together

**Comment by kisvegabor** [comment]
Hi, 

You that's it's incorrect because `LV_DRAW_SW_COMPLEX 0` can't render rounded rectangles.

**Comment by C47D** [comment]
@kisvegabor , I think we can close this issue
