### ISSUE TITLE
MYCLASS definition is missing in lv_x11_input.c

### ISSUE THREAD

**Issue by canfoderiskii** [kisvegabor/lvgl#5737]
### LVGL version

v9.0.0

commit: 81215d06fd56c1be118e5ff275c1009aabae7476

### What happened?

failed to compile when `LV_USE_X11=1`

![image](https://github.com/lvgl/lvgl/assets/10685920/c62504f5-ccfc-45cf-80fa-59855048c00b)

**Comment by canfoderiskii** [comment]
After I delete all `LV_ASSERT_OBJ(indev, MY_CLASS);` lines, the compilation is good again, and the simulator runs fine.

**Comment by kisvegabor** [comment]
Thanks for the report, I  fixed it here: https://github.com/lvgl/lvgl/pull/5742
