### ISSUE TITLE
flex layout feature

### ISSUE THREAD

**Issue by git208388** [kisvegabor/lvgl#5748]
### Problem to solve

Does the flex layout of lvgl not support automatically stretching child widgets? For example, if I create a flex layout object with a width and height of 240, 280, and then create a child widget obj_child, can the width and height of this obj_child automatically stretch to the width and height of the parent object, instead of the default width and height of 130, 130?

### Success criteria

no

### Solution outline

no

### Rabbit holes

no

### Testing

no

### Teaching

no

**Comment by kisvegabor** [comment]
You don't need a flex layout for this. Just set the width and height to `lv_pct(100)`.
