### ISSUE TITLE
label will be created with a black border.

### ISSUE THREAD

**Issue by HongYan12345** [kisvegabor/lvgl#5751]
### LVGL version

8.3

### What happened?

When the background is fully transparent, the label will be created with a black border.
I set the lv_scr_act() to be fully transparent, I can already see the image below through lvgl, but creating a label on top of it will have a black border, I've set the border and shadow to 0 and fully transparent.
![7b036490-2635-46a5-893d-7ebe31eca1be](https://github.com/lvgl/lvgl/assets/106100576/e8e11d3e-be95-42cc-bc22-4137a792cbb8)

### How to reproduce?

    static lv_style_t transparent_style;
    lv_style_init(&transparent_style);
    lv_style_set_bg_opa(&transparent_style, LV_OPA_0);
    lv_style_set_shadow_opa(&transparent_style, LV_OPA_0);
    lv_style_set_border_opa(&transparent_style, LV_OPA_0);
    lv_obj_add_style(lv_scr_act(), &transparent_style, LV_PART_MAIN);

    lv_obj_t *obj = lv_label_create(parent);
    lv_obj_add_style(obj, &label_style_bold_12, LV_PART_MAIN);
    lv_obj_align(obj, LV_ALIGN_BOTTOM_RIGHT, -10, -10);

**Comment by HongYan12345** [comment]
> Have you enabled `LV_COLOR_SCREEN_TRANSP`?
of course
#define LV_COLOR_DEPTH 32
#define LV_COLOR_SCREEN_TRANSP 1

**Comment by HongYan12345** [comment]
Missing disp_drv.screen_transp = 1 when initializing lv_disp_drv_t;

 static lv_disp_drv_t disp_drv;                         /*Descriptor of a display driver*/
    lv_disp_drv_init(&disp_drv);                    /*Basic initialization*/

    /*Set up the functions to access to your display*/

    /*Set the resolution of the display*/
    disp_drv.hor_res = MY_DISP_VER_RES;
    disp_drv.ver_res = MY_DISP_HOR_RES;

    /*Used to copy the buffer's content to the display*/
    disp_drv.flush_cb = sf_ui_fb_flush;

    /*Set a display buffer*/
    disp_drv.draw_buf = &draw_buf_dsc_1;
    disp_drv.sw_rotate = 1;
    disp_drv.rotated = LV_DISP_ROT_90;
   ###  **disp_drv.screen_transp = 1;**

**Comment by kisvegabor** [comment]
I was sure that `disp_drv.screen_transp` is initialized to `LV_COLOR_SCREEN_TRANSP` but it seems [it's not the case](https://github.com/lvgl/lvgl/blob/release/v8.3/src/hal/lv_hal_disp.c#L95).

Anyway, as the issues seems to be resolved I close this issue.

**Comment by flyzxy** [comment]
> I was sure that `disp_drv.screen_transp` is initialized to `LV_COLOR_SCREEN_TRANSP` but it seems [it's not the case](https://github.com/lvgl/lvgl/blob/release/v8.3/src/hal/lv_hal_disp.c#L95).
> 
> Anyway, as the issues seems to be resolved I close it.

@kisvegabor 

I found `disp_drv.screen_transp` is initialized to `0` since [this commit](https://github.com/lvgl/lvgl/commit/ff7204ecadd10132b436b11c8948b9a882b58798).

Actually, I don't understand why `screen_transp still shouldn't be enabled` ?
