### ISSUE TITLE
X11 driver hangs or crashes on assert on delete event

### ISSUE THREAD

**Issue by Maldus512** [kisvegabor/lvgl#5759]
### LVGL version

v9.0.0-197-gc25555107

### What happened?

The X11 display driver's `LV_EVENT_DELETE` handler passes a NULL buffer to `lv_display_set_buffers`, presumably to deinitialize it.

https://github.com/lvgl/lvgl/blob/c25555107ca42fd0051800823452d514497d9ae8/src/drivers/x11/lv_x11_display.c#L202

However `lv_display_set_buffers` immediately asserts that the received buffer is not NULL, leading to a crash or freezing the program:

https://github.com/lvgl/lvgl/blob/c25555107ca42fd0051800823452d514497d9ae8/src/display/lv_display.c#L402

What is the point of that call? Could it be removed altogether?

### How to reproduce?

Run a simulated application with X11.

**Comment by FASTSHIFT** [comment]
Have you tried removing it `lv_display_set_buffers(disp, NULL, NULL, 0, LV_DISPLAY_RENDER_MODE_PARTIAL);`? I think it should be unnecessary.

**Comment by kisvegabor** [comment]
I confirm that it's not required to set buffer to `NULL`.

Fixed here: #5799
