### ISSUE TITLE
LVGL V9: Object and Image creater do not free the memory 

### ISSUE THREAD

**Issue by fatiihyildizz** [kisvegabor/lvgl#5760]
### Introduce the problem

Hello,

I designed a 2 page project using LVGL V9. Transitions between pages are done with gestures. When the Gesture event comes, I change the pages as follows (I did it using the GUI Guide as a reference) : 
![image](https://github.com/lvgl/lvgl/assets/56608623/581a7831-7fad-4d8b-9934-6359fe378aa9)

The same event is also available on the other screen. But after scrolling through the pages for a while, I get the following error:
![image](https://github.com/lvgl/lvgl/assets/56608623/d1bd8ab0-87aa-49eb-848d-8e6d2575f061)

In the screen_init functions, I call the lv_obj_create function for the screen and add images to that object with lv_img_create. 
`ps_screen_main = lv_obj_create(NULL);`
`ps_img_bg = lv_img_create(ps_screen_main);`
Why am I getting an overflow error? Shouldn't LVGL free some things when creating img and obj? Or is there something I'm missing?

**Comment by kisvegabor** [comment]
The last parameter of `lv_screen_load_anim` is `false` now, which means the the screen that you are leaving won't be deleted automatically. 

So do you create the screen periodically somewhere or just create them once on start up?

**Comment by fatiihyildizz** [comment]
@kisvegabor I reinstall it when I enter the relevant screen

**Comment by kisvegabor** [comment]
- Do you get the same error is you call `lv_obj_invalidate(lv_screen_actiev())` after `lv_timer_handler` and wait a minute on each screen?
- The issue can be due to memory fragmentation too. Is it better if you increase `LV_MEM_SIZE`?
