### ISSUE TITLE
Previous button in the music  demo is not clickable

### ISSUE THREAD

**Issue by verosys** [kisvegabor/lvgl#5763]
### LVGL version

V8.3.11 and greater

### What happened?

In the music demo, the button to go to the previous title (located to the left of the play button) is not clickable.

Root cause of this problem: The flag  _'LV_OBJ_FLAG_CLICKABLE'_ is not set for this button

Solution: In the file _'lv_demo_music_main.c'_ the following line must be added after line 588:

> lv_obj_add_flag(icon, LV_OBJ_FLAG_CLICKABLE);	// Make the prev button clickable

The code for the previous button now looks at follows, starting from line 585

>     icon = lv_image_create(cont);
>     lv_image_set_src(icon, &img_lv_demo_music_btn_prev);
>     lv_obj_set_grid_cell(icon, LV_GRID_ALIGN_CENTER, 2, 1, LV_GRID_ALIGN_CENTER, 0, 1);
>     lv_obj_add_event_cb(icon, prev_click_event_cb, LV_EVENT_CLICKED, NULL);
>     lv_obj_add_flag(icon, LV_OBJ_FLAG_CLICKABLE);	// Make the prev button clickable
> 

### How to reproduce?

Compile and run the music demo. Press on the next button to go to the next title.
After the next title is shown press the previous button to go to the previous title but nothing happens and the title does not change

**Comment by FASTSHIFT** [comment]
Fixed: https://github.com/lvgl/lvgl/pull/5808
