### ISSUE TITLE
lvgl may cause screen confusion during operation

### ISSUE THREAD

**Issue by yel-best** [kisvegabor/lvgl#5765]
### LVGL version

v8.3.8

### What happened?

There is no problem when I draw the page and run it, but when I add a modal box and delete the pop-up layer, the screen will appear incompletely refreshed. The effect is as follows

![a6f2361fe29948aa14a4ff07d4e9ef0](https://github.com/lvgl/lvgl/assets/82205638/3d0bcccf-605e-42c7-80d8-d0d7ff299e34)

### How to reproduce?

The following is my general method for adding pop-up layers and closing pop-up layers. It is probably to add an interface with a gray background on the top layer and add some informative descriptions.

```
void lv_close_loading(void)
{
    terminal_default_config.isloading = false;
    if (loading_page_cont != NULL)
    {
        lv_obj_del(loading_page_cont);
        loading_page_cont = NULL;
        lv_obj_clear_flag(lv_layer_top(), LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_bg_opa(lv_layer_top(), LV_OPA_TRANSP, 0);
    }
}

void lv_loading(void)
{
    terminal_default_config.isloading = true;
    //   terminal_default_config.loadingTime = millis();
    lv_obj_add_flag(lv_layer_top(), LV_OBJ_FLAG_CLICKABLE);

    static lv_style_t loading_spinner_style;
    lv_style_init(&loading_spinner_style);
    // lv_style_set_arc_color(&loading_style, lv_palette_main(LV_PALETTE_BLUE));

    lv_style_set_arc_width(&loading_spinner_style, 5);

    static lv_style_t loading_cont_style;
    lv_style_init(&loading_cont_style);
    lv_style_set_radius(&loading_cont_style, 0);
    lv_style_set_border_side(&loading_cont_style, LV_BORDER_SIDE_NONE);

    loading_page_cont = lv_obj_create(lv_layer_top());
    lv_obj_set_size(loading_page_cont, LV_PCT(100), LV_PCT(100));
    lv_obj_set_flex_align(loading_page_cont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_flex_flow(loading_page_cont, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_add_style(loading_page_cont, &loading_cont_style, 0);

    lv_obj_t *loading_spinner = lv_spinner_create(loading_page_cont, 1500, 70);
    // lv_obj_add_style(loading_spinner, &loading_spinner_style, 0);
    lv_obj_set_size(loading_spinner, 30, 30);
    lv_obj_set_style_arc_color(loading_spinner, lv_palette_main(LV_PALETTE_YELLOW), LV_PART_INDICATOR);

    lv_obj_set_style_arc_width(loading_spinner, 5, LV_PART_MAIN);
    lv_obj_set_style_arc_width(loading_spinner, 5, LV_PART_INDICATOR);

    loading_page_label = lv_label_create(loading_page_cont);
    lv_label_set_text(loading_page_label, "");
    lv_obj_set_style_text_color(loading_page_label, lv_palette_main(LV_PALETTE_YELLOW), 0);

    lv_obj_set_style_bg_opa(loading_page_cont, LV_OPA_90, 0);
    lv_obj_set_style_bg_color(loading_page_cont, lv_palette_main(LV_PALETTE_GREY), 0);
}

```

**Comment by kisvegabor** [comment]
Could you send an image about the UI without the popup? Just to see how it should like and what the artifacts are.

Please try this:
```c
void lv_close_loading(void)
{
    terminal_default_config.isloading = false;
    if (loading_page_cont != NULL)
    {
        lv_obj_del(loading_page_cont);
        loading_page_cont = NULL;
        lv_obj_clear_flag(lv_layer_top(), LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_bg_opa(lv_layer_top(), LV_OPA_TRANSP, 0);
       
       //ADD THIS
       lv_obj_invalidate(lv_layer_top());

    }
}
```

**Comment by yel-best** [comment]
> Could you send an image about the UI without the popup? Just to see how it should like and what the artifacts are.
> 
> Please try this:
> 
> ```c
> void lv_close_loading(void)
> {
>     terminal_default_config.isloading = false;
>     if (loading_page_cont != NULL)
>     {
>         lv_obj_del(loading_page_cont);
>         loading_page_cont = NULL;
>         lv_obj_clear_flag(lv_layer_top(), LV_OBJ_FLAG_CLICKABLE);
>         lv_obj_set_style_bg_opa(lv_layer_top(), LV_OPA_TRANSP, 0);
>        
>        //ADD THIS
>        lv_obj_invalidate(lv_layer_top());
> 
>     }
> }
> ```

When the pop-up layer disappears, it should look like this

![b7d4efcafb7231d6a536df4967c7d09](https://github.com/lvgl/lvgl/assets/82205638/bcb3b20f-3a6f-4fe4-8258-f83c607f9ae3)

**Comment by yel-best** [comment]
oh... after I added this code, the pop-up modal layer still appeared and was not completely closed, and the layers were confused.

Can you have a better opinion?


```
 //ADD THIS
 lv_obj_invalidate(lv_layer_top());
```

**Comment by yel-best** [comment]
@kisvegabor Hi Can you help me? thanks... 🥲

**Comment by kisvegabor** [comment]
It's really strange. 

Can you print the refreshed areas from the `flush_cb`? After closing the pop up do you see that the whole screen was updated?
