### ISSUE TITLE
rtthread iar8.40 使用组件加入后出现海量bug

### ISSUE THREAD

**Issue by meng-plus** [kisvegabor/lvgl#5776]
### LVGL version

V9.0.1dev

### What happened?

此处的报错让我很疑惑 
#define LV_ATTRIBUTE_FAST_MEM  在 lv_conf.h中有定义 
但是在编译链中却提示 lv_color_op.h 中  给出下面截图的报错 我很不理解， 在裸机中采用iar7.8中一切正常
```c
static inline lv_color_t LV_ATTRIBUTE_FAST_MEM lv_color_mix(lv_color_t c1, lv_color_t c2, uint8_t mix)
```
![image](https://github.com/lvgl/lvgl/assets/37764731/a161152d-a68a-4f7a-a7fc-20977c0fc4d7)
![image](https://github.com/lvgl/lvgl/assets/37764731/73bb3099-44b0-400f-aa14-41ddee123e5b)

### How to reproduce?
需要说明的是 我用rtthread 的env添加8.3.5版本是正常的，但是我切换到最新版本就出现了这个样子，

### 环境
rtthread iar8.4  lvgl9 
主控lpc4088  lvgl835版本正常 
用env工具换成9后 出现海亮报错

**Comment by kisvegabor** [comment]
It seems to me it's an issue with `lv_conf.h` as well.
