### ISSUE TITLE
Please add `lv_span_get_style()` function

### ISSUE THREAD

**Issue by s-hadinger** [kisvegabor/lvgl#5784]
### Introduce the problem

As part of the Berry mapping, I need to get the style from a `lv_span_t` object. Currently the only way is to tamper with the internal structure:

```C
lv_style_t * st = &span->style;
```

### Proposal

It would make the mapping a lot easier if you could add the getter function in `lv_span.c`:

```C
lv_style_t * lv_span_get_style(lv_span_t * span)
{
    return &span->style;
}
```

and in `lv_span.h`:

```C

/**
 * Get style from span
 * @param span   pointer to a span.
 * @return      pointer to a style
 */
lv_style_t * lv_span_get_style(lv_span_t * span);
```

**Comment by kisvegabor** [comment]
Sounds reasonable. Let's discuss all span related things in #5352.
