### ISSUE TITLE
Trailing `\n` ignored in `span`

### ISSUE THREAD

**Issue by s-hadinger** [kisvegabor/lvgl#5785]
### LVGL version

v9.0.0

### What happened?

When setting text of `lv_span`, a carriage return is accepted to get to the next line, except when it's the last character of the span.

However it works well if the `\n` is the first character of a span.

Is it by design?

### How to reproduce?

Example of Micropython in LVGL9 simulator:

```python

# Initialize

import display_driver
import lvgl as lv

# Create a button with a label

scr = lv.obj()
label = lv.label(scr)


text = lv.spangroup(scr)
text.set_pos(10,10)
text.set_size(100,100)
text.set_style_bg_color(lv.color_hex(0x000088), 0)

sp1 = text.new_span()
sp1.set_text("Hello\n")
sp2 = text.new_span()
sp2.set_text(" World")

sp1 = text.new_span()
sp1.set_text("Hello")
sp2 = text.new_span()
sp2.set_text("\n World")

lv.screen_load(scr)
```

Output is:
<img width="105" alt="image" src="https://github.com/lvgl/lvgl/assets/49731213/9d6abf25-f1b1-4bb9-a423-6a77cbf7bb4b">

**Comment by kisvegabor** [comment]
It's not by design, but it's really a bug. 

Now I'm trying to catch up with the comments and issues so I can look into it only a little bit later. If you see where the problem could be, please send a PR.

**Comment by C47D** [comment]
So, is it expected to have both `Hello World` in the same line? Or should they be spitted as the `Hello World` below?
