### ISSUE TITLE
Messagebox widget api, lv_msgbox_get_footer() is returning header object instead of footer object. 

### ISSUE THREAD

**Issue by mahesh-slx** [kisvegabor/lvgl#5788]
### LVGL version

v9.0.0

### What happened?

In ``lv_msgbox.c`` file, ``lv_msgbox_get_footer()`` api is returning ``header``, which actually should return ``footer``. 

```
lv_obj_t * lv_msgbox_get_footer(lv_obj_t * obj)
{
    LV_ASSERT_OBJ(obj, MY_CLASS);
    lv_msgbox_t * mbox = (lv_msgbox_t *)obj;
    return mbox->header;
}
```

**Comment by kisvegabor** [comment]
Ah, a beautiful copy paste error :slightly_smiling_face: Thank you for reporting it.

I've fixed it in #5804.
