### ISSUE TITLE
lv_imagebutton_set_src failed to display image without left & right elements

### ISSUE THREAD

**Issue by PierreRambaud** [kisvegabor/lvgl#5803]
### LVGL version

v9.0.0-212-g481dd7b91

### What happened?

When trying to use `lv_imagebutton_set_src` without left & right elements, it fails to render the image.
As far as I know, both parameters are not mandatory, I should be able to use NULL.

https://github.com/lvgl/lvgl/assets/1462701/81e9f93b-bca0-4fac-a270-256cc6c0c814

### How to reproduce?

```c
  lv_obj_t* button = lv_imagebutton_create(parent);
  lv_obj_add_style(button, &style_default_text, 0);
  lv_obj_set_width(button, 150);

  lv_imagebutton_set_src(button, LV_IMAGEBUTTON_STATE_RELEASED, NULL, img_src, NULL);
  lv_imagebutton_set_src(button, LV_IMAGEBUTTON_STATE_PRESSED, NULL, img_pressed_src, NULL);

  lv_obj_t* label = lv_label_create(button);
  lv_label_set_text(label, title);
  lv_obj_align(label, LV_ALIGN_CENTER, 10, 4);
```

**Comment by PierreRambaud** [comment]
I still have the problem with latest changes, can you show me which commit should have fix  this please?

**Comment by kisvegabor** [comment]
I hoped this: https://github.com/lvgl/lvgl/pull/5719

Please send the required images too to reproduce the issue.

cc @liamHowatt, could you help us the debug it?

**Comment by liamHowatt** [comment]
@kisvegabor in my debugging I couldn't find anything wrong with left and right NULL or not, but I did have issues with drawing mid. I opened a PR for a fix that may be the problem here.

#5849

@PierreRambaud please try my fix to see if it solves your issue. The commit is 2845d5c99b9385c8f5f2c38d673f7c88b4fdf89f

**Comment by PierreRambaud** [comment]
> @kisvegabor in my debugging I couldn't find anything wrong with left and right NULL or not, but I did have issues with drawing mid. I opened a PR for a fix that may be the problem here.
> 
> #5849
> 
> @PierreRambaud please try my fix to see if it solves your issue. The commit is [2845d5c](https://github.com/lvgl/lvgl/commit/2845d5c99b9385c8f5f2c38d673f7c88b4fdf89f)

Everything seems to be ok with your latest fix! I can use NULL for left and right parameter :pray:

**Comment by kisvegabor** [comment]
Should be resolved by https://github.com/lvgl/lvgl/pull/5849.
