### ISSUE TITLE
how to set span group frame border?

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5805]
### LVGL version

9.0.1

### What happened?

I create a spangroup, but all set is set he header information, no set to frame border, and show no frame boder,as fllower:
![图片](https://github.com/lvgl/lvgl/assets/40679769/d348ea8b-6d45-4c26-8205-3daa8ebcc858)

same as the lable widget

**Comment by xinsuinizhuan** [comment]
I want a group like this, Group have the border, and have the it's title, and group all it's self widgets:
![图片](https://github.com/lvgl/lvgl/assets/40679769/d0fd94d4-a45e-42c2-97b3-51dcd165f0e9)
But the real is only have the title, have no border:
![Uploading 图片.png…]()

**Comment by xinsuinizhuan** [comment]
I want a group like this, Group have the border, and have the it's title, and group all it's self widgets:
![图片](https://github.com/lvgl/lvgl/assets/40679769/d0fd94d4-a45e-42c2-97b3-51dcd165f0e9)
But the real is only have the title, have no border:
![Uploading 图片.png…]()

**Comment by kisvegabor** [comment]
Can you just place a label on top of a border? You also need to set the `bg_color` of the label to the same color as the background of the border to make it covert the border.
