### ISSUE TITLE
Crashing LVGL with Wifi

### ISSUE THREAD

**Issue by YusufBesim** [kisvegabor/lvgl#5813]
### Introduce the problem

Hello,

I'm using ESP32-S3 and developing gui with LVGL when I try add wifi it crashes

rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x42020faf
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2920
entry 0x403c98d8
Found xl9535

I tried run wifi and lvgl separated CPU like: (Changed stack size nothing changed)

xTaskCreatePinnedToCore(taskDisplayHandler, "TaskDisplayHandler", 8500, NULL, 1, NULL, 0);
xTaskCreatePinnedToCore(fetchData, "FetchDataTask", 12000, NULL, 1, NULL, 1);
void taskDisplayHandler(void * parameter)
{
Serial.println("Task Display Handler Started");
while (1) {
lv_task_handler();
vTaskDelay(pdMS_TO_TICKS(10));
}
}
void fetchData(void * parameter) {
Serial.println("Wifi Starting...");
WiFi.begin(ssid, password);
while (1) {
Serial.println("Fetching data...");
vTaskDelay(pdMS_TO_TICKS(1000));
}
}

Backtrace

Backtrace: 0x40382d01:0x3fcaac40 0x40383845:0x3fcaac60 0x403839a8:0x3fcaac80 0x40377e37:0x3fcaaca0 0x40377e49:0x3fcaacd0 0x4037f0e4:0x3fcaacf0 0x420030d9:0x3fcaad30 0x4200384a:0x3fcaad60 0x420038a6:0x3fcaad80 0x42003a12:0x3fcaadc0 0x42004078:0x3fcaadf0 0x42014fe0:0x3fcaae40 0x4200308f:0x3fcaae70

  #0  0x40382d01:0x3fcaac40 in remove_free_block at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:206
      (inlined by) block_locate_free at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:442
      (inlined by) tlsf_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:849
  #1  0x40383845:0x3fcaac60 in multi_heap_malloc_impl at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap.c:187
  #2  0x403839a8:0x3fcaac80 in multi_heap_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap_poisoning.c:234
      (inlined by) multi_heap_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap_poisoning.c:223
  #3  0x40377e37:0x3fcaaca0 in heap_caps_malloc_base at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:175
      (inlined by) heap_caps_malloc_base at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:120
  #4  0x40377e49:0x3fcaacd0 in heap_caps_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:195
  #5  0x4037f0e4:0x3fcaacf0 in xTaskCreatePinnedToCore at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/freertos/tasks.c:863
  #6  0x420030d9:0x3fcaad30 in open_screen2_event_handler(_lv_event_t*) at src/main.cpp:575
  #7  0x4200384a:0x3fcaad60 in event_send_core at lib/lvg/src/core/lv_event.c:467
  #8  0x420038a6:0x3fcaad80 in lv_event_send at lib/lvg/src/core/lv_event.c:75
  #9  0x42003a12:0x3fcaadc0 in indev_proc_release at lib/lvg/src/core/lv_indev.c:980
  #10 0x42004078:0x3fcaadf0 in indev_pointer_proc at lib/lvg/src/core/lv_indev.c:384
      (inlined by) lv_indev_read_timer_cb at lib/lvg/src/core/lv_indev.c:101
  #11 0x42014fe0:0x3fcaae40 in lv_timer_exec at lib/lvg/src/misc/lv_timer.c:313
      (inlined by) lv_timer_handler at lib/lvg/src/misc/lv_timer.c:109
  #12 0x4200308f:0x3fcaae70 in taskDisplayHandler(void*) at lib/lvg/src/lv_api_map.h:37 (discriminator 1)
      (inlined by) taskDisplayHandler(void*) at src/main.cpp:784 (discriminator 1)

Thanks for help.

**Comment by kisvegabor** [comment]
It seems like the memory allocator crashes due to multi threading.

Which LVGL version do you use?
Do you use LVGL's built in malloc or changed it to stdlib malloc?
