### ISSUE TITLE
Running into memory allocator assert (prev_free field can not be null)

### ISSUE THREAD

**Issue by danielfu11** [kisvegabor/lvgl#5817]
### LVGL version

v8.3.11

### What happened?

Hi,

I am running into an tlsf_assert in remote_free_block where “prev_free field can not be null”. What does this mean and how can this condition be triggered? If the block is the head of the list, is it not expected that the prev_free points to NULL?

How can I go about debugging this issue?

I am running v8.3.11. Any pointers or help would be much appreciated

Thanks!

**Comment by FASTSHIFT** [comment]
Can you reproduce the problem in the [simulator](https://github.com/lvgl/lv_port_pc_eclipse)? Or give a snippet of code that can reproduce the BUG?
This is usually a heap corruption caused by memory access out of bounds or use after memory release.

**Comment by fbiego** [comment]
This happens when you don't call `lv_init();`
Leaving this here incase someone has the same issue

**Comment by danielfu11** [comment]
@fbiego That was not my issue, unfortunately.

The issue was an undocumented silicon bug in the imxrt106X MCU causing SDRAM accesses to fail. See forum thread here: https://community.nxp.com/t5/i-MX-RT-Crossover-MCUs/i-MXRT1060-SEMC-SDRAM-Data-Corruption/m-p/1172919
