### ISSUE TITLE
lv_obj takes a long time to create

### ISSUE THREAD

**Issue by ChowhoundWu** [kisvegabor/lvgl#5819]
### Introduce the problem

I have created many complex interfaces using lvgl v8.2, which resulted in too many lv_obj objects, causing long startup times. On a desktop computer, it takes about 3 seconds to start, while on a Linux development board, it takes around 30 seconds. Is there any good solution?

**Comment by Viatorus** [comment]
Take a look here: https://github.com/lvgl/lvgl/issues/5815
