### ISSUE TITLE
Lvgl start cost too much time

### ISSUE THREAD

**Issue by ChowhoundWu** [kisvegabor/lvgl#5820]
### LVGL version

v8.20

### What happened?

I have created many complex interfaces using lvgl v8.2, which resulted in too many lv_obj objects and styles, causing long startup times. On a desktop computer, it takes about 3 seconds to start, while on a Linux development board, it takes around 30 seconds. Is there any good solution?

**Comment by kisvegabor** [comment]
Hi,

Have you disabled the LV_USE_ASSERTs in lv_conf.h?

**Comment by ChowhoundWu** [comment]
In my lv_conf.h it's ：

#define LV_USE_ASSERT_NULL          1   /*Check if the parameter is NULL. (Very fast, recommended)*/
#define LV_USE_ASSERT_MALLOC        1   /*Checks is the memory is successfully allocated or no. (Very fast, recommended)*/
#define LV_USE_ASSERT_STYLE         0   /*Check if the styles are properly initialized. (Very fast, recommended)*/
#define LV_USE_ASSERT_MEM_INTEGRITY 0   /*Check the integrity of `lv_mem` after critical operations. (Slow)*/
#define LV_USE_ASSERT_OBJ           0   /*Check the object's type and existence (e.g. not deleted). (Slow)*/

I assigned a lot of lv_obj, each lv_obj had its own style, and I had a lot of lv_obj (about 30?). As a page container, then 10 page containers were created and tested on a desktop, which took about 2.5 seconds, but it would take a lot of time to generate an obj on a Linux board even if the compilation is optimized to O2.

**Comment by ChowhoundWu** [comment]
Also the pages are a lot, and these are all different from each other.

**Comment by kisvegabor** [comment]
On Linux can you run a profiler to see what takes that much time? 

Can you share a small code snippet which is slow on your end?

I don't know if it's related, but it was already reported that textarea creation is slower than it ought to be.

**Comment by ChowhoundWu** [comment]
FMotorControl = new TCardInverter(this);
    SetPos(FMotorControl->GetLvObj(), 0, 52);
    SetSize(FMotorControl->GetLvObj(), 675, 225);

**Comment by ChowhoundWu** [comment]
I drew a simple UML diagram to illustrate：

**Comment by ChowhoundWu** [comment]
I drew a simple UML diagram to illustrate：
![6f52acff389c13f404a9f8c3f5fbfcd6](https://github.com/lvgl/lvgl/assets/41661837/2f01dc7c-902f-4511-88d4-89445bb0eaad)

**Comment by ChowhoundWu** [comment]
It's a simple uml, I use C++, new TCard Cont 20 times cost about 1.6s on PC. And on a Linux development board  it cost about 16s.

**Comment by kisvegabor** [comment]
Please send a code snippet that I can use the reproduce the slow creation.
