### ISSUE TITLE
FATFS does not detect the end of entries in fs_dir_read

### ISSUE THREAD

**Issue by serper** [kisvegabor/lvgl#5823]
### LVGL version

v9.0.0

### What happened?

The fs_dir_read function not takes into account the end of the entries, since it never finishes reading the next one, thus entering a loop.

### How to reproduce?

If, for example, you use lv_file_explorer, loading the list of files loops until another error occurs and the list shows all files and hundreds of empty entries.

**Comment by serper** [comment]
To correct it, only is needed to put one line in file _lvgl/src/libs/fsdrv/lv_fs_fatfs.c_ on the funcion:

```
static lv_fs_res_t fs_dir_read(lv_fs_drv_t * drv, void * dir_p, char * fn, uint32_t fn_len)
{
    LV_UNUSED(drv);
    FRESULT res;
    FILINFO fno;
    fn[0] = '\0';

    do {
        res = f_readdir(dir_p, &fno);
        if(res != FR_OK) return LV_FS_RES_UNKNOWN;

        if (fno.fname[0] == 0) break; /* End of the directory */

        if(fno.fattrib & AM_DIR) {
            lv_snprintf(fn, fn_len, "/%s", fno.fname);
        }
        else lv_strncpy(fn, fno.fname, fn_len);

    } while(lv_strcmp(fn, "/.") == 0 || lv_strcmp(fn, "/..") == 0);

    return LV_FS_RES_OK;
}
```
This line is that is needed:  
```
if (fno.fname[0] == 0) break; /* End of the directory */
```

**Comment by FASTSHIFT** [comment]
Very good! Can you submit a PR?

**Comment by serper** [comment]
Yes
https://github.com/lvgl/lvgl/pull/5826
