### ISSUE TITLE
Header files that do not have extern "c"

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#5825]
### Introduce the problem

These header do not have the `extern "C"` in them

gifdec.h
ftoption.h
lodepng.h
stb_truetype_htcw.h
lv_style_gen.h
lv_obj_style_gen.h

The only thing I didn't go through was thorvg because it is written in CPP. I would imagine that the header files should also have it done to them as well. I am not sure. 

### Proposal

Add it to the header files

**Comment by kdschlosser** [comment]
OK but the rest of the files that are listed do need the `extern "c"` correct? I wanted to make sure before I make the changes needed and submit a PR for them.

**Comment by FASTSHIFT** [comment]
Other files require extern "C", among which `lv_style_gen.h` `lv_obj_style_gen.h` is generated by a script and the [script file](https://github.com/lvgl/lvgl/blob/master/scripts/style_api_gen.py) needs to be modified.

**Comment by kdschlosser** [comment]
I know the script needs to be updated and that is not a big deal to do.

**Comment by kdschlosser** [comment]
#5857

**Comment by kdschlosser** [comment]
Thank you sir for the help with this.
