### ISSUE TITLE
If the offset_y parameter in function lv_canvas_transform is negative, it cannot be displayed properly

### ISSUE THREAD

**Issue by sywxf** [kisvegabor/lvgl#5827]
### LVGL version

8.3.10

### What happened?

<img width="282" alt="截屏2024-03-10 下午10 35 50" src="https://github.com/lvgl/lvgl/assets/3109813/954f8e47-4d43-47df-8efb-bef1ca917535">
<img width="265" alt="截屏2024-03-10 下午10 34 50" src="https://github.com/lvgl/lvgl/assets/3109813/f0cc9b1e-40c7-42a5-86a8-cde0fd057a78">

### How to reproduce?

lv_canvas_transform(canv, &imgs[4], 0, LV_IMG_ZOOM_NONE, 0, -100, 0, 0, true);

**Comment by liamHowatt** [comment]
## Reproduction

I reproduced the issue on v8.3.10 using the example `lv_example_canvas_1` and adjusting this line:

https://github.com/lvgl/lvgl/blob/06e229cc7679c01119ca5d905a1f9dad96f475f0/examples/widgets/canvas/lv_example_canvas_1.c#L50

0, 0 -- unmodified, okay
`lv_canvas_transform(canvas, &img, 120, LV_IMG_ZOOM_NONE, 0, 0, CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2, true);`
![image](https://github.com/lvgl/lvgl/assets/30486941/e4a07c8a-b805-4bb2-be4f-131ac6522101)

0, -50 -- y-offset of -50, displayed incorrectly
`lv_canvas_transform(canvas, &img, 120, LV_IMG_ZOOM_NONE, 0, -50, CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2, true);`
![image](https://github.com/lvgl/lvgl/assets/30486941/41e986f9-a1e4-468a-b03a-2b512833d2ff)

## Fix
Branch: https://github.com/liamHowatt/lvgl/tree/fix/canvtranf-offset-y

https://github.com/liamHowatt/lvgl/commit/a9dbcb59cfd85639976361065228e790e6f337a0?diff=unified&w=1

I removed an `if` block that stopped it from drawing the rows above the original position of the image. I can't determine why this was there in the first place or whether there are any side effects for removing it.

Now,
0, -50 -- y-offset of -50, okay
`lv_canvas_transform(canvas, &img, 120, LV_IMG_ZOOM_NONE, 0, -50, CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2, true);`
![image](https://github.com/lvgl/lvgl/assets/30486941/e92f6307-50e9-4c51-9973-d3e244f55e4f)

This function `lv_canvas_transform` no longer exists in v9 and I'm not sure how fixes for older major versions are handled. Open to input from others on this.

**Comment by kisvegabor** [comment]
@liamHowatt 
Thanks for the investigation! 

> This function lv_canvas_transform no longer exists in v9 and I'm not sure how fixes for older major versions are handled. Open to input from others on this.

I consider it a s bugfix. Could you send a Pull request to the `release/v8.3` branch?

**Comment by kisvegabor** [comment]
Foxed by https://github.com/lvgl/lvgl/pull/5846
