### ISSUE TITLE
How to draw curves？This feature is very common and useful

### ISSUE THREAD

**Issue by Staok** [kisvegabor/lvgl#5842]
### Introduce the problem

when use the Line widget, there is no any support of draw curves

### Proposal

a curve can be defined by three points and a curvature value, hope the Line widget support this feature, this is very useful

**Comment by kisvegabor** [comment]
You can use the [arc widget](https://docs.lvgl.io/master/widgets/arc.html). It describes the curve differently, but the result should be the same :slightly_smiling_face:

**Comment by Staok** [comment]
use the arc weight can cope my work for now...ok
