### ISSUE TITLE
lv_api_map_v8.h missing some defines to compile current SLS 1.4 generated code

### ISSUE THREAD

**Issue by antonio-pasini** [kisvegabor/lvgl#5848]
### LVGL version

v9.0

### What happened?

To make compiling SLS 1.4 generated code i had to add the following definitions in lv_api_map_v8.h:

#define LV_IMGBTN_STATE_PRESSED	LV_IMAGEBUTTON_STATE_PRESSED
#define LV_IMGBTN_STATE_RELEASED	LV_IMAGEBUTTON_STATE_RELEASED

#define lv_mem_alloc		lv_malloc
#define lv_mem_free		lv_free
#define lv_imgbtn_create	lv_imagebutton_create
#define lv_imgbtn_set_src	lv_imagebutton_set_src
#define lv_event_send		lv_obj_send_event

probably others are missing too. 

Also missing is an equivalent to lv_chart_set_axis_tick() which SLS uses when using chart widget. 
But for this I didn't find a simple replacement.

**Comment by kisvegabor** [comment]
Hi Antonio,

Thank you for reporting this issue. Could you send a Pull request?

Really there is no simple replacement for the chart axis. :slightly_frowning_face:
