### ISSUE TITLE
manually change the state of an item in the table to focused

### ISSUE THREAD

**Issue by liangfei2021** [kisvegabor/lvgl#5854]
### LVGL version

lvgl 8.2

### What happened?

donot find the handle

**Comment by liangfei2021** [comment]
@kisvegabor

**Comment by kisvegabor** [comment]
There is no API for it but you can do this:
```c
    lv_table_t * table = (lv_table_t *) obj;
    table->col_act = 1;
    table->row_act = 3;
    lv_obj_invalidate(obj);
```

**Comment by liangfei2021** [comment]
thank you，I try

**Comment by liangfei2021** [comment]
There are multiple items in the table, how to make them scroll up (my screen can't be touched, only the relevant functions can be called)

**Comment by liamHowatt** [comment]
You could use `lv_obj_scroll_by`, `lv_obj_scroll_to` on the table.

If my understanding is correct, the cells aren't `obj`s so they can't have the `LV_OBJ_FLAG_SCROLL_ON_FOCUS` flag set or have `lv_obj_scroll_to_view` done to them.

If `get_row_height` was public then it could be used in conjunction with `lv_obj_scroll_to`. `lv_table_set_col_width` is public.
