### ISSUE TITLE
background-repeat implementation issues

### ISSUE THREAD

**Issue by C-Ackerman** [kisvegabor/lvgl#5859]
### LVGL version

v9.0.0

### What happened?

How to implement background-repeat: repeat-x; repeat-y   
https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat

For example repeat-y  i try lv_obj_set_size(bgimg, 150, LV_SIZE_CONTENT); and lv_image_set_align(bgimg, LV_IMAGE_ALIGN_TILE);, but modify the image like this The size will affect its child nodes, so the child nodes also need to set LV_OBJ_FLAG_OVERFLOW_VISIBLE to control the rendering area?Is there any other way?

![image](https://github.com/lvgl/lvgl/assets/49789618/5197b9f3-69d3-485e-b4d7-2306db81e96b)

![image](https://github.com/lvgl/lvgl/assets/49789618/7bdc2cd5-9334-4981-ac9d-bc3c9c0786e0)

```
void lv_example_style_6(void)
{

    lv_obj_t * native = lv_obj_create(lv_screen_active());
    lv_obj_set_size(native, 450, 450);
    static lv_style_t style;
    lv_style_init(&style);
    // lv_style_set_bg_color(&style, lv_palette_lighten(LV_PALETTE_GREY, 3));
    lv_style_set_border_width(&style, 2);
    lv_style_set_border_color(&style, lv_palette_lighten(LV_PALETTE_YELLOW, 3));
    lv_obj_add_style(native, &style, 0);

    lv_obj_t * bgimg = lv_image_create(native);
    lv_image_set_src(bgimg, "/data/app/logo.png");
    lv_obj_set_size(bgimg, 150, LV_SIZE_CONTENT);
    lv_image_set_align(bgimg, LV_IMAGE_ALIGN_TILE);


    lv_obj_t * panel1 = lv_obj_create(bgimg);
    lv_obj_set_size(panel1, 440, 440);
    lv_obj_center(panel1);
    static lv_style_t style1;
    lv_style_init(&style1);
    lv_style_set_opa(&style1, 50);
    lv_style_set_border_width(&style1, 2);
    lv_style_set_border_color(&style1, lv_palette_lighten(LV_PALETTE_PINK, 3));
    lv_obj_add_style(panel1, &style1, 0);


    lv_obj_t * label = lv_label_create(bgimg);
    lv_label_set_text(label, "Widgets demo");
    lv_obj_set_size(label, 100, 200);
    lv_obj_align(label, LV_ALIGN_CENTER, 50, 100);
}
```

**Comment by kisvegabor** [comment]
What about creating the images on `native` and not on `bgimg`?
If needed you can add `LV_OBJ_FLAG_IGNORE_LAYOUT` or `LV_OBJ_FLAG_IGNORE_LAYOUT` to `bgimg`.

**Comment by C-Ackerman** [comment]
What about creating the images on native and not on bgimg?

How to create image on native? Now it seems to be created on native.

 lv_obj_t * bgimg = lv_image_create(native);

**Comment by kisvegabor** [comment]
I mean
```c
    lv_obj_t * panel1 = lv_obj_create(native);
    ...
    
    lv_obj_t * label = lv_label_create(native);
```

**Comment by kisvegabor** [comment]
What is the exact intention? `native` is a container, which has a `bgimg` as background, and there are some children too?

**Comment by C-Ackerman** [comment]
> What is the exact intention? `native` is a container, which has a `bgimg` as background, and there are some children too?

How to implement background-size and background-image？

**Comment by kisvegabor** [comment]
There is an example about how I imagine it:
```c
  /*Create a container with COLUMN flex direction*/
    lv_obj_t * cont_col = lv_obj_create(lv_screen_active());
    lv_obj_set_size(cont_col, 240, 300);
    lv_obj_align_to(cont_col, cont_row, LV_ALIGN_OUT_BOTTOM_MID, 0, 5);
    lv_obj_set_flex_flow(cont_col, LV_FLEX_FLOW_COLUMN);

    LV_IMAGE_DECLARE(img_cogwheel_argb);
    lv_obj_t * image = lv_image_create(cont_col);
    lv_obj_set_size(image, lv_pct(100), lv_pct(100));
    lv_image_set_src(image, &img_cogwheel_argb);
    lv_image_set_inner_align(image, LV_IMAGE_ALIGN_TILE);
    lv_obj_add_flag(image, LV_OBJ_FLAG_FLOATING);


    uint32_t i;
    for(i = 0; i < 10; i++) {
        lv_obj_t * obj;
        lv_obj_t * label;

        /*Add items to the column*/
        obj = lv_button_create(cont_col);
        lv_obj_set_size(obj, LV_PCT(100), LV_SIZE_CONTENT);

        label = lv_label_create(obj);
        lv_label_set_text_fmt(label, "Item: %"LV_PRIu32, i);
        lv_obj_center(label);
    }
```

![bgimg](https://github.com/lvgl/lvgl/assets/7599318/aa3188ef-8455-47a1-a0c2-3f820a1973a8)
