### ISSUE TITLE
background-position implementation issues

### ISSUE THREAD

**Issue by C-Ackerman** [kisvegabor/lvgl#5860]
### LVGL version

v9.0.0

### What happened?

If  want to implement background-repeat: repeat-y background-position: 25% 50%;

lv_image_set_offset_x(bgimg, 50); and lv_image_set_align(bgimg, LV_IMAGE_ALIGN_TILE); cannot take effect at the same time.
lv_obj_set_x(bgimg, 100); and lv_image_set_align(bgimg, LV_IMAGE_ALIGN_TILE); can take effect at the same time, but this will also change the position of the child node （panel1）, so you need to adjust the position of the child node again.Is there a better way

![image](https://github.com/lvgl/lvgl/assets/49789618/84dceff8-085d-4413-9318-aa60db158f20)

![image](https://github.com/lvgl/lvgl/assets/49789618/be9151cc-6b9b-49ed-9533-447d52f8589f)

```
void lv_example_style_6(void)
{

    lv_obj_t * native = lv_obj_create(lv_screen_active());
    lv_obj_set_size(native, 450, 450);
    static lv_style_t style;
    lv_style_init(&style);
    // lv_style_set_bg_color(&style, lv_palette_lighten(LV_PALETTE_GREY, 3));
    lv_style_set_border_width(&style, 2);
    lv_style_set_border_color(&style, lv_palette_lighten(LV_PALETTE_YELLOW, 3));
    lv_obj_add_style(native, &style, 0);

    lv_obj_t * bgimg = lv_image_create(native);
    lv_image_set_src(bgimg, "/data/app/logo.png");
    // lv_image_set_offset_x(bgimg, 100);
    // lv_obj_set_pos(bgimg,  260, 150);
    lv_obj_set_x(bgimg, 100);
    // lv_image_set_scale_x(bgimg, LV_SCALE_NONE * 2);
    lv_obj_set_size(bgimg, 150, LV_SIZE_CONTENT);
    lv_image_set_align(bgimg, LV_IMAGE_ALIGN_TILE);


    lv_obj_t * panel1 = lv_obj_create(bgimg);
    lv_obj_set_size(panel1, 440, 440);
    lv_obj_center(panel1);
    static lv_style_t style1;
    lv_style_init(&style1);
    lv_style_set_opa(&style1, 50);
    lv_style_set_border_width(&style1, 2);
    lv_style_set_border_color(&style1, lv_palette_lighten(LV_PALETTE_PINK, 3));
    lv_obj_add_style(panel1, &style1, 0);


    lv_obj_t * label = lv_label_create(bgimg);
    lv_label_set_text(label, "Widgets demo");
    lv_obj_set_size(label, 100, 200);
    lv_obj_align(label, LV_ALIGN_CENTER, 50, 100);
}

```

**Comment by kisvegabor** [comment]
By applying `LV_OBJ_FLAG_IGNORE_LAYOUT` or `LV_OBJ_FLAG_IGNORE_LAYOUT` on `bgimg` will make it ignore layouts, scrolling, etc and it won't affect any children.
