### ISSUE TITLE
Bin image usage with LVGL v9

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5868]
### LVGL version

master

### What happened?

Reported from https://forum.lvgl.io/t/bin-image-usage-with-lvgl-v9/14965/1

I'm not sure of the root cause. It must be an issue that not covered by current configuration file.

My hands are tied now, appreciate help.

### How to reproduce?

See original post.

**Comment by kisvegabor** [comment]
Should be fixed by https://github.com/lvgl/lvgl/pull/5892
