### ISSUE TITLE
reverse mode for lv_arc

### ISSUE THREAD

**Issue by IB-AST** [kisvegabor/lvgl#5870]
### LVGL version

V8.3.11

### What happened?

Touch handling in reverse arc mode does not seem to work correctly.

Setting any value through code is okay, but when touching it shows odd behaviour.

Video taken from SLS, but behaviour is same on real display.

https://github.com/lvgl/lvgl/assets/148654555/fd0a70cd-0d05-4d4b-a916-04a314f3a125

 

### How to reproduce?

just use arc in reverse mode and touch

**Comment by kisvegabor** [comment]
Hi,

It was already fixed in v9 and I've cherry-picked the fix to `release/v8.4` [here](https://github.com/lvgl/lvgl/commit/c512eccb7bba2ea5439bb1310356debfb86506b8).

**Comment by IB-AST** [comment]
Thanks a lot for tackling this kisvegabor!

Flickering is fixed, but unfortunately it will not allow for full range touch now.

Touch always stops same max. angle at about 11o'Clock.

At arc range of 0-1400 (Bg start 90°/ Bg end 315°)  it allows a max. value of ~840 on touch.

Different range or start/end angle gets same results.

**Comment by kisvegabor** [comment]
Please send a code snippet and a video to better understand the issue.

**Comment by kisvegabor** [comment]
Thank you, but please also send a code snippet to create and initialize the arc. This way I can see if I could fix it. :slightly_smiling_face:

**Comment by IB-AST** [comment]
This is genereated by SLS:

    ui_Instrument2 = lv_arc_create(ui_InstrumentPanel);
    lv_obj_set_width(ui_Instrument2, 200);
    lv_obj_set_height(ui_Instrument2, 200);
    lv_obj_set_x(ui_Instrument2, 110);
    lv_obj_set_y(ui_Instrument2, 15);
    lv_obj_set_align(ui_Instrument2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Instrument2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_Instrument2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_Instrument2, 0, 1400);
    lv_arc_set_value(ui_Instrument2, 300);
    lv_arc_set_bg_angles(ui_Instrument2, 90, 315);
    lv_arc_set_mode(ui_Instrument2, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_Instrument2, 45);
    lv_obj_set_style_arc_color(ui_Instrument2, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Instrument2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Instrument2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Instrument2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Instrument2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_AccentColor);
    ui_object_set_themeable_style_property(ui_Instrument2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_AccentColor);
    lv_obj_set_style_arc_width(ui_Instrument2, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Instrument2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Instrument2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Instrument2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

Project settings:
![image](https://github.com/lvgl/lvgl/assets/148654555/2dfe88cd-184e-496f-b84c-91875c0f8fc7)

**Comment by kisvegabor** [comment]
I've just tested this code, and it doesn't work in either v8 or v9.
 
@C47D could take look at it? This is a simplified code to reproduce the issue:

```c
lv_obj_t * ui_Instrument2 = lv_arc_create(lv_scr_act());
lv_obj_set_size(ui_Instrument2, 200, 200);
lv_obj_set_align(ui_Instrument2, LV_ALIGN_CENTER);
lv_arc_set_range(ui_Instrument2, 0, 1400);
lv_arc_set_value(ui_Instrument2, 300);
lv_arc_set_bg_angles(ui_Instrument2, 90, 315);
lv_arc_set_mode(ui_Instrument2, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_Instrument2, 45);
```

**Comment by IB-AST** [comment]
Not stale

**Comment by kisvegabor** [comment]
I haven't hear from @C47D  from a while. I hope is okay, and just busy with something. 

@liamHowatt can you add it to your todo list after the API retirement?

**Comment by liamHowatt** [comment]
PR opened! #6188
