### ISSUE TITLE
Outstanding bugs! CAN’T set different panels to show different gradient colors!

### ISSUE THREAD

**Issue by Staok** [kisvegabor/lvgl#5877]
### LVGL version

8.3.11

### What happened?

LVGL 8.3.11
squareLine 1.4.0

use several grad to set different panel, but they result the same show
I put this bug issue to LVGL github repo:
https://github.com/lvgl/lvgl/issues/5866

but I try in squareLine result the same issue:
![image](https://github.com/lvgl/lvgl/assets/59993573/647f227d-a96b-4e05-8bf9-fee80dd7ebaa)

the running result is:
![image](https://github.com/lvgl/lvgl/assets/59993573/253b9684-4474-4ecc-bed6-98feaebb53aa)

so this is a LVGL bug??

I urgently need to use this feature.
That different panels to be able to set different gradient colors

**Comment by Staok** [comment]
@kisvegabor looking forward for reply, I waited for days, is this happened because the wrong usage I did or the LVGL bug, can it be fixed, waiting for help

**Comment by kisvegabor** [comment]
Hi,

I've replied in #5866.
