### ISSUE TITLE
Possible bug: Taking snapshot saves only part of screen

### ISSUE THREAD

**Issue by PGNetHun** [kisvegabor/lvgl#5886]
### LVGL version

9.0.0.0

### What happened?

Potential bug in LVGL:

taking snapshot saves only part of screen.

details:
https://forum.lvgl.io/t/lvgl-snapshot-take/15105

**Comment by kisvegabor** [comment]
Closing as the issue was in the user's code. See [here](https://forum.lvgl.io/t/lvgl-snapshot-take/15105/4?u=kisvegabor).
