### ISSUE TITLE
If a branch is no longer useful, please delete it

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#5894]
### Introduce the problem

![1](https://github.com/lvgl/lvgl/assets/150422110/cb749d56-9c9e-47c5-9c23-b4a04c028dff)
![2](https://github.com/lvgl/lvgl/assets/150422110/63079d03-f723-4f73-a752-37033caa92fc)

**Comment by kisvegabor** [comment]
I've just cleaned it up. `feat/crown` will be removed too when https://github.com/lvgl/lvgl/pull/5057 is merged.
