### ISSUE TITLE
Use `lv_strncat` where necessary

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#5897]
Add `lv_strncat` and replace `lv_strcat` where necessary.

> Having only `lv_strncat` makes sense. 

> I agree to to spare `lv_strncpy` for an other PR.

_Originally posted by @kisvegabor in https://github.com/lvgl/lvgl/pull/5767#discussion_r1513452127_

**Comment by kisvegabor** [comment]
@liamHowatt I think it would be great first issue. Could you open a PR for it?

**Comment by liamHowatt** [comment]
Fyi: #5927
