### ISSUE TITLE
Layout costs much time

### ISSUE THREAD

**Issue by W-Mai** [kisvegabor/lvgl#5901]
### LVGL version

v9.0.0

### What happened?

Layout costs much time.
When multiple obj are nested together, there will be too many additional layout calculations.

## Prepare the testcase

I create a new repo to reproduce this problem.

<img width="480" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/8d64e5f2-4ae6-427e-b291-a609bc6e3082">

1. Download this repo https://github.com/W-Mai/lvgl_settings_demo.git
2. Init submodule `git submodule update --init --recursive`
3. Checkout out to the profile branch `git checkout profile`
4. Apply a patch for more profile `git apply 0001-profile-profile-add-more-prifile-for-cache-decoder-l.patch`

## Generate no nested version trace:

```shell
mkdir -p build && cd build
cmake -GNinja -DLV_USE_FREETYPE=ON ..
ninja -j8
../bin/main > ../bin/trace_no_nested.log
# then close the app
../lvgl/scripts/trace_filter.py ../bin/trace_no_nested.log ../bin/trace_no_nested.systrace
cd ..
```

## Generate nested version trace:

```shell
mkdir -p build && cd build
cmake -GNinja -DLV_USE_FREETYPE=ON -DCREATE_FILE_WRAPPERS=ON ..
ninja -j8
../bin/main > ../bin/trace_nested.log
# then close the app
../lvgl/scripts/trace_filter.py ../bin/trace_nested.log ../bin/trace_nested.systrace
cd ..
```

### Note:

If you don't want to generate by your self, here are generated log I used before.

[traces.zip](https://github.com/lvgl/lvgl/files/14636049/traces.zip)

## Use perfetto to visualize traces

Open https://ui.perfetto.dev/

Drag the trace file to the web to see the results.

No nested:

0 ms 150 us

<img width="1581" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/eb096e4a-0f03-406f-ad13-8df66c85e0e5">

Nested:

10 ms 99 us

<img width="1584" alt="image" src="https://github.com/lvgl/lvgl/assets/24841247/005bfced-32a6-46a1-9073-00868fc55769">

## Summary

It can be seen that when nesting occurs, the time and complexity of the layout have increased by several orders of magnitude, and there should be a lot of optimization space here.

$$
\frac{10ms\ 99us}{0ms\ 150us}=67.33
$$

## My View

You can add cache to the size related to the self size event, and add more accurate flags to avoid repeated layout work.

cc @kisvegabor This is the test case we mentioned at the meeting.

**Comment by kisvegabor** [comment]
I've opened #5938. Let's continue there.
