### ISSUE TITLE
Build error when using v9.1.0 with SDL and 2 Buffers

### ISSUE THREAD

**Issue by Ka1mes** [kisvegabor/lvgl#5942]
### LVGL version

9.1.0

### What happened?

I am using LVGL with SDL on Windows and just ported to version 9.1.0. The project would initially not build due to a small error in the lv_sdl_window.c file. 
lvgl\src\drivers\sdl\lv_sdl_window.c:402:47: error: 'ver_res' undeclared (first use in this function)
  402 |         dsc->fb2 = realloc(dsc->fb2, stride * ver_res);

The fix is to change: 
#if LV_SDL_BUF_COUNT == 2
        dsc->fb2 = realloc(dsc->fb2, stride * ver_res);
        memset(dsc->fb2, 0x00, stride * ver_res);
#endif

 to:

#if LV_SDL_BUF_COUNT == 2
        dsc->fb2 = realloc(dsc->fb2, stride * disp->ver_res);
        memset(dsc->fb2, 0x00, stride * disp->ver_res);
#endif 

### How to reproduce?

Just try to build using SDL with 2 Buffers and Windows backend.

**Comment by C47D** [comment]
Hi, could you send a pull request with the fix?

**Comment by kisvegabor** [comment]
Not stale

**Comment by Ka1mes** [comment]
Merge request was approved
