### ISSUE TITLE
Missing include in esp_lvgl_port_disp

### ISSUE THREAD

**Issue by sidharth-458** [kisvegabor/lvgl#5976]
### LVGL version

v9.1.0

### What happened?

after trying to build my new project resulted in ESP_IDF_VERSION_VAL define showing errors.

### How to reproduce?

build esp_lvgl_port_disp.c .

**Comment by sidharth-458** [comment]
adding #include "esp_idf_version.h" in esp_lvgl_port_disp.c works perfectly

**Comment by kisvegabor** [comment]
I think this file is coming from [esp-bsp](https://github.com/espressif/esp-bsp).  @tore-espressif, @espzav  could you take a look at this issue?

**Comment by espzav** [comment]
Thank you for report this issue. I am working on some fixes and improvements in `esp_lvgl_port` now, I will add this into next release too.
