### ISSUE TITLE
lv_barcode Causing memory leakage

### ISSUE THREAD

**Issue by cfqdream** [kisvegabor/lvgl#5981]
### LVGL version

v9.0.0

### What happened?

// repeat run next programe,report：[Warn]  (11833.148, +123)        lv_draw_buf_create: No memory: 143x1, cf: 16, stride: 572, 572Byte,  lv_draw_buf.c:205
void lv_example_barcode_1(void)
{
        lv_obj_clean(lv_screen_active());
        lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
        lv_color_t fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

        lv_obj_t* barcode = lv_barcode_create(lv_screen_active());
        lv_obj_set_height(barcode, 50);
        lv_obj_center(barcode);

        /*Set color*/
        lv_barcode_set_dark_color(barcode, fg_color);
        lv_barcode_set_light_color(barcode, bg_color);

        /*Add a border with bg_color*/
        lv_obj_set_style_border_color(barcode, bg_color, 0);
        lv_obj_set_style_border_width(barcode, 5, 0);

        /*Set data*/
        lv_barcode_update(barcode, "1234567890123456");
}

**Comment by liamHowatt** [comment]
Thanks for the tip @cfqdream! There is a memory leak here. It's not caused by the barcode directly but the barcode does expose a bug in the image decoding logic. Here's the PR: #5990
