### ISSUE TITLE
perf_update_timer_cb break!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#5992]
### LVGL version

9.0.0

### What happened?

when i run the example in windows, then close the frame, it break,because the disp_refr_timer is NULL:
as:
![图片](https://github.com/lvgl/lvgl/assets/40679769/dee1657f-fbe0-4f44-b546-da4c854aaf1e)

![图片](https://github.com/lvgl/lvgl/assets/40679769/4a7e7892-cfdd-4e80-98ea-f140ff96f267)

**Comment by kisvegabor** [comment]
Is it an issue with the latest master too?

**Comment by kisvegabor** [comment]
It should be resolved in https://github.com/lvgl/lvgl/pull/6073

**Comment by kisvegabor** [comment]
#6073 is merged so closing this issue.
