### ISSUE TITLE
Double and triple click support

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#6020]
### Problem to solve

Continue #5351.
The users get used to the double and triple click as they are commonly used on PC. 

### Success criteria

1. Double and triple click are are recognized by LVGL internally. 
2. It works for all input device type

### Solution outline

In `lv_indev.c` a generic method can be implemented to handle press, click, release, short click, long press, long press repeat, double click and triple click. This method can be applied to all input devices. 

### Rabbit holes

Nothing for now.

### Testing

Once it's implemented deep testing shall be added for all detected "gestures" and input device types.

### Teaching

Update the docs.

### Considerations

I proposed to support complex cases like the second press after a click, or the long press after a double click, but thinking about it more I think they are not common, so we shouldn't focus on them.

**Comment by AllanOricil** [comment]
I'm trying to implement this myself in lvgl 8. When are you guys thinking about releasing it? I need double touch for turning on and off my CYD.  Will this be backported to v8?

**Comment by kisvegabor** [comment]
cc @niklasf do have an estimate about when you can finish the Pull Request?

**Comment by niklasf** [comment]
Probably in the next few weeks. In the meantime, it's completely fine if someone else wants to take over or start a new patch.

**Comment by AllanOricil** [comment]
@niklasf cool! So I will wait you to finish it! 
Im going to use it in this project 

https://github.com/AllanOricil/esp32-mfa-authenticator

Screen will turn off with double touching, and on with single touch.

**Comment by AllanOricil** [comment]
I ended up implementing my own double touch solution using the input callback. Is working pretty well. 

https://github.com/AllanOricil/esp32-mfa-authenticator/pull/18/files

**Comment by AllanOricil** [comment]
I have simplified a bit the double and single touch solution I created before

https://github.com/AllanOricil/esp32-mfa-authenticator/blob/d1ca27a9d234f6551dea1f0d9edb259e4e260357/src/touch.cpp#L179-L227

**Comment by kisvegabor** [comment]
Cool! Could you send a PR to see the changes?
