### ISSUE TITLE
Moving wallpaper test from benchmark wrong coordinates

### ISSUE THREAD

**Issue by anaGrad** [kisvegabor/lvgl#6025]
### LVGL version

v9.1.0

### What happened?

During testing we found that the area that is saved in the draw task for the moving wallpaper test is the area of just the image and not the area of the whole rectangle on which the image should be placed. 
![image](https://github.com/lvgl/lvgl/assets/146175511/35c177e0-c77e-443a-917b-a07e59205075)

**Comment by nicusorcitu** [comment]
Given that, the VGLite will wrongly draw the image only to the specified area 0,0 99,99.
For this particular case with the tile image on the full screen, the t->coords should have been the full screen.
Can this be fixed upstream? Thanks.

**Comment by nicusorcitu** [comment]
@cristian-stoica

**Comment by kisvegabor** [comment]
Thank you reporting it. It also explains an anomaly that we have just discovered with multi core rendering. 

I've added a fix in #6029.

**Comment by anaGrad** [comment]
Thank you for the fix, it works perfectly.
