### ISSUE TITLE
Clarification OSAL Support (FreeRTOS, Windows, pthread ...)

### ISSUE THREAD

**Issue by mr-sven** [kisvegabor/lvgl#6039]
### Introduce the problem

I'm working on issue https://github.com/lvgl/lvgl/issues/5515 and it's unclear what the effort of this is.
My expectation was when using `#define LV_USE_OS LV_OS_FREERTOS`, I don't have to call `lv_timer_handler()` because there is already a thread/task for drawing.

### Proposal

Better documentation for what the `LV_USE_OS` flag is. 
Does it make LVGL threadsafe? 
Do I need to call `lv_task_handler`?
If yes, do I need a mutex for it?

**Comment by kisvegabor** [comment]
Thank you for bringing this up. It really needs a better documentation. [This page](https://docs.lvgl.io/master/porting/os.html) could be a good place for the additions.


> Better documentation for what the LV_USE_OS flag is.

It enables the `lv_mutex/thread/signal_*()` functions. They are used during rendering to make LVGL yield the rendering task while it's waiting for a GPU or flushing.  `LV_USE_OS` is also required for som GPU and for multi-core software rendering (each core has its own thread). 

> Does it make LVGL threadsafe?

No, it doesn't. 

> Do I need to call lv_task_handler?

Yes, you can do it anywhere and anyhow you want, but typically it's called in a task

> If yes, do I need a mutex for it?

You need a mutex only if you call `lv_*` functions from an other thread too.

**Comment by mr-sven** [comment]
I now pointed out the issue on https://github.com/lvgl/lvgl/issues/5515, but I don't know if this is the right approach to fix it.

**Comment by kisvegabor** [comment]
> I now pointed out the issue on https://github.com/lvgl/lvgl/issues/5515, but I don't know if this is the right approach to fix it.

Probably I'm missing something but can't see how #5515 is related to this.
