### ISSUE TITLE
Montserrat 10 is missing in the LVGL default title font list in menuconfig

### ISSUE THREAD

**Issue by tnqzh123** [kisvegabor/lvgl#6057]
### LVGL version

9.1.0

### What happened?

I'm using LVGL on ESP32-S3. I've noticed that LVGL have a built-in Montserrat 10 font, but it isn't in the default title font list in menuconfig, while all other fonts are in the list.

![image](https://github.com/espressif/esp-bsp/assets/16630630/93fdb7c1-24d5-4e7e-9dbb-191a15d2e4cf)
![image](https://github.com/espressif/esp-bsp/assets/16630630/f5eaf0ad-2bb8-487e-83bc-cfbfb5374e8e)

I found `LV_FONT_DEFAULT_MONTSERRAT_10` is missing in the `LV_FONT_DEFAULT` choice in Kconfig file:

https://github.com/lvgl/lvgl/blob/4d0c02982758304fa39d9b4ddc4be0dc991ed00f/Kconfig#L688-L700

and `CONFIG_LV_FONT_DEFAULT_MONTSERRAT_10` is still in src/lvgl_conf_kconfig.h: 

https://github.com/lvgl/lvgl/blob/4d0c02982758304fa39d9b4ddc4be0dc991ed00f/src/lv_conf_kconfig.h#L146-L154

After adding `LV_FONT_DEFAULT_MONTSERRAT_10` to the Kconfig file, it appeared in the menuconfig, and working well.

![image](https://github.com/lvgl/lvgl/assets/16630630/da031291-ee1f-4fbc-b02f-1102c3357ff1)

**Comment by liamHowatt** [comment]
Thanks @tnqzh123, do you feel like opening a PR for it?

**Comment by tnqzh123** [comment]
> Thanks @tnqzh123, do you feel like opening a PR for it?

@liamHowatt Of course sure. #6058

**Comment by liamHowatt** [comment]
Thanks!
