### ISSUE TITLE
Missing header file lfs.h

### ISSUE THREAD

**Issue by mgaman** [kisvegabor/lvgl#6076]
### LVGL version

v9.1.0

### What happened?

Environment VS Code/platformIO
In lv_conf.h enable LV_USE_FS_LITTLEFS and set the drive letter.
Compillation fails 
.pio/libdeps/esp32-s3-devkitc-1/lvgl/src/libs/fsdrv/lv_fs_littlefs.c:4:10: fatal error: lfs.h: No such file or directory

### How to reproduce?

#define LV_USE_FS_LITTLEFS 1
#if LV_USE_FS_LITTLEFS
    #define LV_FS_LITTLEFS_LETTER 'A'     /*Set an upper cased letter on which the drive will accessible (e.g. 'A')*/
#endif

**Comment by liamHowatt** [comment]
The current way to use LittleFS with LVLG is to download the LittleFS source code separately, configure it, and add it to your build configuration for your LVGL application.

LittleFS GitHub repo: https://github.com/littlefs-project/littlefs

Context: https://github.com/lvgl/lvgl/pull/5562#discussion_r1476262770
