### ISSUE TITLE
lv_label_set_text_fmt formats certain doubles wrong

### ISSUE THREAD

**Issue by fpvkiwi** [kisvegabor/lvgl#6091]
### LVGL version

v8.3.11

### What happened?

Using lv_label_set_text_fmt to format a double gives wrong text.

Code:

```double x = 1.95;
lv_label_set_text_fmt(label, "%.1f", x);
Serial.printf("Text: \"%s\"\n", lv_label_get_text(label));
```

Output:

```Text: "00000000000000000000000000000010"```

Expected:

```Text: "1.9"```

The regular printf shows the expected behavior:

```Serial.printf("printf %%lf: \"%lf\"\n", x);
Serial.printf("printf %%f: \"%f\"\n", x);
Serial.printf("printf %%.1f: \"%.1f\"\n", x);
```

Output:

```printf %lf: "1.950000"
printf %f: "1.950000"
printf %.1f: "1.9"
```

Converting 1.95 to a float before calling lv_label_set_text_fmt() does work.
However, printf should convert all floats to doubles anyway, according to https://stackoverflow.com/a/4264154

### How to reproduce?

```double x = 1.95;
lv_label_set_text_fmt(label, "%.1f", x);
Serial.printf("Text: \"%s\"\n", lv_label_get_text(label));
```

**Comment by kisvegabor** [comment]
Hey,

By default LVGL uses [it's builtin printf library](https://github.com/lvgl/lvgl/blob/master/src/stdlib/builtin/lv_sprintf_builtin.c). I just took quick look and it seems there are some `double` conversations there. 

Can you look into it with a debugger to see where the issue happens?
