### ISSUE TITLE
In the master branch, sliding the interface on the edge will cause lvgl to get stuck and cannot be operated anymore

### ISSUE THREAD

**Issue by huenrong** [kisvegabor/lvgl#6098]
### LVGL version

master branch

### What happened?

In the master branch, use `lv_demo_widgets()`, and it will get stuck when sliding on the edge, just like in the video

https://github.com/lvgl/lvgl/assets/47348530/e00c21af-e2de-4b5d-8649-6939dec97db0

**Comment by IAMMX** [comment]
This problem is caused by # 5979, it should be reversed for this PR

**Comment by kisvegabor** [comment]
Thank you for the report. It should be fixed by https://github.com/lvgl/lvgl/pull/6109
