### ISSUE TITLE
Add back CONFIG_LV_COLOR_16_SWAP

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#6104]
### Introduce the problem

While migrating all existing project using lvgl on Nuttx, https://github.com/apache/nuttx/pull/11780, many configurations have enabled CONFIG_LV_COLOR_16_SWAP. It may be a common issue others will face too.

```bash
nuttx/boards/risc-v/esp32c3-legacy/esp32c3-devkit/configs/lvgl/defconfig:38:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/esp32-2432S028/configs/lvgl/defconfig:39:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/esp32-wrover-kit/configs/lvgl/defconfig:44:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s2/esp32s2-kaluga-1/configs/lvgl_ili9341/defconfig:42:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s2/esp32s2-kaluga-1/configs/lvgl_st7789/defconfig:44:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s3/esp32s3-box/configs/lvgl-3/defconfig:56:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s3/esp32s3-box/configs/lvgl/defconfig:59:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/ttgo_t_display_esp32/configs/lvgl_lcd/defconfig:45:CONFIG_LV_COLOR_16_SWAP=y
nuttx/defconfig:39:CONFIG_LV_COLOR_16_SWAP=y
```

### Proposal

Add equivalent configuration option `CONFIG_LV_COLOR_16_SW_SWAP` that does the swap by software just before `flush_cb` by calling `lv_draw_sw_rgb565_swap`.

Update existing configuration to use `CONFIG_LV_COLOR_16_SW_SWAP` instead.

**Comment by XuNeo** [comment]
Mainly for backward compatibility. Without `CONFIG_LV_COLOR_16_SW_SWAP `, those listed configurations will be break in lvgl v9 and it's tough for me to upgrade all LCD drivers to support hardware swap.

**Comment by kisvegabor** [comment]
Makes sense, can you prepare a PR?

**Comment by FASTSHIFT** [comment]
If the LCD driver does not support the endian setting, the SPI can be switched to Bit Order set to MSB FIRST+16bit mode when sending the image buffer with DMA, and then switched to 8bit mode after sending, so that the code is simple and efficient. 
I believe most MCUs can support this mode.

See:
![65794137df908305e3d853e35e97324](https://github.com/lvgl/lvgl/assets/26767803/6c3e01f2-0872-477c-b0e6-042c6ee1e80f)

![MVIMG_20240429_000014](https://github.com/lvgl/lvgl/assets/26767803/66cd6419-ac52-4a8a-b456-5a0567d2c3e3)

**Comment by XuNeo** [comment]
Nice work.

Calling `lv_draw_sw_rgb565_swap` also has limitation. It performs byte order swap in place, thus needs to swap back before drawing next frame.

**Comment by kisvegabor** [comment]
> It performs byte order swap in place, thus needs to swap back before drawing next frame.

Why? The buffer into which the UI drawn is dropped after sending the image. Or do you use LVGL in direct mode?

**Comment by XuNeo** [comment]
Yes, we have to consider direct mode too.

**Comment by kisvegabor** [comment]
In this case we should swap the bytes only on a given area. Adding `lv_draw_sw_rgb565_swap_area` can be useful.
