### ISSUE TITLE
Progress bar is rendering incorrectly.

### ISSUE THREAD

**Issue by icyqwq** [kisvegabor/lvgl#6107]
### LVGL version

v9.1.0

### What happened?

<img width="445" alt="9f4ca00d6a07c7d6eb301bfd8ff721e1" src="https://github.com/lvgl/lvgl/assets/24635694/b1d97882-97d6-411a-8667-08f2be6f1131">

When using the code below to update the progress bar value, the rendering seems to be misaligned.

```
lv_obj_t *bar1;
void lv_example_bar_1(void)
{
    bar1 = lv_bar_create(lv_screen_active());
    lv_obj_set_size(bar1, 200, 20);
    lv_obj_center(bar1);
    lv_bar_set_value(bar1, 70, LV_ANIM_OFF);
}

int main()
{
    lv_example_bar_1();

    while (1) {
        for (int i = 0; i < 10; i++) {
            lv_bar_set_value(bar1, i*10, LV_ANIM_OFF);
            vTaskDelay(1500);
        }
    }

    return 0;
}
```

Since my screen doesn't support rotation, I used `lv_draw_sw_rotate` to rotate the content being drawn. The rendering mode is double-buffered using `LV_DISPLAY_RENDER_MODE_PARTIAL`.

If I add `lv_obj_invalidate(lv_scr_act());` to force a full-screen redraw after setting the value like this:
```
for (int i = 0; i < 10; i++) {
    lv_bar_set_value(bar1, i*10, LV_ANIM_OFF);
    lv_obj_invalidate(lv_scr_act());
    vTaskDelay(1500);
}
```
The bug is gone. So I guess this issue should be related to parital rendering with rotation?

**Comment by icyqwq** [comment]
Im trying to draw a progress bar using canvas, but I ended up with same results.
Here's my code.

```
template<typename Derived>
class BaseWidget
{
protected:
    int32_t _w, _h;
    lv_draw_buf_t *_draw_buf;
    lv_obj_t * _canvas;
    lv_layer_t _layer;
    lv_draw_rect_dsc_t _dsc_bg;

public:
    BaseWidget(lv_obj_t *parent, int32_t w, int32_t h)
    {
        _w = w;
        _h = h;

        _draw_buf = lv_draw_buf_create(w, h, LV_COLOR_FORMAT_RGB888, 0);

        _canvas = lv_canvas_create(parent);
        lv_canvas_set_draw_buf(_canvas, _draw_buf);
        
        lv_canvas_init_layer(_canvas, &_layer);
        lv_draw_rect_dsc_init(&_dsc_bg);
        _dsc_bg.radius = 8;
    }

    virtual ~BaseWidget() {}

    inline lv_obj_t *getCanvas()
    {
        return _canvas;
    }
    
    inline Derived& setBgColor(lv_color_t color, lv_opa_t opa)
    {
        _dsc_bg.bg_color = color;
        _dsc_bg.bg_opa = opa;

        return static_cast<Derived&>(*this);
    }

    inline Derived& clearBg()
    {
        lv_area_t coordsbg = {0, 0, _w, _h};
		lv_draw_rect(&_layer, &_dsc_bg, &coordsbg);

        return static_cast<Derived&>(*this);
    }
};


class ProgressBarWidget : public BaseWidget<ProgressBarWidget>
{
private:
    int32_t _min, _max, _range, _value; 
    lv_draw_rect_dsc_t _dsc;

public:
    ProgressBarWidget(lv_obj_t *parent, int32_t w, int32_t h) : BaseWidget(parent, w, h)
    {
        lv_draw_rect_dsc_init(&_dsc);
        _dsc.radius = 8;
    }

    ~ProgressBarWidget() {}

    inline ProgressBarWidget& setIndicatorColor(lv_color_t color, lv_opa_t opa)
    {
        _dsc.bg_color = color;
        _dsc.bg_opa = opa;
        return *this;
    }

    inline ProgressBarWidget& setRange(int min, int max)
    {
        _min = min;
        _max = max;
        _range = _max - _min;
        return *this;
    }

    inline ProgressBarWidget& setValue(int value)
    {
		_value = value;
        if (value < _min) {
            value = _min;
        }
        else if (value > _max) {
            value = _max;
        }
        int px = ((value - _min) / (float)_range) * _w;
        lv_area_t coords = {0, 0, px, 50};
        clearBg();
        lv_draw_rect(&_layer, &_dsc, &coords);

        lv_canvas_finish_layer(_canvas, &_layer);
        lv_obj_invalidate(_canvas);

        return *this;
    }

	inline ProgressBarWidget& setValueAnim(int value, int duration=800)
	{
		lv_anim_t a;
		lv_anim_init(&a);
		lv_anim_set_exec_cb(&a, [](void *obj, int32_t v) {
			ProgressBarWidget *self = static_cast<ProgressBarWidget*>(obj);
			self->setValue(v);
		});
		lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
		lv_anim_set_duration(&a, duration);
		lv_anim_set_var(&a, this);
		lv_anim_set_values(&a, _value, value);
		lv_anim_set_repeat_count(&a, 0);
		lv_anim_start(&a);

		return *this;
	}
};

ProgressBarWidget *pb = new ProgressBarWidget(lv_screen_active(), 200, 20);
    pb->setBgColor(lv_color_make(0x00, 0x00, 0x00), LV_OPA_COVER)
        .setIndicatorColor(lv_color_make(0x00, 0x00, 0xFF), LV_OPA_COVER)
        .setRange(0, 100)
        .setValue(50);

```

**Comment by icyqwq** [comment]
I print out the refresh window at `disp_flush()`:
```
printf("flush: %d %d %d %d\n", area->x1, area->y1, area->x2, area->y2);
```
And I got:
```
refresh: 0 0 201 21
```
The size of the canvas is 200x20, but the actual refresh area is xs:0, ys:0, xe:20, ye:200. I believe the correct window should be xs:0, ys:0, xe:19, ye:199.

**Comment by icyqwq** [comment]
Interestingly, If I set the size to 200x19, the rendering result is correct. And I failed to reporduce this bug on another panel. So I reckon this issue might be due to this panel not supporting of odd coordinates, I'll do more test about this.

**Comment by icyqwq** [comment]
> I print out the refresh window at `disp_flush()`:
> 
> ```
> printf("flush: %d %d %d %d\n", area->x1, area->y1, area->x2, area->y2);
> ```
> 
> And I got:
> 
> ```
> refresh: 0 0 200 20
> ```
> 
> The size of the canvas is 200x20, but the actual refresh area is xs:0, ys:0, xe:200, ye:20. I believe the correct window should be xs:0, ys:0, xe:199, ye:19.

Oh, I still want to find the answer to this problem.

**Comment by kisvegabor** [comment]
Some display controllers require the x/y coordinates of the window area to be even or odd. Please check it in the data sheet. 

If really this is the case you can add an event to the display like this, and adjust the coordinates as needed:
```c

static void event_cb(lv_event_t * e)
{
	lv_area_t * a = lv_event_get_param(e);
	/*Modify the area to be invalidated*/
	a->x1 = a->x1 & (~0&1); /*Make x1 even*/
}

 lv_display_add_event_cb(disp, event_cb, LV_EVENT_INVALIDATE_AREA, NULL);
```

**Comment by icyqwq** [comment]
> Some display controllers require the x/y coordinates of the window area to be even or odd. Please check it in the data sheet.
> 
> If really this is the case you can add an event to the display like this, and adjust the coordinates as needed:
> 
> ```c
> static void event_cb(lv_event_t * e)
> {
> 	lv_area_t * a = lv_event_get_param(e);
> 	/*Modify the area to be invalidated*/
> 	a->x1 = a->x1 & (~0&1); /*Make x1 even*/
> }
> 
>  lv_display_add_event_cb(disp, event_cb, LV_EVENT_INVALIDATE_AREA, NULL);
> ```

Thanks, I'll check that. And I wonder the answer about refresh window issue, shouldn't the window coordinates be x, y, w-1, h-1?
