### ISSUE TITLE
Incorrect Relative Path for Including lvgl.h in lv_rnd_unicodes.h

### ISSUE THREAD

**Issue by 1saeed** [kisvegabor/lvgl#6117]
### LVGL version

v9.1

### What happened?

Environment:

Operating System: Linux
Library Version: V9.1

Description:
The file `lv_rnd_unicodes.h` incorrectly uses a relative path to include the `lvgl.h` header file. The current include statement #include "`../lvgl.h`" fails because `lvgl.h` is not located in the specified path. This could lead to compilation errors when the header is included in projects.

### How to reproduce?

Steps to Reproduce:

Set up a project including the LVGL library.
Attempt to include` lv_rnd_unicodes.h` in any source file.
Compile the project.
Observe the compilation error related to the missing `lvgl.h` file.
Proposed Fix:
Change the include statement from:

`#include "../lvgl.h"`
to an absolute path based on the typical project structure:

`#include "lvgl/lvgl.h"`
Impact:
This change would prevent compilation errors and improve the usability of the library in diverse project setups.

**Comment by kisvegabor** [comment]
Hi,

Thank you for reporting it! I've fixed it here: #6141


`#if LV_BUILD_TEST` was also missing and that was why this file interacted with normal builds.
