### ISSUE TITLE
The coordinates of the screen and the cursor do not match

### ISSUE THREAD

**Issue by iSetebos** [kisvegabor/lvgl#6132]
### LVGL version

v 8.4

### What happened?

I have a 1920*1080 display. There was a problem with the X-coordinate cursor. It seems that when the cursor is displayed, its X-coordinate is divided somewhere by 4. If the driver sees the position of 1920 along the course, it finds it on 1/4 of the screen. At the same time, the screen below it is not redrawn correctly.

**Comment by kisvegabor** [comment]
> the screen below it is not redrawn correctly.

Can you send a screenshot about the issue?

Do you use `disp_drv.full_refresh = 1` or partial efreshing?

Does other parts of the UI work correctly? E.e. if you press a button, is it rendered correctly?
