### ISSUE TITLE
Keyboard keys are colored differently

### ISSUE THREAD

**Issue by blackchen-1** [kisvegabor/lvgl#6137]
### Introduce the problem

Can you make the keyboard keys uniform in color? Now some keys are white and some are gray
![keyboard](https://github.com/lvgl/lvgl/assets/102461289/1dd2461a-6223-4919-848c-ddf2ae6fc51a)

**Comment by kisvegabor** [comment]
By default the control keys are grey. It's inspired by smartphone keyboards. Like this:
![image](https://github.com/lvgl/lvgl/assets/7599318/606aa3b1-3d46-46c1-86ba-b7f8d7ae8fa3)

You can remove the grey "state" by adding this:
```c
lv_buttonmatrix_clear_button_ctrl_all(kb, LV_BUTTONMATRIX_CTRL_CHECKED);
```

**Comment by blackchen-1** [comment]
If you switch modes, the color difference changes back. How to solve this problem. Make a judgment to switch modes. Didn't toggle to add lv_buttonmatrix_clear_button_ctrl_all at once?

**Comment by kisvegabor** [comment]
Ah, that's true! In this case please add this: 
```c
lv_obj_set_style_bg_color(kb, lv_color_white(), LV_PART_ITEMS | LV_STATE_CHECKED);
```
