### ISSUE TITLE
carousel widget is missing, how to replace?

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6139]
### LVGL version

v9.1.1

### What happened?

in v8.3 have the lv_carousel_get_element_act function, but missing in v9， how to replace or get the carousel in v9?

**Comment by kisvegabor** [comment]
There as no `lv_carousel` in v8 either. Which widget do you mean?

**Comment by ZhouKes** [comment]
I think your code is generated by NXP GUI Guider, the widgets 'carousel' is in NXP's LVGI Library, not in original LVGL; 
You can copy it to your projects. It's in \lvgl\src\extra\widgets\carousel

**Comment by kisvegabor** [comment]
GuiGuider is not maintained by us but by NXP, so I can't comment on it. :slightly_frowning_face: 

(cc @nicusorcitu)

**Comment by nicusorcitu** [comment]
Please address this question to NXP GG community:
https://community.nxp.com/t5/GUI-Guider/bd-p/GUI-Guider

**Comment by nicusorcitu** [comment]
Please ask NXP Gui Guider team about the widgets, the best way to contact them is via NXP community:
https://community.nxp.com/t5/GUI-Guider/bd-p/GUI-Guider

**Comment by nicusorcitu** [comment]
@cristian-stoica

**Comment by xinsuinizhuan** [comment]
> Please ask NXP Gui Guider team about the widgets, the best way to contact them is via NXP community: https://community.nxp.com/t5/GUI-Guider/bd-p/GUI-Guider

I think it is about how to add the custome widget problem? need to pay attention to what
