### ISSUE TITLE
Add RAW and RAW_ALPHA color format support in LVGLImage.py tool

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#6144]
Currently, the image converter tool does not support RAW and RAW_ALPHA color format. It's needed when we want to convert PNG image to a C array and load it directly from flash.

> 

However, something is not clear to me either. @Xuneo, can we use [LVGLImage.py](https://github.com/lvgl/lvgl/blob/master/scripts/LVGLImage.py) to create a raw image (e.g. PNG data as it is) as a C array with `lv_image_dsc_t`?

_Originally posted by @kisvegabor in https://github.com/lvgl/lv_web_emscripten/issues/23#issuecomment-2076723052_

**Comment by kisvegabor** [comment]
Thanks for opening this issue! 

As the new version of ThorVG requires premultipled images, I think we shall add an option for it too.
