### ISSUE TITLE
crashed when tabview slide release

### ISSUE THREAD

**Issue by turoksama** [kisvegabor/lvgl#6150]
### LVGL version

v9.1.1 dev

### What happened?

updated to v9.1.1 dev, a simple tabview drag will crashed the system, something bad happened in lv_obj_get_parent() something.

### How to reproduce?

	lv_obj_t *scr = lv_screen_active();
	lv_obj_t *tv = lv_tabview_create(scr);
	lv_tabview_add_tab(tv, "111111");
	lv_tabview_add_tab(tv, "222222");

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/6109 is merged, so closing this issue.
