### ISSUE TITLE
Problems using LV_OBJ_FLAG_SCROLL_ON_FOCUS

### ISSUE THREAD

**Issue by 36221768** [kisvegabor/lvgl#6153]
### Introduce the problem

problems using LV_OBJ_FLAG_SCROLL_ON_FOCUS, I'm trying to auto-scroll objects, but the flag doesn't seem to work: // Create a text area for logging
ui_text_area = lv_textarea_create(ui_pnlMain);
lv_obj_set_x(ui_text_area, 0);
lv_obj_set_y(ui_text_area, lv_pct(15));
lv_obj_set_width(ui_text_area, lv_pct(100));
lv_obj_set_height(ui_text_area, lv_pct(75));
lv_obj_set_align(ui_text_area, LV_ALIGN_TOP_LEFT);
// make object unclickable by input devices
lv_obj_clear_flag(ui_text_area, LV_OBJ_FLAG_CLICKABLE);
//
lv_obj_add_flag(ui_text_area, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_add_flag(ui_text_area, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

**Comment by kisvegabor** [comment]
Hi,

Exactly what is not working? Do you add the text area in a scrollable widget and click it or focus it in a group?
