### ISSUE TITLE
`lv_obj_set_property()` with selector

### ISSUE THREAD

**Issue by hyansuper** [kisvegabor/lvgl#6166]
### Introduce the problem

can I set property for different state/part with code described in https://docs.lvgl.io/master/others/obj_property.html#a-step-further.
for example, I want to specify PART_INDECATOR color property in the array, how to do it?

**Comment by hyansuper** [comment]
Oh, I think I figure it out:
```c
lv_property_t props[] = {
    { .id = LV_STYLE_BG_COLOR | LV_PART_INDICATOR, .color = (lv_color_t){.red = 0x11, .green = 0x22, .blue = 0x33}, },
}

LV_OBJ_SET_PROPERTY_ARRAY(obj, props);
```
This is really neat!

**Comment by hyansuper** [comment]
There's a small error:
[LV_PROPERTY_ID_BUILTIN_LAST](https://github.com/lvgl/lvgl/blob/67fad672e3711013c6d6fa45ac3ce0ab6867f7f4/src/core/lv_obj_property.h#L61) should be larger than [LV_PROPERTY_IMAGE_END](https://github.com/lvgl/lvgl/blob/67fad672e3711013c6d6fa45ac3ce0ab6867f7f4/src/widgets/image/lv_image.h#L98)

**Comment by kisvegabor** [comment]
Hi @hyansuper,

Thanks you for opening this issue.

> LV_STYLE_BG_COLOR | LV_PART_INDICATOR

I can't see in the code where/why it should work. See [here](https://github.com/lvgl/lvgl/blob/master/src/core/lv_obj_property.c#L61). 

@XuNeo Is the `set_property` feature still interesting for you? If so we can plan to finish it and make it more compete.

**Comment by hyansuper** [comment]
> LV_STYLE_BG_COLOR | LV_PART_INDICATOR

my mistake, that won't work😂

**Comment by XuNeo** [comment]
I have looked into the issue, and found out no easy solution. Let's discuss.
There are two main solutions.
1. add `selector` to  all property APIs. There could be requirement to specify `selector` in a const property array. Thus it may also required to add `selector` field in `lv_property_t`.
Note that `selector` is only used when id is style ID.
```c
typedef struct {
    lv_prop_id_t id;                /**< property ID, includes style ID(lv_style_prop_t) and widgets property ID.*/
    lv_style_selector_t selector;   /**< style selector, only used for when id is style ID*/
    union {
        int32_t num;                /**< Number integer number (opacity, enums, booleans or "normal" numbers)*/
        const void * ptr;           /**< Constant pointers  (font, cone text, etc)*/
        lv_color_t color;           /**< Colors*/
        lv_value_precise_t precise; /**< float or int for precise value*/
        lv_style_value_t _style;    /**< A place holder for style value which is same as property value.*/
    };
} lv_property_t;

lv_result_t lv_obj_set_property(lv_obj_t * obj, const lv_property_t * value, lv_style_selector_t selector);
lv_property_t lv_obj_get_property(lv_obj_t * obj, lv_prop_id_t id, lv_style_selector_t selector);

```
2. Remove style ID support from property API, `lv_obj_set_local_style_prop` can be used directly. Widget general properties and styles are two categories and they deserve two sets of API.
```c
lv_result_t lv_obj_set_property(lv_obj_t * obj, const lv_property_t * value);
void lv_obj_set_local_style_prop(lv_obj_t * obj, lv_style_prop_t prop, lv_style_value_t value,
                                 lv_style_selector_t selector);
```



I vote for 2, since mixing them looks really neat.

> Oh, I think I figure it out:
> 
> ```c
> lv_property_t props[] = {
>     { .id = LV_STYLE_BG_COLOR | LV_PART_INDICATOR, .color = (lv_color_t){.red = 0x11, .green = 0x22, .blue = 0x33}, },
> }
> 
> LV_OBJ_SET_PROPERTY_ARRAY(obj, props);
> ```
> 
> This is really neat!

**Comment by hyansuper** [comment]
> lv_property_t props[] = {
    { .id = LV_STYLE_BG_COLOR | LV_PART_INDICATOR, .color = (lv_color_t){.red = 0x11, .green = 0x22, .blue = 0x33}, },
}

Do you mean to make this usable?
I like this solution too, you already mixed data type into id by bitwise operation, we can also mix in selectors

**Comment by XuNeo** [comment]
> you already mixed data type into id by bitwise operation, we can also mix in selectors

The issue is that `selector` is 32bit long(state + part). So id alone is not enough.



> I am not sure, is `label_long_mode` considered a property or a style? to me it controls how label looks, just like label size.

It feels like style is a special property one widget can have. Widget can also have normal properties like label long mode etc.



> Do you mean to make this usable?

I mean that we should drop style prop ID support from API `lv_obj_set_property` and call `lv_obj_set_local_style_prop` (with some helpers) if you want to set a style value.

**Comment by hyansuper** [comment]
Hi @XuNeo , I hope you keep the property API that unifies style and properties.

It's ok if selectors can't be used. I can add 'LV_PROPERTY_BAR_INDICATOR_COLOR' if I need it. just like you did in [lv_image.c](https://github.com/lvgl/lvgl/blob/37cf3bb4e41a1713d437de1090b7b5e37dbd4728/src/widgets/image/lv_image.c#L34).

With lv_obj_set_property(), I can make my device swap UI easily by parsing a portable bin file that contains a list of property id-value pairs.

**Comment by XuNeo** [comment]
Not stale.

Hi @kisvegabor ,

What do you think of adding `selector ` filed to property struct and APIs?

**Comment by XuNeo** [comment]
> Hi @XuNeo , I hope you keep the property API that unifies style and properties.

Since style is a special property, how about change the value of property for style, to include state and part selectors?
```c
typedef struct {
    lv_prop_id_t id;
    union {
        int32_t num;                /**< Number integer number (opacity, enums, booleans or "normal" numbers)*/
        const void * ptr;           /**< Constant pointers  (font, cone text, etc)*/
        lv_color_t color;           /**< Colors*/
        lv_value_precise_t precise; /**< float or int for precise value*/
        struct {
            uint32_t selector;
            lv_style_value_t _style;
        } style;
    };
} lv_property_t;
```

The struct size will 4bytes longer of cause.

**Comment by hyansuper** [comment]
Sounds good to me😃

**Comment by hyansuper** [comment]
it seems the "31" in https://github.com/lvgl/lvgl/blob/70c562de16bb3a196c907ec99199e4824b18368c/src/core/lv_obj.h#L184 is a mistake @XuNeo

**Comment by XuNeo** [comment]
Shoot. I'm making same mistake in the new PR. https://github.com/lvgl/lvgl/pull/6537

I'll correct them. Thanks!

**Comment by hyansuper** [comment]
> There's a small error:
> 
> [LV_PROPERTY_ID_BUILTIN_LAST](https://github.com/lvgl/lvgl/blob/67fad672e3711013c6d6fa45ac3ce0ab6867f7f4/src/core/lv_obj_property.h#L61) should be larger than [LV_PROPERTY_IMAGE_END](https://github.com/lvgl/lvgl/blob/67fad672e3711013c6d6fa45ac3ce0ab6867f7f4/src/widgets/image/lv_image.h#L98)

Also this one @XuNeo

**Comment by XuNeo** [comment]
It's already changed to a large value on master:

https://github.com/lvgl/lvgl/blob/70c562de16bb3a196c907ec99199e4824b18368c/src/core/lv_obj_property.h#L67
