### ISSUE TITLE
Compilation error using VG-Lite

### ISSUE THREAD

**Issue by oleg-amp** [kisvegabor/lvgl#6173]
### LVGL version

v9.1

### What happened?

When I set LV_USE_DRAW_VGLITE in lv_conf.h I get compilation error: `lvgl-src/src/draw/nxp/vglite/lv_draw_vglite_label.c:172:15:error: 'vg_lite_int32_t' undeclared`
I can see that it is declared in vg_lite.h file located in vg_lite_tvg directory. 

Please elaborate how to compile the lvgl with vg_lite correctly. I did read all the related documentation. It does not explain well the required versions of lvgl <--> nxp SDK <--> vg_lite.

I use lvgl 9.1 with vg_lite took from nxp SDK 2.13.1 (vg_lite is version 2 there).

### How to reproduce?

`#define LV_USE_DRAW_VGLITE 1`

**Comment by kisvegabor** [comment]
@anaGrad @nicusorcitu 
Could you take a look at this issue?.

**Comment by josepho0918** [comment]
The same issue encountered.

**Comment by nicusorcitu** [comment]
@cristian-stoica

**Comment by nicusorcitu** [comment]
LVGL 9.1 works only with vglite 4.x

**Comment by oleg-amp** [comment]
Hmm, so how am I supposed to use vg-lite on NXP RT1176 with lvgl 9.1?
Are there any instructions to use/port vg-lite 4.x for NXP?
I tried to find the answer in https://github.com/lvgl/lvgl/issues/4813 couldn't get to the bottom of the line where to take code/examples from.

**Comment by nicusorcitu** [comment]
>> Hmm, so how am I supposed to use vg-lite on NXP RT1176 with lvgl 9.1?
>
You will need to wait for the SDK release 2.17.

**Comment by oleg-amp** [comment]
What if I roll-back lvgl to 8.x, how do I use vg-lite 3.x? Which NXP SDK has the 3.x vg-lite?

**Comment by nicusorcitu** [comment]
I would like to mention that SDK 2.13.1 that you are currently using already have vglite driver 3.0.15.

**Comment by oleg-amp** [comment]
Ok, I checked the version in vg_lite.h, but it appears I had to check the ChangeLogKSDK.txt file. In vg_lite.h file version 2 is defined, while ChangeLogKSDK.txt shows current version is 3.0.15_rev7.
Ok, thanks for you help. Closing this issue. I will open new issue related to drawing lines with vg-lite to present why lvgl 9 may come handy compared to lvgl 8.
