### ISSUE TITLE
LVGL Forum SPAMMER

### ISSUE THREAD

**Issue by PGNetHun** [kisvegabor/lvgl#6192]
### LVGL version

-

### What happened?

Hello!

Spammers appeared in LVGL forum, please BAN those ***:
https://forum.lvgl.io/u/Kumari
https://forum.lvgl.io/u/tfei_gsihs

![image](https://github.com/lvgl/lvgl/assets/25751703/e302cb22-03f6-4cce-bd07-5b6d5633a1af)

**Comment by PGNetHun** [comment]
Unfortunately scammers from India found LVGL forum (among other forums), and now they are bombing it with messages.
@kisvegabor , if you wish I can help deleting those topics/messages and banning those scammers, or if it's possible write a script that filters out those scam messages before being stored in forum database. (filter using regular expressions or simply checking for some keywords)

**Comment by kisvegabor** [comment]
Thank you for offering your help! Is it possible to write a custom script to Discourse?

I also added some filters and disabled google based login.

**Comment by kisvegabor** [comment]
They are still passing through...

Can you link some other forums where they are attacking?

**Comment by kisvegabor** [comment]
I have installed the [Akismet](https://akismet.com/) plugin. Hopefully it will make it.

**Comment by PGNetHun** [comment]
> I have installed the [Akismet](https://akismet.com/) plugin. Hopefully it will make it.

Since then there are no spam messages in forum.
Thx, I will close this ticket.

**Comment by kisvegabor** [comment]
Yeah, it seems it really solved it.
