### ISSUE TITLE
Mosaic 

### ISSUE THREAD

**Issue by iSetebos** [kisvegabor/lvgl#6202]
### Introduce the problem

In version 9, the mosaic for displaying the image is not available?

**Comment by liamHowatt** [comment]
Hi, can you try using `lv_image_set_inner_align(img, LV_IMAGE_ALIGN_TILE);` for your use case? I think tiling is the same as mosaic.

**Comment by kisvegabor** [comment]
Hi,

It's supported via `lv_image_set_inner_align(obj, LV_IMAGE_ALIGN_TILE);`

**Comment by iSetebos** [comment]
It helped. Thank you!!!
