### ISSUE TITLE
How to display Thai on the interface

### ISSUE THREAD

**Issue by jeremyvirtue** [kisvegabor/lvgl#6209]
### LVGL version

9.0.0

### What happened?

when Thai is displayed with consonants superimposed on vowels and tones, the tone cannot be fully displayed and will be mixed with vowels,They show left and right. How can I display it correctly?

**Comment by trivij** [comment]
use BlynkGO is the best!

**Comment by liamHowatt** [comment]
Thanks for the tip @trivij!

@jeremyvirtue, which font were you seeing the issues with?

cc @BlynkGo (they participate here sometimes)

Regarding BlynkGO, I tried this:
https://github.com/BlynkGO/BlynkGO_font/blob/master/Eng-Thai/ThaiSansNeue/ThaiSansNeue_Bold_25.c
and it looks correct at first sight but I am not familiar with the language.

![image](https://github.com/lvgl/lvgl/assets/30486941/36e021d1-0b26-4d4a-8ad9-d21aa6be41e5)

I simply downloaded the C file, added it to my build files, and made this change

```diff
diff --git a/../../Downloads/ThaiSansNeue_Bold_25.c b/../lvgl_workspace/ThaiSansNeue_Bold_25.c
index 49716e5b3..f3034a328 100644
--- a/../../Downloads/ThaiSansNeue_Bold_25.c
+++ b/../lvgl_workspace/ThaiSansNeue_Bold_25.c
@@ -4,7 +4,11 @@
  * Opts: --bpp 4 --size 25 --no-compress --font ThaiSansNeue-Bold_modified.ttf --range 32-126,161-255,3584-3675,8192-8805,63232-63632 --format lvgl -o ThaiSansNeue_Bold_25.c
  ******************************************************************************/
 
-#include "blynkgo_lib.h"
+#ifdef LV_LVGL_H_INCLUDE_SIMPLE
+    #include "lvgl.h"
+#else
+    #include "lvgl/lvgl.h"
+#endif
 
 #ifndef THAISANSNEUE_BOLD_25
 #define THAISANSNEUE_BOLD_25 1
```

And then used it like so:

```c
static void thai_font_blynkgo()
{
    LV_FONT_DECLARE(ThaiSansNeue_Bold_25);
    lv_obj_t * label = lv_label_create(lv_screen_active());
    lv_obj_set_style_text_font(label, &ThaiSansNeue_Bold_25, 0);
    lv_label_set_text(label, "วิธีการใช้งาน");
}
```

I also tried arluck_25.c but had a less satisfying result.

**Comment by jeremyvirtue** [comment]
> ```diff
> blynkgo_lib
> ```
I try to understand,But do you have to use BlynkGO OS for this solution?Can we try to isolate it?

**Comment by liamHowatt** [comment]
I didn't use BlynkGO OS. Please read my comment again :slightly_smiling_face: 

> I simply downloaded the C file, added it to my build files, and made this change

**Comment by LEKPCSTEAM** [comment]
ลองดูนะครับสำหรับแก้ไขสระลอย **ภาษาไทย** โดยเฉพาะใน .ttf  เมื่อแปลงเสร็จจะได้ .ttf ที่แก้ไขแล้ว รายละเอียดอยู่ใน repo ครับ 

Feel free to check this out—it's designed specifically for fixing **Thai** floating vowels in .ttf files. Once converted, you’ll get the patched .ttf file. All the details are in the repo. 

Before:

<img width="277" height="115" alt="Image" src="https://github.com/user-attachments/assets/72865f05-9eae-4d3a-9660-a33887164ce7" />

After:

<img width="269" height="110" alt="Image" src="https://github.com/user-attachments/assets/b5e3ab67-b554-42a7-8b0b-9331d8b2cbec" />

Repo:
[https://github.com/LEKPCSTEAM/LVGL-Thai-Font-Tool.git](
https://github.com/LEKPCSTEAM/LVGL-Thai-Font-Tool.git)
