### ISSUE TITLE
Recoloring in V9

### ISSUE THREAD

**Issue by andyrea76** [kisvegabor/lvgl#6210]
### Introduce the problem

removal of recolor feature in V9 and replacing with spans does not seem as useful as the recolor option

### Proposal

the original scheme to dynamically change the colour of text for simple popups or areas of a screen that maybe use symbol fonts where the text or highlight or order of symbols is variable, the ability to just format up a string to throw at the label text is very quick, simple and only means a single object reference to the label. 

i can see the new spans and so on has a much greater degree of flexibility than this but you have a lot more objects to create potentially dynamically as elements to highlight change 

surely the old scheme of recolouring by the text parsing A: was already there and working for many people and B: could still exist in parallel to also not break something else in the not entirely trivial migration from 8.x up to 9

**Comment by kisvegabor** [comment]
To keep this topic organized, let's discuss it in #6019.
