### ISSUE TITLE
have the C++ version image convert tool and font generate tool?

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6216]
### Introduce the problem

I want genetate the image by c++ in my project, not lvgl is c++ and image convert is python

**Comment by XuNeo** [comment]
You are very welcome to contribute a C++ version. It could be much faster than python version.
In the mean time, you may want to check the rust version image converter: https://lib.rs/crates/icu_tool

**Comment by kisvegabor** [comment]
I'm not sure officially it's worth maintaining a C++ converter too. 

What is your use case for the C++ converter?

**Comment by xinsuinizhuan** [comment]
My project is C++， and i want add a picture, then auto convert to a binary file, so my project need add the python code, and configuration python enviroment. If the lvgl is python code, the converter tool also is python, but the lvgl i c++, the the tool is python, is't discordant.

**Comment by xinsuinizhuan** [comment]
also font generate tools, with c++

**Comment by xinsuinizhuan** [comment]
Some one get the tool, but is for lvlg 8.0

**Comment by xinsuinizhuan** [comment]
but this image format how to match in lvlg 9.0?
 {{LV_IMG_CF_TRUE_COLOR, "LV_IMG_CF_TRUE_COLOR"},
                                                                     {LV_IMG_CF_TRUE_COLOR_ALPHA, "LV_IMG_CF_TRUE_COLOR_ALPHA"},
                                                                     {LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED, "LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED"},
                                                                     {LV_IMG_CF_INDEXED_1BIT, "LV_IMG_CF_INDEXED_1BIT"},
                                                                     {LV_IMG_CF_INDEXED_2BIT, "LV_IMG_CF_INDEXED_2BIT"},
                                                                     {LV_IMG_CF_INDEXED_4BIT, "LV_IMG_CF_INDEXED_4BIT"},
                                                                     {LV_IMG_CF_INDEXED_8BIT, "LV_IMG_CF_INDEXED_8BIT"},
                                                                     {LV_IMG_CF_ALPHA_1BIT, "LV_IMG_CF_ALPHA_1BIT"},
                                                                     {LV_IMG_CF_ALPHA_2BIT, "LV_IMG_CF_ALPHA_2BIT"},
                                                                     {LV_IMG_CF_ALPHA_4BIT, "LV_IMG_CF_ALPHA_4BIT"},
                                                                     {LV_IMG_CF_ALPHA_8BIT, "LV_IMG_CF_ALPHA_8BIT"},
                                                                    };

**Comment by kisvegabor** [comment]
```
LV_IMG_CF_INDEXED_1BIT -> LV_COLOR_FORMAT_I1
LV_IMG_CF_ALPHA_1BIT -> LV_COLOR_FORMAT_A1
LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED -> Removed
LV_IMG_CF_TRUE_COLOR -> LV_IMG_CF_TRUE_COLOR
LV_IMG_CF_TRUE_COLOR_ALPHA -> LV_COLOR_FORMAT_NATIVE_WITH_ALPHA
```

**Comment by xinsuinizhuan** [comment]
LV_IMG_CF_TRUE_COLOR -> LV_IMG_CF_TRUE_COLOR？ LV_IMG_CF_TRUE_COLOR is not exit in lvlg9?

Is this right?
LV_IMG_CF_TRUE_COLOR->LV_COLOR_FORMAT_RGB888
LV_IMG_CF_TRUE_COLOR_ALPHA->LV_COLOR_FORMAT_ARGB8888

**Comment by kisvegabor** [comment]
Sorry, copy paste issue. Yes, true color -> native.

**Comment by kisvegabor** [comment]
Closing as not planned.
