### ISSUE TITLE
Error: failed to map framebuffer device to memory: Invalid argument

### ISSUE THREAD

**Issue by whsqjss** [kisvegabor/lvgl#6227]
### LVGL version

v8.4.0

### What happened?

App run failed, which is build by lv_binding_js(cross plaltform compile), target os is architecture aarch64.
Here is error log:
![image](https://github.com/lvgl/lvgl/assets/35548533/658ea9d1-5402-4b6a-8455-66e47c5ca4a9)

**Comment by kisvegabor** [comment]
Please try with `sudo`.
