### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by stevenzhang2024** [kisvegabor/lvgl#6234]
### LVGL version

v9.1

### What happened?
the ltdc driver is ok.
![微信图片_20240517100147](https://github.com/lvgl/lvgl/assets/157681096/1bcbcecf-58e7-4ec9-b248-147d8b95e650)

When we port LVGL9.1. Display like this,is the config error or other problems?

![微信图片_20240517100418](https://github.com/lvgl/lvgl/assets/157681096/620d9187-7bb3-40d8-b165-b70eb13abc11)

### How to reproduce?

/*Color depth: 8 (A8), 16 (RGB565), 24 (RGB888), 32 (XRGB8888)*/
#define LV_COLOR_DEPTH 16
/*1: Enable system monitor component*/
#define LV_USE_SYSMON   1
#define LV_USE_OS   LV_OS_FREERTOS

**Comment by dennisye963** [comment]
It seems like you are missing color depth conversion, something like "convert_color_depth" function in lvgl/src/extra/libs/png/lv_png.c

**Comment by stevenzhang2024** [comment]
Oh ,no. The problem is stm32h7xx cache.  `SCB_EnableICache();SCB_EnableDCache();`
