### ISSUE TITLE
Change TileView Scroll animation speed

### ISSUE THREAD

**Issue by jgauchia** [kisvegabor/lvgl#6239]
### LVGL version

v9.1.0

### What happened?

As described in this [post](https://forum.lvgl.io/t/scroll-animation-speed-in-tile-view-widget/16361) scroll animation speed of a tileview is fixed by "define" constant in **lv_obj_scroll.c**

```
#define SCROLL_ANIM_TIME_MIN    200    /*ms*/
#define SCROLL_ANIM_TIME_MAX    400    /*ms*/
``` 

There are any "possibility" to add a public method or similar in order to change the scroll animation time?

Thank you!

**Comment by jgauchia** [comment]
> Hi,
> 
> You can do this to modify the scroll animation:
> ```c
> 
> void anim_start_event_cb(lv_event_t * e)
> {
> 	lv_anim_t * a = lv_event_get_param(e);
> 	if(a) a->duration = 2000;
> }
> 
> ...
> 
>     lv_obj_t * tv = lv_tileview_create(lv_screen_active());
>     lv_obj_add_event_cb(tv, anim_start_event_cb, LV_EVENT_SCROLL_BEGIN, NULL);
> ```

Hi!

Thank you!

**Comment by kisvegabor** [comment]
You are welcome! 

I'm closing this issue.
