### ISSUE TITLE
Could provide a font convert tool by c++？

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6260]
### Introduce the problem

The image and font convert is need, but have no code by C++， i must convert them by other language code. Some one provide the convert tool, but they fit the old version lvlg，in newest lvgl version could not use. So suggest to provide the conver tool as a model part by lvlg

**Comment by kisvegabor** [comment]
It's not ion the roadmap to add C++ converters, but please describe your use case to see 
1. is there is an alternative solution
2. if it could be useful for others too

**Comment by kisvegabor** [comment]
Closing as not planned.
