### ISSUE TITLE
Linux DRM display mode locks up by default due to missing lv_tick_set_cb

### ISSUE THREAD

**Issue by falkTX** [kisvegabor/lvgl#6266]
### LVGL version

v9.1.0-182

### What happened?

When testing different Linux display drivers I noticed that the legacy framebuffer one was working, but the DRM/KMS got stuck and didn't render anything besides the initial screen.

Issue seems to be the `lv_tick_set_cb` call being present on the legacy framebuffer option, but not on the DRM/KMS one.
Issue is not present if that call is done by the user.

For consistency both should have the tick call, or maybe neither..?

**Comment by kisvegabor** [comment]
Thanks!

Should be fixed in https://github.com/lvgl/lvgl/pull/6306
