### ISSUE TITLE
Buggy Demos in 9.x

### ISSUE THREAD

**Issue by alexriegler12** [kisvegabor/lvgl#6270]
### LVGL version

9.x

### What happened?

Some Demos on the documentation website don't work anymore or have glitches, for examples:
"add fade mask to roller" just displays a white screen
The scale demo with two gauges allows to move the needle of the right gauge that uses an image as needle like it was scrollable. This doesn't seem to be right.

**Comment by kisvegabor** [comment]
Hi,

I've fixed the roller example here: https://github.com/lvgl/lvgl/pull/6307

Do you mean this scale example?
![image](https://github.com/lvgl/lvgl/assets/7599318/176d7f4d-5117-4c50-b371-d1ff165089ed)

If so, it looks good to me.

**Comment by alexriegler12** [comment]
the needle of the right scale can be moved by scrolling to the left or right. this doesn't seem right.

**Comment by liamHowatt** [comment]
Good catch. The needle on the second scale is horizontally scrollable. You can drag the needle left and right. PR open: #6320
