### ISSUE TITLE
Problem with lv_demo_widgets demo(Instrument panel) after porting code to hardware

### ISSUE THREAD

**Issue by ZLXT** [kisvegabor/lvgl#6300]
### LVGL version

8.3.3

### What happened?

Hi.
When I ported LVGL to zynq7020, there was an issue with the lv_demo_widgets demo. The dashboard screen refresh is incorrect. I don't know what problem caused this.
When not using LVGL, there is no problem drawing on the screen.
May I ask if anyone has encountered the same problem as me?

https://github.com/lvgl/lvgl/assets/23455922/d07d21cc-a5e7-4d5b-ad13-eb7f2b145b1c

https://github.com/lvgl/lvgl/assets/23455922/0817ed1b-0050-440e-a73f-9cd6b39dc1f0

**Comment by kisvegabor** [comment]
It looks like a caching issue. Please try invalidating the D cache in the `flush_cb`.
