### ISSUE TITLE
Button Matrix cannot be removed from lv_conf.h

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [kisvegabor/lvgl#6303]
### LVGL version

9..1

### What happened?

If you set `#define LV_USE_BUTTONMATRIX  0` it won't compile

### How to reproduce?

When you set `#define LV_USE_BUTTONMATRIX  0`
In the file lv_api_map_v8.h, this line makes it fail
`typedef lv_buttonmatrix_ctrl_t      lv_btnmatrix_ctrl_t;`

I think those typedefs need to be wrapped with #if, no?

**Comment by XuNeo** [comment]
Fixed in https://github.com/lvgl/lvgl/pull/6269, please try the latest code.
