### ISSUE TITLE
Tiny TTF should be caching stbtt_FindGlyphIndex

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [kisvegabor/lvgl#6305]
### LVGL version

9.1

### What happened?

TinyTTF currently does not cache the results of stbtt_FindGlyphIndex but it really really should, and should be using the cache in the font glyph desc retrieval callback. stbtt_FindGlyphIndex is probably the most expensive call in the lib outside of rendering.

I can't imagine the cache is incredibly effective right now.

**Comment by MacDragon** [comment]
I can confirm it really really hurts current performance, I've not had time to go back and try to do a 'real' cache implementation, but I quickly hacked a local one into our project and it increased performance well over an order of magnitude for a busy text screen. The quick hack I did was mentioned in one of the lvgl 9 closed cache threads the other day, and a suggestion was given to copy ideas from freetype implementatino to tiny ttf.

**Comment by codewitch-honey-crisis** [comment]
Thanks for you feedback. I'm the original contributor of this library which I adapted from some public domain code for game engines :), and I implemented the cache quickly as it was a requirement for LVGL. I need to do some legwork if I was to upgrade this code, because I do not yet fully understand the LVGL cache system yet. I learned just enough of it to be dangerous.

**Comment by MacDragon** [comment]
With the additional quick 'n dirty cacheing in place, it now works pretty well for us, difference in speed vs plain bitmap fonts is negligible now, at least in environment with plenty enough RAM to cache everything - I did also increase the max amount of elements allowed into the cache quite a bit, though I haven't tried to verify how much difference that made.

**Comment by codewitch-honey-crisis** [comment]
I appreciate this. It's all very helpful. I'll tinker with the caching once I solve some unrelated issues I'm having with the new LVGL 9+

**Comment by codewitch-honey-crisis** [comment]
@kisvegabor can I get some guidance on using the cache? I'm not clear on how the search key is used below:
```cpp
const lv_font_t * font = g_dsc->resolved_font;
tiny_ttf_cache_data_t search_key = {
    .font = (lv_font_t *)font,
    .unicode = unicode_letter,
    .size = font->line_height,
    //.glyph_index
    //.draw_buf
};```
I've added glyph_index. Like draw_buf it's to be fetched FROM the cache, not used to search for the data. Does that make sense? How does `lv_cache_acquire_or_create(tiny_ttf_cache, &search_key, (void *)font->dsc);` know to leave draw_buf out of the search criteria? I need the same for glyph_index.

**Comment by codewitch-honey-crisis** [comment]
I tried caching the glyph indices but it turns out the LVGL cache system is slower than stbtt_FindGlyphIndex. In any case, the latest bits are much faster than 9.1 release so I'm happy.

**Comment by W-Mai** [comment]
> I tried caching the glyph indices but it turns out the LVGL cache system is slower than stbtt_FindGlyphIndex. In any case, the latest bits are much faster than 9.1 release so I'm happy.

So, is there no longer a need to increase the cache?

But @MacDragon said that the performance has improved a lot.

**Comment by MacDragon** [comment]
My hack was entirely containing cache lookup to a small internally held table, no hash lookups - so I can't comment how much faster or slower it is compared to cache system lookup call, and would only probably be viable for a reasonably small latin like glyph set, the ttf fonts we're using have < 200 glyphs included after being stripped for size. But for at least one busy test screen, my whole lvgl rendering cycle appeared to go from 280ms to 8ms

**Comment by codewitch-honey-crisis** [comment]
@MacDragon which version of LVGL?

**Comment by codewitch-honey-crisis** [comment]
The latest bits in the master branch are much faster, in my experience. After looking at it, someone changed the cache code to eliminate the call to FindGlyphIndex inside the rendering routine. That improved performance pretty dramatically.

**Comment by MacDragon** [comment]
Interesting, preferences is generally to stick on a 'release' version, so haven't tried raw master branch.

**Comment by codewitch-honey-crisis** [comment]
I totally get it. I'm just putting it out there so you know once the next version is rolled out, those perf improvements have been made. :)

**Comment by MacDragon** [comment]
Good to know certainly, will bear in mind whenever next release is.

**Comment by codewitch-honey-crisis** [comment]
src/libs/tiny_ttf/tiny_ttf.c (give or take, it's from memory)

**Comment by W-Mai** [comment]
> src/libs/tiny_ttf/tiny_ttf.c (give or take, it's from memory)
> 
> I'm not sure it can be retrofitted to earlier versions, as I am half sure the generalized caching system has evolved since 9.1

OK fine

As far as the information I know now is concerned, tiny_ttf adds the cache generated by bitmap.

Generally speaking, what we are looking forward to is

1. unicode -> glyph_index
2. glyph_index -> bitmap

Two-level cache, but at present, there is only glyph_index -> bitmap cache now.

@MacDragon describes the addition of a glyph_index cache.

I don't seem to find this related cache.

By the way, it's I modified the cache of bitmap, so I'm quite concerned about this issue. 😁

**Comment by W-Mai** [comment]
TinyTTF currently does not cache the results of stbtt_FindGlyphIndex but it really really should, and should be using the cache in the font glyph desc retrieval callback. stbtt_FindGlyphIndex is probably the most expensive call in the lib outside of rendering.

I can't imagine the cache is incredibly effective right now.

**Comment by codewitch-honey-crisis** [comment]
There isn't a two level cache. The reason being is I tried implementing a two level cache using the generalized caching system. My tests found that stbtt_FindGlyphIndex is usually or always faster than a cache lookup. Now, when caching entire renders as bitmaps, it pays for itself, but just caching letters->glyph_indexes for a font does not.

It may be possible to do what MacDragon is doing and implement your own cache. I've decided not to do that after considering it because the renders are already quite quick now that the bitmap cache also caches the glyph_index, coupled with the fact that going "off book" and sidestepping LVGL's cache and its management infrastructure left a bad taste in my mouth. It would require at best, a whole separate set of config #defines just to hammer out how much cache to give it. And that's best case scenario, and not accounting for the added flash footprint, maintenance, and testing. It just doesn't seem worth it given current performance. Have you tried the latest branch?

**Comment by MacDragon** [comment]
Yes, I did note in my post in other thread about the hacky implementation that I wouldn't consider something like it for a pull either, it as mostly noting that there was maybe potential, but if how labels are rendered has changed it may be less necessary.

**Comment by codewitch-honey-crisis** [comment]
You know what would be interesting? If LVGL cached the actual metrics fetching call results instead of calling the metrics callback over and over. Caching the width, height and advance by unicode letter and font. I'd have to remove the set_font_size call in tiny ttf because it would break the cache, but in general it might sidestep this issue, and pay for itself. @kisvegabor , your thoughts on this?

**Comment by codewitch-honey-crisis** [comment]
freetype also takes gobs of ram. TinyTTF doesn't, which is kind of the point of it,

**Comment by codewitch-honey-crisis** [comment]
Did you even use the latest bits? I'm not putting in two-level cache.

**Comment by W-Mai** [comment]
> Did you even use the latest bits? I'm not putting in two-level cache.

I know that, that's what I wrote, the draw_buf cache, lying in the latest bits.

But I think we can add a new `unicode -> glyph_dsc` will speed up the process.

Please take a look at, here is the code what I'm mentioned 😁
- #6333
