### ISSUE TITLE
Line 11 of src/libs/tiny_ttf.c declared incorrectly

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [kisvegabor/lvgl#6308]
### LVGL version

9.0

### What happened?

All recent versions with Tiny TTF
Line 11 of the C file
```cpp
#if LV_USE_TINY_TTF
```
should be
```cpp
#if LV_USE_TINY_TTF != 0
```

I would fix it but I'm not set up to make a PR right now.

**Comment by kisvegabor** [comment]
I asked @W-Mai to fix it in an open PR.

**Comment by W-Mai** [comment]
> I asked @W-Mai to fix it in an open PR.

Done!
