### ISSUE TITLE
8.4/9.1 Hardware based display rotation input devices

### ISSUE THREAD

**Issue by faxe1008** [kisvegabor/lvgl#6312]
### LVGL version

v9.1, v8.4

### What happened?

The code that takes the input devices coordinates and translates them to the display rotation for any given rotation looks like it contains an error (Nearly identical on v8.4 and v9.1):
[https://github.com/lvgl/lvgl/blob/master/src/indev/lv_indev.c#L639](https://github.com/lvgl/lvgl/blob/master/src/indev/lv_indev.c#L639)

```
    lv_disp_t * disp = i->driver->disp;
    /*Save the raw points so they can be used again in _lv_indev_read*/
    i->proc.types.pointer.last_raw_point.x = data->point.x;
    i->proc.types.pointer.last_raw_point.y = data->point.y;

    if(disp->driver->rotated == LV_DISP_ROT_180 || disp->driver->rotated == LV_DISP_ROT_270) {
        data->point.x = disp->driver->hor_res - data->point.x - 1;
        data->point.y = disp->driver->ver_res - data->point.y - 1;
    }
    if(disp->driver->rotated == LV_DISP_ROT_90 || disp->driver->rotated == LV_DISP_ROT_270) {
        lv_coord_t tmp = data->point.y;
        data->point.y = data->point.x;
        data->point.x = disp->driver->ver_res - tmp - 1;
    }
```
Why do you subtract 1 from the coordinate?

**Comment by kisvegabor** [comment]
If e.g. `hor_res == 320` the valid range of coordinates is `0..319`. So when `x == 0`, it shall be `320 - 1 - 0 = 319`.

**Comment by faxe1008** [comment]
For the making sure that the point is within the valid range this makes sense, but not for the case where the rotated points still live in the bounds of the display.

Example:
```
display_width = 320
display_height = 240

x = 25
y = 45

will yield the point (194, 25)
```
This looks odd to me. Also if you visualize this with a smaller example:
![Nonrotated](https://github.com/lvgl/lvgl/assets/5813055/6e4ccb84-933b-4e4a-ad41-39568b9111dd)
 and you rotate the display by 90° you should get:
![rotated_90](https://github.com/lvgl/lvgl/assets/5813055/91393afb-bbdd-4e68-9d74-19e34df2dcb3)
Which is not the case with the above formula, it will yield `(1,2)` instead.

**Comment by kdschlosser** [comment]
It is easier to understand like this...


![image](https://github.com/lvgl/lvgl/assets/10932297/870c6186-f266-45b6-92e8-5ec71e8321f7)


and rotated 90°


![image](https://github.com/lvgl/lvgl/assets/10932297/a90aee7b-aac0-4840-9209-ffb9689d7fb8)

**Comment by kdschlosser** [comment]
if we have this

![image](https://github.com/lvgl/lvgl/assets/10932297/1a96b628-1363-4147-ad8e-cb412d399523)


which is width = 6 and height = 8

and the target pixel is 3, 2

and we rotate it 180 degrees

x = width - x - 1 = ?
y =height - y - 1 = ?

x = 6 - 3 - 1 = 2
y = 8 - 2 - 1 = 5

you get 2, 5 for the new pixel using the math above

now check this out

![image](https://github.com/lvgl/lvgl/assets/10932297/ea17f945-7b61-489f-8a3e-32cc3b9f6f45)

**Comment by kisvegabor** [comment]
@kdschlosser's example confirms me that the current calculation is correct.
