### ISSUE TITLE
About the Release Date of New Versions

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#6319]
### Introduce the problem

v9.1 It's been two months since the release. When is v9.2 planned?

**Comment by kisvegabor** [comment]
A lot of fixes and features were added indeed, however there are a few open PR that I would like to merge before v9.2. Namely:
- https://github.com/lvgl/lvgl/pull/6333
- https://github.com/lvgl/lvgl/pull/6332
- https://github.com/lvgl/lvgl/pull/6341
- https://github.com/lvgl/lvgl/pull/6068
- https://github.com/lvgl/lvgl/pull/6298

**Comment by faxe1008** [comment]
@kisvegabor just to add to the list (and possibly get some reviews :^) ) I also have this PR here for I1 color format support https://github.com/lvgl/lvgl/pull/6345

This would help us use the many intree monochrome displays.

**Comment by kisvegabor** [comment]
Getting closer. @liamHowatt made some progress with https://github.com/lvgl/lvgl/pull/6068

**Comment by IAMMX** [comment]
> Getting closer. @liamHowatt made some progress with #6068

👍

**Comment by kisvegabor** [comment]
Closing in favor of #6570
