### ISSUE TITLE
ESP32 SPIFFS

### ISSUE THREAD

**Issue by gauix4** [kisvegabor/lvgl#6325]
### Introduce the problem

No documentation or example for using SPIFFS on ESP32 S3

### Proposal

it would be nice to make an example of the use of SPIFFS on ESP32 S3 many people can't do this and there is no documentation on this subject
I can't either
thanks in advance :)

**Comment by becseya** [comment]
SPIFF is [compatible with POSIX](https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/api-reference/storage/spiffs.html?highlight=posix#application-example) which is supported in LVGL. But I see value adding an explicit example. What do you think? @kisvegabor 

@gauix4 What would be the use-case? Do you want to store images in the internal flash?

**Comment by gauix4** [comment]
@becseya 
Yes, this would be to store images but not in JPEG but rather in binary lvgl or compressed binary, this is much more interesting because the volume is much smaller than JPEG.

Thank you very much for answering anyway ! :)

**Comment by kisvegabor** [comment]
It was already asked by many people how to use LVGL's File System on ESP. So an example and a more detailed docs would be really nice.

**Comment by gauix4** [comment]
@kisvegabor  hoo yess
I would also like to use it

**Comment by kisvegabor** [comment]
See #6367 🙂

**Comment by kisvegabor** [comment]
If it's not working by following the instruction in  https://github.com/lvgl/lvgl/pull/6367 please comment in the Pull request.

**Comment by gauix4** [comment]
<img width="1721" alt="Capture d’écran 2024-09-16 à 02 46 30" src="https://github.com/user-attachments/assets/c96d94a4-48d5-47fc-9dc4-f0b04b578c9b">

**Comment by jgauchia** [comment]
Hi @gauix4 

I'm using binary images and SPIFFS in my project since LVGL 8.3.

My programming skills are limited but maybe these steps can help you:

-  Check partitions of your board, I suposed that you have a SPIFFS partition with available space

- Create a folder in your project called **data** and put **bin** files on it

![help](https://github.com/user-attachments/assets/da979599-e1ba-41dd-b655-d20b80c56101)

- Upload data to ESP32 file system 
(This metod or **pio run --target uploadfs**)

![help](https://github.com/user-attachments/assets/aa15e289-70e4-4a44-b52d-e19ce5c6a724)

- lv_conf.h (using POSIX)

```
/** Setting a default driver letter allows skipping the driver prefix in filepaths. */
#define LV_FS_DEFAULT_DRIVE_LETTER 'F'

/** API for fopen, fread, etc. */
#define LV_USE_FS_STDIO 0
#if LV_USE_FS_STDIO
    #define LV_FS_STDIO_LETTER '\0'     /**< Set an upper cased letter on which the drive will accessible (e.g. 'A') */
    #define LV_FS_STDIO_PATH ""         /**< Set the working directory. File/directory paths will be appended to it. */
    #define LV_FS_STDIO_CACHE_SIZE 0    /**< >0 to cache this number of bytes in lv_fs_read() */
#endif

/** API for open, read, etc. */
#define LV_USE_FS_POSIX 1
#if LV_USE_FS_POSIX
    #define LV_FS_POSIX_LETTER 'F'     /*Set an upper cased letter on which the drive will accessible (e.g. 'A')*/
    #define LV_FS_POSIX_PATH "/spiffs"         /*Set the working directory. File/directory paths will be appended to it.*/
    #define LV_FS_POSIX_CACHE_SIZE 0    /*>0 to cache this number of bytes in lv_fs_read()*/
#endif
```

- Init SPIFFS 

```
  esp_vfs_spiffs_conf_t conf = {
    .base_path = "/spiffs",
    .partition_label = NULL,
    .max_files = 5,
    .format_if_mount_failed = false
  };

  esp_err_t ret = esp_vfs_spiffs_register(&conf);

  if (ret !=ESP_OK)
  {
    if (ret == ESP_FAIL)
      log_e("Failed to mount or format filesystem");
    else if (ret == ESP_ERR_NOT_FOUND)
      log_e("Failed to find SPIFFS partition");
    else
      log_e("Failed to initialize SPIFFS (%s)",esp_err_to_name(ret));
    return ESP_FAIL;
  }

  size_t total = 0, used = 0;
  ret = esp_spiffs_info(NULL, &total, &used);
  if (ret!= ESP_OK)
    log_e("Failed to get SPIFFS partition information (%s)", esp_err_to_name(ret));
  else
    log_i("Partition size: total: %d used: %d", total, used);
  
  return ESP_OK;
```

- Use your bin file in LVGL (example)

```
lv_obj_t *altitImg = lv_img_create(lv_scr_act());
lv_img_set_src(altitImg, "/altit.bin");
```

(Sorry @kisvegabor if I answer this closed Issue)

**Comment by gauix4** [comment]
Thank you for your help ! Yes of course I put the binary files in data there is no problem with all that the only problem as I say is really the implementation of the code and the options nothing works! zero documentation nothing and rereading the code is a monumental mess!

<img width="1723" alt="Capture d’écran 2024-09-16 à 17 07 46" src="https://github.com/user-attachments/assets/d1e878a1-e4ee-4366-9d89-475282caafdd">

where did you find the minimum documentation to know how to make this library work because frankly I find absolutely nothing and when I find something; since I don't speak English it's only technical words and it doesn't translate them and I don't understand anything frankly the developers really didn't make any effort to detail the functionalities I think they are too caught up in their work and forget that other people will reread the code but given the name of the variables it is very complicated especially when you don't speak English at all

**Comment by gauix4** [comment]
@kisvegabor @kisvegabor

I still haven't seen any documentation or examples, it's still a pain, I've been on it for several days and I've been testing things, I still haven't made any progress except being even more annoyed at not finding anything and seeing a lot of people looking too.
sorry if I bet ungrateful that's not the goal it's just that there I'm fed up of not moving forward spending hours to go nowhere each time I think I find something in the end it's absolutely not that I try to reread the code to do tests but nothing conclusive at all

**Comment by gauix4** [comment]
<img width="360" alt="Capture d’écran 2024-09-17 à 04 13 45" src="https://github.com/user-attachments/assets/8939169d-627e-41da-be81-a3e77d26f442">

![458484493_386962824452389_5389570496780490856_n](https://github.com/user-attachments/assets/9712f2d7-9801-45f2-b481-7d20b4acc3bb)

<img width="1694" alt="Capture d’écran 2024-09-17 à 04 44 48" src="https://github.com/user-attachments/assets/8299ebea-30f5-4adb-a80d-7e1dffcd66ba">
<img width="1728" alt="Capture d’écran 2024-09-17 à 04 45 40" src="https://github.com/user-attachments/assets/1a849e38-32d1-4322-bc70-1069d1570455">
<img width="1728" alt="Capture d’écran 2024-09-17 à 04 47 21" src="https://github.com/user-attachments/assets/5354af09-2928-4a1c-807b-568109c327fb">

<img width="1728" alt="Capture d’écran 2024-09-17 à 04 46 48" src="https://github.com/user-attachments/assets/4b902376-7448-4fe1-9ccd-0aa5ef4e4eeb">

I am also unable to activate PNG decoding, it always asks me for a library which cannot be found.

**Comment by mak966** [comment]
hi, 
I am stuck at the same place like gauix4  

lv_conf.h
--------------
/*API for fopen, fread, etc*/
#define LV_USE_FS_STDIO 1
#if LV_USE_FS_STDIO
    #define LV_FS_STDIO_LETTER 'S'     /*Set an upper cased letter on which the drive will accessible (e.g. 'A')*/
    #define LV_FS_STDIO_PATH ""         /*Set the working directory. File/directory paths will be appended to it.*/
    #define LV_FS_STDIO_CACHE_SIZE 0    /*>0 to cache this number of bytes in lv_fs_read()*/
#endif
/*LODEPNG decoder library*/
#define LV_USE_LODEPNG 1		// 0

my code 
--------------
  lv_init();  Serial.println("LVGL inited");
  // Register print function for debugging
    // SPIFFS driver'ını LVGL'ye kaydet
    lv_fs_init();
..........
  scr1 = lv_obj_create(NULL);

  lv_obj_t *img_button = lv_image_create(scr1);
  lv_image_set_src(img_button, "S:/103.png"); // Başlangıç resmi
  lv_obj_set_size(img_button, 100, 100);
  lv_obj_align(img_button, LV_ALIGN_BOTTOM_LEFT, 10, 10 );  

-----------

the code compiles without error
however 

debug lines :
------------
17:26:11.150 -> Dosya: 103.png
17:26:11.150 -> Dosya: parametre_isim.txt
(txt files I can read from SPIFFS)

17:26:11.684 -> [Warn]	(0.000, +0)	 lv_fs_open: Can't open file (S:/103.png): unknown driver letter lv_fs.c:88
17:26:11.684 -> [Warn]	(0.000, +0)	 lv_fs_open: Can't open file (S:/103.png): unknown driver letter lv_fs.c:88
17:26:11.684 -> 

I am using lvgl9.2 with CYDisplay , I can put simple buttons on the screen without problem
the png file is 6 Kbyte

can you help?
