### ISSUE TITLE
Lottile on web pages https://docs.lvgl.io/master/widgets/lottie.html ,there is no button to view the C code

### ISSUE THREAD

**Issue by IAMMX** [kisvegabor/lvgl#6338]
### LVGL version

master

### What happened?

Lottile on web pages https://docs.lvgl.io/master/widgets/lottie.html ,there is no button to view the C code

![image](https://github.com/lvgl/lvgl/assets/150422110/bf07dafe-2651-41de-a6ea-953701e90ea7)

**Comment by kisvegabor** [comment]
Fixed by #6342
