### ISSUE TITLE
Slider only changes value when moved

### ISSUE THREAD

**Issue by alexriegler12** [kisvegabor/lvgl#6339]
### LVGL version

9.x.x

### What happened?

If you touch the area of a slider outside of the knob, it only updates the position when you  move the finger, unlike 8.x.x, where it is instantly updated when you touch it. Is that intentional or is it a bug?

**Comment by C47D** [comment]
Hi,

As far as I know that's intentional, you have to touch near the knob or over the knobs in order to move it.

**Comment by kisvegabor** [comment]
Hi,

It's really intentional, however the touched value should be applied on release too. 
![slider](https://github.com/lvgl/lvgl/assets/7599318/caf1ac67-475a-4037-b765-52eac96e0a81)
