### ISSUE TITLE
simple container of radius one shows mixed color

### ISSUE THREAD

**Issue by jihunluv** [kisvegabor/lvgl#6351]
### LVGL version

lvgl 8.3.11

### What happened?

cloned lv_port_pc_vscode with 8.3.11 tag

Created simple testcase where the container has radius 1,
![image](https://github.com/lvgl/lvgl/assets/24875924/0869d7fb-fe70-470d-92d6-9ef4f14b74da)

Expected result is the container's color is white. Instead, the container color is pink (like mixed with background)
When the radius is 2, the color of container is white.

### How to reproduce?

static void user_image_demo1()
{
  lv_obj_t *scr = lv_obj_create(NULL);
  lv_obj_set_size(scr, LV_PCT(100), LV_PCT(100));
  lv_obj_set_pos(scr, 0, 0);
  lv_obj_set_style_bg_color(scr, lv_color_hex(0xFF0000), LV_PART_MAIN|LV_STATE_DEFAULT);
  lv_obj_t *container = lv_obj_create(scr);
  lv_obj_set_style_radius(container, 1, LV_PART_MAIN);
  lv_obj_set_style_border_width(container, 0, LV_PART_MAIN);
  lv_obj_set_size(container, 491, 271);
  lv_obj_set_pos(container, 19, 20);
  lv_scr_load(scr);
}

**Comment by kisvegabor** [comment]
I've tested in the Eclipse simulator and it works for me with v8.3 and v8.4 too. 

If you are still at the beginning of your project can you upgrade to LVGL v9?

**Comment by jihunluv** [comment]
Sorry about incomplete bug report.
I've tested this with v9 already and it seems OK with that version.
But with V8.3.11 tag and below is the configuration I've used.
Makefile

-LV_DRIVER          := X11
-#LV_DRIVER          := SDL2
+#LV_DRIVER          := X11
+LV_DRIVER          := SDL2

-LV_DRIVER_USE       := USE_SDL
+LV_DRIVER_USE       := USE_SDL_GPU


It seems the problem is related to SDL_GPU configuration.

**Comment by kisvegabor** [comment]
Happy to here that it's working in v9. Can you continue your project with v9?

The SDL render implementation of v8 is quite complex and I won' be able to look into it in the ear future. :slightly_frowning_face:

**Comment by jihunluv** [comment]
Thank you for the feedback, V9 is not a viable option for me because of  migration issues. Perhaps we can withhold this issue for sometime.
