### ISSUE TITLE
Can lvgl support copying and pasting text using the mouse on Windows?

### ISSUE THREAD

**Issue by yjw1617** [kisvegabor/lvgl#6352]
### Introduce the problem

"Does LVGL support copying and pasting text using the mouse on Windows? I have tried label and textarea, but it doesn't work."

**Comment by kisvegabor** [comment]
Nope, unfortunately such text editing is not supported now. :slightly_frowning_face: 

We might push LVGL more into the desktop app development direction (whre this feature would be required) and I thought it's a good idea. However, now I believe that being strong in embedded and keep ourselfs focused is a better strategy.
