### ISSUE TITLE
Tabview scrolling issue

### ISSUE THREAD

**Issue by Goran58** [kisvegabor/lvgl#6357]
### LVGL version

v9.1

### What happened?

If you continue to scroll left when you have reached the last tab, you jump back to the second-to-last tab. Scrolling from the last to the second-to-last tab is always done without animation. This worked until version 9.0. 

### How to reproduce?

The error can be easily reproduced on, for example, LVGL's demo page.

**Comment by kisvegabor** [comment]
Hi,

On my side it's working well with `master`. Could you also try with `master`?
![widgets](https://github.com/lvgl/lvgl/assets/7599318/d3b1379f-4c60-458d-965b-149684c22d2c)

**Comment by Goran58** [comment]
Hi,
Sorry that I was a bit unclear, but by the demo page I actually meant the widget examples, see below. And there it also goes wrong for master but not for version <= 9. Possibly, the error depends on which input device is used. I am using evdev on a Linux computer.
![lvgl](https://github.com/lvgl/lvgl/assets/6393885/76f349e7-6036-4c6b-a17a-032cfa38f1cd)

**Comment by Goran58** [comment]
Have now tried with master. Same problem, see below.

https://github.com/lvgl/lvgl/assets/6393885/bb33d861-55c1-455d-ad74-b6c4635a060c

**Comment by faruq-zhao** [comment]
Hi.
I successfully reproduced this error in the `master` branch.
Please see the video below for specific performance:
[Screencast from 2024-06-15 02-46-21.webm](https://github.com/lvgl/lvgl/assets/49693069/9b58bf7a-dd8f-4dc8-a415-46df4d3b37fa)

This error seems to be introduced by PR #6230.
https://github.com/kisvegabor/lvgl_upstream/blob/269dd90211225fca8e56311d3120acf1ba51f0b3/src/indev/lv_indev_scroll.c#L683
When you continue to slide on the last tab,`no_more_end_snap` is always false.
@kisvegabor Do you have time to check it out? Thank you.

**Comment by niklasf** [comment]
The same patch is also breaking scrolling on the last tile of tile views: https://docs.lvgl.io/master/examples.html#tileview

**Comment by kisvegabor** [comment]
I've just fixed it in #6393.
Please test it.

**Comment by Goran58** [comment]
The fix in #6393 seems to work, at least in the tabview case. 
Thanks a lot.
