### ISSUE TITLE
Make the NuttX drivers even simpler

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#6365]
### Introduce the problem

I'm preparing to the NuttX conference on Friday. LVGL's NuttX integration is quite complete, except that the users need to create an `uvloop` themselves. 

### Proposal

I wonder if [this](https://github.com/apache/nuttx-apps/blob/master/examples/lvgldemo/lvgldemo.c#L69C1-L87C2) can be part of `lv_nuttx_libuv.c`. If the user wants something custom, he can just write use its own implementation and simply not call the built-in `lv_nuttx_uv_loop`.

**Comment by kisvegabor** [comment]
cc @XuNeo

**Comment by XuNeo** [comment]
I see no problem to move to `lv_nuttx_libuv.c`.

This part can also have a dedicated function like `lv_nuttx_run()`

```c
#ifdef CONFIG_LV_USE_NUTTX_LIBUV
  lv_nuttx_uv_loop(&ui_loop, &result);
#else
  while (1)
    {
      uint32_t idle;
      idle = lv_timer_handler();


      /* Minimum sleep of 1ms */


      idle = idle ? idle : 1;
      usleep(idle * 1000);
    }
#endif
```

**Comment by liamHowatt** [comment]
> users need to create an `uvloop` themselves.

I think you already know, but `libuv` integration is optional. It just [uses the normal sleep loop if it's disabled](https://github.com/apache/nuttx-apps/blob/00f98947786892eaabf60b2e61fad553aee1c36c/examples/lvgldemo/lvgldemo.c#L148-L161). It's [not enabled by default in the sim](https://github.com/apache/nuttx/blob/dc651e090eb366f9abb18c48be1dbb92b7084bdc/boards/sim/sim/sim/configs/lvgl_fb/defconfig#L38-L39).

**Comment by liamHowatt** [comment]
Not stale.
