### ISSUE TITLE
Gridnav does not send LV_EVENT_FOCUSED

### ISSUE THREAD

**Issue by di-jtrumpower** [kisvegabor/lvgl#6368]
### LVGL version

v9.1.0-214-g59277de9f

### What happened?

Gridnav does not send LV_EVENT_FOCUSED, I found an issue linked in the forum from a year ago with example code:

https://forum.lvgl.io/t/trigger-lv-event-focused-with-grid-navigation/12371

I dug into the code and found that focus events are only sent from lv_indev (touchscreen/pointers). Style changes work fine which is strange. I am assuming the way that focus events are sent are different than how styling is set. Adding in the send event in the key handler for gridnav seems like the correct answer but wasn't sure if there was  reason it  wasn't done or I am missing something obvious.

**Comment by kisvegabor** [comment]
Hi,

I've looked into it and I agree that manually sending the events [here](https://github.com/lvgl/lvgl/blob/master/src/others/gridnav/lv_gridnav.c#L231-L232) should work. Could send a pull request for it?

**Comment by di-jtrumpower** [comment]
Yes I will send a PR shortly

**Comment by kisvegabor** [comment]
Fixed by https://github.com/lvgl/lvgl/pull/6385
