### ISSUE TITLE
Canvas examples

### ISSUE THREAD

**Issue by AZ-Renesas** [kisvegabor/lvgl#6374]
### LVGL version

9.1.1

### What happened?

The canvas examples are showing a black screen on EK-RA8D1.

### How to reproduce?

Try to run lv_example_canvas_1.c

**Comment by kisvegabor** [comment]
Thanks, we will check it out! 

cc @becseya

**Comment by becseya** [comment]
It seems to be a Dave2D bug, that requires deeper investigation.

In the meantime you can use `#define LV_USE_DRAW_DAVE2D 0`, @AZ-Renesas.

**Comment by AZ-Renesas** [comment]
Hello,
Thanks for looking into this ?

Does this mean that I cannot implement something like on canvas examples ?
https://docs.lvgl.io/master/widgets/canvas.html

How does setting LV_USE_DRAW_DAVE2D to 0 help me to use all canvas functions ?

**Comment by becseya** [comment]
Setting `LV_USE_DRAW_DAVE2D` to `0` instead of `1` in `src/lv_conf.h` will allow you run canvas examples and develop your application using canvas while we are working on the issue.

**Comment by AZ-Renesas** [comment]
Thanks, after setting it to 0 I can implement a canvas. Please let us know for any updates.

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
Sorry that it took so long. After a long debugging session I found the single number to change to resolve the issue. :slightly_smiling_face: 

See https://github.com/lvgl/lvgl/pull/6498
