### ISSUE TITLE
README has broken picture

### ISSUE THREAD

**Issue by maxgerhardt** [kisvegabor/lvgl#6400]
### LVGL version

9.0.0

### What happened?

Just open https://github.com/lvgl/lvgl

![grafik](https://github.com/lvgl/lvgl/assets/26485477/c3a80ffd-9838-4981-a39c-0f5cd930b340)

**Comment by C47D** [comment]
There's a 404 when trying to fetch the LVGL logo from https://lvgl.io/.

BTW: The page looks really good, LVGL Rocks!

**Comment by kisvegabor** [comment]
Thanks! They were cached for me and haven't noticed the issue. :pray: 

Opened #6404 

>  The page looks really good, LVGL Rocks!

Thank you! cc @richardgazdik :wink:
