### ISSUE TITLE
Replace use of lvgl.io bootstrap in web simulator with CDN

### ISSUE THREAD

**Issue by Viatorus** [kisvegabor/lvgl#6419]
### LVGL version

any

### What happened?

Going to any simulator page linked here: https://sim.lvgl.io/ shows a page like this (firefox/chrome/mobile):

![image](https://github.com/lvgl/lvgl/assets/3637911/45588623-9f36-4e1b-9746-a48f5bb8bef3)

**Comment by kisvegabor** [comment]
Thank you for reporting this issue!

We have launched our new website a few weeks ago and I thought the issue might be related to it. However I see only this error in the Console which looks like something else.
![image](https://github.com/lvgl/lvgl/assets/7599318/36470084-5bfe-48bf-be7b-526f96820bde)

@embeddedt do have a little bit of time to take a look at it?

**Comment by embeddedt** [comment]
@kisvegabor The simulators relied on https://lvgl.io/assets/bootstrap/css/bootstrap.min.css and https://lvgl.io/assets/bootstrap/js/bootstrap.min.js, which appear to be missing after the site redesign. Can these assets be put back, or do we need to edit the existing simulators to use Bootstrap from another source?

**Comment by kisvegabor** [comment]
Ah, thank you! As a hotfix I added bootstrap. However to avoid similar issues in the future, could we use [bootstrap from CDN](https://www.bootstrapcdn.com/)?

**Comment by Viatorus** [comment]
The Save Button is also not working (at least on my side):

> ERROR: Network Error
> POST https://forum.lvgl.io:8443/save_file net::ERR_CONNECTION_RESET

**Comment by kisvegabor** [comment]
I've fixed it, but saving/loading is very slow on my end.

**Comment by embeddedt** [comment]
All of the simulators (including the pre-v8 ones) should now be updated to pull Bootstrap from cdn.js rather than relying on the lvgl.io copy.

**Comment by kisvegabor** [comment]
Thank you @embeddedt!
