### ISSUE TITLE
Compile Error with Code Blocks 20.03 (solved)

### ISSUE THREAD

**Issue by bartholomaeuz** [kisvegabor/lvgl#6428]
### LVGL version

v9.1.0

### What happened?

I get an compile error from the following branch:
https://github.com/lvgl/lv_port_win_codeblocks

lvgl\src\drivers\windows\lv_windows_context.c|141|error: 'CREATE_WAITABLE_TIMER_MANUAL_RESET' undeclared (first use in this function)|
lvgl\src\drivers\windows\lv_windows_context.c|141|note: each undeclared identifier is reported only once for each function it appears in|
lvgl\src\drivers\windows\lv_windows_context.c|142|error: 'CREATE_WAITABLE_TIMER_HIGH_RESOLUTION' undeclared (first use in this function)|
||=== Build finished: 2 error(s), 4 warning(s) (2 minute(s), 1 second(s)) ===|

### How to reproduce?

add following lines to this file:
lvgl\src\drivers\windows\lv_windows_context.c

 #define CREATE_WAITABLE_TIMER_MANUAL_RESET 1
 #define CREATE_WAITABLE_TIMER_HIGH_RESOLUTION 2

**Comment by kisvegabor** [comment]
Hi,

Thank you for reporting this issue! 

cc @MouriNaruto

**Comment by MouriNaruto** [comment]
Got it. I will fix that in the recent days.

Kenji Mouri.

**Comment by bluetur1** [comment]
It has not be fixed now.Thank you very much for your report. Be lucky to meet !
@heishuini
