### ISSUE TITLE
documentation for msgbox needs to be updated.

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#6433]
### LVGL version

master

### What happened?

the documentation overview is incorrect for how to use this widget.

### How to reproduce?

https://docs.lvgl.io/master/widgets/msgbox.html

**Comment by kisvegabor** [comment]
Oh, it's really outdated. Do you have time to update it? I can also update it but only one week later.

**Comment by kdschlosser** [comment]
I literally just messed up my right hand. i am not able to use it at all. my typing ability is greatly reduced....

**Comment by kisvegabor** [comment]
Unfortunately I couldn't find time for it.
@liamHowatt Do you have some free time to update message box's docs?

**Comment by liamHowatt** [comment]
Okay! Will do.

**Comment by liamHowatt** [comment]
PR open. Please let me know if it's missing anything.
