### ISSUE TITLE
Event Sequence

### ISSUE THREAD

**Issue by fatihozen3** [kisvegabor/lvgl#6439]
### Introduce the problem

I use IMXRT1170 and LVGL v9.1 version.

When I use event on an object;

I use LV_EVENT_SHORT_CLICKED, LV_EVENT_LONG_PRESSED, LV_EVENT_LONG_PRESSED_REPEAT and LV_EVENT_RELEASED.

1) I expect release event occurence after all events but when I do short click, first release event occurs and then short clicked event. Is this normal ?

2) When I use Long Press Repeat, I can't use effectively or can't catch every time Long Press event, I guess their timings are so close. Is there any advice to use both exactly ?

**in lv_indev.c file**
```
/*Long press time in milliseconds.
 *Time to send `LV_EVENT_LONG_PRESSSED`)*/
#define LV_INDEV_DEF_LONG_PRESS_TIME      400

/*Repeated trigger period in long press [ms]
 *Time between `LV_EVENT_LONG_PRESSED_REPEAT*/
#define LV_INDEV_DEF_LONG_PRESS_REP_TIME  100
```

 Should I increase LV_INDEV_DEF_LONG_PRESS_REP_TIME ? but I dont want to interfere with lvgl code.

**Comment by liamHowatt** [comment]
1. Yes, the way the logic is currently organized, the `LV_EVENT_RELEASED` event is sent before the `LV_EVENT_SHORT_CLICKED` and `LV_EVENT_CLICKED` events.
2. Could you please explain why you're having trouble catching both events? The normal long press is sent after 400 ms, and then the long press repeat event is sent every 100 ms afterwards, as long as it's being pressed. There should not be a time when both events are sent at the same time.

You may want to catch the `LV_EVENT_PRESSING` event and check the current tick every time to decide what to do. It is sent at least every refresh period as long as the target is being pressed.
