### ISSUE TITLE
Does 9.1 have LV_COLOR_16_SWAP

### ISSUE THREAD

**Issue by spbgzh** [kisvegabor/lvgl#6440]
### LVGL version

v9.1

### What happened?

Now I still need to use ConvHL to swap bytes

### How to reproduce?

void ConvHL(uint8_t *s, int32_t l) {
  uint8_t v;
  while (l > 0) {
    v = *(s + 1);
    *(s + 1) = *s;
    *s = v;
    s += 2;
    l -= 2;
  }
}

**Comment by liamHowatt** [comment]
Yes, there is `lv_draw_sw_rgb565_swap`. Is that what you were looking for?

**Comment by kisvegabor** [comment]
`LV_COLOR_16_SWAP` is also [supported](https://github.com/lvgl/lvgl/blob/master/src/core/lv_refr.c#L1076) for backward compatibility.
