### ISSUE TITLE
Flag LV_PART_INDICATOR dont work to change the font of indicator checkbox.

### ISSUE THREAD

**Issue by 3622-1768** [kisvegabor/lvgl#6456]
### LVGL version

v8.1

### What happened?

I am attempting to change the font of the checkbox because the symbol isn't drawing correctly. Here is what I'm trying:

### How to reproduce?

  cb = lv_checkbox_create(cont);
    lv_checkbox_set_text(cb, "Lemon");
    lv_obj_add_event_cb(cb, event_checkbox, LV_EVENT_ALL, NULL);
    lv_obj_set_style_text_font(cb, &Montserrat_Latin_24, LV_PART_INDICATOR | LV_STATE_DEFAULT);

**Comment by Yangnaan** [comment]
try:
lv_obj_set_style_text_font(cb, &Montserrat_Latin_24, LV_PART_MAIN);

it works.

**Comment by 3622-1768** [comment]
the icon is still not drawn correctly: 
![Screenshot 2024-07-02 123301 bmp](https://github.com/lvgl/lvgl/assets/83682338/392ffe33-0e43-45ea-90d9-08f941d4f6f8)

**Comment by Yangnaan** [comment]
try :

lv_obj_set_style_text_font(cb, &Montserrat_Latin_24, LV_PART_INDICATOR | LV_STATE_CHECKED);

**Comment by 3622-1768** [comment]
it works!
thanks!

**Comment by C47D** [comment]
@kisvegabor should we add this note and code sample on the docs?

**Comment by kisvegabor** [comment]
In #6521 I've restructured the theme a little bit to make it work with `LV_PART_INDICATOR | LV_STATE_DEFAULT`.
