### ISSUE TITLE
setting specific time in meter widget

### ISSUE THREAD

**Issue by Wlad79** [kisvegabor/lvgl#6458]
### LVGL version

v8.4

### What happened?

I'm trying to set specific clock time (minutes and hours) in meter widget from [this](https://github.com/lvgl/lvgl/blob/c86cea34dde41b246fdb05d48cfcf2c645856dd7/examples/widgets/meter/lv_example_meter_3.c). The time should count from that start time til unlimited.

### How to reproduce?

I'm figured out that with `lv_meter_set_indicator_value(meter, indic_min, 10);` can the minutes needle set to 10 but with next refresh will be set to zero. Then I have tried out this function `lv_meter_set_indicator_start_value(meter, indic_min, 10);` but without success.

**Comment by liamHowatt** [comment]
The meter is being set by an animation in that example. You have to adjust the animation to add your own behavior. You can remove the animation and control the indicator with `lv_meter_set_indicator_end_value(meter, indic, v)` where `indic` is `indic_min` or `indic_hour`.
