### ISSUE TITLE
Drawing of vector on a canvas layer - the area outside the vector is filled with "white" 

### ISSUE THREAD

**Issue by minipost** [kisvegabor/lvgl#6463]
### LVGL version

v9.1.0

### What happened?

The "lv_example_canvas_8" draws a blue triangle on a grey canvas. However contrary to previous canvas examples the area outside of the triangle appears to be filled with white.

### How to reproduce?

Run [example 8](https://github.com/lvgl/lvgl/blob/1e2b1988aa205d096939c7401a3b971e4814af8d/examples/widgets/canvas/lv_example_canvas_8.c)

Observe that the canvas area not covered by the triangle is white:
![image](https://github.com/lvgl/lvgl/assets/2884519/60e8dccf-c106-469d-b1c2-8cc8ea4b3b3c)

comment out l. 38 "lv_draw_vector(dsc);" and observe that the the grey canvas background is now visible.
![image](https://github.com/lvgl/lvgl/assets/2884519/d069da1a-c194-4c38-9aa0-a273b06cd3d8)

**Comment by liamHowatt** [comment]
Thanks. There's already a PR that fixes it: #6406

**Comment by minipost** [comment]
I just tried https://github.com/kisvegabor/lvgl_upstream.git (revision 7089cb14e923eefb634d81c7fc1e635e07bf1923)
Unfortunately the above behavior appears to be the same.

**Comment by liamHowatt** [comment]
You have to checkout the correct branch - `fix/thorvg`, not `master`.
```sh
git fetch kisvegabor
git checkout --track kisvegabor/fix/thorvg
```

**Comment by minipost** [comment]
Tried again on ef3c8daeb228128998136d48056e3c62294c2677
It works

**Comment by Yangnaan** [comment]
i ran lv_example_canvas_8(), the result is blank, 
![捕获](https://github.com/lvgl/lvgl/assets/26960677/ec845319-4756-4f61-a9a7-de33231b26ee)

**Comment by liamHowatt** [comment]
Thanks @Yangnaan, I was able to reproduce the issue by `LV_USE_VECTOR_GRAPHIC` to `1` but forgetting to set `LV_USE_THORVG_INTERNAL` to `1`. Can you make sure `LV_USE_THORVG_INTERNAL` is set to `1`?

**Comment by Yangnaan** [comment]
> Thanks @Yangnaan, I was able to reproduce the issue by `LV_USE_VECTOR_GRAPHIC` to `1` but forgetting to set `LV_USE_THORVG_INTERNAL` to `1`. Can you make sure `LV_USE_THORVG_INTERNAL` is set to `1`?

it works! thanks a lot
