### ISSUE TITLE
JSON generator missing data

### ISSUE THREAD

**Issue by liamHowatt** [kisvegabor/lvgl#6474]
### LVGL version

v9.1.1

### What happened?

All fields except `"macros"` are empty in the generated JSON file.

```json
{
    "enums": [],
    "functions": [],
    "function_pointers": [],
    "structures": [],
    "unions": [],
    "variables": [],
    "typedefs": [],
    "forward_decls": [],
    "macros": [
        {
            [...]
```

### How to reproduce?

```sh
python3 scripts/gen_json scripts/gen_json/gen_json.py > lvgl.json
```

**Comment by liamHowatt** [comment]
cc @kdschlosser

**Comment by kdschlosser** [comment]
OK, i'll go over it and see what got goofed up with it.

**Comment by liamHowatt** [comment]
I just realized the command I put in "how to reproduce" is flawed. It should be
```sh
python3 scripts/gen_json/gen_json.py > lvgl.json
```

That's not why it failed though, just a typo for the issue.

**Comment by liamHowatt** [comment]
No, it works since the PR, thanks. Just clarifying the typo

**Comment by kdschlosser** [comment]
Yeah I saw that you said it was working in the PR but after I had already asked here.
