### ISSUE TITLE
Displaying gif pictures from external flash in qspi address mapping mode

### ISSUE THREAD

**Issue by spbgzh** [kisvegabor/lvgl#6476]
### LVGL version

v9.1

### What happened?

I have encountered a problem. When a raw GIF image is stored in the internal flash, LVGL can read and display it normally. However, when using QSPI memory mapping mode, storing it in the external flash and accessing it directly by address, it cannot be read and displayed normally.
I tried it. If it's just a normal picture, the picture can be read and displayed normally in qspi address mapping mode, but the gif animation can't. At the same time, I also made sure that my RAM is enough.

### How to reproduce?

__attribute__((section(".qspi")))

**Comment by kisvegabor** [comment]
The gifdecoder reads the data just as an array, so believe there are some issues with the memory access.

Can you test it? E.g. create a 100kB `uint8_t` array with increasing numbers and try to read them randomly.
