### ISSUE TITLE
custom.cmake cannot install lvgl.pc

### ISSUE THREAD

**Issue by paulh002** [kisvegabor/lvgl#6478]
### LVGL version

v8.4

### What happened?

When I issue sudo make install on raspberry pi I get the error 
`CMake Error at _deps/lvgl-build/cmake_install.cmake:70 (file):
  file INSTALL cannot find "/home/pi/sdrberry/build/lvgl.pc": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
`
I don't use this file and also don't know why it is necessary, can it be removed? Or issue fixed. Because cmake will stop and don't install the application.

### How to reproduce?
In CMakeList.txt I fetch lvgl with 
`FetchContent_Declare(lvgl GIT_REPOSITORY  https://github.com/lvgl/lvgl.git GIT_TAG v8.4.0)`
Install with:
`sudo make install`

**Comment by kisvegabor** [comment]
It works for me:
```
cd lvgl 
mkdir build
cd build
cmake ..
make -j
sudo make install
```

Could you test it?

**Comment by paulh002** [comment]
This is not the problem. The make install fails when it is part of an application cmake file and lvgl is included using FetchContent_Declare. The path for lvgl.pc is not correct in that case

**Comment by kisvegabor** [comment]
Please a minimal CMake file file which uses `FetchContent_Declare` to reproduce the issue.

**Comment by paulh002** [comment]
I made a small project which demonstrates the issue.  
You can clone it from https://github.com/paulh002/cmaketest  

to build it:  
git clone https://github.com/paulh002/cmaketest  
cd cmaketest
mkdir build
cd build
cmake ..
make
sudo make install


Result will be:
pi@pi5:~/cmaketest/build $ sudo make install
[ 45%] Built target lvgl
[ 45%] Built target cmaketest
[ 85%] Built target lvgl_examples
[100%] Built target lvgl_demos
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/lvgl/../lv_conf.h
CMake Error at _deps/lvgl-build/cmake_install.cmake:70 (file):
  file INSTALL cannot find "/home/pi/cmaketest/build/lvgl.pc": No such file
  or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)


make: *** [Makefile:100: install] Error 1

**Comment by paulh002** [comment]
changing line configure_file("${LVGL_ROOT_DIR}/lvgl.pc.in" lvgl.pc @ONLY) to configure_file("${LVGL_ROOT_DIR}/lvgl.pc.in" ${CMAKE_BINARY_DIR}/lvgl.pc @ONLY) seems to correct the problem.

**Comment by kisvegabor** [comment]
Not stale!

@paulh002 can you send a pull request with this fix?

**Comment by paulh002** [comment]
ok

**Comment by kisvegabor** [comment]
Not stale
