### ISSUE TITLE
A way to inject custom byte orders to be written to the frame buffer

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#6484]
### Introduce the problem

I am working on a driver for MicroPython for RGB LED Arrays. This would be kind of cool for large format type displays. Initially the driver is going to support a single array of "Pixels" (RGB LEDS) connected using either an SPI connection or a single data line with no clock. Initially it is only going to support direct rendering and I do plan on adding partial render in the future. I also plan on adding the ability to have multiple arrays that will act as a single display.

Here is my issue. RGB LEDs have the whole gamut of byte orders. RGB, RBG, GRB, GBR, BRG and BGR. The only thing that seems to be common across the different manufacturers is when using an RGBW LED the white seems to always be last if it is supported.

So my problem is there is no support for RGBW and I have code that can handle converting RGB to RGBW but I need to have that extra byte of data put into the frame buffer LVGL doesn't support altering the byte order at render time. The frame buffer has to be iterated over and the bytes moved around. This poses an issue when dealing with changing from RGB to RGBW and needing to start at the end of the frame buffer and shifting all of the pixel data over a byte and at the same time also changing the byte order. This is going to produce a lot of extra overhead I think might be able to be mitigated and I will explain how in a minute. The other issue is with SPI connections and there being header and footer data that needs to be in the frame buffer as well. So there are start and stop offsets that have to be dealt with.

### Proposal

My thought is what about the ability to set a callback function that will write a single pixels color? That function would accept the frame buffer that needs to be written to, the color that is being written and the pixel number for that color (not the array index). This way pixel data would be able to have it's byte order and also it's location in the frame buffer altered "on demand" so to speak. If the pointer is not set then the usual code will run that handles writing the data to the frame buffer. This will remove the need for having the RGB565 byte swap function that has to be called by the user to set the byte order. 

Another option is to use a macro for the writing portion that the user is able to override... 

I like the macro idea better than the function as it would be less processor time used.

**Comment by kisvegabor** [comment]
In v8 we had [disp->set_px_cb](https://github.com/lvgl/lvgl/blob/release/v8.4/src/hal/lv_hal_disp.h#L113-L117) to support these kind of cases. However it was very slow. Actually it's faster to render in a common format and convert it before flushing. 

For the extra byte in RGBW, what about using `LV_COLOR_FORMAT_XRGB8888`? It's like `ARGB8888` but `A` is ignored.

**Comment by kdschlosser** [comment]
That will work for the extra byte but the buffer has to still be iterated over to set the byte order and to convert RGB to RGBW. If iteration over the buffer still has to occur it's not that big a deal at that point to make the buffer the size that is actually needed but pass a smaller size to LVGL along with the buffer. Then it's just a matter of iterating over the buffer starting at the end of it and moving the data while making the conversion and setting the byte order. The issue with this approach is direct mode and double buffering. The buffer data is going to get all kinds of mucked up. I would need to use a 3rd buffer to copy to to handle that and if that is what needs to be done may as well use a combination of direct and partial mode which is what is called a bounce buffer. a since small buffer that LVGL writes to and that small buffer or partial buffer gets copied to a dma buffer and while that dma buffer is being transmitted LVGL is able to fill that small buffer again. The partial buffer is more than likely going to be able to get filled multiple times before a large one finishes transferring and once the transfer is done the data from the updated second full buffer would get copied to the one that just finished sending. This can be done as a DMA transfer between the 2 so user code would be able to run while that copy was taking place..

an LED matrix doesn't need to be updated constantly so there is no constraints there while all led's need to be updated when sending the data the data doesn't need to be sent over and over again at a specific interval to keep the led's lit. send the data once and they will stay that way until an update is made or the power gets turned off...


If instead of using a function call to set the pixel data which consumes additional processor time using a macro would not. It would allow for custom code to be used when writing the pixel data replacing the code that is currently used. this would solve the problem with the copy when using direct mode because the correct data would be copied to the other buffer.

**Comment by kdschlosser** [comment]
the added code needed to check for the existence of the callback and the calling of the function would add a considerable amount of time to the rendering process. so I can see where it would be faster to iterate over the buffer after the fact. code replacement using macros would not have this issue. Speed is not so much of an issue with LED's because the transfer speed is slow, 800kbps for single wire arrays. using dma memory would allow for double buffering for the transfer and by time the one buffer actually finishes transmitting chances are LVGL would already be done rendering even if the render was slow.

See what I am talking about.. ??

Do you know of LVGL being used for an LED matirx?

**Comment by kisvegabor** [comment]
> Do you know of LVGL being used for an LED matirx?

In 2017 I've created a LED matrix from 7-800 LEDs and installed it above our bed. It could show some random "clouds", show the time, etc, but most importantly - on a special key combination - it could display the "Would you marry me?" text. 😊

---

Adding macros could work, but
- It's a compile time setting, and we are migrating towards runtime config
- It's a huge complexity, as it needs to be supported in all assembly extensions of the SW render too

This is the only use case when it was required, and it's not really needed here either as "the transfer speed is slow, 800kbps for single wire arrays".

---

Regarding the "bounce buffer" I think this would be the true magic: 2 partial buffers + 2 direct mode buffers.
This way LVGL could render into the first partial buffer, when it ready it can be copied by DMA to the inactive direct mode buffer. (While coping LVGL can render to the other partial buffer). When all areas are rendered the direct buffers were synced internally and automatically. This way we can render into small and fast buffers, but still can have tearing free output. It's the best of the 2 worlds.

**Comment by kdschlosser** [comment]
I get ya, There would not be a need to have 2 full buffers and 2 partial. only 1 full and 2 partial. The LED's are not like an RGB display that has no GRAM. So it would be OK to copy a partial buffer directly to the full buffer as there wouldn't be any tearing issue due to how LED's don't need to be updated at a specific frequency. using the partial buffers would also make the iteration over the buffer to change about the byte order a lot faster. It would make sense to copy the pixel data that that time and not use DMA to copy from a partial buffer to the full buffer. DMA would only be used for sending. 

I wasn't sure if there was only a single place in LVGL that actually did the writing of data to the frame buffer or if there was code in several places to do it and the code for each place was different.

**Comment by kdschlosser** [comment]
I have most of the code written for it for the micropython binding I am working on. It is going to be for the ESP32 to start off with. I have to look into how to go about doing it for other MCU's I am hoping that I don't have to use bit-bang. I am using the RMT for the ESP32 to transmit the data. It is very much like IR pulses and it only uses a single data line. the LED's that use 2 data lines are SPI so that's fairly simple to deal with as well.

**Comment by kisvegabor** [comment]
2 partial + 1 direct is already supported. Basically it's the 2 partial mode and in the flush_cb you copy the rendered images to a frame buffer.

I'm more puzzled with the 2 partial + 2 direct as it's really the mixture of the the two. I keep thinking about it :slightly_smiling_face:

**Comment by kdschlosser** [comment]
You would use 2 partial and 2 direct for say and RGB display. This would have to be used with DMA memory for the 2 direct buffers. This would be a better solution for large resolution displays that have a lot being updated on the display. This is an ideal solution for those that don't want to have LVGL render the entire display at one time.

as an example...

Interrupts are a fantastic thing for timing critical code that needs to run. But they have a downside, they are expensive to use. Too many of them and you end up using too much of the CPU time saving and restoring the CPU state. So they are not always ideal to use. You also have the inability to allocate memory outside of the stack which is not always ideal. If there is code that needs to be run in a smaller window of time then would be allowed by rendering the display in direct mode you would want to use smaller buffers for this. You couldn't update a single large frame buffer using 2 partials if using an RGB display because you would end up with tearing. You would need to use 2 partials and 2 full in order to have it render properly. This would be for the sole purpose of having LVGL exit the call to task_handler without having to wait the needed time to render the full frame buffer.

This is one of the reasons having the task handler return a True or a False as a way to inform the user if there was anything that was updated. If there was nothing that was updated (returns False) then swapping the 2 full buffers could be done. If it is (True) that would indicate that data has been written to the buffer which gets handled internally in the flush function and the user would not have code run that swaps the 2 full buffers. 

Because of the use of DMA memory is the reason why you could have 2 small buffers. If all 4 buffers were in DMA memory one full one would be transferring using DMA, One of the small buffers could be getting copied to the second full buffer and LVGL could be filling the second small buffer. 


That is the only use case where I can see it being beneficial to use 2 full and 2 partial buffers.

**Comment by kisvegabor** [comment]
In the past days I have heard some other use cases which shows that we should consider improving buffer management. 

The other use case is rendering the screen in tiles with multiple cores. One core, one tile. It should utalizes cores better than our current strategy (which works better in CPU+GPU scenarios)

I'm thinking about how to touch these interfaces without API break and add support fir
- direct+partial mode
- tiled multi core rendering 
- return after each tile

**Comment by kdschlosser** [comment]
OK so should I reopen this issue?

**Comment by kisvegabor** [comment]
I'll open a new one when I have an idea about how to approach it.

**Comment by egonbeermat** [comment]
> In 2017 I've created a LED matrix from 7-800 LEDs and installed it above our bed. It could show some random "clouds", show the time, etc, but most importantly - on a special key combination - it could display the "Would you marry me?" text. 😊

Did she create an LED matrix to say yes?!
