### ISSUE TITLE
invalid conversion from 'void*' to 'lv_meter_indicator_t

### ISSUE THREAD

**Issue by LaZorraTech** [kisvegabor/lvgl#6488]
### LVGL version

8.4.0

### What happened?

For this example:
https://github.com/lvgl/lvgl/blob/release/v8.4/examples/widgets/meter/lv_example_meter_1.c

When I try to compile it, I get the following error:

src/main.cpp:237:41: error: invalid conversion from 'void*' to 'lv_meter_indicator_t*' [-fpermissive]
     lv_meter_set_indicator_value(meter, indic, v);

So far, all of the other examples/demos I have tried have compiled wonderfully.  However this one hangs with a compiler error.  Is there a recommendation for how to correct this?

I am compiling for this PLATFORM: Espressif 32 (6.5.0) > Espressif ESP32-S3-DevKitC-1-N8R8 (8 MB QD, 8 MB PSRAM) and in arduino.

Thank you for any assistance!
Todd

### How to reproduce?

static void set_value(void * indic, int32_t v)
{
    lv_meter_set_indicator_value(meter, indic, v);
}

**Comment by kisvegabor** [comment]
It's a C++ specific warning. C handles it implicitly. 

In C++ you need to case `void*` explicitly: `(lv_meter_indicator_t*) indic`
