### ISSUE TITLE
Images converted using lvgl's online image converter exhibit color differences.

### ISSUE THREAD

**Issue by makun666** [kisvegabor/lvgl#6491]
### LVGL version

v8.3.10

### What happened?

I need to convert a solid-color background image into a C array using LVGL's online converter. I've selected the CF_TRUE_COLOR_ALPHA color format, and I'm using a 16-bit color depth.

However, I have noticed a slight difference between the C array generated by the online converter and the C array I obtain by reading the same file directly using the png decoder.

Here are the details:
When I use the online converter, the converted value for each pixel in ARGB565 format is 0xE7 0x00 0xFF.
But when I read the file directly, the corresponding pixel value is 0xE6 0x00 0xFF.

For reference, the original ARGB888 value for that pixel in the C array is 0x36 0x1c 0x00 0xff. Converting this to ARGB565 results in the value 0xE6 0x00 0xFF.

I need to use the solid-color background image along with another image. When viewed using an image viewer software on Windows, there is no color difference between this image and the background.

Below is the solid-color background image.
![bg](https://github.com/lvgl/lvgl/assets/88659564/b5950c72-413c-4d30-8ff5-f301543860bc)

However, after converting the background images using the online Image Converter, there is a significant color difference.
![20240709-110108](https://github.com/lvgl/lvgl/assets/88659564/34678335-f674-4e2e-b49d-30804668941c)

When the background image is stored in Flash and displayed using a PNG decoder, the color difference issue does not arise. Alternatively, manually modifying the c-array after conversion in Image Converter to 0xE6 00 also eliminates the color difference.

Therefore, I would like to inquire if there is a potential issue with the online Image Converter.

**Comment by kisvegabor** [comment]
Is it an option for you to update the LVGL v9? It would be much easier for us to fix this issue in v9.

**Comment by makun666** [comment]
Since our project is basically completed, it would be quite challenging to switch to using the lvgl v9 version.

Based on my understanding, there seems to be an issue with the online image converter, right?

Furthermore, I have tried selecting the v9 version on the online image converter, but the converted array is still problematic.

**Comment by liamHowatt** [comment]
Could you please send the PNG file for us to try to reproduce the off-by-one color value?

**Comment by makun666** [comment]
[bg.zip](https://github.com/user-attachments/files/16258061/bg.zip)
The one above is the solid color background image. 
You can try it out and will find that there are differences between the arrays obtained using the LVGL online image converter and directly converting a local file with a PNG decoder.

**Comment by xinsuinizhuan** [comment]
so we need the C++ version tools or functions, convert image and font, not online to convert.

**Comment by makun666** [comment]
> Could you please send the PNG file for us to try to reproduce the off-by-one color value?

Have you reproduced this problem using the pictures I sent?

**Comment by liamHowatt** [comment]
Yes, I found some flawed logic while using a debugger and confirmed a fix. Both v8 and v9 of the online converter have the issue. I opened a PR for each. Thanks for reporting it.
https://github.com/lvgl/lv_img_conv/pull/40
https://github.com/lvgl/lv_img_conv/pull/41

**Comment by liamHowatt** [comment]
I hope it doesn't ruin the dithering feature of the v8 converter.

**Comment by kisvegabor** [comment]
Actually the original solution should produce better result. What if we fix in the v8's PNG decoder [here](https://github.com/lvgl/lvgl/blob/release/v8.4/src/extra/libs/png/lv_png.c#L249C13-L249C26)? I wouldn't update `lv_color_make` in v8 as it might produce unexpected issues on other places, but we can replace this function with a more accurate conversation.

**Comment by liamHowatt** [comment]
My initial thought is that the tool is deviating from a standard way of converting between color spaces and it would be a big deal to change conversions everywhere to match the tool's unique conversion method. I can imagine an issue being opened where someone says there is a difference between the same image as PNG vs BMP, but upon investigation, the v8 BMP decoder only supports BMPs of the same color format so no conversion would happen there. Also, it seems to me that C array images will never have the color format converted at runtime.

Are there any other places in LVGL where color formats of images are converted using `lv_color_make` other than the PNG decoder? It seems like there isn't, so this change seems safe :+1:

**Comment by liamHowatt** [comment]
I see GIF converts color formats. It feels less likely to me that someone would want to match a GIF to a background color, but they very well could. It's something to consider for the change too.

Palettes should also be considered.

**Comment by kisvegabor** [comment]
The [JPEG decoder](https://github.com/lvgl/lvgl/blob/release/v8.4/src/extra/libs/sjpg/lv_sjpg.c#L759) can be also an issue.  However, as this the first time this issue came up, I think we are good with fixing the PNG decoder only.

**Comment by liamHowatt** [comment]
16 bit is working in this PR: #6626. I'm facing some challenges with 8 bit. Will revisit it soon.

**Comment by liamHowatt** [comment]
Not stale

**Comment by kisvegabor** [comment]
Should be fixed by #6626
