### ISSUE TITLE
Partly Screen Refresh

### ISSUE THREAD

**Issue by fatihozen3** [kisvegabor/lvgl#6496]
### Introduce the problem

I use IMXRT1170 mcu and LVGL v9.1.0 for now.

My screen size  800x480. I have 3 different pages. 1. and 2. pages' sizes are 800x480 but 3rd page is  600x240. I open this page with bottom direction gesture(swipe down as mobile phones quick settings menu).

When I change screen from 1 to 2 and I swipe down to open half sized page, I expect to see 3rd page on 2nd page but 3rd page opens and areas remaining from 3rd screen changes as previous screen was 1, but I was on 2nd page. It seems bad... How could I manage this ?

**Comment by liamHowatt** [comment]
Could you please send code to reproduce?

Also, are you able to specify the exact version of LVGL down to the commit?

Thanks!
