### ISSUE TITLE
Side effects inside assert statement

### ISSUE THREAD

**Issue by mdkendall** [kisvegabor/lvgl#6497]
### Introduce the problem

In addition to the special-type `LV_ASSERT_FOO` macros enabled by the `LV_USE_ASSERT_FOO` macros in `lv_conf.h`, there is an underlying LV_ASSERT macro which appears to be used 'bare' in handful of places.

Unlike the `LV_ASSERT_FOO` macros, this one cannot be disabled for two reasons. First, there appears to be no mechanism for doing so. Second, disabling it (by defining it to nothing) would cause problems because in at least one place it wraps a function call.

https://github.com/lvgl/lvgl/blob/ca70164c6b409ecfc09b407bd3d85c734fdfe67e/src/core/lv_refr.c#L587

### Proposal

Instead of
```
LV_ASSERT(lv_draw_buf_reshape( ... ) != NULL);
```
it would be better to use
```
lv_draw_buf_t *ret = lv_draw_buf_reshape( ... );
LV_ASSERT(ret != NULL);
```
Also, since this is a check for not null, `LV_ASSERT_NULL` can be used instead of `LV_ASSERT` here.

In general, expressions inside assertions should never have side effects, so that they can be safely eliminated from non-debug builds.

**Comment by kisvegabor** [comment]
Very true! 

Could you send a Pull request to fix it. I roccemend:
```c
lv_draw_buf_t *ret = lv_draw_buf_reshape( ... );
LV_ASSERT_NULL(ret);
```
I know it should be `LV_ASSERT_NOT_NULL`. It's my historical stupidity...
