### ISSUE TITLE
LVGL reset loop when creating an image

### ISSUE THREAD

**Issue by Gemelon** [kisvegabor/lvgl#6504]
### LVGL version

v8.3.11

### What happened?

I’m new to LVGL and try to make my first display layout.
My setup:
ESP32-S3-DevkitC-1 V1.1 N16R8
Display 2,8 Zoll LCD TFT ILI9341 with xpt2046 Touch
tft_eSPI 2.5.34
lvgl 8.3.11

In my test project I’m using lvgl 8.3.11 because I try to use SquareLine Studio.

It works fine as long as I don’t create an image. The image is displayed for one second an then the controller resets.

What can the problem be?

I found out that it depends on the size of she image.

### How to reproduce?

Load an Image

**Comment by liamHowatt** [comment]
Is the image a variable or a file?
