### ISSUE TITLE
Add a little dimension to the LVGL logo

### ISSUE THREAD

**Issue by kdschlosser** [kisvegabor/lvgl#6508]
### Introduce the problem

Not a problem at all. I git a little hair across my ass to give the LVGL logo some dimension.

### Proposal

This is the kind of thing companies pay some decent money for... You get it for the going rate of FREE..... I hope you like these and decide to use one or both. I can also make this animated but it would take me some time to do as I am not up to snuff with using blender. These are 2D images obviously but the actual work is a rendered 3D object. I have it saved as an STL, 3MF and OBJ currently. 

Tell me what you think

![lvgl_logo](https://github.com/user-attachments/assets/d61588ac-8ffa-44a0-a886-9fd7942c5d7e)

and even more depth

![lvgl_logo_metallic](https://github.com/user-attachments/assets/e46134ec-5a58-4326-b9d1-0b13a03b2635)

@kisvegabor

**Comment by kisvegabor** [comment]
Thanks Kevin! I think our designer has a solid vision about the design, however we could use it very well for a 3D demo later. Can you attach the STL and 3MF files?

**Comment by kdschlosser** [comment]
[lvgl_logo.zip](https://github.com/user-attachments/files/16243493/lvgl_logo.zip)

**Comment by kdschlosser** [comment]
The STL file is a little booger'd up for some reason. not sure why or maybe it's just the preview that is messed up.

**update**
It looks like it is the preview that is messed up and not the actual STL file. When I open it in Blender it looks OK. 


Here is another one with more file formats.
[lvgl_logo2.zip](https://github.com/user-attachments/files/16243631/lvgl_logo2.zip)

**Comment by kisvegabor** [comment]
Thank you!
It will be needed a little bit later (in a few months). I close this issue until then.
