### ISSUE TITLE
Software rotating (180°) of LV_COLOR_FORMAT_L8 doesn't work

### ISSUE THREAD

**Issue by razor5k** [kisvegabor/lvgl#6518]
### LVGL version

v9.1.0

### What happened?

I use the SSD1322 display controller and the color format L8. I tried to rotate the display by 180° but nothing happens. There's no specific rotate function implemented for L8.

### How to reproduce?

lv_draw_sw_rotate(src, dst, width, height, width, width, LV_DISPLAY_ROTATION_180, LV_COLOR_FORMAT_L8);

**Comment by kisvegabor** [comment]
Hi,

L8 support was really missing. I've added in in https://github.com/lvgl/lvgl/pull/6520
