### ISSUE TITLE
Significant performance difference between V8.3 and V9 when using SDL

### ISSUE THREAD

**Issue by darko31** [kisvegabor/lvgl#6524]
### LVGL version

v9.0.0

### What happened?

Hello,

first of all thank you very much for this awesome library. I am sure that everybody appreciates this kind of project.

While testing lv_port_pc_eclipse on my PC and also on the target hardware that has Weston running (IMX8ULP-EVK board
with 1280x720 screen attached to it), I noticed a significantly higher CPU usage on V9 version of the demo in comparison to the v8.3.

This is not such a big issue on the PC, but running the V9 demo on the IMX8ULP yields almost 100% CPU usage on a single core and somewhere around 10 FPS when the Analytics tab in the demo is showed with all the graphs.

The IMX8ULP is no powerhouse, it's a dual core ARM A35 running at 800MHz, but still, running the v8.3 version of the demo the FPS is stable at 33 FPS and CPU usage is around 50%.

This can be seen also with the natively compiled demos on the PC. Here's a comparison
![Screenshot from 2024-07-17 14-42-13](https://github.com/user-attachments/assets/82504ea5-f124-477f-af04-71615af1768d)

the left window is v9 version while the right one is v8.3.
I've set the resolution to 480x800, the CMake release is set to debug and LV_USE_ASSERT_MEM_INTEGRITY and 
LV_USE_ASSERT_OBJ are set to 0.

Is this difference because of the slightly different contents displayed on the screen or is something else at play?
The first Profile tab of the demo looks pretty much the same between v8.3 and v9 and v9 again has significantly higher CPU usage (5% vs 30%).

I ran both apps with with perf and loaded debug symbols for the libSDL2 and here are the captures
![lvgl_v8 3](https://github.com/user-attachments/assets/dfff7de4-6ccd-4123-98b7-2683713d86df)
![lvgl_v9](https://github.com/user-attachments/assets/537b8bad-f947-41c3-8d77-03d4bfe51050)

v8.3 and v9 seem to use a different way of rendering things, BlitRGBtoRGBPixelAlpha vs BlitNtoNPixelAlpha.

Excuse my lack of understanding, I'm still learning about the LVGL and SDL.

If you have some suggestions on how to optimize the V9 version, please share.

Thank you!
Darko

**Comment by kisvegabor** [comment]
Hi,

Thank you reporting this issue! An important questions: do use pure software rendering or do you use SDL rendering (`LV_USE_DRAW_SDL   1` in v9)

**Comment by darko31** [comment]
> Hi,
> 
> Thank you reporting this issue! An important questions: do use pure software rendering or do you use SDL rendering (`LV_USE_DRAW_SDL 1` in v9)

Ah, it is not enabled because if I enable it, it doesn't show any pictures at all and prints this error

`could not load image: SDL_RWFromFile(): No file or no mode specified`

Screenshoots below
![demo_analytics_9_1_draw_sdl](https://github.com/user-attachments/assets/a26afd9b-d80b-4315-81dd-c1c58fc8bf8d)
![demo_profile_9_1_draw_sdl](https://github.com/user-attachments/assets/073f8cbe-35bb-4e41-b7cf-a2a96f8dc374)

This is with release/v9.0 and release/v9.1 tags.

If I switch to the latest master (0a1e411038306b3fb4ee846dd6999907ef6222f2), the Profile page looks good
![demo_profile_master_draw_sdl](https://github.com/user-attachments/assets/a3d1850f-c9ff-4b5a-926f-f2baabbd2a0b)

but Analytics page is still looking weird
![demo_analytics_master_draw_sdl](https://github.com/user-attachments/assets/1b633b58-714d-4456-9a77-3acf54003374)

I'm looking into the updates in the lv_sdl_window.c but let me know if I should look at something else.
Thanks!

**Comment by kisvegabor** [comment]
On paper the v9 SDL implementation should be faster because it used XRGB8888 format instead of ARGB888 and it doesn't copy the rendered area to SDL's buffer, but renders directly there.

Maybe your devices likes ARGB888 more. Can you try changing [this line](https://github.com/lvgl/lvgl/blob/master/src/drivers/sdl/lv_sdl_window.c#L420) to `SDL_PIXELFORMAT_ARGB8888`?

Please keep using the software rendering. The SDL based rendering is being updated [here](https://github.com/lvgl/lvgl/pull/6437). I just wanted to be sure what you are using.

**Comment by darko31** [comment]
Okay, I'll try it out. Let me know if I can do some testing and/or debugging related to this although it seems that it can be consistently reproduced on a PC, it doesn't require some specific setup.

**Comment by darko31** [comment]
> On paper the v9 SDL implementation should be faster because it used XRGB8888 format instead of ARGB888 and it doesn't copy the rendered area to SDL's buffer, but renders directly there.
> 
> Maybe your devices likes ARGB888 more. Can you try changing [this line](https://github.com/lvgl/lvgl/blob/master/src/drivers/sdl/lv_sdl_window.c#L420) to `SDL_PIXELFORMAT_ARGB8888`?
> 
> Please keep using the software rendering. The SDL based rendering is being updated [here](https://github.com/lvgl/lvgl/pull/6437). I just wanted to be sure what you are using.

The default lv_conf.h in the lv_pc_port_eclipse has LV_COLOR_DEPTH set to 16, but after changing it to 32 and making the change you suggested, the CPU usage on the IMX8ULP drops down to around 52% to 60% and FPS is pretty stable at ~28 FPS when Analytics tab is open and scrolled down to the network speed widget. This is slightly higher than V8.3.

Thanks for the suggestion!

I'm interested to try out the https://github.com/lvgl/lvgl/pull/6437 to see how it works.

**Comment by kisvegabor** [comment]
Some performance issues are reported in https://github.com/lvgl/lvgl/pull/6437 too. I'll look into it this week. Let's continue in the PR.
