### ISSUE TITLE
Add a picture unlock widget, similar to the phone lock screen unlock interface.

### ISSUE THREAD

**Issue by LONGZR007** [kisvegabor/lvgl#6527]
### Introduce the problem

Something like:：
![QQ_1721284111972](https://github.com/user-attachments/assets/db7052b6-0ee5-4079-8aa7-021624bb8ac1)

**Comment by liamHowatt** [comment]
I think some people would find it useful but it seems fairly niche. Most of the widgets are common. Do you think it has a lot of use cases?

**Comment by kisvegabor** [comment]
I can imagine it rather as an example or part of demo.
