### ISSUE TITLE
lv_obj_set_property() function not work correctly when using style properties.

### ISSUE THREAD

**Issue by sliang951753** [kisvegabor/lvgl#6551]
### LVGL version

v9.0.0

### What happened?

The macro #define LV_PROPERTY_ID(clz, name, type, index)    LV_PROPERTY_## clz ##_##name = (LV_PROPERTY_## clz ##_START + (index)) | ((type) << LV_PROPERTY_TYPE_SHIFT)
defines a property ID. But it does not store the real "index", it adds the property id start value to the index.
For example, the index of LV_STYLE_X is  8,  however the LV_PROPERTY_STYLE_X stores LV_STYLE_X + LV_PROPERTY_STYLE_START = 9. The problem will occur when set this property by using lv_obj_set_local_style_prop(), the second argument is the index of the style property.  
I think the code should be 
lv_obj_set_local_style_prop(obj, index - LV_PROPERTY_STYLE_START, value->style, value->selector);
instead of 
lv_obj_set_local_style_prop(obj, index, value->style, value->selector);

Anyone can help to check this ?

**Comment by XuNeo** [comment]
I think I have covered the case here.

https://github.com/lvgl/lvgl/blob/daa7fefb3a4bd058f1c5b5166871085876d0ada4/tests/src/test_cases/widgets/test_obj_property.c#L38-L44

The index value for style property, is the value from `enum _lv_style_prop_t`

See lv_style_properties.h

```c
enum {
    LV_PROPERTY_ID(STYLE, ALIGN,                    LV_PROPERTY_TYPE_INT,        LV_STYLE_ALIGN),
    LV_PROPERTY_ID(STYLE, ANIM,                     LV_PROPERTY_TYPE_INT,        LV_STYLE_ANIM),
...
```

**Comment by XuNeo** [comment]
Sorry. After check the test code, the prop.id is wrong.

You are right. The style enum is offset by 1.

**Comment by sliang951753** [comment]
> Sorry. After check the test code, the prop.id is wrong.
> 
> You are right. The style enum is offset by 1.

prop.id = LV_STYLE_X;  // this works. 
prop.id = LV_PROPERTY_STYLE_X; // this doesn't work.

It looks your test case is not correct.

the STYLE property already starts from 1, so when making the PROPERTY_STYLE_X, we don't need to add the STYLE PROPERTY START ID.  

If we need to add the STYLE PROPERTY START ID to identify it is a style property, we need to substract the STYLE PROPERTY START ID when using it. 

Since I'm not familiar with the style subsystem design, could you help to check which solution is the best for this case ?

**Comment by XuNeo** [comment]
I drafted a fix, could you please check if it works for you?

**Comment by sliang951753** [comment]
> I drafted a fix, could you please check if it works for you?

It works. Thank you.
