### ISSUE TITLE
[LVGL_V9.10] Is the uint8_t preference_score of struct _lv_draw_task_t still under development?

### ISSUE THREAD

**Issue by panlin0** [kisvegabor/lvgl#6560]
### Introduce the problem

files:
src/draw/sw/lv_draw_sw.c
src/draw/nxp/pxp/lv_draw_pxp.c
src/draw/lv_draw.c

lv_draw.c /lv_draw_finalize_task_creation calls it without handling the return value of preference_score and evaluate_cb. Is this a feature reserved for later?

**Comment by kisvegabor** [comment]
It's rather a left over from earlier developments and return value should be removed. Are interested in contributing by sending a Pull request to remove the return values?
