### ISSUE TITLE
Thread sync signal / wait sometimes does not work properly on Windows platform.

### ISSUE THREAD

**Issue by sliang951753** [kisvegabor/lvgl#6563]
### LVGL version

v9.0.0

### What happened?

Because the v value of  struct lv_thread_sync_t does not explicitly be initialized on windows platform, it will be random and cause the thread sync function not work properly sometime.
`
lv_result_t lv_thread_sync_init(lv_thread_sync_t * sync)
{
    if(!sync) {
        return LV_RESULT_INVALID;
    }

    InitializeCriticalSection(&sync->cs);
    InitializeConditionVariable(&sync->cv);

    **sync->v = false;  // MUST initialize to false.  Make it behave the same as pthread port.**
 
    return LV_RESULT_OK;
}
`

**Comment by liamHowatt** [comment]
Thank you!  #6604
