### ISSUE TITLE
lv_port_stm_nucleo_g071rb SquareLine Studio project source files

### ISSUE THREAD

**Issue by JohnDZhang** [kisvegabor/lvgl#6566]
### Introduce the problem

The example lv_port_stm_nucleo_g071rb is particularly beautiful,
Where can I find the SquareLineStudio UI project source files of https://github.com/lvgl/lv_port_stm_nucleo_g071rb?
Many thanks for you!

**Comment by kisvegabor** [comment]
I think SquareLine can tell more about it. 
Please open a topic at https://forum.squareline.io/
