### ISSUE TITLE
CREATE_WAITABLE_TIMER_MANUAL_RESET and CREATE_WAITABLE_TIMER_HIGH_RESOLUTION has no undeclared

### ISSUE THREAD

**Issue by a1019657069** [kisvegabor/lvgl#6569]
### LVGL version

v9

### What happened?

lv_windows_context.c CREATE_WAITABLE_TIMER_MANUAL_RESET and CREATE_WAITABLE_TIMER_HIGH_RESOLUTION has no undeclared

**Comment by liamHowatt** [comment]
Related to #6428, fixed by #6425

Are you able to use a more recent version of LVGL that includes the fix?
