### ISSUE TITLE
Schedule of release 9.2

### ISSUE THREAD

**Issue by cristian-stoica** [kisvegabor/lvgl#6570]
### Introduce the problem

@kisvegabor When is the release 9.2 scheduled?
If the release is not imminent we would like to include several recent patches we've made if there is enough time for review.
Thank you

**Comment by kisvegabor** [comment]
I'd like to merge only one more PR: https://github.com/lvgl/lvgl/pull/6068

Can you send the patches next week?

**Comment by kisvegabor** [comment]
Once #6068 is merged I'd like to have 1 week of feature freeze. After that we are good to go! 

cc @XuNeo @FASTSHIFT @liamHowatt

**Comment by cristian-stoica** [comment]
yes - thank you

**Comment by kisvegabor** [comment]
Let's really set up a deadline otherwise we will never have a release 😀

Let's merge/add what we can this week and have a feature stop next week. What do you think?

**Comment by kisvegabor** [comment]
cc @XuNeo @FASTSHIFT @liamHowatt

**Comment by vwheeler63** [comment]
If you don't mind me asking -- is it okay to get the doc-builds fixes into this release?

**Comment by kisvegabor** [comment]
@vwheeler63 It would be great, but I need to take a deeper look at its current status.

**Comment by vwheeler63** [comment]
@kisvegabor Makes sense.

**Comment by kisvegabor** [comment]
Yes, we will merge what we can this week, and make release on Monday (August 26)

**Comment by kisvegabor** [comment]
@GorgonMeducer could you prepare a PR to update the CMSIS packs for the release?

**Comment by GorgonMeducer** [comment]
No problem. @kisvegabor

**Comment by kisvegabor** [comment]
v9.2 is released so closing this issue.
