### ISSUE TITLE
Add method to detect not synced Kconfig, specially for NuttX

### ISSUE THREAD

**Issue by XuNeo** [kisvegabor/lvgl#6576]
>              OK - it's a NuttX thing. It seems that NuttX takes a copy of LVGLs Kconfig file and uses it locally rather than using the LVGL one directly. Vaguely remember some NuttX discussion about this - so the solution is imperfect but I understand it now.

_Originally posted by @TimJTi in https://github.com/lvgl/lvgl/issues/6313#issuecomment-2245290554_

Since the build system of NuttX has limitation of using third-party Kconfig that downloaded during build. NuttX copies the Kconfig file to work around it. But when migrating between different LVGL version, it's likely happen the Kconfig is out of sync with LVGL's Kconfig. We can use version number to detect it and report error if so.

**Comment by TimJTi** [comment]
Is this something more related to NuttX, so we can let this auto-close here?

**Comment by kisvegabor** [comment]
I think so, however @XuNeo knows more about it.
