### ISSUE TITLE
Add `LV_OBJ_CLASS_GROUP_DEF_TRUE` to the Arc object so it can be used with rotary encoder indevs

### ISSUE THREAD

**Issue by 0xjmux** [kisvegabor/lvgl#6609]
### LVGL version

8.3

### What happened?

I want to use the "Arc" widget in a project that's using a rotary encoder as the sole input device, and am using EEZ-studio to generate the LVGL UI. I thought not being able to select the Arc widget to modify the value was an issue with the code generation, but it turns out that actually LVGL's Arc widget doesn't have the `LV_OBJ_CLASS_GROUP_DEF_TRUE` attribute. Can this be added to the Arc widget so it can be used with Rotary encoder input devices?

Thanks! 

* My original issue, for reference: https://github.com/eez-open/studio/issues/465

**Comment by kisvegabor** [comment]
I think makes sense. Can you send s PR for both v8.4 and master. Please also update docs to mention that now arc can navigated by keys.

**Comment by 0xjmux** [comment]
not stale; haven't had the time to get to this yet
