### ISSUE TITLE
Is there any official obj can be easy to Reflects the state of the hardware？

### ISSUE THREAD

**Issue by liriyao** [kisvegabor/lvgl#6644]
### Introduce the problem

In order to show a lively wifi icon on my embed linux device,i have to crate some img objs and prepare img infomation In advance.What's more, I also need to mix the code for the WiFi driver with the code for lvgl to build very easy wifi icon display logic。It was  suffered .Hope lvgl can support these common hardware.

**Comment by kisvegabor** [comment]
I suggest looking into [observers](https://docs.lvgl.io/master/others/observer.html). This a well know pattern to separate the data and UI.
