### ISSUE TITLE
LVGL and STM32 Integration Issue

### ISSUE THREAD

**Issue by Jamshaid13** [kisvegabor/lvgl#6656]
### Introduce the problem

I am working with LVGL v9.1.1, I am simulating it correctly in the simulator. When i do all the step of integration with STM32 Project (STM32CUBEIDE v1.16.0). I am getting these errors? why this is been happening. 

Is this toolchain issue/ any bug?

 

Note: i have cross verify my integration process by developing gui in LVGL v8.3 and integrating it with STM32CUBEIDE, that's working fine. 

![JamshaidUsman_0-1723094091220](https://github.com/user-attachments/assets/c6d88d11-01bc-425c-b433-bc2fd45c346c)

**Comment by kisvegabor** [comment]
You should remove the include from lv_conf.h. I hope it will solve it. 🤞
