### ISSUE TITLE
Kconfig file format error?

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#6659]
### LVGL version

v9.1.1

### What happened?

I was reading an article about Kconfig (from the Linux used in the NVIDIA realm) that showed some of the parsing source code from the Linux Kernel's `conf` program (which reads the Kconfig file).  What I saw in that source code was that it only accepted leading tab characters ('\t' or 0x09) in the input for "child" items.  The code I saw left no room for recognizing leading space characters (0x20).  However, I noticed that in LVGL's ./Kconfig file on line 1692 (the line after "config LV_USE_LIBINPUT" beginning with "bool") has 4 leading spaces in it instead of tabs, while the entire rest of the file uses leading tab characters.  While I have not been able to determine if this is a real issue or not with the context in which Kconfig would be used (appears to be including LVGL in a Linux Kernel?), I am reporting this in case it is because it appears to be unintentional.

### How to reproduce?

View ./Kconfig with an editor that can show the difference between leading spaces and tabs, and go to line 1692 (or if that line changed, search for LV_USE_LIBINPUT and look at the line immediate after it beginning with the word "bool").

![image](https://github.com/user-attachments/assets/aada0b04-e04d-4646-abe8-01524982b66d)

**Comment by kisvegabor** [comment]
Thank you for pointing it out! Seemingly it doesn't cause any issues, but it's be better to fix it for sure. 

LVGL is not integrated into the Linux kernel, but many RTOS-es and framewroks are using Kconfig too (Zephyr, NuttX, RT-Thread, ESP-IDF).

**Comment by vwheeler63** [comment]
@kisvegabor   Ah!  Submitted as PR #6695.

**Comment by kisvegabor** [comment]
Fixed by https://github.com/lvgl/lvgl/pull/6695
