### ISSUE TITLE
Roller Crashes If Only Given One String

### ISSUE THREAD

**Issue by DovahBrownies** [kisvegabor/lvgl#6660]
### LVGL version

9.1

### What happened?

The roller widget crashes if only a single string is provided as an option to choose from. Issues doesn't seem to exist in version 8.4.

Suspected culprit code:
https://github.com/lvgl/lvgl/blob/master/src/widgets/roller/lv_roller.c#L510-L515

![image](https://github.com/user-attachments/assets/2485923f-3453-4c72-8fd2-62648c9668df)

**Comment by liamHowatt** [comment]
Thanks!

**Comment by mvladic** [comment]
It doesn't crash anymore. But, something is odd when there is one option compared when there is two or more options.

One option:

![roller_with_one_option](https://github.com/user-attachments/assets/97fccb02-ae47-448f-a5b8-29fb9cc0543e)

Two options:

![roller_with_two_options](https://github.com/user-attachments/assets/ad8b7433-e3e2-4d04-8869-ad28de31ca9d)

**Comment by vwheeler63** [comment]
Good morning, @mvladic 

Nice screen capture to illustrate!  I believe you will find that behavior goes away if you remove the SCROLLABLE flag from the parent object like this:

```
lv_obj_remove_flag(ptr_to_parent_obj, LV_OBJ_FLAG_SCROLLABLE);
```

**Comment by mvladic** [comment]
Hm, it didn't help, same result.

**Comment by vwheeler63** [comment]
@kisvegabor  Gabor?  What did we miss?

**Comment by kisvegabor** [comment]
The roller is handled in the `LV_EVENT_PRESSING` so disabling scrolling won't help. 

What about ignoring event for 0 and 1 options like this?
```diff
diff --git a/src/widgets/roller/lv_roller.c b/src/widgets/roller/lv_roller.c
index 4c7893ed6..0eae6a351 100644
--- a/src/widgets/roller/lv_roller.c
+++ b/src/widgets/roller/lv_roller.c
@@ -349,10 +349,14 @@ static void lv_roller_event(const lv_obj_class_t * class_p, lv_event_t * e)
         refr_position(obj, LV_ANIM_OFF);
     }
     else if(code == LV_EVENT_PRESSED) {
+       if(roller->option_cnt <= 1) return;
+
         roller->moved = 0;
         lv_anim_delete(get_label(obj), set_y_anim);
     }
     else if(code == LV_EVENT_PRESSING) {
+       if(roller->option_cnt <= 1) return;
+
         lv_indev_t * indev = lv_indev_active();
         lv_point_t p;
         lv_indev_get_vect(indev, &p);
@@ -364,6 +368,8 @@ static void lv_roller_event(const lv_obj_class_t * class_p, lv_event_t * e)
         }
     }
     else if(code == LV_EVENT_RELEASED || code == LV_EVENT_PRESS_LOST) {
+       if(roller->option_cnt <= 1) return;
+
         release_handler(obj);
     }
     else if(code == LV_EVENT_FOCUSED) {
@@ -399,6 +405,8 @@ static void lv_roller_event(const lv_obj_class_t * class_p, lv_event_t * e)
         }
     }
     else if(code == LV_EVENT_KEY) {
+       if(roller->option_cnt <= 1) return;
+
         uint32_t c = lv_event_get_key(e);
         if(c == LV_KEY_RIGHT || c == LV_KEY_DOWN) {
             if(roller->sel_opt_id + 1 < roller->option_cnt) {
@@ -416,6 +424,8 @@ static void lv_roller_event(const lv_obj_class_t * class_p, lv_event_t * e)
         }
     }
     else if(code == LV_EVENT_ROTARY) {
+       if(roller->option_cnt <= 1) return;
+
         int32_t r = lv_event_get_rotary_diff(e);
         int32_t new_id = roller->sel_opt_id + r;
         new_id = LV_CLAMP(0, new_id, (int32_t)roller->option_cnt - 1);

```

**Comment by vwheeler63** [comment]
Interestingly, this might also apply to one of my LVGL projects here....  :-)

**Comment by liamHowatt** [comment]
> What about ignoring the events for 0 and 1 option count, like this?

LGTM.

Another possibility is letting the 1 option move. In that case, the fix would be to unfreeze the label in the selected area.

**Comment by kisvegabor** [comment]
I think `return`ing is simpler and we can easily improve it later if needed :slightly_smiling_face:
