### ISSUE TITLE
LV_MEM_SIZE Optimum Value

### ISSUE THREAD

**Issue by fatihozen3** [kisvegabor/lvgl#6663]
### Introduce the problem

Hi I use IMXRT 1176 MCU and LVGL v9.1.0 .

I have some screens and screen's have lots of objects. When I add big sized object to screen I get below error according to LV_MEM_SIZE and object's size.

![image](https://github.com/user-attachments/assets/4db11b9f-87d6-47e7-8f83-ef4f43dc2300)

I can pass this error by increasing LV_MEM_SIZE but is this the optimum solution ? Will I increase mem size when I add new object to the screen every time ? What is the optimum value according to my system ? Is there any upper limit for this mem size ? It is 300 kB for now and it may be increased... I think 300 kB is a lot. How can I pass this error without increasing Mem Size ?

**Comment by jbd1986** [comment]
The default size is QUITE low, but your target device plays a big role here.  We have 1GB of RAM on our system, so I've set LV_MEM_SIZE to 64MB (64 * 1024 * 1024).  I have no issues with that large of a max size.

**Comment by kisvegabor** [comment]
The default value is enough to run `lv_demo_widgets` which is considered a simple real-life-like UI.

You can set `LV_MEM_SIZE` to a larger value and enable `LV_USE_MEM_MONITOR`. This way you will see the current and max memory usage too.
