### ISSUE TITLE
Cannot disable build of demos, examples and thorvg

### ISSUE THREAD

**Issue by Vesek** [kisvegabor/lvgl#6668]
### LVGL version

v9.1.0-375-g8699a7e86

### What happened?

When `LV_BUILD_EXAMPLES` is set to `0` in `lv_conf.h` - cmake still builds examples.
The same applies to demos and thorvg.

Adding `LV_CONF_BUILD_DISABLE_EXAMPLES` as seen in `env_support/cmake/custom.cmake` also doesn't help. The only way to get rid of examples is by removing them from `custom.cmake`.

### How to reproduce?

1. set any of the variables metioned above to disabled and build
2. cmake still build examples

**Comment by kisvegabor** [comment]
This part is really not well documented/tested now. We have an open PR where we are about to make it better #6115
