### ISSUE TITLE
Vertical flickering background artifacts when `LV_THEME_DEFAULT_DARK=1`

### ISSUE THREAD

**Issue by IvanVnucec** [kisvegabor/lvgl#6674]
### LVGL version

v8.3

### What happened?

I'm using Sunton CYD (Cheap Yellow Display) PlatformIo Board.
The project is based on the [rzeldent/platformio-espressif32-sunton](https://github.com/rzeldent/platformio-espressif32-sunton).
I've enabled `LV_THEME_DEFAULT_DARK` flag in the `lv_conf.h` and added simple button to the default screen and the screen had strange flickering artifacts (see image below).

I've also tried `LV_THEME_DEFAULT_DARK=0` and the flickering disappears.
However, when I set darker grey background with `lv_obj_set_style_bg_color(lv_scr_act(), lv_palette_darken(LV_PALETTE_GREY, 3), 0)`, there is a visible stripe flickering at x=0. Moreover, every darken palette besides level 0 and 1 has stripe flickering.

![image](https://github.com/user-attachments/assets/dcbb482d-648d-4234-83af-66bd87735783)

### How to reproduce?

lv_conf.h:
```c
#define LV_USE_THEME_DEFAULT 1
#if LV_USE_THEME_DEFAULT

    /*0: Light mode; 1: Dark mode*/
    #define LV_THEME_DEFAULT_DARK 1

    /*1: Enable grow on press*/
    #define LV_THEME_DEFAULT_GROW 0

    /*Default transition time in [ms]*/
    #define LV_THEME_DEFAULT_TRANSITION_TIME 80
#endif /*LV_USE_THEME_DEFAULT*/
```

main.cpp:
```c
#include <Arduino.h>

#include <esp32_smartdisplay.h>
#include <lvgl.h>

void setup()
{
    smartdisplay_init();
    smartdisplay_lcd_set_backlight(1.0f);

    lv_disp_t *default_display = lv_disp_get_default();
    lv_disp_set_rotation(default_display, LV_DISP_ROT_270);

    // add button to the center
    lv_obj_t *btn = lv_btn_create(lv_scr_act());
    lv_obj_center(btn);
    lv_obj_t *label = lv_label_create(btn);
    lv_label_set_text_static(label, "Click me!");
}

void loop()
{
    lv_timer_handler();
}
```

**Comment by kisvegabor** [comment]
I think not an LVGL issue.

Please try painting the background to black and draw blue rectangle on top of it (as on your image) without using LVGL. You can check out how `smartdisplay` does that.
