### ISSUE TITLE
lv_obj_add_flag and remove_flag should check if the flag is already set/unset

### ISSUE THREAD

**Issue by lorddevereux** [kisvegabor/lvgl#6687]
### Introduce the problem

I recently ran into a case where a rogue function was continually calling **lv_obj_remove_flag(widget, LV_OBJ_FLAG_HIDDEN)** on a few widgets.
Every call causes the object to be invalidated and therefore redrawn even though it hasn't actually changed. This caused a massive performance impact (3 FPS -> 30 FPS!). Whilst it should be up to the user to make sure they don't call the function unnecessarily, I think patching to prevent this will save someone debugging in future.

Posting as a discussion before submitting PR in case someone think of a good reason not to do it!

### Proposal

Add to lv_obj_add_flag ~line 233
`if (obj->flags & f)`
`        return;`

Add to lv_obj_remove_flag ~line 270
`if (!(obj->flags & f))`
`        return;`

**Comment by kisvegabor** [comment]
Great catch!  Could you send a Pull request?

Just a minor change for `add` as it should work with ORed flags too (e.g. add `HIDDEN | IGNORE_LAYOUT`):
```c
if ((obj->flags & f) == f) /*Check if all flags are set*/
        return;
```

**Comment by kisvegabor** [comment]
No stale

**Comment by jurstu** [comment]
I believe I made the proposed changes. PR coming.
