### ISSUE TITLE
Arabic with vowels is not displayed correctly.

### ISSUE THREAD

**Issue by jihunluv** [kisvegabor/lvgl#6700]
### LVGL version

v9.1.0

### What happened?

I have no sense of Arabic characters but found an issue with rendering vowels. 

Below is GIMP output of string اللُّغَة

![image](https://github.com/user-attachments/assets/f88659f7-eb73-4361-b2e7-6dd846060a9f)

Below is Freetype enabled  LVGL v9.1.0 (LV_USE_BIDI  / LV_USE_ARABIC_PERSIAN_CHARS flags are on)
![image](https://github.com/user-attachments/assets/006b7bf8-3adb-4a53-b174-2944ddbff74f)

Can you help with this problem?

### How to reproduce?

void lv_example_freetype_1(void)
{
    /*Create a font*/
    lv_font_t * font = lv_freetype_font_create(PATH_PREFIX "lvgl/examples/libs/freetype/NotoSansArabic-Medium.ttf",
                                               LV_FREETYPE_FONT_RENDER_MODE_BITMAP,
                                               80,
                                               LV_FREETYPE_FONT_STYLE_NORMAL);

    if(!font) {
        LV_LOG_ERROR("freetype font create failed.");
        return;
    }

    /*Create style with the new font*/
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_text_font(&style, font);
    lv_style_set_text_align(&style, LV_TEXT_ALIGN_CENTER);

/*Create a label with the new style*/
    lv_obj_t * label = lv_label_create(lv_screen_active());
    lv_obj_add_style(label, &style, 0);
    // lv_label_set_text(label, "Hello world\nI'm a font created with FreeType");
    lv_label_set_text(label, "اللُّغَة");

    lv_obj_center(label);
}

**Comment by jihunluv** [comment]
I guess related issue is already discussed in below topic.

https://forum.lvgl.io/t/alternative-text-shaping-engine/12414

Any support in near future?

**Comment by kisvegabor** [comment]
LVGL's typesetting engine is okay, but don't cover all the cases. I've just opened an [issue](https://github.com/lvgl/lvgl/issues/6763) for the planned tasks of v9.3. Reworking the typesetting engine is not on the list now, but it will consider it for v9.4.

**Comment by jihunluv** [comment]
It is great news that you will consider the feature at least in v9.4. can you guess the timeline?

**Comment by kisvegabor** [comment]
v9.3 is for early 2025, so v9.4 or v10 can come in the second half of 2025. But it's a large feature, I can promise anything now. :slightly_frowning_face:

**Comment by MazdakFarzone** [comment]
@kisvegabor I have tampered with Harfbuzz and integrated it as a library in lvgl, it solves the shaping issue. Do you want to check it out? Or are we moving in another direction?

**Comment by jihunluv** [comment]
@MazdakFarzone, That's really great news. I wonder how much harfbuzz takes up the memory resources at the least. And I hope you could share some progress. @kisvegabor, I believe this feature will definitely improve the LVGL experience and its language coverage.
