### ISSUE TITLE
Different behavior regarding LV_EVENT_VALUE_CHANGED event when step is changed in Spinbox

### ISSUE THREAD

**Issue by mvladic** [kisvegabor/lvgl#6702]
### LVGL version

v9.1 v8.4

### What happened?

When step in Spinbox is changed with the encoder then LV_EVENT_VALUE_CHANGED event is sent, but when it is changed with the touch interface no LV_EVENT_VALUE_CHANGED event is sent.

****

### How to reproduce?

See below, first I change Spinbox step with the encoder button and in LV_EVENT_VALUE_CHANGED event handler I log the step change, but when I press with the touch the step position is changed but no LV_EVENT_VALUE_CHANGED event is sent, thus nothing is printed in the log.

![spinbox_step_change](https://github.com/user-attachments/assets/f50548b4-30f8-488d-8613-1099216e40f8)

**Comment by mvladic** [comment]
Here is the code responsible for this difference in behaviour:

![image](https://github.com/user-attachments/assets/381017ff-f717-4a17-aee3-008048265616)

**Comment by kisvegabor** [comment]
Hi,

We will release v9.2 on Monday (August 26). Can you send a PR to fix this issue? If so, I'll try my best to include it in the release.

**Comment by liamHowatt** [comment]
Fixed by #6719
