### ISSUE TITLE
could meter actualize radar image?

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6706]
### Introduce the problem

I want actualize this  radar image:
![图片](https://github.com/user-attachments/assets/f4b816e2-58dd-4c3f-b03b-4ca45e5ce619)

could meter actualize?

**Comment by kisvegabor** [comment]
You can use the circles as image by setting a `background_image`. The needles should be images as well, that can be rotated by LVGL automatically.
