### ISSUE TITLE
No custom swipe possible in LVGL 9

### ISSUE THREAD

**Issue by HokageM** [kisvegabor/lvgl#6707]
### Introduce the problem

I used a custom setting for `LV_INDEV_DEF_SCROLL_LIMIT` and `LV_INDEV_DEF_SCROLL_THROW`.

In LVGL 9, these defines are located inside the .cpp file, which prevents customization. Additionally, there is no function available to set the `scroll_limit` and `scroll_throw` for an lv_indev_t object.

### Proposal

I would suggest a function to set scroll_limit and scroll_throw:
```
lv_indev_set_scroll_limit()
lv_indev_set_scroll_throw()
```

**Comment by kisvegabor** [comment]
These setters are really missing.[ One was just added](https://github.com/lvgl/lvgl/pull/6664) in past days. Do have time and interest to contribute by adding API calls for the missing ones?

**Comment by HokageM** [comment]
Done :)

**Comment by kisvegabor** [comment]
Arigato, mighty Hokage-sama! The Hidden Leaf Village owes you a debt of gratitude! :blush:
