### ISSUE TITLE
why lv_demo_vector_graphic add draw text not show

### ISSUE THREAD

**Issue by xiangxud** [kisvegabor/lvgl#6716]
### LVGL version

v9.1.1

### What happened?

i use  lv_port_pc_visual_studio project and add function as follow ,    call draw_vector(&layer); not show text not call is show,why?

void lv_draw_text(void)
{
    lv_draw_rect_dsc_t rect_dsc;
    lv_draw_rect_dsc_init(&rect_dsc);
    rect_dsc.radius = 10;
    rect_dsc.bg_opa = LV_OPA_COVER;
    rect_dsc.bg_grad.dir = LV_GRAD_DIR_VER;
    rect_dsc.bg_grad.stops[0].color = lv_palette_main(LV_PALETTE_RED);
    rect_dsc.bg_grad.stops[0].opa = LV_OPA_100;
    rect_dsc.bg_grad.stops[1].color = lv_palette_main(LV_PALETTE_BLUE);
    rect_dsc.bg_grad.stops[1].opa = LV_OPA_50;
    rect_dsc.border_width = 2;
    rect_dsc.border_opa = LV_OPA_90;
    rect_dsc.border_color = lv_color_white();
    rect_dsc.shadow_width = 5;
    rect_dsc.shadow_offset_x = 5;
    rect_dsc.shadow_offset_y = 5;

    lv_draw_label_dsc_t label_dsc;
    lv_draw_label_dsc_init(&label_dsc);
    label_dsc.color = lv_palette_main(LV_PALETTE_ORANGE);
    label_dsc.text = "Some text on text canvas";

    lv_draw_buf_t* draw_buf = lv_draw_buf_create(WIDTH, HEIGHT, LV_COLOR_FORMAT_ARGB8888, LV_STRIDE_AUTO);
    lv_draw_buf_clear(draw_buf, NULL);

    lv_obj_t* canvas = lv_canvas_create(lv_screen_active());
    lv_canvas_set_draw_buf(canvas, draw_buf);
    lv_layer_t layer;
    lv_canvas_init_layer(canvas, &layer);
    lv_vector_dsc_t* ctx = lv_vector_dsc_create(&layer);
    lv_area_t coords_rect = { 400+100, 20+300, 600+100, 70+300 };
    lv_draw_rect(&layer, &rect_dsc, &coords_rect);

    lv_area_t coords_text = { 400+100, 80+300, 600+100, 120+300 };
    lv_draw_label(&layer, &label_dsc, &coords_text);
#if 1
    // call this the text not show
    draw_vector(&layer);
#endif
    lv_canvas_finish_layer(canvas, &layer);

}

**Comment by kisvegabor** [comment]
I cc @FASTSHIFT. He is the master of our vector API.  🙂
