### ISSUE TITLE
LVGL 9.2 arduino framework with ESP32-C3 module reboots repeatedly.

### ISSUE THREAD

**Issue by 43823845** [kisvegabor/lvgl#6745]
### Introduce the problem

How to comment out the following code    disp = lv_tft_espi_create(TFT_HOR_RES, TFT_VER_RES, draw_buf, sizeof(draw_buf)); Module returned to normal operation ，Does anyone know what's causing it?

Guru Meditation Error: Core  0 panic'ed (Store access fault). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x420507ec  RA      : 0x420507e4  SP      : 0x3fca6c80  GP      : 0x3fc8c600  
TP      : 0x3fc89c68  T0      : 0x00000003  T1      : 0xffc3ffff  T2      : 0x00000020  
S0/FP   : 0x3fca2b50  S1      : 0x00000000  A0      : 0x00000001  A1      : 0xffffffff  
A2      : 0x00000000  A3      : 0xfdffffff  A4      : 0x08000000  A5      : 0x00000010  
A6      : 0xffffffff  A7      : 0x04c4b400  S2      : 0x00000007  S3      : 0x00000001  
S4      : 0x000000a0  S5      : 0x3fc8dd6c  S6      : 0x00000a00  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x0196e6aa  T4      : 0x0000000f  T5      : 0x003c0000  T6      : 0x00000003  
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000010  
MHARTID : 0x00000000

**Comment by 43823845** [comment]
Analyze the problem and TFT_espi related, but the problem is still not solved, if the use of ESP32-PICO-D4 chip does not appear to restart the problem, can be used normally!

**Comment by liamHowatt** [comment]
Please first try increasing the memory available to LVGL in lv_conf.h
