### ISSUE TITLE
The physical keyboard cannot respond to long and short press events

### ISSUE THREAD

**Issue by lztmfx** [kisvegabor/lvgl#6747]
### LVGL version

V8.3.10

### What happened?

I adapted the keyboard based on "/dev/input/eventX" with reference to lvgl/src/examples/porting. I found that LVGL can only trigger the LV-EVENT_KEY event for this key, and cannot obtain the LV-EVENT_LONG_PRESSED, LV-EVENT_LONG_PRESSED-REPEAT, LV-EVENT_CLICKED events. This makes it impossible for me to use the keys to achieve more functions. Is it because lvgl's physical keys only support LV-EVENT_KEY? How can I make physical buttons support long and short press functions?

**Comment by kisvegabor** [comment]
This topic was already mentioned several times in the past. I see no issue with supporting LONG_PRESS and the other events with any keys. However in this case the user might need to call `lv_indev_get_type()` to see if a KEYPAD or a POINTER triggered the event, and get the key only in case of KEYPAD. 

@lztmfx We are fully booked with feature developments for the upcoming weeks, so I wonder if you are interested in sending PR with this update.
