### ISSUE TITLE
Is there a plan to make labels support color font？

### ISSUE THREAD

**Issue by ckoh01** [kisvegabor/lvgl#6755]
### Introduce the problem

Currently, due to the large size of bin format files convented with raw images, loading them from external flash takes a long time, which resulting in slow rendering speed.
If lv_font_conv can convert color fonts to bin format, the font bin file size should be much smaller. and get a high loading speed from extern flash.

### Proposal

https://github.com/googlefonts/noto-emoji
![5706](https://github.com/user-attachments/assets/8240e798-4c13-4abb-9dc9-59265b1031b8)

Step:
1.convert the raw image to SVG first, 
2.Then convent SVG to color fonts *.ttf on line(https://icomoon.io/app/#/select)
3.Then convent *.ttf to font bin files with lv_font_conv utils.  

Finally, we use lvgl widgets "labels" that support color font to display the image.
However, the current labels may not support color fonts. Is it possible for labels to have this feature in the future?

**Comment by kisvegabor** [comment]
I think you are looking for [image font](https://docs.lvgl.io/master/others/imgfont.html). You can store the images as indexed 8 bit too.

**Comment by ckoh01** [comment]
I thought [image font](https://docs.lvgl.io/master/others/imgfont.html) still use image array. which size is still a little big for loading from extern flash.

![15](https://github.com/user-attachments/assets/d58c088f-716b-4a5b-87d4-4d219be22234)

My goal is for the label to support color font. Is this feasible？

**Comment by kisvegabor** [comment]
Sorry, I don't understand the problem. So you can display the images from the Noto font but the color is incorrect?

**Comment by ckoh01** [comment]
sorry, i mean
[[LV_SYMBOL_](https://docs.lvgl.io/master/overview/font.html#fonts)](https://docs.lvgl.io/master/overview/font.html#special-fonts)
FontAwesome font can be showed in label widgets, but it alway show mono color(like red or else).

Noto font is a color font, can the label display Noto font's characters in color?

**Comment by liamHowatt** [comment]
This new feature might do exactly what you want :slightly_smiling_face: #6686

**Comment by kisvegabor** [comment]
Note that even FreeType support only bitmaps and not vectors. See [here](https://github.com/lvgl/lvgl/pull/6686/files#diff-5c88f9b0a37d8d678ec24b9eae8b59a25e1423543c7d9f12ff2c15d2c0bcd1bbR92-R94). 

For embedded I think the combination of SVG `lv_imagefont` would be nice. (SVG is on the roadmap of LVGL v9.3)
