### ISSUE TITLE
ime_pinyin array overwrite crash

### ISSUE THREAD

**Issue by squi2rel** [kisvegabor/lvgl#6756]
### LVGL version

v8.4.0

### What happened?

just repeat type one letter, it will crash
![image](https://github.com/user-attachments/assets/39a46071-aead-4a65-9a38-973d823d0bb8)

### How to reproduce?

In this example, I pressed 'a'
![image](https://github.com/user-attachments/assets/8bfcab84-5a30-45f3-b7a0-4dc6d5305279)

**Comment by kisvegabor** [comment]
Does it crash in v9.2 too?

**Comment by kisvegabor** [comment]
It seems working [here](https://docs.lvgl.io/8.3/others/ime_pinyin.html?highlight=pinyin) and [here](https://docs.lvgl.io/master/others/ime_pinyin.html#pinyin-ime) too.

**Comment by squi2rel** [comment]
The [example](https://docs.lvgl.io/master/others/ime_pinyin.html#example) also crash too
![image](https://github.com/user-attachments/assets/cc750d97-f3a6-4ab7-a41b-b8e585a89c7f)

**Comment by squi2rel** [comment]
The [example](https://docs.lvgl.io/master/others/ime_pinyin.html#example) also crash too
![image](https://github.com/user-attachments/assets/cc750d97-f3a6-4ab7-a41b-b8e585a89c7f)

**Comment by kisvegabor** [comment]
Please send a video. I've added like 50 `f`s and it's still working :smile:

**Comment by squi2rel** [comment]
https://github.com/user-attachments/assets/35013547-8b93-42c3-b6cd-e2dc4c442db3

maybe 70 letters?

**Comment by kisvegabor** [comment]
Okay, I crashed in v8 but worked in v9. It seems this PR fixed the issue: https://github.com/lvgl/lvgl/pull/6501/files

**Comment by lhdjply** [comment]
> Okay, it crashed in v8 but worked in v9. It seems this PR fixed the issue: https://github.com/lvgl/lvgl/pull/6501/files

It is crash in V9 too. see pr #6767
