### ISSUE TITLE
When rotating an object, the shadow will appear automatically?

### ISSUE THREAD

**Issue by M-D-777** [kisvegabor/lvgl#6772]
### LVGL version

v9.x

### What happened?

When rotating an obj, a shadow will automatically appear around the obj, even if I set the shadow width to 0.
When not rotating the obj, there is no shadow line.
![image](https://github.com/user-attachments/assets/da507faa-9c2e-4007-9e55-7ebab23256f5)
I would like to not have this shadow or have the option to turn it off.
Because I want to use this simple square obj to cover other obj to achieve a polygon effect.
Like This:
![image](https://github.com/user-attachments/assets/e5e7c51c-b23b-4f7d-ad27-4f62576efd6e)

### How to reproduce?

Both c and micropython versions can be reproduced
```obj = lv.obj(lv.screen_active())
obj.set_size(100, 100)
obj.set_pos(100, 100)
obj.set_style_radius(0, lv.PART.MAIN | lv.STATE.DEFAULT)
obj.set_style_shadow_width(0, lv.PART.MAIN | lv.STATE.DEFAULT)
# obj.set_style_shadow_spread(0, lv.PART.MAIN)
obj.set_style_border_width(0, lv.PART.MAIN | lv.STATE.DEFAULT)
obj.set_style_bg_color(lv.screen_active().get_style_bg_color(lv.PART.MAIN), lv.PART.MAIN | lv.STATE.DEFAULT)
obj.remove_flag(lv.obj.FLAG.SCROLLABLE)
obj.set_style_outline_width(0, lv.PART.MAIN | lv.STATE.DEFAULT)
obj.set_style_transform_pivot_x(50, 0)
obj.set_style_transform_pivot_y(50, 0)
obj.set_style_transform_rotation(450, 0)```

**Comment by M-D-777** [comment]
https://github.com/lvgl/lv_micropython/tree/841ece1321d462745fff3ef054780ae569292683
I have confirmed that this version does not have this issue. Looking forward to the new version resolving this issue. Thank you

**Comment by liamHowatt** [comment]
I reproduced it. I think it might not be a shadow. I think it's a rendering bug with rotation. When I set shadow opacity to transparent or shadow color to white, it's still there. I'm not sure what it would take to fix this. cc @kisvegabor

**Comment by kisvegabor** [comment]
I've just opened a PR to fix it. See #6794

The problem was with mixing the black color of transparent pixels.
