### ISSUE TITLE
Task dependency

### ISSUE THREAD

**Issue by cosmindanielradu19** [kisvegabor/lvgl#6784]
### Introduce the problem

As it was stated in [perf(nxp): v9.1.0 upstream vglite optimization](https://github.com/lvgl/lvgl/pull/6646), this patch lowers the CPU usage.

This change shown that there is a misbehaving of lv_layer and it should be analyzed and fixed in LVGL 9.3 as it was stated in [this comment](https://github.com/lvgl/lvgl/pull/6646#discussion_r1718069520)

### Proposal

[task_dependency.patch](https://github.com/user-attachments/files/16847553/task_dependency.patch)

**Comment by kisvegabor** [comment]
Thanks for opening this issue! I'll immerse in it again at the latest next week.

**Comment by kisvegabor** [comment]
I found it! :tada: See my long comment in the code in #6825

**Comment by cosmindanielradu19** [comment]
Thank you for the PR 👏
We will look into it during the next days

**Comment by nicusorcitu** [comment]
We will test it soon and see how it performs.

**Comment by nicusorcitu** [comment]
@cosmindanielradu19 please have it on TODO list.

**Comment by cosmindanielradu19** [comment]
> @cosmindanielradu19 please have it on TODO list.

I have tested the PR, and everything works great. The performance is the expected one.

**Comment by nicusorcitu** [comment]
We will cherry-pick this commit into our 9.2 branch.
@kisvegabor what is the plan for lvgl 9.3? Or will it be lvgl 10? Thanks.

**Comment by kisvegabor** [comment]
Amazing! :tada: 

We can release v9.2.1 when the the FreeRTOS realted fixes are also merged. I can cherry pick some of the fixes (including this one) to v9.2.1.

There is no reason to release v10 yet as there are no planned breaking changes. We are aiming to release v9.3 in early 2025. See [here](https://github.com/lvgl/lvgl/issues/6763)

**Comment by nicusorcitu** [comment]
What is the release date of 9.2.1?
I would like to push also some extra patches that broke the vglite support in 9.2 + some improvements.
Would be nice to have them all included in 9.2.1 too.

**Comment by kisvegabor** [comment]
No problem, we can wait a few weeks. What about October 1?

**Comment by nicusorcitu** [comment]
Perfect, we will push until Oct 1st. Thanks.
