### ISSUE TITLE
freertos mutex is recursive since #6573 but 'give' and 'take' macros are not recursive

### ISSUE THREAD

**Issue by razor5k** [kisvegabor/lvgl#6808]
### LVGL version

v9.2.0

### What happened?

In freertos #6573 the xSemaphoreCreateRecursiveMutex() is used now but the doc says that xSemaphoreGive() and xSemaphoreTake() shouldn't be used with recursive mutexes. I think that the recursive give and take variants should be used instead.

### How to reproduce?

```
pxMutex->xMutex = xSemaphoreCreateRecursiveMutex();
...
xSemaphoreGiveRecursive(pxMutex->xMutex);
...
xSemaphoreTakeRecursive(pxMutex->xMutex, portMAX_DELAY);

```

**Comment by razor5k** [comment]
6803 Fixes only the 'take' part but not the 'give'.

**Comment by kisvegabor** [comment]
Let's continue in the PR.
