### ISSUE TITLE
LV_ASSERT_STYLE failing during initialisation of default theme

### ISSUE THREAD

**Issue by TimJTi** [kisvegabor/lvgl#6809]
### LVGL version

v9.2.0

### What happened?

I enabled logging for other reasons and that allowed LV_ASSERT_STYLE  errors to be visible to me, and, with the addition of a little bit of code to aid tracing, I am seeing that every call to lv_style_set_prop is "failing" during the initialisation of styles of the default theme (line 289 of lv_style.c).

Foe example:

`lv_theme_default_init->style_init->lv_set_transition->lv_style_set_prop and the ASSERT is tripped`

This is a NuttX based custom application which is otherwise working OK.

Is this behaviour expected?

**Comment by kisvegabor** [comment]
Hi,

It's really strange and not the expected behavior for sure. I have no idea to be honest. 

cc @XuNeo
