### ISSUE TITLE
lv_obj_set_style_size(chart, 0, 0, LV_PART_INDICATOR); not working fine

### ISSUE THREAD

**Issue by ataweg** [kisvegabor/lvgl#6811]
### LVGL version

master

### What happened?

In my application, with the head revision of LVGL, only individual points were displayed in a chart instead of lines (lv_obj_set_style_size(chart, 0, 0, LV_PART_INDICATOR)). To rule out a problem on my side, I tried lv_example_chart_1.c with the help of lv_port_pc_visual_studio.

In order to find out from which commit the incorrect behavior occurs, I updated lvgl bit by bit. It turns out that the incorrect behavior occurs between commit a8c8275b560fa74b8bdd72d1d180c98d22a33fc8 (good) and the following 1d14386b99cdff731cc3367d1d8b5e96ffb8fcea (fail) from August 2nd.

>git checkout a8c8275b560fa74b8bdd72d1d180c98d22a33fc8
HEAD is now at a8c8275b5 feat(os): use recursive mutex by default (#6573)

F:\working\_Temp\lv_port_pc_visual_studio\LvglPlatform\lvgl\examples\widgets\chart\lv_example_chart_1.c

 ![Bild2](https://github.com/user-attachments/assets/ba29b0c6-fc65-4c62-9835-43033f905f22)
 
Added “    lv_obj_set_style_size(chart, 0, 0, LV_PART_INDICATOR);” after line 14

![Bild1](https://github.com/user-attachments/assets/9ffe4b22-901c-4832-b412-4df2ec4c7092)

>git checkout 1d14386b99cdff731cc3367d1d8b5e96ffb8fcea
Previous HEAD position was a8c8275b5 feat(os): use recursive mutex by default (#6573)
HEAD is now at 1d14386b9 refactor(API): don't expose private symbols in lvgl.h. phase-out "_lv*" names (#6068)

 ![Bild3](https://github.com/user-attachments/assets/48ccce31-add6-4853-bf78-73379179ff8e)

Added “    lv_obj_set_style_size(chart, 0, 0, LV_PART_INDICATOR);” after line 14

 ![Bild4](https://github.com/user-attachments/assets/ef5a71c9-e271-49ef-93d3-eb3b37b77a12)

**Comment by kisvegabor** [comment]
Hi,

Could you try with the latest `master`. It work well on my end.

**Comment by ataweg** [comment]
I still have the problem. Attached are the modified files so that the latest version (7f57f37560c29ae6007b828fb93a61764f483e1f) of lvgl works.

for for ...\lv_port_pc_visual_studio
[lvgl_issues_6811.zip](https://github.com/user-attachments/files/16978532/lvgl_issues_6811.zip)

for ...\lv_port_pc_visual_studio\LvglPlatform\lvgl
[lvgl_issues_6811-lvgl.zip](https://github.com/user-attachments/files/16978535/lvgl_issues_6811-lvgl.zip)

**Comment by ataweg** [comment]
When setting in lv_example_chart_1() 
````lv_obj_set_style_size(chart, 0, 0, LV_PART_INDICATOR);````

I dug a little deeper into lvgl and found  something not optimal in draw_series_line():
```
    if(LV_MIN(point_w, point_h) > line_dsc.width / 2) line_dsc.raw_end = 1;
    if(line_dsc.width == 1) line_dsc.raw_end = 1;
```
when I replave above with 
````line_dsc.raw_end = 1;````

I got 
![Bild5](https://github.com/user-attachments/assets/fd4fb846-99c4-476a-8118-bfcab80b15a9)
Not good, but I have lines.

**Comment by ataweg** [comment]
Running the example on an ESP32 is ok. 
Is it a grafic driver issue?

**Comment by kisvegabor** [comment]
I can't imagine how can it be a Windows driver issue. Dump question. Are you sure that you are using the same LVGL version. Using `git describe` is a giid way to check it

**Comment by ataweg** [comment]
I mean the graphical driver from lv_port_pc_visual_studio.

>git describe
v9.2.0-80-g48cbe7bd7
>git log -1
commit 48cbe7bd7653af00e14c28c339f27c5a4c408159 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabor Kiss-Vamosi <kisvegabor@gmail.com>
Date:   Wed Sep 25 11:39:51 2024 +0200
    perf(benchmark): use XRGB8888 image withn 32bit color depth (#6914)

It is noticeable that with the major conversion to private headers (https://github.com/lvgl/lvgl/commit/a8c8275b560fa74b8bdd72d1d180c98d22a33fc8 -->  https://github.com/lvgl/lvgl/commit/1d14386b99cdff731cc3367d1d8b5e96ffb8fcea ) this problem has occurred.

**Comment by kisvegabor** [comment]
It was really a large update but I wonder how can ir work on my end with SDL. 

cc @MouriNaruto

**Comment by MouriNaruto** [comment]
Windows driver should work as the same as SDL driver if SDL driver also uses the LVGL Software render.

Kenji Mouri

**Comment by kissa96** [comment]
Hi, how does this issue hold?

**Comment by ataweg** [comment]
Hi, the issue is still there with lv_port_pc_visual_studio commit  15ea92a227970cb766527071cc7737dfb5cf5e58 .  (The latest version has issues with Mile.Project.Windows).

Were you able to test it under the same conditions?
I use 
-   Microsoft Windows [Version 10.0.22631.4317]
 - Microsoft Visual Studio Community 2022 (64-Bit) - Current Version 17.11.5

I would be very surprised if this is a specific problem with my setup.

**Comment by Mair** [comment]
As reported by someone doing the LVGL, this is also affecting lines drawn in scales.
![image](https://github.com/user-attachments/assets/64e0e628-d483-46a0-bbb1-3acff622fe1b)

**Comment by kissa96** [comment]
Visual Studio has a known issue regarding line drawing.

**Comment by kisvegabor** [comment]
@MouriNaruto found the root of the problem and I've just opened a PR to fix it: https://github.com/lvgl/lvgl/pull/7171

Please confirm if its working well.

**Comment by ataweg** [comment]
Now it works as it should.
![Bild1](https://github.com/user-attachments/assets/40634368-f4c8-410c-a16e-642d312120f5)

**Comment by kisvegabor** [comment]
Amazing, thank you for the feedback!
