### ISSUE TITLE
Is there a non-packed monochrome mode in LVGL 9

### ISSUE THREAD

**Issue by alexriegler12** [kisvegabor/lvgl#6813]
### Introduce the problem

It seems that versions before 9 had a non packed monochrome mode that uses a bytě per pixel (instead of 8 pixels in one byte). Does something similar exist in LVGL 9.2?

**Comment by liamHowatt** [comment]
There is L8 what you're looking for? If you set `LV_COLOR_DEPTH` to `8`, each byte will be a grayscale "luminance" value from 0 to 255. You could try using it with the mono theme.

**Comment by alexriegler12** [comment]
should you just use the ternary operator to check if over 128 to make the pixel white?
