### ISSUE TITLE
How to input "^" with lv_keyboard?

### ISSUE THREAD

**Issue by lanistor** [kisvegabor/lvgl#6814]
### Introduce the problem

Is there a built-in keyboard supporting "^"? Or must redefine the buttons of keyboard?

**Comment by liamHowatt** [comment]
Do you know about [lv_keyboard_set_map](https://docs.lvgl.io/master/API/widgets/keyboard/lv_keyboard.html#_CPPv420lv_keyboard_set_modeP8lv_obj_t18lv_keyboard_mode_t)?

**Comment by kisvegabor** [comment]
It's really missing form the default layout, however I can't see where can we fit it. :slightly_frowning_face:

**Comment by liamHowatt** [comment]
Maybe we could add another `lv_keyboard_mode_t` with more symbols?

**Comment by kisvegabor** [comment]
Are there more missing symbols? I wouldn't add a new page for a single symbol.

**Comment by lanistor** [comment]
> Are there more missing symbols? I wouldn't add a new page for a single symbol.

I found these missing symbols : `~`, `^`, `\`` `|`.
