### ISSUE TITLE
How to modify the coordinates of the partial refresh area？

### ISSUE THREAD

**Issue by TopgunZh** [kisvegabor/lvgl#6821]
### LVGL version

v8.3.11

### What happened?

I have a screen resolution of 172x640. I tested and found that the starting coordinates x1 of the pixels I write cannot be odd numbers, otherwise the screen will tear.

Although I can solve this problem by turning on full screen refresh, I cannot use full screen refresh after turning on horizontal screen in lvgl.

So the problem I am facing now is that after turning the screen horizontally, I can’t refresh the full screen. How can I modify it so that the starting coordinates x1 of the local refresh area remain an even number?

### How to reproduce?

This is a defect in the screen driver itself, not a software problem. I want to limit the starting point coordinates by modifying the lvgl underlying driver.

**Comment by kisvegabor** [comment]
In v8 you can use a `rounder_cb`. See [here](https://docs.lvgl.io/8.4/porting/display.html#optional-fields)

For v9 I updated the docs in #6836

What is the name of your display controller? I'd like to mention it as an example in the docs.
