### ISSUE TITLE
Scrolling list of buttons by dragging often stops until touch is released

### ISSUE THREAD

**Issue by niklasf** [kisvegabor/lvgl#6828]
### LVGL version

v9.2.0

### What happened?

Try scrolling a list of buttons by dragging quickly.

Often the drag is stopped and scrolling does not continue until lifting the finger and trying again.

Sometimes the drag does not even start scrolling.

This worked smoothly in LVGL 8. Bisected to ecf1ea4d37833cd1b7b3f5d9fb6fabc5acb9850b as the first bad commit.

### How to reproduce?

Can be reproduced on touch display, but also by dragging the mouse in an SDL window.
```c
static void demo()
{
    lv_obj_t * screen = lv_obj_create(NULL);
    lv_obj_set_size(screen, 512, 600);
    lv_obj_set_flex_flow(screen, LV_FLEX_FLOW_COLUMN);

    for (int i = 0; i < 100; i++)
    {
        lv_obj_t * btn = lv_button_create(screen);
        lv_obj_set_size(btn, lv_pct(100), LV_SIZE_CONTENT);
        // Worse with: lv_obj_clear_flag(btn, LV_OBJ_FLAG_PRESS_LOCK);
    }

    lv_disp_load_scr(screen);
}
```

**Comment by kisvegabor** [comment]
Thanks for the report and the example code. I've just sent a fix. 

I removed the code added in https://github.com/lvgl/lvgl/commit/ecf1ea4d37833cd1b7b3f5d9fb6fabc5acb9850b. In my tests the  issues that it was attempting to fix is not showing up in my PR either.
