### ISSUE TITLE
Slider Events for Knob

### ISSUE THREAD

**Issue by fatiihyildizz** [kisvegabor/lvgl#6862]
### LVGL version

v9.1.0

### What happened?

I cannot scroll in the areas of the knob that are outside the slider bar. It does not detect an event. Why might this be happening?

![image](https://github.com/user-attachments/assets/52e9b630-5f13-4372-b236-4f50335f4a52)

**Comment by C47D** [comment]
> I cannot scroll in the areas of the knob that are outside the slider bar.

What do you mean with scroll?

1. The knob not going all the way to the slider edge OR
2. Not being able to detect a click there?

As far as I know the widget is designed so the knob center is the limit of movement for the knob. If you meant option 2, you can use [extended-click-area](https://docs.lvgl.io/latest/en/html/widgets/obj.html#extended-click-area)

**Comment by fatiihyildizz** [comment]
Hi,
I was talking about option 2. And this function worked for me.

Thank you

**Comment by kisvegabor** [comment]
> If you meant option 2, you can use [extended-click-area](https://docs.lvgl.io/latest/en/html/widgets/obj.html#extended-click-area)

Confirmed

**Comment by kisvegabor** [comment]
As the question seems to be answered I close this issue.
