### ISSUE TITLE
label bug

### ISSUE THREAD

**Issue by zzzlll111** [kisvegabor/lvgl#6868]
### LVGL version

v8.2

### What happened?

4 labels of the same size and height arranged in the horizontal coordinate of 12, 21, 25 will cause a slow refresh under arm or the number of labels is 8 or 16 will also cause a slow refresh of the screen if the spacing or the number is not a multiple of 8

### How to reproduce?

![KA1N7 %DB`V4 G1()1A } 9](https://github.com/user-attachments/assets/a77d2590-4208-4c83-9900-43530756b0c5)
The label here is my 100ms accumulated once, but the naked eye can see that it is not refreshed at one time, but if you add one more label or change the label spacing, this problem will not occur

**Comment by kisvegabor** [comment]
What was the problem?
