### ISSUE TITLE
Parent size not calculated correctly if obj not in the Y center.

### ISSUE THREAD

**Issue by FloHomi** [kisvegabor/lvgl#6872]
### LVGL version

v9.2.0

### What happened?

the get size of the parent obj ist not beeing calculated correctly, if children are not exacly in the center. 
(maybe something similar to #6837) 
Using flex works 
`    lv_obj_set_flex_flow(icon_button, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(icon_button, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
`

### How to reproduce?

    lv_obj_t* cont1 = lv_obj_create(lv_scr_act());
    lv_obj_set_size(cont1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_t* label1 = lv_label_create(cont1);
    lv_label_set_text(label1, "LOOOOOOOOOONG");
    lv_obj_align(label1, LV_ALIGN_CENTER, 0, 40);   
    //lv_obj_align(label1, LV_ALIGN_CENTER, 40, 0);    //with x offset it gets the right width

    lv_obj_t* cont2 = lv_obj_create(lv_scr_act());
    lv_obj_set_size(cont2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_t* label2 = lv_label_create(cont2);
    lv_label_set_text(label2, "LOOOOOOOOOONG");
    lv_obj_align(label2, LV_ALIGN_CENTER, 0, 0);

    lv_obj_update_layout(cont1);
    int width1 = lv_obj_get_width(cont1);   //38
    int width2 = lv_obj_get_width(cont2);  //188
    return;

**Comment by kisvegabor** [comment]
@liamHowatt could you take a look at it?
