### ISSUE TITLE
Return values from lv_malloc_zeroed in lv_draw not checked

### ISSUE THREAD

**Issue by pfvogel** [kisvegabor/lvgl#6877]
### LVGL version

9.3.0

### What happened?

Running the get_started_example_2 on custom platform resulted in a hard fault.  I tracked it down to a NULL return from lv_malloc_zeroed in the lv_draw_add_task routine that was not checked prior to dereferencing.  It appears that both lv_draw_add_task and lv_draw_create_unit do not check the return value.

### How to reproduce?

On my platform, running the getting_started_example_2 with a stack size of 8k caused the problem.  I was able to avoid the issue by increasing the stack size to 16k

**Comment by kisvegabor** [comment]
It's interesting because 8kB should be enough for such an example. 

Probably some similar error checks are really missing. Would you be open to creating a Pull requqst to fix some of these?

**Comment by pfvogel** [comment]
Sorry, this fell off my radar.  I will create a PR  with the additional checks on the malloc returns.
