### ISSUE TITLE
Lvgl deinit functions are not freeing resources

### ISSUE THREAD

**Issue by AmritpalSinghSarao** [kisvegabor/lvgl#6886]
### LVGL version

8.3.11

### What happened?

(00:00:00.177) Free heap: 277420 bytes
W (00:00:00.183) Minimum heap ever reached: 277012 bytes
W (00:00:00.190) Free heap for 8-bit allocations: 277420 bytes
I (00:00:00.200) Install panel IO
I (00:00:00.204) Install SSD1306 panel driver
I (00:00:00.302) Initialize LVGL
W (00:00:00.302) Free heap: 276656 bytes
W (00:00:00.303) Minimum heap ever reached: 276656 bytes
W (00:00:00.310) Free heap for 8-bit allocations: 276656 bytes
I (00:00:00.318) LVGL: Starting LVGL task
W (00:00:00.329) lcd_panel.io.i2c: Callback on_color_trans_done was already set and has now been overwritten!
I (00:00:00.344) LCD display initialized
W (00:00:00.345) Free heap: 255548 bytes
W (00:00:00.347) Minimum heap ever reached: 255548 bytes
W (00:00:00.354) Free heap for 8-bit allocations: 255548 bytes
I (00:00:00.369) Starting to deinitialize Display!
W (00:00:00.374) Free heap: 252860 bytes
W (00:00:00.380) Minimum heap ever reached: 252860 bytes
W (00:00:00.387) Free heap for 8-bit allocations: 252860 bytes
I (00:00:00.462) Display turned on
I (00:00:00.502) Display turned off
I (00:00:00.506) esp_lcd_panel_del
W (00:00:00.506) Free heap: 252860 bytes
W (00:00:00.508) Minimum heap ever reached: 252860 bytes
W (00:00:00.515) Free heap for 8-bit allocations: 252860 bytes
I (00:00:00.523) esp_lcd_panel_io_del
W (00:00:00.529) Free heap: 252932 bytes
W (00:00:00.535) Minimum heap ever reached: 252860 bytes
W (00:00:00.542) Free heap for 8-bit allocations: 252932 bytes
I (00:00:00.550) lvgl_port_deinit
W (00:00:00.556) Free heap: 253280 bytes
W (00:00:00.562) Minimum heap ever reached: 252860 bytes
W (00:00:00.569) Free heap for 8-bit allocations: 253280 bytes
I (00:00:00.577) i2c_driver_delete
W (00:00:00.582) Free heap: 253412 bytes
W (00:00:00.588) Minimum heap ever reached: 252860 bytes
W (00:00:00.596) Free heap for 8-bit allocations: 253412 bytes
I (00:00:00.604) Done
W (00:00:03.622) Free heap: 258196 bytes
W (00:00:03.622) Minimum heap ever reached: 252860 bytes
W (00:00:03.623) Free heap for 8-bit allocations: 258196 bytes

From the logs, it seems that after deinitializing the display with lvgl_port_deinit() and lv_deinit(), the heap memory is not fully recovered to its original state. You can see that there are changes in the free heap but the memory doesn't fully return to what it was before the initialization of the display and LVGL.

**Comment by kisvegabor** [comment]
If I recall correctly it really wasn't perfect in v8. Is migrating to v9 an option for you?

**Comment by kissa96** [comment]
Hi @AmritpalSinghSarao have you resolved this issuse?

**Comment by kisvegabor** [comment]
Closing in lack of feedback.
