### ISSUE TITLE
When I compiled lvgl_demos, the memory quickly reached 27G and the computer crashed

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#6918]
### LVGL version

9.3

### What happened?

newest code,compile in widows with cmake and vs2019, compile the lvgl first, then when compile the  lvgl_demos,the memory quickly reached 27G and the computer crashed

**Comment by xinsuinizhuan** [comment]
I find the error, when compile the svg tiger.c file,the memery will quickly reached 27G

**Comment by liamHowatt** [comment]
The Visual Studio compiler uses over 27 GB of RAM to compile tiger.c from #6845?

**Comment by xinsuinizhuan** [comment]
> The Visual Studio compiler uses over 27 GB of RAM to compile tiger.c from #6845?

yes.

**Comment by xinsuinizhuan** [comment]
have solved this issue?

**Comment by liamHowatt** [comment]
That file is gone now for unrelated reasons so try again.

For reference, here was the file before it was removed: https://github.com/lvgl/lvgl/blob/b7b2c9b7e348f538dd667e80795cff5d3ee9e0a0/demos/svg/assets/tiger.c
