### ISSUE TITLE
In rt-thread, the msinttypes in the latest lvgl version caused the compilation to fail

### ISSUE THREAD

**Issue by hydevcode** [kisvegabor/lvgl#6919]
### LVGL version

v8.3-latest v9.2.0 v9.1.0 latest

### What happened?

I tried to use the latest lvgl package under stm32f407-rt-spark and found that when I compiled it, I got some error

<img width="425" alt="微信图片_20240924140930" src="https://github.com/user-attachments/assets/f4450ef1-d7c9-409a-b4f7-1369bf33dd0b">

But when I removed the msinttypes, the program compiled normally

I found that the SConscript in env_support probably compiled msinttypes along with it, and then I just excluded msinttypes in SConscript and it was ready to use

<img width="796" alt="微信图片_20240924143332" src="https://github.com/user-attachments/assets/62bbe724-f912-4534-997f-4187dab7b417">

### How to reproduce?
In rt-thread, update the lvgl version to the latest
_No response_

**Comment by kurisaW** [comment]
@mysterywolf 满老师一起帮忙看看这个问题昂，这是之前说的lvgl软件包版本问题，这个问题主要是lvgl那边在新版本中加入了src/libs/thorvg/rapidjson/msinttypes目录下的两个头文件，但实际这两个文件我们是不必要的，现在看来不只是最新的版本存在问题，从8.xx_latest版本就已经存在这个问题了，对于这些已经发布的版本应该怎么处理好？这位同学已经基于星火一号在各个版本的lvgl软件包上测试并运行过了

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/6938 is merged so I close this issue.
