### ISSUE TITLE
refresh problem

### ISSUE THREAD

**Issue by zzzlll111** [kisvegabor/lvgl#6920]
### LVGL version

v8.2

### What happened?

Why can't local refresh schedule CPU utilization, which may cause the picture to stall, while global refresh can quickly schedule CPU utilization

**Comment by kisvegabor** [comment]
What  do you mean by CPU utilization?

**Comment by zzzlll111** [comment]
I'm sorry, maybe there's something wrong with my expression because I'm using a translation software
![image](https://github.com/user-attachments/assets/794feb40-640b-419d-8d47-1baa456e9721)

**Comment by kisvegabor** [comment]
I'm sorry I don't uderstand what the problem is
