### ISSUE TITLE
style line color not displaying in Horizontal Mode

### ISSUE THREAD

**Issue by rebibb** [kisvegabor/lvgl#6930]
### LVGL version

V9.1

### What happened?

creating simple scale with colored ranges.  If created in HORIZONTAL MODE... the styles for the ranges do not show.  If created in MODE_VERTICAL... the range styles work - specifically main line width and line color for LV_PART MAIN

### How to reproduce?

#include "Arduino_H7_Video.h"
#include "Arduino_GigaDisplayTouch.h"

#include "lvgl.h"

Arduino_H7_Video Display(800, 480, GigaDisplayShield); /* Arduino_H7_Video Display(1024, 768, USBCVideo); */
Arduino_GigaDisplayTouch TouchDetector;
/**
 * A simple horizontal scale - just a bar really
 */
void setup() {
  Display.begin();
  TouchDetector.begin();

  lv_obj_t* screen = lv_obj_create(lv_scr_act());
  lv_obj_set_size(screen, Display.width(), Display.height());

  lv_obj_t* scale = lv_scale_create(lv_screen_active());
  lv_obj_set_size(scale, 300, 200);
  lv_scale_set_label_show(scale, false);
  lv_scale_set_mode(scale, LV_SCALE_MODE_HORIZONTAL_TOP);
  lv_obj_center(scale);

  lv_scale_set_total_tick_count(scale, 21);
  lv_scale_set_major_tick_every(scale, 5);
  lv_scale_set_range(scale, 0, 100);

  static lv_style_t main_line_style;
  lv_style_init(&main_line_style);

  /* Main line properties */
  lv_style_set_line_color(&main_line_style, lv_palette_main(LV_PALETTE_GREEN));
  lv_style_set_line_width(&main_line_style, 20);  // main line width
  lv_obj_add_style(scale, &main_line_style, LV_PART_MAIN);

  /* Add a caution range  */

  static lv_style_t caution_main_line_style;
  lv_style_init(&caution_main_line_style);

  /* Main line properties */
  lv_style_set_line_color(&caution_main_line_style, lv_palette_main(LV_PALETTE_YELLOW));
  lv_style_set_line_width(&caution_main_line_style,20); /*main line width in caution */

  /* Configure section  styles */
  lv_scale_section_t* caution = lv_scale_add_section(scale);
  lv_scale_section_set_range(caution, 50, 75);
  lv_scale_section_set_style(caution, LV_PART_MAIN, &caution_main_line_style);
}
void loop() {
  lv_timer_handler();
}

**Comment by kisvegabor** [comment]
Let's continue in the PR
