### ISSUE TITLE
Software drawing issue

### ISSUE THREAD

**Issue by cosmindanielradu19** [kisvegabor/lvgl#6934]
### LVGL version

v9.2

### What happened?

Using the MIMXRT1170-EVK, I ran the demo benchmark and I've discovered that if I'm using SW + PXP as draw units, there are some issues with the output on "Containers with overlay" test.

I've minimized the test to only one container, without any components (basically, just the panel, without labels, images, etc).

For each frame generated, we have 4 tasks that runs.

![tasks_order](https://github.com/user-attachments/assets/4cd74373-b346-44ad-b8b2-93de5a876309)

PXP invalidates the whole cache before drawing, but the result is still wrong on the rounded corners.

![drawn_frame](https://github.com/user-attachments/assets/fea628b7-54a9-41c0-a587-9a3e3c85620d)

When all the containers are enabled, but without content, all the corners are wrong.

![all_containers](https://github.com/user-attachments/assets/d6aaf841-cf70-4969-97a9-570857c3d828)

### How to reproduce?

```c
#define LV_USE_OS   LV_OS_FREERTOS
#define LV_DRAW_SW_DRAW_UNIT_CNT    1
#define LV_USE_DRAW_PXP 1
#define LV_USE_PXP_DRAW_THREAD 1
```

or

```c
#define LV_USE_OS   LV_OS_NONE
#define LV_DRAW_SW_DRAW_UNIT_CNT    1
#define LV_USE_DRAW_PXP 1
```

**Comment by nicusorcitu** [comment]
![image](https://github.com/user-attachments/assets/f62e56cb-435c-4eda-8a19-d074e74d2f32)
Before each PXP operation, there is a clean and invalidate cache for the whole area it will touch.
![image](https://github.com/user-attachments/assets/e3d7f11d-49e8-41b2-a060-511201b20626)
More precisely, in case of the fill screen, the PXP will invalidate the cache for the entire framebuffer.
So everything that CPU does on the framebuffer should have been complete before PXP run.

What we observed is that if we run "invalidate ALL data cache" instead, it will fix this problem.

But this does not make sense at all. Why should we care about other data addresses than the one where PXP is going to have access?!
Same issue happens also with VGLite + CPU (If we make VGLite to handle only the fill screen and CPU to handle the rounded rectangles).

**Comment by nicusorcitu** [comment]
@kisvegabor this is more like an informational ticket.
We need to understand what CPU does when it draw a rounded rectangle + border. Because the invalidate cache for the whole framebuffer seems to not be enough.

**Comment by kisvegabor** [comment]
So what I see from the image is 
1. PXP fills the screen to grey correctly
2. SW renders the rounded corners correctly
3. PXP doesn't fill the area correctly with the overlay.

As you "sync" the cache before each PXP operation the SW rendered content should b ready to use by PXP. 

The obvious issue seems like PXP's `_invalidate_cache` is calculating the area incorrectly, doesn't invalidate the area correctly. I'm not sure just thinking aloud: maybe you need to wait for finishing the invalidation of a line or similar issues.

> We need to understand what CPU does when it draw a rounded rectangle + border. 

Really nothing special in this regard. Allocates a buffer for masking, calculate the rounded corners there and, blend the result. All pure software rendering.

**Comment by nicusorcitu** [comment]
> The obvious issue seems like PXP's _invalidate_cache is calculating the area incorrectly
This is what we thought initially, but it is not: the PXP will invalidate the full framebuffer:
https://github.com/lvgl/lvgl/blob/48cbe7bd7653af00e14c28c339f27c5a4c408159/src/draw/nxp/pxp/lv_draw_buf_pxp.c#L72
We checked and the address and size are correct.

> Allocates a buffer for masking, calculate the rounded corners there, and blend the result. All pure software rendering.
This should have been complete if we invalidate the full framebuffer?
Could it be the CPU is still writing to the temporarly buffer allocated for masking while the CPU draw function returns?

**Comment by kisvegabor** [comment]
> This should have been complete if we invalidate the full framebuffer?
Could it be the CPU is still writing to the temporarly buffer allocated for masking while the CPU draw function returns?

Nope, SW rendering is simple sequential. If an RTOS is used:
1. take a tasks
2. Mark it as `LV_DRAW_TASK_STATE_IN_PROGRESS`
3. Notify the rendering thread
4. The rendering thread draws it
5. The rendering thread marks the task as `LV_DRAW_TASK_STATE_READY`
6. The rendering thread calls `lv_draw_dispatch_request()`.

**Comment by nicusorcitu** [comment]
We found the rootcause and fixed it. It was pretty simple, size was wrongly set to uint16:
![image](https://github.com/user-attachments/assets/d29ddfc3-7040-4c90-a77c-0125953ce3f6)
We can close this ticket now.

We will prepare the patches to be pushed upstream, hopefully today to get into 9.2.1.
Thanks!

**Comment by vwheeler63** [comment]
> Aaaaaah! I can feel what you might felt after many hours of debugging. 😮‍💨

I'll bet you $1 that this is one of those things that the Visual Studio compiler complains about in `lv_port_pc_visual_studio` (silent narrowing conversion warning), though I cannot get `lv_draw_buf_pxp.c` to compile to test it (though setting LV_USE_DRAW_PXP to 1) because I don't have `lvgl_support.h`, `fsl_cache.h`, and `fsl_pxp.h`.  I'm curious if I may be missing an update....

**Comment by nicusorcitu** [comment]
You probably missed some files or you don't have the proper include path to find these headers on the preprocessing stage during compile time.

**Comment by vwheeler63** [comment]
> You probably missed some files or you don't have the proper include path to find these headers on the preprocessing stage during compile time.

`lvgl_support.h` is literally nowhere in the `lv_port_pc_visual_studio` subdirectories.  I thought maybe it would come with some `lvgl/lvgl` updates so I manually did a `git fetch` and updated my `master` branch, but it is still not there.  The other 2 files are also not within that directory structure.  Where are they supposed to be?

**Comment by nicusorcitu** [comment]
Please generate a SDK https://mcuxpresso.nxp.com/en/select for your board and you will have everything in place.
You will need also the PXP driver files. Those are not inside the lvgl library.

**Comment by vwheeler63** [comment]
> You will need also the PXP driver files. Those are not inside the lvgl library.

Ahh!  That answers my question!  Thank you!!
