### ISSUE TITLE
Add back label recoloring

### ISSUE THREAD

**Issue by kisvegabor** [kisvegabor/lvgl#6944]
### Introduce the problem

As [requested by multiple people](https://github.com/lvgl/lvgl/issues/6019) the label recoloring feature of v7 and v8 should be added back.

### Proposal

The same code that we had in v8 should work in v9 too. To re-implement this feature mainly these parts needs to be added again:
- https://github.com/lvgl/lvgl/blob/release/v8.4/src/widgets/lv_label.c#L484-L489
- https://github.com/lvgl/lvgl/blob/release/v8.4/src/draw/lv_draw_label.c#L244-L282
- https://github.com/lvgl/lvgl/blob/release/v8.4/src/misc/lv_txt.c#L196-L205

In general searching for `LV_TEXT_FLAG_RECOLOR` should be a good starting point.

**Comment by C47D** [comment]
I can take over this if you still need the help @kisvegabor

**Comment by kisvegabor** [comment]
Fantastic! Thank you Carlos! :heart: 

> I guess also we need to add:

All seems correct.

**Comment by kisvegabor** [comment]
Done in https://github.com/lvgl/lvgl/pull/6966

Thank you Carlos! :pray:
