### ISSUE TITLE
Creating the same output as in version 5.3

### ISSUE THREAD

**Issue by SalahuddinAsh** [kisvegabor/lvgl#6962]
### LVGL version

5.3

### What happened?

I used to generate C arrays for my fonts using the online font converter version 5.3 using this link https://lvgl.io/tools/font_conv_v5_3

The generated arrays used to have the character as comments beside the code itself as in this screenshot
<img width="356" alt="image" src="https://github.com/user-attachments/assets/7ea09815-b258-4bd4-afef-a7563fe846d2">
 
 The glyph descriptors used to be simple with w_px and glyph_index only
 
<img width="534" alt="image" src="https://github.com/user-attachments/assets/c50acea2-ad42-4f2a-9cf0-9fc287d7dbbe">

This used to work fine with my code

Currently as the link to font converter 5,3 is not valid anymore, when I try to create a C array with the current font converter I get completely different output with a much bigger glyph descriptor and there is no symbol for the character as comments beside the code itself.

I also tried to run the offline tool https://github.com/lvgl/lv_font_conv  but the output was the same

lv_font_conv --font JetBrainsMono-Bold.ttf -r 0x20-0x7f --size 24 --format lvgl --lv-include lvgl.h --bpp 1 -o myfont.c

Is there a way that I can get the same output as before?

**Comment by kisvegabor** [comment]
Hey,

When we have created our new webpage the v5.3 font converter wasn't added. I thought it's not really used anymore :sweat_smile: 

You can still access it here: https://dev.lvgl.io/tools/font_conv_v5_3

**Comment by kissa96** [comment]
@SalahuddinAsh Hi, is this still a valid issue?

**Comment by kissa96** [comment]
Cool. Looking forward to it

**Comment by kisvegabor** [comment]
it would be really great to add it, however the the old tool is written in PHP and the current site doesn't use PHP :slightly_frowning_face:

**Comment by kisvegabor** [comment]
In lack of a good solution I close this issue for now. 🙁
