### ISSUE TITLE
Bug: Compiler error when including lv_lcd_generic_mipi.h

### ISSUE THREAD

**Issue by mverch67** [kisvegabor/lvgl#6983]
### LVGL version

9.2.0

### What happened?

The compiler guards at the end of the file do not match the order used at the beginning which results in unterminated extern "C" declaration:
https://github.com/lvgl/lvgl/blob/0ff875423a9b7dad164324b658b044a566128489/src/drivers/display/lcd/lv_lcd_generic_mipi.h#L235

Start:
```
#ifndef LV_LCD_GENERIC_MIPI_H
#define LV_LCD_GENERIC_MIPI_H

#ifdef __cplusplus
extern "C" {
#endif

#if LV_USE_GENERIC_MIPI
```

End:
```
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*LV_USE_GENERIC_MIPI*/

#endif /* LV_LCD_GENERIC_MIPI_H */
```

It should be like this:
![image](https://github.com/user-attachments/assets/93bde3c8-49f8-4db8-bafd-5329d3eff662)

### How to reproduce?

Define one of these LV_USE_ST77xx as 1 in lv_conf.h and include "drivers/display/lcd/lv_lcd_generic_mipi.h" in the custom C++ driver code.

**Comment by kissa96** [comment]
Nice catch! Fixed in #7062

**Comment by kisvegabor** [comment]
FYI, it was fixed a few days ago in master: https://github.com/lvgl/lvgl/pull/6905

**Comment by kisvegabor** [comment]
As https://github.com/lvgl/lvgl/pull/6905 is merged I close it.
