### ISSUE TITLE
Documentation: LV_TA_CURSOR_LAST was renamed

### ISSUE THREAD

**Issue by plueschpruem** [kisvegabor/lvgl#6991]
### LVGL version

9.x

### What happened?

The [documentation](https://docs.lvgl.io/master/widgets/textarea.html) still lists **LV_TA_CURSOR_LAST** – but it has been changed to **LV_TEXTAREA_CURSOR_LAST**

**Comment by vwheeler63** [comment]
Good catch!  Since I am working one some major improvements with the documentation, to prevent conflicts, I have taken this on myself and submitted the fix for this in PR #6995.
