### ISSUE TITLE
Documentation / Help request: Simulating an OLED

### ISSUE THREAD

**Issue by mado89** [kisvegabor/lvgl#6996]
Hi,
I am on the lookout for input on how to simulate a monochrome OLED display (128x64px). Can this be done with SDL while the simulated code uses lv_ functions?
Thanks

**Comment by kisvegabor** [comment]
I moved this issue to the main LVGL repo as the SDL driver is locate here. 


It's really not supported now, but it's possible to add it to the SDL driver [here](https://github.com/lvgl/lvgl/blob/master/src/drivers/sdl/lv_sdl_window.c). If the display's color format is `I1` we should use `ARGB8888` for SDL [here](https://github.com/lvgl/lvgl/blob/master/src/drivers/sdl/lv_sdl_window.c#L384-L393) and convert the indexed data to ARGB8888 in the `flush_cb`

**Comment by kisvegabor** [comment]
PR opened, see https://github.com/lvgl/lvgl/pull/7036

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/7036 is ready and being reviewed.

**Comment by mado89** [comment]
Thanks for your efforts. I will check when I have time again (currently working on a different project, sorry)
