### ISSUE TITLE
KEYPAD indev LV_EVENT_DOUBLE_CLICKED

### ISSUE THREAD

**Issue by jgauchia** [kisvegabor/lvgl#7003]
### Introduce the problem

Hi,
It's possible to have double click event, LV_EVENT_DOUBLE_CLICKED, on KEYPAD indev?
Actually only LV_EVENT_SHORT_CLICKED works.

**Comment by kissa96** [comment]
The keypad has a special mindset behind it, as you wouldn't normally double or triple press/hold, etc. it while entering the code. Only LV_EVENT_SHORT_CLICKED makes sense from a use case standpoint.
We could implement all events for the keypad as well, but as a normal use case does not require it, we decided not to.
If we receive enough feedback on this feature, then we might implement it in a future release.

**Comment by jgauchia** [comment]
Ok @kissa96 thank you!

**Comment by kisvegabor** [comment]
I think in the near future we should add it to our todo list as more an more people are asking for these features. 🙂 
We already have a lot of tings for v9.3, but it can fit in v9.4.

**Comment by jgauchia** [comment]
No problem @kisvegabor ,It is not a priority.

All this was to be able to add, in the case of an ESP32 the GPIO0, by double clicking it enters sleep mode, perhaps it is not the most ideal option to use KEYPAD for this,

Currently I have it implemented with, single press sleep mode, long press shutdown.

Thank you so much!

**Comment by kisvegabor** [comment]
I'm closing this for now.
