### ISSUE TITLE
break! img_draw_core

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#7007]
### LVGL version

v9.3.0

### What happened?

run lv_demo_widgets()，mouse roller in Analyses page:
the buf_stride is zero:
![图片](https://github.com/user-attachments/assets/e77ddc6a-29be-453b-8189-1d2f26bd8d60)

**Comment by xinsuinizhuan** [comment]
still break:
![图片](https://github.com/user-attachments/assets/373f6d3b-91ee-4c85-9b98-88a021c1e588)

**Comment by kisvegabor** [comment]
Please enable LVGL's logging in `lv_conf.h`. Do you see an out of memory error?

**Comment by xinsuinizhuan** [comment]
to make Division, juedge buffer_stride whether is zero is normal， it is hard to add?

**Comment by xinsuinizhuan** [comment]
have add the judget?

**Comment by liamHowatt** [comment]
> still break:

The fix you attempted in that screenshot leaves `tmp_buf` uninitialized if stride is zero.

The question is how stride is becoming zero? Is `blend_w` zero or is `lv_color_format_get_size(cf_final)` returning zero?
