### ISSUE TITLE
empty screen have flicker when set optimization from -O0 to -O3

### ISSUE THREAD

**Issue by woniulive** [kisvegabor/lvgl#7008]
### LVGL version

v9.2.0

### What happened?

I use STM32L4P5RG + external QSPI flash + external QSPI PSRAM + SPI DMA to driver TFT.
When I use -O0, the benchmark demo work correctly.
When I use -O3, empty screen have flicker when the benchmark demo run.

-O0:
![image](https://github.com/user-attachments/assets/537e3908-5213-4b7a-a64c-951a34bc9efb)

-O3:
![image](https://github.com/user-attachments/assets/9afaeee7-2483-492e-ba69-97aaeae66ef5)
-O3 video: https://github.com/user-attachments/assets/c4104dfe-01c4-4fb6-8ff1-f59d9b177d20

**Comment by kisvegabor** [comment]
Hi,

What is color format of the display? Is it 24 bit (RGB888)?

**Comment by woniulive** [comment]
Hi @kisvegabor :
I use RGB565.

**Comment by kisvegabor** [comment]
Sorry for the late reply.  It seems only the screen sized fills are problematic. Maybe it's a RAM config issue. Without using LVGL, please try to fill the RAM 16 bit numbers increasing from 0 and ready back the result.

**Comment by kissa96** [comment]
O3 optimization can result in unpredictable behavior if the screen is not properly handled with variables. Or better said, O3 needs code which is 100% standards compliant.

I am guessing you are never accessing the blank screen part, so it gets optimized out and some garbage is displayed instead

**Comment by kisvegabor** [comment]
I use O3 all the time so I can say that LVGL itself is O3 compatible.

**Comment by woniulive** [comment]
@kisvegabor @kissa96 :
After I confirmed with ST official, it seems that the reason is PSRAM, the data store in PSRAM will be wrong if I set optimization from -O0 to -O3. After I decrease the frequecy of PSRAM, it work correctly.
Thank you for your help.
This issue can be closed now.

**Comment by kisvegabor** [comment]
Oh, interesting. Thank you for letting us know.
