### ISSUE TITLE
handle language rules

### ISSUE THREAD

**Issue by junminacts** [kisvegabor/lvgl#7031]
### Problem to solve

LVGL cannot break lines according to language rules

### Success criteria

can break lines and handle letter sequence according to language rules

### Solution outline

can use thirdparty libraries, icu4c, harfbuzz, etc.

### Rabbit holes

No

### Testing

not yet

### Teaching

not yet

**Comment by kissa96** [comment]
LVGL might support this feature as time goes on. The general theme for LVGL is to be lightweight and dependency free.
We do not want to rely on external libs for supporting languages.

**Comment by kisvegabor** [comment]
As LVGL gets more popular on MPUs where harfbuzz is available a better architecture and interface for typesetting is definitely on the longer term roadmap. It can be added probably only next year :slightly_frowning_face:
