### ISSUE TITLE
ESP32 crashes when adding mask to Roller (only when built_type=release) 

### ISSUE THREAD

**Issue by caipifrosch** [kisvegabor/lvgl#7048]
### LVGL version

V8.4.1

### What happened?

wadtchdog reboots ESP32 when starting roller screen and adding a mask on lvgl roller (cylinder effect).

Only crashing when build_type is set to release. works fine when specifying build_type=debug in platformio.ini.

Roller also works in release when mask is not applied.

Thanks a lot for your feedback in advance.

### How to reproduce?

On Roller Init:

lv_obj_add_event_cb(obj, roller_mask_event_cb, LV_EVENT_ALL, NULL);

callback:

static void roller_mask_event_cb(lv_event_t * e) {

    // Get the event code (type of event like drawing, checking coverage, etc.)
    lv_event_code_t code = lv_event_get_code(e);
    
    // Get the target object that triggered the event (the roller)
    lv_obj_t * obj = (lv_obj_t *)lv_event_get_target(e);

    // Static variables to store the IDs of the top and bottom fade masks
    static int16_t mask_top_id = -1;
    static int16_t mask_bottom_id = -1;

    // Handle the event for cover check
    if (code == LV_EVENT_COVER_CHECK) {
        // Tell the system that this object uses a mask for coverage
        lv_event_set_cover_res(e, LV_COVER_RES_MASKED);

    // Handle the event for the beginning of the main drawing phase
    } else if (code == LV_EVENT_DRAW_MAIN_BEGIN) {
        // Retrieve the font used for the text in the roller
        const lv_font_t * font = lv_obj_get_style_text_font(obj, LV_PART_MAIN);
        
        // Get the line spacing for the text in the roller
        lv_coord_t line_space = lv_obj_get_style_text_line_space(obj, LV_PART_MAIN);
        
        // Get the height of the font
        lv_coord_t font_h = lv_font_get_line_height(font);

        // Get the roller's current coordinates on the screen
        lv_area_t roller_coords;
        lv_obj_get_coords(obj, &roller_coords);

        // Define the area where the top mask will be applied
        lv_area_t rect_area;
        rect_area.x1 = roller_coords.x1;
        rect_area.x2 = roller_coords.x2;
        rect_area.y1 = roller_coords.y1;
        rect_area.y2 = roller_coords.y1 + (lv_obj_get_height(obj) - font_h - line_space) / 2;

        // Allocate memory for the top fade mask using LVGL's memory buffer
        lv_draw_mask_fade_param_t *fade_mask_top = (lv_draw_mask_fade_param_t*) lv_mem_buf_get(sizeof(lv_draw_mask_fade_param_t));

        // Initialize the top fade mask to fade from transparent to opaque
        lv_draw_mask_fade_init(fade_mask_top, &rect_area, LV_OPA_TRANSP, rect_area.y1, LV_OPA_COVER, rect_area.y2);
        
        // Add the top mask and save the mask ID for later removal
        mask_top_id = lv_draw_mask_add(fade_mask_top, NULL);

        // Define the area where the bottom mask will be applied
        rect_area.y1 = rect_area.y2 + font_h + line_space - 1;
        rect_area.y2 = roller_coords.y2;

        // Allocate memory for the bottom fade mask
        lv_draw_mask_fade_param_t * fade_mask_bottom = (lv_draw_mask_fade_param_t*) lv_mem_buf_get(sizeof(lv_draw_mask_fade_param_t));

        // Initialize the bottom fade mask to fade from opaque to transparent
        lv_draw_mask_fade_init(fade_mask_bottom, &rect_area, LV_OPA_COVER, rect_area.y1, LV_OPA_TRANSP, rect_area.y2);
        
        // Add the bottom mask and save the mask ID for later removal
        mask_bottom_id = lv_draw_mask_add(fade_mask_bottom, NULL);

    // Handle the event for the end of the drawing phase
    } else if (code == LV_EVENT_DRAW_POST_END) {
        // Remove the top mask using its ID
        lv_draw_mask_fade_param_t * fade_mask_top = (lv_draw_mask_fade_param_t*) lv_draw_mask_remove_id(mask_top_id);

        // Remove the bottom mask using its ID
        lv_draw_mask_fade_param_t * fade_mask_bottom = (lv_draw_mask_fade_param_t*) lv_draw_mask_remove_id(mask_bottom_id);
        
        // Release the memory used by the top fade mask
        lv_mem_buf_release(fade_mask_top);

        // Release the memory used by the bottom fade mask
        lv_mem_buf_release(fade_mask_bottom);
        
        // Free the mask parameters for the top mask
        lv_draw_mask_free_param(&fade_mask_top);

        // Free the mask parameters for the bottom mask
        lv_draw_mask_free_param(&fade_mask_bottom);
        
        // Reset the mask IDs to indicate that no masks are currently applied
        mask_top_id = -1;
        mask_bottom_id = -1;
    }

}

**Comment by kisvegabor** [comment]
Hi,

Sorry for the delay. 

There is an extra `&` in these lines:
```c
    // Free the mask parameters for the top mask
    lv_draw_mask_free_param(&fade_mask_top);

    // Free the mask parameters for the bottom mask
    lv_draw_mask_free_param(&fade_mask_bottom);
```

They should be:
```c
    // Free the mask parameters for the top mask
    lv_draw_mask_free_param(fade_mask_top);

    // Free the mask parameters for the bottom mask
    lv_draw_mask_free_param(fade_mask_bottom);
```
