### ISSUE TITLE
Does anyone use lvgl to create mini game applications?

### ISSUE THREAD

**Issue by wanghui1983** [kisvegabor/lvgl#7056]
### Introduce the problem

Currently, it is very popular to implement mini games on watches, most of which may be based on JS frameworks. Do any developers develop mini games based on LVGL? Do you have any relevant resources?

### Proposal

We want to find some resources to use lvgl for making small games, which can help us develop some small games for watches

**Comment by lizhaoming19980614** [comment]
https://github.com/100askTeam/lv_lib_100ask/tree/master/src/lv_100ask_2048

**Comment by kissa96** [comment]
Hi @wanghui1983, although core LVGL is not made for creating games, it is certainly capable of it, with its own widget limitations. Go get creative :)

**Comment by kissa96** [comment]
@liamHowatt Can you close this issue please? Thx
