### ISSUE TITLE
LV_COLOR_16_SWAP define missing from config

### ISSUE THREAD

**Issue by cosmindanielradu19** [kisvegabor/lvgl#7060]
### LVGL version

v9.2.0

### What happened?

For LVGL support on LPC platforms, it seems that we need to set LV_COLOR_16_SWAP as 1, or the panel output color is not correct.

The LV_COLOR_16_SWAP was enabled in the lv_conf.h on LVGL v8.3.10, and the define is still used in [lv_refr.c](https://github.com/lvgl/lvgl/blob/master/src/core/lv_refr.c#L1260) . Shall we create a PR to add it in the current config?

Without LV_COLOR_16_SWAP 

![image](https://github.com/user-attachments/assets/902622cd-a7f3-4a2c-83d9-31b9547ee4c2)

With LV_COLOR_16_SWAP 

![image](https://github.com/user-attachments/assets/64b95629-7ade-4d20-be61-6fd6f409bf1e)

**Comment by cosmindanielradu19** [comment]
@kisvegabor 
We already have the patch for this fix. If the changes looks good to you, we can create a PR.

[0001-fix-config-bring-back-LV_COLOR_16_SWAP-define.patch](https://github.com/user-attachments/files/17362621/0001-fix-config-bring-back-LV_COLOR_16_SWAP-define.patch)

**Comment by kisvegabor** [comment]
Hi,
We have kept `LV_COLOR_DEPTH_16_SWAP` only for backward compatibility. The v9-ish was of doing it is calling `lv_draw_sw_rgb565_swap` in the `flush_cb`. See the details [here](https://docs.lvgl.io/master/porting/display.html#swap-endianness).

**Comment by keerthansys22** [comment]
Hi @cosmindanielradu19, I'm attaching the working code snippet of lv_draw_sw_rgb565_swap in my flush_cb. Thanks.

```c
static void disp_flush(lv_disp_t* display, const lv_area_t * area, uint8_t * color_p)
{
    lv_draw_sw_rgb565_swap(buf_1, (MY_DISP_HOR_RES * MY_DISP_VER_RES));
    lcd_send_data(area->x1, area->y1, area->x2, area->y2, (uint8_t *)color_p);

    lv_display_flush_ready(display);
}

**Comment by cosmindanielradu19** [comment]
Thank you for the clarification

**Comment by flintobrien** [comment]
For LVGL 9.5 with LV_DISPLAY_RENDER_MODE_PARTIAL I needed to amend @keerthansys22 <disp_flush> like so. This got the LVGL music demo working with LV_COLOR_FORMAT_RGB565 and the music demo images that are ARGB8888.
```c
static void disp_flush(lv_display_t* display, const lv_area_t * area, uint8_t * px_map)
{
    const int offsetx1 = area->x1 ;
    const int offsetx2 = area->x2 ;
    const int offsety1 = area->y1;
    const int offsety2 = area->y2;

    uint32_t buff_size_px = (offsetx2 - offsetx1 + 1) * (offsety2 - offsety1 + 1);
    lv_draw_sw_rgb565_swap(px_map, buff_size_px);
    lcd_send_data(offsetx1, offsety1, offsetx2 + 1, offsety2 + 1, px_map);
}

**Comment by AndreCostaaa** [comment]
Hi. For LVGL v9.5 you can use LV_COLOR_FORMAT_RGB565_SWAPPED to tell LVGL to render 565 in big endian

It's more performant than to swap in the flush callback

**Comment by flintobrien** [comment]
@AndreCostaaa thank for you mentioning RGB565_SWAPPED. I couldn't get that working yesterday, so I spent more time on it today. The 9.5 docs don't talk about all the steps to get it working. I had to disable LV_DRAW_SW_SUPPORT_RGB565 and call `lv_display_set_color_format` before it starting working. I was afraid of disabling RGB565 since it seems so fundamental to the architecture. I wasn't calling `lv_display_set_color_format()` previously. Presumably RGB565 is the default format for 16 bit color. I kept searching for how to set the color format in the config file and didn't think to look for an `lv_display_set` function.

## Steps:
1. Update config:
```c
    #define LV_DRAW_SW_SUPPORT_RGB565       0
    #define LV_DRAW_SW_SUPPORT_RGB565_SWAPPED       1
```
2. Add this line somewhere after `lv_display_create()`
```c
lv_display_set_color_format(display1, LV_COLOR_FORMAT_RGB565_SWAPPED);
```
3. No need to call `lv_draw_sw_rgb565_swap()` any more inside my display flush callback function.

**Comment by AndreCostaaa** [comment]
You can keep RGB565 enabled too

Yes indeed the color depth config lacks that kind of granularity

Thank you for sharing your pain points, i'll make sure we improve upon them

Happy hacking 😎

**Comment by flintobrien** [comment]
`LV_COLOR_FORMAT_RGB565_SWAPPED` would not work when I kept SUPPORT_RGB565 enabled for the music demo. I tried toggling multiple times. With that one change (enabling RGB565 support), the display doesn't do anything and I don't see any errors/warnings (with LV logging enabled at warning level).

### System
[Waveshare ESP32-S3 AMOLED 1.19"](https://www.waveshare.com/esp32-s3-amoled-1.91.htm?sku=28596), VS Code, ESP IDF 2.0.2
### config changes
```c
#define ESP_MAIN_TASK_STACK_SIZE 8000 // default 3584
#define LV_USE_OS LV_OS_FREERTOS // default LV_OS_NONE
#define LV_USE_LOG 1
#define LV_LOG_PRINTF 1
```
