### ISSUE TITLE
Source control: what files/folders to include

### ISSUE THREAD

**Issue by focussing** [kisvegabor/lvgl#7065]
### LVGL version

v9.2.0 / all versions

### What happened?

Posted in Forum but no reactions.

My development environment is Arduino using Sketchbook location. Raspberry Pi RP2040 is the controller.
The Sketchbook location holds the source files (.ino and .h), and also the libraries folder.
I want to put the whole workspace including source files and also libraries under version control.
However the number of files and folders are quite high, so I want only to put all necessary files and folders under version control.
Which can I delete without problems?

**Comment by kissa96** [comment]
For LVGL to work properly, you need ./src, lv_conf.h and lvgl.h in the project directory

**Comment by kisvegabor** [comment]
And `lvgl.h`. :slightly_smiling_face:

**Comment by focussing** [comment]
I was out of office for a week, next week I will come back to this issue.
Thanks a lot so far!
