### ISSUE TITLE
LV_OBJ_FLAG_OVERFLOW_VISIBLE Does Not Work

### ISSUE THREAD

**Issue by stachurr** [kisvegabor/lvgl#7091]
### LVGL version

v9.2.0

### What happened?

I cannot get LV_OBJ_FLAG_OVERFLOW_VISIBLE to work, even in the simplest case. I have a label inside an object whose text is being clipped regardless of the flags' status.

Out of desperation, I tried all combinations of LV_OBJ_FLAG_OVERFLOW_VISIBLE and LV_OBJ_FLAG_FLOATING between the label and object without success. Maybe I am misunderstanding? Thank you for your time.

### How to reproduce?

This is the code I expected to work.
obj: OVERFLOW_VISIBLE
label: FLOATING
```
lv_obj_t* obj = lv_obj_create(lv_screen_active());
lv_obj_set_size    (obj, 100, 100);
lv_obj_center      (obj);
lv_obj_add_flag    (obj, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
lv_obj_t* label = lv_label_create(obj);
lv_label_set_text  (label, "00000000000000000000\n"
                           "11111111111111111111\n"
                           "22222222222222222222\n"
                           "33333333333333333333\n"
                           "44444444444444444444");
lv_obj_add_flag    (label, LV_OBJ_FLAG_FLOATING);
```
![image](https://github.com/user-attachments/assets/a3abdde9-e35d-4591-ad5c-67f820495b72)

**Here are some other attempts and their results...**

obj: OVERFLOW_VISIBLE
label: --
![image](https://github.com/user-attachments/assets/22b5ee21-4df3-4dd4-aca5-578de674d4f9)

obj: OVERFLOW_VISIBLE
label: OVERFLOW_VISIBLE, FLOATING
![image](https://github.com/user-attachments/assets/ff5d44ab-273b-4796-92bf-595def440af3)

obj: OVERFLOW_VISIBLE, FLOATING
label: OVERFLOW_VISIBLE, FLOATING
![image](https://github.com/user-attachments/assets/6100ecfd-f71e-4c6d-b379-952cd2fa776a)

obj: OVERFLOW_VISIBLE, FLOATING
label: OVERFLOW_VISIBLE
![image](https://github.com/user-attachments/assets/2d48f39d-7694-4abf-ad9f-ceabdef0daab)

obj: --
label: OVERFLOW_VISIBLE
![image](https://github.com/user-attachments/assets/ea5add7a-4a25-4d73-b613-6bd888539de7)

**Comment by XuNeo** [comment]
Please try my example here: https://github.com/XuNeo/luavgl/blob/master/simulator/widgets/lv_pointer.c#L81-L85

LVGL changes it mainly because there's no other way...
It's workaround of parallel rendering.

**Comment by XuNeo** [comment]
The documentation clearly needs to update.

**Comment by stachurr** [comment]
Hmmm I'm not sure I understand your example. I've included as such and now see nothing is drawn. Is this how you intended?
```
static void ext_draw_size_event_cb(lv_event_t * e)
{
    lv_coord_t * cur_size = (lv_coord_t*)lv_event_get_param(e);
    *cur_size = LV_MAX(*cur_size, LV_HOR_RES);
}
...
lv_obj_t* obj = lv_obj_create(m_screen);
        lv_obj_set_size     (obj, 100, 100);
        lv_obj_center       (obj);
        lv_obj_add_flag     (obj, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
        lv_obj_add_event_cb(obj, ext_draw_size_event_cb, LV_EVENT_REFR_EXT_DRAW_SIZE, NULL);
        lv_obj_t* label = lv_label_create(obj);
        lv_label_set_text   (label, "00000000000000000000\n"
                                    "11111111111111111111\n"
                                    "22222222222222222222\n"
                                    "33333333333333333333\n"
                                    "44444444444444444444");
```

**Comment by XuNeo** [comment]
Great, could you please update the documentation correspondingly? Thank you!

**Comment by kisvegabor** [comment]
Hi,

I can't see the problem here. The set a larger draw size you should use an event and it's shown in @XuNeo's example.

**Comment by XuNeo** [comment]
The problem is that v8 doesn't need it and doc also doesn't mention this requirement. We need to update doc.
