### ISSUE TITLE
No such file or directory: #include <process.h>

### ISSUE THREAD

**Issue by BenGeoSim** [kisvegabor/lvgl#7105]
### LVGL version

v8.3.10

### What happened?

Sorry I don't think true issue. I am using 8.3.10 and getting "no such file process.h". I am using old version to match tutorial, is there a dependancy I am missing? Thanks!

**Comment by kissa96** [comment]
<process.h> is a predefined header, not an LVGL header.
Which function relies on it?

**Comment by BenGeoSim** [comment]
Pardon my ignorance: it comes up as an error when I try and compile with the Arduino IDE.
This is for a Waveshare product so I think it will beyond the scope of this GitHub repo, as they provide library files which may break the compilation in unexpected ways. The error is called in the file lvgl/src/osal/lv_windows.c

**Comment by kissa96** [comment]
Which board are you using?
If this is not LVGL related, can you please close the issue as resolved? Thx in advance

**Comment by BenGeoSim** [comment]
I'll close it now, I'm using this board:
https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-2.1#Overview

**Comment by liamHowatt** [comment]
Where is the library coming from? I can't find `#include <process.h>` in https://downloads.arduino.cc/libraries/github.com/lvgl/lvgl-8.3.10.zip

**Comment by TheKerbecs** [comment]
It is the library from the demo code for Waveshare LCD screens.

https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4#Demo

**Comment by liamHowatt** [comment]
Hmm when I download and extract https://files.waveshare.com/wiki/ESP32-S3-Touch-LCD-4/ESP32-S3-Touch-LCD-4_democode.zip and https://files.waveshare.com/wiki/ESP32-S3-Touch-LCD-4/ESP32-S3-Touch-LCD-4_democode_V2.zip and run `grep -r 'process\.r'` there are no results.

What's the full Arduino compiler error message?

**Comment by TheKerbecs** [comment]
c:\Users\radle\OneDrive\Dokumente\Arduino\libraries\lvgl\src\osal\lv_windows.c:14:10: fatal error: process.h: No such file or directory
   14 | #include <process.h>
      |          ^~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

I gave that to ChatGPT and it told me to rename the file to .bak at the end. That solved the issue. 

Now when i wanted to look for the osal folder it was deleted, i dont remember if i did that or it was done automatically. I managed to recover it via OneDrive. 
Here is the link for it
https://1drv.ms/f/s!ApIWOyc1W43-7qdaQXsbZY1A7JLmhA?e=ccD03v
