### ISSUE TITLE
arc could not see the lable!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#7145]
### LVGL version

8.3.10 and 8.4

### What happened?

![图片](https://github.com/user-attachments/assets/ede35a28-72e0-455b-b073-d35bf071152d)
could not see the lable value

### How to reproduce?

static void value_changed_event_cb(lv_event_t* e);

void lv_example_arc_1(void)
{
	lv_obj_t* label = lv_label_create(lv_scr_act());

	/*Create an Arc*/
	lv_obj_t* arc = lv_arc_create(lv_scr_act());
	lv_obj_set_size(arc, 150, 150);
	lv_arc_set_rotation(arc, 135);
	lv_arc_set_bg_angles(arc, 0, 270);
	lv_arc_set_value(arc, 10);
	lv_obj_center(arc);
	lv_obj_add_event_cb(arc, value_changed_event_cb, LV_EVENT_VALUE_CHANGED, label);

	/*Manually update the label for the first time*/
	lv_event_send(arc, LV_EVENT_VALUE_CHANGED, NULL);
}

static void value_changed_event_cb(lv_event_t* e)
{
	lv_obj_t* arc = lv_event_get_target(e);
	lv_obj_t* label = (lv_obj_t*)lv_event_get_user_data(e);

	lv_label_set_text_fmt(label, "%d%%", lv_arc_get_value(arc));

	/*Rotate the label to the current position of the arc*/
	lv_arc_rotate_obj_to_angle(arc, label, 25);
}

**Comment by xinsuinizhuan** [comment]
but 9.3 is ok.

**Comment by xinsuinizhuan** [comment]
![图片](https://github.com/user-attachments/assets/9a6b76ad-d3ff-4946-9660-903651bbe415)
9.3

**Comment by kissa96** [comment]
Hi, it seems you have not created a label, so there is nothing which could display the text. LVGL functions return immediately if the supplied object is NULL

**Comment by lizhaoming634** [comment]
#define LV_COLOR_SCREEN_TRANSP 1

**Comment by xinsuinizhuan** [comment]
> #define LV_COLOR_SCREEN_TRANSP 1

is is not work, when set the lv_color_screen_transp, some where could see it, it seem the rect, int the rect cornner could see:
![图片](https://github.com/user-attachments/assets/40784d4b-13a8-44e6-b934-900f326f2e32)

it is the issure:lv_arc_rotate_obj_to_angle
![图片](https://github.com/user-attachments/assets/9d730d51-35ae-4d6a-b184-0fc2794b207a)

**Comment by xinsuinizhuan** [comment]
> Hi, it seems you have not created a label, so there is nothing which could display the text. LVGL functions return immediately if the supplied object is NULL

![图片](https://github.com/user-attachments/assets/e18d432c-64a1-49b4-9957-2f51843ce15c)

**Comment by kisvegabor** [comment]
If the label is created on the arc it will be clipped. Try creating it on a the screen.

**Comment by xinsuinizhuan** [comment]
thank you. #define LV_COLOR_SCREEN_TRANSP 1 and the label is created on the screen, it is ok.

**Comment by kisvegabor** [comment]
Great! I'm losing this issue then.
