### ISSUE TITLE
File explorer: Is the `.` element really useful?

### ISSUE THREAD

**Issue by C47D** [kisvegabor/lvgl#7160]
### Introduce the problem

The `.` element is really used/useful? I've never seen it on other file explorers.

Here's an example of the github explorer, there's only the `..` element.
![image](https://github.com/user-attachments/assets/f93edc36-67ff-49d5-8487-44f1ba1942d2)

### Proposal

Remove the `.` element from the file explorer.

**Comment by kissa96** [comment]
.github and .devcontainer are hidden folders. In Unix, anything that has a . in its name, is considered a hidden folder

**Comment by liamHowatt** [comment]
`.` is shown by the file explorer because `lv_fs_dir_read` finds it. You can see `.` in the output of `ls -a` on Linux or `dir` on Windows.

`..` means parent directory. `.` means current directory.

We could make the file explorer ignore it if we decide it's useless.

**Comment by kisvegabor** [comment]
I can't see for what can we use `.`. If it's not to complicated we could replace `..` with `<- Back` or so.

**Comment by liamHowatt** [comment]
> `.` is shown by the file explorer because `lv_fs_dir_read` finds it.

Sorry, I was incorrect. It actually gets added regardless of whether `lv_fs_dir_read` finds it, apparently.

**Comment by liamHowatt** [comment]
Closing as #7270 was merged.
