### ISSUE TITLE
Compiler settings

### ISSUE THREAD

**Issue by cosmindanielradu19** [kisvegabor/lvgl#7175]
### Introduce the problem

As long as the PR with kconfig broke the builds, and the fact that those configs are compiler dependent, I would suggest adding a `lv_compiler.h` file that should contain all the `COMPILER SETTINGS` from kconfig. The defines can remain only in the new header, and can be removed from both `lv_conf.h` and `kconfig` file.

### Proposal

```c
/**
 * @file lv_compiler.h
 * Configuration file for LVGL based on the compiler
 */

#ifndef LV_COMPILER_H
#define LV_COMPILER_H

#ifdef __GNUC__
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN __attribute__((aligned(LV_ATTRIBUTE_MEM_ALIGN_SIZE)))
#define LV_ATTRIBUTE_LARGE_CONST __attribute__((section("DataQuickAccess"))) 
#else
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_LARGE_CONST
#endif

#endif /*LV_COMPILER_H*/

```

**Comment by nicusorcitu** [comment]
Another solution can be the one suggested here: https://github.com/lvgl/lvgl/issues/7098#issuecomment-2439339979
We must agree on a way for such compiled configurations. There is no rush on doing it now, just it should be considered once with the split of lv_conf.h from here: https://github.com/lvgl/lvgl/issues/6010
