### ISSUE TITLE
ARC Events Documentation Out of Date?

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7179]
### LVGL version

v9.3

### What happened?

On the documentation page  https://docs.lvgl.io/master/details/widgets/arc.html#events  all the events listed after `LV_EVENT_VALUE_CHANGED` appear to have been removed from the Widget's code, in which case, I should remove them from the documentation.  @kisvegabor can you confirm?

![image](https://github.com/user-attachments/assets/2365cd60-c634-424e-928c-2a7cef2bf5c2)

### How to reproduce?

n/a

**Comment by kisvegabor** [comment]
I confirm that `LV_DRAW_PART_BEGIN/END` are leftovers from v8 and doesn't exist in v9.

**Comment by vwheeler63** [comment]
> I confirm that `LV_DRAW_PART_BEGIN/END` are leftovers from v8 and doesn't exist in v9.

Thank you!  I have removed them and will include in batch 4.

**Comment by vwheeler63** [comment]
> Thank you! I have removed them and will include in batch 4.

cc:  @kisvegabor 

Correction -- I have made these changes here locally already, but I will wait until the first `arc.rst` changes are merged before re-submitting so I don't cause a conflict.

**Comment by vwheeler63** [comment]
Will be submitting a "wrap-up" PR on all the widgets (Arc included) once the existing PRs are committed, to avoid merge conflicts.

**Comment by kisvegabor** [comment]
@vwheeler63 Is the fix already merged?

**Comment by vwheeler63** [comment]
> @vwheeler63 Is the fix already merged?

Indeed it is!  PR #7405 took care of it.
