### ISSUE TITLE
Placeholder Text Not Centered For lv_textarea_t

### ISSUE THREAD

**Issue by stachurr** [kisvegabor/lvgl#7182]
### LVGL version

v9.2.0

### What happened?

Setting a placeholder for a `lv_textarea_t` doesn't center the text. Note however, the normal text IS centered -- just not the placeholder text.
I also tried `lv_obj_set_style_align(m_textarea, LV_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER);` with no luck.
In all screenshots attached, I focused the textarea so the centered cursor would render, giving more visual cues.
![offcentered text](https://github.com/user-attachments/assets/7d821568-cdb3-4340-ac8c-d737f9c1e246)

Here are some screenshots using different fonts (1 built-in, 1 custom):
![montserrat 16](https://github.com/user-attachments/assets/e22eae75-5d07-463e-bb23-52e1d8853ad0)
![lato 16](https://github.com/user-attachments/assets/57d11934-572b-4073-8529-85302914a6a6)

For now, I'm appending 4 spaces to the placeholder which shifts the text left enough to look centered...
![montserrat 16 with spaces](https://github.com/user-attachments/assets/695749e7-101c-4d12-bba5-bac4c63e2197)
![lato 16 with spaces](https://github.com/user-attachments/assets/3777d095-8cdd-4480-94be-b9df66c26217)

### How to reproduce?

```
lv_obj_t* screen = lv_screen_active();
lv_obj_t* textarea = lv_textarea_create(screen);
lv_obj_set_size(textarea, 200, 100);
lv_textarea_set_placeholder_text(textarea, "Enter Something...");
//lv_obj_set_style_align(textarea, LV_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER);
```

**Comment by liamHowatt** [comment]
It's a bit of an edge case. Would you prefer the cursor to be at the left edge of the placeholder text while the placeholder text is visible?

**Comment by kisvegabor** [comment]
You should use `LV_TEXT_ALIGN_CENTER` instead of `LV_ALIGN_CENTER`.
```c
lv_obj_set_style_text_align(textarea, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER);
```

**Comment by stachurr** [comment]
Hi @kisvegabor, I have already tried this and it does not work.

**Comment by kisvegabor** [comment]
There was a related fix in `master`. Please use the latest commit from the `master` branch.

**Comment by stachurr** [comment]
Thank you.
