### ISSUE TITLE
chart widget break. when one series have one data, it will be break!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [kisvegabor/lvgl#7184]
### LVGL version

all version

### What happened?

when one series have one data, it will be break! Code here break:
![图片](https://github.com/user-attachments/assets/c36339d9-0320-470a-9859-c31e902405e1)
it should be change as:
![图片](https://github.com/user-attachments/assets/3feeffdd-c48e-47bf-aa99-29754f01df3a)

there are so many division, should judge the divisor is zero, in code!!!

**Comment by liamHowatt** [comment]
I encountered this divide-by-zero bug as well. Please open a PR.

**Comment by kissa96** [comment]
Hi @xinsuinizhuan, do you want to open a PR, or should I handle it?

**Comment by xinsuinizhuan** [comment]
you handle it!

**Comment by xinsuinizhuan** [comment]
https://github.com/lvgl/lvgl/issues/7007 this is also the divide-by-zero bug.

**Comment by liamHowatt** [comment]
Closing as #7211 has been merged.
