### ISSUE TITLE
Documentation Dark Mode Has One Really Bad Color

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7195]
### LVGL version

v9.3

### What happened?

cc:  @kisvegabor 

In Dark Mode in the documentation, the color that is used to highlight *recognized function names* is so dark that it is nearly invisible:  it nearly blends into the black background.  See example here:  https://docs.lvgl.io/master/details/base-widget/scroll.html#scroll-manually  which looks like this on my screen:

![image](https://github.com/user-attachments/assets/e942330e-85b0-4445-b2c7-fada940da75f)

Furthermore, in LIGHT mode, it is so dark it is nearly black against the light background so I almost cannot tell it is highlighted:

![image](https://github.com/user-attachments/assets/80094bfa-4860-4a8a-a7e2-65fc4f418460)

I investigated the generated cascading sequence in the documentation web pages and found that it only exists in `./out_html/_static/pygments.css` (provided by Sphinx via the `pygments` Python package for code-block highlighting) as

```css
.highlight .nf { color: #06287e } /* Name.Function */
```
and does not otherwise occur in the remaining (cascaded) 6 style sheets included after that.  So it can be successfully overridden in `./docs/_static/css/custom.css`.  

I have worked out a new color for this and tested it:
```css
.highlight .nf { color: #2648ee } /* Name.Function */
```
and it works beautifully for my eyes for both backgrounds.  See the results here.

![image](https://github.com/user-attachments/assets/e311277c-0350-4996-bf10-0af1c57944c8)

![image](https://github.com/user-attachments/assets/e0aa6c65-c7ed-418b-934b-301b9f10e4b3)

Gábor, if you will, please confirm that this new color is acceptable.  (Call in any other opinions that might be interested.)  If it is acceptable, I am ready with a PR to submit.  I'm awaiting confirmation that this new color works for everyone involved.

Kind regards,
Vic

### How to reproduce?

See above.

**Comment by kisvegabor** [comment]
Hi,

Than you for the investigation. 

It's okay for me to change it. Please send a PR

**Comment by vwheeler63** [comment]
> Please send a PR

Done!  PR #7199
