### ISSUE TITLE
ImageButton graphic doesn't change when pressed, unless you set an empty style

### ISSUE THREAD

**Issue by Windwoes** [kisvegabor/lvgl#7203]
### LVGL version

9.3.0

### What happened?

If I create an image button and give it graphics for pressed and released states, the button graphic does not update when pressed, unless I also set an empty style on the image button, and then it works.

### How to reproduce?

```c
static void loadImgBtn(lv_obj_t** ptrImgBtn, uint16_t width, uint16_t height,
                       const void* imgUnpressed,const void* imgPressed, uint16_t x, uint16_t y)
{
    *ptrImgBtn = lv_imagebutton_create(ui_screen);
    lv_imagebutton_set_src(*ptrImgBtn, LV_IMAGEBUTTON_STATE_RELEASED, imgUnpressed, NULL, NULL);
    lv_imagebutton_set_src(*ptrImgBtn, LV_IMAGEBUTTON_STATE_PRESSED, imgPressed, NULL, NULL);
    lv_obj_set_width(*ptrImgBtn, width);
    lv_obj_set_height(*ptrImgBtn, height);
    lv_obj_align(*ptrImgBtn, LV_ALIGN_TOP_LEFT, x, y);

    // Workaround bug in LVGL where the button graphic won't change when pressed,
    // unless we set a style and then it seems work ?
    static lv_style_t style;
    lv_style_init(&style);
    lv_obj_add_style(*ptrImgBtn, &style, LV_STATE_PRESSED | LV_STATE_DEFAULT);
}
```

**Comment by lizhaoming634** [comment]
maybe you can try
 lv_obj_add_style(*ptrImgBtn, &style, LV_STATE_PRESSED | LV_PART_MAIN);

**Comment by liamHowatt** [comment]
Thanks for reporting it. I was able to reproduce it.

You can make it work by simply applying the image source as the `src_mid` parameter instead of the `src_left` parameter.

```c
    lv_imagebutton_set_src(*ptrImgBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, imgUnpressed, NULL);
    lv_imagebutton_set_src(*ptrImgBtn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, imgPressed, NULL);
```

The problem is that the imagebutton refresh handler does nothing if the middle image is `NULL`. I opened a PR: #7224

**Comment by Windwoes** [comment]
> You can make it work by simply applying the image source as the src_mid parameter instead of the src_left parameter.

Okay, I'll try that when I get a chance. Also, I think it would be helpful to update the docs to explain why there are 3 source parameters and the effects of specifying (or not) the various combinations. It looks like previous versions of LVGL only took a single source image parameter.

**Comment by liamHowatt** [comment]
I added a line to the docs which says: "Typically the middle image should be one of the set image sources."
