### ISSUE TITLE
Chart Cursor Misplaced on Bar Graph with Multiple Series

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7206]
### LVGL version

v9.3

### What happened?

This was done by adding a red LV_DIR_ALL cursor to `lv_chart_example_2.c`, and calling:
```c
lv_chart_set_cursor_point(chart, cursor, ser1, 2);
```
which should place the cursor on the 3rd value, at the top edge of the bar in series 1.  As you can see, it gets the right value and *height*, but the wrong bar (wrong series).
![image](https://github.com/user-attachments/assets/9b3a31cb-7aa0-46a5-9194-a04949caad73)

Likewise with series 2:
```c
lv_chart_set_cursor_point(chart, cursor, ser2, 2);
```
Same as before:  it gets the right *height*, but the wrong bar.
![image](https://github.com/user-attachments/assets/58a17e6b-bfa4-41ed-aae1-9779e596d95b)

### How to reproduce?

Add this to `lv_example_chart_2.c` after the 2 data series have been created:

```c
    /* Add cursor to chart to see if it moves with scrolling. */
    lv_chart_cursor_t* cursor = lv_chart_add_cursor(chart, lv_color_make(255, 0, 0), LV_DIR_ALL);
    lv_chart_set_cursor_point(chart, cursor, ser1, 2);
```

**Comment by vwheeler63** [comment]
Note:  this *may* also affect `lv_chart_get_point_pos_by_id()` which is intended to fetch the coordinates of that point.

**Comment by lizhaoming634** [comment]
![image](https://github.com/user-attachments/assets/3406452f-48e3-425a-97a3-4567cbd206a8)

**Comment by lizhaoming634** [comment]
This is another mistake in the chart, it's better to modify it together
https://github.com/lvgl/lvgl/issues/7184

**Comment by vwheeler63** [comment]
> This is another mistake in the chart, it's better to modify it together #7184

What does that cause?

**Comment by lizhaoming634** [comment]
> > This is another mistake in the chart, it's better to modify it together #7184
> 
> What does that cause?

This may lead to zero division errors

**Comment by vwheeler63** [comment]
> This may lead to zero division errors

I see!  If you can handle both, you are welcome to.

**Comment by vwheeler63** [comment]
Handled by PR #7211!  Thank you @lizhaoming634 !
