### ISSUE TITLE
lv_scale indicator display misalignment and line cap is incorrect！

### ISSUE THREAD

**Issue by karriszou** [kisvegabor/lvgl#7212]
### LVGL version

v9.2.2

### What happened?

![issue](https://github.com/user-attachments/assets/2db9127f-ae75-4f80-923a-f80a538844d4)

As shown in the picture, the indicator is displayed incorrectly and this is worse when increasing the size of the indicator.

**Comment by lizhaoming634** [comment]
Can you provide example code?

**Comment by liamHowatt** [comment]
Are you on Windows? Please try a version of LVGL from after this fix: #7171

**Comment by karriszou** [comment]
@liamHowatt Thank you, when I upgraded to the new version, the problem disappeared!

**Comment by karriszou** [comment]
Close
