### ISSUE TITLE
how to delete a animimg widget obj?

### ISSUE THREAD

**Issue by Staok** [kisvegabor/lvgl#7215]
### LVGL version

8.3.11

### What happened?

After creating a obj of the lv_animing widget by lv_animimg_creat(), I want to del the obj, can I just use the lv_del_obj() API to correctly release this obj? I found that there is **NO** destructor_cb registered in the lv_animimg.c file

**Comment by kisvegabor** [comment]
A `destructor_cb` is just optional to free any memories allocated by the widget type. It seems animimage doesn't allocate anything, so it should be fine. 

Do experience a memory leak?
