### ISSUE TITLE
Duplicate lv_draw_sw_deinit() in lv_deinit() with 

### ISSUE THREAD

**Issue by antonio-pasini** [kisvegabor/lvgl#7219]
### LVGL version

9.2.2

### What happened?

Calling lv_deinit() with LV_USE_DRAW_SW= 1, LV_DRAW_SW_COMPLEX = 1 and LV_USE_OS =  LV_OS_FREERTOS will end up calling lw_draw_sw_deinit() twice (cfr. lv_init.c, lines367 and lines 407); this makes the mutex deinit fail, because the lv_mutex_delete() is not checking for pxMutex->xIsInitialized being already pdFALSE.

### How to reproduce?

#define LV_USE_DRAW_SW  1
#define LV_DRAW_SW_COMPLEX   1
#define LV_USE_OS   LV_OS_FREERTOS

**Comment by kisvegabor** [comment]
Oh, thank you for pointing it out! Could you send a PR?

**Comment by antonio-pasini** [comment]
Created PR #7266

**Comment by kisvegabor** [comment]
The PR is merged, closing. Thank you! 🙂
