### ISSUE TITLE
Use VS Code to build LVGL9.2.2 simulator to appear the following errors.

### ISSUE THREAD

**Issue by jor1178** [kisvegabor/lvgl#7222]
### LVGL version

v9.2.2

### What happened?

Use VS Code to build LVGL9.2.2 simulator to appear the following errors.
![bd5d8ed7061370871cede3e2bf1d07f](https://github.com/user-attachments/assets/b81a661d-7bd6-44c6-8847-204d6ecbff44)

**Comment by jor1178** [comment]
gcc version：14.2.0
cmake version：3.31.0-rc3
SDL version：2.30.9

**Comment by liamHowatt** [comment]
https://stackoverflow.com/a/55019187

Looks like you should remove `-lasan` or `-fsanitize=address` or `-fsanitize=undefined` or any `-fsanitize=*` from any build flags if your toolchain does not support it.

Are you using https://github.com/lvgl/lv_port_pc_vscode?
