### ISSUE TITLE
Slider-Knob Delayed Updates in Examples

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7230]
### LVGL version

v9.3

### What happened?

Updates to Slider-Knob position are being delayed in current examples (current = 5-Nov-2024 15:40 GMT).  This is occurring in both FireFox and Chrome browsers (the only 2 I have tested this with), in both LIGHT and DARK modes, and is occurring everywhere Sliders are used in examples (including on the Slider page).  The following screenshots illustrate the problem, from https://docs.lvgl.io/master/details/widgets/msgbox.html 

Original Display (Pre-Slider-Change):
![image](https://github.com/user-attachments/assets/c395f4f2-b016-49b5-a893-ade213e5731e)

After Slider Movement:
![image](https://github.com/user-attachments/assets/e635028f-6a26-4626-b85f-d89579000ece)

After Scrolling (which causes the display of the knob positions to be updated again):
![image](https://github.com/user-attachments/assets/2a165046-a744-47e3-b13f-fd1ccb52efa4)

This "feels" like a failure to invalidate the KNOB after sliding, but I am guessing.

### How to reproduce?

See above.

**Comment by lizhaoming634** [comment]
The slider example runs well in version 9.2, but it encounters issues when running on the master version
![image](https://github.com/user-attachments/assets/94e73908-46b5-4aa5-9485-cc6f34904639)
![image](https://github.com/user-attachments/assets/cd512671-a879-4bc9-b1b1-51206d13dacd)

**Comment by lhdjply** [comment]
Maybe need revert #6638

**Comment by kschwan** [comment]
Same issue here. Happens since #6638

**Comment by lizhaoming634** [comment]
@kisvegabor Could you please take a look at this issue?

**Comment by vwheeler63** [comment]
Perhaps it is really simple like 1 line of code to invalidate the knob....  At the right place.

**Comment by lizhaoming634** [comment]
The roller is also experiencing issues.
![image](https://github.com/user-attachments/assets/b8d7d2f1-dea5-4128-8436-a6f5c965c32b)
When the roller scrolls to 10, further upward scrolling causes issues.

**Comment by kisvegabor** [comment]
I found a bug in #6638 [here](https://github.com/lvgl/lvgl/pull/6638/files#diff-87868f4fa80d2fbd02400750545f9d5db3581d6d096b84487e1421d6464f9e6bR883):
`*area = obj->coords;` should be `*area = obj_coords`. 

Could you also try it?

**Comment by vwheeler63** [comment]
> I found a bug in #6638 [here](https://github.com/lvgl/lvgl/pull/6638/files#diff-87868f4fa80d2fbd02400750545f9d5db3581d6d096b84487e1421d6464f9e6bR883): `*area = obj->coords;` should be `*area = obj_coords`.
> 
> Could you also try it?

Beautiful!  Yes, that solves it for BOTH the Knob (on Slider) and the Roller!  Thankfully that bug only arrived a few days ago!

**Comment by vwheeler63** [comment]
@kisvegabor I didn't see the fix already in the pull requests, so I went ahead and submitted it in PR #7264.
