### ISSUE TITLE
lvgl load binary font file, will mapping to wrong character.

### ISSUE THREAD

**Issue by lanistor** [kisvegabor/lvgl#7232]
### LVGL version

8.4

### What happened?

When convert lots of characters, lv_font_conv will mapping wrong character, such as: using `庾语` replaced `德语`, using `尘` replaced `密`.

Test cases:
1. When reducing the count of characters, such as 2000, the problem disappear, https://lvgl.io/tools/fontconverter has the same problem
2. Increase memory of node `node --max-old-space-size=10240 lv_font_conv.js` ... also have the problem.
3. Using `--format lvgl` works fine, the problems appears on binary file by `--format bin`.
4. `--no-compress`, `--full-info` has no effect.
5. In simulator and in ESP32 device, it has different behavior: in simulator, it cannot display some language's words (belowing words after `旁遮普语`), but in ESP32 device, these language can display, using the same font binary file, add all load file by `lv_fs_stdio_init()`.
6. Use freetype loat this ttf file to render is ok.

<img width="941" alt="截屏2024-11-06 12 41 32" src="https://github.com/user-attachments/assets/9e9de8be-8d8b-45fc-959d-2f109f62fe72">

### Env
lv_font_conv: `1.5.3`
OS: `MacOSX 15.1`
Lvgl: `release/v8.4`
Node: `v18.19.1`
Here is the binary file: https://github.com/lanistor/assets/blob/master/lvgl/MAIN_30.bin.

Referer: https://github.com/lvgl/lv_font_conv/issues/126

### How to reproduce?
```bash
lv_font_conv \
  --font ./docs/fonts/assets/SourceHanSans-Min.ttf \
  -r 0x0000-0xffff \
  --size 14 --format bin --bpp 4 --no-compress \
  -o ./simulator/SDCARD/SYS/FONT/COMMON/MAIN_30.bin
```

```cpp
  lv_theme_default_init(lv_disp_get_default(), color_make(0x00),
                        color_make(0x80), false, &lv_font_main);

  lv_style_init(&fl_style_font);
  lv_style_set_text_font(&fl_style_font, &lv_font_main);

  lv_font_t* my_font =
    lv_font_load(LVGL_FS_ROOT "/SYS/FONT/COMMON/MAIN_30.bin");
  lv_style_set_text_font(&fl_style_font, my_font);
```

**Comment by lanistor** [comment]
@kisvegabor Could you help me see this issue?

**Comment by lanistor** [comment]
Finally, i use freetype vector fonts resolved it.

**Comment by kisvegabor** [comment]
Could you check if enabling `LV_FONT_FMT_TXT_LARGE` has any effect?

**Comment by lanistor** [comment]
> Could you check if enabling `LV_FONT_FMT_TXT_LARGE` has any effect?

It's defined to `LV_FONT_FMT_TXT_LARGE=1`
