### ISSUE TITLE
Focusing objects broken

### ISSUE THREAD

**Issue by Orange-Murker** [kisvegabor/lvgl#7237]
### LVGL version

master

### What happened?

On the latest master the blue outline that surrounds the focused object does not move correctly when another object is focused. Instead, only the corners of that outline are moved to the newly focused object.

Reverting 58e2d508e1c6ac9cb45da9566aef5d41776c0d29 fixes the issue.

**Comment by kisvegabor** [comment]
Hi,

It's resolved by https://github.com/lvgl/lvgl/pull/7264
