### ISSUE TITLE
lv_scale -- Suggested Refactor

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7285]
### Introduce the problem

cc:  @kisvegabor @C47D 

I would like to start with a compliment about `lv_scale_t`.  It's a nice model with its Sections and how nicely they dovetail with the drawing steps.

There are 3 issues with Scale that I have found:

1.  There are 2 field names in `_lv_scale_section_t` that are mis-named:

- `_lv_scale_section_t.minor_range` and
- `_lv_scale_section_t.major_range`

should really be called

- `_lv_scale_section_t.range_min` and
- `_lv_scale_section_t.range_max`

because their use is exclusively and only to compare against `_lv_scale_t.range_min` and `_lv_scale_t.range_max` respectively, and they have the *exact same semantics*.

Details:  More precisely stated, `Sections` make it possible for portions of a `Scale` to *convey meaning* by using different style properties to draw them (colors, line thicknesses, font, etc.).  A `Section` represents a sub-range of the `Scale`, whose styles (like cascading style sheets) take precedence while drawing the PARTS (lines, ticks and labels) of the `Scale` that are within the range of that `Section`.  *That is all these 2 values are used for is determining if the "scale value" of a PART being drawn (computed from `range_min` and `range_max`) is within the `min` and `max` value of the `Section`.*

To put it simply, `minor_range` and `major_range` are names that were chosen early by the original writer, and later, more appropriate names are found later, that more accurately reflect the meaning of their content.  (This is, of course, a common occurrence in software development, and is a classic case for refactoring by renaming fields of a custom data type.)

2.  The same structure uses 2 `uint32_t` values to store Boolean values.   They are:  `first_tick_idx_is_major` and `last_tick_idx_is_major`.  This is wasteful of RAM, and unless there is a future plan for them (not documented in the code), they could be reduced to single bits.  Thankfully these are also internal fields that will not break the API to change them.

3.  It is also worth considering that after a Section's creation using `lv_scale_add_section()`, it has a default range of [0..0], which *isn't neutral*.  I.e. a Tick at the 0-point on the Scale can be drawing using that Section's line-style properties.  So if, after creation, as Section is meant to be *neutral* (i.e. will not be drawn), a better approach would be to make the range [0..-1] so that that Section is guaranteed not to affect anything until a valid range has been assigned that at least overlaps part of the Scale's range, if it is not fully within it.

### Proposal

A.  Rename:

   - `_lv_scale_section_t.minor_range` => `range_min`, and
   - `_lv_scale_section_t.major_range` => `range_max`.

Thankfully, if `lv_scale_private.h` fulfills its role, this will not break the API.

Part of this refactoring also needs to include the formal argument names of the `lv_scale_section_set_range()` function (`minor_range` and `major_range`) to match those of `lv_scale_set_range()` (`min` and `max` for consistency) since their semantics are also identical.

B.  Change the type of `first_tick_idx_is_major` and `last_tick_idx_is_major` to single bits.

C.  If '3' above is a desirable trait, then setting
```
    section->major_range = -1;
```
at initialization time inside `lv_scale_add_section()` would be the change to implement it.  (As a note, these field are SIGNED, and they are currently being assigned UNSIGNED 0 values `0U` — doesn't make sense.)

**Comment by C47D** [comment]
Hi @vwheeler63 ,

Thanks for reading through the `lv_scale` mess, I agree with your observations and I would like to ask @kisvegabor if we can proceed with the updates, I'm not really aware of the release schedule.

**Comment by vwheeler63** [comment]
> mess

Please don't read this as "fault finding"!  I've developed several dozen components like this (for different environments) and can attest they go through idea phases and change.  This simply looks like part of its evolution to me.  👍  And my proposal here doesn't break the API, so if Gábor likes it, I would think we could do it immediately.

**Comment by kisvegabor** [comment]
Hey,

The rename and type change make perfect sense to me, however I'm a little bit hesitant about the default value. 
Usually we use a default value which is already visible. E.g. the default label text is `"Text"` instead of `""`. However, in this case an not visible section can make sense too, especially if it's documented in
- the docs
- and `lv_scale_add_section` API comments (e.g. `lv_scale_section_set range` needs to be called to set a valid range)

We ave plenty of time until v9.3 (2025 Q1), so it's not a concern.

**Comment by vwheeler63** [comment]
> The rename and type change make perfect sense to me, however....

Hi, Gábor!  

I'm glad you like the idea.  Default range of [0..0] can also make sense, since it doesn't have any styles added to it yet, it still won't be drawn.  So the existing initialization value does no harm and it cannot "accidentally" cause something to be drawn that was not intended.

When you say, "it's not a concern" -- does that mean it is okay to implement now?

Kind regards,
Vic

**Comment by C47D** [comment]
> Please don't read this as "fault finding"! I've developed several dozen components like this (for different environments) and can attest they go through idea phases and change. This simply looks like part of its evolution to me.

No worries, I see it as an evolution of the SW. I will start to work on this in the weekend, I'm in a tight schedule at work right now :smile:

**Comment by vwheeler63** [comment]
@C47D

If it helps, I can crank it out in about 5 minutes.

**Comment by vwheeler63** [comment]
@kisvegabor I found out something important!  Even with no styles set, the [0..0] range STILL causes it to be drawn, as it inherits the styles from the Scale!  It isn't visible, but the drawing *is being executed*!  So initial range [0..-1] is actually a *correct* way to initialize it since it eliminates that CPU overhead until the user has set it otherwise.

**Comment by C47D** [comment]
> @C47D
> 
> If it helps, I can crank it out in about 5 minutes.

Sure, you can take it 👍

**Comment by vwheeler63** [comment]
> Sure, you can take it

Okay!  I'm currently awaiting another PR to commit where `lv_scale` got involved (PR #7277), and will add these refactors afterwards.

**Comment by vwheeler63** [comment]
@kisvegabor @C47D  Note that I just added item `#D` in my proposal above -- I ran into it while I was clarifying the documentation in `lv_scale.h` -- when reading the documentation for those items made no sense to me.  So I clarified it by seeing how they were used in the C code and updated the documentation accordingly to be crisply clear about what those functions (and struct member) do.

**Comment by kisvegabor** [comment]
> rename member field `angle_range` => `needle_max_angle`  (which is what it actually is)

I don't think it's a good idea. The needle is optional for the scale. So we should describe the scale in general, and if there is a needle it can use these values. 

Am I missing something?

**Comment by vwheeler63** [comment]
> > rename member field `angle_range` => `needle_max_angle`  (which is what it actually is)
> 
> I don't think it's a good idea. The needle is optional for the scale. So we should describe the scale in general, and if there is a needle it can use these values.
> 
> Am I missing something?

You are actually correct!  I discovered in the process of updating the documentation that the name "angle_range" is actually correct, but it was not well documented.  It is now well documented in my PR, and I did not change the names.  I will remove "D" from the above because it was not valid.
