### ISSUE TITLE
Code error lv_font_montserrat_46

### ISSUE THREAD

**Issue by aasaleh024** [kisvegabor/lvgl#7287]
### Introduce the problem

c:184:49: error: 'lv_font_montserrat_46' undeclared (first use in this function); did you mean 'lv_font_montserrat_32'?
 lv_obj_set_style_text_font(ui_First50_Screen4, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
 
 this is the error im getting , i tried to fix it in my LVGL library i did not find lv_conf.h all i a have is lv_conf_template.h 
 went in the code and switched 0 to 1 still not working

**Comment by keerthansys22** [comment]
In lv_conf.h, search for **"#define LV_FONT_MONTSERRAT_46 0"** and enable this to 1 to use this font.

**Comment by keerthansys22** [comment]
Hi @aasaleh024, I guess you are missing this part - https://docs.lvgl.io/master/intro/add-lvgl-to-your-project/configuration.html#lv-conf-h

Once you follow link to create lv_conf.h and do the changes as I have mentioned above it should work. Let us know the outcome.
