### ISSUE TITLE
Minor Maintenance Issue in `lv_draw_label.c`

### ISSUE THREAD

**Issue by vwheeler63** [kisvegabor/lvgl#7288]
### LVGL version

v9.3

### What happened?

In `lv_draw_label_dsc_init()`, the `sel_start` and `sel_end` fields of `lv_draw_label_dsc_t` are initialized with `LV_DRAW_LABEL_NO_TXT_SEL` (which is a macro that equates to `(0xFFFF)`).  However, later in `lv_draw_label_iterate_characters()` (currently on line 419) these values (now copied to local variables) are compared to hard-coded 0xFFFF instead of `LV_DRAW_LABEL_NO_TXT_SEL`.  I suspect this was overlooked when `LV_DRAW_LABEL_NO_TXT_SEL` was implemented.

Suggested handling:  Change hard coded values to `LV_DRAW_LABEL_NO_TXT_SEL`.

### How to reproduce?

n/a

**Comment by kisvegabor** [comment]
Makes sense! Please send a PR.
