### ISSUE TITLE
Missing subpixel rendering in lv_conf.h

### ISSUE THREAD

**Issue by keerthansys22** [kisvegabor/lvgl#7291]
### LVGL version

v9.2.2

### What happened?

I couldn't find the flag to enable the sub-pixel rendering in lv_conf.h of version 9.2.2.

/*Enable subpixel rendering*/
#define LV_USE_FONT_SUBPX 1

**Comment by kisvegabor** [comment]
Hi,

It was removed in v9 to
- maintain better compatibility with the features set of GPUs
- to keep the code simple (it seemed to use it was rarely used feature)

Did is significantly increase the font quality in your case?

**Comment by keerthansys22** [comment]
Thanks for your reply. 
Yes, there was a slight improvement in terms of the font quality for custom fonts.

**Comment by kisvegabor** [comment]
Thank you! I'll keep it in mind, and if there will be more request about we can consider implementing again in a was it fits better to GPUs too.

**Comment by keerthansys22** [comment]
Thank you :)
