### ISSUE TITLE
My project uses too much flash memory

### ISSUE THREAD

**Issue by QUOCTHAI8901** [kisvegabor/lvgl#7300]
### LVGL version

v9.3.0

### What happened?

I use Renesas RA6M1 microcontroller.I have disabled most of the components, just enabled label in lv_conf.h
The project used 180kb flash memory.
Is there any way to reduce it? I tried following the image below but it didn't work
![image](https://github.com/user-attachments/assets/f7135852-8ff4-47e6-bc94-e754bd65730e)

**Comment by QUOCTHAI8901** [comment]
update: version is v9.2.2

**Comment by kisvegabor** [comment]
Can you send the `elf` file of you app?
