### ISSUE TITLE
Draw buf size

### ISSUE THREAD

**Issue by cosmindanielradu19** [kisvegabor/lvgl#7305]
### LVGL version

master

### What happened?

I'm trying to use LV_COLOR_DEPTH 1, but I encounter a problem when the draw buffer is allocated.
[Here](https://github.com/lvgl/lvgl/blob/master/src/draw/lv_draw_buf.c#L346), in `lv_draw_buf_reshape`, `_calculate_draw_buf_size` is called.
Inside [`_calculate_draw_buf_size`](https://github.com/lvgl/lvgl/blob/master/src/draw/lv_draw_buf.c#L657), at the size of the buffer, it's also added the size of the indexed palette. 

In our test case, we have a 720x1280 display, the stride is 736, so the frame buffer will have size = 942.080.
Because of that indexed palette addition, the calculated buf size will be 942.088, so it will not fit.

Shouldn't the indexed palette be present only on source buffer? Is this necessary to have it also on destination buffer? 

### How to reproduce?

```c
#define LV_COLOR_DEPTH 1
```

**Comment by kisvegabor** [comment]
> In our test case, we have a 720x1280 display, the stride is 736,

It seems like 1 byte per pixel. With I1 shouldn't the stride be like 720 / 8 = 90 bytes?

> Shouldn't the indexed palette be present only on source buffer? Is this necessary to have it also on destination buffer?

We don't differentiate between source and destination buffers. That is the draw buffers don't know if they belong to the display, or they are images, or they are layers. In case of canvases when you render to them they are destination buffers, bur when you are rendering their images, they are source buffers.

So for consistency the palette is always added.
