### ISSUE TITLE
PRESSED event repeated when some widget goes from not DISABLED to DISABLED state

### ISSUE THREAD

**Issue by mvladic** [kisvegabor/lvgl#7327]
### LVGL version

v9.3.0 dev

### Platform

Visual Studio, Emscripten

### What happened?

I have a button and a label. When I receive PRESSED event for the button and in the event handler if I change label state from not DISABLED to DISABLED I will receive another PRESSED event for this button!? 

If I use CLICKED event instead of PRESSED I will not receive two CLICKED events, so this problem occurs only for the PRESSED event.

Also, if I postpone changing label state to DISABLED after RELEASED event is sent for the button then it will not send second PRESSED event.

If I disable this line:

![image](https://github.com/user-attachments/assets/fd551273-b159-4edb-927f-393c1bfa86d4)

I will not receive second PRESSED event. So, this `lv_indev_reset` is the culprit that the second PRESSED event was sent.

**Comment by kisvegabor** [comment]
I've tried with this code and it worked well for me. We have recently merged some related changes to master, so please make sure that you are using the last commit. 
  
```c
static void event_cb(lv_event_t * e)
{
    LV_LOG_USER("Pressed");

    static uint32_t cnt = 1;
    lv_obj_t * btn = lv_event_get_target(e);
    lv_obj_add_state(btn, LV_STATE_DISABLED);
}

void lv_example_event_11(void)
{
    lv_obj_t * btn = lv_button_create(lv_screen_active());
    lv_obj_set_size(btn, 100, 50);
    lv_obj_center(btn);
    lv_obj_add_event_cb(btn, event_cb, LV_EVENT_PRESSED, NULL);

    lv_obj_t * label = lv_label_create(btn);
    lv_label_set_text(label, "Click me!");
    lv_obj_center(label);
}
```

**Comment by mvladic** [comment]
Yes, you are right, with the latest master version this problem doesn't occur anymore! I will close this issue.

---
Just for the record, here is to code to reproduce this bug on previous versions:

```
static lv_obj_t * another_label;

static void disable_another_label(void *) {
    lv_obj_add_state(another_label, LV_STATE_DISABLED);
    LV_LOG_USER("Another label disabled");
}

static void event_cb(lv_event_t * e) {
    LV_LOG_USER("Pressed");
    lv_async_call(disable_another_label, lv_scr_act());
}

void lv_example_event_11(void) {
    // Create "Click me!" button
    lv_obj_t * btn = lv_button_create(lv_screen_active());
    lv_obj_set_size(btn, 100, 50);
    lv_obj_center(btn);
    lv_obj_add_event_cb(btn, event_cb, LV_EVENT_PRESSED, NULL);

    lv_obj_t * label = lv_label_create(btn);
    lv_label_set_text(label, "Click me!");
    lv_obj_center(label);

    // Create another label
    another_label = lv_label_create(lv_screen_active());
    lv_obj_set_pos(another_label, 0, 0);
    lv_obj_set_size(another_label, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_label_set_text(another_label, "Hello, world!");
    lv_obj_set_style_opa(another_label, 50, LV_PART_MAIN | LV_STATE_DISABLED);
}    
```

On v9.2.2 here is the LOG output where two PRESSED event can be seen:

![image](https://github.com/user-attachments/assets/d9555d7a-6d10-4b08-8fe8-fd37b711a7f3)

On master version there is only one PRESSED:

![image](https://github.com/user-attachments/assets/0142e457-e330-4edd-ae5b-077a27328b42)

**Comment by KyL0N** [comment]
@kisvegabor hello, if the button listen for ```LV_EVENT_KEY```, and KEY_PAD indev trigger this event, the KEY_PAD will send the key twice, the first is the real key, and the second is sent by pressing process

if turn the button into textarea, the problem will be clear
