### ISSUE TITLE
The disp_drv.physical_xxx does not work by using SDL2 (the flush_cb is sdl_display_flush() in the lv_driver lib)

### ISSUE THREAD

**Issue by Staok** [kisvegabor/lvgl#7330]
### LVGL version

8.3.11

### Platform

win64, PC

### What happened?

Using SDL2 (the flush_cb is sdl_display_flush() in the lv_driver lib)

In the sdl hal init():
...
lv_disp_draw_buf_init(draw buf: &disp buf, buf1: buf_1,buf2: buf_2,...);
...
disp_drv.hor_res = SDL_HOR_RES;
disp_drv.ver_res = SDL_VER_RES;
disp_drv.physical_hor_res = SDL_HOR_RES / 2;
disp_drv.physical_ver_res = SDL_VER_RES / 2;
...
lv_disp_t * disp = lv_disp_drv_register(driver: &disp_drv():
...

the display is is abnormal
for some reason, the screen display cannot show here. The screen display is divided into two upper halves display arranged on the left and right.

the sdl config in lv_drv_conf:
![image](https://github.com/user-attachments/assets/082c11ec-b9d7-4c4b-bc8a-98b964ec2470)

**Comment by kisvegabor** [comment]
I've just checked that and this part is really messy in v8's SDL driver. I can't see a good way to make it work without a whole rework. :slightly_frowning_face: 

By setting a smaller physical resolution would you like to just clip the screen?
