### ISSUE TITLE
Custom fonts with 8 Bpp is not visible 

### ISSUE THREAD

**Issue by keerthansys22** [kisvegabor/lvgl#7347]
### LVGL version

v9.2.2

### Platform

Custom board with Linux OS

### What happened?

I'm trying to convert my custom font using [LVGL font converter](https://lvgl.io/tools/fontconverter) and I tried with 4 bpp (bits-per-pixel) and the font is not clear and sharper.

So, I generated the fonts with higher bpp value i.e **8 bpp** but the fonts are not visible. Is there any option to be enabled in the configuration file?

My custom fonts are not super clear and sharper, I'm thinking of using compressed fonts, but the document suggests the compression is more effective with larger fonts and higher bpp. In my case, the **maximum font size is 10 pt**. Would you suggest me to go for compressed fonts? 

**With 4 bpp : -**

![shared image (2)](https://github.com/user-attachments/assets/8b8063da-24fc-4cc1-9a21-132a9f9cd9cc)

**With 8 bpp: -**

![shared image (3)](https://github.com/user-attachments/assets/ca26c623-c389-48e8-b833-a2b3b55f8632)

**Comment by liamHowatt** [comment]
Is the version you're on older or newer than 417415f (#7100)? It was added then (October 26).

**Comment by keerthansys22** [comment]
I'm on version V9.2.2, are you suggesting me to check with v9.3.0-dev ?

**Comment by liamHowatt** [comment]
> are you suggesting me to check with v9.3.0-dev ?

Yes

> Any suggestions to use compressed fonts for my use-case?

What for? See the docs: https://docs.lvgl.io/master/details/main-components/font.html#compressed-fonts

**Comment by keerthansys22** [comment]
Yes, its working in V9.3.0-dev, thanks.
