### ISSUE TITLE
Transparent background display issue

### ISSUE THREAD

**Issue by wu781521512** [kisvegabor/lvgl#7349]
### LVGL version

9.0

### Platform

linux

### What happened?

The effect I want to achieve is similar to Figure 1 to Figure 2
For example, in Figure 2, the alarm page is displayed during a call, with the upper part transparent
But the current effect is that Figure 1 has not been cleared, and Figure 1 and Figure 2 overlap and are displayed together
<img width="208" alt="1" src="https://github.com/user-attachments/assets/cd49cb80-3854-49b7-ba40-65556d572bab">
<img width="207" alt="2" src="https://github.com/user-attachments/assets/4b95af88-79f2-47bf-ac74-ac02e0be4b18">

My code implementation is similar to the following
Please help me see how to solve this problem. Thank you very much

### How to reproduce?

```C
auto pageRoot = lv_obj_create (NULL);
lv_obj_set_style_bg_opa(pageRoot, LV_OPA_0, 0 );
lv_obj_t* rootContainer = lv_obj_create(pageRoot);
lv_obj_set_size(rootContainer, LV_HOR_RES, LV_VER_RES);
lv_obj_set_style_bg_color(rootContainer, lv_color_black(), 0);
lv_obj_set_style_border_width(rootContainer, 0, 0);
lv_obj_set_style_radius(rootContainer, 0, 0);

// Trigger a certain condition
lv_obj_clean(pageRoot);
lv_obj_t* rootContainer = lv_obj_create(pageRoot);
lv_obj_set_size(rootContainer, LV_HOR_RES, lv_pct(50));
lv_obj_set_style_bg_color(rootContainer, lv_color_white(), 0);
lv_obj_align(rootContainer, LV_ALIGN_BOTTOM_LEFT, 0, 0);
```

**Comment by wu781521512** [comment]
lv_conf.h  Just set LV_COLOR_SCREEN_TRANSP

**Comment by kisvegabor** [comment]
In v9.0 there is no `LV_COLOR_SCREEN_TRANSP`.
