### ISSUE TITLE
Change the color of arrows of Overview of LVGL's Data Flow into more distinctive colors.

### ISSUE THREAD

**Issue by vishnu-illikkal** [kisvegabor/lvgl#7352]
### Introduce the problem

https://docs.lvgl.io/master/intro/basics.html
https://docs.lvgl.io/master/_images/intro_data_flow.png

Currently the color is like Green for Control flow and red for data flow

### Proposal

Change the color to Blue and Green something like that so we can easily understand.

**Comment by liamHowatt** [comment]
@vwheeler63 did you create this diagram a few weeks ago?

I think it looks ok but if you have the source and it's not too much to ask, could you change the green arrows to blue?

> Change the color to Blue and Green something like that so we can easily understand.

Do you mean blue and red? The background is green. Is the goal to make the arrows be a different color than the green background?

**Comment by vwheeler63** [comment]
> did you create this diagram a few weeks ago?
> 
> I think it looks ok but if you have the source and it's not too much to ask, could you change the green arrows to blue?

Yes, it's very quick to change those colors.  (There are plans to get the source under `draw.io` [which is XML I believe], but until then, no problem.)

**Comment by vwheeler63** [comment]
> @vwheeler63 There is a code based uml diagram creator known as plantuml It is more easier than draw io in most of the cases.

Thank you for the tip!  It is not I making the decisions about `draw.io`, but I pass along your tip!  It sounds and looks like a great diagramming tool!

cc:  @kisvegabor

**Comment by vwheeler63** [comment]
@vishnu-illikkal In case you didn't notice, there are a couple of pending questions above.  I'm not sure I understand exactly what the problem is.  Can you explain?

**Comment by vwheeler63** [comment]
> @vwheeler63 I only meant the colours for the arrows Currently both are similar. So it is difficult to identify. So just use any 2 colours that can be easily distinguished. The background colour looks fine. Also make the color of arrows distinguishable from the background also. So in essence 3 different easily distinguishable colours.

Hi!  I wish I could see it from your perspective, since they are easily distinguishable on my screen.  

Re "Currently both are similar." -- on my screen, one is set of arrows is dark green, and one is orange (same orange as on the LVGL Logo):

![image](https://github.com/user-attachments/assets/b6b80ee3-b2fa-4876-a05d-65408377d44d)

Is that what you are seeing?  I'm confused about what is similar about those 2 colors.

Or are you referring to the dark-green arrows on the light-green background being difficult to differentiate on your screen?

**Comment by vishnu-illikkal** [comment]
@vwheeler63 

for the next question this is the answer
Q : can you give me a color palate examples for the colors.

Here are some color palette examples that ensure accessibility and distinguishability for the arrows, considering color blindness and contrast issues:

### Palette Example 1: **Blue and Orange**
- **Flow of Control**: Blue (#1E90FF)
- **Flow of Data**: Orange (#FFA500)
- **Background**: Light Green (#90EE90)

This combination ensures a good contrast and is colorblind-friendly.

---

### Palette Example 2: **Purple and Yellow**
- **Flow of Control**: Purple (#800080)
- **Flow of Data**: Yellow (#FFD700)
- **Background**: Light Green (#8FBC8F)

This palette has high contrast and is easily distinguishable.

---

### Palette Example 3: **Cyan and Dark Red**
- **Flow of Control**: Cyan (#00CED1)
- **Flow of Data**: Dark Red (#8B0000)
- **Background**: Light Green (#98FB98)

Cyan and dark red provide excellent contrast and avoid red-green confusion.

---

### Palette Example 4: **Teal and Gold**
- **Flow of Control**: Teal (#008080)
- **Flow of Data**: Gold (#FFD700)
- **Background**: Light Green (#90EE90)

This combination uses warm and cool tones that stand out against each other.

---

### Palette Example 5: **Black and Orange**
- **Flow of Control**: Black (#000000)
- **Flow of Data**: Bright Orange (#FF8C00)
- **Background**: Light Green (#99FF99)

Using black as one of the arrow colors ensures very high contrast.

---

### Tips for Implementation:
- Test the color combination using an online **colorblind simulator** to ensure it works well for various types of color vision deficiencies.
- Ensure the chosen colors have a contrast ratio of at least 4.5:1 against the background for readability.
- Use tools like [[Contrast Checker](https://webaim.org/resources/contrastchecker/)](https://webaim.org/resources/contrastchecker/) to validate your choices.

**Comment by vishnu-illikkal** [comment]
@vwheeler63 
This is what i meant.

**Comment by vwheeler63** [comment]
> @vwheeler63 This is what i meant.

Wow, @vishnu-illikkal !!  Color-blindness accessibility issues is an area I have not studied yet, so this is *very* helpful!!  I cannot use black arrows since I don't want them to be confused with the parent-child relationship arrows in the Widget tree, but the other sets of choices are very welcome!  You will find the adjusted colors now submitted in PR #7409 .

cc:  @liamHowatt

**Comment by vishnu-illikkal** [comment]
@vwheeler63  Thanks, Glad the suggestions were helpful.

**Comment by vwheeler63** [comment]
Hi, @vishnu-illikkal !  If you didn't already catch it in PR #7409, your feedback on the results was requested.  We'd like to know -- given your training -- how the results look to you.

**Comment by vishnu-illikkal** [comment]
@vwheeler63  Yes i have seen that.
Of course i will be happy to assist in any way i can.
Also please note that I don't have any specific training on the colors and stuff, the current image was difficult to distinguish for myself, that's why i given this issue.

**Comment by vwheeler63** [comment]
> the current image was difficult to distinguish for myself

Ah!  Well, all the better -- the image is visible in the "Files changed" tab of PR #7409, if you haven't already seen it.  [This link](https://github.com/lvgl/lvgl/pull/7409/files) will take you right to it.

**Comment by vishnu-illikkal** [comment]
> > the current image was difficult to distinguish for myself
> 
> Ah! Well, all the better -- the image is visible in the "Files changed" tab of PR #7409, if you haven't already seen it. [This link](https://github.com/lvgl/lvgl/pull/7409/files) will take you right to it.

@vwheeler63 Thanks for the link, i haven't seen the changes before, i just saw the post.
