### ISSUE TITLE
Failed to build THORVG for lottie on esp-idf.

### ISSUE THREAD

**Issue by MR-VENOM** [kisvegabor/lvgl#7373]
### LVGL version

9.2.2

### Platform

ESP-IDF

### What happened?

Failing to build the project when THORVG is enabled.

```
In file included from /home/venom/disk/custom-esp32-examples/lvgl-lottie/managed_components/lvgl__lvgl/src/libs/thorvg/tvgSwRaster.cpp:238:
/home/venom/disk/custom-esp32-examples/lvgl-lottie/managed_components/lvgl__lvgl/src/libs/thorvg/tvgSwRasterTexmap.h: In function 'void _rasterPolygonImageSegment(SwSurface*, const SwImage*, const SwBBox*, int, int, AASpans*, uint8_t, bool)':
/home/venom/disk/custom-esp32-examples/lvgl-lottie/managed_components/lvgl__lvgl/src/libs/thorvg/tvgSwRasterTexmap.h:643:1: error: insn does not satisfy its constraints:
  643 | }
      | ^
(insn 1370 1164 1482 72 (set (reg:SF 21 f2 [752])
        (mem/u/c:SF (symbol_ref/u:SI ("*.LC46") [flags 0x2]) [0  S4 A32])) 58 {movsf_internal}
     (nil))
during RTL pass: postreload
/home/venom/disk/custom-esp32-examples/lvgl-lottie/managed_components/lvgl__lvgl/src/libs/thorvg/tvgSwRasterTexmap.h:643:1: internal compiler error: in extract_constrain_insn, at recog.cc:2692
0x79c572e29d8f __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x79c572e29e3f __libc_start_main_impl
        ../csu/libc-start.c:392
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
[63/356] Building C object esp-idf/lvgl__lvgl/CMakeFiles/__idf_lvgl__lvgl.dir/src/widgets/menu/lv_menu.c.obj
ninja: build stopped: subcommand failed.

 *  The terminal process "ninja" terminated with exit code: 1. 
```

**Comment by liamHowatt** [comment]
I reproduced it. I don't have an immediate solution. It's something to do with the way IDF handles certain C++. I tried using the latest `master` and the issue is gone but replaced by another problem.

I wonder if anyone has successfully compiled ThorVG on IDF with past versions or if it has always had issues.

**Comment by MR-VENOM** [comment]
> I reproduced it. I don't have an immediate solution. It's something to do with the way IDF handles certain C++. I tried using the latest `master` and the issue is gone but replaced by another problem.
> 
> I wonder if anyone has successfully compiled ThorVG on IDF with past versions or if it has always had issues.

@liamHowatt  I got an workaround from the guys over [ESP](https://github.com/espressif/esp-bsp/issues/445#issuecomment-2507749378) :

> Linking [jcmvbkbc/gcc-xtensa#14](https://github.com/jcmvbkbc/gcc-xtensa/issues/14) — adding `-fno-if-conversion` to compilation flags could help.
> 
> The issue will be finally fixed in toolchain based on GCC 14, which is used in IDF v5.4 or later.

And It works as intended. Need to do some more check to see anything else crashes

**Comment by liamHowatt** [comment]
Discussion continued here: #7402
